begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* LIBGIMP - The GIMP Library  * Copyright (C) 1995-2003 Peter Mattis and Spencer Kimball  *  * gimp_pdb_headers.h  *  * This library is free software: you can redistribute it and/or  * modify it under the terms of the GNU Lesser General Public  * License as published by the Free Software Foundation; either  * version 3 of the License, or (at your option) any later version.  *  * This library is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU  * Lesser General Public License for more details.  *  * You should have received a copy of the GNU Lesser General Public  * License along with this library.  If not, see  *<http://www.gnu.org/licenses/>.  */
end_comment

begin_comment
comment|/* NOTE: This file is auto-generated by pdbgen.pl */
end_comment

begin_ifndef
ifndef|#
directive|ifndef
name|__GIMP_PDB_HEADERS_H__
end_ifndef

begin_define
DECL|macro|__GIMP_PDB_HEADERS_H__
define|#
directive|define
name|__GIMP_PDB_HEADERS_H__
end_define

begin_include
include|#
directive|include
file|<libgimp/gimp_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpbrush_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpbrushes_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpbrushselect_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpbuffer_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpchannel_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpcolor_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpcontext_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpconvert_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpdisplay_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpdrawable_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpdrawabletransform_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpedit_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpfileops_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpfloatingsel_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpfonts_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpfontselect_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpgimprc_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpgradient_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpgradients_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpgradientselect_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpgrid_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpguides_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimphelp_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpimage_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpimageselect_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpitem_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpitemtransform_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimplayer_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpmessage_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimppainttools_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimppalette_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimppalettes_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimppaletteselect_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimppaths_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimppattern_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimppatterns_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimppatternselect_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpplugin_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpproceduraldb_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpprogress_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpselection_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpselectiontools_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimptextlayer_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimptexttool_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimptransformtools_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpundo_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpunit_pdb.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpvectors_pdb.h>
end_include

begin_endif
endif|#
directive|endif
end_endif

begin_comment
comment|/* __GIMP_PDB_HEADERS_H__ */
end_comment

end_unit

