begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* The GIMP -- an image manipulation program  * Copyright (C) 1995 Spencer Kimball and Peter Mattis  *  * This program is free software; you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 2 of the License, or  * (at your option) any later version.  *  * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *  * You should have received a copy of the GNU General Public License  * along with this program; if not, write to the Free Software  * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  */
end_comment

begin_include
include|#
directive|include
file|"config.h"
end_include

begin_include
include|#
directive|include
file|<string.h>
end_include

begin_include
include|#
directive|include
file|<gtk/gtk.h>
end_include

begin_include
include|#
directive|include
file|"libgimpwidgets/gimpwidgets.h"
end_include

begin_include
include|#
directive|include
file|"actions-types.h"
end_include

begin_include
include|#
directive|include
file|"core/gimp.h"
end_include

begin_include
include|#
directive|include
file|"core/gimpbrushgenerated.h"
end_include

begin_include
include|#
directive|include
file|"core/gimpcontext.h"
end_include

begin_include
include|#
directive|include
file|"core/gimpdatafactory.h"
end_include

begin_include
include|#
directive|include
file|"core/gimplist.h"
end_include

begin_include
include|#
directive|include
file|"core/gimptoolinfo.h"
end_include

begin_include
include|#
directive|include
file|"tools/gimpcoloroptions.h"
end_include

begin_include
include|#
directive|include
file|"actions.h"
end_include

begin_include
include|#
directive|include
file|"context-commands.h"
end_include

begin_decl_stmt
DECL|variable|paint_modes
specifier|static
specifier|const
name|GimpLayerModeEffects
name|paint_modes
index|[]
init|=
block|{
name|GIMP_NORMAL_MODE
block|,
name|GIMP_DISSOLVE_MODE
block|,
name|GIMP_BEHIND_MODE
block|,
name|GIMP_COLOR_ERASE_MODE
block|,
name|GIMP_MULTIPLY_MODE
block|,
name|GIMP_DIVIDE_MODE
block|,
name|GIMP_SCREEN_MODE
block|,
name|GIMP_OVERLAY_MODE
block|,
name|GIMP_DODGE_MODE
block|,
name|GIMP_BURN_MODE
block|,
name|GIMP_HARDLIGHT_MODE
block|,
name|GIMP_SOFTLIGHT_MODE
block|,
name|GIMP_GRAIN_EXTRACT_MODE
block|,
name|GIMP_GRAIN_MERGE_MODE
block|,
name|GIMP_DIFFERENCE_MODE
block|,
name|GIMP_ADDITION_MODE
block|,
name|GIMP_SUBTRACT_MODE
block|,
name|GIMP_DARKEN_ONLY_MODE
block|,
name|GIMP_LIGHTEN_ONLY_MODE
block|,
name|GIMP_HUE_MODE
block|,
name|GIMP_SATURATION_MODE
block|,
name|GIMP_COLOR_MODE
block|,
name|GIMP_VALUE_MODE
block|}
decl_stmt|;
end_decl_stmt

begin_comment
comment|/*  local function prototypes  */
end_comment

begin_function_decl
specifier|static
name|void
name|context_select_object
parameter_list|(
name|GimpActionSelectType
name|select_type
parameter_list|,
name|GimpContext
modifier|*
name|context
parameter_list|,
name|GimpContainer
modifier|*
name|container
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|gint
name|context_paint_mode_index
parameter_list|(
name|GimpLayerModeEffects
name|paint_mode
parameter_list|)
function_decl|;
end_function_decl

begin_comment
comment|/*  public functions  */
end_comment

begin_function
name|void
DECL|function|context_colors_default_cmd_callback (GtkAction * action,gpointer data)
name|context_colors_default_cmd_callback
parameter_list|(
name|GtkAction
modifier|*
name|action
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpContext
modifier|*
name|context
decl_stmt|;
name|return_if_no_context
argument_list|(
name|context
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|gimp_context_set_default_colors
argument_list|(
name|context
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|context_colors_swap_cmd_callback (GtkAction * action,gpointer data)
name|context_colors_swap_cmd_callback
parameter_list|(
name|GtkAction
modifier|*
name|action
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpContext
modifier|*
name|context
decl_stmt|;
name|return_if_no_context
argument_list|(
name|context
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|gimp_context_swap_colors
argument_list|(
name|context
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|context_foreground_red_cmd_callback (GtkAction * action,gint value,gpointer data)
name|context_foreground_red_cmd_callback
parameter_list|(
name|GtkAction
modifier|*
name|action
parameter_list|,
name|gint
name|value
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpContext
modifier|*
name|context
decl_stmt|;
name|GimpRGB
name|color
decl_stmt|;
name|return_if_no_context
argument_list|(
name|context
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|gimp_context_get_foreground
argument_list|(
name|context
argument_list|,
operator|&
name|color
argument_list|)
expr_stmt|;
name|color
operator|.
name|r
operator|=
name|action_select_value
argument_list|(
operator|(
name|GimpActionSelectType
operator|)
name|value
argument_list|,
name|color
operator|.
name|r
argument_list|,
literal|0.0
argument_list|,
literal|1.0
argument_list|,
literal|0.01
argument_list|,
literal|0.1
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gimp_context_set_foreground
argument_list|(
name|context
argument_list|,
operator|&
name|color
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|context_foreground_green_cmd_callback (GtkAction * action,gint value,gpointer data)
name|context_foreground_green_cmd_callback
parameter_list|(
name|GtkAction
modifier|*
name|action
parameter_list|,
name|gint
name|value
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpContext
modifier|*
name|context
decl_stmt|;
name|GimpRGB
name|color
decl_stmt|;
name|return_if_no_context
argument_list|(
name|context
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|gimp_context_get_foreground
argument_list|(
name|context
argument_list|,
operator|&
name|color
argument_list|)
expr_stmt|;
name|color
operator|.
name|g
operator|=
name|action_select_value
argument_list|(
operator|(
name|GimpActionSelectType
operator|)
name|value
argument_list|,
name|color
operator|.
name|g
argument_list|,
literal|0.0
argument_list|,
literal|1.0
argument_list|,
literal|0.01
argument_list|,
literal|0.1
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gimp_context_set_foreground
argument_list|(
name|context
argument_list|,
operator|&
name|color
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|context_foreground_blue_cmd_callback (GtkAction * action,gint value,gpointer data)
name|context_foreground_blue_cmd_callback
parameter_list|(
name|GtkAction
modifier|*
name|action
parameter_list|,
name|gint
name|value
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpContext
modifier|*
name|context
decl_stmt|;
name|GimpRGB
name|color
decl_stmt|;
name|return_if_no_context
argument_list|(
name|context
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|gimp_context_get_foreground
argument_list|(
name|context
argument_list|,
operator|&
name|color
argument_list|)
expr_stmt|;
name|color
operator|.
name|b
operator|=
name|action_select_value
argument_list|(
operator|(
name|GimpActionSelectType
operator|)
name|value
argument_list|,
name|color
operator|.
name|b
argument_list|,
literal|0.0
argument_list|,
literal|1.0
argument_list|,
literal|0.01
argument_list|,
literal|0.1
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gimp_context_set_foreground
argument_list|(
name|context
argument_list|,
operator|&
name|color
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|context_background_red_cmd_callback (GtkAction * action,gint value,gpointer data)
name|context_background_red_cmd_callback
parameter_list|(
name|GtkAction
modifier|*
name|action
parameter_list|,
name|gint
name|value
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpContext
modifier|*
name|context
decl_stmt|;
name|GimpRGB
name|color
decl_stmt|;
name|return_if_no_context
argument_list|(
name|context
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|gimp_context_get_background
argument_list|(
name|context
argument_list|,
operator|&
name|color
argument_list|)
expr_stmt|;
name|color
operator|.
name|r
operator|=
name|action_select_value
argument_list|(
operator|(
name|GimpActionSelectType
operator|)
name|value
argument_list|,
name|color
operator|.
name|r
argument_list|,
literal|0.0
argument_list|,
literal|1.0
argument_list|,
literal|0.01
argument_list|,
literal|0.1
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gimp_context_set_background
argument_list|(
name|context
argument_list|,
operator|&
name|color
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|context_background_green_cmd_callback (GtkAction * action,gint value,gpointer data)
name|context_background_green_cmd_callback
parameter_list|(
name|GtkAction
modifier|*
name|action
parameter_list|,
name|gint
name|value
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpContext
modifier|*
name|context
decl_stmt|;
name|GimpRGB
name|color
decl_stmt|;
name|return_if_no_context
argument_list|(
name|context
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|gimp_context_get_background
argument_list|(
name|context
argument_list|,
operator|&
name|color
argument_list|)
expr_stmt|;
name|color
operator|.
name|g
operator|=
name|action_select_value
argument_list|(
operator|(
name|GimpActionSelectType
operator|)
name|value
argument_list|,
name|color
operator|.
name|g
argument_list|,
literal|0.0
argument_list|,
literal|1.0
argument_list|,
literal|0.01
argument_list|,
literal|0.1
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gimp_context_set_background
argument_list|(
name|context
argument_list|,
operator|&
name|color
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|context_background_blue_cmd_callback (GtkAction * action,gint value,gpointer data)
name|context_background_blue_cmd_callback
parameter_list|(
name|GtkAction
modifier|*
name|action
parameter_list|,
name|gint
name|value
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpContext
modifier|*
name|context
decl_stmt|;
name|GimpRGB
name|color
decl_stmt|;
name|return_if_no_context
argument_list|(
name|context
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|gimp_context_get_background
argument_list|(
name|context
argument_list|,
operator|&
name|color
argument_list|)
expr_stmt|;
name|color
operator|.
name|b
operator|=
name|action_select_value
argument_list|(
operator|(
name|GimpActionSelectType
operator|)
name|value
argument_list|,
name|color
operator|.
name|b
argument_list|,
literal|0.0
argument_list|,
literal|1.0
argument_list|,
literal|0.01
argument_list|,
literal|0.1
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gimp_context_set_background
argument_list|(
name|context
argument_list|,
operator|&
name|color
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|context_opacity_cmd_callback (GtkAction * action,gint value,gpointer data)
name|context_opacity_cmd_callback
parameter_list|(
name|GtkAction
modifier|*
name|action
parameter_list|,
name|gint
name|value
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpContext
modifier|*
name|context
decl_stmt|;
name|gdouble
name|opacity
decl_stmt|;
name|return_if_no_context
argument_list|(
name|context
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|opacity
operator|=
name|action_select_value
argument_list|(
operator|(
name|GimpActionSelectType
operator|)
name|value
argument_list|,
name|gimp_context_get_opacity
argument_list|(
name|context
argument_list|)
argument_list|,
name|GIMP_OPACITY_TRANSPARENT
argument_list|,
name|GIMP_OPACITY_OPAQUE
argument_list|,
literal|0.01
argument_list|,
literal|0.1
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gimp_context_set_opacity
argument_list|(
name|context
argument_list|,
name|opacity
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|context_paint_mode_cmd_callback (GtkAction * action,gint value,gpointer data)
name|context_paint_mode_cmd_callback
parameter_list|(
name|GtkAction
modifier|*
name|action
parameter_list|,
name|gint
name|value
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpContext
modifier|*
name|context
decl_stmt|;
name|GimpLayerModeEffects
name|paint_mode
decl_stmt|;
name|gint
name|index
decl_stmt|;
name|return_if_no_context
argument_list|(
name|context
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|paint_mode
operator|=
name|gimp_context_get_paint_mode
argument_list|(
name|context
argument_list|)
expr_stmt|;
name|index
operator|=
name|action_select_value
argument_list|(
operator|(
name|GimpActionSelectType
operator|)
name|value
argument_list|,
name|context_paint_mode_index
argument_list|(
name|paint_mode
argument_list|)
argument_list|,
literal|0
argument_list|,
name|G_N_ELEMENTS
argument_list|(
name|paint_modes
argument_list|)
operator|-
literal|1
argument_list|,
literal|1.0
argument_list|,
literal|1.0
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gimp_context_set_paint_mode
argument_list|(
name|context
argument_list|,
name|paint_modes
index|[
name|index
index|]
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|context_tool_select_cmd_callback (GtkAction * action,gint value,gpointer data)
name|context_tool_select_cmd_callback
parameter_list|(
name|GtkAction
modifier|*
name|action
parameter_list|,
name|gint
name|value
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpContext
modifier|*
name|context
decl_stmt|;
name|return_if_no_context
argument_list|(
name|context
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|context_select_object
argument_list|(
operator|(
name|GimpActionSelectType
operator|)
name|value
argument_list|,
name|context
argument_list|,
name|context
operator|->
name|gimp
operator|->
name|tool_info_list
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|context_brush_select_cmd_callback (GtkAction * action,gint value,gpointer data)
name|context_brush_select_cmd_callback
parameter_list|(
name|GtkAction
modifier|*
name|action
parameter_list|,
name|gint
name|value
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpContext
modifier|*
name|context
decl_stmt|;
name|return_if_no_context
argument_list|(
name|context
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|context_select_object
argument_list|(
operator|(
name|GimpActionSelectType
operator|)
name|value
argument_list|,
name|context
argument_list|,
name|context
operator|->
name|gimp
operator|->
name|brush_factory
operator|->
name|container
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|context_pattern_select_cmd_callback (GtkAction * action,gint value,gpointer data)
name|context_pattern_select_cmd_callback
parameter_list|(
name|GtkAction
modifier|*
name|action
parameter_list|,
name|gint
name|value
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpContext
modifier|*
name|context
decl_stmt|;
name|return_if_no_context
argument_list|(
name|context
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|context_select_object
argument_list|(
operator|(
name|GimpActionSelectType
operator|)
name|value
argument_list|,
name|context
argument_list|,
name|context
operator|->
name|gimp
operator|->
name|pattern_factory
operator|->
name|container
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|context_palette_select_cmd_callback (GtkAction * action,gint value,gpointer data)
name|context_palette_select_cmd_callback
parameter_list|(
name|GtkAction
modifier|*
name|action
parameter_list|,
name|gint
name|value
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpContext
modifier|*
name|context
decl_stmt|;
name|return_if_no_context
argument_list|(
name|context
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|context_select_object
argument_list|(
operator|(
name|GimpActionSelectType
operator|)
name|value
argument_list|,
name|context
argument_list|,
name|context
operator|->
name|gimp
operator|->
name|palette_factory
operator|->
name|container
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|context_gradient_select_cmd_callback (GtkAction * action,gint value,gpointer data)
name|context_gradient_select_cmd_callback
parameter_list|(
name|GtkAction
modifier|*
name|action
parameter_list|,
name|gint
name|value
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpContext
modifier|*
name|context
decl_stmt|;
name|return_if_no_context
argument_list|(
name|context
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|context_select_object
argument_list|(
operator|(
name|GimpActionSelectType
operator|)
name|value
argument_list|,
name|context
argument_list|,
name|context
operator|->
name|gimp
operator|->
name|gradient_factory
operator|->
name|container
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|context_font_select_cmd_callback (GtkAction * action,gint value,gpointer data)
name|context_font_select_cmd_callback
parameter_list|(
name|GtkAction
modifier|*
name|action
parameter_list|,
name|gint
name|value
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpContext
modifier|*
name|context
decl_stmt|;
name|return_if_no_context
argument_list|(
name|context
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|context_select_object
argument_list|(
operator|(
name|GimpActionSelectType
operator|)
name|value
argument_list|,
name|context
argument_list|,
name|context
operator|->
name|gimp
operator|->
name|fonts
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|context_brush_shape_cmd_callback (GtkAction * action,gint value,gpointer data)
name|context_brush_shape_cmd_callback
parameter_list|(
name|GtkAction
modifier|*
name|action
parameter_list|,
name|gint
name|value
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpContext
modifier|*
name|context
decl_stmt|;
name|GimpBrush
modifier|*
name|brush
decl_stmt|;
name|return_if_no_context
argument_list|(
name|context
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|brush
operator|=
name|gimp_context_get_brush
argument_list|(
name|context
argument_list|)
expr_stmt|;
if|if
condition|(
name|GIMP_IS_BRUSH_GENERATED
argument_list|(
name|brush
argument_list|)
condition|)
block|{
name|GimpBrushGenerated
modifier|*
name|generated
init|=
name|GIMP_BRUSH_GENERATED
argument_list|(
name|brush
argument_list|)
decl_stmt|;
name|gimp_brush_generated_set_shape
argument_list|(
name|generated
argument_list|,
operator|(
name|GimpBrushGeneratedShape
operator|)
name|value
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
name|void
DECL|function|context_brush_radius_cmd_callback (GtkAction * action,gint value,gpointer data)
name|context_brush_radius_cmd_callback
parameter_list|(
name|GtkAction
modifier|*
name|action
parameter_list|,
name|gint
name|value
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpContext
modifier|*
name|context
decl_stmt|;
name|GimpBrush
modifier|*
name|brush
decl_stmt|;
name|return_if_no_context
argument_list|(
name|context
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|brush
operator|=
name|gimp_context_get_brush
argument_list|(
name|context
argument_list|)
expr_stmt|;
if|if
condition|(
name|GIMP_IS_BRUSH_GENERATED
argument_list|(
name|brush
argument_list|)
condition|)
block|{
name|GimpBrushGenerated
modifier|*
name|generated
init|=
name|GIMP_BRUSH_GENERATED
argument_list|(
name|brush
argument_list|)
decl_stmt|;
name|gdouble
name|radius
decl_stmt|;
name|radius
operator|=
name|gimp_brush_generated_get_radius
argument_list|(
name|generated
argument_list|)
expr_stmt|;
name|radius
operator|=
name|action_select_value
argument_list|(
operator|(
name|GimpActionSelectType
operator|)
name|value
argument_list|,
name|radius
argument_list|,
literal|1.0
argument_list|,
literal|256.0
argument_list|,
literal|1.0
argument_list|,
literal|10.0
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gimp_brush_generated_set_radius
argument_list|(
name|generated
argument_list|,
name|radius
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
name|void
DECL|function|context_brush_spikes_cmd_callback (GtkAction * action,gint value,gpointer data)
name|context_brush_spikes_cmd_callback
parameter_list|(
name|GtkAction
modifier|*
name|action
parameter_list|,
name|gint
name|value
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpContext
modifier|*
name|context
decl_stmt|;
name|GimpBrush
modifier|*
name|brush
decl_stmt|;
name|return_if_no_context
argument_list|(
name|context
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|brush
operator|=
name|gimp_context_get_brush
argument_list|(
name|context
argument_list|)
expr_stmt|;
if|if
condition|(
name|GIMP_IS_BRUSH_GENERATED
argument_list|(
name|brush
argument_list|)
condition|)
block|{
name|GimpBrushGenerated
modifier|*
name|generated
init|=
name|GIMP_BRUSH_GENERATED
argument_list|(
name|brush
argument_list|)
decl_stmt|;
name|gint
name|spikes
decl_stmt|;
name|spikes
operator|=
name|gimp_brush_generated_get_spikes
argument_list|(
name|generated
argument_list|)
expr_stmt|;
name|spikes
operator|=
name|action_select_value
argument_list|(
operator|(
name|GimpActionSelectType
operator|)
name|value
argument_list|,
name|spikes
argument_list|,
literal|2.0
argument_list|,
literal|20.0
argument_list|,
literal|1.0
argument_list|,
literal|4.0
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gimp_brush_generated_set_spikes
argument_list|(
name|generated
argument_list|,
name|spikes
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
name|void
DECL|function|context_brush_hardness_cmd_callback (GtkAction * action,gint value,gpointer data)
name|context_brush_hardness_cmd_callback
parameter_list|(
name|GtkAction
modifier|*
name|action
parameter_list|,
name|gint
name|value
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpContext
modifier|*
name|context
decl_stmt|;
name|GimpBrush
modifier|*
name|brush
decl_stmt|;
name|return_if_no_context
argument_list|(
name|context
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|brush
operator|=
name|gimp_context_get_brush
argument_list|(
name|context
argument_list|)
expr_stmt|;
if|if
condition|(
name|GIMP_IS_BRUSH_GENERATED
argument_list|(
name|brush
argument_list|)
condition|)
block|{
name|GimpBrushGenerated
modifier|*
name|generated
init|=
name|GIMP_BRUSH_GENERATED
argument_list|(
name|brush
argument_list|)
decl_stmt|;
name|gdouble
name|hardness
decl_stmt|;
name|hardness
operator|=
name|gimp_brush_generated_get_hardness
argument_list|(
name|generated
argument_list|)
expr_stmt|;
name|hardness
operator|=
name|action_select_value
argument_list|(
operator|(
name|GimpActionSelectType
operator|)
name|value
argument_list|,
name|hardness
argument_list|,
literal|0.0
argument_list|,
literal|1.0
argument_list|,
literal|0.01
argument_list|,
literal|0.1
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gimp_brush_generated_set_hardness
argument_list|(
name|generated
argument_list|,
name|hardness
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
name|void
DECL|function|context_brush_aspect_cmd_callback (GtkAction * action,gint value,gpointer data)
name|context_brush_aspect_cmd_callback
parameter_list|(
name|GtkAction
modifier|*
name|action
parameter_list|,
name|gint
name|value
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpContext
modifier|*
name|context
decl_stmt|;
name|GimpBrush
modifier|*
name|brush
decl_stmt|;
name|return_if_no_context
argument_list|(
name|context
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|brush
operator|=
name|gimp_context_get_brush
argument_list|(
name|context
argument_list|)
expr_stmt|;
if|if
condition|(
name|GIMP_IS_BRUSH_GENERATED
argument_list|(
name|brush
argument_list|)
condition|)
block|{
name|GimpBrushGenerated
modifier|*
name|generated
init|=
name|GIMP_BRUSH_GENERATED
argument_list|(
name|brush
argument_list|)
decl_stmt|;
name|gdouble
name|aspect
decl_stmt|;
name|aspect
operator|=
name|gimp_brush_generated_get_aspect_ratio
argument_list|(
name|generated
argument_list|)
expr_stmt|;
name|aspect
operator|=
name|action_select_value
argument_list|(
operator|(
name|GimpActionSelectType
operator|)
name|value
argument_list|,
name|aspect
argument_list|,
literal|1.0
argument_list|,
literal|20.0
argument_list|,
literal|1.0
argument_list|,
literal|4.0
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gimp_brush_generated_set_aspect_ratio
argument_list|(
name|generated
argument_list|,
name|aspect
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
name|void
DECL|function|context_brush_angle_cmd_callback (GtkAction * action,gint value,gpointer data)
name|context_brush_angle_cmd_callback
parameter_list|(
name|GtkAction
modifier|*
name|action
parameter_list|,
name|gint
name|value
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpContext
modifier|*
name|context
decl_stmt|;
name|GimpBrush
modifier|*
name|brush
decl_stmt|;
name|return_if_no_context
argument_list|(
name|context
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|brush
operator|=
name|gimp_context_get_brush
argument_list|(
name|context
argument_list|)
expr_stmt|;
if|if
condition|(
name|GIMP_IS_BRUSH_GENERATED
argument_list|(
name|brush
argument_list|)
condition|)
block|{
name|GimpBrushGenerated
modifier|*
name|generated
init|=
name|GIMP_BRUSH_GENERATED
argument_list|(
name|brush
argument_list|)
decl_stmt|;
name|gdouble
name|angle
decl_stmt|;
name|angle
operator|=
name|gimp_brush_generated_get_angle
argument_list|(
name|generated
argument_list|)
expr_stmt|;
if|if
condition|(
name|value
operator|==
name|GIMP_ACTION_SELECT_FIRST
condition|)
name|angle
operator|=
literal|0.0
expr_stmt|;
elseif|else
if|if
condition|(
name|value
operator|==
name|GIMP_ACTION_SELECT_LAST
condition|)
name|angle
operator|=
literal|90.0
expr_stmt|;
else|else
name|angle
operator|=
name|action_select_value
argument_list|(
operator|(
name|GimpActionSelectType
operator|)
name|value
argument_list|,
name|angle
argument_list|,
literal|0.0
argument_list|,
literal|180.0
argument_list|,
literal|1.0
argument_list|,
literal|15.0
argument_list|,
name|TRUE
argument_list|)
expr_stmt|;
name|gimp_brush_generated_set_angle
argument_list|(
name|generated
argument_list|,
name|angle
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
name|void
DECL|function|context_color_tool_average_radius_cmd_callback (GtkAction * action,gint value,gpointer data)
name|context_color_tool_average_radius_cmd_callback
parameter_list|(
name|GtkAction
modifier|*
name|action
parameter_list|,
name|gint
name|value
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpContext
modifier|*
name|context
decl_stmt|;
name|GimpToolInfo
modifier|*
name|tool_info
decl_stmt|;
name|return_if_no_context
argument_list|(
name|context
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|tool_info
operator|=
name|gimp_context_get_tool
argument_list|(
name|context
argument_list|)
expr_stmt|;
if|if
condition|(
name|tool_info
operator|&&
name|GIMP_IS_COLOR_OPTIONS
argument_list|(
name|tool_info
operator|->
name|tool_options
argument_list|)
condition|)
block|{
name|GimpToolOptions
modifier|*
name|options
init|=
name|tool_info
operator|->
name|tool_options
decl_stmt|;
name|GParamSpec
modifier|*
name|pspec
decl_stmt|;
name|gdouble
name|radius
decl_stmt|;
name|g_object_get
argument_list|(
name|options
argument_list|,
literal|"average-radius"
argument_list|,
operator|&
name|radius
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|pspec
operator|=
name|g_object_class_find_property
argument_list|(
name|G_OBJECT_GET_CLASS
argument_list|(
name|options
argument_list|)
argument_list|,
literal|"average-radius"
argument_list|)
expr_stmt|;
name|radius
operator|=
name|action_select_value
argument_list|(
operator|(
name|GimpActionSelectType
operator|)
name|value
argument_list|,
name|radius
argument_list|,
name|G_PARAM_SPEC_DOUBLE
argument_list|(
name|pspec
argument_list|)
operator|->
name|minimum
argument_list|,
name|G_PARAM_SPEC_DOUBLE
argument_list|(
name|pspec
argument_list|)
operator|->
name|maximum
argument_list|,
literal|1.0
argument_list|,
literal|10.0
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|g_object_set
argument_list|(
name|options
argument_list|,
literal|"average-radius"
argument_list|,
name|radius
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_comment
comment|/*  private functions  */
end_comment

begin_function
specifier|static
name|void
DECL|function|context_select_object (GimpActionSelectType select_type,GimpContext * context,GimpContainer * container)
name|context_select_object
parameter_list|(
name|GimpActionSelectType
name|select_type
parameter_list|,
name|GimpContext
modifier|*
name|context
parameter_list|,
name|GimpContainer
modifier|*
name|container
parameter_list|)
block|{
name|GimpObject
modifier|*
name|current
decl_stmt|;
name|current
operator|=
name|gimp_context_get_by_type
argument_list|(
name|context
argument_list|,
name|container
operator|->
name|children_type
argument_list|)
expr_stmt|;
name|current
operator|=
name|action_select_object
argument_list|(
name|select_type
argument_list|,
name|container
argument_list|,
name|current
argument_list|)
expr_stmt|;
if|if
condition|(
name|current
condition|)
name|gimp_context_set_by_type
argument_list|(
name|context
argument_list|,
name|container
operator|->
name|children_type
argument_list|,
name|current
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|gint
DECL|function|context_paint_mode_index (GimpLayerModeEffects paint_mode)
name|context_paint_mode_index
parameter_list|(
name|GimpLayerModeEffects
name|paint_mode
parameter_list|)
block|{
name|gint
name|i
init|=
literal|0
decl_stmt|;
while|while
condition|(
name|i
operator|<
operator|(
name|G_N_ELEMENTS
argument_list|(
name|paint_modes
argument_list|)
operator|-
literal|1
operator|)
operator|&&
name|paint_modes
index|[
name|i
index|]
operator|!=
name|paint_mode
condition|)
name|i
operator|++
expr_stmt|;
return|return
name|i
return|;
block|}
end_function

end_unit

