begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* Generated data (by gimp-mkenums) */
end_comment

begin_include
include|#
directive|include
file|"config.h"
end_include

begin_include
include|#
directive|include
file|<gio/gio.h>
end_include

begin_include
include|#
directive|include
file|"libgimpbase/gimpbase.h"
end_include

begin_include
include|#
directive|include
file|"plug-in-enums.h"
end_include

begin_include
include|#
directive|include
file|"gimp-intl.h"
end_include

begin_comment
comment|/* enumerations from "./plug-in-enums.h" */
end_comment

begin_function
name|GType
DECL|function|gimp_plug_in_image_type_get_type (void)
name|gimp_plug_in_image_type_get_type
parameter_list|(
name|void
parameter_list|)
block|{
specifier|static
specifier|const
name|GFlagsValue
name|values
index|[]
init|=
block|{
block|{
name|GIMP_PLUG_IN_RGB_IMAGE
block|,
literal|"GIMP_PLUG_IN_RGB_IMAGE"
block|,
literal|"rgb-image"
block|}
block|,
block|{
name|GIMP_PLUG_IN_GRAY_IMAGE
block|,
literal|"GIMP_PLUG_IN_GRAY_IMAGE"
block|,
literal|"gray-image"
block|}
block|,
block|{
name|GIMP_PLUG_IN_INDEXED_IMAGE
block|,
literal|"GIMP_PLUG_IN_INDEXED_IMAGE"
block|,
literal|"indexed-image"
block|}
block|,
block|{
name|GIMP_PLUG_IN_RGBA_IMAGE
block|,
literal|"GIMP_PLUG_IN_RGBA_IMAGE"
block|,
literal|"rgba-image"
block|}
block|,
block|{
name|GIMP_PLUG_IN_GRAYA_IMAGE
block|,
literal|"GIMP_PLUG_IN_GRAYA_IMAGE"
block|,
literal|"graya-image"
block|}
block|,
block|{
name|GIMP_PLUG_IN_INDEXEDA_IMAGE
block|,
literal|"GIMP_PLUG_IN_INDEXEDA_IMAGE"
block|,
literal|"indexeda-image"
block|}
block|,
block|{
literal|0
block|,
name|NULL
block|,
name|NULL
block|}
block|}
decl_stmt|;
specifier|static
specifier|const
name|GimpFlagsDesc
name|descs
index|[]
init|=
block|{
block|{
name|GIMP_PLUG_IN_RGB_IMAGE
block|,
literal|"GIMP_PLUG_IN_RGB_IMAGE"
block|,
name|NULL
block|}
block|,
block|{
name|GIMP_PLUG_IN_GRAY_IMAGE
block|,
literal|"GIMP_PLUG_IN_GRAY_IMAGE"
block|,
name|NULL
block|}
block|,
block|{
name|GIMP_PLUG_IN_INDEXED_IMAGE
block|,
literal|"GIMP_PLUG_IN_INDEXED_IMAGE"
block|,
name|NULL
block|}
block|,
block|{
name|GIMP_PLUG_IN_RGBA_IMAGE
block|,
literal|"GIMP_PLUG_IN_RGBA_IMAGE"
block|,
name|NULL
block|}
block|,
block|{
name|GIMP_PLUG_IN_GRAYA_IMAGE
block|,
literal|"GIMP_PLUG_IN_GRAYA_IMAGE"
block|,
name|NULL
block|}
block|,
block|{
name|GIMP_PLUG_IN_INDEXEDA_IMAGE
block|,
literal|"GIMP_PLUG_IN_INDEXEDA_IMAGE"
block|,
name|NULL
block|}
block|,
block|{
literal|0
block|,
name|NULL
block|,
name|NULL
block|}
block|}
decl_stmt|;
specifier|static
name|GType
name|type
init|=
literal|0
decl_stmt|;
if|if
condition|(
name|G_UNLIKELY
argument_list|(
operator|!
name|type
argument_list|)
condition|)
block|{
name|type
operator|=
name|g_flags_register_static
argument_list|(
literal|"GimpPlugInImageType"
argument_list|,
name|values
argument_list|)
expr_stmt|;
name|gimp_type_set_translation_context
argument_list|(
name|type
argument_list|,
literal|"plug-in-image-type"
argument_list|)
expr_stmt|;
name|gimp_flags_set_value_descriptions
argument_list|(
name|type
argument_list|,
name|descs
argument_list|)
expr_stmt|;
block|}
return|return
name|type
return|;
block|}
end_function

begin_function
name|GType
DECL|function|gimp_plug_in_call_mode_get_type (void)
name|gimp_plug_in_call_mode_get_type
parameter_list|(
name|void
parameter_list|)
block|{
specifier|static
specifier|const
name|GEnumValue
name|values
index|[]
init|=
block|{
block|{
name|GIMP_PLUG_IN_CALL_NONE
block|,
literal|"GIMP_PLUG_IN_CALL_NONE"
block|,
literal|"none"
block|}
block|,
block|{
name|GIMP_PLUG_IN_CALL_RUN
block|,
literal|"GIMP_PLUG_IN_CALL_RUN"
block|,
literal|"run"
block|}
block|,
block|{
name|GIMP_PLUG_IN_CALL_QUERY
block|,
literal|"GIMP_PLUG_IN_CALL_QUERY"
block|,
literal|"query"
block|}
block|,
block|{
name|GIMP_PLUG_IN_CALL_INIT
block|,
literal|"GIMP_PLUG_IN_CALL_INIT"
block|,
literal|"init"
block|}
block|,
block|{
literal|0
block|,
name|NULL
block|,
name|NULL
block|}
block|}
decl_stmt|;
specifier|static
specifier|const
name|GimpEnumDesc
name|descs
index|[]
init|=
block|{
block|{
name|GIMP_PLUG_IN_CALL_NONE
block|,
literal|"GIMP_PLUG_IN_CALL_NONE"
block|,
name|NULL
block|}
block|,
block|{
name|GIMP_PLUG_IN_CALL_RUN
block|,
literal|"GIMP_PLUG_IN_CALL_RUN"
block|,
name|NULL
block|}
block|,
block|{
name|GIMP_PLUG_IN_CALL_QUERY
block|,
literal|"GIMP_PLUG_IN_CALL_QUERY"
block|,
name|NULL
block|}
block|,
block|{
name|GIMP_PLUG_IN_CALL_INIT
block|,
literal|"GIMP_PLUG_IN_CALL_INIT"
block|,
name|NULL
block|}
block|,
block|{
literal|0
block|,
name|NULL
block|,
name|NULL
block|}
block|}
decl_stmt|;
specifier|static
name|GType
name|type
init|=
literal|0
decl_stmt|;
if|if
condition|(
name|G_UNLIKELY
argument_list|(
operator|!
name|type
argument_list|)
condition|)
block|{
name|type
operator|=
name|g_enum_register_static
argument_list|(
literal|"GimpPlugInCallMode"
argument_list|,
name|values
argument_list|)
expr_stmt|;
name|gimp_type_set_translation_context
argument_list|(
name|type
argument_list|,
literal|"plug-in-call-mode"
argument_list|)
expr_stmt|;
name|gimp_enum_set_value_descriptions
argument_list|(
name|type
argument_list|,
name|descs
argument_list|)
expr_stmt|;
block|}
return|return
name|type
return|;
block|}
end_function

begin_function
name|GType
DECL|function|gimp_file_procedure_group_get_type (void)
name|gimp_file_procedure_group_get_type
parameter_list|(
name|void
parameter_list|)
block|{
specifier|static
specifier|const
name|GEnumValue
name|values
index|[]
init|=
block|{
block|{
name|GIMP_FILE_PROCEDURE_GROUP_ANY
block|,
literal|"GIMP_FILE_PROCEDURE_GROUP_ANY"
block|,
literal|"any"
block|}
block|,
block|{
name|GIMP_FILE_PROCEDURE_GROUP_OPEN
block|,
literal|"GIMP_FILE_PROCEDURE_GROUP_OPEN"
block|,
literal|"open"
block|}
block|,
block|{
name|GIMP_FILE_PROCEDURE_GROUP_SAVE
block|,
literal|"GIMP_FILE_PROCEDURE_GROUP_SAVE"
block|,
literal|"save"
block|}
block|,
block|{
name|GIMP_FILE_PROCEDURE_GROUP_EXPORT
block|,
literal|"GIMP_FILE_PROCEDURE_GROUP_EXPORT"
block|,
literal|"export"
block|}
block|,
block|{
literal|0
block|,
name|NULL
block|,
name|NULL
block|}
block|}
decl_stmt|;
specifier|static
specifier|const
name|GimpEnumDesc
name|descs
index|[]
init|=
block|{
block|{
name|GIMP_FILE_PROCEDURE_GROUP_ANY
block|,
literal|"GIMP_FILE_PROCEDURE_GROUP_ANY"
block|,
name|NULL
block|}
block|,
block|{
name|GIMP_FILE_PROCEDURE_GROUP_OPEN
block|,
literal|"GIMP_FILE_PROCEDURE_GROUP_OPEN"
block|,
name|NULL
block|}
block|,
block|{
name|GIMP_FILE_PROCEDURE_GROUP_SAVE
block|,
literal|"GIMP_FILE_PROCEDURE_GROUP_SAVE"
block|,
name|NULL
block|}
block|,
block|{
name|GIMP_FILE_PROCEDURE_GROUP_EXPORT
block|,
literal|"GIMP_FILE_PROCEDURE_GROUP_EXPORT"
block|,
name|NULL
block|}
block|,
block|{
literal|0
block|,
name|NULL
block|,
name|NULL
block|}
block|}
decl_stmt|;
specifier|static
name|GType
name|type
init|=
literal|0
decl_stmt|;
if|if
condition|(
name|G_UNLIKELY
argument_list|(
operator|!
name|type
argument_list|)
condition|)
block|{
name|type
operator|=
name|g_enum_register_static
argument_list|(
literal|"GimpFileProcedureGroup"
argument_list|,
name|values
argument_list|)
expr_stmt|;
name|gimp_type_set_translation_context
argument_list|(
name|type
argument_list|,
literal|"file-procedure-group"
argument_list|)
expr_stmt|;
name|gimp_enum_set_value_descriptions
argument_list|(
name|type
argument_list|,
name|descs
argument_list|)
expr_stmt|;
block|}
return|return
name|type
return|;
block|}
end_function

begin_comment
comment|/* Generated data ends here */
end_comment

end_unit

