begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* LIBGIMP - The GIMP Library  * Copyright (C) 1995-1999 Peter Mattis and Spencer Kimball  *  * gimpwidgets.c  * Copyright (C) 2000 Michael Natterer<mitch@gimp.org>  *  * This library is free software; you can redistribute it and/or  * modify it under the terms of the GNU Lesser General Public  * License as published by the Free Software Foundation; either  * version 2 of the License, or (at your option) any later version.  *  * This library is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU  * Library General Public License for more details.  *  * You should have received a copy of the GNU Lesser General Public  * License along with this library; if not, write to the  * Free Software Foundation, Inc., 59 Temple Place - Suite 330,  * Boston, MA 02111-1307, USA.  */
end_comment

begin_include
include|#
directive|include
file|"config.h"
end_include

begin_include
include|#
directive|include
file|<gtk/gtk.h>
end_include

begin_include
include|#
directive|include
file|"gimpchainbutton.h"
end_include

begin_include
include|#
directive|include
file|"gimphelpui.h"
end_include

begin_include
include|#
directive|include
file|"gimppixmap.h"
end_include

begin_include
include|#
directive|include
file|"gimpunitmenu.h"
end_include

begin_include
include|#
directive|include
file|"gimpwidgets.h"
end_include

begin_include
include|#
directive|include
file|"gimpmath.h"
end_include

begin_include
include|#
directive|include
file|"libgimp-intl.h"
end_include

begin_comment
comment|/*  *  Widget Constructors  */
end_comment

begin_comment
comment|/**  * gimp_option_menu_new:  * @menu_only: #TRUE if the function should return a #GtkMenu only.  * @...: A #NULL terminated @va_list describing the menu items.  *  * Returns: A #GtkOptionMenu or a #GtkMenu (depending on @menu_only).  *  */
end_comment

begin_function
name|GtkWidget
modifier|*
DECL|function|gimp_option_menu_new (gboolean menu_only,...)
name|gimp_option_menu_new
parameter_list|(
name|gboolean
name|menu_only
parameter_list|,
comment|/* specify menu items as va_list: 		       *  gchar          *label, 		       *  GtkSignalFunc   callback, 		       *  gpointer        data, 		       *  gpointer        user_data, 		       *  GtkWidget     **widget_ptr, 		       *  gboolean        active 		       */
modifier|...
parameter_list|)
block|{
name|GtkWidget
modifier|*
name|menu
decl_stmt|;
name|GtkWidget
modifier|*
name|menuitem
decl_stmt|;
comment|/*  menu item variables  */
name|gchar
modifier|*
name|label
decl_stmt|;
name|GtkSignalFunc
name|callback
decl_stmt|;
name|gpointer
name|data
decl_stmt|;
name|gpointer
name|user_data
decl_stmt|;
name|GtkWidget
modifier|*
modifier|*
name|widget_ptr
decl_stmt|;
name|gboolean
name|active
decl_stmt|;
name|va_list
name|args
decl_stmt|;
name|gint
name|i
decl_stmt|;
name|gint
name|initial_index
decl_stmt|;
name|menu
operator|=
name|gtk_menu_new
argument_list|()
expr_stmt|;
comment|/*  create the menu items  */
name|initial_index
operator|=
literal|0
expr_stmt|;
name|va_start
argument_list|(
name|args
argument_list|,
name|menu_only
argument_list|)
expr_stmt|;
name|label
operator|=
name|va_arg
argument_list|(
name|args
argument_list|,
name|gchar
operator|*
argument_list|)
expr_stmt|;
for|for
control|(
name|i
operator|=
literal|0
init|;
name|label
condition|;
name|i
operator|++
control|)
block|{
name|callback
operator|=
name|va_arg
argument_list|(
name|args
argument_list|,
name|GtkSignalFunc
argument_list|)
expr_stmt|;
name|data
operator|=
name|va_arg
argument_list|(
name|args
argument_list|,
name|gpointer
argument_list|)
expr_stmt|;
name|user_data
operator|=
name|va_arg
argument_list|(
name|args
argument_list|,
name|gpointer
argument_list|)
expr_stmt|;
name|widget_ptr
operator|=
name|va_arg
argument_list|(
name|args
argument_list|,
name|GtkWidget
operator|*
operator|*
argument_list|)
expr_stmt|;
name|active
operator|=
name|va_arg
argument_list|(
name|args
argument_list|,
name|gboolean
argument_list|)
expr_stmt|;
if|if
condition|(
name|strcmp
argument_list|(
name|label
argument_list|,
literal|"---"
argument_list|)
condition|)
block|{
name|menuitem
operator|=
name|gtk_menu_item_new_with_label
argument_list|(
name|label
argument_list|)
expr_stmt|;
name|gtk_signal_connect
argument_list|(
name|GTK_OBJECT
argument_list|(
name|menuitem
argument_list|)
argument_list|,
literal|"activate"
argument_list|,
name|callback
argument_list|,
name|data
argument_list|)
expr_stmt|;
if|if
condition|(
name|user_data
condition|)
name|gtk_object_set_user_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|menuitem
argument_list|)
argument_list|,
name|user_data
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|menuitem
operator|=
name|gtk_menu_item_new
argument_list|()
expr_stmt|;
block|}
name|gtk_menu_append
argument_list|(
name|GTK_MENU
argument_list|(
name|menu
argument_list|)
argument_list|,
name|menuitem
argument_list|)
expr_stmt|;
if|if
condition|(
name|widget_ptr
condition|)
operator|*
name|widget_ptr
operator|=
name|menuitem
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|menuitem
argument_list|)
expr_stmt|;
comment|/*  remember the initial menu item  */
if|if
condition|(
name|active
condition|)
name|initial_index
operator|=
name|i
expr_stmt|;
name|label
operator|=
name|va_arg
argument_list|(
name|args
argument_list|,
name|gchar
operator|*
argument_list|)
expr_stmt|;
block|}
name|va_end
argument_list|(
name|args
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|menu_only
condition|)
block|{
name|GtkWidget
modifier|*
name|optionmenu
decl_stmt|;
name|optionmenu
operator|=
name|gtk_option_menu_new
argument_list|()
expr_stmt|;
name|gtk_option_menu_set_menu
argument_list|(
name|GTK_OPTION_MENU
argument_list|(
name|optionmenu
argument_list|)
argument_list|,
name|menu
argument_list|)
expr_stmt|;
comment|/*  select the initial menu item  */
name|gtk_option_menu_set_history
argument_list|(
name|GTK_OPTION_MENU
argument_list|(
name|optionmenu
argument_list|)
argument_list|,
name|initial_index
argument_list|)
expr_stmt|;
return|return
name|optionmenu
return|;
block|}
return|return
name|menu
return|;
block|}
end_function

begin_comment
comment|/**  * gimp_option_menu_new2:  * @menu_only: #TRUE if the function should return a #GtkMenu only.  * @menu_item_callback: The callback each menu item's "activate" signal will  *                      be connected with.  * @data: The data which will be passed to gtk_signal_connect().  * @initial: The @user_data of the initially selected menu item.  * @...: A #NULL terminated @va_list describing the menu items.  *  * Returns: A #GtkOptionMenu or a #GtkMenu (depending on @menu_only).  *  */
end_comment

begin_function
name|GtkWidget
modifier|*
DECL|function|gimp_option_menu_new2 (gboolean menu_only,GtkSignalFunc menu_item_callback,gpointer data,gpointer initial,...)
name|gimp_option_menu_new2
parameter_list|(
name|gboolean
name|menu_only
parameter_list|,
name|GtkSignalFunc
name|menu_item_callback
parameter_list|,
name|gpointer
name|data
parameter_list|,
name|gpointer
name|initial
parameter_list|,
comment|/* user_data */
comment|/* specify menu items as va_list: 			*  gchar      *label, 			*  gpointer    user_data, 			*  GtkWidget **widget_ptr, 			*/
modifier|...
parameter_list|)
block|{
name|GtkWidget
modifier|*
name|menu
decl_stmt|;
name|GtkWidget
modifier|*
name|menuitem
decl_stmt|;
comment|/*  menu item variables  */
name|gchar
modifier|*
name|label
decl_stmt|;
name|gpointer
name|user_data
decl_stmt|;
name|GtkWidget
modifier|*
modifier|*
name|widget_ptr
decl_stmt|;
name|va_list
name|args
decl_stmt|;
name|gint
name|i
decl_stmt|;
name|gint
name|initial_index
decl_stmt|;
name|menu
operator|=
name|gtk_menu_new
argument_list|()
expr_stmt|;
comment|/*  create the menu items  */
name|initial_index
operator|=
literal|0
expr_stmt|;
name|va_start
argument_list|(
name|args
argument_list|,
name|initial
argument_list|)
expr_stmt|;
name|label
operator|=
name|va_arg
argument_list|(
name|args
argument_list|,
name|gchar
operator|*
argument_list|)
expr_stmt|;
for|for
control|(
name|i
operator|=
literal|0
init|;
name|label
condition|;
name|i
operator|++
control|)
block|{
name|user_data
operator|=
name|va_arg
argument_list|(
name|args
argument_list|,
name|gpointer
argument_list|)
expr_stmt|;
name|widget_ptr
operator|=
name|va_arg
argument_list|(
name|args
argument_list|,
name|GtkWidget
operator|*
operator|*
argument_list|)
expr_stmt|;
if|if
condition|(
name|strcmp
argument_list|(
name|label
argument_list|,
literal|"---"
argument_list|)
condition|)
block|{
name|menuitem
operator|=
name|gtk_menu_item_new_with_label
argument_list|(
name|label
argument_list|)
expr_stmt|;
name|gtk_signal_connect
argument_list|(
name|GTK_OBJECT
argument_list|(
name|menuitem
argument_list|)
argument_list|,
literal|"activate"
argument_list|,
name|menu_item_callback
argument_list|,
name|data
argument_list|)
expr_stmt|;
if|if
condition|(
name|user_data
condition|)
name|gtk_object_set_user_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|menuitem
argument_list|)
argument_list|,
name|user_data
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|menuitem
operator|=
name|gtk_menu_item_new
argument_list|()
expr_stmt|;
block|}
name|gtk_menu_append
argument_list|(
name|GTK_MENU
argument_list|(
name|menu
argument_list|)
argument_list|,
name|menuitem
argument_list|)
expr_stmt|;
if|if
condition|(
name|widget_ptr
condition|)
operator|*
name|widget_ptr
operator|=
name|menuitem
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|menuitem
argument_list|)
expr_stmt|;
comment|/*  remember the initial menu item  */
if|if
condition|(
name|user_data
operator|==
name|initial
condition|)
name|initial_index
operator|=
name|i
expr_stmt|;
name|label
operator|=
name|va_arg
argument_list|(
name|args
argument_list|,
name|gchar
operator|*
argument_list|)
expr_stmt|;
block|}
name|va_end
argument_list|(
name|args
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|menu_only
condition|)
block|{
name|GtkWidget
modifier|*
name|optionmenu
decl_stmt|;
name|optionmenu
operator|=
name|gtk_option_menu_new
argument_list|()
expr_stmt|;
name|gtk_option_menu_set_menu
argument_list|(
name|GTK_OPTION_MENU
argument_list|(
name|optionmenu
argument_list|)
argument_list|,
name|menu
argument_list|)
expr_stmt|;
comment|/*  select the initial menu item  */
name|gtk_option_menu_set_history
argument_list|(
name|GTK_OPTION_MENU
argument_list|(
name|optionmenu
argument_list|)
argument_list|,
name|initial_index
argument_list|)
expr_stmt|;
return|return
name|optionmenu
return|;
block|}
return|return
name|menu
return|;
block|}
end_function

begin_comment
comment|/**  * gimp_option_menu_set_history:  * @option_menu: A #GtkOptionMenu as returned by gimp_option_menu_new() or  *               gimp_option_menu_new2().  * @user_data: The @user_data of the menu item you want to select.  *  */
end_comment

begin_function
name|void
DECL|function|gimp_option_menu_set_history (GtkOptionMenu * option_menu,gpointer user_data)
name|gimp_option_menu_set_history
parameter_list|(
name|GtkOptionMenu
modifier|*
name|option_menu
parameter_list|,
name|gpointer
name|user_data
parameter_list|)
block|{
name|GtkWidget
modifier|*
name|menu_item
decl_stmt|;
name|GList
modifier|*
name|list
decl_stmt|;
name|gint
name|history
init|=
literal|0
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|option_menu
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
name|GTK_IS_OPTION_MENU
argument_list|(
name|option_menu
argument_list|)
argument_list|)
expr_stmt|;
for|for
control|(
name|list
operator|=
name|GTK_MENU_SHELL
argument_list|(
name|option_menu
operator|->
name|menu
argument_list|)
operator|->
name|children
init|;
name|list
condition|;
name|list
operator|=
name|g_list_next
argument_list|(
name|list
argument_list|)
control|)
block|{
name|menu_item
operator|=
name|GTK_WIDGET
argument_list|(
name|list
operator|->
name|data
argument_list|)
expr_stmt|;
if|if
condition|(
name|GTK_IS_LABEL
argument_list|(
name|GTK_BIN
argument_list|(
name|menu_item
argument_list|)
operator|->
name|child
argument_list|)
operator|&&
name|gtk_object_get_user_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|menu_item
argument_list|)
argument_list|)
operator|==
name|user_data
condition|)
block|{
break|break;
block|}
name|history
operator|++
expr_stmt|;
block|}
if|if
condition|(
name|list
condition|)
name|gtk_option_menu_set_history
argument_list|(
name|option_menu
argument_list|,
name|history
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/**  * gimp_radio_group_new:  * @in_frame: #TRUE if you want a #GtkFrame around the radio button group.  * @frame_title: The title of the Frame or #NULL if you don't want a title.  * @...: A #NULL terminated @va_list describing the radio buttons.  *  * Returns: A #GtkFrame or #GtkVbox (depending on @in_frame).  *  */
end_comment

begin_function
name|GtkWidget
modifier|*
DECL|function|gimp_radio_group_new (gboolean in_frame,gchar * frame_title,...)
name|gimp_radio_group_new
parameter_list|(
name|gboolean
name|in_frame
parameter_list|,
name|gchar
modifier|*
name|frame_title
parameter_list|,
comment|/* specify radio buttons as va_list: 		       *  gchar          *label, 		       *  GtkSignalFunc   callback, 		       *  gpointer        data, 		       *  gpointer        user_data, 		       *  GtkWidget     **widget_ptr, 		       *  gboolean        active, 		       */
modifier|...
parameter_list|)
block|{
name|GtkWidget
modifier|*
name|vbox
decl_stmt|;
name|GtkWidget
modifier|*
name|button
decl_stmt|;
name|GSList
modifier|*
name|group
decl_stmt|;
comment|/*  radio button variables  */
name|gchar
modifier|*
name|label
decl_stmt|;
name|GtkSignalFunc
name|callback
decl_stmt|;
name|gpointer
name|data
decl_stmt|;
name|gpointer
name|user_data
decl_stmt|;
name|GtkWidget
modifier|*
modifier|*
name|widget_ptr
decl_stmt|;
name|gboolean
name|active
decl_stmt|;
name|va_list
name|args
decl_stmt|;
name|vbox
operator|=
name|gtk_vbox_new
argument_list|(
name|FALSE
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|group
operator|=
name|NULL
expr_stmt|;
comment|/*  create the radio buttons  */
name|va_start
argument_list|(
name|args
argument_list|,
name|frame_title
argument_list|)
expr_stmt|;
name|label
operator|=
name|va_arg
argument_list|(
name|args
argument_list|,
name|gchar
operator|*
argument_list|)
expr_stmt|;
while|while
condition|(
name|label
condition|)
block|{
name|callback
operator|=
name|va_arg
argument_list|(
name|args
argument_list|,
name|GtkSignalFunc
argument_list|)
expr_stmt|;
name|data
operator|=
name|va_arg
argument_list|(
name|args
argument_list|,
name|gpointer
argument_list|)
expr_stmt|;
name|user_data
operator|=
name|va_arg
argument_list|(
name|args
argument_list|,
name|gpointer
argument_list|)
expr_stmt|;
name|widget_ptr
operator|=
name|va_arg
argument_list|(
name|args
argument_list|,
name|GtkWidget
operator|*
operator|*
argument_list|)
expr_stmt|;
name|active
operator|=
name|va_arg
argument_list|(
name|args
argument_list|,
name|gboolean
argument_list|)
expr_stmt|;
if|if
condition|(
name|label
operator|!=
operator|(
name|gpointer
operator|)
literal|1
condition|)
name|button
operator|=
name|gtk_radio_button_new_with_label
argument_list|(
name|group
argument_list|,
name|label
argument_list|)
expr_stmt|;
else|else
name|button
operator|=
name|gtk_radio_button_new
argument_list|(
name|group
argument_list|)
expr_stmt|;
name|group
operator|=
name|gtk_radio_button_group
argument_list|(
name|GTK_RADIO_BUTTON
argument_list|(
name|button
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|vbox
argument_list|)
argument_list|,
name|button
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
if|if
condition|(
name|user_data
condition|)
name|gtk_object_set_user_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|button
argument_list|)
argument_list|,
name|user_data
argument_list|)
expr_stmt|;
if|if
condition|(
name|widget_ptr
condition|)
operator|*
name|widget_ptr
operator|=
name|button
expr_stmt|;
if|if
condition|(
name|active
condition|)
name|gtk_toggle_button_set_active
argument_list|(
name|GTK_TOGGLE_BUTTON
argument_list|(
name|button
argument_list|)
argument_list|,
name|TRUE
argument_list|)
expr_stmt|;
name|gtk_signal_connect
argument_list|(
name|GTK_OBJECT
argument_list|(
name|button
argument_list|)
argument_list|,
literal|"toggled"
argument_list|,
name|callback
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|button
argument_list|)
expr_stmt|;
name|label
operator|=
name|va_arg
argument_list|(
name|args
argument_list|,
name|gchar
operator|*
argument_list|)
expr_stmt|;
block|}
name|va_end
argument_list|(
name|args
argument_list|)
expr_stmt|;
if|if
condition|(
name|in_frame
condition|)
block|{
name|GtkWidget
modifier|*
name|frame
decl_stmt|;
name|gtk_container_set_border_width
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|vbox
argument_list|)
argument_list|,
literal|2
argument_list|)
expr_stmt|;
name|frame
operator|=
name|gtk_frame_new
argument_list|(
name|frame_title
argument_list|)
expr_stmt|;
name|gtk_container_add
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|frame
argument_list|)
argument_list|,
name|vbox
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|vbox
argument_list|)
expr_stmt|;
return|return
name|frame
return|;
block|}
return|return
name|vbox
return|;
block|}
end_function

begin_comment
comment|/**  * gimp_radio_group_new2:  * @in_frame: #TRUE if you want a #GtkFrame around the radio button group.  * @frame_title: The title of the Frame or #NULL if you don't want a title.  * @radio_button_callback: The callback each button's "toggled" signal will  *                         be connected with.  * @data: The data which will be passed to gtk_signal_connect().  * @initial: The @user_data of the initially pressed radio button.  * @...: A #NULL terminated @va_list describing the radio buttons.  *  * Returns: A #GtkFrame or #GtkVbox (depending on @in_frame).  *  */
end_comment

begin_function
name|GtkWidget
modifier|*
DECL|function|gimp_radio_group_new2 (gboolean in_frame,gchar * frame_title,GtkSignalFunc radio_button_callback,gpointer data,gpointer initial,...)
name|gimp_radio_group_new2
parameter_list|(
name|gboolean
name|in_frame
parameter_list|,
name|gchar
modifier|*
name|frame_title
parameter_list|,
name|GtkSignalFunc
name|radio_button_callback
parameter_list|,
name|gpointer
name|data
parameter_list|,
name|gpointer
name|initial
parameter_list|,
comment|/* user_data */
comment|/* specify radio buttons as va_list: 			*  gchar      *label, 			*  gpointer    user_data, 			*  GtkWidget **widget_ptr, 			*/
modifier|...
parameter_list|)
block|{
name|GtkWidget
modifier|*
name|vbox
decl_stmt|;
name|GtkWidget
modifier|*
name|button
decl_stmt|;
name|GSList
modifier|*
name|group
decl_stmt|;
comment|/*  radio button variables  */
name|gchar
modifier|*
name|label
decl_stmt|;
name|gpointer
name|user_data
decl_stmt|;
name|GtkWidget
modifier|*
modifier|*
name|widget_ptr
decl_stmt|;
name|va_list
name|args
decl_stmt|;
name|vbox
operator|=
name|gtk_vbox_new
argument_list|(
name|FALSE
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|group
operator|=
name|NULL
expr_stmt|;
comment|/*  create the radio buttons  */
name|va_start
argument_list|(
name|args
argument_list|,
name|initial
argument_list|)
expr_stmt|;
name|label
operator|=
name|va_arg
argument_list|(
name|args
argument_list|,
name|gchar
operator|*
argument_list|)
expr_stmt|;
while|while
condition|(
name|label
condition|)
block|{
name|user_data
operator|=
name|va_arg
argument_list|(
name|args
argument_list|,
name|gpointer
argument_list|)
expr_stmt|;
name|widget_ptr
operator|=
name|va_arg
argument_list|(
name|args
argument_list|,
name|GtkWidget
operator|*
operator|*
argument_list|)
expr_stmt|;
if|if
condition|(
name|label
operator|!=
operator|(
name|gpointer
operator|)
literal|1
condition|)
name|button
operator|=
name|gtk_radio_button_new_with_label
argument_list|(
name|group
argument_list|,
name|label
argument_list|)
expr_stmt|;
else|else
name|button
operator|=
name|gtk_radio_button_new
argument_list|(
name|group
argument_list|)
expr_stmt|;
name|group
operator|=
name|gtk_radio_button_group
argument_list|(
name|GTK_RADIO_BUTTON
argument_list|(
name|button
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|vbox
argument_list|)
argument_list|,
name|button
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
if|if
condition|(
name|user_data
condition|)
name|gtk_object_set_user_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|button
argument_list|)
argument_list|,
name|user_data
argument_list|)
expr_stmt|;
if|if
condition|(
name|widget_ptr
condition|)
operator|*
name|widget_ptr
operator|=
name|button
expr_stmt|;
if|if
condition|(
name|initial
operator|==
name|user_data
condition|)
name|gtk_toggle_button_set_active
argument_list|(
name|GTK_TOGGLE_BUTTON
argument_list|(
name|button
argument_list|)
argument_list|,
name|TRUE
argument_list|)
expr_stmt|;
name|gtk_signal_connect
argument_list|(
name|GTK_OBJECT
argument_list|(
name|button
argument_list|)
argument_list|,
literal|"toggled"
argument_list|,
name|radio_button_callback
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|button
argument_list|)
expr_stmt|;
name|label
operator|=
name|va_arg
argument_list|(
name|args
argument_list|,
name|gchar
operator|*
argument_list|)
expr_stmt|;
block|}
name|va_end
argument_list|(
name|args
argument_list|)
expr_stmt|;
if|if
condition|(
name|in_frame
condition|)
block|{
name|GtkWidget
modifier|*
name|frame
decl_stmt|;
name|gtk_container_set_border_width
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|vbox
argument_list|)
argument_list|,
literal|2
argument_list|)
expr_stmt|;
name|frame
operator|=
name|gtk_frame_new
argument_list|(
name|frame_title
argument_list|)
expr_stmt|;
name|gtk_container_add
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|frame
argument_list|)
argument_list|,
name|vbox
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|vbox
argument_list|)
expr_stmt|;
return|return
name|frame
return|;
block|}
return|return
name|vbox
return|;
block|}
end_function

begin_comment
comment|/**  * gimp_spin_button_new:  * @adjustment: Returns the spinbutton's #GtkAdjustment.  * @value: The initial value of the spinbutton.  * @lower: The lower boundary.  * @upper: The uppper boundary.  * @step_increment: The spinbutton's step increment.  * @page_increment: The spinbutton's page increment (mouse button 2).  * @page_size: The spinbutton's page size.  * @climb_rate: The spinbutton's climb rate.  * @digits: The spinbutton's number of decimal digits.  *  * This function is a shortcut for gtk_adjustment_new() and a subsequent  * gtk_spin_button_new() and does some more initialisation stuff like  * setting a standard minimun horizontal size.  *  * Returns: A #GtkSpinbutton and it's #GtkAdjustment.  *  */
end_comment

begin_function
name|GtkWidget
modifier|*
DECL|function|gimp_spin_button_new (GtkObject ** adjustment,gfloat value,gfloat lower,gfloat upper,gfloat step_increment,gfloat page_increment,gfloat page_size,gfloat climb_rate,guint digits)
name|gimp_spin_button_new
parameter_list|(
name|GtkObject
modifier|*
modifier|*
name|adjustment
parameter_list|,
comment|/* return value */
name|gfloat
name|value
parameter_list|,
name|gfloat
name|lower
parameter_list|,
name|gfloat
name|upper
parameter_list|,
name|gfloat
name|step_increment
parameter_list|,
name|gfloat
name|page_increment
parameter_list|,
name|gfloat
name|page_size
parameter_list|,
name|gfloat
name|climb_rate
parameter_list|,
name|guint
name|digits
parameter_list|)
block|{
name|GtkWidget
modifier|*
name|spinbutton
decl_stmt|;
operator|*
name|adjustment
operator|=
name|gtk_adjustment_new
argument_list|(
name|value
argument_list|,
name|lower
argument_list|,
name|upper
argument_list|,
name|step_increment
argument_list|,
name|page_increment
argument_list|,
name|page_size
argument_list|)
expr_stmt|;
name|spinbutton
operator|=
name|gtk_spin_button_new
argument_list|(
name|GTK_ADJUSTMENT
argument_list|(
operator|*
name|adjustment
argument_list|)
argument_list|,
name|climb_rate
argument_list|,
name|digits
argument_list|)
expr_stmt|;
name|gtk_spin_button_set_shadow_type
argument_list|(
name|GTK_SPIN_BUTTON
argument_list|(
name|spinbutton
argument_list|)
argument_list|,
name|GTK_SHADOW_NONE
argument_list|)
expr_stmt|;
name|gtk_spin_button_set_numeric
argument_list|(
name|GTK_SPIN_BUTTON
argument_list|(
name|spinbutton
argument_list|)
argument_list|,
name|TRUE
argument_list|)
expr_stmt|;
name|gtk_widget_set_usize
argument_list|(
name|spinbutton
argument_list|,
literal|75
argument_list|,
operator|-
literal|1
argument_list|)
expr_stmt|;
return|return
name|spinbutton
return|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_scale_entry_unconstrained_adjustment_callback (GtkAdjustment * adjustment,GtkAdjustment * other_adj)
name|gimp_scale_entry_unconstrained_adjustment_callback
parameter_list|(
name|GtkAdjustment
modifier|*
name|adjustment
parameter_list|,
name|GtkAdjustment
modifier|*
name|other_adj
parameter_list|)
block|{
name|gtk_signal_handler_block_by_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|other_adj
argument_list|)
argument_list|,
name|adjustment
argument_list|)
expr_stmt|;
name|gtk_adjustment_set_value
argument_list|(
name|other_adj
argument_list|,
name|adjustment
operator|->
name|value
argument_list|)
expr_stmt|;
name|gtk_signal_handler_unblock_by_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|other_adj
argument_list|)
argument_list|,
name|adjustment
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/**  * gimp_scale_entry_new:  * @table: The #GtkTable the widgets will be attached to.  * @column: The column to start with.  * @row: The row to attach the widgets.  * @text: The text for the #GtkLabel which will appear left of the #GtkHScale.  * @scale_usize: The minimum horizontal size of the #GtkHScale.  * @spinbutton_usize: The minimum horizontal size of the #GtkSpinButton.  * @value: The initial value.  * @lower: The lower boundary.  * @upper: The upper boundary.  * @step_increment: The step increment.  * @page_increment: The page increment.  * @digits: The number of decimal digits.  * @constrain: #TRUE if the range of possible values of the #GtkSpinButton  *             should be the same as of the #GtkHScale.  * @unconstrained_lower: The spinbutton's lower boundary  *                       if @constrain == #FALSE.  * @unconstrained_upper: The spinbutton's upper boundary  *                       if @constrain == #FALSE.  * @tooltip: A tooltip message for the scale and the spinbutton.  * @help_data: The widgets' help_data (see gimp_help_set_help_data()).  *  * This function creates a #GtkLabel, a #GtkHScale and a #GtkSpinButton and  * attaches them to a 3-column #GtkTable.  *  * Note that if you pass a @tooltip or @help_data to this function you'll  * have to initialize GIMP's help system with gimp_help_init() before using it.  *  * Returns: The #GtkSpinButton's #GtkAdjustment.  *  */
end_comment

begin_function
name|GtkObject
modifier|*
DECL|function|gimp_scale_entry_new (GtkTable * table,gint column,gint row,gchar * text,gint scale_usize,gint spinbutton_usize,gfloat value,gfloat lower,gfloat upper,gfloat step_increment,gfloat page_increment,guint digits,gboolean constrain,gfloat unconstrained_lower,gfloat unconstrained_upper,gchar * tooltip,gchar * help_data)
name|gimp_scale_entry_new
parameter_list|(
name|GtkTable
modifier|*
name|table
parameter_list|,
name|gint
name|column
parameter_list|,
name|gint
name|row
parameter_list|,
name|gchar
modifier|*
name|text
parameter_list|,
name|gint
name|scale_usize
parameter_list|,
name|gint
name|spinbutton_usize
parameter_list|,
name|gfloat
name|value
parameter_list|,
name|gfloat
name|lower
parameter_list|,
name|gfloat
name|upper
parameter_list|,
name|gfloat
name|step_increment
parameter_list|,
name|gfloat
name|page_increment
parameter_list|,
name|guint
name|digits
parameter_list|,
name|gboolean
name|constrain
parameter_list|,
name|gfloat
name|unconstrained_lower
parameter_list|,
name|gfloat
name|unconstrained_upper
parameter_list|,
name|gchar
modifier|*
name|tooltip
parameter_list|,
name|gchar
modifier|*
name|help_data
parameter_list|)
block|{
name|GtkWidget
modifier|*
name|label
decl_stmt|;
name|GtkWidget
modifier|*
name|scale
decl_stmt|;
name|GtkWidget
modifier|*
name|spinbutton
decl_stmt|;
name|GtkObject
modifier|*
name|adjustment
decl_stmt|;
name|GtkObject
modifier|*
name|return_adj
decl_stmt|;
name|label
operator|=
name|gtk_label_new
argument_list|(
name|text
argument_list|)
expr_stmt|;
name|gtk_misc_set_alignment
argument_list|(
name|GTK_MISC
argument_list|(
name|label
argument_list|)
argument_list|,
literal|1.0
argument_list|,
literal|0.5
argument_list|)
expr_stmt|;
name|gtk_table_attach
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
name|label
argument_list|,
name|column
argument_list|,
name|column
operator|+
literal|1
argument_list|,
name|row
argument_list|,
name|row
operator|+
literal|1
argument_list|,
name|GTK_FILL
argument_list|,
name|GTK_FILL
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|label
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|constrain
operator|&&
name|unconstrained_lower
operator|<=
name|lower
operator|&&
name|unconstrained_upper
operator|>=
name|upper
condition|)
block|{
name|GtkObject
modifier|*
name|constrained_adj
decl_stmt|;
name|constrained_adj
operator|=
name|gtk_adjustment_new
argument_list|(
name|value
argument_list|,
name|lower
argument_list|,
name|upper
argument_list|,
name|step_increment
argument_list|,
name|page_increment
argument_list|,
literal|0.0
argument_list|)
expr_stmt|;
name|spinbutton
operator|=
name|gimp_spin_button_new
argument_list|(
operator|&
name|adjustment
argument_list|,
name|value
argument_list|,
name|unconstrained_lower
argument_list|,
name|unconstrained_upper
argument_list|,
name|step_increment
argument_list|,
name|page_increment
argument_list|,
literal|0.0
argument_list|,
literal|1.0
argument_list|,
name|digits
argument_list|)
expr_stmt|;
name|gtk_signal_connect
argument_list|(
name|GTK_OBJECT
argument_list|(
name|constrained_adj
argument_list|)
argument_list|,
literal|"value_changed"
argument_list|,
name|GTK_SIGNAL_FUNC
argument_list|(
name|gimp_scale_entry_unconstrained_adjustment_callback
argument_list|)
argument_list|,
name|adjustment
argument_list|)
expr_stmt|;
name|gtk_signal_connect
argument_list|(
name|GTK_OBJECT
argument_list|(
name|adjustment
argument_list|)
argument_list|,
literal|"value_changed"
argument_list|,
name|GTK_SIGNAL_FUNC
argument_list|(
name|gimp_scale_entry_unconstrained_adjustment_callback
argument_list|)
argument_list|,
name|constrained_adj
argument_list|)
expr_stmt|;
name|return_adj
operator|=
name|adjustment
expr_stmt|;
name|adjustment
operator|=
name|constrained_adj
expr_stmt|;
block|}
else|else
block|{
name|spinbutton
operator|=
name|gimp_spin_button_new
argument_list|(
operator|&
name|adjustment
argument_list|,
name|value
argument_list|,
name|lower
argument_list|,
name|upper
argument_list|,
name|step_increment
argument_list|,
name|page_increment
argument_list|,
literal|0.0
argument_list|,
literal|1.0
argument_list|,
name|digits
argument_list|)
expr_stmt|;
name|return_adj
operator|=
name|adjustment
expr_stmt|;
block|}
if|if
condition|(
name|spinbutton_usize
operator|>
literal|0
condition|)
name|gtk_widget_set_usize
argument_list|(
name|spinbutton
argument_list|,
name|spinbutton_usize
argument_list|,
operator|-
literal|1
argument_list|)
expr_stmt|;
name|scale
operator|=
name|gtk_hscale_new
argument_list|(
name|GTK_ADJUSTMENT
argument_list|(
name|adjustment
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|scale_usize
operator|>
literal|0
condition|)
name|gtk_widget_set_usize
argument_list|(
name|scale
argument_list|,
name|scale_usize
argument_list|,
operator|-
literal|1
argument_list|)
expr_stmt|;
name|gtk_scale_set_digits
argument_list|(
name|GTK_SCALE
argument_list|(
name|scale
argument_list|)
argument_list|,
name|digits
argument_list|)
expr_stmt|;
name|gtk_scale_set_draw_value
argument_list|(
name|GTK_SCALE
argument_list|(
name|scale
argument_list|)
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gtk_table_attach
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
name|scale
argument_list|,
name|column
operator|+
literal|1
argument_list|,
name|column
operator|+
literal|2
argument_list|,
name|row
argument_list|,
name|row
operator|+
literal|1
argument_list|,
name|GTK_FILL
operator||
name|GTK_EXPAND
argument_list|,
name|GTK_FILL
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|scale
argument_list|)
expr_stmt|;
name|gtk_table_attach
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
name|spinbutton
argument_list|,
name|column
operator|+
literal|2
argument_list|,
name|column
operator|+
literal|3
argument_list|,
name|row
argument_list|,
name|row
operator|+
literal|1
argument_list|,
name|GTK_SHRINK
argument_list|,
name|GTK_SHRINK
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|spinbutton
argument_list|)
expr_stmt|;
if|if
condition|(
name|tooltip
operator|||
name|help_data
condition|)
block|{
name|gimp_help_set_help_data
argument_list|(
name|scale
argument_list|,
name|tooltip
argument_list|,
name|help_data
argument_list|)
expr_stmt|;
name|gimp_help_set_help_data
argument_list|(
name|spinbutton
argument_list|,
name|tooltip
argument_list|,
name|help_data
argument_list|)
expr_stmt|;
block|}
name|gtk_object_set_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|return_adj
argument_list|)
argument_list|,
literal|"label"
argument_list|,
name|label
argument_list|)
expr_stmt|;
name|gtk_object_set_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|return_adj
argument_list|)
argument_list|,
literal|"scale"
argument_list|,
name|scale
argument_list|)
expr_stmt|;
name|gtk_object_set_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|return_adj
argument_list|)
argument_list|,
literal|"spinbutton"
argument_list|,
name|spinbutton
argument_list|)
expr_stmt|;
return|return
name|return_adj
return|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_random_seed_toggle_update (GtkWidget * widget,gpointer data)
name|gimp_random_seed_toggle_update
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|gint
modifier|*
name|toggle_val
decl_stmt|;
name|toggle_val
operator|=
operator|(
name|gint
operator|*
operator|)
name|data
expr_stmt|;
if|if
condition|(
name|gtk_toggle_button_get_active
argument_list|(
name|GTK_TOGGLE_BUTTON
argument_list|(
name|widget
argument_list|)
argument_list|)
condition|)
operator|*
name|toggle_val
operator|=
operator|(
name|gint
operator|)
name|gtk_object_get_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|widget
argument_list|)
argument_list|,
literal|"time_true"
argument_list|)
expr_stmt|;
else|else
operator|*
name|toggle_val
operator|=
operator|(
name|gint
operator|)
name|gtk_object_get_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|widget
argument_list|)
argument_list|,
literal|"time_false"
argument_list|)
expr_stmt|;
name|gimp_toggle_button_sensitive_update
argument_list|(
name|GTK_TOGGLE_BUTTON
argument_list|(
name|widget
argument_list|)
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/**  * gimp_random_seed_new:  * @seed: A pointer to the variable which stores the random seed.  * @use_time: A pointer to the variable which stores the @use_time  *            toggle boolean.  * @time_true: The value to write to @use_time if the toggle button is checked.  * @time_false: The value to write to @use_time if the toggle button is  *              unchecked.  *  * Note that this widget automatically sets tooltips with  * gimp_help_set_help_data(), so you'll have to initialize GIMP's help  * system with gimp_help_init() before using it.  *  * Returns: A #GtkHBox containing a #GtkSpinButton for the random seed and  *          a #GtkToggleButton for toggling the @use_time behaviour.  *  */
end_comment

begin_function
name|GtkWidget
modifier|*
DECL|function|gimp_random_seed_new (gint * seed,gint * use_time,gint time_true,gint time_false)
name|gimp_random_seed_new
parameter_list|(
name|gint
modifier|*
name|seed
parameter_list|,
name|gint
modifier|*
name|use_time
parameter_list|,
name|gint
name|time_true
parameter_list|,
name|gint
name|time_false
parameter_list|)
block|{
name|GtkWidget
modifier|*
name|hbox
decl_stmt|;
name|GtkWidget
modifier|*
name|spinbutton
decl_stmt|;
name|GtkObject
modifier|*
name|adj
decl_stmt|;
name|GtkWidget
modifier|*
name|button
decl_stmt|;
name|hbox
operator|=
name|gtk_hbox_new
argument_list|(
name|FALSE
argument_list|,
literal|4
argument_list|)
expr_stmt|;
name|spinbutton
operator|=
name|gimp_spin_button_new
argument_list|(
operator|&
name|adj
argument_list|,
operator|*
name|seed
argument_list|,
literal|0
argument_list|,
name|G_MAXRAND
argument_list|,
literal|1
argument_list|,
literal|10
argument_list|,
literal|0
argument_list|,
literal|1
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|hbox
argument_list|)
argument_list|,
name|spinbutton
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_signal_connect
argument_list|(
name|GTK_OBJECT
argument_list|(
name|adj
argument_list|)
argument_list|,
literal|"value_changed"
argument_list|,
name|GTK_SIGNAL_FUNC
argument_list|(
name|gimp_int_adjustment_update
argument_list|)
argument_list|,
name|seed
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|spinbutton
argument_list|)
expr_stmt|;
name|gimp_help_set_help_data
argument_list|(
name|spinbutton
argument_list|,
name|_
argument_list|(
literal|"If the \"Time\" button is not pressed, "
literal|"use this value for random number generator "
literal|"seed - this allows you to repeat a "
literal|"given \"random\" operation"
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|button
operator|=
name|gtk_toggle_button_new_with_label
argument_list|(
name|_
argument_list|(
literal|"Time"
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_misc_set_padding
argument_list|(
name|GTK_MISC
argument_list|(
name|GTK_BIN
argument_list|(
name|button
argument_list|)
operator|->
name|child
argument_list|)
argument_list|,
literal|2
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_signal_connect
argument_list|(
name|GTK_OBJECT
argument_list|(
name|button
argument_list|)
argument_list|,
literal|"toggled"
argument_list|,
name|GTK_SIGNAL_FUNC
argument_list|(
name|gimp_random_seed_toggle_update
argument_list|)
argument_list|,
name|use_time
argument_list|)
expr_stmt|;
name|gtk_box_pack_end
argument_list|(
name|GTK_BOX
argument_list|(
name|hbox
argument_list|)
argument_list|,
name|button
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|button
argument_list|)
expr_stmt|;
name|gimp_help_set_help_data
argument_list|(
name|button
argument_list|,
name|_
argument_list|(
literal|"Seed random number generator from the current "
literal|"time - this guarantees a reasonable "
literal|"randomization"
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|gtk_object_set_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|button
argument_list|)
argument_list|,
literal|"time_true"
argument_list|,
operator|(
name|gpointer
operator|)
name|time_true
argument_list|)
expr_stmt|;
name|gtk_object_set_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|button
argument_list|)
argument_list|,
literal|"time_false"
argument_list|,
operator|(
name|gpointer
operator|)
name|time_false
argument_list|)
expr_stmt|;
name|gtk_object_set_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|button
argument_list|)
argument_list|,
literal|"inverse_sensitive"
argument_list|,
name|spinbutton
argument_list|)
expr_stmt|;
name|gtk_toggle_button_set_active
argument_list|(
name|GTK_TOGGLE_BUTTON
argument_list|(
name|button
argument_list|)
argument_list|,
operator|*
name|use_time
operator|==
name|time_true
argument_list|)
expr_stmt|;
name|gtk_object_set_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|hbox
argument_list|)
argument_list|,
literal|"spinbutton"
argument_list|,
name|spinbutton
argument_list|)
expr_stmt|;
name|gtk_object_set_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|hbox
argument_list|)
argument_list|,
literal|"togglebutton"
argument_list|,
name|button
argument_list|)
expr_stmt|;
return|return
name|hbox
return|;
block|}
end_function

begin_typedef
typedef|typedef
struct|struct
DECL|struct|__anon2b2be4590108
block|{
DECL|member|chainbutton
name|GimpChainButton
modifier|*
name|chainbutton
decl_stmt|;
DECL|member|chain_constrains_ratio
name|gboolean
name|chain_constrains_ratio
decl_stmt|;
DECL|member|orig_x
name|gdouble
name|orig_x
decl_stmt|;
DECL|member|orig_y
name|gdouble
name|orig_y
decl_stmt|;
DECL|member|last_x
name|gdouble
name|last_x
decl_stmt|;
DECL|member|last_y
name|gdouble
name|last_y
decl_stmt|;
DECL|typedef|GimpCoordinatesData
block|}
name|GimpCoordinatesData
typedef|;
end_typedef

begin_function
specifier|static
name|void
DECL|function|gimp_coordinates_callback (GtkWidget * widget,gpointer data)
name|gimp_coordinates_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpCoordinatesData
modifier|*
name|gcd
decl_stmt|;
name|gdouble
name|new_x
decl_stmt|;
name|gdouble
name|new_y
decl_stmt|;
name|gcd
operator|=
operator|(
name|GimpCoordinatesData
operator|*
operator|)
name|data
expr_stmt|;
name|new_x
operator|=
name|gimp_size_entry_get_refval
argument_list|(
name|GIMP_SIZE_ENTRY
argument_list|(
name|widget
argument_list|)
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|new_y
operator|=
name|gimp_size_entry_get_refval
argument_list|(
name|GIMP_SIZE_ENTRY
argument_list|(
name|widget
argument_list|)
argument_list|,
literal|1
argument_list|)
expr_stmt|;
if|if
condition|(
name|gimp_chain_button_get_active
argument_list|(
name|gcd
operator|->
name|chainbutton
argument_list|)
condition|)
block|{
name|gtk_signal_emit_stop_by_name
argument_list|(
name|GTK_OBJECT
argument_list|(
name|widget
argument_list|)
argument_list|,
literal|"value_changed"
argument_list|)
expr_stmt|;
if|if
condition|(
name|gcd
operator|->
name|chain_constrains_ratio
condition|)
block|{
if|if
condition|(
operator|(
name|gcd
operator|->
name|orig_x
operator|!=
literal|0
operator|)
operator|&&
operator|(
name|gcd
operator|->
name|orig_y
operator|!=
literal|0
operator|)
condition|)
block|{
if|if
condition|(
name|new_x
operator|!=
name|gcd
operator|->
name|last_x
condition|)
block|{
name|gcd
operator|->
name|last_x
operator|=
name|new_x
expr_stmt|;
name|gcd
operator|->
name|last_y
operator|=
name|new_y
operator|=
operator|(
name|new_x
operator|*
name|gcd
operator|->
name|orig_y
operator|)
operator|/
name|gcd
operator|->
name|orig_x
expr_stmt|;
name|gimp_size_entry_set_refval
argument_list|(
name|GIMP_SIZE_ENTRY
argument_list|(
name|widget
argument_list|)
argument_list|,
literal|1
argument_list|,
name|new_y
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|new_y
operator|!=
name|gcd
operator|->
name|last_y
condition|)
block|{
name|gcd
operator|->
name|last_y
operator|=
name|new_y
expr_stmt|;
name|gcd
operator|->
name|last_x
operator|=
name|new_x
operator|=
operator|(
name|new_y
operator|*
name|gcd
operator|->
name|orig_x
operator|)
operator|/
name|gcd
operator|->
name|orig_y
expr_stmt|;
name|gimp_size_entry_set_refval
argument_list|(
name|GIMP_SIZE_ENTRY
argument_list|(
name|widget
argument_list|)
argument_list|,
literal|0
argument_list|,
name|new_x
argument_list|)
expr_stmt|;
block|}
block|}
block|}
else|else
block|{
if|if
condition|(
name|new_x
operator|!=
name|gcd
operator|->
name|last_x
condition|)
block|{
name|gcd
operator|->
name|last_y
operator|=
name|new_y
operator|=
name|gcd
operator|->
name|last_x
operator|=
name|new_x
expr_stmt|;
name|gimp_size_entry_set_refval
argument_list|(
name|GIMP_SIZE_ENTRY
argument_list|(
name|widget
argument_list|)
argument_list|,
literal|1
argument_list|,
name|new_x
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|new_y
operator|!=
name|gcd
operator|->
name|last_y
condition|)
block|{
name|gcd
operator|->
name|last_x
operator|=
name|new_x
operator|=
name|gcd
operator|->
name|last_y
operator|=
name|new_y
expr_stmt|;
name|gimp_size_entry_set_refval
argument_list|(
name|GIMP_SIZE_ENTRY
argument_list|(
name|widget
argument_list|)
argument_list|,
literal|0
argument_list|,
name|new_y
argument_list|)
expr_stmt|;
block|}
block|}
block|}
else|else
block|{
if|if
condition|(
name|new_x
operator|!=
name|gcd
operator|->
name|last_x
condition|)
name|gcd
operator|->
name|last_x
operator|=
name|new_x
expr_stmt|;
if|if
condition|(
name|new_y
operator|!=
name|gcd
operator|->
name|last_y
condition|)
name|gcd
operator|->
name|last_y
operator|=
name|new_y
expr_stmt|;
block|}
block|}
end_function

begin_comment
comment|/**  * gimp_coordinates_new:  * @unit: The initial unit of the #GimpUnitMenu.  * @unit_format: The unit format string as passed to gimp_size_entry_new().  * @menu_show_pixels: #TRUE if the #GimpUnitMenu should contain an item for  *                    GIMP_UNIT_PIXEL.  * @menu_show_percent: #TRUE if the #GimpUnitMenu should contain an item for  *                     GIMP_UNIT_PERCENT.  * @spinbutton_usize: The horizontal usize of the #GimpSizeEntry's  *                    #GtkSpinButton's.  * @update_policy: The update policy for the #GimpSizeEntry.  * @chainbutton_active: #TRUE if the attached #GimpChainButton should be  *                      active.  * @chain_constrains_ratio: #TRUE if the chainbutton should constrain the  *                          fields' aspect ratio. If #FALSE, the values will  *                          be constrained.  * @xlabel: The label for the X coordinate.  * @x: The initial value of the X coordinate.  * @xres: The horizontal resolution in DPI.  * @lower_boundary_x: The lower boundary of the X coordinate.  * @upper_boundary_x: The upper boundary of the X coordinate.  * @xsize_0: The X value which will be treated as 0%.  * @xsize_100: The X value which will be treated as 100%.  * @ylabel: The label for the Y coordinate.  * @y: The initial value of the Y coordinate.  * @yres: The vertical resolution in DPI.  * @lower_boundary_y: The lower boundary of the Y coordinate.  * @upper_boundary_y: The upper boundary of the Y coordinate.  * @ysize_0: The Y value which will be treated as 0%.  * @ysize_100: The Y value which will be treated as 100%.  *  * Returns: A #GimpSizeEntry with two fields for x/y coordinates/sizes with  *          a #GimpChainButton attached to constrain either the two fields'  *          values or the ratio between them.  *  */
end_comment

begin_function
name|GtkWidget
modifier|*
DECL|function|gimp_coordinates_new (GimpUnit unit,gchar * unit_format,gboolean menu_show_pixels,gboolean menu_show_percent,gint spinbutton_usize,GimpSizeEntryUpdatePolicy update_policy,gboolean chainbutton_active,gboolean chain_constrains_ratio,gchar * xlabel,gdouble x,gdouble xres,gdouble lower_boundary_x,gdouble upper_boundary_x,gdouble xsize_0,gdouble xsize_100,gchar * ylabel,gdouble y,gdouble yres,gdouble lower_boundary_y,gdouble upper_boundary_y,gdouble ysize_0,gdouble ysize_100)
name|gimp_coordinates_new
parameter_list|(
name|GimpUnit
name|unit
parameter_list|,
name|gchar
modifier|*
name|unit_format
parameter_list|,
name|gboolean
name|menu_show_pixels
parameter_list|,
name|gboolean
name|menu_show_percent
parameter_list|,
name|gint
name|spinbutton_usize
parameter_list|,
name|GimpSizeEntryUpdatePolicy
name|update_policy
parameter_list|,
name|gboolean
name|chainbutton_active
parameter_list|,
name|gboolean
name|chain_constrains_ratio
parameter_list|,
name|gchar
modifier|*
name|xlabel
parameter_list|,
name|gdouble
name|x
parameter_list|,
name|gdouble
name|xres
parameter_list|,
name|gdouble
name|lower_boundary_x
parameter_list|,
name|gdouble
name|upper_boundary_x
parameter_list|,
name|gdouble
name|xsize_0
parameter_list|,
comment|/* % */
name|gdouble
name|xsize_100
parameter_list|,
comment|/* % */
name|gchar
modifier|*
name|ylabel
parameter_list|,
name|gdouble
name|y
parameter_list|,
name|gdouble
name|yres
parameter_list|,
name|gdouble
name|lower_boundary_y
parameter_list|,
name|gdouble
name|upper_boundary_y
parameter_list|,
name|gdouble
name|ysize_0
parameter_list|,
comment|/* % */
name|gdouble
name|ysize_100
comment|/* % */
parameter_list|)
block|{
name|GimpCoordinatesData
modifier|*
name|gcd
decl_stmt|;
name|GtkObject
modifier|*
name|adjustment
decl_stmt|;
name|GtkWidget
modifier|*
name|spinbutton
decl_stmt|;
name|GtkWidget
modifier|*
name|sizeentry
decl_stmt|;
name|GtkWidget
modifier|*
name|chainbutton
decl_stmt|;
name|spinbutton
operator|=
name|gimp_spin_button_new
argument_list|(
operator|&
name|adjustment
argument_list|,
literal|1
argument_list|,
literal|0
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|,
literal|10
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|)
expr_stmt|;
name|sizeentry
operator|=
name|gimp_size_entry_new
argument_list|(
literal|1
argument_list|,
name|unit
argument_list|,
name|unit_format
argument_list|,
name|menu_show_pixels
argument_list|,
name|menu_show_percent
argument_list|,
name|FALSE
argument_list|,
name|spinbutton_usize
argument_list|,
name|update_policy
argument_list|)
expr_stmt|;
name|gtk_table_set_col_spacing
argument_list|(
name|GTK_TABLE
argument_list|(
name|sizeentry
argument_list|)
argument_list|,
literal|0
argument_list|,
literal|4
argument_list|)
expr_stmt|;
name|gtk_table_set_col_spacing
argument_list|(
name|GTK_TABLE
argument_list|(
name|sizeentry
argument_list|)
argument_list|,
literal|2
argument_list|,
literal|4
argument_list|)
expr_stmt|;
name|gimp_size_entry_add_field
argument_list|(
name|GIMP_SIZE_ENTRY
argument_list|(
name|sizeentry
argument_list|)
argument_list|,
name|GTK_SPIN_BUTTON
argument_list|(
name|spinbutton
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|gtk_table_attach_defaults
argument_list|(
name|GTK_TABLE
argument_list|(
name|sizeentry
argument_list|)
argument_list|,
name|spinbutton
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|,
literal|0
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|spinbutton
argument_list|)
expr_stmt|;
name|gimp_size_entry_set_unit
argument_list|(
name|GIMP_SIZE_ENTRY
argument_list|(
name|sizeentry
argument_list|)
argument_list|,
operator|(
name|update_policy
operator|==
name|GIMP_SIZE_ENTRY_UPDATE_RESOLUTION
operator|)
operator|||
operator|(
name|menu_show_pixels
operator|==
name|FALSE
operator|)
condition|?
name|GIMP_UNIT_INCH
else|:
name|GIMP_UNIT_PIXEL
argument_list|)
expr_stmt|;
name|gimp_size_entry_set_resolution
argument_list|(
name|GIMP_SIZE_ENTRY
argument_list|(
name|sizeentry
argument_list|)
argument_list|,
literal|0
argument_list|,
name|xres
argument_list|,
name|TRUE
argument_list|)
expr_stmt|;
name|gimp_size_entry_set_resolution
argument_list|(
name|GIMP_SIZE_ENTRY
argument_list|(
name|sizeentry
argument_list|)
argument_list|,
literal|1
argument_list|,
name|yres
argument_list|,
name|TRUE
argument_list|)
expr_stmt|;
name|gimp_size_entry_set_refval_boundaries
argument_list|(
name|GIMP_SIZE_ENTRY
argument_list|(
name|sizeentry
argument_list|)
argument_list|,
literal|0
argument_list|,
name|lower_boundary_x
argument_list|,
name|upper_boundary_x
argument_list|)
expr_stmt|;
name|gimp_size_entry_set_refval_boundaries
argument_list|(
name|GIMP_SIZE_ENTRY
argument_list|(
name|sizeentry
argument_list|)
argument_list|,
literal|1
argument_list|,
name|lower_boundary_y
argument_list|,
name|upper_boundary_y
argument_list|)
expr_stmt|;
if|if
condition|(
name|menu_show_percent
condition|)
block|{
name|gimp_size_entry_set_size
argument_list|(
name|GIMP_SIZE_ENTRY
argument_list|(
name|sizeentry
argument_list|)
argument_list|,
literal|0
argument_list|,
name|xsize_0
argument_list|,
name|xsize_100
argument_list|)
expr_stmt|;
name|gimp_size_entry_set_size
argument_list|(
name|GIMP_SIZE_ENTRY
argument_list|(
name|sizeentry
argument_list|)
argument_list|,
literal|1
argument_list|,
name|ysize_0
argument_list|,
name|ysize_100
argument_list|)
expr_stmt|;
block|}
name|gimp_size_entry_set_refval
argument_list|(
name|GIMP_SIZE_ENTRY
argument_list|(
name|sizeentry
argument_list|)
argument_list|,
literal|0
argument_list|,
name|x
argument_list|)
expr_stmt|;
name|gimp_size_entry_set_refval
argument_list|(
name|GIMP_SIZE_ENTRY
argument_list|(
name|sizeentry
argument_list|)
argument_list|,
literal|1
argument_list|,
name|y
argument_list|)
expr_stmt|;
name|gimp_size_entry_attach_label
argument_list|(
name|GIMP_SIZE_ENTRY
argument_list|(
name|sizeentry
argument_list|)
argument_list|,
name|xlabel
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
literal|1.0
argument_list|)
expr_stmt|;
name|gimp_size_entry_attach_label
argument_list|(
name|GIMP_SIZE_ENTRY
argument_list|(
name|sizeentry
argument_list|)
argument_list|,
name|ylabel
argument_list|,
literal|1
argument_list|,
literal|0
argument_list|,
literal|1.0
argument_list|)
expr_stmt|;
name|chainbutton
operator|=
name|gimp_chain_button_new
argument_list|(
name|GIMP_CHAIN_RIGHT
argument_list|)
expr_stmt|;
if|if
condition|(
name|chainbutton_active
condition|)
name|gimp_chain_button_set_active
argument_list|(
name|GIMP_CHAIN_BUTTON
argument_list|(
name|chainbutton
argument_list|)
argument_list|,
name|TRUE
argument_list|)
expr_stmt|;
name|gtk_table_attach
argument_list|(
name|GTK_TABLE
argument_list|(
name|sizeentry
argument_list|)
argument_list|,
name|chainbutton
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|,
literal|0
argument_list|,
literal|2
argument_list|,
name|GTK_SHRINK
operator||
name|GTK_FILL
argument_list|,
name|GTK_EXPAND
operator||
name|GTK_FILL
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|chainbutton
argument_list|)
expr_stmt|;
name|gcd
operator|=
name|g_new
argument_list|(
name|GimpCoordinatesData
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|gcd
operator|->
name|chainbutton
operator|=
name|GIMP_CHAIN_BUTTON
argument_list|(
name|chainbutton
argument_list|)
expr_stmt|;
name|gcd
operator|->
name|chain_constrains_ratio
operator|=
name|chain_constrains_ratio
expr_stmt|;
name|gcd
operator|->
name|orig_x
operator|=
name|x
expr_stmt|;
name|gcd
operator|->
name|orig_y
operator|=
name|y
expr_stmt|;
name|gcd
operator|->
name|last_x
operator|=
name|x
expr_stmt|;
name|gcd
operator|->
name|last_y
operator|=
name|y
expr_stmt|;
name|gtk_signal_connect_object
argument_list|(
name|GTK_OBJECT
argument_list|(
name|sizeentry
argument_list|)
argument_list|,
literal|"destroy"
argument_list|,
name|GTK_SIGNAL_FUNC
argument_list|(
name|g_free
argument_list|)
argument_list|,
operator|(
name|GtkObject
operator|*
operator|)
name|gcd
argument_list|)
expr_stmt|;
name|gtk_signal_connect
argument_list|(
name|GTK_OBJECT
argument_list|(
name|sizeentry
argument_list|)
argument_list|,
literal|"value_changed"
argument_list|,
name|GTK_SIGNAL_FUNC
argument_list|(
name|gimp_coordinates_callback
argument_list|)
argument_list|,
name|gcd
argument_list|)
expr_stmt|;
name|gtk_object_set_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|sizeentry
argument_list|)
argument_list|,
literal|"chainbutton"
argument_list|,
name|chainbutton
argument_list|)
expr_stmt|;
return|return
name|sizeentry
return|;
block|}
end_function

begin_typedef
typedef|typedef
struct|struct
DECL|struct|__anon2b2be4590208
block|{
DECL|member|adjustment
name|GtkAdjustment
modifier|*
name|adjustment
decl_stmt|;
DECL|member|divided_adj
name|GtkAdjustment
modifier|*
name|divided_adj
decl_stmt|;
DECL|member|mem_size_unit
name|guint
name|mem_size_unit
decl_stmt|;
DECL|typedef|GimpMemSizeEntryData
block|}
name|GimpMemSizeEntryData
typedef|;
end_typedef

begin_function
specifier|static
name|void
DECL|function|gimp_mem_size_entry_callback (GtkAdjustment * adj,gpointer data)
name|gimp_mem_size_entry_callback
parameter_list|(
name|GtkAdjustment
modifier|*
name|adj
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpMemSizeEntryData
modifier|*
name|gmsed
decl_stmt|;
name|guint
name|new_value
decl_stmt|;
name|gmsed
operator|=
operator|(
name|GimpMemSizeEntryData
operator|*
operator|)
name|data
expr_stmt|;
name|new_value
operator|=
name|adj
operator|->
name|value
operator|*
name|gmsed
operator|->
name|mem_size_unit
expr_stmt|;
name|gtk_adjustment_set_value
argument_list|(
name|gmsed
operator|->
name|adjustment
argument_list|,
name|new_value
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_mem_size_unit_callback (GtkWidget * widget,gpointer data)
name|gimp_mem_size_unit_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpMemSizeEntryData
modifier|*
name|gmsed
decl_stmt|;
name|guint
name|divided_mem_size
decl_stmt|;
name|guint
name|new_unit
decl_stmt|;
name|gmsed
operator|=
operator|(
name|GimpMemSizeEntryData
operator|*
operator|)
name|data
expr_stmt|;
name|new_unit
operator|=
operator|(
name|guint
operator|)
name|gtk_object_get_user_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|widget
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|new_unit
operator|&&
name|new_unit
operator|!=
name|gmsed
operator|->
name|mem_size_unit
condition|)
block|{
name|divided_mem_size
operator|=
name|gmsed
operator|->
name|adjustment
operator|->
name|value
operator|/
name|new_unit
expr_stmt|;
name|gmsed
operator|->
name|mem_size_unit
operator|=
name|new_unit
expr_stmt|;
name|gtk_adjustment_set_value
argument_list|(
name|GTK_ADJUSTMENT
argument_list|(
name|gmsed
operator|->
name|divided_adj
argument_list|)
argument_list|,
name|divided_mem_size
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_comment
comment|/**  * gimp_mem_size_entry_new:  * @adjustment: The adjustment containing the memsize and it's limits.  *  * Returns: A #GtkHBox with a #GtkSpinButton and a #GtkOptionMenu.  */
end_comment

begin_function
name|GtkWidget
modifier|*
DECL|function|gimp_mem_size_entry_new (GtkAdjustment * adjustment)
name|gimp_mem_size_entry_new
parameter_list|(
name|GtkAdjustment
modifier|*
name|adjustment
parameter_list|)
block|{
name|GtkWidget
modifier|*
name|hbox
decl_stmt|;
name|GtkObject
modifier|*
name|divided_adj
decl_stmt|;
name|GtkWidget
modifier|*
name|spinbutton
decl_stmt|;
name|GtkWidget
modifier|*
name|optionmenu
decl_stmt|;
name|GimpMemSizeEntryData
modifier|*
name|gmsed
decl_stmt|;
name|guint
name|mem_size_unit
init|=
literal|1
decl_stmt|;
name|guint
name|divided_mem_size
decl_stmt|;
name|gint
name|i
decl_stmt|;
name|gmsed
operator|=
name|g_new
argument_list|(
name|GimpMemSizeEntryData
argument_list|,
literal|1
argument_list|)
expr_stmt|;
for|for
control|(
name|i
operator|=
literal|0
init|;
name|i
operator|<
literal|3
condition|;
name|i
operator|++
control|)
block|{
if|if
condition|(
operator|(
name|gint
operator|)
name|adjustment
operator|->
name|value
operator|%
operator|(
name|mem_size_unit
operator|*
literal|1024
operator|)
operator|!=
literal|0
condition|)
break|break;
name|mem_size_unit
operator|*=
literal|1024
expr_stmt|;
block|}
name|divided_mem_size
operator|=
name|adjustment
operator|->
name|value
operator|/
name|mem_size_unit
expr_stmt|;
name|hbox
operator|=
name|gtk_hbox_new
argument_list|(
name|FALSE
argument_list|,
literal|2
argument_list|)
expr_stmt|;
name|spinbutton
operator|=
name|gimp_spin_button_new
argument_list|(
operator|&
name|divided_adj
argument_list|,
name|divided_mem_size
argument_list|,
literal|0.0
argument_list|,
operator|(
literal|4096.0
operator|*
literal|1024
operator|*
literal|1024
operator|-
literal|1
operator|)
argument_list|,
literal|1.0
argument_list|,
literal|16.0
argument_list|,
literal|0.0
argument_list|,
literal|1.0
argument_list|,
literal|0.0
argument_list|)
expr_stmt|;
name|gtk_signal_connect
argument_list|(
name|GTK_OBJECT
argument_list|(
name|divided_adj
argument_list|)
argument_list|,
literal|"value_changed"
argument_list|,
name|GTK_SIGNAL_FUNC
argument_list|(
name|gimp_mem_size_entry_callback
argument_list|)
argument_list|,
name|gmsed
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|hbox
argument_list|)
argument_list|,
name|spinbutton
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|spinbutton
argument_list|)
expr_stmt|;
name|optionmenu
operator|=
name|gimp_option_menu_new2
argument_list|(
name|FALSE
argument_list|,
name|gimp_mem_size_unit_callback
argument_list|,
name|gmsed
argument_list|,
operator|(
name|gpointer
operator|)
name|mem_size_unit
argument_list|,
name|_
argument_list|(
literal|"Bytes"
argument_list|)
argument_list|,
operator|(
name|gpointer
operator|)
literal|1
argument_list|,
name|NULL
argument_list|,
name|_
argument_list|(
literal|"KiloBytes"
argument_list|)
argument_list|,
operator|(
name|gpointer
operator|)
literal|1024
argument_list|,
name|NULL
argument_list|,
name|_
argument_list|(
literal|"MegaBytes"
argument_list|)
argument_list|,
call|(
name|gpointer
call|)
argument_list|(
literal|1024
operator|*
literal|1024
argument_list|)
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|hbox
argument_list|)
argument_list|,
name|optionmenu
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|optionmenu
argument_list|)
expr_stmt|;
name|gtk_signal_connect_object
argument_list|(
name|GTK_OBJECT
argument_list|(
name|hbox
argument_list|)
argument_list|,
literal|"destroy"
argument_list|,
name|GTK_SIGNAL_FUNC
argument_list|(
name|gtk_object_unref
argument_list|)
argument_list|,
name|GTK_OBJECT
argument_list|(
name|adjustment
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_signal_connect_object
argument_list|(
name|GTK_OBJECT
argument_list|(
name|hbox
argument_list|)
argument_list|,
literal|"destroy"
argument_list|,
name|GTK_SIGNAL_FUNC
argument_list|(
name|g_free
argument_list|)
argument_list|,
operator|(
name|GtkObject
operator|*
operator|)
name|gmsed
argument_list|)
expr_stmt|;
name|gmsed
operator|->
name|adjustment
operator|=
name|adjustment
expr_stmt|;
name|gmsed
operator|->
name|divided_adj
operator|=
name|GTK_ADJUSTMENT
argument_list|(
name|divided_adj
argument_list|)
expr_stmt|;
name|gmsed
operator|->
name|mem_size_unit
operator|=
name|mem_size_unit
expr_stmt|;
name|gtk_object_set_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|hbox
argument_list|)
argument_list|,
literal|"spinbutton"
argument_list|,
name|spinbutton
argument_list|)
expr_stmt|;
name|gtk_object_set_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|hbox
argument_list|)
argument_list|,
literal|"optionmenu"
argument_list|,
name|optionmenu
argument_list|)
expr_stmt|;
return|return
name|hbox
return|;
block|}
end_function

begin_comment
comment|/**  * gimp_pixmap_button_new:  * @xpm_data: The XPM data which will be passed to gimp_pixmap_new().  * @text: An optional text which will appear right of the pixmap.  *  * Returns: A #GtkButton with a #GimpPixmap and an optional #GtkLabel.  *  */
end_comment

begin_function
name|GtkWidget
modifier|*
DECL|function|gimp_pixmap_button_new (gchar ** xpm_data,gchar * text)
name|gimp_pixmap_button_new
parameter_list|(
name|gchar
modifier|*
modifier|*
name|xpm_data
parameter_list|,
name|gchar
modifier|*
name|text
parameter_list|)
block|{
name|GtkWidget
modifier|*
name|button
decl_stmt|;
name|GtkWidget
modifier|*
name|pixmap
decl_stmt|;
name|button
operator|=
name|gtk_button_new
argument_list|()
expr_stmt|;
name|pixmap
operator|=
name|gimp_pixmap_new
argument_list|(
name|xpm_data
argument_list|)
expr_stmt|;
if|if
condition|(
name|text
condition|)
block|{
name|GtkWidget
modifier|*
name|abox
decl_stmt|;
name|GtkWidget
modifier|*
name|hbox
decl_stmt|;
name|GtkWidget
modifier|*
name|label
decl_stmt|;
name|abox
operator|=
name|gtk_alignment_new
argument_list|(
literal|0.5
argument_list|,
literal|0.5
argument_list|,
literal|0.0
argument_list|,
literal|0.0
argument_list|)
expr_stmt|;
name|gtk_container_add
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|button
argument_list|)
argument_list|,
name|abox
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|abox
argument_list|)
expr_stmt|;
name|hbox
operator|=
name|gtk_hbox_new
argument_list|(
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_container_add
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|abox
argument_list|)
argument_list|,
name|hbox
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|hbox
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|hbox
argument_list|)
argument_list|,
name|pixmap
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|4
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|pixmap
argument_list|)
expr_stmt|;
name|label
operator|=
name|gtk_label_new
argument_list|(
name|text
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|hbox
argument_list|)
argument_list|,
name|label
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|4
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|label
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|gtk_container_add
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|button
argument_list|)
argument_list|,
name|pixmap
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|pixmap
argument_list|)
expr_stmt|;
block|}
return|return
name|button
return|;
block|}
end_function

begin_comment
comment|/*  *  Standard Callbacks  */
end_comment

begin_comment
comment|/**  * gimp_toggle_button_sensitive_update:  * @toggle_button: The #GtkToggleButton the "set_sensitive" and  *                 "inverse_sensitive" lists are attached to.  *  * If you attached a pointer to a #GtkWidget with gtk_object_set_data() and  * the "set_sensitive" key to the #GtkToggleButton, the sensitive state of  * the attached widget will be set according to the toggle button's  * "active" state.  *  * You can attach an arbitrary list of widgets by attaching another  * "set_sensitive" data pointer to the first widget (and so on...).  *  * This function can also set the sensitive state according to the toggle  * button's inverse "active" state by attaching widgets with the  * "inverse_sensitive" key.  *  */
end_comment

begin_function
name|void
DECL|function|gimp_toggle_button_sensitive_update (GtkToggleButton * toggle_button)
name|gimp_toggle_button_sensitive_update
parameter_list|(
name|GtkToggleButton
modifier|*
name|toggle_button
parameter_list|)
block|{
name|GtkWidget
modifier|*
name|set_sensitive
decl_stmt|;
name|gboolean
name|active
decl_stmt|;
name|active
operator|=
name|gtk_toggle_button_get_active
argument_list|(
name|toggle_button
argument_list|)
expr_stmt|;
name|set_sensitive
operator|=
name|gtk_object_get_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|toggle_button
argument_list|)
argument_list|,
literal|"set_sensitive"
argument_list|)
expr_stmt|;
while|while
condition|(
name|set_sensitive
condition|)
block|{
name|gtk_widget_set_sensitive
argument_list|(
name|set_sensitive
argument_list|,
name|active
argument_list|)
expr_stmt|;
name|set_sensitive
operator|=
name|gtk_object_get_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|set_sensitive
argument_list|)
argument_list|,
literal|"set_sensitive"
argument_list|)
expr_stmt|;
block|}
name|set_sensitive
operator|=
name|gtk_object_get_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|toggle_button
argument_list|)
argument_list|,
literal|"inverse_sensitive"
argument_list|)
expr_stmt|;
while|while
condition|(
name|set_sensitive
condition|)
block|{
name|gtk_widget_set_sensitive
argument_list|(
name|set_sensitive
argument_list|,
operator|!
name|active
argument_list|)
expr_stmt|;
name|set_sensitive
operator|=
name|gtk_object_get_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|set_sensitive
argument_list|)
argument_list|,
literal|"inverse_sensitive"
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_comment
comment|/**  * gimp_toggle_button_update:  * @widget: A #GtkToggleButton.  * @data: A pointer to a #gint variable which will store the value of  *        gtk_toggle_button_get_active().  *  * Note that this function calls gimp_toggle_button_sensitive_update().  *  */
end_comment

begin_function
name|void
DECL|function|gimp_toggle_button_update (GtkWidget * widget,gpointer data)
name|gimp_toggle_button_update
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|gint
modifier|*
name|toggle_val
decl_stmt|;
name|toggle_val
operator|=
operator|(
name|gint
operator|*
operator|)
name|data
expr_stmt|;
if|if
condition|(
name|gtk_toggle_button_get_active
argument_list|(
name|GTK_TOGGLE_BUTTON
argument_list|(
name|widget
argument_list|)
argument_list|)
condition|)
operator|*
name|toggle_val
operator|=
name|TRUE
expr_stmt|;
else|else
operator|*
name|toggle_val
operator|=
name|FALSE
expr_stmt|;
name|gimp_toggle_button_sensitive_update
argument_list|(
name|GTK_TOGGLE_BUTTON
argument_list|(
name|widget
argument_list|)
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/**  * gimp_radio_button_update:  * @widget: A #GtkRadioButton.  * @data: A pointer to a #gint variable which will store the value of  *        (#gint) gtk_object_get_user_data().  *  * Note that this function calls gimp_toggle_button_sensitive_update().  *  */
end_comment

begin_function
name|void
DECL|function|gimp_radio_button_update (GtkWidget * widget,gpointer data)
name|gimp_radio_button_update
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|gint
modifier|*
name|toggle_val
decl_stmt|;
if|if
condition|(
name|gtk_toggle_button_get_active
argument_list|(
name|GTK_TOGGLE_BUTTON
argument_list|(
name|widget
argument_list|)
argument_list|)
condition|)
block|{
name|toggle_val
operator|=
operator|(
name|gint
operator|*
operator|)
name|data
expr_stmt|;
operator|*
name|toggle_val
operator|=
operator|(
name|gint
operator|)
name|gtk_object_get_user_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|widget
argument_list|)
argument_list|)
expr_stmt|;
block|}
name|gimp_toggle_button_sensitive_update
argument_list|(
name|GTK_TOGGLE_BUTTON
argument_list|(
name|widget
argument_list|)
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/**  * gimp_menu_item_update:  * @widget: A #GtkMenuItem.  * @data: A pointer to a #gint variable which will store the value of  *        (#gint) gtk_object_get_user_data().  *  */
end_comment

begin_function
name|void
DECL|function|gimp_menu_item_update (GtkWidget * widget,gpointer data)
name|gimp_menu_item_update
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|gint
modifier|*
name|item_val
decl_stmt|;
name|item_val
operator|=
operator|(
name|gint
operator|*
operator|)
name|data
expr_stmt|;
operator|*
name|item_val
operator|=
operator|(
name|gint
operator|)
name|gtk_object_get_user_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|widget
argument_list|)
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/**  * gimp_int_adjustment_update:  * @adjustment: A #GtkAdjustment.  * @data: A pointer to a #gint variable which will store the adjustment's  *        value.  *  * Note that the #GtkAdjustment's value (which is a #gfloat) will be rounded  * with (#gint) (value + 0.5).  *  */
end_comment

begin_function
name|void
DECL|function|gimp_int_adjustment_update (GtkAdjustment * adjustment,gpointer data)
name|gimp_int_adjustment_update
parameter_list|(
name|GtkAdjustment
modifier|*
name|adjustment
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|gint
modifier|*
name|val
decl_stmt|;
name|val
operator|=
operator|(
name|gint
operator|*
operator|)
name|data
expr_stmt|;
operator|*
name|val
operator|=
call|(
name|gint
call|)
argument_list|(
name|adjustment
operator|->
name|value
operator|+
literal|0.5
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/**  * gimp_uint_adjustment_update:  * @adjustment: A #GtkAdjustment.  * @data: A pointer to a #guint variable which will store the adjustment's  *        value.  *  * Note that the #GtkAdjustment's value (which is a #gfloat) will be rounded  * with (#guint) (value + 0.5).  *  */
end_comment

begin_function
name|void
DECL|function|gimp_uint_adjustment_update (GtkAdjustment * adjustment,gpointer data)
name|gimp_uint_adjustment_update
parameter_list|(
name|GtkAdjustment
modifier|*
name|adjustment
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|guint
modifier|*
name|val
decl_stmt|;
name|val
operator|=
operator|(
name|guint
operator|*
operator|)
name|data
expr_stmt|;
operator|*
name|val
operator|=
call|(
name|guint
call|)
argument_list|(
name|adjustment
operator|->
name|value
operator|+
literal|0.5
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/**  * gimp_float_adjustment_update:  * @adjustment: A #GtkAdjustment.  * @data: A pointer to a #gfloat varaiable which willl store the adjustment's  *        value.  *  */
end_comment

begin_function
name|void
DECL|function|gimp_float_adjustment_update (GtkAdjustment * adjustment,gpointer data)
name|gimp_float_adjustment_update
parameter_list|(
name|GtkAdjustment
modifier|*
name|adjustment
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|gfloat
modifier|*
name|val
decl_stmt|;
name|val
operator|=
operator|(
name|gfloat
operator|*
operator|)
name|data
expr_stmt|;
operator|*
name|val
operator|=
name|adjustment
operator|->
name|value
expr_stmt|;
block|}
end_function

begin_comment
comment|/**  * gimp_double_adjustment_update:  * @adjustment: A #GtkAdjustment.  * @data: A pointer to a #gdouble variable which will store the adjustment's  *        value.  *  */
end_comment

begin_function
name|void
DECL|function|gimp_double_adjustment_update (GtkAdjustment * adjustment,gpointer data)
name|gimp_double_adjustment_update
parameter_list|(
name|GtkAdjustment
modifier|*
name|adjustment
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|gdouble
modifier|*
name|val
decl_stmt|;
name|val
operator|=
operator|(
name|gdouble
operator|*
operator|)
name|data
expr_stmt|;
operator|*
name|val
operator|=
name|adjustment
operator|->
name|value
expr_stmt|;
block|}
end_function

begin_comment
comment|/**  * gimp_unit_menu_update:  * @widget: A #GimpUnitMenu.  * @data: A pointer to a #GimpUnit variable which will store the unit menu's  *        value.  *  * This callback can set the number of decimal digits of an arbitrary number  * of #GtkSpinButton's. To use this functionality, attach the spinbuttons  * as list of data pointers attached with gtk_object_set_data() with the  * "set_digits" key.  *  * See gimp_toggle_button_sensitive_update() for a description of how  * to set up the list.  *  */
end_comment

begin_function
name|void
DECL|function|gimp_unit_menu_update (GtkWidget * widget,gpointer data)
name|gimp_unit_menu_update
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpUnit
modifier|*
name|val
decl_stmt|;
name|GtkWidget
modifier|*
name|spinbutton
decl_stmt|;
name|gint
name|digits
decl_stmt|;
name|val
operator|=
operator|(
name|GimpUnit
operator|*
operator|)
name|data
expr_stmt|;
operator|*
name|val
operator|=
name|gimp_unit_menu_get_unit
argument_list|(
name|GIMP_UNIT_MENU
argument_list|(
name|widget
argument_list|)
argument_list|)
expr_stmt|;
name|digits
operator|=
operator|(
operator|(
operator|*
name|val
operator|==
name|GIMP_UNIT_PIXEL
operator|)
condition|?
literal|0
else|:
operator|(
operator|(
operator|*
name|val
operator|==
name|GIMP_UNIT_PERCENT
operator|)
condition|?
literal|2
else|:
operator|(
name|MIN
argument_list|(
literal|6
argument_list|,
name|MAX
argument_list|(
literal|3
argument_list|,
name|gimp_unit_get_digits
argument_list|(
operator|*
name|val
argument_list|)
argument_list|)
argument_list|)
operator|)
operator|)
operator|)
expr_stmt|;
name|spinbutton
operator|=
name|gtk_object_get_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|widget
argument_list|)
argument_list|,
literal|"set_digits"
argument_list|)
expr_stmt|;
while|while
condition|(
name|spinbutton
condition|)
block|{
name|gtk_spin_button_set_digits
argument_list|(
name|GTK_SPIN_BUTTON
argument_list|(
name|spinbutton
argument_list|)
argument_list|,
name|digits
argument_list|)
expr_stmt|;
name|spinbutton
operator|=
name|gtk_object_get_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|spinbutton
argument_list|)
argument_list|,
literal|"set_digits"
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_comment
comment|/*  *  Helper Functions  */
end_comment

begin_comment
comment|/**  * gimp_table_attach_aligned:  * @table: The #GtkTable the widgets will be attached to.  * @column: The column to start with.  * @row: The row to attach the eidgets.  * @label_text: The text for the #GtkLabel which will be attached left of the  *              widget.  * @xalign: The horizontal alignment of the #GtkLabel.  * @yalign: The vertival alignment of the #GtkLabel.  * @widget: The #GtkWidget to attach right of the label.  * @colspan: The number of columns the widget will use.  * @left_align: #TRUE if the widget should be left-aligned.  *  * Note that the @label_text can be #NULL and that the widget will be attached  * starting at (@column + 1) in this case, too.  *  */
end_comment

begin_function
name|void
DECL|function|gimp_table_attach_aligned (GtkTable * table,gint column,gint row,gchar * label_text,gfloat xalign,gfloat yalign,GtkWidget * widget,gint colspan,gboolean left_align)
name|gimp_table_attach_aligned
parameter_list|(
name|GtkTable
modifier|*
name|table
parameter_list|,
name|gint
name|column
parameter_list|,
name|gint
name|row
parameter_list|,
name|gchar
modifier|*
name|label_text
parameter_list|,
name|gfloat
name|xalign
parameter_list|,
name|gfloat
name|yalign
parameter_list|,
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gint
name|colspan
parameter_list|,
name|gboolean
name|left_align
parameter_list|)
block|{
if|if
condition|(
name|label_text
condition|)
block|{
name|GtkWidget
modifier|*
name|label
decl_stmt|;
name|label
operator|=
name|gtk_label_new
argument_list|(
name|label_text
argument_list|)
expr_stmt|;
name|gtk_misc_set_alignment
argument_list|(
name|GTK_MISC
argument_list|(
name|label
argument_list|)
argument_list|,
name|xalign
argument_list|,
name|yalign
argument_list|)
expr_stmt|;
name|gtk_label_set_justify
argument_list|(
name|GTK_LABEL
argument_list|(
name|label
argument_list|)
argument_list|,
name|GTK_JUSTIFY_RIGHT
argument_list|)
expr_stmt|;
name|gtk_table_attach
argument_list|(
name|table
argument_list|,
name|label
argument_list|,
name|column
argument_list|,
name|column
operator|+
literal|1
argument_list|,
name|row
argument_list|,
name|row
operator|+
literal|1
argument_list|,
name|GTK_FILL
argument_list|,
name|GTK_FILL
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|label
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|left_align
condition|)
block|{
name|GtkWidget
modifier|*
name|alignment
decl_stmt|;
name|alignment
operator|=
name|gtk_alignment_new
argument_list|(
literal|0.0
argument_list|,
literal|0.5
argument_list|,
literal|0.0
argument_list|,
literal|0.0
argument_list|)
expr_stmt|;
name|gtk_container_add
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|alignment
argument_list|)
argument_list|,
name|widget
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|widget
argument_list|)
expr_stmt|;
name|widget
operator|=
name|alignment
expr_stmt|;
block|}
name|gtk_table_attach
argument_list|(
name|table
argument_list|,
name|widget
argument_list|,
name|column
operator|+
literal|1
argument_list|,
name|column
operator|+
literal|1
operator|+
name|colspan
argument_list|,
name|row
argument_list|,
name|row
operator|+
literal|1
argument_list|,
name|GTK_EXPAND
operator||
name|GTK_FILL
argument_list|,
name|GTK_EXPAND
operator||
name|GTK_FILL
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|widget
argument_list|)
expr_stmt|;
block|}
end_function

end_unit

