begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* The GIMP -- an image manipulation program  * Copyright (C) 1995 Spencer Kimball and Peter Mattis  *  * gimpenumcombobox.c  * Copyright (C) 2004  Sven Neumann<sven@gimp.org>  *  * This program is free software; you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 2 of the License, or  * (at your option) any later version.  *  * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *  * You should have received a copy of the GNU General Public License  * along with this program; if not, write to the Free Software  * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  */
end_comment

begin_include
include|#
directive|include
file|"config.h"
end_include

begin_include
include|#
directive|include
file|<gtk/gtk.h>
end_include

begin_include
include|#
directive|include
file|"libgimpwidgets/gimpwidgets.h"
end_include

begin_include
include|#
directive|include
file|"widgets-types.h"
end_include

begin_include
include|#
directive|include
file|"gimpenumcombobox.h"
end_include

begin_include
include|#
directive|include
file|"gimpenumstore.h"
end_include

begin_include
include|#
directive|include
file|"gimp-intl.h"
end_include

begin_function
name|GType
DECL|function|gimp_enum_combo_box_get_type (void)
name|gimp_enum_combo_box_get_type
parameter_list|(
name|void
parameter_list|)
block|{
specifier|static
name|GType
name|enum_combo_box_type
init|=
literal|0
decl_stmt|;
if|if
condition|(
operator|!
name|enum_combo_box_type
condition|)
block|{
specifier|static
specifier|const
name|GTypeInfo
name|enum_combo_box_info
init|=
block|{
sizeof|sizeof
argument_list|(
name|GimpEnumComboBoxClass
argument_list|)
block|,
name|NULL
block|,
comment|/* base_init      */
name|NULL
block|,
comment|/* base_finalize  */
name|NULL
block|,
comment|/* class_init     */
name|NULL
block|,
comment|/* class_finalize */
name|NULL
block|,
comment|/* class_data     */
sizeof|sizeof
argument_list|(
name|GimpEnumComboBox
argument_list|)
block|,
literal|0
block|,
comment|/* n_preallocs    */
name|NULL
comment|/* instance_init  */
block|}
decl_stmt|;
name|enum_combo_box_type
operator|=
name|g_type_register_static
argument_list|(
name|GTK_TYPE_COMBO_BOX
argument_list|,
literal|"GimpEnumComboBox"
argument_list|,
operator|&
name|enum_combo_box_info
argument_list|,
literal|0
argument_list|)
expr_stmt|;
block|}
return|return
name|enum_combo_box_type
return|;
block|}
end_function

begin_comment
comment|/**  * gimp_enum_combo_box_new:  * @enum_type: the #GType of an enum.  *  * Creates a new #GtkComboBox using the #GimpEnumStore. The enum needs  * to be registered to the type system and should have translatable  * value names.  *  * Return value: a new #GimpEnumComboBox.  **/
end_comment

begin_function
name|GtkWidget
modifier|*
DECL|function|gimp_enum_combo_box_new (GType enum_type)
name|gimp_enum_combo_box_new
parameter_list|(
name|GType
name|enum_type
parameter_list|)
block|{
name|GtkListStore
modifier|*
name|store
decl_stmt|;
name|GtkWidget
modifier|*
name|combo_box
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|G_TYPE_IS_ENUM
argument_list|(
name|enum_type
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|store
operator|=
name|gimp_enum_store_new
argument_list|(
name|enum_type
argument_list|)
expr_stmt|;
name|combo_box
operator|=
name|gimp_enum_combo_box_new_with_model
argument_list|(
name|GIMP_ENUM_STORE
argument_list|(
name|store
argument_list|)
argument_list|)
expr_stmt|;
name|g_object_unref
argument_list|(
name|store
argument_list|)
expr_stmt|;
return|return
name|combo_box
return|;
block|}
end_function

begin_function
name|GtkWidget
modifier|*
DECL|function|gimp_enum_combo_box_new_with_model (GimpEnumStore * enum_store)
name|gimp_enum_combo_box_new_with_model
parameter_list|(
name|GimpEnumStore
modifier|*
name|enum_store
parameter_list|)
block|{
name|GtkWidget
modifier|*
name|combo_box
decl_stmt|;
name|GtkCellRenderer
modifier|*
name|cell
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_ENUM_STORE
argument_list|(
name|enum_store
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|combo_box
operator|=
name|g_object_new
argument_list|(
name|GIMP_TYPE_ENUM_COMBO_BOX
argument_list|,
literal|"model"
argument_list|,
name|enum_store
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|cell
operator|=
name|gtk_cell_renderer_pixbuf_new
argument_list|()
expr_stmt|;
name|gtk_cell_layout_pack_start
argument_list|(
name|GTK_CELL_LAYOUT
argument_list|(
name|combo_box
argument_list|)
argument_list|,
name|cell
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gtk_cell_layout_set_attributes
argument_list|(
name|GTK_CELL_LAYOUT
argument_list|(
name|combo_box
argument_list|)
argument_list|,
name|cell
argument_list|,
literal|"pixbuf"
argument_list|,
name|GIMP_ENUM_STORE_ICON
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|cell
operator|=
name|gtk_cell_renderer_text_new
argument_list|()
expr_stmt|;
name|gtk_cell_layout_pack_start
argument_list|(
name|GTK_CELL_LAYOUT
argument_list|(
name|combo_box
argument_list|)
argument_list|,
name|cell
argument_list|,
name|TRUE
argument_list|)
expr_stmt|;
name|gtk_cell_layout_set_attributes
argument_list|(
name|GTK_CELL_LAYOUT
argument_list|(
name|combo_box
argument_list|)
argument_list|,
name|cell
argument_list|,
literal|"text"
argument_list|,
name|GIMP_ENUM_STORE_LABEL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
return|return
name|combo_box
return|;
block|}
end_function

begin_function
name|gboolean
DECL|function|gimp_enum_combo_box_set_active (GimpEnumComboBox * combo_box,gint value)
name|gimp_enum_combo_box_set_active
parameter_list|(
name|GimpEnumComboBox
modifier|*
name|combo_box
parameter_list|,
name|gint
name|value
parameter_list|)
block|{
name|GtkTreeModel
modifier|*
name|model
decl_stmt|;
name|GtkTreeIter
name|iter
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_ENUM_COMBO_BOX
argument_list|(
name|combo_box
argument_list|)
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|model
operator|=
name|gtk_combo_box_get_model
argument_list|(
name|GTK_COMBO_BOX
argument_list|(
name|combo_box
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|gimp_enum_store_lookup_by_value
argument_list|(
name|model
argument_list|,
name|value
argument_list|,
operator|&
name|iter
argument_list|)
condition|)
block|{
name|gtk_combo_box_set_active_iter
argument_list|(
name|GTK_COMBO_BOX
argument_list|(
name|combo_box
argument_list|)
argument_list|,
operator|&
name|iter
argument_list|)
expr_stmt|;
return|return
name|TRUE
return|;
block|}
return|return
name|FALSE
return|;
block|}
end_function

begin_function
name|gboolean
DECL|function|gimp_enum_combo_box_get_active (GimpEnumComboBox * combo_box,gint * value)
name|gimp_enum_combo_box_get_active
parameter_list|(
name|GimpEnumComboBox
modifier|*
name|combo_box
parameter_list|,
name|gint
modifier|*
name|value
parameter_list|)
block|{
name|GtkTreeIter
name|iter
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_ENUM_COMBO_BOX
argument_list|(
name|combo_box
argument_list|)
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
if|if
condition|(
name|gtk_combo_box_get_active_iter
argument_list|(
name|GTK_COMBO_BOX
argument_list|(
name|combo_box
argument_list|)
argument_list|,
operator|&
name|iter
argument_list|)
condition|)
block|{
name|gtk_tree_model_get
argument_list|(
name|gtk_combo_box_get_model
argument_list|(
name|GTK_COMBO_BOX
argument_list|(
name|combo_box
argument_list|)
argument_list|)
argument_list|,
operator|&
name|iter
argument_list|,
name|GIMP_ENUM_STORE_VALUE
argument_list|,
name|value
argument_list|,
operator|-
literal|1
argument_list|)
expr_stmt|;
return|return
name|TRUE
return|;
block|}
return|return
name|FALSE
return|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_enum_combo_box_set_stock_prefix (GimpEnumComboBox * combo_box,const gchar * stock_prefix)
name|gimp_enum_combo_box_set_stock_prefix
parameter_list|(
name|GimpEnumComboBox
modifier|*
name|combo_box
parameter_list|,
specifier|const
name|gchar
modifier|*
name|stock_prefix
parameter_list|)
block|{
name|GtkTreeModel
modifier|*
name|model
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_ENUM_COMBO_BOX
argument_list|(
name|combo_box
argument_list|)
argument_list|)
expr_stmt|;
name|model
operator|=
name|gtk_combo_box_get_model
argument_list|(
name|GTK_COMBO_BOX
argument_list|(
name|combo_box
argument_list|)
argument_list|)
expr_stmt|;
name|gimp_enum_store_set_icons
argument_list|(
name|GIMP_ENUM_STORE
argument_list|(
name|model
argument_list|)
argument_list|,
name|GTK_WIDGET
argument_list|(
name|combo_box
argument_list|)
argument_list|,
name|stock_prefix
argument_list|,
name|GTK_ICON_SIZE_MENU
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/*  This is a kludge to allow to work around bug #135875  */
end_comment

begin_function
name|void
DECL|function|gimp_enum_combo_box_set_visible (GimpEnumComboBox * combo_box,GtkTreeModelFilterVisibleFunc func,gpointer data)
name|gimp_enum_combo_box_set_visible
parameter_list|(
name|GimpEnumComboBox
modifier|*
name|combo_box
parameter_list|,
name|GtkTreeModelFilterVisibleFunc
name|func
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GtkTreeModel
modifier|*
name|model
decl_stmt|;
name|GtkTreeModelFilter
modifier|*
name|filter
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_ENUM_COMBO_BOX
argument_list|(
name|combo_box
argument_list|)
argument_list|)
expr_stmt|;
name|model
operator|=
name|gtk_combo_box_get_model
argument_list|(
name|GTK_COMBO_BOX
argument_list|(
name|combo_box
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|GTK_IS_TREE_MODEL_FILTER
argument_list|(
name|model
argument_list|)
condition|)
block|{
name|filter
operator|=
name|GTK_TREE_MODEL_FILTER
argument_list|(
name|model
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|filter
operator|=
name|GTK_TREE_MODEL_FILTER
argument_list|(
name|gtk_tree_model_filter_new
argument_list|(
name|model
argument_list|,
name|NULL
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_combo_box_set_model
argument_list|(
name|GTK_COMBO_BOX
argument_list|(
name|combo_box
argument_list|)
argument_list|,
name|GTK_TREE_MODEL
argument_list|(
name|filter
argument_list|)
argument_list|)
expr_stmt|;
name|g_object_unref
argument_list|(
name|filter
argument_list|)
expr_stmt|;
block|}
name|gtk_tree_model_filter_set_visible_func
argument_list|(
name|filter
argument_list|,
name|func
argument_list|,
name|data
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|gtk_tree_model_filter_refilter
argument_list|(
name|filter
argument_list|)
expr_stmt|;
block|}
end_function

end_unit

