begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* LIBGIMP - The GIMP Library   * Copyright (C) 1995-1997 Peter Mattis and Spencer Kimball   *  * gimpoffsetarea.c  * Copyright (C) 2001  Sven Neumann<sven@gimp.org>  *  * This library is free software; you can redistribute it and/or  * modify it under the terms of the GNU Lesser General Public  * License as published by the Free Software Foundation; either  * version 2 of the License, or (at your option) any later version.  *   * This library is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU  * Lesser General Public License for more details.  *  * You should have received a copy of the GNU Lesser General Public  * License along with this library; if not, write to the  * Free Software Foundation, Inc., 59 Temple Place - Suite 330,  * Boston, MA 02111-1307, USA.  */
end_comment

begin_include
include|#
directive|include
file|<stdio.h>
end_include

begin_include
include|#
directive|include
file|<gtk/gtk.h>
end_include

begin_include
include|#
directive|include
file|"gimpwidgetstypes.h"
end_include

begin_include
include|#
directive|include
file|"gimpoffsetarea.h"
end_include

begin_define
DECL|macro|DRAWING_AREA_SIZE
define|#
directive|define
name|DRAWING_AREA_SIZE
value|200
end_define

begin_enum
enum|enum
DECL|enum|__anon2b30f7300103
block|{
DECL|enumerator|OFFSETS_CHANGED
name|OFFSETS_CHANGED
block|,
DECL|enumerator|LAST_SIGNAL
name|LAST_SIGNAL
block|}
enum|;
end_enum

begin_function_decl
specifier|static
name|void
name|gimp_offset_area_class_init
parameter_list|(
name|GimpOffsetAreaClass
modifier|*
name|klass
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_offset_area_init
parameter_list|(
name|GimpOffsetArea
modifier|*
name|offset_area
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_offset_area_resize
parameter_list|(
name|GimpOffsetArea
modifier|*
name|offset_area
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|gboolean
name|gimp_offset_area_event
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|GdkEvent
modifier|*
name|event
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_offset_area_draw
parameter_list|(
name|GimpOffsetArea
modifier|*
name|offset_area
parameter_list|)
function_decl|;
end_function_decl

begin_decl_stmt
DECL|variable|gimp_offset_area_signals
specifier|static
name|guint
name|gimp_offset_area_signals
index|[
name|LAST_SIGNAL
index|]
init|=
block|{
literal|0
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|parent_class
specifier|static
name|GtkDrawingAreaClass
modifier|*
name|parent_class
init|=
name|NULL
decl_stmt|;
end_decl_stmt

begin_function
name|GType
DECL|function|gimp_offset_area_get_type (void)
name|gimp_offset_area_get_type
parameter_list|(
name|void
parameter_list|)
block|{
specifier|static
name|GType
name|offset_area_type
init|=
literal|0
decl_stmt|;
if|if
condition|(
operator|!
name|offset_area_type
condition|)
block|{
specifier|static
specifier|const
name|GTypeInfo
name|offset_area_info
init|=
block|{
sizeof|sizeof
argument_list|(
name|GimpOffsetAreaClass
argument_list|)
block|,
operator|(
name|GBaseInitFunc
operator|)
name|NULL
block|,
operator|(
name|GBaseFinalizeFunc
operator|)
name|NULL
block|,
operator|(
name|GClassInitFunc
operator|)
name|gimp_offset_area_class_init
block|,
name|NULL
block|,
comment|/* class_finalize */
name|NULL
block|,
comment|/* class_data     */
sizeof|sizeof
argument_list|(
name|GimpOffsetArea
argument_list|)
block|,
literal|0
block|,
comment|/* n_preallocs    */
operator|(
name|GInstanceInitFunc
operator|)
name|gimp_offset_area_init
block|,       }
decl_stmt|;
name|offset_area_type
operator|=
name|g_type_register_static
argument_list|(
name|GTK_TYPE_DRAWING_AREA
argument_list|,
literal|"GimpOffsetArea"
argument_list|,
operator|&
name|offset_area_info
argument_list|,
literal|0
argument_list|)
expr_stmt|;
block|}
return|return
name|offset_area_type
return|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_offset_area_class_init (GimpOffsetAreaClass * klass)
name|gimp_offset_area_class_init
parameter_list|(
name|GimpOffsetAreaClass
modifier|*
name|klass
parameter_list|)
block|{
name|GtkObjectClass
modifier|*
name|object_class
decl_stmt|;
name|GtkWidgetClass
modifier|*
name|widget_class
decl_stmt|;
name|object_class
operator|=
name|GTK_OBJECT_CLASS
argument_list|(
name|klass
argument_list|)
expr_stmt|;
name|widget_class
operator|=
name|GTK_WIDGET_CLASS
argument_list|(
name|klass
argument_list|)
expr_stmt|;
name|parent_class
operator|=
name|g_type_class_peek_parent
argument_list|(
name|klass
argument_list|)
expr_stmt|;
name|gimp_offset_area_signals
index|[
name|OFFSETS_CHANGED
index|]
operator|=
name|g_signal_new
argument_list|(
literal|"offsets_changed"
argument_list|,
name|G_TYPE_FROM_CLASS
argument_list|(
name|klass
argument_list|)
argument_list|,
name|G_SIGNAL_RUN_FIRST
argument_list|,
name|G_STRUCT_OFFSET
argument_list|(
name|GimpOffsetAreaClass
argument_list|,
name|offsets_changed
argument_list|)
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|,
name|gtk_marshal_VOID__INT_INT
argument_list|,
name|G_TYPE_NONE
argument_list|,
literal|2
argument_list|,
name|G_TYPE_INT
argument_list|,
name|G_TYPE_INT
argument_list|)
expr_stmt|;
name|widget_class
operator|->
name|event
operator|=
name|gimp_offset_area_event
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_offset_area_init (GimpOffsetArea * offset_area)
name|gimp_offset_area_init
parameter_list|(
name|GimpOffsetArea
modifier|*
name|offset_area
parameter_list|)
block|{
name|offset_area
operator|->
name|orig_width
operator|=
literal|0
expr_stmt|;
name|offset_area
operator|->
name|orig_height
operator|=
literal|0
expr_stmt|;
name|offset_area
operator|->
name|width
operator|=
literal|0
expr_stmt|;
name|offset_area
operator|->
name|height
operator|=
literal|0
expr_stmt|;
name|offset_area
operator|->
name|offset_x
operator|=
literal|0
expr_stmt|;
name|offset_area
operator|->
name|offset_y
operator|=
literal|0
expr_stmt|;
name|offset_area
operator|->
name|display_ratio_x
operator|=
literal|1.0
expr_stmt|;
name|offset_area
operator|->
name|display_ratio_y
operator|=
literal|1.0
expr_stmt|;
name|gtk_widget_add_events
argument_list|(
name|GTK_WIDGET
argument_list|(
name|offset_area
argument_list|)
argument_list|,
name|GDK_EXPOSURE_MASK
operator||
name|GDK_BUTTON_PRESS_MASK
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/**  * gimp_offset_area_new:  * @orig_width: the original width  * @orig_height: the original height  *   * Creates a new #GimpOffsetArea widget. A #GimpOffsetArea can be used   * when resizing an image or a drawable to allow the user to interactively   * specify the new offsets.  *   * Return value: the new #GimpOffsetArea widget.  **/
end_comment

begin_function
name|GtkWidget
modifier|*
DECL|function|gimp_offset_area_new (gint orig_width,gint orig_height)
name|gimp_offset_area_new
parameter_list|(
name|gint
name|orig_width
parameter_list|,
name|gint
name|orig_height
parameter_list|)
block|{
name|GimpOffsetArea
modifier|*
name|offset_area
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|orig_width
operator|>
literal|0
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
name|orig_height
operator|>
literal|0
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|offset_area
operator|=
name|g_object_new
argument_list|(
name|GIMP_TYPE_OFFSET_AREA
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|offset_area
operator|->
name|orig_width
operator|=
name|offset_area
operator|->
name|width
operator|=
name|orig_width
expr_stmt|;
name|offset_area
operator|->
name|orig_height
operator|=
name|offset_area
operator|->
name|height
operator|=
name|orig_height
expr_stmt|;
name|gimp_offset_area_resize
argument_list|(
name|offset_area
argument_list|)
expr_stmt|;
return|return
name|GTK_WIDGET
argument_list|(
name|offset_area
argument_list|)
return|;
block|}
end_function

begin_comment
comment|/**  * gimp_offset_area_set_size:  * @offset_area: a #GimpOffsetArea.  * @width: the new width  * @height: the new height  *   * Sets the size of the image/drawable displayed by the #GimpOffsetArea.  * If the offsets change as a result of this change, the %offsets_changed  * signal is emitted.  **/
end_comment

begin_function
name|void
DECL|function|gimp_offset_area_set_size (GimpOffsetArea * offset_area,gint width,gint height)
name|gimp_offset_area_set_size
parameter_list|(
name|GimpOffsetArea
modifier|*
name|offset_area
parameter_list|,
name|gint
name|width
parameter_list|,
name|gint
name|height
parameter_list|)
block|{
name|gint
name|offset_x
decl_stmt|;
name|gint
name|offset_y
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_OFFSET_AREA
argument_list|(
name|offset_area
argument_list|)
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
name|width
operator|>
literal|0
operator|&&
name|height
operator|>
literal|0
argument_list|)
expr_stmt|;
if|if
condition|(
name|offset_area
operator|->
name|width
operator|!=
name|width
operator|||
name|offset_area
operator|->
name|height
operator|!=
name|height
condition|)
block|{
name|offset_area
operator|->
name|width
operator|=
name|width
expr_stmt|;
name|offset_area
operator|->
name|height
operator|=
name|height
expr_stmt|;
if|if
condition|(
name|offset_area
operator|->
name|orig_width
operator|<=
name|offset_area
operator|->
name|width
condition|)
name|offset_x
operator|=
name|CLAMP
argument_list|(
name|offset_area
operator|->
name|offset_x
argument_list|,
literal|0
argument_list|,
name|offset_area
operator|->
name|width
operator|-
name|offset_area
operator|->
name|orig_width
argument_list|)
expr_stmt|;
else|else
name|offset_x
operator|=
name|CLAMP
argument_list|(
name|offset_area
operator|->
name|offset_x
argument_list|,
name|offset_area
operator|->
name|width
operator|-
name|offset_area
operator|->
name|orig_width
argument_list|,
literal|0
argument_list|)
expr_stmt|;
if|if
condition|(
name|offset_area
operator|->
name|orig_height
operator|<=
name|offset_area
operator|->
name|height
condition|)
name|offset_y
operator|=
name|CLAMP
argument_list|(
name|offset_area
operator|->
name|offset_y
argument_list|,
literal|0
argument_list|,
name|offset_area
operator|->
name|height
operator|-
name|offset_area
operator|->
name|orig_height
argument_list|)
expr_stmt|;
else|else
name|offset_y
operator|=
name|CLAMP
argument_list|(
name|offset_area
operator|->
name|offset_y
argument_list|,
name|offset_area
operator|->
name|height
operator|-
name|offset_area
operator|->
name|orig_height
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|offset_area
operator|->
name|offset_x
operator|=
name|offset_x
expr_stmt|;
name|offset_area
operator|->
name|offset_y
operator|=
name|offset_y
expr_stmt|;
name|gimp_offset_area_resize
argument_list|(
name|offset_area
argument_list|)
expr_stmt|;
name|gtk_widget_queue_draw
argument_list|(
name|GTK_WIDGET
argument_list|(
name|offset_area
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|offset_x
operator|!=
name|offset_area
operator|->
name|offset_x
operator|||
name|offset_y
operator|!=
name|offset_area
operator|->
name|offset_y
condition|)
block|{
name|g_signal_emit
argument_list|(
name|G_OBJECT
argument_list|(
name|offset_area
argument_list|)
argument_list|,
name|gimp_offset_area_signals
index|[
name|OFFSETS_CHANGED
index|]
argument_list|,
literal|0
argument_list|,
name|offset_area
operator|->
name|offset_x
argument_list|,
name|offset_area
operator|->
name|offset_y
argument_list|)
expr_stmt|;
block|}
block|}
block|}
end_function

begin_comment
comment|/**  * gimp_offset_area_set_size:  * @offset_area: a #GimpOffsetArea.  * @width: the X offset  * @height: the Y offset  *   * Sets the offsets of the image/drawable displayed by the #GimpOffsetArea.  * It does not emit the %offsets_changed signal.  **/
end_comment

begin_function
name|void
DECL|function|gimp_offset_area_set_offsets (GimpOffsetArea * offset_area,gint offset_x,gint offset_y)
name|gimp_offset_area_set_offsets
parameter_list|(
name|GimpOffsetArea
modifier|*
name|offset_area
parameter_list|,
name|gint
name|offset_x
parameter_list|,
name|gint
name|offset_y
parameter_list|)
block|{
name|g_return_if_fail
argument_list|(
name|GIMP_IS_OFFSET_AREA
argument_list|(
name|offset_area
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|offset_area
operator|->
name|offset_x
operator|!=
name|offset_x
operator|||
name|offset_area
operator|->
name|offset_y
operator|!=
name|offset_y
condition|)
block|{
if|if
condition|(
name|offset_area
operator|->
name|orig_width
operator|<=
name|offset_area
operator|->
name|width
condition|)
name|offset_area
operator|->
name|offset_x
operator|=
name|CLAMP
argument_list|(
name|offset_x
argument_list|,
literal|0
argument_list|,
name|offset_area
operator|->
name|width
operator|-
name|offset_area
operator|->
name|orig_width
argument_list|)
expr_stmt|;
else|else
name|offset_area
operator|->
name|offset_x
operator|=
name|CLAMP
argument_list|(
name|offset_x
argument_list|,
name|offset_area
operator|->
name|width
operator|-
name|offset_area
operator|->
name|orig_width
argument_list|,
literal|0
argument_list|)
expr_stmt|;
if|if
condition|(
name|offset_area
operator|->
name|orig_height
operator|<=
name|offset_area
operator|->
name|height
condition|)
name|offset_area
operator|->
name|offset_y
operator|=
name|CLAMP
argument_list|(
name|offset_y
argument_list|,
literal|0
argument_list|,
name|offset_area
operator|->
name|height
operator|-
name|offset_area
operator|->
name|orig_height
argument_list|)
expr_stmt|;
else|else
name|offset_area
operator|->
name|offset_y
operator|=
name|CLAMP
argument_list|(
name|offset_y
argument_list|,
name|offset_area
operator|->
name|height
operator|-
name|offset_area
operator|->
name|orig_height
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_queue_draw
argument_list|(
name|GTK_WIDGET
argument_list|(
name|offset_area
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_offset_area_resize (GimpOffsetArea * offset_area)
name|gimp_offset_area_resize
parameter_list|(
name|GimpOffsetArea
modifier|*
name|offset_area
parameter_list|)
block|{
name|gint
name|width
decl_stmt|;
name|gint
name|height
decl_stmt|;
name|gdouble
name|ratio
decl_stmt|;
if|if
condition|(
name|offset_area
operator|->
name|orig_width
operator|==
literal|0
operator|||
name|offset_area
operator|->
name|orig_height
operator|==
literal|0
condition|)
return|return;
if|if
condition|(
name|offset_area
operator|->
name|orig_width
operator|<=
name|offset_area
operator|->
name|width
condition|)
name|width
operator|=
name|offset_area
operator|->
name|width
expr_stmt|;
else|else
name|width
operator|=
name|offset_area
operator|->
name|orig_width
operator|*
literal|2
operator|-
name|offset_area
operator|->
name|width
expr_stmt|;
if|if
condition|(
name|offset_area
operator|->
name|orig_height
operator|<=
name|offset_area
operator|->
name|height
condition|)
name|height
operator|=
name|offset_area
operator|->
name|height
expr_stmt|;
else|else
name|height
operator|=
name|offset_area
operator|->
name|orig_height
operator|*
literal|2
operator|-
name|offset_area
operator|->
name|height
expr_stmt|;
name|ratio
operator|=
operator|(
name|gdouble
operator|)
name|DRAWING_AREA_SIZE
operator|/
operator|(
name|gdouble
operator|)
name|MAX
argument_list|(
name|width
argument_list|,
name|height
argument_list|)
expr_stmt|;
name|width
operator|=
name|ratio
operator|*
operator|(
name|gdouble
operator|)
name|width
expr_stmt|;
name|height
operator|=
name|ratio
operator|*
operator|(
name|gdouble
operator|)
name|height
expr_stmt|;
name|gtk_drawing_area_size
argument_list|(
name|GTK_DRAWING_AREA
argument_list|(
name|offset_area
argument_list|)
argument_list|,
name|width
argument_list|,
name|height
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|gboolean
DECL|function|gimp_offset_area_event (GtkWidget * widget,GdkEvent * event)
name|gimp_offset_area_event
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|GdkEvent
modifier|*
name|event
parameter_list|)
block|{
specifier|static
name|gint
name|orig_offset_x
init|=
literal|0
decl_stmt|;
specifier|static
name|gint
name|orig_offset_y
init|=
literal|0
decl_stmt|;
specifier|static
name|gint
name|start_x
init|=
literal|0
decl_stmt|;
specifier|static
name|gint
name|start_y
init|=
literal|0
decl_stmt|;
name|GimpOffsetArea
modifier|*
name|offset_area
init|=
name|GIMP_OFFSET_AREA
argument_list|(
name|widget
argument_list|)
decl_stmt|;
name|GdkEventConfigure
modifier|*
name|conf_event
decl_stmt|;
name|gint
name|offset_x
decl_stmt|;
name|gint
name|offset_y
decl_stmt|;
if|if
condition|(
name|offset_area
operator|->
name|orig_width
operator|==
literal|0
operator|||
name|offset_area
operator|->
name|orig_height
operator|==
literal|0
condition|)
return|return
name|FALSE
return|;
switch|switch
condition|(
name|event
operator|->
name|type
condition|)
block|{
case|case
name|GDK_CONFIGURE
case|:
name|conf_event
operator|=
operator|(
name|GdkEventConfigure
operator|*
operator|)
name|event
expr_stmt|;
name|offset_area
operator|->
name|display_ratio_x
operator|=
operator|(
name|gdouble
operator|)
name|conf_event
operator|->
name|width
operator|/
operator|(
operator|(
name|offset_area
operator|->
name|orig_width
operator|<=
name|offset_area
operator|->
name|width
operator|)
condition|?
name|offset_area
operator|->
name|width
else|:
name|offset_area
operator|->
name|orig_width
operator|*
literal|2
operator|-
name|offset_area
operator|->
name|width
operator|)
expr_stmt|;
name|offset_area
operator|->
name|display_ratio_y
operator|=
operator|(
name|gdouble
operator|)
name|conf_event
operator|->
name|height
operator|/
operator|(
operator|(
name|offset_area
operator|->
name|orig_height
operator|<=
name|offset_area
operator|->
name|height
operator|)
condition|?
name|offset_area
operator|->
name|height
else|:
name|offset_area
operator|->
name|orig_height
operator|*
literal|2
operator|-
name|offset_area
operator|->
name|height
operator|)
expr_stmt|;
break|break;
case|case
name|GDK_EXPOSE
case|:
name|gimp_offset_area_draw
argument_list|(
name|offset_area
argument_list|)
expr_stmt|;
break|break;
case|case
name|GDK_BUTTON_PRESS
case|:
name|gdk_pointer_grab
argument_list|(
name|widget
operator|->
name|window
argument_list|,
name|FALSE
argument_list|,
operator|(
name|GDK_BUTTON1_MOTION_MASK
operator||
name|GDK_BUTTON_RELEASE_MASK
operator|)
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|,
name|event
operator|->
name|button
operator|.
name|time
argument_list|)
expr_stmt|;
name|orig_offset_x
operator|=
name|offset_area
operator|->
name|offset_x
expr_stmt|;
name|orig_offset_y
operator|=
name|offset_area
operator|->
name|offset_y
expr_stmt|;
name|start_x
operator|=
name|event
operator|->
name|button
operator|.
name|x
expr_stmt|;
name|start_y
operator|=
name|event
operator|->
name|button
operator|.
name|y
expr_stmt|;
break|break;
case|case
name|GDK_MOTION_NOTIFY
case|:
name|offset_x
operator|=
name|orig_offset_x
operator|+
operator|(
name|event
operator|->
name|motion
operator|.
name|x
operator|-
name|start_x
operator|)
operator|/
name|offset_area
operator|->
name|display_ratio_x
expr_stmt|;
name|offset_y
operator|=
name|orig_offset_y
operator|+
operator|(
name|event
operator|->
name|motion
operator|.
name|y
operator|-
name|start_y
operator|)
operator|/
name|offset_area
operator|->
name|display_ratio_y
expr_stmt|;
if|if
condition|(
name|offset_area
operator|->
name|offset_x
operator|!=
name|offset_x
operator|||
name|offset_area
operator|->
name|offset_y
operator|!=
name|offset_y
condition|)
block|{
name|gimp_offset_area_set_offsets
argument_list|(
name|offset_area
argument_list|,
name|offset_x
argument_list|,
name|offset_y
argument_list|)
expr_stmt|;
name|g_signal_emit
argument_list|(
name|G_OBJECT
argument_list|(
name|offset_area
argument_list|)
argument_list|,
name|gimp_offset_area_signals
index|[
name|OFFSETS_CHANGED
index|]
argument_list|,
literal|0
argument_list|,
name|offset_area
operator|->
name|offset_x
argument_list|,
name|offset_area
operator|->
name|offset_y
argument_list|)
expr_stmt|;
block|}
break|break;
case|case
name|GDK_BUTTON_RELEASE
case|:
name|gdk_pointer_ungrab
argument_list|(
name|event
operator|->
name|button
operator|.
name|time
argument_list|)
expr_stmt|;
name|start_x
operator|=
name|start_y
operator|=
literal|0
expr_stmt|;
break|break;
default|default:
break|break;
block|}
return|return
name|FALSE
return|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_offset_area_draw (GimpOffsetArea * offset_area)
name|gimp_offset_area_draw
parameter_list|(
name|GimpOffsetArea
modifier|*
name|offset_area
parameter_list|)
block|{
name|GtkWidget
modifier|*
name|widget
init|=
name|GTK_WIDGET
argument_list|(
name|offset_area
argument_list|)
decl_stmt|;
name|gint
name|w
decl_stmt|,
name|h
decl_stmt|;
name|gint
name|x
decl_stmt|,
name|y
decl_stmt|;
name|gdk_window_clear
argument_list|(
name|widget
operator|->
name|window
argument_list|)
expr_stmt|;
name|x
operator|=
name|offset_area
operator|->
name|display_ratio_x
operator|*
operator|(
operator|(
name|offset_area
operator|->
name|orig_width
operator|<=
name|offset_area
operator|->
name|width
operator|)
condition|?
name|offset_area
operator|->
name|offset_x
else|:
name|offset_area
operator|->
name|offset_x
operator|+
name|offset_area
operator|->
name|orig_width
operator|-
name|offset_area
operator|->
name|width
operator|)
expr_stmt|;
name|y
operator|=
name|offset_area
operator|->
name|display_ratio_y
operator|*
operator|(
operator|(
name|offset_area
operator|->
name|orig_height
operator|<=
name|offset_area
operator|->
name|height
operator|)
condition|?
name|offset_area
operator|->
name|offset_y
else|:
name|offset_area
operator|->
name|offset_y
operator|+
name|offset_area
operator|->
name|orig_height
operator|-
name|offset_area
operator|->
name|height
operator|)
expr_stmt|;
name|w
operator|=
name|offset_area
operator|->
name|display_ratio_x
operator|*
name|offset_area
operator|->
name|orig_width
expr_stmt|;
name|h
operator|=
name|offset_area
operator|->
name|display_ratio_y
operator|*
name|offset_area
operator|->
name|orig_height
expr_stmt|;
name|gtk_draw_shadow
argument_list|(
name|widget
operator|->
name|style
argument_list|,
name|widget
operator|->
name|window
argument_list|,
name|GTK_STATE_NORMAL
argument_list|,
name|GTK_SHADOW_OUT
argument_list|,
name|x
argument_list|,
name|y
argument_list|,
name|w
argument_list|,
name|h
argument_list|)
expr_stmt|;
if|if
condition|(
name|offset_area
operator|->
name|orig_width
operator|>
name|offset_area
operator|->
name|width
operator|||
name|offset_area
operator|->
name|orig_height
operator|>
name|offset_area
operator|->
name|height
condition|)
block|{
if|if
condition|(
name|offset_area
operator|->
name|orig_width
operator|>
name|offset_area
operator|->
name|width
condition|)
block|{
name|x
operator|=
name|offset_area
operator|->
name|display_ratio_x
operator|*
operator|(
name|offset_area
operator|->
name|orig_width
operator|-
name|offset_area
operator|->
name|width
operator|)
expr_stmt|;
name|w
operator|=
name|offset_area
operator|->
name|display_ratio_x
operator|*
name|offset_area
operator|->
name|width
expr_stmt|;
block|}
else|else
block|{
name|x
operator|=
operator|-
literal|1
expr_stmt|;
name|w
operator|=
name|widget
operator|->
name|allocation
operator|.
name|width
operator|+
literal|2
expr_stmt|;
block|}
if|if
condition|(
name|offset_area
operator|->
name|orig_height
operator|>
name|offset_area
operator|->
name|height
condition|)
block|{
name|y
operator|=
name|offset_area
operator|->
name|display_ratio_y
operator|*
operator|(
name|offset_area
operator|->
name|orig_height
operator|-
name|offset_area
operator|->
name|height
operator|)
expr_stmt|;
name|h
operator|=
name|offset_area
operator|->
name|display_ratio_y
operator|*
name|offset_area
operator|->
name|height
expr_stmt|;
block|}
else|else
block|{
name|y
operator|=
operator|-
literal|1
expr_stmt|;
name|h
operator|=
name|widget
operator|->
name|allocation
operator|.
name|height
operator|+
literal|2
expr_stmt|;
block|}
name|gdk_draw_rectangle
argument_list|(
name|widget
operator|->
name|window
argument_list|,
name|widget
operator|->
name|style
operator|->
name|black_gc
argument_list|,
literal|0
argument_list|,
name|x
argument_list|,
name|y
argument_list|,
name|w
argument_list|,
name|h
argument_list|)
expr_stmt|;
block|}
block|}
end_function

end_unit

