begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* The GIMP -- an image manipulation program  * Copyright (C) 1995 Spencer Kimball and Peter Mattis  *  * gimpdialogfactory.c  * Copyright (C) 2001 Michael Natterer<mitch@gimp.org>  *  * This program is free software; you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 2 of the License, or  * (at your option) any later version.  *  * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *  * You should have received a copy of the GNU General Public License  * along with this program; if not, write to the Free Software  * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  */
end_comment

begin_include
include|#
directive|include
file|"config.h"
end_include

begin_include
include|#
directive|include
file|<stdlib.h>
end_include

begin_include
include|#
directive|include
file|<string.h>
end_include

begin_include
include|#
directive|include
file|<gtk/gtk.h>
end_include

begin_include
include|#
directive|include
file|"libgimpwidgets/gimpwidgets.h"
end_include

begin_include
include|#
directive|include
file|"widgets-types.h"
end_include

begin_include
include|#
directive|include
file|"core/gimpcontext.h"
end_include

begin_include
include|#
directive|include
file|"gimpcontainerview.h"
end_include

begin_include
include|#
directive|include
file|"gimpcontainerview-utils.h"
end_include

begin_include
include|#
directive|include
file|"gimpcursor.h"
end_include

begin_include
include|#
directive|include
file|"gimpdialogfactory.h"
end_include

begin_include
include|#
directive|include
file|"gimpdock.h"
end_include

begin_include
include|#
directive|include
file|"gimpdockbook.h"
end_include

begin_include
include|#
directive|include
file|"gimpdockable.h"
end_include

begin_include
include|#
directive|include
file|"gimpimagedock.h"
end_include

begin_include
include|#
directive|include
file|"gimpitemfactory.h"
end_include

begin_typedef
typedef|typedef
enum|enum
DECL|enum|__anon2b6d4ecd0103
block|{
DECL|enumerator|GIMP_DIALOG_VISIBILITY_UNKNOWN
name|GIMP_DIALOG_VISIBILITY_UNKNOWN
init|=
literal|0
block|,
DECL|enumerator|GIMP_DIALOG_VISIBILITY_INVISIBLE
name|GIMP_DIALOG_VISIBILITY_INVISIBLE
block|,
DECL|enumerator|GIMP_DIALOG_VISIBILITY_VISIBLE
name|GIMP_DIALOG_VISIBILITY_VISIBLE
DECL|typedef|GimpDialogVisibilityState
block|}
name|GimpDialogVisibilityState
typedef|;
end_typedef

begin_typedef
typedef|typedef
enum|enum
DECL|enum|__anon2b6d4ecd0203
block|{
DECL|enumerator|GIMP_DIALOG_SHOW_ALL
name|GIMP_DIALOG_SHOW_ALL
block|,
DECL|enumerator|GIMP_DIALOG_HIDE_ALL
name|GIMP_DIALOG_HIDE_ALL
block|,
DECL|enumerator|GIMP_DIALOG_SHOW_TOOLBOX
name|GIMP_DIALOG_SHOW_TOOLBOX
DECL|typedef|GimpDialogShowState
block|}
name|GimpDialogShowState
typedef|;
end_typedef

begin_function_decl
specifier|static
name|void
name|gimp_dialog_factory_class_init
parameter_list|(
name|GimpDialogFactoryClass
modifier|*
name|klass
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_dialog_factory_init
parameter_list|(
name|GimpDialogFactory
modifier|*
name|factory
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_dialog_factory_finalize
parameter_list|(
name|GObject
modifier|*
name|object
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_dialog_factories_save_foreach
parameter_list|(
name|gchar
modifier|*
name|name
parameter_list|,
name|GimpDialogFactory
modifier|*
name|factory
parameter_list|,
name|FILE
modifier|*
name|fp
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_dialog_factories_restore_foreach
parameter_list|(
name|gchar
modifier|*
name|name
parameter_list|,
name|GimpDialogFactory
modifier|*
name|factory
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_dialog_factory_get_window_info
parameter_list|(
name|GtkWidget
modifier|*
name|window
parameter_list|,
name|GimpSessionInfo
modifier|*
name|info
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_dialog_factory_set_window_geometry
parameter_list|(
name|GtkWidget
modifier|*
name|window
parameter_list|,
name|GimpSessionInfo
modifier|*
name|info
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_dialog_factory_get_aux_info
parameter_list|(
name|GtkWidget
modifier|*
name|dialog
parameter_list|,
name|GimpSessionInfo
modifier|*
name|info
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_dialog_factory_set_aux_info
parameter_list|(
name|GtkWidget
modifier|*
name|dialog
parameter_list|,
name|GimpSessionInfo
modifier|*
name|info
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_dialog_factories_hide_foreach
parameter_list|(
name|gchar
modifier|*
name|name
parameter_list|,
name|GimpDialogFactory
modifier|*
name|factory
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_dialog_factories_show_foreach
parameter_list|(
name|gchar
modifier|*
name|name
parameter_list|,
name|GimpDialogFactory
modifier|*
name|factory
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_dialog_factories_idle_foreach
parameter_list|(
name|gchar
modifier|*
name|name
parameter_list|,
name|GimpDialogFactory
modifier|*
name|factory
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_dialog_factories_unidle_foreach
parameter_list|(
name|gchar
modifier|*
name|name
parameter_list|,
name|GimpDialogFactory
modifier|*
name|factory
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_decl_stmt
DECL|variable|parent_class
specifier|static
name|GimpObjectClass
modifier|*
name|parent_class
init|=
name|NULL
decl_stmt|;
end_decl_stmt

begin_function
name|GType
DECL|function|gimp_dialog_factory_get_type (void)
name|gimp_dialog_factory_get_type
parameter_list|(
name|void
parameter_list|)
block|{
specifier|static
name|GType
name|factory_type
init|=
literal|0
decl_stmt|;
if|if
condition|(
operator|!
name|factory_type
condition|)
block|{
specifier|static
specifier|const
name|GTypeInfo
name|factory_info
init|=
block|{
sizeof|sizeof
argument_list|(
name|GimpDialogFactoryClass
argument_list|)
block|,
name|NULL
block|,
comment|/* base_init */
name|NULL
block|,
comment|/* base_finalize */
operator|(
name|GClassInitFunc
operator|)
name|gimp_dialog_factory_class_init
block|,
name|NULL
block|,
comment|/* class_finalize */
name|NULL
block|,
comment|/* class_data */
sizeof|sizeof
argument_list|(
name|GimpDialogFactory
argument_list|)
block|,
literal|0
block|,
comment|/* n_preallocs */
operator|(
name|GInstanceInitFunc
operator|)
name|gimp_dialog_factory_init
block|,       }
decl_stmt|;
name|factory_type
operator|=
name|g_type_register_static
argument_list|(
name|GIMP_TYPE_OBJECT
argument_list|,
literal|"GimpDialogFactory"
argument_list|,
operator|&
name|factory_info
argument_list|,
literal|0
argument_list|)
expr_stmt|;
block|}
return|return
name|factory_type
return|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_dialog_factory_class_init (GimpDialogFactoryClass * klass)
name|gimp_dialog_factory_class_init
parameter_list|(
name|GimpDialogFactoryClass
modifier|*
name|klass
parameter_list|)
block|{
name|GObjectClass
modifier|*
name|object_class
decl_stmt|;
name|object_class
operator|=
name|G_OBJECT_CLASS
argument_list|(
name|klass
argument_list|)
expr_stmt|;
name|parent_class
operator|=
name|g_type_class_peek_parent
argument_list|(
name|klass
argument_list|)
expr_stmt|;
name|object_class
operator|->
name|finalize
operator|=
name|gimp_dialog_factory_finalize
expr_stmt|;
name|klass
operator|->
name|factories
operator|=
name|g_hash_table_new
argument_list|(
name|g_str_hash
argument_list|,
name|g_str_equal
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_dialog_factory_init (GimpDialogFactory * factory)
name|gimp_dialog_factory_init
parameter_list|(
name|GimpDialogFactory
modifier|*
name|factory
parameter_list|)
block|{
name|factory
operator|->
name|item_factory
operator|=
name|NULL
expr_stmt|;
name|factory
operator|->
name|new_dock_func
operator|=
name|NULL
expr_stmt|;
name|factory
operator|->
name|registered_dialogs
operator|=
name|NULL
expr_stmt|;
name|factory
operator|->
name|session_infos
operator|=
name|NULL
expr_stmt|;
name|factory
operator|->
name|open_dialogs
operator|=
name|NULL
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_dialog_factory_finalize (GObject * object)
name|gimp_dialog_factory_finalize
parameter_list|(
name|GObject
modifier|*
name|object
parameter_list|)
block|{
name|GimpDialogFactory
modifier|*
name|factory
decl_stmt|;
name|GList
modifier|*
name|list
decl_stmt|;
name|factory
operator|=
name|GIMP_DIALOG_FACTORY
argument_list|(
name|object
argument_list|)
expr_stmt|;
name|g_hash_table_remove
argument_list|(
name|GIMP_DIALOG_FACTORY_GET_CLASS
argument_list|(
name|object
argument_list|)
operator|->
name|factories
argument_list|,
name|GIMP_OBJECT
argument_list|(
name|factory
argument_list|)
operator|->
name|name
argument_list|)
expr_stmt|;
for|for
control|(
name|list
operator|=
name|factory
operator|->
name|registered_dialogs
init|;
name|list
condition|;
name|list
operator|=
name|g_list_next
argument_list|(
name|list
argument_list|)
control|)
block|{
name|GimpDialogFactoryEntry
modifier|*
name|entry
decl_stmt|;
name|entry
operator|=
operator|(
name|GimpDialogFactoryEntry
operator|*
operator|)
name|list
operator|->
name|data
expr_stmt|;
name|g_free
argument_list|(
name|entry
operator|->
name|identifier
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|entry
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|factory
operator|->
name|registered_dialogs
condition|)
block|{
name|g_list_free
argument_list|(
name|factory
operator|->
name|registered_dialogs
argument_list|)
expr_stmt|;
name|factory
operator|->
name|registered_dialogs
operator|=
name|NULL
expr_stmt|;
block|}
if|if
condition|(
name|factory
operator|->
name|open_dialogs
condition|)
block|{
name|g_list_free
argument_list|(
name|factory
operator|->
name|open_dialogs
argument_list|)
expr_stmt|;
name|factory
operator|->
name|open_dialogs
operator|=
name|NULL
expr_stmt|;
block|}
name|G_OBJECT_CLASS
argument_list|(
name|parent_class
argument_list|)
operator|->
name|finalize
argument_list|(
name|object
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|GimpDialogFactory
modifier|*
DECL|function|gimp_dialog_factory_new (const gchar * name,GimpContext * context,GimpItemFactory * item_factory,GimpDialogNewFunc new_dock_func)
name|gimp_dialog_factory_new
parameter_list|(
specifier|const
name|gchar
modifier|*
name|name
parameter_list|,
name|GimpContext
modifier|*
name|context
parameter_list|,
name|GimpItemFactory
modifier|*
name|item_factory
parameter_list|,
name|GimpDialogNewFunc
name|new_dock_func
parameter_list|)
block|{
name|GimpDialogFactoryClass
modifier|*
name|factory_class
decl_stmt|;
name|GimpDialogFactory
modifier|*
name|factory
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|name
operator|!=
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_CONTEXT
argument_list|(
name|context
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
operator|!
name|item_factory
operator|||
name|GIMP_IS_ITEM_FACTORY
argument_list|(
name|item_factory
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
comment|/* EEK */
name|factory_class
operator|=
name|g_type_class_ref
argument_list|(
name|GIMP_TYPE_DIALOG_FACTORY
argument_list|)
expr_stmt|;
if|if
condition|(
name|g_hash_table_lookup
argument_list|(
name|factory_class
operator|->
name|factories
argument_list|,
name|name
argument_list|)
condition|)
block|{
name|g_warning
argument_list|(
literal|"%s(): dialog factory \"%s\" already exists"
argument_list|,
name|G_GNUC_FUNCTION
argument_list|,
name|name
argument_list|)
expr_stmt|;
return|return
name|NULL
return|;
block|}
name|factory
operator|=
name|g_object_new
argument_list|(
name|GIMP_TYPE_DIALOG_FACTORY
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|gimp_object_set_name
argument_list|(
name|GIMP_OBJECT
argument_list|(
name|factory
argument_list|)
argument_list|,
name|name
argument_list|)
expr_stmt|;
name|g_hash_table_insert
argument_list|(
name|factory_class
operator|->
name|factories
argument_list|,
name|GIMP_OBJECT
argument_list|(
name|factory
argument_list|)
operator|->
name|name
argument_list|,
name|factory
argument_list|)
expr_stmt|;
name|factory
operator|->
name|context
operator|=
name|context
expr_stmt|;
name|factory
operator|->
name|item_factory
operator|=
name|item_factory
expr_stmt|;
name|factory
operator|->
name|new_dock_func
operator|=
name|new_dock_func
expr_stmt|;
return|return
name|factory
return|;
block|}
end_function

begin_function
name|GimpDialogFactory
modifier|*
DECL|function|gimp_dialog_factory_from_name (const gchar * name)
name|gimp_dialog_factory_from_name
parameter_list|(
specifier|const
name|gchar
modifier|*
name|name
parameter_list|)
block|{
name|GimpDialogFactoryClass
modifier|*
name|factory_class
decl_stmt|;
name|GimpDialogFactory
modifier|*
name|factory
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|name
operator|!=
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|factory_class
operator|=
name|g_type_class_peek
argument_list|(
name|GIMP_TYPE_DIALOG_FACTORY
argument_list|)
expr_stmt|;
name|factory
operator|=
operator|(
name|GimpDialogFactory
operator|*
operator|)
name|g_hash_table_lookup
argument_list|(
name|factory_class
operator|->
name|factories
argument_list|,
name|name
argument_list|)
expr_stmt|;
return|return
name|factory
return|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_dialog_factory_register_entry (GimpDialogFactory * factory,const gchar * identifier,GimpDialogNewFunc new_func,gint preview_size,gboolean singleton,gboolean session_managed,gboolean remember_size,gboolean remember_if_open)
name|gimp_dialog_factory_register_entry
parameter_list|(
name|GimpDialogFactory
modifier|*
name|factory
parameter_list|,
specifier|const
name|gchar
modifier|*
name|identifier
parameter_list|,
name|GimpDialogNewFunc
name|new_func
parameter_list|,
name|gint
name|preview_size
parameter_list|,
name|gboolean
name|singleton
parameter_list|,
name|gboolean
name|session_managed
parameter_list|,
name|gboolean
name|remember_size
parameter_list|,
name|gboolean
name|remember_if_open
parameter_list|)
block|{
name|GimpDialogFactoryEntry
modifier|*
name|entry
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_DIALOG_FACTORY
argument_list|(
name|factory
argument_list|)
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
name|identifier
operator|!=
name|NULL
argument_list|)
expr_stmt|;
name|entry
operator|=
name|g_new0
argument_list|(
name|GimpDialogFactoryEntry
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|entry
operator|->
name|identifier
operator|=
name|g_strdup
argument_list|(
name|identifier
argument_list|)
expr_stmt|;
name|entry
operator|->
name|new_func
operator|=
name|new_func
expr_stmt|;
name|entry
operator|->
name|preview_size
operator|=
name|preview_size
expr_stmt|;
name|entry
operator|->
name|singleton
operator|=
name|singleton
condition|?
name|TRUE
else|:
name|FALSE
expr_stmt|;
name|entry
operator|->
name|session_managed
operator|=
name|session_managed
condition|?
name|TRUE
else|:
name|FALSE
expr_stmt|;
name|entry
operator|->
name|remember_size
operator|=
name|remember_size
condition|?
name|TRUE
else|:
name|FALSE
expr_stmt|;
name|entry
operator|->
name|remember_if_open
operator|=
name|remember_if_open
condition|?
name|TRUE
else|:
name|FALSE
expr_stmt|;
name|factory
operator|->
name|registered_dialogs
operator|=
name|g_list_prepend
argument_list|(
name|factory
operator|->
name|registered_dialogs
argument_list|,
name|entry
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|GimpDialogFactoryEntry
modifier|*
DECL|function|gimp_dialog_factory_find_entry (GimpDialogFactory * factory,const gchar * identifier)
name|gimp_dialog_factory_find_entry
parameter_list|(
name|GimpDialogFactory
modifier|*
name|factory
parameter_list|,
specifier|const
name|gchar
modifier|*
name|identifier
parameter_list|)
block|{
name|GList
modifier|*
name|list
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_DIALOG_FACTORY
argument_list|(
name|factory
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
name|identifier
operator|!=
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
for|for
control|(
name|list
operator|=
name|factory
operator|->
name|registered_dialogs
init|;
name|list
condition|;
name|list
operator|=
name|g_list_next
argument_list|(
name|list
argument_list|)
control|)
block|{
name|GimpDialogFactoryEntry
modifier|*
name|entry
decl_stmt|;
name|entry
operator|=
operator|(
name|GimpDialogFactoryEntry
operator|*
operator|)
name|list
operator|->
name|data
expr_stmt|;
if|if
condition|(
operator|!
name|strcmp
argument_list|(
name|identifier
argument_list|,
name|entry
operator|->
name|identifier
argument_list|)
condition|)
block|{
return|return
name|entry
return|;
block|}
block|}
return|return
name|NULL
return|;
block|}
end_function

begin_function
name|GimpSessionInfo
modifier|*
DECL|function|gimp_dialog_factory_find_session_info (GimpDialogFactory * factory,const gchar * identifier)
name|gimp_dialog_factory_find_session_info
parameter_list|(
name|GimpDialogFactory
modifier|*
name|factory
parameter_list|,
specifier|const
name|gchar
modifier|*
name|identifier
parameter_list|)
block|{
name|GList
modifier|*
name|list
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_DIALOG_FACTORY
argument_list|(
name|factory
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
name|identifier
operator|!=
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
for|for
control|(
name|list
operator|=
name|factory
operator|->
name|session_infos
init|;
name|list
condition|;
name|list
operator|=
name|g_list_next
argument_list|(
name|list
argument_list|)
control|)
block|{
name|GimpSessionInfo
modifier|*
name|info
decl_stmt|;
name|info
operator|=
operator|(
name|GimpSessionInfo
operator|*
operator|)
name|list
operator|->
name|data
expr_stmt|;
if|if
condition|(
operator|(
name|info
operator|->
name|toplevel_entry
operator|&&
operator|!
name|strcmp
argument_list|(
name|identifier
argument_list|,
name|info
operator|->
name|toplevel_entry
operator|->
name|identifier
argument_list|)
operator|)
operator|||
operator|(
name|info
operator|->
name|dockable_entry
operator|&&
operator|!
name|strcmp
argument_list|(
name|identifier
argument_list|,
name|info
operator|->
name|dockable_entry
operator|->
name|identifier
argument_list|)
operator|)
condition|)
block|{
return|return
name|info
return|;
block|}
block|}
return|return
name|NULL
return|;
block|}
end_function

begin_function
specifier|static
name|GtkWidget
modifier|*
DECL|function|gimp_dialog_factory_dialog_new_internal (GimpDialogFactory * factory,GimpContext * context,const gchar * identifier,gint preview_size,gboolean raise_if_found)
name|gimp_dialog_factory_dialog_new_internal
parameter_list|(
name|GimpDialogFactory
modifier|*
name|factory
parameter_list|,
name|GimpContext
modifier|*
name|context
parameter_list|,
specifier|const
name|gchar
modifier|*
name|identifier
parameter_list|,
name|gint
name|preview_size
parameter_list|,
name|gboolean
name|raise_if_found
parameter_list|)
block|{
name|GimpDialogFactoryEntry
modifier|*
name|entry
decl_stmt|;
name|GtkWidget
modifier|*
name|dialog
init|=
name|NULL
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_DIALOG_FACTORY
argument_list|(
name|factory
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
name|identifier
operator|!=
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|entry
operator|=
name|gimp_dialog_factory_find_entry
argument_list|(
name|factory
argument_list|,
name|identifier
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|entry
condition|)
block|{
name|g_warning
argument_list|(
literal|"%s(): no entry entry registered for \"%s\""
argument_list|,
name|G_GNUC_FUNCTION
argument_list|,
name|identifier
argument_list|)
expr_stmt|;
return|return
name|NULL
return|;
block|}
if|if
condition|(
operator|!
name|entry
operator|->
name|new_func
condition|)
block|{
name|g_warning
argument_list|(
literal|"%s(): entry for \"%s\" has no constructor"
argument_list|,
name|G_GNUC_FUNCTION
argument_list|,
name|identifier
argument_list|)
expr_stmt|;
return|return
name|NULL
return|;
block|}
comment|/*  a singleton dialog is always only raised if it already exisits  */
if|if
condition|(
name|raise_if_found
operator|||
name|entry
operator|->
name|singleton
condition|)
block|{
name|GimpSessionInfo
modifier|*
name|info
decl_stmt|;
name|info
operator|=
name|gimp_dialog_factory_find_session_info
argument_list|(
name|factory
argument_list|,
name|identifier
argument_list|)
expr_stmt|;
if|if
condition|(
name|info
condition|)
name|dialog
operator|=
name|info
operator|->
name|widget
expr_stmt|;
block|}
comment|/*  create the dialog if it was not found  */
if|if
condition|(
operator|!
name|dialog
condition|)
block|{
name|GtkWidget
modifier|*
name|dock
init|=
name|NULL
decl_stmt|;
comment|/*  If the dialog will be a dockable (factory->new_dock_func) and        *  we are called from gimp_dialog_factory_dialog_raise() (! context),        *  create a new dock _before_ creating the dialog.        *  We do this because the new dockable needs to be created in it's        *  dock's context.        */
if|if
condition|(
name|factory
operator|->
name|new_dock_func
operator|&&
operator|!
name|context
condition|)
block|{
name|dock
operator|=
name|gimp_dialog_factory_dock_new
argument_list|(
name|factory
argument_list|)
expr_stmt|;
name|gimp_image_dock_set_show_image_menu
argument_list|(
name|GIMP_IMAGE_DOCK
argument_list|(
name|dock
argument_list|)
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gimp_dock_add_book
argument_list|(
name|GIMP_DOCK
argument_list|(
name|dock
argument_list|)
argument_list|,
name|GIMP_DOCKBOOK
argument_list|(
name|gimp_dockbook_new
argument_list|()
argument_list|)
argument_list|,
literal|0
argument_list|)
expr_stmt|;
block|}
comment|/*  Create the new dialog in the appropriate context which is        *  - the passed context if not NULL        *  - the newly created dock's context if we just created it        *  - the factory's context, which happens when raising a toplevel        *    dialog was the original request.        */
if|if
condition|(
name|preview_size
operator|<
literal|16
condition|)
name|preview_size
operator|=
name|entry
operator|->
name|preview_size
expr_stmt|;
if|if
condition|(
name|context
condition|)
name|dialog
operator|=
name|entry
operator|->
name|new_func
argument_list|(
name|factory
argument_list|,
name|context
argument_list|,
name|preview_size
argument_list|)
expr_stmt|;
elseif|else
if|if
condition|(
name|dock
condition|)
name|dialog
operator|=
name|entry
operator|->
name|new_func
argument_list|(
name|factory
argument_list|,
name|GIMP_DOCK
argument_list|(
name|dock
argument_list|)
operator|->
name|context
argument_list|,
name|preview_size
argument_list|)
expr_stmt|;
else|else
name|dialog
operator|=
name|entry
operator|->
name|new_func
argument_list|(
name|factory
argument_list|,
name|factory
operator|->
name|context
argument_list|,
name|preview_size
argument_list|)
expr_stmt|;
if|if
condition|(
name|dialog
condition|)
block|{
name|g_object_set_data
argument_list|(
name|G_OBJECT
argument_list|(
name|dialog
argument_list|)
argument_list|,
literal|"gimp-dialog-factory"
argument_list|,
name|factory
argument_list|)
expr_stmt|;
name|g_object_set_data
argument_list|(
name|G_OBJECT
argument_list|(
name|dialog
argument_list|)
argument_list|,
literal|"gimp-dialog-factory-entry"
argument_list|,
name|entry
argument_list|)
expr_stmt|;
comment|/*  If we created a dock before, the newly created dialog is 	   *  supposed to be a GimpDockable. 	   */
if|if
condition|(
name|dock
condition|)
block|{
if|if
condition|(
name|GIMP_IS_DOCKABLE
argument_list|(
name|dialog
argument_list|)
condition|)
block|{
name|gimp_dock_add
argument_list|(
name|GIMP_DOCK
argument_list|(
name|dock
argument_list|)
argument_list|,
name|GIMP_DOCKABLE
argument_list|(
name|dialog
argument_list|)
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|dock
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|g_warning
argument_list|(
literal|"%s(): GimpDialogFactory is a dockable factory "
literal|"but constructor for \"%s\" did not return a "
literal|"GimpDockable"
argument_list|,
name|G_GNUC_FUNCTION
argument_list|,
name|identifier
argument_list|)
expr_stmt|;
name|gtk_widget_destroy
argument_list|(
name|dialog
argument_list|)
expr_stmt|;
name|dialog
operator|=
name|NULL
expr_stmt|;
block|}
block|}
block|}
elseif|else
if|if
condition|(
name|dock
condition|)
block|{
name|g_warning
argument_list|(
literal|"%s(): constructor for \"%s\" returned NULL"
argument_list|,
name|G_GNUC_FUNCTION
argument_list|,
name|identifier
argument_list|)
expr_stmt|;
name|gtk_widget_destroy
argument_list|(
name|dock
argument_list|)
expr_stmt|;
name|dock
operator|=
name|NULL
expr_stmt|;
block|}
if|if
condition|(
name|dialog
condition|)
name|gimp_dialog_factory_add_dialog
argument_list|(
name|factory
argument_list|,
name|dialog
argument_list|)
expr_stmt|;
block|}
comment|/*  finally, if we found an existing dialog or created a new one,    *  raise it    */
if|if
condition|(
name|dialog
condition|)
block|{
if|if
condition|(
name|GTK_WIDGET_TOPLEVEL
argument_list|(
name|dialog
argument_list|)
condition|)
block|{
if|if
condition|(
operator|!
name|GTK_WIDGET_VISIBLE
argument_list|(
name|dialog
argument_list|)
condition|)
name|gtk_widget_show
argument_list|(
name|dialog
argument_list|)
expr_stmt|;
elseif|else
if|if
condition|(
name|dialog
operator|->
name|window
condition|)
name|gdk_window_raise
argument_list|(
name|dialog
operator|->
name|window
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|GIMP_IS_DOCKABLE
argument_list|(
name|dialog
argument_list|)
condition|)
block|{
name|GimpDockable
modifier|*
name|dockable
decl_stmt|;
name|gint
name|page_num
decl_stmt|;
name|dockable
operator|=
name|GIMP_DOCKABLE
argument_list|(
name|dialog
argument_list|)
expr_stmt|;
if|if
condition|(
name|dockable
operator|->
name|dockbook
operator|&&
name|dockable
operator|->
name|dockbook
operator|->
name|dock
condition|)
block|{
name|page_num
operator|=
name|gtk_notebook_page_num
argument_list|(
name|GTK_NOTEBOOK
argument_list|(
name|dockable
operator|->
name|dockbook
argument_list|)
argument_list|,
name|dialog
argument_list|)
expr_stmt|;
if|if
condition|(
name|page_num
operator|!=
operator|-
literal|1
condition|)
block|{
name|GtkWidget
modifier|*
name|toplevel
decl_stmt|;
name|gtk_notebook_set_current_page
argument_list|(
name|GTK_NOTEBOOK
argument_list|(
name|dockable
operator|->
name|dockbook
argument_list|)
argument_list|,
name|page_num
argument_list|)
expr_stmt|;
name|toplevel
operator|=
name|gtk_widget_get_toplevel
argument_list|(
name|dialog
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|GTK_WIDGET_VISIBLE
argument_list|(
name|toplevel
argument_list|)
condition|)
name|gtk_widget_show
argument_list|(
name|toplevel
argument_list|)
expr_stmt|;
elseif|else
if|if
condition|(
name|toplevel
operator|->
name|window
condition|)
name|gdk_window_raise
argument_list|(
name|toplevel
operator|->
name|window
argument_list|)
expr_stmt|;
block|}
block|}
block|}
block|}
return|return
name|dialog
return|;
block|}
end_function

begin_comment
comment|/**  * gimp_dialog_factory_dialog_new:  * @factory:    a #GimpDialogFactory  * @identifier: the identifier of the dialog as registered with  *              gimp_dialog_factory_register_entry()  *   * Creates a new toplevel dialog or a #GimpDockable, depending on whether  * %factory is a toplevel of dockable factory.  *  * Implicitly raises singleton dialogs.  *   * Return value: the newly created dialog or an already existing singleton  *               dialog.  **/
end_comment

begin_function
name|GtkWidget
modifier|*
DECL|function|gimp_dialog_factory_dialog_new (GimpDialogFactory * factory,const gchar * identifier,gint preview_size)
name|gimp_dialog_factory_dialog_new
parameter_list|(
name|GimpDialogFactory
modifier|*
name|factory
parameter_list|,
specifier|const
name|gchar
modifier|*
name|identifier
parameter_list|,
name|gint
name|preview_size
parameter_list|)
block|{
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_DIALOG_FACTORY
argument_list|(
name|factory
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
name|identifier
operator|!=
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
return|return
name|gimp_dialog_factory_dialog_new_internal
argument_list|(
name|factory
argument_list|,
name|factory
operator|->
name|context
argument_list|,
name|identifier
argument_list|,
name|preview_size
argument_list|,
name|FALSE
argument_list|)
return|;
block|}
end_function

begin_comment
comment|/**  * gimp_dialog_factory_dialog_raise:  * @factory   : a #GimpDialogFactory  * @identifier: the identifier of the dialog as registered with  *              gimp_dialog_factory_register_entry()  *   * Raises an already existing toplevel dialog or #GimpDockable if it was  * already created by this %facory.  *  * Implicitly creates a new dialog if it was not found.  *   * Return value: the raised or newly created dialog.  **/
end_comment

begin_function
name|GtkWidget
modifier|*
DECL|function|gimp_dialog_factory_dialog_raise (GimpDialogFactory * factory,const gchar * identifier,gint preview_size)
name|gimp_dialog_factory_dialog_raise
parameter_list|(
name|GimpDialogFactory
modifier|*
name|factory
parameter_list|,
specifier|const
name|gchar
modifier|*
name|identifier
parameter_list|,
name|gint
name|preview_size
parameter_list|)
block|{
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_DIALOG_FACTORY
argument_list|(
name|factory
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
name|identifier
operator|!=
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
return|return
name|gimp_dialog_factory_dialog_new_internal
argument_list|(
name|factory
argument_list|,
name|NULL
argument_list|,
name|identifier
argument_list|,
name|preview_size
argument_list|,
name|TRUE
argument_list|)
return|;
block|}
end_function

begin_comment
comment|/**  * gimp_dialog_factory_dockable_new:  * @factory   : a #GimpDialogFactory  * @dock      : a #GimpDock crated by this %factory.  * @identifier: the identifier of the dialog as registered with  *              gimp_dialog_factory_register_entry()  *   * Creates a new #GimpDockable in the context of the #GimpDock it will be  * added to.  *  * Implicitly raises& returns an already existing singleton dockable,  * so callers should check that dockable->dockbook is NULL before trying  * to add it to it's #GimpDockbook.  *   * Return value: the newly created #GimpDockable or an already existing  *               singleton dockable.  **/
end_comment

begin_function
name|GtkWidget
modifier|*
DECL|function|gimp_dialog_factory_dockable_new (GimpDialogFactory * factory,GimpDock * dock,const gchar * identifier,gint preview_size)
name|gimp_dialog_factory_dockable_new
parameter_list|(
name|GimpDialogFactory
modifier|*
name|factory
parameter_list|,
name|GimpDock
modifier|*
name|dock
parameter_list|,
specifier|const
name|gchar
modifier|*
name|identifier
parameter_list|,
name|gint
name|preview_size
parameter_list|)
block|{
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_DIALOG_FACTORY
argument_list|(
name|factory
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_DOCK
argument_list|(
name|dock
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
name|identifier
operator|!=
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
return|return
name|gimp_dialog_factory_dialog_new_internal
argument_list|(
name|factory
argument_list|,
name|dock
operator|->
name|context
argument_list|,
name|identifier
argument_list|,
name|preview_size
argument_list|,
name|FALSE
argument_list|)
return|;
block|}
end_function

begin_comment
comment|/**  * gimp_dialog_factory_dock_new:  * @factory: a #GimpDialogFacotry  *   * Returns a new #GimpDock in this %factory's context. We use a function  * pointer passed to this %factory's constructor instead of simply  * gimp_dock_new() because we may want different instances of  * #GimpDialogFactory create different subclasses of #GimpDock.  *   * Return value: the newly created #GimpDock.  **/
end_comment

begin_function
name|GtkWidget
modifier|*
DECL|function|gimp_dialog_factory_dock_new (GimpDialogFactory * factory)
name|gimp_dialog_factory_dock_new
parameter_list|(
name|GimpDialogFactory
modifier|*
name|factory
parameter_list|)
block|{
name|GtkWidget
modifier|*
name|dock
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_DIALOG_FACTORY
argument_list|(
name|factory
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
name|factory
operator|->
name|new_dock_func
operator|!=
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|dock
operator|=
name|factory
operator|->
name|new_dock_func
argument_list|(
name|factory
argument_list|,
name|factory
operator|->
name|context
argument_list|,
literal|0
argument_list|)
expr_stmt|;
if|if
condition|(
name|dock
condition|)
block|{
name|g_object_set_data
argument_list|(
name|G_OBJECT
argument_list|(
name|dock
argument_list|)
argument_list|,
literal|"gimp-dialog-factory"
argument_list|,
name|factory
argument_list|)
expr_stmt|;
name|gimp_dialog_factory_add_dialog
argument_list|(
name|factory
argument_list|,
name|dock
argument_list|)
expr_stmt|;
block|}
return|return
name|dock
return|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_dialog_factory_add_dialog (GimpDialogFactory * factory,GtkWidget * dialog)
name|gimp_dialog_factory_add_dialog
parameter_list|(
name|GimpDialogFactory
modifier|*
name|factory
parameter_list|,
name|GtkWidget
modifier|*
name|dialog
parameter_list|)
block|{
name|GimpDialogFactory
modifier|*
name|dialog_factory
decl_stmt|;
name|GimpDialogFactoryEntry
modifier|*
name|entry
decl_stmt|;
name|GimpSessionInfo
modifier|*
name|info
decl_stmt|;
name|GList
modifier|*
name|list
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_DIALOG_FACTORY
argument_list|(
name|factory
argument_list|)
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
name|GTK_IS_WIDGET
argument_list|(
name|dialog
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|g_list_find
argument_list|(
name|factory
operator|->
name|open_dialogs
argument_list|,
name|dialog
argument_list|)
condition|)
block|{
name|g_warning
argument_list|(
literal|"%s(): dialog already registered"
argument_list|,
name|G_GNUC_FUNCTION
argument_list|)
expr_stmt|;
return|return;
block|}
name|dialog_factory
operator|=
name|g_object_get_data
argument_list|(
name|G_OBJECT
argument_list|(
name|dialog
argument_list|)
argument_list|,
literal|"gimp-dialog-factory"
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|dialog_factory
condition|)
block|{
name|g_warning
argument_list|(
literal|"%s(): dialog was not created by a GimpDialogFactory"
argument_list|,
name|G_GNUC_FUNCTION
argument_list|)
expr_stmt|;
return|return;
block|}
if|if
condition|(
name|dialog_factory
operator|!=
name|factory
condition|)
block|{
name|g_warning
argument_list|(
literal|"%s(): dialog was created by a different GimpDialogFactory"
argument_list|,
name|G_GNUC_FUNCTION
argument_list|)
expr_stmt|;
return|return;
block|}
name|entry
operator|=
name|g_object_get_data
argument_list|(
name|G_OBJECT
argument_list|(
name|dialog
argument_list|)
argument_list|,
literal|"gimp-dialog-factory-entry"
argument_list|)
expr_stmt|;
if|if
condition|(
name|entry
condition|)
comment|/* dialog is a toplevel (but not a GimpDock) or a GimpDockable */
block|{
name|gboolean
name|toplevel
decl_stmt|;
name|toplevel
operator|=
name|GTK_WIDGET_TOPLEVEL
argument_list|(
name|dialog
argument_list|)
expr_stmt|;
name|g_print
argument_list|(
literal|"%s: registering %s \"%s\"\n"
argument_list|,
name|G_GNUC_FUNCTION
argument_list|,
name|toplevel
condition|?
literal|"toplevel"
else|:
literal|"dockable"
argument_list|,
name|entry
operator|->
name|identifier
argument_list|)
expr_stmt|;
for|for
control|(
name|list
operator|=
name|factory
operator|->
name|session_infos
init|;
name|list
condition|;
name|list
operator|=
name|g_list_next
argument_list|(
name|list
argument_list|)
control|)
block|{
name|info
operator|=
operator|(
name|GimpSessionInfo
operator|*
operator|)
name|list
operator|->
name|data
expr_stmt|;
if|if
condition|(
operator|(
operator|(
name|info
operator|->
name|toplevel_entry
operator|==
name|entry
operator|)
operator|&&
name|toplevel
operator|)
operator|||
operator|(
name|info
operator|->
name|dockable_entry
operator|==
name|entry
operator|)
condition|)
block|{
if|if
condition|(
name|entry
operator|->
name|singleton
condition|)
block|{
if|if
condition|(
name|info
operator|->
name|widget
condition|)
block|{
name|g_warning
argument_list|(
literal|"%s(): singleton dialog \"%s\"created twice"
argument_list|,
name|G_GNUC_FUNCTION
argument_list|,
name|entry
operator|->
name|identifier
argument_list|)
expr_stmt|;
return|return;
block|}
block|}
elseif|else
if|if
condition|(
name|info
operator|->
name|widget
condition|)
block|{
continue|continue;
block|}
name|info
operator|->
name|widget
operator|=
name|dialog
expr_stmt|;
if|if
condition|(
name|entry
operator|->
name|session_managed
condition|)
block|{
name|gimp_dialog_factory_set_window_geometry
argument_list|(
name|info
operator|->
name|widget
argument_list|,
name|info
argument_list|)
expr_stmt|;
block|}
break|break;
block|}
block|}
if|if
condition|(
operator|!
name|list
condition|)
comment|/*  didn't find a session info  */
block|{
name|info
operator|=
name|g_new0
argument_list|(
name|GimpSessionInfo
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|info
operator|->
name|widget
operator|=
name|dialog
expr_stmt|;
if|if
condition|(
name|toplevel
condition|)
name|info
operator|->
name|toplevel_entry
operator|=
name|entry
expr_stmt|;
else|else
name|info
operator|->
name|dockable_entry
operator|=
name|entry
expr_stmt|;
name|factory
operator|->
name|session_infos
operator|=
name|g_list_append
argument_list|(
name|factory
operator|->
name|session_infos
argument_list|,
name|info
argument_list|)
expr_stmt|;
block|}
block|}
elseif|else
if|if
condition|(
name|GIMP_IS_DOCK
argument_list|(
name|dialog
argument_list|)
condition|)
comment|/*  dialog is a GimpDock  */
block|{
name|g_print
argument_list|(
literal|"%s: registering dock\n"
argument_list|,
name|G_GNUC_FUNCTION
argument_list|)
expr_stmt|;
for|for
control|(
name|list
operator|=
name|factory
operator|->
name|session_infos
init|;
name|list
condition|;
name|list
operator|=
name|g_list_next
argument_list|(
name|list
argument_list|)
control|)
block|{
name|info
operator|=
operator|(
name|GimpSessionInfo
operator|*
operator|)
name|list
operator|->
name|data
expr_stmt|;
if|if
condition|(
operator|!
name|info
operator|->
name|widget
condition|)
comment|/*  take the first empty slot  */
block|{
name|info
operator|->
name|widget
operator|=
name|dialog
expr_stmt|;
name|gimp_dialog_factory_set_window_geometry
argument_list|(
name|info
operator|->
name|widget
argument_list|,
name|info
argument_list|)
expr_stmt|;
break|break;
block|}
block|}
if|if
condition|(
operator|!
name|list
condition|)
comment|/*  didn't find a session info  */
block|{
name|info
operator|=
name|g_new0
argument_list|(
name|GimpSessionInfo
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|info
operator|->
name|widget
operator|=
name|dialog
expr_stmt|;
name|factory
operator|->
name|session_infos
operator|=
name|g_list_append
argument_list|(
name|factory
operator|->
name|session_infos
argument_list|,
name|info
argument_list|)
expr_stmt|;
block|}
block|}
else|else
block|{
name|g_warning
argument_list|(
literal|"%s(): cannot add dialog which neither has a "
literal|"GimpDialogFactoryEntry attached nor is a GimpDock"
argument_list|,
name|G_GNUC_FUNCTION
argument_list|)
expr_stmt|;
return|return;
block|}
name|factory
operator|->
name|open_dialogs
operator|=
name|g_list_prepend
argument_list|(
name|factory
operator|->
name|open_dialogs
argument_list|,
name|dialog
argument_list|)
expr_stmt|;
name|g_signal_connect_object
argument_list|(
name|G_OBJECT
argument_list|(
name|dialog
argument_list|)
argument_list|,
literal|"destroy"
argument_list|,
name|G_CALLBACK
argument_list|(
name|gimp_dialog_factory_remove_dialog
argument_list|)
argument_list|,
name|factory
argument_list|,
name|G_CONNECT_SWAPPED
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_dialog_factory_remove_dialog (GimpDialogFactory * factory,GtkWidget * dialog)
name|gimp_dialog_factory_remove_dialog
parameter_list|(
name|GimpDialogFactory
modifier|*
name|factory
parameter_list|,
name|GtkWidget
modifier|*
name|dialog
parameter_list|)
block|{
name|GimpDialogFactory
modifier|*
name|dialog_factory
decl_stmt|;
name|GimpSessionInfo
modifier|*
name|session_info
decl_stmt|;
name|GList
modifier|*
name|list
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_DIALOG_FACTORY
argument_list|(
name|factory
argument_list|)
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
name|GTK_IS_WIDGET
argument_list|(
name|dialog
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|g_list_find
argument_list|(
name|factory
operator|->
name|open_dialogs
argument_list|,
name|dialog
argument_list|)
condition|)
block|{
name|g_warning
argument_list|(
literal|"%s(): dialog not registered"
argument_list|,
name|G_GNUC_FUNCTION
argument_list|)
expr_stmt|;
return|return;
block|}
name|factory
operator|->
name|open_dialogs
operator|=
name|g_list_remove
argument_list|(
name|factory
operator|->
name|open_dialogs
argument_list|,
name|dialog
argument_list|)
expr_stmt|;
name|dialog_factory
operator|=
name|g_object_get_data
argument_list|(
name|G_OBJECT
argument_list|(
name|dialog
argument_list|)
argument_list|,
literal|"gimp-dialog-factory"
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|dialog_factory
condition|)
block|{
name|g_warning
argument_list|(
literal|"%s(): dialog was not created by a GimpDialogFactory"
argument_list|,
name|G_GNUC_FUNCTION
argument_list|)
expr_stmt|;
return|return;
block|}
if|if
condition|(
name|dialog_factory
operator|!=
name|factory
condition|)
block|{
name|g_warning
argument_list|(
literal|"%s(): dialog was created by a different GimpDialogFactory"
argument_list|,
name|G_GNUC_FUNCTION
argument_list|)
expr_stmt|;
return|return;
block|}
for|for
control|(
name|list
operator|=
name|factory
operator|->
name|session_infos
init|;
name|list
condition|;
name|list
operator|=
name|g_list_next
argument_list|(
name|list
argument_list|)
control|)
block|{
name|session_info
operator|=
operator|(
name|GimpSessionInfo
operator|*
operator|)
name|list
operator|->
name|data
expr_stmt|;
if|if
condition|(
name|session_info
operator|->
name|widget
operator|==
name|dialog
condition|)
block|{
name|session_info
operator|->
name|widget
operator|=
name|NULL
expr_stmt|;
comment|/*  don't save session info for empty docks  */
if|if
condition|(
name|GIMP_IS_DOCK
argument_list|(
name|dialog
argument_list|)
condition|)
block|{
name|factory
operator|->
name|session_infos
operator|=
name|g_list_remove
argument_list|(
name|factory
operator|->
name|session_infos
argument_list|,
name|session_info
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|session_info
argument_list|)
expr_stmt|;
block|}
break|break;
block|}
block|}
block|}
end_function

begin_function
name|void
DECL|function|gimp_dialog_factories_session_save (FILE * file)
name|gimp_dialog_factories_session_save
parameter_list|(
name|FILE
modifier|*
name|file
parameter_list|)
block|{
name|GimpDialogFactoryClass
modifier|*
name|factory_class
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|file
operator|!=
name|NULL
argument_list|)
expr_stmt|;
name|factory_class
operator|=
name|g_type_class_peek
argument_list|(
name|GIMP_TYPE_DIALOG_FACTORY
argument_list|)
expr_stmt|;
name|g_hash_table_foreach
argument_list|(
name|factory_class
operator|->
name|factories
argument_list|,
operator|(
name|GHFunc
operator|)
name|gimp_dialog_factories_save_foreach
argument_list|,
name|file
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_dialog_factories_session_restore (void)
name|gimp_dialog_factories_session_restore
parameter_list|(
name|void
parameter_list|)
block|{
name|GimpDialogFactoryClass
modifier|*
name|factory_class
decl_stmt|;
name|factory_class
operator|=
name|g_type_class_peek
argument_list|(
name|GIMP_TYPE_DIALOG_FACTORY
argument_list|)
expr_stmt|;
name|g_hash_table_foreach
argument_list|(
name|factory_class
operator|->
name|factories
argument_list|,
operator|(
name|GHFunc
operator|)
name|gimp_dialog_factories_restore_foreach
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_dialog_factories_toggle (GimpDialogFactory * toolbox_factory,const gchar * toolbox_identifier)
name|gimp_dialog_factories_toggle
parameter_list|(
name|GimpDialogFactory
modifier|*
name|toolbox_factory
parameter_list|,
specifier|const
name|gchar
modifier|*
name|toolbox_identifier
parameter_list|)
block|{
specifier|static
name|GimpDialogShowState
name|toggle_state
init|=
name|GIMP_DIALOG_SHOW_ALL
decl_stmt|;
specifier|static
name|gboolean
name|doing_update
init|=
name|FALSE
decl_stmt|;
name|GimpDialogFactoryClass
modifier|*
name|factory_class
decl_stmt|;
if|if
condition|(
name|doing_update
condition|)
return|return;
name|doing_update
operator|=
name|TRUE
expr_stmt|;
name|factory_class
operator|=
name|g_type_class_peek
argument_list|(
name|GIMP_TYPE_DIALOG_FACTORY
argument_list|)
expr_stmt|;
switch|switch
condition|(
name|toggle_state
condition|)
block|{
case|case
name|GIMP_DIALOG_SHOW_ALL
case|:
name|toggle_state
operator|=
name|GIMP_DIALOG_HIDE_ALL
expr_stmt|;
name|g_hash_table_foreach
argument_list|(
name|factory_class
operator|->
name|factories
argument_list|,
operator|(
name|GHFunc
operator|)
name|gimp_dialog_factories_hide_foreach
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
break|break;
case|case
name|GIMP_DIALOG_HIDE_ALL
case|:
name|toggle_state
operator|=
name|GIMP_DIALOG_SHOW_TOOLBOX
expr_stmt|;
name|gimp_dialog_factory_dialog_raise
argument_list|(
name|toolbox_factory
argument_list|,
name|toolbox_identifier
argument_list|,
operator|-
literal|1
argument_list|)
expr_stmt|;
break|break;
case|case
name|GIMP_DIALOG_SHOW_TOOLBOX
case|:
name|toggle_state
operator|=
name|GIMP_DIALOG_SHOW_ALL
expr_stmt|;
name|g_hash_table_foreach
argument_list|(
name|factory_class
operator|->
name|factories
argument_list|,
operator|(
name|GHFunc
operator|)
name|gimp_dialog_factories_show_foreach
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
default|default:
break|break;
block|}
name|doing_update
operator|=
name|FALSE
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_dialog_factories_idle (void)
name|gimp_dialog_factories_idle
parameter_list|(
name|void
parameter_list|)
block|{
name|GimpDialogFactoryClass
modifier|*
name|factory_class
decl_stmt|;
name|factory_class
operator|=
name|g_type_class_peek
argument_list|(
name|GIMP_TYPE_DIALOG_FACTORY
argument_list|)
expr_stmt|;
name|g_hash_table_foreach
argument_list|(
name|factory_class
operator|->
name|factories
argument_list|,
operator|(
name|GHFunc
operator|)
name|gimp_dialog_factories_idle_foreach
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_dialog_factories_unidle (void)
name|gimp_dialog_factories_unidle
parameter_list|(
name|void
parameter_list|)
block|{
name|GimpDialogFactoryClass
modifier|*
name|factory_class
decl_stmt|;
name|factory_class
operator|=
name|g_type_class_peek
argument_list|(
name|GIMP_TYPE_DIALOG_FACTORY
argument_list|)
expr_stmt|;
name|g_hash_table_foreach
argument_list|(
name|factory_class
operator|->
name|factories
argument_list|,
operator|(
name|GHFunc
operator|)
name|gimp_dialog_factories_unidle_foreach
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/*  private functions  */
end_comment

begin_function
specifier|static
name|void
DECL|function|gimp_dialog_factories_save_foreach (gchar * name,GimpDialogFactory * factory,FILE * fp)
name|gimp_dialog_factories_save_foreach
parameter_list|(
name|gchar
modifier|*
name|name
parameter_list|,
name|GimpDialogFactory
modifier|*
name|factory
parameter_list|,
name|FILE
modifier|*
name|fp
parameter_list|)
block|{
name|GList
modifier|*
name|list
decl_stmt|;
for|for
control|(
name|list
operator|=
name|factory
operator|->
name|session_infos
init|;
name|list
condition|;
name|list
operator|=
name|g_list_next
argument_list|(
name|list
argument_list|)
control|)
block|{
name|GimpSessionInfo
modifier|*
name|info
decl_stmt|;
name|info
operator|=
operator|(
name|GimpSessionInfo
operator|*
operator|)
name|list
operator|->
name|data
expr_stmt|;
comment|/*  we keep session info entries for all toplevel dialogs created        *  by the factory but don't save them if they don't want to be        *  managed        */
if|if
condition|(
name|info
operator|->
name|dockable_entry
operator|||
operator|(
name|info
operator|->
name|toplevel_entry
operator|&&
operator|!
name|info
operator|->
name|toplevel_entry
operator|->
name|session_managed
operator|)
condition|)
continue|continue;
if|if
condition|(
name|info
operator|->
name|widget
condition|)
name|gimp_dialog_factory_get_window_info
argument_list|(
name|info
operator|->
name|widget
argument_list|,
name|info
argument_list|)
expr_stmt|;
name|fprintf
argument_list|(
name|fp
argument_list|,
literal|"(session-info \"%s\" \"%s\"\n"
argument_list|,
name|name
argument_list|,
name|info
operator|->
name|toplevel_entry
condition|?
name|info
operator|->
name|toplevel_entry
operator|->
name|identifier
else|:
literal|"dock"
argument_list|)
expr_stmt|;
name|fprintf
argument_list|(
name|fp
argument_list|,
literal|"    (position %d %d)"
argument_list|,
name|info
operator|->
name|x
argument_list|,
name|info
operator|->
name|y
argument_list|)
expr_stmt|;
if|if
condition|(
name|info
operator|->
name|width
operator|>
literal|0
operator|&&
name|info
operator|->
name|height
operator|>
literal|0
condition|)
name|fprintf
argument_list|(
name|fp
argument_list|,
literal|"\n    (size %d %d)"
argument_list|,
name|info
operator|->
name|width
argument_list|,
name|info
operator|->
name|height
argument_list|)
expr_stmt|;
if|if
condition|(
name|info
operator|->
name|open
condition|)
name|fprintf
argument_list|(
name|fp
argument_list|,
literal|"\n    (open-on-exit)"
argument_list|)
expr_stmt|;
comment|/*  save aux-info  */
if|if
condition|(
name|info
operator|->
name|widget
condition|)
block|{
name|gimp_dialog_factory_get_aux_info
argument_list|(
name|info
operator|->
name|widget
argument_list|,
name|info
argument_list|)
expr_stmt|;
if|if
condition|(
name|info
operator|->
name|aux_info
condition|)
block|{
name|GList
modifier|*
name|aux
decl_stmt|;
name|fprintf
argument_list|(
name|fp
argument_list|,
literal|"\n    (aux-info ("
argument_list|)
expr_stmt|;
for|for
control|(
name|aux
operator|=
name|info
operator|->
name|aux_info
init|;
name|aux
condition|;
name|aux
operator|=
name|g_list_next
argument_list|(
name|aux
argument_list|)
control|)
block|{
name|gchar
modifier|*
name|str
decl_stmt|;
name|str
operator|=
operator|(
name|gchar
operator|*
operator|)
name|aux
operator|->
name|data
expr_stmt|;
if|if
condition|(
name|aux
operator|->
name|prev
condition|)
name|fprintf
argument_list|(
name|fp
argument_list|,
literal|" \"%s\""
argument_list|,
name|str
argument_list|)
expr_stmt|;
else|else
name|fprintf
argument_list|(
name|fp
argument_list|,
literal|"\"%s\""
argument_list|,
name|str
argument_list|)
expr_stmt|;
block|}
name|fprintf
argument_list|(
name|fp
argument_list|,
literal|"))"
argument_list|)
expr_stmt|;
name|g_list_foreach
argument_list|(
name|info
operator|->
name|aux_info
argument_list|,
operator|(
name|GFunc
operator|)
name|g_free
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_list_free
argument_list|(
name|info
operator|->
name|aux_info
argument_list|)
expr_stmt|;
name|info
operator|->
name|aux_info
operator|=
name|NULL
expr_stmt|;
block|}
block|}
if|if
condition|(
operator|!
name|info
operator|->
name|toplevel_entry
operator|&&
name|info
operator|->
name|widget
condition|)
block|{
name|GimpDock
modifier|*
name|dock
decl_stmt|;
name|GList
modifier|*
name|books
decl_stmt|;
name|dock
operator|=
name|GIMP_DOCK
argument_list|(
name|info
operator|->
name|widget
argument_list|)
expr_stmt|;
name|fprintf
argument_list|(
name|fp
argument_list|,
literal|"\n    (dock "
argument_list|)
expr_stmt|;
for|for
control|(
name|books
operator|=
name|dock
operator|->
name|dockbooks
init|;
name|books
condition|;
name|books
operator|=
name|g_list_next
argument_list|(
name|books
argument_list|)
control|)
block|{
name|GimpDockbook
modifier|*
name|dockbook
decl_stmt|;
name|GList
modifier|*
name|children
decl_stmt|;
name|GList
modifier|*
name|pages
decl_stmt|;
name|dockbook
operator|=
operator|(
name|GimpDockbook
operator|*
operator|)
name|books
operator|->
name|data
expr_stmt|;
name|fprintf
argument_list|(
name|fp
argument_list|,
literal|"("
argument_list|)
expr_stmt|;
name|children
operator|=
name|gtk_container_get_children
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|dockbook
argument_list|)
argument_list|)
expr_stmt|;
for|for
control|(
name|pages
operator|=
name|children
init|;
name|pages
condition|;
name|pages
operator|=
name|g_list_next
argument_list|(
name|pages
argument_list|)
control|)
block|{
name|GimpDockable
modifier|*
name|dockable
decl_stmt|;
name|GimpDialogFactoryEntry
modifier|*
name|entry
decl_stmt|;
name|dockable
operator|=
operator|(
name|GimpDockable
operator|*
operator|)
name|pages
operator|->
name|data
expr_stmt|;
name|entry
operator|=
name|g_object_get_data
argument_list|(
name|G_OBJECT
argument_list|(
name|dockable
argument_list|)
argument_list|,
literal|"gimp-dialog-factory-entry"
argument_list|)
expr_stmt|;
if|if
condition|(
name|entry
condition|)
block|{
name|GimpContainerView
modifier|*
name|view
decl_stmt|;
name|gint
name|preview_size
init|=
operator|-
literal|1
decl_stmt|;
name|view
operator|=
name|gimp_container_view_get_by_dockable
argument_list|(
name|dockable
argument_list|)
expr_stmt|;
if|if
condition|(
name|view
operator|&&
name|view
operator|->
name|preview_size
operator|>=
literal|16
condition|)
block|{
name|preview_size
operator|=
name|view
operator|->
name|preview_size
expr_stmt|;
block|}
if|if
condition|(
name|preview_size
operator|>
literal|0
operator|&&
name|preview_size
operator|!=
name|entry
operator|->
name|preview_size
condition|)
block|{
name|fprintf
argument_list|(
name|fp
argument_list|,
literal|"\"%s@%d\""
argument_list|,
name|entry
operator|->
name|identifier
argument_list|,
name|preview_size
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|fprintf
argument_list|(
name|fp
argument_list|,
literal|"\"%s\""
argument_list|,
name|entry
operator|->
name|identifier
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|pages
operator|->
name|next
condition|)
name|fprintf
argument_list|(
name|fp
argument_list|,
literal|" "
argument_list|)
expr_stmt|;
block|}
block|}
name|g_list_free
argument_list|(
name|children
argument_list|)
expr_stmt|;
name|fprintf
argument_list|(
name|fp
argument_list|,
literal|")%s"
argument_list|,
name|books
operator|->
name|next
condition|?
literal|"\n          "
else|:
literal|""
argument_list|)
expr_stmt|;
block|}
name|fprintf
argument_list|(
name|fp
argument_list|,
literal|")"
argument_list|)
expr_stmt|;
block|}
name|fprintf
argument_list|(
name|fp
argument_list|,
literal|")\n\n"
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_dialog_factories_restore_foreach (gchar * name,GimpDialogFactory * factory,gpointer data)
name|gimp_dialog_factories_restore_foreach
parameter_list|(
name|gchar
modifier|*
name|name
parameter_list|,
name|GimpDialogFactory
modifier|*
name|factory
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GList
modifier|*
name|list
decl_stmt|;
for|for
control|(
name|list
operator|=
name|factory
operator|->
name|session_infos
init|;
name|list
condition|;
name|list
operator|=
name|g_list_next
argument_list|(
name|list
argument_list|)
control|)
block|{
name|GimpSessionInfo
modifier|*
name|info
decl_stmt|;
name|info
operator|=
operator|(
name|GimpSessionInfo
operator|*
operator|)
name|list
operator|->
name|data
expr_stmt|;
if|if
condition|(
operator|!
name|info
operator|->
name|open
condition|)
continue|continue;
name|info
operator|->
name|open
operator|=
name|FALSE
expr_stmt|;
if|if
condition|(
name|info
operator|->
name|toplevel_entry
condition|)
block|{
name|GtkWidget
modifier|*
name|dialog
decl_stmt|;
name|dialog
operator|=
name|gimp_dialog_factory_dialog_new
argument_list|(
name|factory
argument_list|,
name|info
operator|->
name|toplevel_entry
operator|->
name|identifier
argument_list|,
name|info
operator|->
name|toplevel_entry
operator|->
name|preview_size
argument_list|)
expr_stmt|;
if|if
condition|(
name|dialog
operator|&&
name|info
operator|->
name|aux_info
condition|)
name|gimp_dialog_factory_set_aux_info
argument_list|(
name|dialog
argument_list|,
name|info
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|GimpDock
modifier|*
name|dock
decl_stmt|;
name|GList
modifier|*
name|books
decl_stmt|;
name|dock
operator|=
name|GIMP_DOCK
argument_list|(
name|gimp_dialog_factory_dock_new
argument_list|(
name|factory
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|dock
operator|&&
name|info
operator|->
name|aux_info
condition|)
name|gimp_dialog_factory_set_aux_info
argument_list|(
name|GTK_WIDGET
argument_list|(
name|dock
argument_list|)
argument_list|,
name|info
argument_list|)
expr_stmt|;
for|for
control|(
name|books
operator|=
name|info
operator|->
name|sub_dialogs
init|;
name|books
condition|;
name|books
operator|=
name|g_list_next
argument_list|(
name|books
argument_list|)
control|)
block|{
name|GimpDockbook
modifier|*
name|dockbook
decl_stmt|;
name|GList
modifier|*
name|pages
decl_stmt|;
name|dockbook
operator|=
name|GIMP_DOCKBOOK
argument_list|(
name|gimp_dockbook_new
argument_list|()
argument_list|)
expr_stmt|;
name|gimp_dock_add_book
argument_list|(
name|dock
argument_list|,
name|dockbook
argument_list|,
operator|-
literal|1
argument_list|)
expr_stmt|;
for|for
control|(
name|pages
operator|=
name|books
operator|->
name|data
init|;
name|pages
condition|;
name|pages
operator|=
name|g_list_next
argument_list|(
name|pages
argument_list|)
control|)
block|{
name|GtkWidget
modifier|*
name|dockable
decl_stmt|;
name|gchar
modifier|*
name|identifier
decl_stmt|;
name|gchar
modifier|*
name|substring
decl_stmt|;
name|gint
name|preview_size
init|=
operator|-
literal|1
decl_stmt|;
name|identifier
operator|=
operator|(
name|gchar
operator|*
operator|)
name|pages
operator|->
name|data
expr_stmt|;
if|if
condition|(
operator|(
name|substring
operator|=
name|strstr
argument_list|(
name|identifier
argument_list|,
literal|"@"
argument_list|)
operator|)
condition|)
block|{
operator|*
name|substring
operator|=
literal|'\0'
expr_stmt|;
name|preview_size
operator|=
name|atoi
argument_list|(
name|substring
operator|+
literal|1
argument_list|)
expr_stmt|;
if|if
condition|(
name|preview_size
operator|<
literal|16
condition|)
name|preview_size
operator|=
operator|-
literal|1
expr_stmt|;
block|}
name|dockable
operator|=
name|gimp_dialog_factory_dockable_new
argument_list|(
name|factory
argument_list|,
name|dock
argument_list|,
name|identifier
argument_list|,
name|preview_size
argument_list|)
expr_stmt|;
if|if
condition|(
name|dockable
condition|)
name|gimp_dockbook_add
argument_list|(
name|dockbook
argument_list|,
name|GIMP_DOCKABLE
argument_list|(
name|dockable
argument_list|)
argument_list|,
operator|-
literal|1
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|identifier
argument_list|)
expr_stmt|;
block|}
name|g_list_free
argument_list|(
name|books
operator|->
name|data
argument_list|)
expr_stmt|;
block|}
name|g_list_free
argument_list|(
name|info
operator|->
name|sub_dialogs
argument_list|)
expr_stmt|;
name|info
operator|->
name|sub_dialogs
operator|=
name|NULL
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|GTK_WIDGET
argument_list|(
name|dock
argument_list|)
argument_list|)
expr_stmt|;
block|}
name|g_list_foreach
argument_list|(
name|info
operator|->
name|aux_info
argument_list|,
operator|(
name|GFunc
operator|)
name|g_free
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_list_free
argument_list|(
name|info
operator|->
name|aux_info
argument_list|)
expr_stmt|;
name|info
operator|->
name|aux_info
operator|=
name|NULL
expr_stmt|;
block|}
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_dialog_factory_get_window_info (GtkWidget * window,GimpSessionInfo * info)
name|gimp_dialog_factory_get_window_info
parameter_list|(
name|GtkWidget
modifier|*
name|window
parameter_list|,
name|GimpSessionInfo
modifier|*
name|info
parameter_list|)
block|{
name|g_return_if_fail
argument_list|(
name|GTK_IS_WIDGET
argument_list|(
name|window
argument_list|)
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
name|GTK_WIDGET_TOPLEVEL
argument_list|(
name|window
argument_list|)
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
name|info
operator|!=
name|NULL
argument_list|)
expr_stmt|;
if|if
condition|(
name|window
operator|->
name|window
condition|)
block|{
name|gdk_window_get_root_origin
argument_list|(
name|window
operator|->
name|window
argument_list|,
operator|&
name|info
operator|->
name|x
argument_list|,
operator|&
name|info
operator|->
name|y
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|info
operator|->
name|toplevel_entry
operator|||
name|info
operator|->
name|toplevel_entry
operator|->
name|remember_size
condition|)
block|{
name|info
operator|->
name|width
operator|=
name|window
operator|->
name|allocation
operator|.
name|width
expr_stmt|;
name|info
operator|->
name|height
operator|=
name|window
operator|->
name|allocation
operator|.
name|height
expr_stmt|;
block|}
else|else
block|{
name|info
operator|->
name|width
operator|=
literal|0
expr_stmt|;
name|info
operator|->
name|height
operator|=
literal|0
expr_stmt|;
block|}
block|}
if|if
condition|(
operator|!
name|info
operator|->
name|toplevel_entry
operator|||
name|info
operator|->
name|toplevel_entry
operator|->
name|remember_if_open
condition|)
name|info
operator|->
name|open
operator|=
name|GTK_WIDGET_VISIBLE
argument_list|(
name|window
argument_list|)
expr_stmt|;
else|else
name|info
operator|->
name|open
operator|=
name|FALSE
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_dialog_factory_set_window_geometry (GtkWidget * window,GimpSessionInfo * info)
name|gimp_dialog_factory_set_window_geometry
parameter_list|(
name|GtkWidget
modifier|*
name|window
parameter_list|,
name|GimpSessionInfo
modifier|*
name|info
parameter_list|)
block|{
specifier|static
name|gint
name|screen_width
init|=
literal|0
decl_stmt|;
specifier|static
name|gint
name|screen_height
init|=
literal|0
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GTK_IS_WINDOW
argument_list|(
name|window
argument_list|)
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
name|GTK_WIDGET_TOPLEVEL
argument_list|(
name|window
argument_list|)
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
name|info
operator|!=
name|NULL
argument_list|)
expr_stmt|;
if|if
condition|(
name|screen_width
operator|==
literal|0
operator|||
name|screen_height
operator|==
literal|0
condition|)
block|{
name|screen_width
operator|=
name|gdk_screen_width
argument_list|()
expr_stmt|;
name|screen_height
operator|=
name|gdk_screen_height
argument_list|()
expr_stmt|;
block|}
name|info
operator|->
name|x
operator|=
name|CLAMP
argument_list|(
name|info
operator|->
name|x
argument_list|,
literal|0
argument_list|,
name|screen_width
operator|-
literal|32
argument_list|)
expr_stmt|;
name|info
operator|->
name|y
operator|=
name|CLAMP
argument_list|(
name|info
operator|->
name|y
argument_list|,
literal|0
argument_list|,
name|screen_height
operator|-
literal|32
argument_list|)
expr_stmt|;
name|gtk_window_move
argument_list|(
name|GTK_WINDOW
argument_list|(
name|window
argument_list|)
argument_list|,
name|info
operator|->
name|x
argument_list|,
name|info
operator|->
name|y
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|info
operator|->
name|toplevel_entry
operator|||
name|info
operator|->
name|toplevel_entry
operator|->
name|remember_size
condition|)
block|{
if|if
condition|(
name|info
operator|->
name|width
operator|>
literal|0
operator|&&
name|info
operator|->
name|height
operator|>
literal|0
condition|)
name|gtk_window_set_default_size
argument_list|(
name|GTK_WINDOW
argument_list|(
name|window
argument_list|)
argument_list|,
name|info
operator|->
name|width
argument_list|,
name|info
operator|->
name|height
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_dialog_factory_get_aux_info (GtkWidget * dialog,GimpSessionInfo * info)
name|gimp_dialog_factory_get_aux_info
parameter_list|(
name|GtkWidget
modifier|*
name|dialog
parameter_list|,
name|GimpSessionInfo
modifier|*
name|info
parameter_list|)
block|{
comment|/* FIXME: make the aux-info stuff generic */
if|if
condition|(
name|GIMP_IS_IMAGE_DOCK
argument_list|(
name|dialog
argument_list|)
condition|)
block|{
name|GimpImageDock
modifier|*
name|dock
decl_stmt|;
name|dock
operator|=
name|GIMP_IMAGE_DOCK
argument_list|(
name|dialog
argument_list|)
expr_stmt|;
name|info
operator|->
name|aux_info
operator|=
name|g_list_append
argument_list|(
name|info
operator|->
name|aux_info
argument_list|,
name|dock
operator|->
name|show_image_menu
condition|?
name|g_strdup
argument_list|(
literal|"menu-shown"
argument_list|)
else|:
name|g_strdup
argument_list|(
literal|"menu-hidden"
argument_list|)
argument_list|)
expr_stmt|;
name|info
operator|->
name|aux_info
operator|=
name|g_list_append
argument_list|(
name|info
operator|->
name|aux_info
argument_list|,
name|dock
operator|->
name|auto_follow_active
condition|?
name|g_strdup
argument_list|(
literal|"follow-active-image"
argument_list|)
else|:
name|g_strdup
argument_list|(
literal|"dont-follow-active-image"
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_dialog_factory_set_aux_info (GtkWidget * dialog,GimpSessionInfo * info)
name|gimp_dialog_factory_set_aux_info
parameter_list|(
name|GtkWidget
modifier|*
name|dialog
parameter_list|,
name|GimpSessionInfo
modifier|*
name|info
parameter_list|)
block|{
name|GList
modifier|*
name|aux
decl_stmt|;
comment|/* FIXME: make the aux-info stuff generic */
if|if
condition|(
name|GIMP_IS_IMAGE_DOCK
argument_list|(
name|dialog
argument_list|)
condition|)
block|{
name|gboolean
name|menu_shown
init|=
name|TRUE
decl_stmt|;
name|gboolean
name|auto_follow
init|=
name|TRUE
decl_stmt|;
for|for
control|(
name|aux
operator|=
name|info
operator|->
name|aux_info
init|;
name|aux
condition|;
name|aux
operator|=
name|g_list_next
argument_list|(
name|aux
argument_list|)
control|)
block|{
name|gchar
modifier|*
name|str
decl_stmt|;
name|str
operator|=
operator|(
name|gchar
operator|*
operator|)
name|aux
operator|->
name|data
expr_stmt|;
if|if
condition|(
operator|!
name|strcmp
argument_list|(
name|str
argument_list|,
literal|"menu-shown"
argument_list|)
condition|)
name|menu_shown
operator|=
name|TRUE
expr_stmt|;
elseif|else
if|if
condition|(
operator|!
name|strcmp
argument_list|(
name|str
argument_list|,
literal|"menu-hidden"
argument_list|)
condition|)
name|menu_shown
operator|=
name|FALSE
expr_stmt|;
elseif|else
if|if
condition|(
operator|!
name|strcmp
argument_list|(
name|str
argument_list|,
literal|"follow-active-image"
argument_list|)
condition|)
name|auto_follow
operator|=
name|TRUE
expr_stmt|;
elseif|else
if|if
condition|(
operator|!
name|strcmp
argument_list|(
name|str
argument_list|,
literal|"dont-follow-active-image"
argument_list|)
condition|)
name|auto_follow
operator|=
name|FALSE
expr_stmt|;
block|}
name|gimp_image_dock_set_show_image_menu
argument_list|(
name|GIMP_IMAGE_DOCK
argument_list|(
name|dialog
argument_list|)
argument_list|,
name|menu_shown
argument_list|)
expr_stmt|;
name|gimp_image_dock_set_auto_follow_active
argument_list|(
name|GIMP_IMAGE_DOCK
argument_list|(
name|dialog
argument_list|)
argument_list|,
name|auto_follow
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_dialog_factories_hide_foreach (gchar * name,GimpDialogFactory * factory,gpointer data)
name|gimp_dialog_factories_hide_foreach
parameter_list|(
name|gchar
modifier|*
name|name
parameter_list|,
name|GimpDialogFactory
modifier|*
name|factory
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GList
modifier|*
name|list
decl_stmt|;
for|for
control|(
name|list
operator|=
name|factory
operator|->
name|open_dialogs
init|;
name|list
condition|;
name|list
operator|=
name|g_list_next
argument_list|(
name|list
argument_list|)
control|)
block|{
if|if
condition|(
name|GTK_IS_WIDGET
argument_list|(
name|list
operator|->
name|data
argument_list|)
operator|&&
name|GTK_WIDGET_TOPLEVEL
argument_list|(
name|list
operator|->
name|data
argument_list|)
condition|)
block|{
name|GimpDialogVisibilityState
name|visibility
init|=
name|GIMP_DIALOG_VISIBILITY_UNKNOWN
decl_stmt|;
if|if
condition|(
name|GTK_WIDGET_VISIBLE
argument_list|(
name|list
operator|->
name|data
argument_list|)
condition|)
block|{
name|visibility
operator|=
name|GIMP_DIALOG_VISIBILITY_VISIBLE
expr_stmt|;
name|gtk_widget_hide
argument_list|(
name|GTK_WIDGET
argument_list|(
name|list
operator|->
name|data
argument_list|)
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|visibility
operator|=
name|GIMP_DIALOG_VISIBILITY_INVISIBLE
expr_stmt|;
block|}
name|g_object_set_data
argument_list|(
name|G_OBJECT
argument_list|(
name|list
operator|->
name|data
argument_list|)
argument_list|,
literal|"gimp-dialog-visibility"
argument_list|,
name|GINT_TO_POINTER
argument_list|(
name|visibility
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_dialog_factories_show_foreach (gchar * name,GimpDialogFactory * factory,gpointer data)
name|gimp_dialog_factories_show_foreach
parameter_list|(
name|gchar
modifier|*
name|name
parameter_list|,
name|GimpDialogFactory
modifier|*
name|factory
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GList
modifier|*
name|list
decl_stmt|;
for|for
control|(
name|list
operator|=
name|factory
operator|->
name|open_dialogs
init|;
name|list
condition|;
name|list
operator|=
name|g_list_next
argument_list|(
name|list
argument_list|)
control|)
block|{
if|if
condition|(
name|GTK_IS_WIDGET
argument_list|(
name|list
operator|->
name|data
argument_list|)
operator|&&
name|GTK_WIDGET_TOPLEVEL
argument_list|(
name|list
operator|->
name|data
argument_list|)
condition|)
block|{
name|GimpDialogVisibilityState
name|visibility
decl_stmt|;
name|visibility
operator|=
name|GPOINTER_TO_INT
argument_list|(
name|g_object_get_data
argument_list|(
name|G_OBJECT
argument_list|(
name|list
operator|->
name|data
argument_list|)
argument_list|,
literal|"gimp-dialog-visibility"
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|GTK_WIDGET_VISIBLE
argument_list|(
name|list
operator|->
name|data
argument_list|)
operator|&&
name|visibility
operator|==
name|GIMP_DIALOG_VISIBILITY_VISIBLE
condition|)
block|{
name|gtk_widget_show
argument_list|(
name|GTK_WIDGET
argument_list|(
name|list
operator|->
name|data
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
block|}
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_dialog_factories_idle_foreach (gchar * name,GimpDialogFactory * factory,gpointer data)
name|gimp_dialog_factories_idle_foreach
parameter_list|(
name|gchar
modifier|*
name|name
parameter_list|,
name|GimpDialogFactory
modifier|*
name|factory
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GdkCursor
modifier|*
name|cursor
decl_stmt|;
name|GList
modifier|*
name|list
decl_stmt|;
name|cursor
operator|=
name|gimp_cursor_new
argument_list|(
name|GDK_WATCH
argument_list|,
name|GIMP_TOOL_CURSOR_NONE
argument_list|,
name|GIMP_CURSOR_MODIFIER_NONE
argument_list|)
expr_stmt|;
for|for
control|(
name|list
operator|=
name|factory
operator|->
name|open_dialogs
init|;
name|list
condition|;
name|list
operator|=
name|g_list_next
argument_list|(
name|list
argument_list|)
control|)
block|{
if|if
condition|(
name|GTK_IS_WIDGET
argument_list|(
name|list
operator|->
name|data
argument_list|)
operator|&&
name|GTK_WIDGET_TOPLEVEL
argument_list|(
name|list
operator|->
name|data
argument_list|)
operator|&&
name|GTK_WIDGET_VISIBLE
argument_list|(
name|list
operator|->
name|data
argument_list|)
condition|)
block|{
name|gdk_window_set_cursor
argument_list|(
name|GTK_WIDGET
argument_list|(
name|list
operator|->
name|data
argument_list|)
operator|->
name|window
argument_list|,
name|cursor
argument_list|)
expr_stmt|;
block|}
block|}
name|gdk_cursor_unref
argument_list|(
name|cursor
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_dialog_factories_unidle_foreach (gchar * name,GimpDialogFactory * factory,gpointer data)
name|gimp_dialog_factories_unidle_foreach
parameter_list|(
name|gchar
modifier|*
name|name
parameter_list|,
name|GimpDialogFactory
modifier|*
name|factory
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GList
modifier|*
name|list
decl_stmt|;
for|for
control|(
name|list
operator|=
name|factory
operator|->
name|open_dialogs
init|;
name|list
condition|;
name|list
operator|=
name|g_list_next
argument_list|(
name|list
argument_list|)
control|)
block|{
if|if
condition|(
name|GTK_IS_WIDGET
argument_list|(
name|list
operator|->
name|data
argument_list|)
operator|&&
name|GTK_WIDGET_TOPLEVEL
argument_list|(
name|list
operator|->
name|data
argument_list|)
operator|&&
name|GTK_WIDGET_VISIBLE
argument_list|(
name|list
operator|->
name|data
argument_list|)
condition|)
block|{
name|gdk_window_set_cursor
argument_list|(
name|GTK_WIDGET
argument_list|(
name|list
operator|->
name|data
argument_list|)
operator|->
name|window
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
block|}
block|}
block|}
end_function

end_unit

