begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* The GIMP -- an image manipulation program  * Copyright (C) 1995 Spencer Kimball and Peter Mattis  *  * gimpchanneltreeview.c  * Copyright (C) 2001-2004 Michael Natterer<mitch@gimp.org>  *  * This program is free software; you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 2 of the License, or  * (at your option) any later version.  *  * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *  * You should have received a copy of the GNU General Public License  * along with this program; if not, write to the Free Software  * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  */
end_comment

begin_include
include|#
directive|include
file|"config.h"
end_include

begin_include
include|#
directive|include
file|<gtk/gtk.h>
end_include

begin_include
include|#
directive|include
file|"libgimpcolor/gimpcolor.h"
end_include

begin_include
include|#
directive|include
file|"libgimpwidgets/gimpwidgets.h"
end_include

begin_include
include|#
directive|include
file|"widgets-types.h"
end_include

begin_include
include|#
directive|include
file|"core/gimpchannel.h"
end_include

begin_include
include|#
directive|include
file|"core/gimpcontainer.h"
end_include

begin_include
include|#
directive|include
file|"core/gimpimage.h"
end_include

begin_include
include|#
directive|include
file|"core/gimpimage-undo.h"
end_include

begin_include
include|#
directive|include
file|"gimpchanneltreeview.h"
end_include

begin_include
include|#
directive|include
file|"gimpcomponenteditor.h"
end_include

begin_include
include|#
directive|include
file|"gimpcontainerview.h"
end_include

begin_include
include|#
directive|include
file|"gimpdnd.h"
end_include

begin_include
include|#
directive|include
file|"gimphelp-ids.h"
end_include

begin_include
include|#
directive|include
file|"gimpwidgets-utils.h"
end_include

begin_include
include|#
directive|include
file|"gimp-intl.h"
end_include

begin_function_decl
specifier|static
name|void
name|gimp_channel_tree_view_class_init
parameter_list|(
name|GimpChannelTreeViewClass
modifier|*
name|klass
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_channel_tree_view_init
parameter_list|(
name|GimpChannelTreeView
modifier|*
name|view
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_channel_tree_view_view_iface_init
parameter_list|(
name|GimpContainerViewInterface
modifier|*
name|view_iface
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|GObject
modifier|*
name|gimp_channel_tree_view_constructor
parameter_list|(
name|GType
name|type
parameter_list|,
name|guint
name|n_params
parameter_list|,
name|GObjectConstructParam
modifier|*
name|params
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_channel_tree_view_set_image
parameter_list|(
name|GimpItemTreeView
modifier|*
name|item_view
parameter_list|,
name|GimpImage
modifier|*
name|gimage
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|GimpItem
modifier|*
name|gimp_channel_tree_view_item_new
parameter_list|(
name|GimpImage
modifier|*
name|image
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_channel_tree_view_set_preview_size
parameter_list|(
name|GimpContainerView
modifier|*
name|view
parameter_list|)
function_decl|;
end_function_decl

begin_decl_stmt
DECL|variable|parent_class
specifier|static
name|GimpDrawableTreeViewClass
modifier|*
name|parent_class
init|=
name|NULL
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|parent_view_iface
specifier|static
name|GimpContainerViewInterface
modifier|*
name|parent_view_iface
init|=
name|NULL
decl_stmt|;
end_decl_stmt

begin_function
name|GType
DECL|function|gimp_channel_tree_view_get_type (void)
name|gimp_channel_tree_view_get_type
parameter_list|(
name|void
parameter_list|)
block|{
specifier|static
name|GType
name|view_type
init|=
literal|0
decl_stmt|;
if|if
condition|(
operator|!
name|view_type
condition|)
block|{
specifier|static
specifier|const
name|GTypeInfo
name|view_info
init|=
block|{
sizeof|sizeof
argument_list|(
name|GimpChannelTreeViewClass
argument_list|)
block|,
name|NULL
block|,
comment|/* base_init */
name|NULL
block|,
comment|/* base_finalize */
operator|(
name|GClassInitFunc
operator|)
name|gimp_channel_tree_view_class_init
block|,
name|NULL
block|,
comment|/* class_finalize */
name|NULL
block|,
comment|/* class_data */
sizeof|sizeof
argument_list|(
name|GimpChannelTreeView
argument_list|)
block|,
literal|0
block|,
comment|/* n_preallocs */
operator|(
name|GInstanceInitFunc
operator|)
name|gimp_channel_tree_view_init
block|,       }
decl_stmt|;
specifier|static
specifier|const
name|GInterfaceInfo
name|view_iface_info
init|=
block|{
operator|(
name|GInterfaceInitFunc
operator|)
name|gimp_channel_tree_view_view_iface_init
block|,
name|NULL
block|,
comment|/* iface_finalize */
name|NULL
comment|/* iface_data     */
block|}
decl_stmt|;
name|view_type
operator|=
name|g_type_register_static
argument_list|(
name|GIMP_TYPE_DRAWABLE_TREE_VIEW
argument_list|,
literal|"GimpChannelTreeView"
argument_list|,
operator|&
name|view_info
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|g_type_add_interface_static
argument_list|(
name|view_type
argument_list|,
name|GIMP_TYPE_CONTAINER_VIEW
argument_list|,
operator|&
name|view_iface_info
argument_list|)
expr_stmt|;
block|}
return|return
name|view_type
return|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_channel_tree_view_class_init (GimpChannelTreeViewClass * klass)
name|gimp_channel_tree_view_class_init
parameter_list|(
name|GimpChannelTreeViewClass
modifier|*
name|klass
parameter_list|)
block|{
name|GObjectClass
modifier|*
name|object_class
init|=
name|G_OBJECT_CLASS
argument_list|(
name|klass
argument_list|)
decl_stmt|;
name|GimpItemTreeViewClass
modifier|*
name|item_view_class
init|=
name|GIMP_ITEM_TREE_VIEW_CLASS
argument_list|(
name|klass
argument_list|)
decl_stmt|;
name|parent_class
operator|=
name|g_type_class_peek_parent
argument_list|(
name|klass
argument_list|)
expr_stmt|;
name|object_class
operator|->
name|constructor
operator|=
name|gimp_channel_tree_view_constructor
expr_stmt|;
name|item_view_class
operator|->
name|set_image
operator|=
name|gimp_channel_tree_view_set_image
expr_stmt|;
name|item_view_class
operator|->
name|item_type
operator|=
name|GIMP_TYPE_CHANNEL
expr_stmt|;
name|item_view_class
operator|->
name|signal_name
operator|=
literal|"active-channel-changed"
expr_stmt|;
name|item_view_class
operator|->
name|get_container
operator|=
name|gimp_image_get_channels
expr_stmt|;
name|item_view_class
operator|->
name|get_active_item
operator|=
operator|(
name|GimpGetItemFunc
operator|)
name|gimp_image_get_active_channel
expr_stmt|;
name|item_view_class
operator|->
name|set_active_item
operator|=
operator|(
name|GimpSetItemFunc
operator|)
name|gimp_image_set_active_channel
expr_stmt|;
name|item_view_class
operator|->
name|reorder_item
operator|=
operator|(
name|GimpReorderItemFunc
operator|)
name|gimp_image_position_channel
expr_stmt|;
name|item_view_class
operator|->
name|add_item
operator|=
operator|(
name|GimpAddItemFunc
operator|)
name|gimp_image_add_channel
expr_stmt|;
name|item_view_class
operator|->
name|remove_item
operator|=
operator|(
name|GimpRemoveItemFunc
operator|)
name|gimp_image_remove_channel
expr_stmt|;
name|item_view_class
operator|->
name|new_item
operator|=
name|gimp_channel_tree_view_item_new
expr_stmt|;
name|item_view_class
operator|->
name|action_group
operator|=
literal|"channels"
expr_stmt|;
name|item_view_class
operator|->
name|activate_action
operator|=
literal|"channels-edit-attributes"
expr_stmt|;
name|item_view_class
operator|->
name|edit_action
operator|=
literal|"channels-edit-attributes"
expr_stmt|;
name|item_view_class
operator|->
name|new_action
operator|=
literal|"channels-new"
expr_stmt|;
name|item_view_class
operator|->
name|new_default_action
operator|=
literal|"channels-new-last-values"
expr_stmt|;
name|item_view_class
operator|->
name|raise_action
operator|=
literal|"channels-raise"
expr_stmt|;
name|item_view_class
operator|->
name|raise_top_action
operator|=
literal|"channels-raise-to-top"
expr_stmt|;
name|item_view_class
operator|->
name|lower_action
operator|=
literal|"channels-lower"
expr_stmt|;
name|item_view_class
operator|->
name|lower_bottom_action
operator|=
literal|"channels-lower-to-bottom"
expr_stmt|;
name|item_view_class
operator|->
name|duplicate_action
operator|=
literal|"channels-duplicate"
expr_stmt|;
name|item_view_class
operator|->
name|delete_action
operator|=
literal|"channels-delete"
expr_stmt|;
name|item_view_class
operator|->
name|reorder_desc
operator|=
name|_
argument_list|(
literal|"Reorder Channel"
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_channel_tree_view_init (GimpChannelTreeView * view)
name|gimp_channel_tree_view_init
parameter_list|(
name|GimpChannelTreeView
modifier|*
name|view
parameter_list|)
block|{ }
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_channel_tree_view_view_iface_init (GimpContainerViewInterface * view_iface)
name|gimp_channel_tree_view_view_iface_init
parameter_list|(
name|GimpContainerViewInterface
modifier|*
name|view_iface
parameter_list|)
block|{
name|parent_view_iface
operator|=
name|g_type_interface_peek_parent
argument_list|(
name|view_iface
argument_list|)
expr_stmt|;
name|view_iface
operator|->
name|set_preview_size
operator|=
name|gimp_channel_tree_view_set_preview_size
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|GObject
modifier|*
DECL|function|gimp_channel_tree_view_constructor (GType type,guint n_params,GObjectConstructParam * params)
name|gimp_channel_tree_view_constructor
parameter_list|(
name|GType
name|type
parameter_list|,
name|guint
name|n_params
parameter_list|,
name|GObjectConstructParam
modifier|*
name|params
parameter_list|)
block|{
name|GObject
modifier|*
name|object
decl_stmt|;
name|GimpEditor
modifier|*
name|editor
decl_stmt|;
name|GimpChannelTreeView
modifier|*
name|view
decl_stmt|;
name|object
operator|=
name|G_OBJECT_CLASS
argument_list|(
name|parent_class
argument_list|)
operator|->
name|constructor
argument_list|(
name|type
argument_list|,
name|n_params
argument_list|,
name|params
argument_list|)
expr_stmt|;
name|editor
operator|=
name|GIMP_EDITOR
argument_list|(
name|object
argument_list|)
expr_stmt|;
name|view
operator|=
name|GIMP_CHANNEL_TREE_VIEW
argument_list|(
name|object
argument_list|)
expr_stmt|;
name|view
operator|->
name|toselection_button
operator|=
name|gimp_editor_add_action_button
argument_list|(
name|GIMP_EDITOR
argument_list|(
name|view
argument_list|)
argument_list|,
literal|"channels"
argument_list|,
literal|"channels-selection-replace"
argument_list|,
literal|"channels-selection-add"
argument_list|,
name|GDK_SHIFT_MASK
argument_list|,
literal|"channels-selection-subtract"
argument_list|,
name|GDK_CONTROL_MASK
argument_list|,
literal|"channels-selection-intersect"
argument_list|,
name|GDK_SHIFT_MASK
operator||
name|GDK_CONTROL_MASK
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|gimp_container_view_enable_dnd
argument_list|(
name|GIMP_CONTAINER_VIEW
argument_list|(
name|view
argument_list|)
argument_list|,
name|GTK_BUTTON
argument_list|(
name|view
operator|->
name|toselection_button
argument_list|)
argument_list|,
name|GIMP_TYPE_CHANNEL
argument_list|)
expr_stmt|;
name|gtk_box_reorder_child
argument_list|(
name|GTK_BOX
argument_list|(
name|GIMP_EDITOR
argument_list|(
name|view
argument_list|)
operator|->
name|button_box
argument_list|)
argument_list|,
name|view
operator|->
name|toselection_button
argument_list|,
literal|5
argument_list|)
expr_stmt|;
return|return
name|object
return|;
block|}
end_function

begin_comment
comment|/*  GimpItemTreeView methods  */
end_comment

begin_function
specifier|static
name|void
DECL|function|gimp_channel_tree_view_set_image (GimpItemTreeView * item_view,GimpImage * gimage)
name|gimp_channel_tree_view_set_image
parameter_list|(
name|GimpItemTreeView
modifier|*
name|item_view
parameter_list|,
name|GimpImage
modifier|*
name|gimage
parameter_list|)
block|{
name|GimpChannelTreeView
modifier|*
name|channel_view
init|=
name|GIMP_CHANNEL_TREE_VIEW
argument_list|(
name|item_view
argument_list|)
decl_stmt|;
if|if
condition|(
operator|!
name|channel_view
operator|->
name|component_editor
condition|)
block|{
name|GimpContainerView
modifier|*
name|view
init|=
name|GIMP_CONTAINER_VIEW
argument_list|(
name|item_view
argument_list|)
decl_stmt|;
name|gint
name|preview_size
decl_stmt|;
name|preview_size
operator|=
name|gimp_container_view_get_preview_size
argument_list|(
name|view
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|channel_view
operator|->
name|component_editor
operator|=
name|gimp_component_editor_new
argument_list|(
name|preview_size
argument_list|,
name|GIMP_EDITOR
argument_list|(
name|item_view
argument_list|)
operator|->
name|menu_factory
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|item_view
argument_list|)
argument_list|,
name|channel_view
operator|->
name|component_editor
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_box_reorder_child
argument_list|(
name|GTK_BOX
argument_list|(
name|item_view
argument_list|)
argument_list|,
name|channel_view
operator|->
name|component_editor
argument_list|,
literal|0
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
operator|!
name|gimage
condition|)
name|gtk_widget_hide
argument_list|(
name|channel_view
operator|->
name|component_editor
argument_list|)
expr_stmt|;
name|gimp_image_editor_set_image
argument_list|(
name|GIMP_IMAGE_EDITOR
argument_list|(
name|channel_view
operator|->
name|component_editor
argument_list|)
argument_list|,
name|gimage
argument_list|)
expr_stmt|;
name|GIMP_ITEM_TREE_VIEW_CLASS
argument_list|(
name|parent_class
argument_list|)
operator|->
name|set_image
argument_list|(
name|item_view
argument_list|,
name|gimage
argument_list|)
expr_stmt|;
if|if
condition|(
name|item_view
operator|->
name|gimage
condition|)
name|gtk_widget_show
argument_list|(
name|channel_view
operator|->
name|component_editor
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|GimpItem
modifier|*
DECL|function|gimp_channel_tree_view_item_new (GimpImage * image)
name|gimp_channel_tree_view_item_new
parameter_list|(
name|GimpImage
modifier|*
name|image
parameter_list|)
block|{
name|GimpChannel
modifier|*
name|new_channel
decl_stmt|;
name|GimpRGB
name|color
decl_stmt|;
name|gimp_rgba_set
argument_list|(
operator|&
name|color
argument_list|,
literal|0.0
argument_list|,
literal|0.0
argument_list|,
literal|0.0
argument_list|,
literal|0.5
argument_list|)
expr_stmt|;
name|gimp_image_undo_group_start
argument_list|(
name|image
argument_list|,
name|GIMP_UNDO_GROUP_EDIT_PASTE
argument_list|,
name|_
argument_list|(
literal|"New Channel"
argument_list|)
argument_list|)
expr_stmt|;
name|new_channel
operator|=
name|gimp_channel_new
argument_list|(
name|image
argument_list|,
name|gimp_image_get_width
argument_list|(
name|image
argument_list|)
argument_list|,
name|gimp_image_get_height
argument_list|(
name|image
argument_list|)
argument_list|,
name|_
argument_list|(
literal|"Empty Channel"
argument_list|)
argument_list|,
operator|&
name|color
argument_list|)
expr_stmt|;
name|gimp_image_add_channel
argument_list|(
name|image
argument_list|,
name|new_channel
argument_list|,
operator|-
literal|1
argument_list|)
expr_stmt|;
name|gimp_image_undo_group_end
argument_list|(
name|image
argument_list|)
expr_stmt|;
return|return
name|GIMP_ITEM
argument_list|(
name|new_channel
argument_list|)
return|;
block|}
end_function

begin_comment
comment|/*  GimpContainerView methods  */
end_comment

begin_function
specifier|static
name|void
DECL|function|gimp_channel_tree_view_set_preview_size (GimpContainerView * view)
name|gimp_channel_tree_view_set_preview_size
parameter_list|(
name|GimpContainerView
modifier|*
name|view
parameter_list|)
block|{
name|GimpChannelTreeView
modifier|*
name|channel_view
init|=
name|GIMP_CHANNEL_TREE_VIEW
argument_list|(
name|view
argument_list|)
decl_stmt|;
name|gint
name|preview_size
decl_stmt|;
name|parent_view_iface
operator|->
name|set_preview_size
argument_list|(
name|view
argument_list|)
expr_stmt|;
name|preview_size
operator|=
name|gimp_container_view_get_preview_size
argument_list|(
name|view
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
if|if
condition|(
name|channel_view
operator|->
name|component_editor
condition|)
name|gimp_component_editor_set_preview_size
argument_list|(
name|GIMP_COMPONENT_EDITOR
argument_list|(
name|channel_view
operator|->
name|component_editor
argument_list|)
argument_list|,
name|preview_size
argument_list|)
expr_stmt|;
block|}
end_function

end_unit

