begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* Generated data (by gimp-mkproxy) */
end_comment

begin_ifndef
ifndef|#
directive|ifndef
name|__GIMP_PROXY_TYPES_H__
end_ifndef

begin_define
DECL|macro|__GIMP_PROXY_TYPES_H__
define|#
directive|define
name|__GIMP_PROXY_TYPES_H__
end_define

begin_comment
comment|/* autogenerated from "./../app/core/core-enums.h" */
end_comment

begin_comment
comment|/* The GIMP -- an image manipulation program  * Copyright (C) 1995 Spencer Kimball and Peter Mattis  *  * This program is free software; you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 2 of the License, or  * (at your option) any later version.  *  * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *  * You should have received a copy of the GNU General Public License  * along with this program; if not, write to the Free Software  * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  */
end_comment

begin_typedef
typedef|typedef
enum|enum
comment|/*< proxy-resume>*/
comment|/*< skip>*/
DECL|enum|__anon2950ddf90103
block|{
DECL|enumerator|GIMP_CHANNEL_OP_ADD
name|GIMP_CHANNEL_OP_ADD
block|,
DECL|enumerator|GIMP_CHANNEL_OP_SUBTRACT
name|GIMP_CHANNEL_OP_SUBTRACT
block|,
DECL|enumerator|GIMP_CHANNEL_OP_REPLACE
name|GIMP_CHANNEL_OP_REPLACE
block|,
DECL|enumerator|GIMP_CHANNEL_OP_INTERSECT
name|GIMP_CHANNEL_OP_INTERSECT
DECL|typedef|GimpChannelOps
block|}
name|GimpChannelOps
typedef|;
end_typedef

begin_comment
comment|/* autogenerated from "./../app/core/core-types.h" */
end_comment

begin_comment
comment|/* The GIMP -- an image manipulation program  * Copyright (C) 1995 Spencer Kimball and Peter Mattis  *  * This program is free software; you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 2 of the License, or  * (at your option) any later version.  *  * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *  * You should have received a copy of the GNU General Public License  * along with this program; if not, write to the Free Software  * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  */
end_comment

begin_typedef
DECL|typedef|GimpObject
typedef|typedef
name|struct
name|_GimpObject
name|GimpObject
typedef|;
end_typedef

begin_comment
DECL|typedef|GimpObject
comment|/*< proxy-include>*/
end_comment

begin_typedef
DECL|typedef|GimpToolInfo
typedef|typedef
name|struct
name|_GimpToolInfo
name|GimpToolInfo
typedef|;
end_typedef

begin_comment
DECL|typedef|GimpToolInfo
comment|/*< proxy-include>*/
end_comment

begin_typedef
DECL|typedef|GimpDrawable
typedef|typedef
name|struct
name|_GimpDrawable
name|GimpDrawable
typedef|;
end_typedef

begin_comment
DECL|typedef|GimpDrawable
comment|/*< proxy-resume>*/
end_comment

begin_typedef
DECL|typedef|GimpChannel
typedef|typedef
name|struct
name|_GimpChannel
name|GimpChannel
typedef|;
end_typedef

begin_typedef
DECL|typedef|GimpLayer
typedef|typedef
name|struct
name|_GimpLayer
name|GimpLayer
typedef|;
end_typedef

begin_typedef
DECL|typedef|GimpLayerMask
typedef|typedef
name|struct
name|_GimpLayerMask
name|GimpLayerMask
typedef|;
end_typedef

begin_typedef
DECL|typedef|GimpImage
typedef|typedef
name|struct
name|_GimpImage
name|GimpImage
typedef|;
end_typedef

begin_comment
comment|/*  data objects  */
end_comment

begin_typedef
DECL|typedef|GimpCoords
typedef|typedef
name|struct
name|_GimpCoords
name|GimpCoords
typedef|;
end_typedef

begin_comment
DECL|typedef|GimpCoords
comment|/*< proxy-include>*/
end_comment

begin_typedef
DECL|typedef|GimpToolOptions
typedef|typedef
name|struct
name|_GimpToolOptions
name|GimpToolOptions
typedef|;
end_typedef

begin_comment
DECL|typedef|GimpToolOptions
comment|/*< proxy-include>*/
end_comment

begin_comment
comment|/* autogenerated from "./../app/widgets/widgets-enums.h" */
end_comment

begin_comment
comment|/* The GIMP -- an image manipulation program  * Copyright (C) 1995 Spencer Kimball and Peter Mattis  *  * This program is free software; you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 2 of the License, or  * (at your option) any later version.  *  * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *  * You should have received a copy of the GNU General Public License  * along with this program; if not, write to the Free Software  * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  */
end_comment

begin_typedef
typedef|typedef
enum|enum
comment|/*< skip, proxy-resume>*/
DECL|enum|__anon2950ddf90203
block|{
DECL|enumerator|GIMP_TOOL_CURSOR_NONE
name|GIMP_TOOL_CURSOR_NONE
block|,
DECL|enumerator|GIMP_RECT_SELECT_TOOL_CURSOR
name|GIMP_RECT_SELECT_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_ELLIPSE_SELECT_TOOL_CURSOR
name|GIMP_ELLIPSE_SELECT_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_FREE_SELECT_TOOL_CURSOR
name|GIMP_FREE_SELECT_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_FUZZY_SELECT_TOOL_CURSOR
name|GIMP_FUZZY_SELECT_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_BEZIER_SELECT_TOOL_CURSOR
name|GIMP_BEZIER_SELECT_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_SCISSORS_TOOL_CURSOR
name|GIMP_SCISSORS_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_MOVE_TOOL_CURSOR
name|GIMP_MOVE_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_ZOOM_TOOL_CURSOR
name|GIMP_ZOOM_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_CROP_TOOL_CURSOR
name|GIMP_CROP_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_RESIZE_TOOL_CURSOR
name|GIMP_RESIZE_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_ROTATE_TOOL_CURSOR
name|GIMP_ROTATE_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_SHEAR_TOOL_CURSOR
name|GIMP_SHEAR_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_PERSPECTIVE_TOOL_CURSOR
name|GIMP_PERSPECTIVE_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_FLIP_HORIZONTAL_TOOL_CURSOR
name|GIMP_FLIP_HORIZONTAL_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_FLIP_VERTICAL_TOOL_CURSOR
name|GIMP_FLIP_VERTICAL_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_TEXT_TOOL_CURSOR
name|GIMP_TEXT_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_COLOR_PICKER_TOOL_CURSOR
name|GIMP_COLOR_PICKER_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_BUCKET_FILL_TOOL_CURSOR
name|GIMP_BUCKET_FILL_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_BLEND_TOOL_CURSOR
name|GIMP_BLEND_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_PENCIL_TOOL_CURSOR
name|GIMP_PENCIL_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_PAINTBRUSH_TOOL_CURSOR
name|GIMP_PAINTBRUSH_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_AIRBRUSH_TOOL_CURSOR
name|GIMP_AIRBRUSH_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_INK_TOOL_CURSOR
name|GIMP_INK_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_CLONE_TOOL_CURSOR
name|GIMP_CLONE_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_ERASER_TOOL_CURSOR
name|GIMP_ERASER_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_SMUDGE_TOOL_CURSOR
name|GIMP_SMUDGE_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_BLUR_TOOL_CURSOR
name|GIMP_BLUR_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_DODGE_TOOL_CURSOR
name|GIMP_DODGE_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_BURN_TOOL_CURSOR
name|GIMP_BURN_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_MEASURE_TOOL_CURSOR
name|GIMP_MEASURE_TOOL_CURSOR
block|,
DECL|enumerator|GIMP_LAST_STOCK_TOOL_CURSOR_ENTRY
name|GIMP_LAST_STOCK_TOOL_CURSOR_ENTRY
DECL|typedef|GimpToolCursorType
block|}
name|GimpToolCursorType
typedef|;
end_typedef

begin_typedef
typedef|typedef
enum|enum
comment|/*< skip>*/
DECL|enum|__anon2950ddf90303
block|{
DECL|enumerator|GIMP_CURSOR_MODIFIER_NONE
name|GIMP_CURSOR_MODIFIER_NONE
block|,
DECL|enumerator|GIMP_CURSOR_MODIFIER_PLUS
name|GIMP_CURSOR_MODIFIER_PLUS
block|,
DECL|enumerator|GIMP_CURSOR_MODIFIER_MINUS
name|GIMP_CURSOR_MODIFIER_MINUS
block|,
DECL|enumerator|GIMP_CURSOR_MODIFIER_INTERSECT
name|GIMP_CURSOR_MODIFIER_INTERSECT
block|,
DECL|enumerator|GIMP_CURSOR_MODIFIER_MOVE
name|GIMP_CURSOR_MODIFIER_MOVE
block|,
DECL|enumerator|GIMP_CURSOR_MODIFIER_RESIZE
name|GIMP_CURSOR_MODIFIER_RESIZE
block|,
DECL|enumerator|GIMP_CURSOR_MODIFIER_CONTROL
name|GIMP_CURSOR_MODIFIER_CONTROL
block|,
DECL|enumerator|GIMP_CURSOR_MODIFIER_ANCHOR
name|GIMP_CURSOR_MODIFIER_ANCHOR
block|,
DECL|enumerator|GIMP_CURSOR_MODIFIER_FOREGROUND
name|GIMP_CURSOR_MODIFIER_FOREGROUND
block|,
DECL|enumerator|GIMP_CURSOR_MODIFIER_BACKGROUND
name|GIMP_CURSOR_MODIFIER_BACKGROUND
block|,
DECL|enumerator|GIMP_CURSOR_MODIFIER_PATTERN
name|GIMP_CURSOR_MODIFIER_PATTERN
block|,
DECL|enumerator|GIMP_CURSOR_MODIFIER_HAND
name|GIMP_CURSOR_MODIFIER_HAND
block|,
DECL|enumerator|GIMP_LAST_CURSOR_MODIFIER_ENTRY
name|GIMP_LAST_CURSOR_MODIFIER_ENTRY
DECL|typedef|GimpCursorModifier
block|}
name|GimpCursorModifier
typedef|;
end_typedef

begin_comment
comment|/* autogenerated from "./../app/display/display-types.h" */
end_comment

begin_comment
comment|/* The GIMP -- an image manipulation program  * Copyright (C) 1995 Spencer Kimball and Peter Mattis  *  * This program is free software; you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 2 of the License, or  * (at your option) any later version.  *  * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *  * You should have received a copy of the GNU General Public License  * along with this program; if not, write to the Free Software  * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  */
end_comment

begin_typedef
DECL|typedef|GimpDisplay
typedef|typedef
name|struct
name|_GimpDisplay
name|GimpDisplay
typedef|;
end_typedef

begin_comment
DECL|typedef|GimpDisplay
comment|/*< proxy-resume>*/
end_comment

begin_typedef
DECL|typedef|GimpDisplayShell
typedef|typedef
name|struct
name|_GimpDisplayShell
name|GimpDisplayShell
typedef|;
end_typedef

begin_endif
endif|#
directive|endif
end_endif

begin_comment
comment|/* __GIMP_PROXY_TYPES_H__ */
end_comment

begin_comment
comment|/* Generated data ends here */
end_comment

end_unit

