begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* The GIMP -- an image manipulation program  * Copyright (C) 1995 Spencer Kimball and Peter Mattis  *  * This program is free software; you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 2 of the License, or  * (at your option) any later version.  *  * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *  * You should have received a copy of the GNU General Public License  * along with this program; if not, write to the Free Software  * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  */
end_comment

begin_include
include|#
directive|include
file|<stdio.h>
end_include

begin_include
include|#
directive|include
file|<stdlib.h>
end_include

begin_include
include|#
directive|include
file|"appenv.h"
end_include

begin_include
include|#
directive|include
file|"general.h"
end_include

begin_include
include|#
directive|include
file|"gimage.h"
end_include

begin_include
include|#
directive|include
file|"channel.h"
end_include

begin_include
include|#
directive|include
file|"channel_cmds.h"
end_include

begin_include
include|#
directive|include
file|"channel_pvt.h"
end_include

begin_decl_stmt
DECL|variable|int_value
specifier|static
name|int
name|int_value
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|fp_value
specifier|static
name|double
name|fp_value
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|success
specifier|static
name|int
name|success
decl_stmt|;
end_decl_stmt

begin_comment
comment|/*****************/
end_comment

begin_comment
comment|/*  CHANNEL_NEW  */
end_comment

begin_function
specifier|static
name|Argument
modifier|*
DECL|function|channel_new_invoker (Argument * args)
name|channel_new_invoker
parameter_list|(
name|Argument
modifier|*
name|args
parameter_list|)
block|{
name|Channel
modifier|*
name|channel
decl_stmt|;
name|int
name|gimage_id
decl_stmt|;
name|int
name|width
decl_stmt|,
name|height
decl_stmt|;
name|char
modifier|*
name|name
decl_stmt|;
name|int
name|opacity
decl_stmt|;
name|unsigned
name|char
name|color
index|[
literal|3
index|]
decl_stmt|;
name|Argument
modifier|*
name|return_args
decl_stmt|;
name|channel
operator|=
name|NULL
expr_stmt|;
name|gimage_id
operator|=
operator|-
literal|1
expr_stmt|;
name|opacity
operator|=
literal|255
expr_stmt|;
name|success
operator|=
name|TRUE
expr_stmt|;
if|if
condition|(
name|success
condition|)
block|{
name|int_value
operator|=
name|args
index|[
literal|0
index|]
operator|.
name|value
operator|.
name|pdb_int
expr_stmt|;
if|if
condition|(
name|gimage_get_ID
argument_list|(
name|int_value
argument_list|)
operator|!=
name|NULL
condition|)
name|gimage_id
operator|=
name|int_value
expr_stmt|;
else|else
name|success
operator|=
name|FALSE
expr_stmt|;
block|}
if|if
condition|(
name|success
condition|)
block|{
name|width
operator|=
name|args
index|[
literal|1
index|]
operator|.
name|value
operator|.
name|pdb_int
expr_stmt|;
name|height
operator|=
name|args
index|[
literal|2
index|]
operator|.
name|value
operator|.
name|pdb_int
expr_stmt|;
name|success
operator|=
operator|(
name|width
operator|>
literal|0
operator|&&
name|height
operator|>
literal|0
operator|)
expr_stmt|;
block|}
if|if
condition|(
name|success
condition|)
name|name
operator|=
operator|(
name|char
operator|*
operator|)
name|args
index|[
literal|3
index|]
operator|.
name|value
operator|.
name|pdb_pointer
expr_stmt|;
if|if
condition|(
name|success
condition|)
block|{
name|fp_value
operator|=
name|args
index|[
literal|4
index|]
operator|.
name|value
operator|.
name|pdb_float
expr_stmt|;
if|if
condition|(
name|fp_value
operator|>=
literal|0
operator|&&
name|fp_value
operator|<=
literal|100
condition|)
name|opacity
operator|=
call|(
name|int
call|)
argument_list|(
operator|(
name|fp_value
operator|*
literal|255
operator|)
operator|/
literal|100
argument_list|)
expr_stmt|;
else|else
name|success
operator|=
name|FALSE
expr_stmt|;
block|}
if|if
condition|(
name|success
condition|)
block|{
name|int
name|i
decl_stmt|;
name|unsigned
name|char
modifier|*
name|color_array
decl_stmt|;
name|color_array
operator|=
operator|(
name|unsigned
name|char
operator|*
operator|)
name|args
index|[
literal|5
index|]
operator|.
name|value
operator|.
name|pdb_pointer
expr_stmt|;
for|for
control|(
name|i
operator|=
literal|0
init|;
name|i
operator|<
literal|3
condition|;
name|i
operator|++
control|)
name|color
index|[
name|i
index|]
operator|=
name|color_array
index|[
name|i
index|]
expr_stmt|;
block|}
if|if
condition|(
name|success
condition|)
name|success
operator|=
operator|(
operator|(
name|channel
operator|=
name|channel_new
argument_list|(
name|gimage_get_ID
argument_list|(
name|gimage_id
argument_list|)
argument_list|,
name|width
argument_list|,
name|height
argument_list|,
name|name
argument_list|,
name|opacity
argument_list|,
name|color
argument_list|)
operator|)
operator|!=
name|NULL
operator|)
expr_stmt|;
name|return_args
operator|=
name|procedural_db_return_args
argument_list|(
operator|&
name|channel_new_proc
argument_list|,
name|success
argument_list|)
expr_stmt|;
if|if
condition|(
name|success
condition|)
name|return_args
index|[
literal|1
index|]
operator|.
name|value
operator|.
name|pdb_int
operator|=
name|GIMP_DRAWABLE
argument_list|(
name|channel
argument_list|)
operator|->
name|ID
expr_stmt|;
return|return
name|return_args
return|;
block|}
end_function

begin_comment
comment|/*  The procedure definition  */
end_comment

begin_decl_stmt
DECL|variable|channel_new_args
name|ProcArg
name|channel_new_args
index|[]
init|=
block|{
block|{
name|PDB_IMAGE
block|,
literal|"image"
block|,
literal|"the image to which to add the channel"
block|}
block|,
block|{
name|PDB_INT32
block|,
literal|"width"
block|,
literal|"the channel width: (width> 0)"
block|}
block|,
block|{
name|PDB_INT32
block|,
literal|"height"
block|,
literal|"the channel height: (height> 0)"
block|}
block|,
block|{
name|PDB_STRING
block|,
literal|"name"
block|,
literal|"the channel name"
block|}
block|,
block|{
name|PDB_FLOAT
block|,
literal|"opacity"
block|,
literal|"the channel opacity: (0<= opacity<= 100)"
block|}
block|,
block|{
name|PDB_COLOR
block|,
literal|"color"
block|,
literal|"the channel compositing color"
block|}
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|channel_new_out_args
name|ProcArg
name|channel_new_out_args
index|[]
init|=
block|{
block|{
name|PDB_CHANNEL
block|,
literal|"channel"
block|,
literal|"the newly created channel"
block|}
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|channel_new_proc
name|ProcRecord
name|channel_new_proc
init|=
block|{
literal|"gimp_channel_new"
block|,
literal|"Create a new channel"
block|,
literal|"This procedure creates a new channel with the specified width and height.  Name, opacity, and color are also supplied parameters.  The new channel still needs to be added to the image, as this is not automatic.  Add the new channel with the 'gimp_image_add_channel' command.  Other attributes such as channel show masked, should be set with explicit procedure calls.  The channel's contents are undefined initially."
block|,
literal|"Spencer Kimball& Peter Mattis"
block|,
literal|"Spencer Kimball& Peter Mattis"
block|,
literal|"1995-1996"
block|,
name|PDB_INTERNAL
block|,
comment|/*  Input arguments  */
literal|6
block|,
name|channel_new_args
block|,
comment|/*  Output arguments  */
literal|1
block|,
name|channel_new_out_args
block|,
comment|/*  Exec method  */
block|{
block|{
name|channel_new_invoker
block|}
block|}
block|, }
decl_stmt|;
end_decl_stmt

begin_comment
comment|/******************/
end_comment

begin_comment
comment|/*  CHANNEL_COPY  */
end_comment

begin_function
specifier|static
name|Argument
modifier|*
DECL|function|channel_copy_invoker (Argument * args)
name|channel_copy_invoker
parameter_list|(
name|Argument
modifier|*
name|args
parameter_list|)
block|{
name|Channel
modifier|*
name|channel
decl_stmt|;
name|Channel
modifier|*
name|copy
decl_stmt|;
name|Argument
modifier|*
name|return_args
decl_stmt|;
name|copy
operator|=
name|NULL
expr_stmt|;
name|success
operator|=
name|TRUE
expr_stmt|;
if|if
condition|(
name|success
condition|)
block|{
name|int_value
operator|=
name|args
index|[
literal|0
index|]
operator|.
name|value
operator|.
name|pdb_int
expr_stmt|;
if|if
condition|(
operator|(
name|channel
operator|=
name|channel_get_ID
argument_list|(
name|int_value
argument_list|)
operator|)
operator|==
name|NULL
condition|)
name|success
operator|=
name|FALSE
expr_stmt|;
block|}
if|if
condition|(
name|success
condition|)
name|success
operator|=
operator|(
operator|(
name|copy
operator|=
name|channel_copy
argument_list|(
name|channel
argument_list|)
operator|)
operator|!=
name|NULL
operator|)
expr_stmt|;
name|return_args
operator|=
name|procedural_db_return_args
argument_list|(
operator|&
name|channel_copy_proc
argument_list|,
name|success
argument_list|)
expr_stmt|;
if|if
condition|(
name|success
condition|)
name|return_args
index|[
literal|1
index|]
operator|.
name|value
operator|.
name|pdb_int
operator|=
name|GIMP_DRAWABLE
argument_list|(
name|copy
argument_list|)
operator|->
name|ID
expr_stmt|;
return|return
name|return_args
return|;
block|}
end_function

begin_comment
comment|/*  The procedure definition  */
end_comment

begin_decl_stmt
DECL|variable|channel_copy_args
name|ProcArg
name|channel_copy_args
index|[]
init|=
block|{
block|{
name|PDB_CHANNEL
block|,
literal|"channel"
block|,
literal|"the channel to copy"
block|}
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|channel_copy_out_args
name|ProcArg
name|channel_copy_out_args
index|[]
init|=
block|{
block|{
name|PDB_CHANNEL
block|,
literal|"channel_copy"
block|,
literal|"the newly copied channel"
block|}
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|channel_copy_proc
name|ProcRecord
name|channel_copy_proc
init|=
block|{
literal|"gimp_channel_copy"
block|,
literal|"Copy a channel"
block|,
literal|"This procedure copies the specified channel and returns the copy."
block|,
literal|"Spencer Kimball& Peter Mattis"
block|,
literal|"Spencer Kimball& Peter Mattis"
block|,
literal|"1995-1996"
block|,
name|PDB_INTERNAL
block|,
comment|/*  Input arguments  */
literal|1
block|,
name|channel_copy_args
block|,
comment|/*  Output arguments  */
literal|1
block|,
name|channel_copy_out_args
block|,
comment|/*  Exec method  */
block|{
block|{
name|channel_copy_invoker
block|}
block|}
block|, }
decl_stmt|;
end_decl_stmt

begin_comment
comment|/********************/
end_comment

begin_comment
comment|/*  CHANNEL_DELETE  */
end_comment

begin_function
specifier|static
name|Argument
modifier|*
DECL|function|channel_delete_invoker (Argument * args)
name|channel_delete_invoker
parameter_list|(
name|Argument
modifier|*
name|args
parameter_list|)
block|{
name|Channel
modifier|*
name|channel
decl_stmt|;
name|success
operator|=
name|TRUE
expr_stmt|;
if|if
condition|(
name|success
condition|)
block|{
name|int_value
operator|=
name|args
index|[
literal|0
index|]
operator|.
name|value
operator|.
name|pdb_int
expr_stmt|;
if|if
condition|(
operator|(
name|channel
operator|=
name|channel_get_ID
argument_list|(
name|int_value
argument_list|)
operator|)
operator|==
name|NULL
condition|)
name|success
operator|=
name|FALSE
expr_stmt|;
block|}
if|if
condition|(
name|success
condition|)
name|channel_delete
argument_list|(
name|channel
argument_list|)
expr_stmt|;
return|return
name|procedural_db_return_args
argument_list|(
operator|&
name|channel_delete_proc
argument_list|,
name|success
argument_list|)
return|;
block|}
end_function

begin_comment
comment|/*  The procedure definition  */
end_comment

begin_decl_stmt
DECL|variable|channel_delete_args
name|ProcArg
name|channel_delete_args
index|[]
init|=
block|{
block|{
name|PDB_CHANNEL
block|,
literal|"channel"
block|,
literal|"the channel to delete"
block|}
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|channel_delete_proc
name|ProcRecord
name|channel_delete_proc
init|=
block|{
literal|"gimp_channel_delete"
block|,
literal|"Delete a channel"
block|,
literal|"This procedure deletes the specified channel.  This does not need to be done if a gimage containing this channel was already deleted."
block|,
literal|"Spencer Kimball& Peter Mattis"
block|,
literal|"Spencer Kimball& Peter Mattis"
block|,
literal|"1995-1996"
block|,
name|PDB_INTERNAL
block|,
comment|/*  Input arguments  */
literal|1
block|,
name|channel_delete_args
block|,
comment|/*  Output arguments  */
literal|0
block|,
name|NULL
block|,
comment|/*  Exec method  */
block|{
block|{
name|channel_delete_invoker
block|}
block|}
block|, }
decl_stmt|;
end_decl_stmt

begin_comment
comment|/**********************/
end_comment

begin_comment
comment|/*  CHANNEL_GET_NAME  */
end_comment

begin_function
specifier|static
name|Argument
modifier|*
DECL|function|channel_get_name_invoker (Argument * args)
name|channel_get_name_invoker
parameter_list|(
name|Argument
modifier|*
name|args
parameter_list|)
block|{
name|Channel
modifier|*
name|channel
decl_stmt|;
name|char
modifier|*
name|name
init|=
name|NULL
decl_stmt|;
name|Argument
modifier|*
name|return_args
decl_stmt|;
name|success
operator|=
name|TRUE
expr_stmt|;
if|if
condition|(
name|success
condition|)
block|{
name|int_value
operator|=
name|args
index|[
literal|0
index|]
operator|.
name|value
operator|.
name|pdb_int
expr_stmt|;
if|if
condition|(
operator|(
name|channel
operator|=
name|channel_get_ID
argument_list|(
name|int_value
argument_list|)
operator|)
condition|)
name|name
operator|=
name|GIMP_DRAWABLE
argument_list|(
name|channel
argument_list|)
operator|->
name|name
expr_stmt|;
else|else
name|success
operator|=
name|FALSE
expr_stmt|;
block|}
name|return_args
operator|=
name|procedural_db_return_args
argument_list|(
operator|&
name|channel_get_name_proc
argument_list|,
name|success
argument_list|)
expr_stmt|;
if|if
condition|(
name|success
condition|)
name|return_args
index|[
literal|1
index|]
operator|.
name|value
operator|.
name|pdb_pointer
operator|=
operator|(
name|name
operator|)
condition|?
name|g_strdup
argument_list|(
name|name
argument_list|)
else|:
name|NULL
expr_stmt|;
return|return
name|return_args
return|;
block|}
end_function

begin_comment
comment|/*  The procedure definition  */
end_comment

begin_decl_stmt
DECL|variable|channel_get_name_args
name|ProcArg
name|channel_get_name_args
index|[]
init|=
block|{
block|{
name|PDB_CHANNEL
block|,
literal|"channel"
block|,
literal|"the channel"
block|}
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|channel_get_name_out_args
name|ProcArg
name|channel_get_name_out_args
index|[]
init|=
block|{
block|{
name|PDB_STRING
block|,
literal|"name"
block|,
literal|"the channel name"
block|}
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|channel_get_name_proc
name|ProcRecord
name|channel_get_name_proc
init|=
block|{
literal|"gimp_channel_get_name"
block|,
literal|"Get the name of the specified channel."
block|,
literal|"This procedure returns the specified channel's name."
block|,
literal|"Spencer Kimball& Peter Mattis"
block|,
literal|"Spencer Kimball& Peter Mattis"
block|,
literal|"1995-1996"
block|,
name|PDB_INTERNAL
block|,
comment|/*  Input arguments  */
literal|1
block|,
name|channel_get_name_args
block|,
comment|/*  Output arguments  */
literal|1
block|,
name|channel_get_name_out_args
block|,
comment|/*  Exec method  */
block|{
block|{
name|channel_get_name_invoker
block|}
block|}
block|, }
decl_stmt|;
end_decl_stmt

begin_comment
comment|/**********************/
end_comment

begin_comment
comment|/*  CHANNEL_SET_NAME  */
end_comment

begin_function
specifier|static
name|Argument
modifier|*
DECL|function|channel_set_name_invoker (Argument * args)
name|channel_set_name_invoker
parameter_list|(
name|Argument
modifier|*
name|args
parameter_list|)
block|{
name|Channel
modifier|*
name|channel
decl_stmt|;
name|char
modifier|*
name|name
decl_stmt|;
name|success
operator|=
name|TRUE
expr_stmt|;
if|if
condition|(
name|success
condition|)
block|{
name|int_value
operator|=
name|args
index|[
literal|0
index|]
operator|.
name|value
operator|.
name|pdb_int
expr_stmt|;
if|if
condition|(
operator|(
name|channel
operator|=
name|channel_get_ID
argument_list|(
name|int_value
argument_list|)
operator|)
operator|==
name|NULL
condition|)
name|success
operator|=
name|FALSE
expr_stmt|;
block|}
if|if
condition|(
name|success
condition|)
block|{
name|name
operator|=
operator|(
name|char
operator|*
operator|)
name|args
index|[
literal|1
index|]
operator|.
name|value
operator|.
name|pdb_pointer
expr_stmt|;
if|if
condition|(
name|GIMP_DRAWABLE
argument_list|(
name|channel
argument_list|)
operator|->
name|name
condition|)
block|{
name|g_free
argument_list|(
name|GIMP_DRAWABLE
argument_list|(
name|channel
argument_list|)
operator|->
name|name
argument_list|)
expr_stmt|;
name|GIMP_DRAWABLE
argument_list|(
name|channel
argument_list|)
operator|->
name|name
operator|=
operator|(
name|name
operator|)
condition|?
name|g_strdup
argument_list|(
name|name
argument_list|)
else|:
name|NULL
expr_stmt|;
block|}
block|}
return|return
name|procedural_db_return_args
argument_list|(
operator|&
name|channel_set_name_proc
argument_list|,
name|success
argument_list|)
return|;
block|}
end_function

begin_comment
comment|/*  The procedure definition  */
end_comment

begin_decl_stmt
DECL|variable|channel_set_name_args
name|ProcArg
name|channel_set_name_args
index|[]
init|=
block|{
block|{
name|PDB_CHANNEL
block|,
literal|"channel"
block|,
literal|"the channel"
block|}
block|,
block|{
name|PDB_STRING
block|,
literal|"name"
block|,
literal|"the new channel name"
block|}
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|channel_set_name_proc
name|ProcRecord
name|channel_set_name_proc
init|=
block|{
literal|"gimp_channel_set_name"
block|,
literal|"Set the name of the specified channel."
block|,
literal|"This procedure sets the specified channel's name to the supplied name."
block|,
literal|"Spencer Kimball& Peter Mattis"
block|,
literal|"Spencer Kimball& Peter Mattis"
block|,
literal|"1995-1996"
block|,
name|PDB_INTERNAL
block|,
comment|/*  Input arguments  */
literal|2
block|,
name|channel_set_name_args
block|,
comment|/*  Output arguments  */
literal|0
block|,
name|NULL
block|,
comment|/*  Exec method  */
block|{
block|{
name|channel_set_name_invoker
block|}
block|}
block|, }
decl_stmt|;
end_decl_stmt

begin_comment
comment|/*************************/
end_comment

begin_comment
comment|/*  CHANNEL_GET_VISIBLE  */
end_comment

begin_function
specifier|static
name|Argument
modifier|*
DECL|function|channel_get_visible_invoker (Argument * args)
name|channel_get_visible_invoker
parameter_list|(
name|Argument
modifier|*
name|args
parameter_list|)
block|{
name|Channel
modifier|*
name|channel
decl_stmt|;
name|int
name|visible
decl_stmt|;
name|Argument
modifier|*
name|return_args
decl_stmt|;
name|visible
operator|=
name|FALSE
expr_stmt|;
name|success
operator|=
name|TRUE
expr_stmt|;
if|if
condition|(
name|success
condition|)
block|{
name|int_value
operator|=
name|args
index|[
literal|0
index|]
operator|.
name|value
operator|.
name|pdb_int
expr_stmt|;
if|if
condition|(
operator|(
name|channel
operator|=
name|channel_get_ID
argument_list|(
name|int_value
argument_list|)
operator|)
condition|)
name|visible
operator|=
name|GIMP_DRAWABLE
argument_list|(
name|channel
argument_list|)
operator|->
name|visible
expr_stmt|;
else|else
name|success
operator|=
name|FALSE
expr_stmt|;
block|}
name|return_args
operator|=
name|procedural_db_return_args
argument_list|(
operator|&
name|channel_get_visible_proc
argument_list|,
name|success
argument_list|)
expr_stmt|;
if|if
condition|(
name|success
condition|)
name|return_args
index|[
literal|1
index|]
operator|.
name|value
operator|.
name|pdb_int
operator|=
name|visible
expr_stmt|;
return|return
name|return_args
return|;
block|}
end_function

begin_comment
comment|/*  The procedure definition  */
end_comment

begin_decl_stmt
DECL|variable|channel_get_visible_args
name|ProcArg
name|channel_get_visible_args
index|[]
init|=
block|{
block|{
name|PDB_CHANNEL
block|,
literal|"channel"
block|,
literal|"the channel"
block|}
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|channel_get_visible_out_args
name|ProcArg
name|channel_get_visible_out_args
index|[]
init|=
block|{
block|{
name|PDB_INT32
block|,
literal|"visible"
block|,
literal|"the channel visibility"
block|}
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|channel_get_visible_proc
name|ProcRecord
name|channel_get_visible_proc
init|=
block|{
literal|"gimp_channel_get_visible"
block|,
literal|"Get the visibility of the specified channel."
block|,
literal|"This procedure returns the specified channel's visibility."
block|,
literal|"Spencer Kimball& Peter Mattis"
block|,
literal|"Spencer Kimball& Peter Mattis"
block|,
literal|"1995-1996"
block|,
name|PDB_INTERNAL
block|,
comment|/*  Input arguments  */
literal|1
block|,
name|channel_get_visible_args
block|,
comment|/*  Output arguments  */
literal|1
block|,
name|channel_get_visible_out_args
block|,
comment|/*  Exec method  */
block|{
block|{
name|channel_get_visible_invoker
block|}
block|}
block|, }
decl_stmt|;
end_decl_stmt

begin_comment
comment|/*************************/
end_comment

begin_comment
comment|/*  CHANNEL_SET_VISIBLE  */
end_comment

begin_function
specifier|static
name|Argument
modifier|*
DECL|function|channel_set_visible_invoker (Argument * args)
name|channel_set_visible_invoker
parameter_list|(
name|Argument
modifier|*
name|args
parameter_list|)
block|{
name|Channel
modifier|*
name|channel
decl_stmt|;
name|int
name|visible
decl_stmt|;
name|success
operator|=
name|TRUE
expr_stmt|;
if|if
condition|(
name|success
condition|)
block|{
name|int_value
operator|=
name|args
index|[
literal|0
index|]
operator|.
name|value
operator|.
name|pdb_int
expr_stmt|;
if|if
condition|(
operator|(
name|channel
operator|=
name|channel_get_ID
argument_list|(
name|int_value
argument_list|)
operator|)
operator|==
name|NULL
condition|)
name|success
operator|=
name|FALSE
expr_stmt|;
block|}
if|if
condition|(
name|success
condition|)
block|{
name|visible
operator|=
name|args
index|[
literal|1
index|]
operator|.
name|value
operator|.
name|pdb_int
expr_stmt|;
name|GIMP_DRAWABLE
argument_list|(
name|channel
argument_list|)
operator|->
name|visible
operator|=
operator|(
name|visible
operator|)
condition|?
name|TRUE
else|:
name|FALSE
expr_stmt|;
block|}
return|return
name|procedural_db_return_args
argument_list|(
operator|&
name|channel_set_visible_proc
argument_list|,
name|success
argument_list|)
return|;
block|}
end_function

begin_comment
comment|/*  The procedure definition  */
end_comment

begin_decl_stmt
DECL|variable|channel_set_visible_args
name|ProcArg
name|channel_set_visible_args
index|[]
init|=
block|{
block|{
name|PDB_CHANNEL
block|,
literal|"channel"
block|,
literal|"the channel"
block|}
block|,
block|{
name|PDB_INT32
block|,
literal|"visible"
block|,
literal|"the new channel visibility"
block|}
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|channel_set_visible_proc
name|ProcRecord
name|channel_set_visible_proc
init|=
block|{
literal|"gimp_channel_set_visible"
block|,
literal|"Set the visibility of the specified channel."
block|,
literal|"This procedure sets the specified channel's visibility."
block|,
literal|"Spencer Kimball& Peter Mattis"
block|,
literal|"Spencer Kimball& Peter Mattis"
block|,
literal|"1995-1996"
block|,
name|PDB_INTERNAL
block|,
comment|/*  Input arguments  */
literal|2
block|,
name|channel_set_visible_args
block|,
comment|/*  Output arguments  */
literal|0
block|,
name|NULL
block|,
comment|/*  Exec method  */
block|{
block|{
name|channel_set_visible_invoker
block|}
block|}
block|, }
decl_stmt|;
end_decl_stmt

begin_comment
comment|/*****************************/
end_comment

begin_comment
comment|/*  CHANNEL_GET_SHOW_MASKED  */
end_comment

begin_function
specifier|static
name|Argument
modifier|*
DECL|function|channel_get_show_masked_invoker (Argument * args)
name|channel_get_show_masked_invoker
parameter_list|(
name|Argument
modifier|*
name|args
parameter_list|)
block|{
name|Channel
modifier|*
name|channel
decl_stmt|;
name|int
name|show_masked
decl_stmt|;
name|Argument
modifier|*
name|return_args
decl_stmt|;
name|show_masked
operator|=
name|FALSE
expr_stmt|;
name|success
operator|=
name|TRUE
expr_stmt|;
if|if
condition|(
name|success
condition|)
block|{
name|int_value
operator|=
name|args
index|[
literal|0
index|]
operator|.
name|value
operator|.
name|pdb_int
expr_stmt|;
if|if
condition|(
operator|(
name|channel
operator|=
name|channel_get_ID
argument_list|(
name|int_value
argument_list|)
operator|)
condition|)
name|show_masked
operator|=
name|channel
operator|->
name|show_masked
expr_stmt|;
else|else
name|success
operator|=
name|FALSE
expr_stmt|;
block|}
name|return_args
operator|=
name|procedural_db_return_args
argument_list|(
operator|&
name|channel_get_show_masked_proc
argument_list|,
name|success
argument_list|)
expr_stmt|;
if|if
condition|(
name|success
condition|)
name|return_args
index|[
literal|1
index|]
operator|.
name|value
operator|.
name|pdb_int
operator|=
name|show_masked
expr_stmt|;
return|return
name|return_args
return|;
block|}
end_function

begin_comment
comment|/*  The procedure definition  */
end_comment

begin_decl_stmt
DECL|variable|channel_get_show_masked_args
name|ProcArg
name|channel_get_show_masked_args
index|[]
init|=
block|{
block|{
name|PDB_CHANNEL
block|,
literal|"channel"
block|,
literal|"the channel"
block|}
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|channel_get_show_masked_out_args
name|ProcArg
name|channel_get_show_masked_out_args
index|[]
init|=
block|{
block|{
name|PDB_INT32
block|,
literal|"show_masked"
block|,
literal|"composite method for channel"
block|}
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|channel_get_show_masked_proc
name|ProcRecord
name|channel_get_show_masked_proc
init|=
block|{
literal|"gimp_channel_get_show_masked"
block|,
literal|"Get the composite type for the channel"
block|,
literal|"This procedure returns the specified channel's composite type.  If it is non-zero, then the channel is composited with the image so that masked regions are shown.  Otherwise, selected regions are shown."
block|,
literal|"Spencer Kimball& Peter Mattis"
block|,
literal|"Spencer Kimball& Peter Mattis"
block|,
literal|"1995-1996"
block|,
name|PDB_INTERNAL
block|,
comment|/*  Input arguments  */
literal|1
block|,
name|channel_get_show_masked_args
block|,
comment|/*  Output arguments  */
literal|1
block|,
name|channel_get_show_masked_out_args
block|,
comment|/*  Exec method  */
block|{
block|{
name|channel_get_show_masked_invoker
block|}
block|}
block|, }
decl_stmt|;
end_decl_stmt

begin_comment
comment|/*****************************/
end_comment

begin_comment
comment|/*  CHANNEL_SET_SHOW_MASKED  */
end_comment

begin_function
specifier|static
name|Argument
modifier|*
DECL|function|channel_set_show_masked_invoker (Argument * args)
name|channel_set_show_masked_invoker
parameter_list|(
name|Argument
modifier|*
name|args
parameter_list|)
block|{
name|Channel
modifier|*
name|channel
decl_stmt|;
name|int
name|show_masked
decl_stmt|;
name|success
operator|=
name|TRUE
expr_stmt|;
if|if
condition|(
name|success
condition|)
block|{
name|int_value
operator|=
name|args
index|[
literal|0
index|]
operator|.
name|value
operator|.
name|pdb_int
expr_stmt|;
if|if
condition|(
operator|(
name|channel
operator|=
name|channel_get_ID
argument_list|(
name|int_value
argument_list|)
operator|)
operator|==
name|NULL
condition|)
name|success
operator|=
name|FALSE
expr_stmt|;
block|}
if|if
condition|(
name|success
condition|)
block|{
name|show_masked
operator|=
name|args
index|[
literal|1
index|]
operator|.
name|value
operator|.
name|pdb_int
expr_stmt|;
name|channel
operator|->
name|show_masked
operator|=
operator|(
name|show_masked
operator|)
condition|?
name|TRUE
else|:
name|FALSE
expr_stmt|;
block|}
return|return
name|procedural_db_return_args
argument_list|(
operator|&
name|channel_set_show_masked_proc
argument_list|,
name|success
argument_list|)
return|;
block|}
end_function

begin_comment
comment|/*  The procedure definition  */
end_comment

begin_decl_stmt
DECL|variable|channel_set_show_masked_args
name|ProcArg
name|channel_set_show_masked_args
index|[]
init|=
block|{
block|{
name|PDB_CHANNEL
block|,
literal|"channel"
block|,
literal|"the channel"
block|}
block|,
block|{
name|PDB_INT32
block|,
literal|"show_masked"
block|,
literal|"the new channel show_masked value"
block|}
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|channel_set_show_masked_proc
name|ProcRecord
name|channel_set_show_masked_proc
init|=
block|{
literal|"gimp_channel_set_show_masked"
block|,
literal|"Set the composite type for the specified channel."
block|,
literal|"This procedure sets the specified channel's composite type.  If it is non-zero, then the channel is composited with the image so that masked regions are shown.  Otherwise, selected regions are shown."
block|,
literal|"Spencer Kimball& Peter Mattis"
block|,
literal|"Spencer Kimball& Peter Mattis"
block|,
literal|"1995-1996"
block|,
name|PDB_INTERNAL
block|,
comment|/*  Input arguments  */
literal|2
block|,
name|channel_set_show_masked_args
block|,
comment|/*  Output arguments  */
literal|0
block|,
name|NULL
block|,
comment|/*  Exec method  */
block|{
block|{
name|channel_set_show_masked_invoker
block|}
block|}
block|, }
decl_stmt|;
end_decl_stmt

begin_comment
comment|/*************************/
end_comment

begin_comment
comment|/*  CHANNEL_GET_OPACITY  */
end_comment

begin_function
specifier|static
name|Argument
modifier|*
DECL|function|channel_get_opacity_invoker (Argument * args)
name|channel_get_opacity_invoker
parameter_list|(
name|Argument
modifier|*
name|args
parameter_list|)
block|{
name|Channel
modifier|*
name|channel
decl_stmt|;
name|double
name|opacity
decl_stmt|;
name|Argument
modifier|*
name|return_args
decl_stmt|;
name|opacity
operator|=
literal|0.0
expr_stmt|;
name|success
operator|=
name|TRUE
expr_stmt|;
if|if
condition|(
name|success
condition|)
block|{
name|int_value
operator|=
name|args
index|[
literal|0
index|]
operator|.
name|value
operator|.
name|pdb_int
expr_stmt|;
if|if
condition|(
operator|(
name|channel
operator|=
name|channel_get_ID
argument_list|(
name|int_value
argument_list|)
operator|)
condition|)
name|opacity
operator|=
operator|(
operator|(
name|channel
operator|->
name|opacity
operator|)
operator|*
literal|100.0
operator|)
operator|/
literal|255.0
expr_stmt|;
else|else
name|success
operator|=
name|FALSE
expr_stmt|;
block|}
name|return_args
operator|=
name|procedural_db_return_args
argument_list|(
operator|&
name|channel_get_opacity_proc
argument_list|,
name|success
argument_list|)
expr_stmt|;
if|if
condition|(
name|success
condition|)
name|return_args
index|[
literal|1
index|]
operator|.
name|value
operator|.
name|pdb_float
operator|=
name|opacity
expr_stmt|;
return|return
name|return_args
return|;
block|}
end_function

begin_comment
comment|/*  The procedure definition  */
end_comment

begin_decl_stmt
DECL|variable|channel_get_opacity_args
name|ProcArg
name|channel_get_opacity_args
index|[]
init|=
block|{
block|{
name|PDB_CHANNEL
block|,
literal|"channel"
block|,
literal|"the channel"
block|}
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|channel_get_opacity_out_args
name|ProcArg
name|channel_get_opacity_out_args
index|[]
init|=
block|{
block|{
name|PDB_FLOAT
block|,
literal|"opacity"
block|,
literal|"the channel opacity"
block|,   }
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|channel_get_opacity_proc
name|ProcRecord
name|channel_get_opacity_proc
init|=
block|{
literal|"gimp_channel_get_opacity"
block|,
literal|"Get the opacity of the specified channel."
block|,
literal|"This procedure returns the specified channel's opacity."
block|,
literal|"Spencer Kimball& Peter Mattis"
block|,
literal|"Spencer Kimball& Peter Mattis"
block|,
literal|"1995-1996"
block|,
name|PDB_INTERNAL
block|,
comment|/*  Input arguments  */
literal|1
block|,
name|channel_get_opacity_args
block|,
comment|/*  Output arguments  */
literal|1
block|,
name|channel_get_opacity_out_args
block|,
comment|/*  Exec method  */
block|{
block|{
name|channel_get_opacity_invoker
block|}
block|}
block|, }
decl_stmt|;
end_decl_stmt

begin_comment
comment|/*************************/
end_comment

begin_comment
comment|/*  CHANNEL_SET_OPACITY  */
end_comment

begin_function
specifier|static
name|Argument
modifier|*
DECL|function|channel_set_opacity_invoker (Argument * args)
name|channel_set_opacity_invoker
parameter_list|(
name|Argument
modifier|*
name|args
parameter_list|)
block|{
name|Channel
modifier|*
name|channel
decl_stmt|;
name|double
name|opacity
decl_stmt|;
name|success
operator|=
name|TRUE
expr_stmt|;
if|if
condition|(
name|success
condition|)
block|{
name|int_value
operator|=
name|args
index|[
literal|0
index|]
operator|.
name|value
operator|.
name|pdb_int
expr_stmt|;
if|if
condition|(
operator|(
name|channel
operator|=
name|channel_get_ID
argument_list|(
name|int_value
argument_list|)
operator|)
operator|==
name|NULL
condition|)
name|success
operator|=
name|FALSE
expr_stmt|;
block|}
if|if
condition|(
name|success
condition|)
block|{
name|opacity
operator|=
name|args
index|[
literal|1
index|]
operator|.
name|value
operator|.
name|pdb_float
expr_stmt|;
name|channel
operator|->
name|opacity
operator|=
call|(
name|int
call|)
argument_list|(
operator|(
name|opacity
operator|*
literal|255
operator|)
operator|/
literal|100
argument_list|)
expr_stmt|;
block|}
return|return
name|procedural_db_return_args
argument_list|(
operator|&
name|channel_set_opacity_proc
argument_list|,
name|success
argument_list|)
return|;
block|}
end_function

begin_comment
comment|/*  The procedure definition  */
end_comment

begin_decl_stmt
DECL|variable|channel_set_opacity_args
name|ProcArg
name|channel_set_opacity_args
index|[]
init|=
block|{
block|{
name|PDB_CHANNEL
block|,
literal|"channel"
block|,
literal|"the channel"
block|}
block|,
block|{
name|PDB_FLOAT
block|,
literal|"opacity"
block|,
literal|"the new channel opacity: (0<= opacity<= 100)"
block|}
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|channel_set_opacity_proc
name|ProcRecord
name|channel_set_opacity_proc
init|=
block|{
literal|"gimp_channel_set_opacity"
block|,
literal|"Set the opacity of the specified channel."
block|,
literal|"This procedure sets the specified channel's opacity."
block|,
literal|"Spencer Kimball& Peter Mattis"
block|,
literal|"Spencer Kimball& Peter Mattis"
block|,
literal|"1995-1996"
block|,
name|PDB_INTERNAL
block|,
comment|/*  Input arguments  */
literal|2
block|,
name|channel_set_opacity_args
block|,
comment|/*  Output arguments  */
literal|0
block|,
name|NULL
block|,
comment|/*  Exec method  */
block|{
block|{
name|channel_set_opacity_invoker
block|}
block|}
block|, }
decl_stmt|;
end_decl_stmt

begin_comment
comment|/***********************/
end_comment

begin_comment
comment|/*  CHANNEL_GET_COLOR  */
end_comment

begin_function
specifier|static
name|Argument
modifier|*
DECL|function|channel_get_color_invoker (Argument * args)
name|channel_get_color_invoker
parameter_list|(
name|Argument
modifier|*
name|args
parameter_list|)
block|{
name|Channel
modifier|*
name|channel
decl_stmt|;
name|unsigned
name|char
modifier|*
name|color
decl_stmt|;
name|Argument
modifier|*
name|return_args
decl_stmt|;
name|color
operator|=
name|NULL
expr_stmt|;
name|success
operator|=
name|TRUE
expr_stmt|;
if|if
condition|(
name|success
condition|)
block|{
name|int_value
operator|=
name|args
index|[
literal|0
index|]
operator|.
name|value
operator|.
name|pdb_int
expr_stmt|;
if|if
condition|(
operator|(
name|channel
operator|=
name|channel_get_ID
argument_list|(
name|int_value
argument_list|)
operator|)
condition|)
block|{
name|color
operator|=
operator|(
name|unsigned
name|char
operator|*
operator|)
name|g_malloc
argument_list|(
literal|3
argument_list|)
expr_stmt|;
name|color
index|[
name|RED_PIX
index|]
operator|=
name|channel
operator|->
name|col
index|[
name|RED_PIX
index|]
expr_stmt|;
name|color
index|[
name|GREEN_PIX
index|]
operator|=
name|channel
operator|->
name|col
index|[
name|GREEN_PIX
index|]
expr_stmt|;
name|color
index|[
name|BLUE_PIX
index|]
operator|=
name|channel
operator|->
name|col
index|[
name|BLUE_PIX
index|]
expr_stmt|;
block|}
else|else
name|success
operator|=
name|FALSE
expr_stmt|;
block|}
name|return_args
operator|=
name|procedural_db_return_args
argument_list|(
operator|&
name|channel_get_color_proc
argument_list|,
name|success
argument_list|)
expr_stmt|;
if|if
condition|(
name|success
condition|)
name|return_args
index|[
literal|1
index|]
operator|.
name|value
operator|.
name|pdb_pointer
operator|=
name|color
expr_stmt|;
return|return
name|return_args
return|;
block|}
end_function

begin_comment
comment|/*  The procedure definition  */
end_comment

begin_decl_stmt
DECL|variable|channel_get_color_args
name|ProcArg
name|channel_get_color_args
index|[]
init|=
block|{
block|{
name|PDB_CHANNEL
block|,
literal|"channel"
block|,
literal|"the channel"
block|}
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|channel_get_color_out_args
name|ProcArg
name|channel_get_color_out_args
index|[]
init|=
block|{
block|{
name|PDB_COLOR
block|,
literal|"color"
block|,
literal|"the channel's composite color"
block|,   }
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|channel_get_color_proc
name|ProcRecord
name|channel_get_color_proc
init|=
block|{
literal|"gimp_channel_get_color"
block|,
literal|"Get the compositing color of the specified channel."
block|,
literal|"This procedure returns the specified channel's compositing color."
block|,
literal|"Spencer Kimball& Peter Mattis"
block|,
literal|"Spencer Kimball& Peter Mattis"
block|,
literal|"1995-1996"
block|,
name|PDB_INTERNAL
block|,
comment|/*  Input arguments  */
literal|1
block|,
name|channel_get_color_args
block|,
comment|/*  Output arguments  */
literal|1
block|,
name|channel_get_color_out_args
block|,
comment|/*  Exec method  */
block|{
block|{
name|channel_get_color_invoker
block|}
block|}
block|, }
decl_stmt|;
end_decl_stmt

begin_comment
comment|/***********************/
end_comment

begin_comment
comment|/*  CHANNEL_SET_COLOR  */
end_comment

begin_function
specifier|static
name|Argument
modifier|*
DECL|function|channel_set_color_invoker (Argument * args)
name|channel_set_color_invoker
parameter_list|(
name|Argument
modifier|*
name|args
parameter_list|)
block|{
name|Channel
modifier|*
name|channel
decl_stmt|;
name|unsigned
name|char
modifier|*
name|color
decl_stmt|;
name|int
name|i
decl_stmt|;
name|success
operator|=
name|TRUE
expr_stmt|;
if|if
condition|(
name|success
condition|)
block|{
name|int_value
operator|=
name|args
index|[
literal|0
index|]
operator|.
name|value
operator|.
name|pdb_int
expr_stmt|;
if|if
condition|(
operator|(
name|channel
operator|=
name|channel_get_ID
argument_list|(
name|int_value
argument_list|)
operator|)
operator|==
name|NULL
condition|)
name|success
operator|=
name|FALSE
expr_stmt|;
block|}
if|if
condition|(
name|success
condition|)
block|{
name|color
operator|=
operator|(
name|unsigned
name|char
operator|*
operator|)
name|args
index|[
literal|1
index|]
operator|.
name|value
operator|.
name|pdb_pointer
expr_stmt|;
for|for
control|(
name|i
operator|=
literal|0
init|;
name|i
operator|<
literal|3
condition|;
name|i
operator|++
control|)
name|channel
operator|->
name|col
index|[
name|i
index|]
operator|=
name|color
index|[
name|i
index|]
expr_stmt|;
block|}
return|return
name|procedural_db_return_args
argument_list|(
operator|&
name|channel_set_color_proc
argument_list|,
name|success
argument_list|)
return|;
block|}
end_function

begin_comment
comment|/*  The procedure definition  */
end_comment

begin_decl_stmt
DECL|variable|channel_set_color_args
name|ProcArg
name|channel_set_color_args
index|[]
init|=
block|{
block|{
name|PDB_CHANNEL
block|,
literal|"channel"
block|,
literal|"the channel"
block|}
block|,
block|{
name|PDB_COLOR
block|,
literal|"color"
block|,
literal|"the composite color"
block|}
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|channel_set_color_proc
name|ProcRecord
name|channel_set_color_proc
init|=
block|{
literal|"gimp_channel_set_color"
block|,
literal|"Set the compositing color of the specified channel."
block|,
literal|"This procedure sets the specified channel's compositing color."
block|,
literal|"Spencer Kimball& Peter Mattis"
block|,
literal|"Spencer Kimball& Peter Mattis"
block|,
literal|"1995-1996"
block|,
name|PDB_INTERNAL
block|,
comment|/*  Input arguments  */
literal|2
block|,
name|channel_set_color_args
block|,
comment|/*  Output arguments  */
literal|0
block|,
name|NULL
block|,
comment|/*  Exec method  */
block|{
block|{
name|channel_set_color_invoker
block|}
block|}
block|, }
decl_stmt|;
end_decl_stmt

end_unit

