begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* docindex.c - Creates the window used by the document index in gimp.  *  * Copyright (C) 1998 Chris Lahey.  *  * This program is free software; you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 2, or (at your option)  * any later version.  *  * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  */
end_comment

begin_include
include|#
directive|include
file|<gtk/gtk.h>
end_include

begin_include
include|#
directive|include
file|<string.h>
end_include

begin_include
include|#
directive|include
file|<stdio.h>
end_include

begin_include
include|#
directive|include
file|<stdlib.h>
end_include

begin_include
include|#
directive|include
file|<gdk/gdkprivate.h>
end_include

begin_include
include|#
directive|include
file|"gimage.h"
end_include

begin_include
include|#
directive|include
file|"fileops.h"
end_include

begin_include
include|#
directive|include
file|"file_new_dialog.h"
end_include

begin_include
include|#
directive|include
file|"commands.h"
end_include

begin_include
include|#
directive|include
file|"docindex.h"
end_include

begin_function_decl
specifier|static
name|void
name|idea_up_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|idea_down_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|idea_remove_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|idea_hide_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|load_idea_manager
parameter_list|(
name|idea_manager
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|save_idea_manager
parameter_list|(
name|idea_manager
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_decl_stmt
DECL|variable|ideas
name|idea_manager
modifier|*
name|ideas
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|image_drop_types
specifier|static
name|char
modifier|*
name|image_drop_types
index|[]
init|=
block|{
literal|"url:ALL"
block|}
decl_stmt|;
end_decl_stmt

begin_function
DECL|function|create_idea_toolbar ()
name|GtkWidget
modifier|*
name|create_idea_toolbar
parameter_list|()
block|{
name|GtkWidget
modifier|*
name|wpixmap
decl_stmt|;
name|GdkPixmap
modifier|*
name|pixmap
decl_stmt|;
name|GdkBitmap
modifier|*
name|mask
decl_stmt|;
name|GtkWidget
modifier|*
name|toolbar
decl_stmt|;
name|toolbar
operator|=
name|gtk_toolbar_new
argument_list|(
name|GTK_ORIENTATION_HORIZONTAL
argument_list|,
name|GTK_TOOLBAR_BOTH
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|toolbar
argument_list|)
expr_stmt|;
name|gtk_toolbar_set_button_relief
argument_list|(
name|GTK_TOOLBAR
argument_list|(
name|toolbar
argument_list|)
argument_list|,
name|GTK_RELIEF_NONE
argument_list|)
expr_stmt|;
name|pixmap
operator|=
name|gdk_pixmap_create_from_xpm
argument_list|(
operator|(
name|GdkWindow
operator|*
operator|)
operator|&
name|gdk_root_parent
argument_list|,
operator|&
name|mask
argument_list|,
operator|&
name|toolbar
operator|->
name|style
operator|->
name|bg
index|[
name|GTK_STATE_NORMAL
index|]
argument_list|,
name|DATADIR
literal|"/go/tb_up_arrow.xpm"
argument_list|)
expr_stmt|;
name|wpixmap
operator|=
name|gtk_pixmap_new
argument_list|(
name|pixmap
argument_list|,
name|mask
argument_list|)
expr_stmt|;
name|gtk_toolbar_append_item
argument_list|(
name|GTK_TOOLBAR
argument_list|(
name|toolbar
argument_list|)
argument_list|,
literal|"Up"
argument_list|,
literal|"Move the selected entry up in the index"
argument_list|,
literal|"Toolbar/Up"
argument_list|,
name|wpixmap
argument_list|,
operator|(
name|GtkSignalFunc
operator|)
name|idea_up_callback
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|pixmap
operator|=
name|gdk_pixmap_create_from_xpm
argument_list|(
operator|(
name|GdkWindow
operator|*
operator|)
operator|&
name|gdk_root_parent
argument_list|,
operator|&
name|mask
argument_list|,
operator|&
name|toolbar
operator|->
name|style
operator|->
name|bg
index|[
name|GTK_STATE_NORMAL
index|]
argument_list|,
name|DATADIR
literal|"/go/tb_down_arrow.xpm"
argument_list|)
expr_stmt|;
name|wpixmap
operator|=
name|gtk_pixmap_new
argument_list|(
name|pixmap
argument_list|,
name|mask
argument_list|)
expr_stmt|;
name|gtk_toolbar_append_item
argument_list|(
name|GTK_TOOLBAR
argument_list|(
name|toolbar
argument_list|)
argument_list|,
literal|"Down"
argument_list|,
literal|"Move the selected entry down in the index"
argument_list|,
literal|"Toolbar/Down"
argument_list|,
name|wpixmap
argument_list|,
operator|(
name|GtkSignalFunc
operator|)
name|idea_down_callback
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|pixmap
operator|=
name|gdk_pixmap_create_from_xpm
argument_list|(
operator|(
name|GdkWindow
operator|*
operator|)
operator|&
name|gdk_root_parent
argument_list|,
operator|&
name|mask
argument_list|,
operator|&
name|toolbar
operator|->
name|style
operator|->
name|bg
index|[
name|GTK_STATE_NORMAL
index|]
argument_list|,
name|DATADIR
literal|"/go/cancel.xpm"
argument_list|)
expr_stmt|;
name|wpixmap
operator|=
name|gtk_pixmap_new
argument_list|(
name|pixmap
argument_list|,
name|mask
argument_list|)
expr_stmt|;
name|gtk_toolbar_append_item
argument_list|(
name|GTK_TOOLBAR
argument_list|(
name|toolbar
argument_list|)
argument_list|,
literal|"Remove"
argument_list|,
literal|"Remove the selected entry from the index"
argument_list|,
literal|"Toolbar/Remove"
argument_list|,
name|wpixmap
argument_list|,
operator|(
name|GtkSignalFunc
operator|)
name|idea_remove_callback
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|pixmap
operator|=
name|gdk_pixmap_create_from_xpm
argument_list|(
operator|(
name|GdkWindow
operator|*
operator|)
operator|&
name|gdk_root_parent
argument_list|,
operator|&
name|mask
argument_list|,
operator|&
name|toolbar
operator|->
name|style
operator|->
name|bg
index|[
name|GTK_STATE_NORMAL
index|]
argument_list|,
name|DATADIR
literal|"/go/tb_exit.xpm"
argument_list|)
expr_stmt|;
name|wpixmap
operator|=
name|gtk_pixmap_new
argument_list|(
name|pixmap
argument_list|,
name|mask
argument_list|)
expr_stmt|;
name|gtk_toolbar_append_item
argument_list|(
name|GTK_TOOLBAR
argument_list|(
name|toolbar
argument_list|)
argument_list|,
literal|"Hide"
argument_list|,
literal|"Hide the Document Index"
argument_list|,
literal|"Toolbar/Hide"
argument_list|,
name|wpixmap
argument_list|,
operator|(
name|GtkSignalFunc
operator|)
name|idea_hide_callback
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
return|return
name|toolbar
return|;
block|}
end_function

begin_define
DECL|macro|IDEA_FILE_ITEMS
define|#
directive|define
name|IDEA_FILE_ITEMS
value|(sizeof( idea_menu ) / sizeof( GtkMenuEntry ))
end_define

begin_decl_stmt
DECL|variable|idea_menu
specifier|static
name|GtkMenuEntry
name|idea_menu
index|[]
init|=
block|{
block|{
literal|"<Main>/File/New"
block|,
literal|"<control>N"
block|,
name|file_new_cmd_callback
block|,
name|NULL
block|}
block|,
block|{
literal|"<Main>/File/Open..."
block|,
literal|"<control>O"
block|,
name|file_open_callback
block|,
name|NULL
block|}
block|,
block|{
literal|"<Main>/File/<separator>"
block|,
name|NULL
block|,
name|NULL
block|,
name|NULL
block|}
block|,
block|{
literal|"<Main>/File/Hide Index"
block|,
literal|"<control>W"
block|,
name|idea_hide_callback
block|,
name|NULL
block|}
block|,
block|{
literal|"<Main>/File/Quit"
block|,
literal|"<control>Q"
block|,
name|file_quit_cmd_callback
block|,
name|NULL
block|}
block|,
block|{
literal|"<Main>/Help/About..."
block|,
name|NULL
block|,
name|about_dialog_cmd_callback
block|,
name|NULL
block|}
block|}
decl_stmt|;
end_decl_stmt

begin_function
DECL|function|create_idea_menu ()
name|GtkMenuFactory
modifier|*
name|create_idea_menu
parameter_list|()
block|{
name|int
name|i
decl_stmt|;
name|GtkMenuFactory
modifier|*
name|factory
decl_stmt|;
name|GtkMenuFactory
modifier|*
name|subfactory
decl_stmt|;
name|GtkMenuEntry
modifier|*
name|current_menu_bar
init|=
name|g_malloc0
argument_list|(
sizeof|sizeof
argument_list|(
name|idea_menu
argument_list|)
argument_list|)
decl_stmt|;
for|for
control|(
name|i
operator|=
literal|0
init|;
name|i
operator|<
name|IDEA_FILE_ITEMS
condition|;
name|i
operator|++
control|)
block|{
name|current_menu_bar
index|[
name|i
index|]
operator|=
name|idea_menu
index|[
name|i
index|]
expr_stmt|;
block|}
name|factory
operator|=
name|gtk_menu_factory_new
argument_list|(
name|GTK_MENU_FACTORY_MENU_BAR
argument_list|)
expr_stmt|;
name|subfactory
operator|=
name|gtk_menu_factory_new
argument_list|(
name|GTK_MENU_FACTORY_MENU_BAR
argument_list|)
expr_stmt|;
name|gtk_menu_factory_add_subfactory
argument_list|(
name|factory
argument_list|,
name|subfactory
argument_list|,
literal|"<Main>"
argument_list|)
expr_stmt|;
name|gtk_menu_factory_add_entries
argument_list|(
name|factory
argument_list|,
name|current_menu_bar
argument_list|,
name|IDEA_FILE_ITEMS
argument_list|)
expr_stmt|;
return|return
name|subfactory
return|;
block|}
end_function

begin_function
DECL|function|reset_usize (gpointer data)
name|gint
name|reset_usize
parameter_list|(
name|gpointer
name|data
parameter_list|)
block|{
name|gtk_widget_set_usize
argument_list|(
name|GTK_WIDGET
argument_list|(
name|data
argument_list|)
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|)
expr_stmt|;
return|return
name|FALSE
return|;
block|}
end_function

begin_function
DECL|function|getinteger (FILE * fp)
name|int
name|getinteger
parameter_list|(
name|FILE
modifier|*
name|fp
parameter_list|)
block|{
name|gchar
name|nextchar
decl_stmt|;
name|int
name|response
init|=
literal|0
decl_stmt|;
name|gboolean
name|negative
init|=
name|FALSE
decl_stmt|;
while|while
condition|(
name|isspace
argument_list|(
name|nextchar
operator|=
name|fgetc
argument_list|(
name|fp
argument_list|)
argument_list|)
condition|)
comment|/* empty statement */
empty_stmt|;
if|if
condition|(
name|nextchar
operator|==
literal|'-'
condition|)
block|{
name|negative
operator|=
name|TRUE
expr_stmt|;
while|while
condition|(
name|isspace
argument_list|(
name|nextchar
operator|=
name|fgetc
argument_list|(
name|fp
argument_list|)
argument_list|)
condition|)
comment|/* empty statement */
empty_stmt|;
block|}
for|for
control|(
init|;
literal|'0'
operator|<=
name|nextchar
operator|&&
literal|'9'
operator|>=
name|nextchar
condition|;
name|nextchar
operator|=
name|fgetc
argument_list|(
name|fp
argument_list|)
control|)
block|{
name|response
operator|*=
literal|10
expr_stmt|;
name|response
operator|+=
name|nextchar
operator|-
literal|'0'
expr_stmt|;
block|}
for|for
control|(
init|;
name|isspace
argument_list|(
name|nextchar
argument_list|)
condition|;
name|nextchar
operator|=
name|fgetc
argument_list|(
name|fp
argument_list|)
control|)
comment|/* empty statement */
empty_stmt|;
name|ungetc
argument_list|(
name|nextchar
argument_list|,
name|fp
argument_list|)
expr_stmt|;
if|if
condition|(
name|negative
condition|)
name|response
operator|=
operator|-
name|response
expr_stmt|;
return|return
name|response
return|;
block|}
end_function

begin_function
DECL|function|clear_white (FILE * fp)
name|void
name|clear_white
parameter_list|(
name|FILE
modifier|*
name|fp
parameter_list|)
block|{
name|gchar
name|nextchar
decl_stmt|;
while|while
condition|(
name|isspace
argument_list|(
name|nextchar
operator|=
name|fgetc
argument_list|(
name|fp
argument_list|)
argument_list|)
condition|)
comment|/* empty statement */
empty_stmt|;
name|ungetc
argument_list|(
name|nextchar
argument_list|,
name|fp
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
DECL|function|append2 (gchar * string1,gboolean del1,gchar * string2,gboolean del2)
specifier|static
name|gchar
modifier|*
name|append2
parameter_list|(
name|gchar
modifier|*
name|string1
parameter_list|,
name|gboolean
name|del1
parameter_list|,
name|gchar
modifier|*
name|string2
parameter_list|,
name|gboolean
name|del2
parameter_list|)
block|{
name|gchar
modifier|*
name|newstring
init|=
name|g_malloc
argument_list|(
name|strlen
argument_list|(
name|string1
argument_list|)
operator|+
name|strlen
argument_list|(
name|string2
argument_list|)
operator|+
literal|1
argument_list|)
decl_stmt|;
name|sprintf
argument_list|(
name|newstring
argument_list|,
literal|"%s%s"
argument_list|,
name|string1
argument_list|,
name|string2
argument_list|)
expr_stmt|;
if|if
condition|(
name|del1
condition|)
name|g_free
argument_list|(
name|string1
argument_list|)
expr_stmt|;
if|if
condition|(
name|del2
condition|)
name|g_free
argument_list|(
name|string2
argument_list|)
expr_stmt|;
return|return
name|newstring
return|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|idea_dnd_drop_data_available_callback (GtkWidget * widget,GdkEventDropDataAvailable * event,gpointer user_data)
name|idea_dnd_drop_data_available_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|GdkEventDropDataAvailable
modifier|*
name|event
parameter_list|,
name|gpointer
name|user_data
parameter_list|)
block|{
name|gint
name|len
init|=
name|event
operator|->
name|data_numbytes
decl_stmt|;
name|gchar
modifier|*
name|data
init|=
name|event
operator|->
name|data
decl_stmt|;
comment|/* Test for the type that was dropped */
if|if
condition|(
name|strcmp
argument_list|(
name|event
operator|->
name|data_type
argument_list|,
literal|"url:ALL"
argument_list|)
operator|==
literal|0
condition|)
block|{
while|while
condition|(
name|len
operator|>
literal|0
condition|)
block|{
name|file_open
argument_list|(
name|data
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|len
operator|-=
operator|(
name|strlen
argument_list|(
name|data
argument_list|)
operator|+
literal|1
operator|)
expr_stmt|;
name|data
operator|+=
name|strlen
argument_list|(
name|data
argument_list|)
operator|+
literal|1
expr_stmt|;
block|}
block|}
return|return;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|idea_cell_dnd_drop_data_available_callback (GtkWidget * widget,GdkEventDropDataAvailable * event,gpointer user_data)
name|idea_cell_dnd_drop_data_available_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|GdkEventDropDataAvailable
modifier|*
name|event
parameter_list|,
name|gpointer
name|user_data
parameter_list|)
block|{
name|gint
name|len
init|=
name|event
operator|->
name|data_numbytes
decl_stmt|;
name|gchar
modifier|*
name|data
init|=
name|event
operator|->
name|data
decl_stmt|;
comment|/* Test for the type that was dropped */
if|if
condition|(
name|strcmp
argument_list|(
name|event
operator|->
name|data_type
argument_list|,
literal|"url:ALL"
argument_list|)
operator|==
literal|0
condition|)
block|{
while|while
condition|(
name|len
operator|>
literal|0
condition|)
block|{
name|file_open
argument_list|(
name|data
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|len
operator|-=
operator|(
name|strlen
argument_list|(
name|data
argument_list|)
operator|+
literal|1
operator|)
expr_stmt|;
name|data
operator|+=
name|strlen
argument_list|(
name|data
argument_list|)
operator|+
literal|1
expr_stmt|;
block|}
block|}
return|return;
block|}
end_function

begin_function
specifier|static
name|gboolean
DECL|function|idea_window_delete_event_callback (GtkWidget * widget,GdkEvent * event,gpointer data)
name|idea_window_delete_event_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|GdkEvent
modifier|*
name|event
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|save_idea_manager
argument_list|(
name|ideas
argument_list|)
expr_stmt|;
name|free
argument_list|(
name|ideas
argument_list|)
expr_stmt|;
name|ideas
operator|=
literal|0
expr_stmt|;
return|return
name|FALSE
return|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|idea_hide_callback (GtkWidget * widget,gpointer data)
name|idea_hide_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|save_idea_manager
argument_list|(
name|ideas
argument_list|)
expr_stmt|;
name|gtk_widget_destroy
argument_list|(
name|ideas
operator|->
name|window
argument_list|)
expr_stmt|;
name|free
argument_list|(
name|ideas
argument_list|)
expr_stmt|;
name|ideas
operator|=
literal|0
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|open_idea_window ()
name|open_idea_window
parameter_list|()
block|{
name|make_idea_window
argument_list|(
operator|-
literal|1
argument_list|,
operator|-
literal|1
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|make_idea_window (int x,int y)
name|make_idea_window
parameter_list|(
name|int
name|x
parameter_list|,
name|int
name|y
parameter_list|)
block|{
name|GtkWidget
modifier|*
name|main_vbox
decl_stmt|,
modifier|*
name|menu
decl_stmt|;
name|GtkWidget
modifier|*
name|scrolled_win
decl_stmt|;
name|GtkWidget
modifier|*
name|toolbar
decl_stmt|;
name|GtkAccelGroup
modifier|*
name|accel
decl_stmt|;
comment|/* malloc idea_manager */
name|ideas
operator|=
name|g_malloc0
argument_list|(
sizeof|sizeof
argument_list|(
name|idea_manager
argument_list|)
argument_list|)
expr_stmt|;
comment|/* Setup tree */
name|ideas
operator|->
name|tree
operator|=
name|gtk_tree_new
argument_list|()
expr_stmt|;
name|gtk_tree_set_selection_mode
argument_list|(
name|GTK_TREE
argument_list|(
name|ideas
operator|->
name|tree
argument_list|)
argument_list|,
name|GTK_SELECTION_BROWSE
argument_list|)
expr_stmt|;
comment|/* Setup scrolled window */
name|scrolled_win
operator|=
name|gtk_scrolled_window_new
argument_list|(
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|gtk_scrolled_window_set_policy
argument_list|(
name|GTK_SCROLLED_WINDOW
argument_list|(
name|scrolled_win
argument_list|)
argument_list|,
name|GTK_POLICY_AUTOMATIC
argument_list|,
name|GTK_POLICY_ALWAYS
argument_list|)
expr_stmt|;
name|gtk_container_add
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|scrolled_win
argument_list|)
argument_list|,
name|ideas
operator|->
name|tree
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|ideas
operator|->
name|tree
argument_list|)
expr_stmt|;
comment|/* allocate the window and attach the menu */
name|ideas
operator|->
name|window
operator|=
name|gtk_window_new
argument_list|(
name|GTK_WINDOW_TOPLEVEL
argument_list|)
expr_stmt|;
name|ideas
operator|->
name|menubar
operator|=
name|create_idea_menu
argument_list|(
name|ideas
argument_list|)
expr_stmt|;
name|menu
operator|=
name|ideas
operator|->
name|menubar
operator|->
name|widget
expr_stmt|;
comment|/* Setup accelerator (hotkey) table */
name|accel
operator|=
name|ideas
operator|->
name|menubar
operator|->
name|accel_group
expr_stmt|;
comment|/* Setup the window_menu widget for additions and removals */
name|ideas
operator|->
name|window_menu
operator|=
name|GTK_WIDGET
argument_list|(
name|GTK_MENU_ITEM
argument_list|(
name|g_list_nth
argument_list|(
name|GTK_MENU_SHELL
argument_list|(
name|menu
argument_list|)
operator|->
name|children
argument_list|,
literal|1
argument_list|)
operator|->
name|data
argument_list|)
operator|->
name|submenu
argument_list|)
expr_stmt|;
comment|/* Add accelerators to window widget */
name|gtk_window_add_accel_group
argument_list|(
name|GTK_WINDOW
argument_list|(
name|ideas
operator|->
name|window
argument_list|)
argument_list|,
name|accel
argument_list|)
expr_stmt|;
comment|/* Setup the status bar */
name|ideas
operator|->
name|status
operator|=
name|gtk_statusbar_new
argument_list|()
expr_stmt|;
name|ideas
operator|->
name|contextid
operator|=
name|gtk_statusbar_get_context_id
argument_list|(
name|GTK_STATUSBAR
argument_list|(
name|ideas
operator|->
name|status
argument_list|)
argument_list|,
literal|"main context"
argument_list|)
expr_stmt|;
comment|/* Setup the toolbar */
name|toolbar
operator|=
name|create_idea_toolbar
argument_list|()
expr_stmt|;
comment|/* Setup a vbox to contain the menu */
name|main_vbox
operator|=
name|gtk_vbox_new
argument_list|(
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|main_vbox
argument_list|)
argument_list|,
name|menu
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|main_vbox
argument_list|)
argument_list|,
name|toolbar
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|main_vbox
argument_list|)
argument_list|,
name|scrolled_win
argument_list|,
name|TRUE
argument_list|,
name|TRUE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|main_vbox
argument_list|)
argument_list|,
name|ideas
operator|->
name|status
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|menu
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|scrolled_win
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|ideas
operator|->
name|status
argument_list|)
expr_stmt|;
comment|/* Set the GOWindow title */
name|ideas
operator|->
name|title
operator|=
name|g_strdup
argument_list|(
literal|"Document Index"
argument_list|)
expr_stmt|;
comment|/* Set the GtkWindow title */
name|gtk_window_set_title
argument_list|(
name|GTK_WINDOW
argument_list|(
name|ideas
operator|->
name|window
argument_list|)
argument_list|,
name|ideas
operator|->
name|title
argument_list|)
expr_stmt|;
comment|/* Set the initial status message */
name|gtk_statusbar_push
argument_list|(
name|GTK_STATUSBAR
argument_list|(
name|ideas
operator|->
name|status
argument_list|)
argument_list|,
name|ideas
operator|->
name|contextid
argument_list|,
literal|"GTK successfully started"
argument_list|)
expr_stmt|;
comment|/* Connect the signals */
name|gtk_signal_connect
argument_list|(
name|GTK_OBJECT
argument_list|(
name|ideas
operator|->
name|window
argument_list|)
argument_list|,
literal|"delete_event"
argument_list|,
name|GTK_SIGNAL_FUNC
argument_list|(
name|idea_window_delete_event_callback
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
comment|/* Add the main vbox to the window */
name|gtk_container_border_width
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|ideas
operator|->
name|window
argument_list|)
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_container_add
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|ideas
operator|->
name|window
argument_list|)
argument_list|,
name|main_vbox
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|main_vbox
argument_list|)
expr_stmt|;
name|gtk_signal_connect
argument_list|(
name|GTK_OBJECT
argument_list|(
name|ideas
operator|->
name|tree
argument_list|)
argument_list|,
literal|"drop_data_available_event"
argument_list|,
name|GTK_SIGNAL_FUNC
argument_list|(
name|idea_dnd_drop_data_available_callback
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
comment|/* Load and Show window */
name|load_idea_manager
argument_list|(
name|ideas
argument_list|)
expr_stmt|;
comment|/* Set the position of the window if it was requested */
if|if
condition|(
name|x
operator|>=
literal|0
operator|&&
name|y
operator|>=
literal|0
condition|)
name|gtk_widget_set_uposition
argument_list|(
name|ideas
operator|->
name|window
argument_list|,
name|x
argument_list|,
name|y
argument_list|)
expr_stmt|;
name|gtk_widget_dnd_drop_set
argument_list|(
name|ideas
operator|->
name|tree
argument_list|,
name|TRUE
argument_list|,
name|image_drop_types
argument_list|,
literal|1
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|load_idea_manager (idea_manager * ideas)
name|load_idea_manager
parameter_list|(
name|idea_manager
modifier|*
name|ideas
parameter_list|)
block|{
name|FILE
modifier|*
name|fp
decl_stmt|;
name|gchar
modifier|*
name|desktopfile
decl_stmt|;
name|gchar
modifier|*
name|home_dir
decl_stmt|;
name|home_dir
operator|=
name|getenv
argument_list|(
literal|"HOME"
argument_list|)
expr_stmt|;
comment|/* open persistant desktop file. */
name|desktopfile
operator|=
name|append2
argument_list|(
name|home_dir
argument_list|,
name|FALSE
argument_list|,
literal|"/"
name|GIMPDIR
literal|"/ideas"
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|fp
operator|=
name|fopen
argument_list|(
name|desktopfile
argument_list|,
literal|"r"
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|desktopfile
argument_list|)
expr_stmt|;
comment|/* Read in persistant desktop information. */
if|if
condition|(
name|fp
condition|)
block|{
name|gint
name|x
decl_stmt|,
name|y
decl_stmt|,
name|width
decl_stmt|,
name|height
decl_stmt|,
name|length
decl_stmt|;
name|gchar
modifier|*
name|title
decl_stmt|;
name|x
operator|=
name|getinteger
argument_list|(
name|fp
argument_list|)
expr_stmt|;
name|y
operator|=
name|getinteger
argument_list|(
name|fp
argument_list|)
expr_stmt|;
name|width
operator|=
name|getinteger
argument_list|(
name|fp
argument_list|)
expr_stmt|;
name|height
operator|=
name|getinteger
argument_list|(
name|fp
argument_list|)
expr_stmt|;
name|gtk_widget_set_usize
argument_list|(
name|ideas
operator|->
name|window
argument_list|,
name|width
argument_list|,
name|height
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|ideas
operator|->
name|window
argument_list|)
expr_stmt|;
name|gtk_widget_set_uposition
argument_list|(
name|ideas
operator|->
name|window
argument_list|,
name|x
argument_list|,
name|y
argument_list|)
expr_stmt|;
name|gtk_idle_add
argument_list|(
name|reset_usize
argument_list|,
name|ideas
operator|->
name|window
argument_list|)
expr_stmt|;
name|clear_white
argument_list|(
name|fp
argument_list|)
expr_stmt|;
while|while
condition|(
operator|!
name|feof
argument_list|(
name|fp
argument_list|)
condition|)
block|{
name|length
operator|=
name|getinteger
argument_list|(
name|fp
argument_list|)
expr_stmt|;
name|title
operator|=
name|g_malloc0
argument_list|(
name|length
operator|+
literal|1
argument_list|)
expr_stmt|;
name|title
index|[
name|fread
argument_list|(
name|title
argument_list|,
literal|1
argument_list|,
name|length
argument_list|,
name|fp
argument_list|)
index|]
operator|=
literal|0
expr_stmt|;
name|idea_add_in_position
argument_list|(
name|title
argument_list|,
operator|-
literal|1
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|title
argument_list|)
expr_stmt|;
name|clear_white
argument_list|(
name|fp
argument_list|)
expr_stmt|;
block|}
name|fclose
argument_list|(
name|fp
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|gtk_widget_show
argument_list|(
name|ideas
operator|->
name|window
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|save_to_ideas (gpointer data,gpointer user_data)
name|save_to_ideas
parameter_list|(
name|gpointer
name|data
parameter_list|,
name|gpointer
name|user_data
parameter_list|)
block|{
name|gchar
modifier|*
name|title
init|=
name|GTK_LABEL
argument_list|(
name|GTK_BIN
argument_list|(
operator|(
name|GtkWidget
operator|*
operator|)
name|data
argument_list|)
operator|->
name|child
argument_list|)
operator|->
name|label
decl_stmt|;
name|fprintf
argument_list|(
operator|(
name|FILE
operator|*
operator|)
name|user_data
argument_list|,
literal|"%d %s\n"
argument_list|,
name|strlen
argument_list|(
name|title
argument_list|)
argument_list|,
name|title
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|save_idea_manager (idea_manager * ideas)
name|save_idea_manager
parameter_list|(
name|idea_manager
modifier|*
name|ideas
parameter_list|)
block|{
name|FILE
modifier|*
name|fp
decl_stmt|;
name|gchar
modifier|*
name|desktopfile
decl_stmt|;
name|gchar
modifier|*
name|home_dir
decl_stmt|;
name|int
name|x
decl_stmt|,
name|y
decl_stmt|,
name|width
decl_stmt|,
name|height
decl_stmt|;
name|home_dir
operator|=
name|getenv
argument_list|(
literal|"HOME"
argument_list|)
expr_stmt|;
comment|/* open persistant desktop file. */
name|desktopfile
operator|=
name|append2
argument_list|(
name|home_dir
argument_list|,
name|FALSE
argument_list|,
literal|"/"
name|GIMPDIR
literal|"/ideas"
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|fp
operator|=
name|fopen
argument_list|(
name|desktopfile
argument_list|,
literal|"w"
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|desktopfile
argument_list|)
expr_stmt|;
name|gdk_window_get_geometry
argument_list|(
name|ideas
operator|->
name|window
operator|->
name|window
argument_list|,
operator|&
name|x
argument_list|,
operator|&
name|y
argument_list|,
operator|&
name|width
argument_list|,
operator|&
name|height
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|gdk_window_get_origin
argument_list|(
name|ideas
operator|->
name|window
operator|->
name|window
argument_list|,
operator|&
name|x
argument_list|,
operator|&
name|y
argument_list|)
expr_stmt|;
name|fprintf
argument_list|(
name|fp
argument_list|,
literal|"%d %d %d %d\n"
argument_list|,
name|x
argument_list|,
name|y
argument_list|,
name|width
argument_list|,
name|height
argument_list|)
expr_stmt|;
name|g_list_foreach
argument_list|(
name|GTK_TREE
argument_list|(
name|ideas
operator|->
name|tree
argument_list|)
operator|->
name|children
argument_list|,
name|save_to_ideas
argument_list|,
name|fp
argument_list|)
expr_stmt|;
name|fclose
argument_list|(
name|fp
argument_list|)
expr_stmt|;
block|}
end_function

begin_struct
DECL|struct|bool_char_pair
struct|struct
name|bool_char_pair
block|{
DECL|member|boole
name|gboolean
name|boole
decl_stmt|;
DECL|member|string
name|gchar
modifier|*
name|string
decl_stmt|;
block|}
struct|;
end_struct

begin_function
DECL|function|raise_if_match (gpointer data,gpointer user_data)
specifier|static
name|void
name|raise_if_match
parameter_list|(
name|gpointer
name|data
parameter_list|,
name|gpointer
name|user_data
parameter_list|)
block|{
name|GimpImage
modifier|*
name|gimage
init|=
name|GIMP_IMAGE
argument_list|(
name|data
argument_list|)
decl_stmt|;
name|struct
name|bool_char_pair
modifier|*
name|pair
init|=
operator|(
expr|struct
name|bool_char_pair
operator|*
operator|)
name|user_data
decl_stmt|;
if|if
condition|(
operator|(
operator|!
name|pair
operator|->
name|boole
operator|)
operator|&&
name|gimage
operator|->
name|has_filename
condition|)
if|if
condition|(
name|strcmp
argument_list|(
name|pair
operator|->
name|string
argument_list|,
name|gimage
operator|->
name|filename
argument_list|)
operator|==
literal|0
condition|)
block|{
name|pair
operator|->
name|boole
operator|=
name|TRUE
expr_stmt|;
comment|/*	gdk_raise_window( NULL, gimage-> ); */
comment|/* FIXME */
block|}
block|}
end_function

begin_function
DECL|function|open_or_raise (gchar * file_name)
name|void
name|open_or_raise
parameter_list|(
name|gchar
modifier|*
name|file_name
parameter_list|)
block|{
name|struct
name|bool_char_pair
name|pair
decl_stmt|;
name|pair
operator|.
name|boole
operator|=
name|FALSE
expr_stmt|;
name|pair
operator|.
name|string
operator|=
name|file_name
expr_stmt|;
name|gimage_foreach
argument_list|(
name|raise_if_match
argument_list|,
operator|&
name|pair
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|pair
operator|.
name|boole
condition|)
block|{
name|file_open
argument_list|(
name|file_name
argument_list|,
name|file_name
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
DECL|function|open_or_raise_callback (GtkWidget * widget,GdkEventButton * event,gpointer func_data)
name|gint
name|open_or_raise_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|GdkEventButton
modifier|*
name|event
parameter_list|,
name|gpointer
name|func_data
parameter_list|)
block|{
if|if
condition|(
name|GTK_IS_TREE_ITEM
argument_list|(
name|widget
argument_list|)
operator|&&
name|event
operator|->
name|type
operator|==
name|GDK_2BUTTON_PRESS
condition|)
block|{
name|open_or_raise
argument_list|(
name|GTK_LABEL
argument_list|(
name|GTK_BIN
argument_list|(
name|widget
argument_list|)
operator|->
name|child
argument_list|)
operator|->
name|label
argument_list|)
expr_stmt|;
block|}
return|return
name|FALSE
return|;
block|}
end_function

begin_function
DECL|function|raise_idea_callback (GtkWidget * widget,gpointer data)
name|void
name|raise_idea_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
if|if
condition|(
name|ideas
condition|)
name|gdk_window_raise
argument_list|(
name|ideas
operator|->
name|window
operator|->
name|window
argument_list|)
expr_stmt|;
else|else
name|open_idea_window
argument_list|()
expr_stmt|;
block|}
end_function

begin_function
DECL|function|check_needed (gpointer data,gpointer user_data)
specifier|static
name|void
name|check_needed
parameter_list|(
name|gpointer
name|data
parameter_list|,
name|gpointer
name|user_data
parameter_list|)
block|{
name|GtkWidget
modifier|*
name|widget
init|=
operator|(
name|GtkWidget
operator|*
operator|)
name|data
decl_stmt|;
name|struct
name|bool_char_pair
modifier|*
name|pair
init|=
operator|(
expr|struct
name|bool_char_pair
operator|*
operator|)
name|user_data
decl_stmt|;
if|if
condition|(
name|strcmp
argument_list|(
name|pair
operator|->
name|string
argument_list|,
name|GTK_LABEL
argument_list|(
name|GTK_BIN
argument_list|(
name|widget
argument_list|)
operator|->
name|child
argument_list|)
operator|->
name|label
argument_list|)
operator|==
literal|0
condition|)
block|{
name|pair
operator|->
name|boole
operator|=
name|TRUE
expr_stmt|;
block|}
block|}
end_function

begin_function
DECL|function|idea_add (gchar * title)
name|void
name|idea_add
parameter_list|(
name|gchar
modifier|*
name|title
parameter_list|)
block|{
name|idea_add_in_position
argument_list|(
name|title
argument_list|,
literal|0
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
DECL|function|idea_add_in_position_with_select (gchar * title,gint position,gboolean select)
name|void
name|idea_add_in_position_with_select
parameter_list|(
name|gchar
modifier|*
name|title
parameter_list|,
name|gint
name|position
parameter_list|,
name|gboolean
name|select
parameter_list|)
block|{
name|GtkWidget
modifier|*
name|treeitem
decl_stmt|;
name|struct
name|bool_char_pair
name|pair
decl_stmt|;
if|if
condition|(
name|ideas
condition|)
block|{
name|pair
operator|.
name|boole
operator|=
name|FALSE
expr_stmt|;
name|pair
operator|.
name|string
operator|=
name|title
expr_stmt|;
name|g_list_foreach
argument_list|(
name|GTK_TREE
argument_list|(
name|ideas
operator|->
name|tree
argument_list|)
operator|->
name|children
argument_list|,
name|check_needed
argument_list|,
operator|&
name|pair
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|pair
operator|.
name|boole
condition|)
block|{
name|treeitem
operator|=
name|gtk_tree_item_new_with_label
argument_list|(
name|title
argument_list|)
expr_stmt|;
if|if
condition|(
name|position
operator|<
literal|0
condition|)
name|gtk_tree_append
argument_list|(
name|GTK_TREE
argument_list|(
name|ideas
operator|->
name|tree
argument_list|)
argument_list|,
name|treeitem
argument_list|)
expr_stmt|;
else|else
name|gtk_tree_insert
argument_list|(
name|GTK_TREE
argument_list|(
name|ideas
operator|->
name|tree
argument_list|)
argument_list|,
name|treeitem
argument_list|,
name|position
argument_list|)
expr_stmt|;
name|gtk_signal_connect
argument_list|(
name|GTK_OBJECT
argument_list|(
name|treeitem
argument_list|)
argument_list|,
literal|"button_press_event"
argument_list|,
name|GTK_SIGNAL_FUNC
argument_list|(
name|open_or_raise_callback
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|gtk_signal_connect
argument_list|(
name|GTK_OBJECT
argument_list|(
name|treeitem
argument_list|)
argument_list|,
literal|"drop_data_available_event"
argument_list|,
name|GTK_SIGNAL_FUNC
argument_list|(
name|idea_cell_dnd_drop_data_available_callback
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|treeitem
argument_list|)
expr_stmt|;
name|gtk_widget_dnd_drop_set
argument_list|(
name|treeitem
argument_list|,
name|TRUE
argument_list|,
name|image_drop_types
argument_list|,
literal|1
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
if|if
condition|(
name|select
condition|)
name|gtk_tree_select_item
argument_list|(
name|GTK_TREE
argument_list|(
name|ideas
operator|->
name|tree
argument_list|)
argument_list|,
name|gtk_tree_child_position
argument_list|(
name|GTK_TREE
argument_list|(
name|ideas
operator|->
name|tree
argument_list|)
argument_list|,
name|treeitem
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
block|}
end_function

begin_function
DECL|function|idea_add_in_position (gchar * title,gint position)
name|void
name|idea_add_in_position
parameter_list|(
name|gchar
modifier|*
name|title
parameter_list|,
name|gint
name|position
parameter_list|)
block|{
name|idea_add_in_position_with_select
argument_list|(
name|title
argument_list|,
name|position
argument_list|,
name|TRUE
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
DECL|function|idea_move (GtkWidget * widget,gint distance,gboolean select)
name|gint
name|idea_move
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gint
name|distance
parameter_list|,
name|gboolean
name|select
parameter_list|)
block|{
name|gint
name|orig_position
init|=
name|g_list_index
argument_list|(
name|GTK_TREE
argument_list|(
name|ideas
operator|->
name|tree
argument_list|)
operator|->
name|children
argument_list|,
name|widget
argument_list|)
decl_stmt|;
name|gint
name|position
init|=
name|orig_position
operator|+
name|distance
decl_stmt|;
name|gchar
modifier|*
name|title
decl_stmt|;
if|if
condition|(
name|position
operator|<
literal|0
condition|)
name|position
operator|=
literal|0
expr_stmt|;
if|if
condition|(
name|position
operator|>=
name|g_list_length
argument_list|(
name|GTK_TREE
argument_list|(
name|ideas
operator|->
name|tree
argument_list|)
operator|->
name|children
argument_list|)
condition|)
name|position
operator|=
name|g_list_length
argument_list|(
name|GTK_TREE
argument_list|(
name|ideas
operator|->
name|tree
argument_list|)
operator|->
name|children
argument_list|)
operator|-
literal|1
expr_stmt|;
if|if
condition|(
name|position
operator|!=
name|orig_position
condition|)
block|{
name|title
operator|=
name|g_strdup
argument_list|(
name|GTK_LABEL
argument_list|(
name|GTK_BIN
argument_list|(
name|widget
argument_list|)
operator|->
name|child
argument_list|)
operator|->
name|label
argument_list|)
expr_stmt|;
name|gtk_container_remove
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|ideas
operator|->
name|tree
argument_list|)
argument_list|,
name|widget
argument_list|)
expr_stmt|;
name|idea_add_in_position_with_select
argument_list|(
name|title
argument_list|,
name|position
argument_list|,
name|select
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|title
argument_list|)
expr_stmt|;
block|}
return|return
name|position
operator|-
name|orig_position
return|;
block|}
end_function

begin_function
DECL|function|idea_remove (GtkWidget * widget)
name|void
name|idea_remove
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|)
block|{
name|gint
name|position
init|=
name|g_list_index
argument_list|(
name|GTK_TREE
argument_list|(
name|ideas
operator|->
name|tree
argument_list|)
operator|->
name|children
argument_list|,
name|widget
argument_list|)
decl_stmt|;
name|gtk_container_remove
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|ideas
operator|->
name|tree
argument_list|)
argument_list|,
name|widget
argument_list|)
expr_stmt|;
if|if
condition|(
name|g_list_length
argument_list|(
name|GTK_TREE
argument_list|(
name|ideas
operator|->
name|tree
argument_list|)
operator|->
name|children
argument_list|)
operator|-
literal|1
operator|<
name|position
condition|)
name|position
operator|=
name|g_list_length
argument_list|(
name|GTK_TREE
argument_list|(
name|ideas
operator|->
name|tree
argument_list|)
operator|->
name|children
argument_list|)
operator|-
literal|1
expr_stmt|;
name|gtk_tree_select_item
argument_list|(
name|GTK_TREE
argument_list|(
name|ideas
operator|->
name|tree
argument_list|)
argument_list|,
name|position
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
DECL|function|idea_up_callback (GtkWidget * widget,gpointer data)
name|void
name|idea_up_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GtkWidget
modifier|*
name|selected
decl_stmt|;
if|if
condition|(
name|GTK_TREE
argument_list|(
name|ideas
operator|->
name|tree
argument_list|)
operator|->
name|selection
condition|)
block|{
name|selected
operator|=
name|GTK_TREE
argument_list|(
name|ideas
operator|->
name|tree
argument_list|)
operator|->
name|selection
operator|->
name|data
expr_stmt|;
if|if
condition|(
name|idea_move
argument_list|(
name|selected
argument_list|,
operator|-
literal|1
argument_list|,
name|TRUE
argument_list|)
operator|!=
operator|-
literal|1
condition|)
name|gtk_statusbar_push
argument_list|(
name|GTK_STATUSBAR
argument_list|(
name|ideas
operator|->
name|status
argument_list|)
argument_list|,
name|ideas
operator|->
name|contextid
argument_list|,
literal|"This file cannot be moved up."
argument_list|)
expr_stmt|;
block|}
else|else
name|gtk_statusbar_push
argument_list|(
name|GTK_STATUSBAR
argument_list|(
name|ideas
operator|->
name|status
argument_list|)
argument_list|,
name|ideas
operator|->
name|contextid
argument_list|,
literal|"There's no selection to move up."
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
DECL|function|idea_down_callback (GtkWidget * widget,gpointer data)
name|void
name|idea_down_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GtkWidget
modifier|*
name|selected
decl_stmt|;
if|if
condition|(
name|GTK_TREE
argument_list|(
name|ideas
operator|->
name|tree
argument_list|)
operator|->
name|selection
condition|)
block|{
name|selected
operator|=
name|GTK_TREE
argument_list|(
name|ideas
operator|->
name|tree
argument_list|)
operator|->
name|selection
operator|->
name|data
expr_stmt|;
if|if
condition|(
name|idea_move
argument_list|(
name|selected
argument_list|,
literal|1
argument_list|,
name|TRUE
argument_list|)
operator|!=
literal|1
condition|)
name|gtk_statusbar_push
argument_list|(
name|GTK_STATUSBAR
argument_list|(
name|ideas
operator|->
name|status
argument_list|)
argument_list|,
name|ideas
operator|->
name|contextid
argument_list|,
literal|"This file cannot be moved down."
argument_list|)
expr_stmt|;
block|}
else|else
name|gtk_statusbar_push
argument_list|(
name|GTK_STATUSBAR
argument_list|(
name|ideas
operator|->
name|status
argument_list|)
argument_list|,
name|ideas
operator|->
name|contextid
argument_list|,
literal|"There's no selection to move down."
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
DECL|function|idea_remove_callback (GtkWidget * widget,gpointer data)
name|void
name|idea_remove_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GtkWidget
modifier|*
name|selected
decl_stmt|;
if|if
condition|(
name|GTK_TREE
argument_list|(
name|ideas
operator|->
name|tree
argument_list|)
operator|->
name|selection
condition|)
block|{
name|selected
operator|=
name|GTK_TREE
argument_list|(
name|ideas
operator|->
name|tree
argument_list|)
operator|->
name|selection
operator|->
name|data
expr_stmt|;
name|idea_remove
argument_list|(
name|selected
argument_list|)
expr_stmt|;
block|}
else|else
name|gtk_statusbar_push
argument_list|(
name|GTK_STATUSBAR
argument_list|(
name|ideas
operator|->
name|status
argument_list|)
argument_list|,
name|ideas
operator|->
name|contextid
argument_list|,
literal|"There's no selection to remove."
argument_list|)
expr_stmt|;
block|}
end_function

end_unit

