begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* The GIMP -- an image manipulation program  * Copyright (C) 1995 Spencer Kimball and Peter Mattis  *  * GimpGradientPreview Widget  * Copyright (C) 2001 Michael Natterer  *  * This program is free software; you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 2 of the License, or  * (at your option) any later version.  *  * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *  * You should have received a copy of the GNU General Public License  * along with this program; if not, write to the Free Software  * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  */
end_comment

begin_include
include|#
directive|include
file|"config.h"
end_include

begin_include
include|#
directive|include
file|<gtk/gtk.h>
end_include

begin_include
include|#
directive|include
file|"apptypes.h"
end_include

begin_include
include|#
directive|include
file|"gimpgradient.h"
end_include

begin_include
include|#
directive|include
file|"gimpgradientpreview.h"
end_include

begin_include
include|#
directive|include
file|"temp_buf.h"
end_include

begin_function_decl
specifier|static
name|void
name|gimp_gradient_preview_class_init
parameter_list|(
name|GimpGradientPreviewClass
modifier|*
name|klass
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_gradient_preview_init
parameter_list|(
name|GimpGradientPreview
modifier|*
name|preview
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_gradient_preview_render
parameter_list|(
name|GimpPreview
modifier|*
name|preview
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_gradient_preview_get_size
parameter_list|(
name|GimpPreview
modifier|*
name|preview
parameter_list|,
name|gint
name|size
parameter_list|,
name|gint
modifier|*
name|width
parameter_list|,
name|gint
modifier|*
name|height
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|gboolean
name|gimp_gradient_preview_needs_popup
parameter_list|(
name|GimpPreview
modifier|*
name|preview
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|GtkWidget
modifier|*
name|gimp_gradient_preview_create_popup
parameter_list|(
name|GimpPreview
modifier|*
name|preview
parameter_list|)
function_decl|;
end_function_decl

begin_decl_stmt
DECL|variable|parent_class
specifier|static
name|GimpPreviewClass
modifier|*
name|parent_class
init|=
name|NULL
decl_stmt|;
end_decl_stmt

begin_function
name|GtkType
DECL|function|gimp_gradient_preview_get_type (void)
name|gimp_gradient_preview_get_type
parameter_list|(
name|void
parameter_list|)
block|{
specifier|static
name|GtkType
name|preview_type
init|=
literal|0
decl_stmt|;
if|if
condition|(
operator|!
name|preview_type
condition|)
block|{
name|GtkTypeInfo
name|preview_info
init|=
block|{
literal|"GimpGradientPreview"
block|,
sizeof|sizeof
argument_list|(
name|GimpGradientPreview
argument_list|)
block|,
sizeof|sizeof
argument_list|(
name|GimpGradientPreviewClass
argument_list|)
block|,
operator|(
name|GtkClassInitFunc
operator|)
name|gimp_gradient_preview_class_init
block|,
operator|(
name|GtkObjectInitFunc
operator|)
name|gimp_gradient_preview_init
block|,
comment|/* reserved_1 */
name|NULL
block|,
comment|/* reserved_2 */
name|NULL
block|,
operator|(
name|GtkClassInitFunc
operator|)
name|NULL
block|}
decl_stmt|;
name|preview_type
operator|=
name|gtk_type_unique
argument_list|(
name|GIMP_TYPE_PREVIEW
argument_list|,
operator|&
name|preview_info
argument_list|)
expr_stmt|;
block|}
return|return
name|preview_type
return|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_gradient_preview_class_init (GimpGradientPreviewClass * klass)
name|gimp_gradient_preview_class_init
parameter_list|(
name|GimpGradientPreviewClass
modifier|*
name|klass
parameter_list|)
block|{
name|GtkObjectClass
modifier|*
name|object_class
decl_stmt|;
name|GimpPreviewClass
modifier|*
name|preview_class
decl_stmt|;
name|object_class
operator|=
operator|(
name|GtkObjectClass
operator|*
operator|)
name|klass
expr_stmt|;
name|preview_class
operator|=
operator|(
name|GimpPreviewClass
operator|*
operator|)
name|klass
expr_stmt|;
name|parent_class
operator|=
name|gtk_type_class
argument_list|(
name|GIMP_TYPE_PREVIEW
argument_list|)
expr_stmt|;
name|preview_class
operator|->
name|get_size
operator|=
name|gimp_gradient_preview_get_size
expr_stmt|;
name|preview_class
operator|->
name|render
operator|=
name|gimp_gradient_preview_render
expr_stmt|;
name|preview_class
operator|->
name|needs_popup
operator|=
name|gimp_gradient_preview_needs_popup
expr_stmt|;
name|preview_class
operator|->
name|create_popup
operator|=
name|gimp_gradient_preview_create_popup
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_gradient_preview_init (GimpGradientPreview * gradient_preview)
name|gimp_gradient_preview_init
parameter_list|(
name|GimpGradientPreview
modifier|*
name|gradient_preview
parameter_list|)
block|{ }
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_gradient_preview_get_size (GimpPreview * preview,gint size,gint * width,gint * height)
name|gimp_gradient_preview_get_size
parameter_list|(
name|GimpPreview
modifier|*
name|preview
parameter_list|,
name|gint
name|size
parameter_list|,
name|gint
modifier|*
name|width
parameter_list|,
name|gint
modifier|*
name|height
parameter_list|)
block|{
operator|*
name|width
operator|=
name|size
operator|*
literal|3
expr_stmt|;
operator|*
name|height
operator|=
name|size
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_gradient_preview_render (GimpPreview * preview)
name|gimp_gradient_preview_render
parameter_list|(
name|GimpPreview
modifier|*
name|preview
parameter_list|)
block|{
name|GimpGradient
modifier|*
name|gradient
decl_stmt|;
name|TempBuf
modifier|*
name|temp_buf
decl_stmt|;
name|gint
name|width
decl_stmt|;
name|gint
name|height
decl_stmt|;
name|gradient
operator|=
name|GIMP_GRADIENT
argument_list|(
name|preview
operator|->
name|viewable
argument_list|)
expr_stmt|;
name|width
operator|=
name|preview
operator|->
name|width
expr_stmt|;
name|height
operator|=
name|preview
operator|->
name|height
expr_stmt|;
name|temp_buf
operator|=
name|gimp_viewable_get_new_preview
argument_list|(
name|preview
operator|->
name|viewable
argument_list|,
name|width
argument_list|,
name|height
argument_list|)
expr_stmt|;
name|gimp_preview_render_and_flush
argument_list|(
name|preview
argument_list|,
name|temp_buf
argument_list|,
operator|-
literal|1
argument_list|)
expr_stmt|;
name|temp_buf_free
argument_list|(
name|temp_buf
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|gboolean
DECL|function|gimp_gradient_preview_needs_popup (GimpPreview * preview)
name|gimp_gradient_preview_needs_popup
parameter_list|(
name|GimpPreview
modifier|*
name|preview
parameter_list|)
block|{
name|GimpGradient
modifier|*
name|gradient
decl_stmt|;
name|gint
name|popup_width
decl_stmt|;
name|gint
name|popup_height
decl_stmt|;
name|gradient
operator|=
name|GIMP_GRADIENT
argument_list|(
name|preview
operator|->
name|viewable
argument_list|)
expr_stmt|;
name|popup_width
operator|=
literal|48
expr_stmt|;
name|popup_height
operator|=
literal|24
expr_stmt|;
if|if
condition|(
name|popup_width
operator|>
name|preview
operator|->
name|width
operator|||
name|popup_height
operator|>
name|preview
operator|->
name|height
condition|)
return|return
name|TRUE
return|;
return|return
name|FALSE
return|;
block|}
end_function

begin_function
specifier|static
name|GtkWidget
modifier|*
DECL|function|gimp_gradient_preview_create_popup (GimpPreview * preview)
name|gimp_gradient_preview_create_popup
parameter_list|(
name|GimpPreview
modifier|*
name|preview
parameter_list|)
block|{
name|GimpGradient
modifier|*
name|gradient
decl_stmt|;
name|gint
name|popup_width
decl_stmt|;
name|gint
name|popup_height
decl_stmt|;
name|gradient
operator|=
name|GIMP_GRADIENT
argument_list|(
name|preview
operator|->
name|viewable
argument_list|)
expr_stmt|;
name|popup_width
operator|=
literal|128
expr_stmt|;
name|popup_height
operator|=
literal|32
expr_stmt|;
return|return
name|gimp_preview_new_full
argument_list|(
name|preview
operator|->
name|viewable
argument_list|,
name|popup_width
argument_list|,
name|popup_height
argument_list|,
literal|0
argument_list|,
name|TRUE
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|)
return|;
block|}
end_function

end_unit

