begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* The GIMP -- an image manipulation program  * Copyright (C) 1995 Spencer Kimball and Peter Mattis  *  * This program is free software; you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 2 of the License, or  * (at your option) any later version.  *  * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *  * You should have received a copy of the GNU General Public License  * along with this program; if not, write to the Free Software  * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  */
end_comment

begin_include
include|#
directive|include
file|"appenv.h"
end_include

begin_include
include|#
directive|include
file|"drawable.h"
end_include

begin_include
include|#
directive|include
file|"gdisplay.h"
end_include

begin_include
include|#
directive|include
file|"gimage.h"
end_include

begin_include
include|#
directive|include
file|"gimage_mask.h"
end_include

begin_include
include|#
directive|include
file|"histogramwidget.h"
end_include

begin_include
include|#
directive|include
file|"tile_manager.h"
end_include

begin_include
include|#
directive|include
file|"libgimp/gimpmath.h"
end_include

begin_define
DECL|macro|WAITING
define|#
directive|define
name|WAITING
value|0
end_define

begin_define
DECL|macro|WORKING
define|#
directive|define
name|WORKING
value|1
end_define

begin_define
DECL|macro|WORK_DELAY
define|#
directive|define
name|WORK_DELAY
value|1
end_define

begin_define
DECL|macro|HISTOGRAM_MASK
define|#
directive|define
name|HISTOGRAM_MASK
value|GDK_EXPOSURE_MASK | \                        GDK_BUTTON_PRESS_MASK | \                        GDK_BUTTON_RELEASE_MASK | \ 		       GDK_BUTTON1_MOTION_MASK
end_define

begin_define
DECL|macro|HISTOGRAM
define|#
directive|define
name|HISTOGRAM
value|0x1
end_define

begin_define
DECL|macro|RANGE
define|#
directive|define
name|RANGE
value|0x2
end_define

begin_define
DECL|macro|ALL
define|#
directive|define
name|ALL
value|0xF
end_define

begin_enum
DECL|enum|__anon2944294a0103
enum|enum
block|{
DECL|enumerator|RANGED
name|RANGED
block|,
DECL|enumerator|LAST_SIGNAL
name|LAST_SIGNAL
block|}
enum|;
end_enum

begin_decl_stmt
DECL|variable|histogram_widget_signals
specifier|static
name|guint
name|histogram_widget_signals
index|[
name|LAST_SIGNAL
index|]
decl_stmt|;
end_decl_stmt

begin_function_decl
specifier|static
name|void
name|histogram_widget_class_init
parameter_list|(
name|HistogramWidgetClass
modifier|*
name|klass
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|histogram_widget_init
parameter_list|(
name|HistogramWidget
modifier|*
name|histogram
parameter_list|)
function_decl|;
end_function_decl

begin_comment
comment|/**************************/
end_comment

begin_comment
comment|/*  Function definitions  */
end_comment

begin_function
name|guint
DECL|function|histogram_widget_get_type (void)
name|histogram_widget_get_type
parameter_list|(
name|void
parameter_list|)
block|{
specifier|static
name|guint
name|type
init|=
literal|0
decl_stmt|;
if|if
condition|(
operator|!
name|type
condition|)
block|{
specifier|static
specifier|const
name|GtkTypeInfo
name|info
init|=
block|{
literal|"HistogramWidget"
block|,
sizeof|sizeof
argument_list|(
name|HistogramWidget
argument_list|)
block|,
sizeof|sizeof
argument_list|(
name|HistogramWidgetClass
argument_list|)
block|,
operator|(
name|GtkClassInitFunc
operator|)
name|histogram_widget_class_init
block|,
operator|(
name|GtkObjectInitFunc
operator|)
name|histogram_widget_init
block|,
name|NULL
block|,
name|NULL
block|}
decl_stmt|;
name|type
operator|=
name|gtk_type_unique
argument_list|(
name|gtk_drawing_area_get_type
argument_list|()
argument_list|,
operator|&
name|info
argument_list|)
expr_stmt|;
block|}
return|return
name|type
return|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|histogram_widget_class_init (HistogramWidgetClass * klass)
name|histogram_widget_class_init
parameter_list|(
name|HistogramWidgetClass
modifier|*
name|klass
parameter_list|)
block|{
name|GtkObjectClass
modifier|*
name|object_class
decl_stmt|;
name|GtkType
name|type
decl_stmt|;
name|object_class
operator|=
name|GTK_OBJECT_CLASS
argument_list|(
name|klass
argument_list|)
expr_stmt|;
name|type
operator|=
name|object_class
operator|->
name|type
expr_stmt|;
name|histogram_widget_signals
index|[
name|RANGED
index|]
operator|=
name|gtk_signal_new
argument_list|(
literal|"rangechanged"
argument_list|,
name|GTK_RUN_FIRST
argument_list|,
comment|/* ? */
name|type
argument_list|,
literal|0
argument_list|,
name|gtk_marshal_NONE__INT_INT
argument_list|,
name|GTK_TYPE_NONE
argument_list|,
literal|2
argument_list|,
name|GTK_TYPE_INT
argument_list|,
name|GTK_TYPE_INT
argument_list|)
expr_stmt|;
name|gtk_object_class_add_signals
argument_list|(
name|GTK_OBJECT_CLASS
argument_list|(
name|klass
argument_list|)
argument_list|,
name|histogram_widget_signals
argument_list|,
name|LAST_SIGNAL
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|histogram_widget_init (HistogramWidget * histogram)
name|histogram_widget_init
parameter_list|(
name|HistogramWidget
modifier|*
name|histogram
parameter_list|)
block|{
name|histogram
operator|->
name|histogram
operator|=
name|NULL
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|histogram_widget_draw (HistogramWidget * histogram,int update)
name|histogram_widget_draw
parameter_list|(
name|HistogramWidget
modifier|*
name|histogram
parameter_list|,
name|int
name|update
parameter_list|)
block|{
name|double
name|max
decl_stmt|;
name|double
name|v
decl_stmt|;
name|int
name|i
decl_stmt|,
name|x
decl_stmt|,
name|y
decl_stmt|;
name|int
name|x1
decl_stmt|,
name|x2
decl_stmt|;
name|int
name|width
decl_stmt|,
name|height
decl_stmt|;
name|width
operator|=
name|GTK_WIDGET
argument_list|(
name|histogram
argument_list|)
operator|->
name|allocation
operator|.
name|width
operator|-
literal|2
expr_stmt|;
name|height
operator|=
name|GTK_WIDGET
argument_list|(
name|histogram
argument_list|)
operator|->
name|allocation
operator|.
name|height
operator|-
literal|2
expr_stmt|;
if|if
condition|(
name|update
operator|&
name|HISTOGRAM
condition|)
block|{
comment|/*  find the maximum value  */
name|max
operator|=
name|gimp_histogram_get_maximum
argument_list|(
name|histogram
operator|->
name|histogram
argument_list|,
name|histogram
operator|->
name|channel
argument_list|)
expr_stmt|;
if|if
condition|(
name|max
operator|>
literal|0.0
condition|)
name|max
operator|=
name|log
argument_list|(
name|max
argument_list|)
expr_stmt|;
else|else
name|max
operator|=
literal|1.0
expr_stmt|;
comment|/*  clear the histogram  */
name|gdk_window_clear
argument_list|(
name|GTK_WIDGET
argument_list|(
name|histogram
argument_list|)
operator|->
name|window
argument_list|)
expr_stmt|;
comment|/*  Draw the axis  */
name|gdk_draw_line
argument_list|(
name|GTK_WIDGET
argument_list|(
name|histogram
argument_list|)
operator|->
name|window
argument_list|,
name|GTK_WIDGET
argument_list|(
name|histogram
argument_list|)
operator|->
name|style
operator|->
name|black_gc
argument_list|,
literal|1
argument_list|,
name|height
operator|+
literal|1
argument_list|,
name|width
argument_list|,
name|height
operator|+
literal|1
argument_list|)
expr_stmt|;
comment|/*  Draw the spikes  */
for|for
control|(
name|i
operator|=
literal|0
init|;
name|i
operator|<
literal|256
condition|;
name|i
operator|++
control|)
block|{
name|x
operator|=
operator|(
name|width
operator|*
name|i
operator|)
operator|/
literal|256
operator|+
literal|1
expr_stmt|;
name|v
operator|=
name|gimp_histogram_get_value
argument_list|(
name|histogram
operator|->
name|histogram
argument_list|,
name|histogram
operator|->
name|channel
argument_list|,
name|i
argument_list|)
expr_stmt|;
if|if
condition|(
name|v
operator|>
literal|0.0
condition|)
name|y
operator|=
call|(
name|int
call|)
argument_list|(
operator|(
name|height
operator|*
name|log
argument_list|(
name|v
argument_list|)
operator|)
operator|/
name|max
argument_list|)
expr_stmt|;
else|else
name|y
operator|=
literal|0
expr_stmt|;
name|gdk_draw_line
argument_list|(
name|GTK_WIDGET
argument_list|(
name|histogram
argument_list|)
operator|->
name|window
argument_list|,
name|GTK_WIDGET
argument_list|(
name|histogram
argument_list|)
operator|->
name|style
operator|->
name|black_gc
argument_list|,
name|x
argument_list|,
name|height
operator|+
literal|1
argument_list|,
name|x
argument_list|,
name|height
operator|+
literal|1
operator|-
name|y
argument_list|)
expr_stmt|;
block|}
block|}
if|if
condition|(
operator|(
name|update
operator|&
name|RANGE
operator|)
operator|&&
name|histogram
operator|->
name|start
operator|>=
literal|0
condition|)
block|{
name|x1
operator|=
operator|(
name|width
operator|*
name|MIN
argument_list|(
name|histogram
operator|->
name|start
argument_list|,
name|histogram
operator|->
name|end
argument_list|)
operator|)
operator|/
literal|256
operator|+
literal|1
expr_stmt|;
name|x2
operator|=
operator|(
name|width
operator|*
name|MAX
argument_list|(
name|histogram
operator|->
name|start
argument_list|,
name|histogram
operator|->
name|end
argument_list|)
operator|)
operator|/
literal|256
operator|+
literal|1
expr_stmt|;
name|gdk_gc_set_function
argument_list|(
name|GTK_WIDGET
argument_list|(
name|histogram
argument_list|)
operator|->
name|style
operator|->
name|black_gc
argument_list|,
name|GDK_INVERT
argument_list|)
expr_stmt|;
name|gdk_draw_rectangle
argument_list|(
name|GTK_WIDGET
argument_list|(
name|histogram
argument_list|)
operator|->
name|window
argument_list|,
name|GTK_WIDGET
argument_list|(
name|histogram
argument_list|)
operator|->
name|style
operator|->
name|black_gc
argument_list|,
name|TRUE
argument_list|,
name|x1
argument_list|,
literal|1
argument_list|,
operator|(
name|x2
operator|-
name|x1
operator|)
operator|+
literal|1
argument_list|,
name|height
argument_list|)
expr_stmt|;
name|gdk_gc_set_function
argument_list|(
name|GTK_WIDGET
argument_list|(
name|histogram
argument_list|)
operator|->
name|style
operator|->
name|black_gc
argument_list|,
name|GDK_COPY
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
specifier|static
name|gint
DECL|function|histogram_widget_events (HistogramWidget * histogram,GdkEvent * event)
name|histogram_widget_events
parameter_list|(
name|HistogramWidget
modifier|*
name|histogram
parameter_list|,
name|GdkEvent
modifier|*
name|event
parameter_list|)
block|{
name|GdkEventButton
modifier|*
name|bevent
decl_stmt|;
name|GdkEventMotion
modifier|*
name|mevent
decl_stmt|;
name|int
name|width
decl_stmt|;
switch|switch
condition|(
name|event
operator|->
name|type
condition|)
block|{
case|case
name|GDK_EXPOSE
case|:
name|histogram_widget_draw
argument_list|(
name|histogram
argument_list|,
name|ALL
argument_list|)
expr_stmt|;
break|break;
case|case
name|GDK_BUTTON_PRESS
case|:
name|bevent
operator|=
operator|(
name|GdkEventButton
operator|*
operator|)
name|event
expr_stmt|;
if|if
condition|(
name|bevent
operator|->
name|button
operator|!=
literal|1
condition|)
break|break;
name|gdk_pointer_grab
argument_list|(
name|GTK_WIDGET
argument_list|(
name|histogram
argument_list|)
operator|->
name|window
argument_list|,
name|FALSE
argument_list|,
name|GDK_BUTTON_RELEASE_MASK
operator||
name|GDK_BUTTON1_MOTION_MASK
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|,
name|bevent
operator|->
name|time
argument_list|)
expr_stmt|;
name|width
operator|=
name|GTK_WIDGET
argument_list|(
name|histogram
argument_list|)
operator|->
name|allocation
operator|.
name|width
operator|-
literal|2
expr_stmt|;
name|histogram_widget_draw
argument_list|(
name|histogram
argument_list|,
name|RANGE
argument_list|)
expr_stmt|;
name|histogram
operator|->
name|start
operator|=
name|CLAMP
argument_list|(
operator|(
operator|(
operator|(
name|bevent
operator|->
name|x
operator|-
literal|1
operator|)
operator|*
literal|256
operator|)
operator|/
name|width
operator|)
argument_list|,
literal|0
argument_list|,
literal|255
argument_list|)
expr_stmt|;
name|histogram
operator|->
name|end
operator|=
name|histogram
operator|->
name|start
expr_stmt|;
name|histogram_widget_draw
argument_list|(
name|histogram
argument_list|,
name|RANGE
argument_list|)
expr_stmt|;
break|break;
case|case
name|GDK_BUTTON_RELEASE
case|:
name|bevent
operator|=
operator|(
name|GdkEventButton
operator|*
operator|)
name|event
expr_stmt|;
name|gdk_pointer_ungrab
argument_list|(
name|bevent
operator|->
name|time
argument_list|)
expr_stmt|;
name|gtk_signal_emit
argument_list|(
name|GTK_OBJECT
argument_list|(
name|histogram
argument_list|)
argument_list|,
name|histogram_widget_signals
index|[
name|RANGED
index|]
argument_list|,
name|MIN
argument_list|(
name|histogram
operator|->
name|start
argument_list|,
name|histogram
operator|->
name|end
argument_list|)
argument_list|,
name|MAX
argument_list|(
name|histogram
operator|->
name|start
argument_list|,
name|histogram
operator|->
name|end
argument_list|)
argument_list|)
expr_stmt|;
break|break;
case|case
name|GDK_MOTION_NOTIFY
case|:
name|mevent
operator|=
operator|(
name|GdkEventMotion
operator|*
operator|)
name|event
expr_stmt|;
name|width
operator|=
name|GTK_WIDGET
argument_list|(
name|histogram
argument_list|)
operator|->
name|allocation
operator|.
name|width
operator|-
literal|2
expr_stmt|;
name|histogram_widget_draw
argument_list|(
name|histogram
argument_list|,
name|RANGE
argument_list|)
expr_stmt|;
name|histogram
operator|->
name|start
operator|=
name|CLAMP
argument_list|(
operator|(
operator|(
operator|(
name|mevent
operator|->
name|x
operator|-
literal|1
operator|)
operator|*
literal|256
operator|)
operator|/
name|width
operator|)
argument_list|,
literal|0
argument_list|,
literal|255
argument_list|)
expr_stmt|;
name|histogram_widget_draw
argument_list|(
name|histogram
argument_list|,
name|RANGE
argument_list|)
expr_stmt|;
break|break;
default|default:
break|break;
block|}
return|return
name|FALSE
return|;
block|}
end_function

begin_function
name|HistogramWidget
modifier|*
DECL|function|histogram_widget_new (int width,int height)
name|histogram_widget_new
parameter_list|(
name|int
name|width
parameter_list|,
name|int
name|height
parameter_list|)
block|{
name|HistogramWidget
modifier|*
name|histogram
init|=
name|HISTOGRAM_WIDGET
argument_list|(
name|gtk_type_new
argument_list|(
name|histogram_widget_get_type
argument_list|()
argument_list|)
argument_list|)
decl_stmt|;
name|gtk_drawing_area_size
argument_list|(
name|GTK_DRAWING_AREA
argument_list|(
name|histogram
argument_list|)
argument_list|,
name|width
operator|+
literal|2
argument_list|,
name|height
operator|+
literal|2
argument_list|)
expr_stmt|;
name|gtk_widget_set_events
argument_list|(
name|GTK_WIDGET
argument_list|(
name|histogram
argument_list|)
argument_list|,
name|HISTOGRAM_MASK
argument_list|)
expr_stmt|;
name|gtk_signal_connect
argument_list|(
name|GTK_OBJECT
argument_list|(
name|histogram
argument_list|)
argument_list|,
literal|"event"
argument_list|,
operator|(
name|GtkSignalFunc
operator|)
name|histogram_widget_events
argument_list|,
name|histogram
argument_list|)
expr_stmt|;
comment|/*  The private details of the histogram  */
name|histogram
operator|->
name|channel
operator|=
name|HISTOGRAM_VALUE
expr_stmt|;
name|histogram
operator|->
name|start
operator|=
literal|0
expr_stmt|;
name|histogram
operator|->
name|end
operator|=
literal|255
expr_stmt|;
name|histogram
operator|->
name|histogram
operator|=
name|NULL
expr_stmt|;
return|return
name|histogram
return|;
block|}
end_function

begin_function
name|void
DECL|function|histogram_widget_destroy (HistogramWidget * histogram)
name|histogram_widget_destroy
parameter_list|(
name|HistogramWidget
modifier|*
name|histogram
parameter_list|)
block|{
name|gtk_widget_destroy
argument_list|(
name|GTK_WIDGET
argument_list|(
name|histogram
argument_list|)
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|histogram
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|histogram_widget_update (HistogramWidget * histogram_widget,GimpHistogram * hist)
name|histogram_widget_update
parameter_list|(
name|HistogramWidget
modifier|*
name|histogram_widget
parameter_list|,
name|GimpHistogram
modifier|*
name|hist
parameter_list|)
block|{
name|histogram_widget
operator|->
name|histogram
operator|=
name|hist
expr_stmt|;
if|if
condition|(
operator|!
name|hist
condition|)
return|return;
if|if
condition|(
name|histogram_widget
operator|->
name|channel
operator|>=
name|gimp_histogram_nchannels
argument_list|(
name|hist
argument_list|)
condition|)
name|histogram_widget_channel
argument_list|(
name|histogram_widget
argument_list|,
literal|0
argument_list|)
expr_stmt|;
comment|/*  Make sure the histogram is updated  */
name|gtk_widget_draw
argument_list|(
name|GTK_WIDGET
argument_list|(
name|histogram_widget
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
comment|/*  Give a range callback  */
name|gtk_signal_emit
argument_list|(
name|GTK_OBJECT
argument_list|(
name|histogram_widget
argument_list|)
argument_list|,
name|histogram_widget_signals
index|[
name|RANGED
index|]
argument_list|,
name|MIN
argument_list|(
name|histogram_widget
operator|->
name|start
argument_list|,
name|histogram_widget
operator|->
name|end
argument_list|)
argument_list|,
name|MAX
argument_list|(
name|histogram_widget
operator|->
name|start
argument_list|,
name|histogram_widget
operator|->
name|end
argument_list|)
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|histogram_widget_range (HistogramWidget * histogram,int start,int end)
name|histogram_widget_range
parameter_list|(
name|HistogramWidget
modifier|*
name|histogram
parameter_list|,
name|int
name|start
parameter_list|,
name|int
name|end
parameter_list|)
block|{
name|histogram_widget_draw
argument_list|(
name|histogram
argument_list|,
name|RANGE
argument_list|)
expr_stmt|;
name|histogram
operator|->
name|start
operator|=
name|start
expr_stmt|;
name|histogram
operator|->
name|end
operator|=
name|end
expr_stmt|;
name|histogram_widget_draw
argument_list|(
name|histogram
argument_list|,
name|RANGE
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|histogram_widget_channel (HistogramWidget * histogram,int channel)
name|histogram_widget_channel
parameter_list|(
name|HistogramWidget
modifier|*
name|histogram
parameter_list|,
name|int
name|channel
parameter_list|)
block|{
name|histogram
operator|->
name|channel
operator|=
name|channel
expr_stmt|;
name|histogram_widget_draw
argument_list|(
name|histogram
argument_list|,
name|ALL
argument_list|)
expr_stmt|;
comment|/*  Give a range callback  */
name|gtk_signal_emit
argument_list|(
name|GTK_OBJECT
argument_list|(
name|histogram
argument_list|)
argument_list|,
name|histogram_widget_signals
index|[
name|RANGED
index|]
argument_list|,
name|MIN
argument_list|(
name|histogram
operator|->
name|start
argument_list|,
name|histogram
operator|->
name|end
argument_list|)
argument_list|,
name|MAX
argument_list|(
name|histogram
operator|->
name|start
argument_list|,
name|histogram
operator|->
name|end
argument_list|)
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|GimpHistogram
modifier|*
DECL|function|histogram_widget_histogram (HistogramWidget * histogram)
name|histogram_widget_histogram
parameter_list|(
name|HistogramWidget
modifier|*
name|histogram
parameter_list|)
block|{
return|return
name|histogram
operator|->
name|histogram
return|;
block|}
end_function

end_unit

