begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* The GIMP -- an image manipulation program  * Copyright (C) 1999 Andy Thomas alt@picnic.demon.co.uk  *  * This program is free software; you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 2 of the License, or  * (at your option) any later version.  *  * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *  * You should have received a copy of the GNU General Public License  * along with this program; if not, write to the Free Software  * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  */
end_comment

begin_ifndef
ifndef|#
directive|ifndef
name|__PATHSP_H__
end_ifndef

begin_define
DECL|macro|__PATHSP_H__
define|#
directive|define
name|__PATHSP_H__
end_define

begin_include
include|#
directive|include
file|"libgimp/gimpmatrix.h"
end_include

begin_include
include|#
directive|include
file|"gdisplayF.h"
end_include

begin_comment
comment|/* GDisplay */
end_comment

begin_include
include|#
directive|include
file|"gimpimageF.h"
end_include

begin_comment
comment|/* Tattoo   */
end_comment

begin_typedef
typedef|typedef
struct|struct
DECL|struct|__anon2b0749720108
block|{
DECL|member|type
name|guint32
name|type
decl_stmt|;
DECL|member|x
name|gdouble
name|x
decl_stmt|;
DECL|member|y
name|gdouble
name|y
decl_stmt|;
DECL|typedef|PathPoint
block|}
name|PathPoint
typedef|;
end_typedef

begin_typedef
typedef|typedef
struct|struct
DECL|struct|__anon2b0749720208
block|{
DECL|member|path_details
name|GSList
modifier|*
name|path_details
decl_stmt|;
DECL|member|pathtype
name|guint32
name|pathtype
decl_stmt|;
comment|/* Only beziers to start with */
DECL|member|closed
name|gboolean
name|closed
decl_stmt|;
DECL|member|state
name|guint32
name|state
decl_stmt|;
DECL|member|locked
name|guint32
name|locked
decl_stmt|;
comment|/* Only bottom bit used */
DECL|member|tattoo
name|Tattoo
name|tattoo
decl_stmt|;
comment|/* The tattoo for the path */
DECL|member|name
name|gchar
modifier|*
name|name
decl_stmt|;
DECL|typedef|Path
block|}
name|Path
typedef|;
end_typedef

begin_typedef
typedef|typedef
struct|struct
DECL|struct|__anon2b0749720308
block|{
DECL|member|gimage
name|GimpImage
modifier|*
name|gimage
decl_stmt|;
DECL|member|gdisp
name|GDisplay
modifier|*
name|gdisp
decl_stmt|;
comment|/* This is a hack.. Needed so we can get back to                       * the same display that these curves were added 		     * too. That way when an entry in the paths dialog 		     * is clicked the bezier tool can be targeted at  		     * correct display. Note this display could have been 		     * deleted (ie different view), but gdisplays_check_valid() 		     * function will take care of that.. In this case we just 		     * pick a display that the gimage is rendered in. 		     */
DECL|member|bz_paths
name|GSList
modifier|*
name|bz_paths
decl_stmt|;
comment|/* list of BZPATHP */
DECL|member|sig_id
name|guint
name|sig_id
decl_stmt|;
DECL|member|last_selected_row
name|gint32
name|last_selected_row
decl_stmt|;
DECL|typedef|PathList
block|}
name|PathList
typedef|;
end_typedef

begin_typedef
typedef|typedef
enum|enum
DECL|enum|__anon2b0749720403
block|{
DECL|enumerator|BEZIER
name|BEZIER
init|=
literal|1
DECL|typedef|PathType
block|}
name|PathType
typedef|;
end_typedef

begin_function_decl
name|PathPoint
modifier|*
name|path_point_new
parameter_list|(
name|gint
parameter_list|,
name|gdouble
parameter_list|,
name|gdouble
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|path_point_free
parameter_list|(
name|PathPoint
modifier|*
name|pathpoint
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|Path
modifier|*
name|path_new
parameter_list|(
name|GimpImage
modifier|*
parameter_list|,
name|PathType
parameter_list|,
name|GSList
modifier|*
parameter_list|,
name|gint
parameter_list|,
name|gint
parameter_list|,
name|gint
parameter_list|,
name|gint
parameter_list|,
name|gchar
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|Path
modifier|*
name|path_copy
parameter_list|(
name|GimpImage
modifier|*
name|gimage
parameter_list|,
name|Path
modifier|*
name|p
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|path_free
parameter_list|(
name|Path
modifier|*
name|path
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|Tattoo
name|path_get_tattoo
parameter_list|(
name|Path
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|Path
modifier|*
name|path_get_path_by_tattoo
parameter_list|(
name|GimpImage
modifier|*
parameter_list|,
name|Tattoo
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|path_stroke
parameter_list|(
name|GimpImage
modifier|*
parameter_list|,
name|PathList
modifier|*
parameter_list|,
name|Path
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|gint
name|path_distance
parameter_list|(
name|Path
modifier|*
parameter_list|,
name|gdouble
parameter_list|,
name|gint
modifier|*
parameter_list|,
name|gint
modifier|*
parameter_list|,
name|gdouble
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|PathList
modifier|*
name|path_list_new
parameter_list|(
name|GimpImage
modifier|*
parameter_list|,
name|gint
parameter_list|,
name|GSList
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|path_list_free
parameter_list|(
name|PathList
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|gboolean
name|paths_set_path
parameter_list|(
name|GimpImage
modifier|*
parameter_list|,
name|gchar
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|gboolean
name|paths_set_path_points
parameter_list|(
name|GimpImage
modifier|*
parameter_list|,
name|gchar
modifier|*
parameter_list|,
name|gint
parameter_list|,
name|gint
parameter_list|,
name|gint
parameter_list|,
name|gdouble
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
modifier|*
name|paths_transform_start_undo
parameter_list|(
name|GimpImage
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|paths_transform_free_undo
parameter_list|(
name|void
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|paths_transform_do_undo
parameter_list|(
name|GimpImage
modifier|*
parameter_list|,
name|void
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|paths_transform_current_path
parameter_list|(
name|GimpImage
modifier|*
parameter_list|,
name|GimpMatrix3
parameter_list|,
name|gboolean
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|gboolean
name|paths_delete_path
parameter_list|(
name|GimpImage
modifier|*
parameter_list|,
name|gchar
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|GSList
modifier|*
name|pathpoints_copy
parameter_list|(
name|GSList
modifier|*
name|list
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|pathpoints_free
parameter_list|(
name|GSList
modifier|*
name|list
parameter_list|)
function_decl|;
end_function_decl

begin_endif
endif|#
directive|endif
end_endif

begin_comment
comment|/*  __PATHSP_H__  */
end_comment

end_unit

