begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* gap_pdb_calls.c  *  * this module contains wraper calls of procedures in the GIMPs Procedural Database  *   */
end_comment

begin_comment
comment|/* The GIMP -- an image manipulation program  * Copyright (C) 1995 Spencer Kimball and Peter Mattis  *  * This program is free software; you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 2 of the License, or  * (at your option) any later version.  *  * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *  * You should have received a copy of the GNU General Public License  * along with this program; if not, write to the Free Software  * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  */
end_comment

begin_comment
comment|/* revision history:  * version 1.1.16a; 2000/02/05  hof: path lockedstaus  * version 1.1.15b; 2000/01/30  hof: image parasites  * version 1.1.15a; 2000/01/26  hof: pathes  *                                   removed old gimp 1.0.x PDB Interfaces  * version 1.1.14a; 2000/01/09  hof: thumbnail save/load,  *                              Procedures for video_info file  * version 0.98.00; 1998/11/28  hof: 1.st (pre) release (GAP port to GIMP 1.1)  */
end_comment

begin_include
include|#
directive|include
file|<stdio.h>
end_include

begin_include
include|#
directive|include
file|<stdlib.h>
end_include

begin_include
include|#
directive|include
file|<string.h>
end_include

begin_comment
comment|/* GIMP includes */
end_comment

begin_include
include|#
directive|include
file|"libgimp/gimp.h"
end_include

begin_comment
comment|/* GAP includes */
end_comment

begin_include
include|#
directive|include
file|"gap_pdb_calls.h"
end_include

begin_decl_stmt
specifier|extern
name|int
name|gap_debug
decl_stmt|;
end_decl_stmt

begin_comment
comment|/* ============================================================================  * p_pdb_procedure_available  *   if requested procedure is available in the PDB return the number of args  *      (0 upto n) that are needed to call the procedure.  *   if not available return -1  * ============================================================================  */
end_comment

begin_function
DECL|function|p_pdb_procedure_available (char * proc_name)
name|gint
name|p_pdb_procedure_available
parameter_list|(
name|char
modifier|*
name|proc_name
parameter_list|)
block|{
comment|/* Note: It would be nice to call "gimp_layer_get_linked" direct,     *       but there is not such an Interface in gimp 0.99.16     * Workaround:     *   I did a patch to implement the "gimp_layer_get_linked"     *   procedure, and call it via PDB call if available.     *   if not available FALSE is returned.     */
name|gint
name|l_nparams
decl_stmt|;
name|gint
name|l_nreturn_vals
decl_stmt|;
name|GimpPDBProcType
name|l_proc_type
decl_stmt|;
name|gchar
modifier|*
name|l_proc_blurb
decl_stmt|;
name|gchar
modifier|*
name|l_proc_help
decl_stmt|;
name|gchar
modifier|*
name|l_proc_author
decl_stmt|;
name|gchar
modifier|*
name|l_proc_copyright
decl_stmt|;
name|gchar
modifier|*
name|l_proc_date
decl_stmt|;
name|GimpParamDef
modifier|*
name|l_params
decl_stmt|;
name|GimpParamDef
modifier|*
name|l_return_vals
decl_stmt|;
name|gint
name|l_rc
decl_stmt|;
name|l_rc
operator|=
literal|0
expr_stmt|;
comment|/* Query the gimp application's procedural database    *  regarding a particular procedure.    */
if|if
condition|(
name|gimp_query_procedure
argument_list|(
name|proc_name
argument_list|,
operator|&
name|l_proc_blurb
argument_list|,
operator|&
name|l_proc_help
argument_list|,
operator|&
name|l_proc_author
argument_list|,
operator|&
name|l_proc_copyright
argument_list|,
operator|&
name|l_proc_date
argument_list|,
operator|&
name|l_proc_type
argument_list|,
operator|&
name|l_nparams
argument_list|,
operator|&
name|l_nreturn_vals
argument_list|,
operator|&
name|l_params
argument_list|,
operator|&
name|l_return_vals
argument_list|)
condition|)
block|{
comment|/* procedure found in PDB */
return|return
operator|(
name|l_nparams
operator|)
return|;
block|}
name|printf
argument_list|(
literal|"Warning: Procedure %s not found.\n"
argument_list|,
name|proc_name
argument_list|)
expr_stmt|;
return|return
operator|-
literal|1
return|;
block|}
end_function

begin_comment
comment|/* end p_pdb_procedure_available */
end_comment

begin_comment
comment|/* ---------------------- PDB procedure calls  -------------------------- */
end_comment

begin_comment
comment|/* ============================================================================  * p_get_gimp_selection_bounds  *     * ============================================================================  */
end_comment

begin_function
name|gint
DECL|function|p_get_gimp_selection_bounds (gint32 image_id,gint32 * x1,gint32 * y1,gint32 * x2,gint32 * y2)
name|p_get_gimp_selection_bounds
parameter_list|(
name|gint32
name|image_id
parameter_list|,
name|gint32
modifier|*
name|x1
parameter_list|,
name|gint32
modifier|*
name|y1
parameter_list|,
name|gint32
modifier|*
name|x2
parameter_list|,
name|gint32
modifier|*
name|y2
parameter_list|)
block|{
specifier|static
name|char
modifier|*
name|l_get_sel_bounds_proc
init|=
literal|"gimp_selection_bounds"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_get_sel_bounds_proc
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_IMAGE
argument_list|,
name|image_id
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
operator|*
name|x1
operator|=
name|return_vals
index|[
literal|2
index|]
operator|.
name|data
operator|.
name|d_int32
expr_stmt|;
operator|*
name|y1
operator|=
name|return_vals
index|[
literal|3
index|]
operator|.
name|data
operator|.
name|d_int32
expr_stmt|;
operator|*
name|x2
operator|=
name|return_vals
index|[
literal|4
index|]
operator|.
name|data
operator|.
name|d_int32
expr_stmt|;
operator|*
name|y2
operator|=
name|return_vals
index|[
literal|5
index|]
operator|.
name|data
operator|.
name|d_int32
expr_stmt|;
return|return
operator|(
name|return_vals
index|[
literal|1
index|]
operator|.
name|data
operator|.
name|d_int32
operator|)
return|;
block|}
name|printf
argument_list|(
literal|"GAP: Error: PDB call of %s failed staus=%d\n"
argument_list|,
name|l_get_sel_bounds_proc
argument_list|,
operator|(
name|int
operator|)
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
argument_list|)
expr_stmt|;
return|return
operator|(
name|FALSE
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_get_gimp_selection_bounds */
end_comment

begin_comment
comment|/* ============================================================================  * p_gimp_selection_load  *     * ============================================================================  */
end_comment

begin_function
name|gint
DECL|function|p_gimp_selection_load (gint32 channel_id)
name|p_gimp_selection_load
parameter_list|(
name|gint32
name|channel_id
parameter_list|)
block|{
specifier|static
name|char
modifier|*
name|l_sel_load
init|=
literal|"gimp_selection_load"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_sel_load
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_CHANNEL
argument_list|,
name|channel_id
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
return|return
operator|(
name|TRUE
operator|)
return|;
block|}
name|printf
argument_list|(
literal|"GAP: Error: PDB call of %s failed status=%d\n"
argument_list|,
name|l_sel_load
argument_list|,
operator|(
name|int
operator|)
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
argument_list|)
expr_stmt|;
return|return
operator|(
name|FALSE
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_gimp_selection_load */
end_comment

begin_comment
comment|/* ============================================================================  * p_layer_set_linked  *   set linked state of the layer  * ============================================================================  */
end_comment

begin_function
name|int
DECL|function|p_layer_set_linked (gint32 layer_id,gint32 new_state)
name|p_layer_set_linked
parameter_list|(
name|gint32
name|layer_id
parameter_list|,
name|gint32
name|new_state
parameter_list|)
block|{
specifier|static
name|char
modifier|*
name|l_set_linked_proc
init|=
literal|"gimp_layer_set_linked"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_set_linked_proc
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_LAYER
argument_list|,
name|layer_id
argument_list|,
name|PARAM_INT32
argument_list|,
name|new_state
argument_list|,
comment|/* TRUE or FALSE */
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
return|return
operator|(
literal|0
operator|)
return|;
block|}
name|printf
argument_list|(
literal|"GAP: Error: p_layer_set_linked to state %d failed\n"
argument_list|,
operator|(
name|int
operator|)
name|new_state
argument_list|)
expr_stmt|;
return|return
operator|(
operator|-
literal|1
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_layer_set_linked */
end_comment

begin_comment
comment|/* ============================================================================  * p_layer_get_linked  *     * ============================================================================  */
end_comment

begin_function
DECL|function|p_layer_get_linked (gint32 layer_id)
name|gint
name|p_layer_get_linked
parameter_list|(
name|gint32
name|layer_id
parameter_list|)
block|{
specifier|static
name|char
modifier|*
name|l_get_linked_proc
init|=
literal|"gimp_layer_get_linked"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
name|gint32
name|is_linked
decl_stmt|;
name|is_linked
operator|=
name|FALSE
expr_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_get_linked_proc
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_LAYER
argument_list|,
name|layer_id
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
name|is_linked
operator|=
name|return_vals
index|[
literal|1
index|]
operator|.
name|data
operator|.
name|d_int32
expr_stmt|;
block|}
name|gimp_destroy_params
argument_list|(
name|return_vals
argument_list|,
name|nreturn_vals
argument_list|)
expr_stmt|;
return|return
name|is_linked
return|;
block|}
end_function

begin_comment
comment|/* ============================================================================  * p_gimp_image_floating_sel_attached_to  *     * ============================================================================  */
end_comment

begin_function
DECL|function|p_gimp_image_floating_sel_attached_to (gint32 image_id)
name|gint32
name|p_gimp_image_floating_sel_attached_to
parameter_list|(
name|gint32
name|image_id
parameter_list|)
block|{
specifier|static
name|char
modifier|*
name|l_fsel_attached_to_proc
init|=
literal|"gimp_image_floating_sel_attached_to"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_fsel_attached_to_proc
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_IMAGE
argument_list|,
name|image_id
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
return|return
operator|(
name|return_vals
index|[
literal|1
index|]
operator|.
name|data
operator|.
name|d_drawable
operator|)
return|;
block|}
name|printf
argument_list|(
literal|"GAP: Error: PDB call of %s failed\n"
argument_list|,
name|l_fsel_attached_to_proc
argument_list|)
expr_stmt|;
return|return
operator|(
operator|-
literal|1
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_gimp_image_floating_sel_attached_to */
end_comment

begin_comment
comment|/* ============================================================================  * p_gimp_floating_sel_attach  *     * ============================================================================  */
end_comment

begin_function
DECL|function|p_gimp_floating_sel_attach (gint32 layer_id,gint32 drawable_id)
name|gint
name|p_gimp_floating_sel_attach
parameter_list|(
name|gint32
name|layer_id
parameter_list|,
name|gint32
name|drawable_id
parameter_list|)
block|{
specifier|static
name|char
modifier|*
name|l_fsel_attach_proc
init|=
literal|"gimp_floating_sel_attach"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_fsel_attach_proc
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_LAYER
argument_list|,
name|layer_id
argument_list|,
name|PARAM_DRAWABLE
argument_list|,
name|drawable_id
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
return|return
operator|(
literal|0
operator|)
return|;
block|}
name|printf
argument_list|(
literal|"GAP: Error: PDB call of %s failed\n"
argument_list|,
name|l_fsel_attach_proc
argument_list|)
expr_stmt|;
return|return
operator|(
operator|-
literal|1
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_gimp_floating_sel_attach */
end_comment

begin_comment
comment|/* ============================================================================  * p_gimp_floating_sel_rigor  *     * ============================================================================  */
end_comment

begin_function
DECL|function|p_gimp_floating_sel_rigor (gint32 layer_id,gint32 undo)
name|gint
name|p_gimp_floating_sel_rigor
parameter_list|(
name|gint32
name|layer_id
parameter_list|,
name|gint32
name|undo
parameter_list|)
block|{
specifier|static
name|char
modifier|*
name|l_fsel_rigor_proc
init|=
literal|"gimp_floating_sel_rigor"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_fsel_rigor_proc
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_LAYER
argument_list|,
name|layer_id
argument_list|,
name|PARAM_INT32
argument_list|,
name|undo
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
return|return
operator|(
literal|0
operator|)
return|;
block|}
name|printf
argument_list|(
literal|"GAP: Error: PDB call of %s failed\n"
argument_list|,
name|l_fsel_rigor_proc
argument_list|)
expr_stmt|;
return|return
operator|(
operator|-
literal|1
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_gimp_floating_sel_rigor */
end_comment

begin_comment
comment|/* ============================================================================  * p_gimp_floating_sel_relax  *     * ============================================================================  */
end_comment

begin_function
DECL|function|p_gimp_floating_sel_relax (gint32 layer_id,gint32 undo)
name|gint
name|p_gimp_floating_sel_relax
parameter_list|(
name|gint32
name|layer_id
parameter_list|,
name|gint32
name|undo
parameter_list|)
block|{
specifier|static
name|char
modifier|*
name|l_fsel_relax_proc
init|=
literal|"gimp_floating_sel_relax"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_fsel_relax_proc
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_LAYER
argument_list|,
name|layer_id
argument_list|,
name|PARAM_INT32
argument_list|,
name|undo
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
return|return
operator|(
literal|0
operator|)
return|;
block|}
name|printf
argument_list|(
literal|"GAP: Error: PDB call of %s failed\n"
argument_list|,
name|l_fsel_relax_proc
argument_list|)
expr_stmt|;
return|return
operator|(
operator|-
literal|1
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_gimp_floating_sel_relax */
end_comment

begin_comment
comment|/* ============================================================================  * p_gimp_image_add_guide  *     * ============================================================================  */
end_comment

begin_function
DECL|function|p_gimp_image_add_guide (gint32 image_id,gint32 position,gint32 orientation)
name|gint32
name|p_gimp_image_add_guide
parameter_list|(
name|gint32
name|image_id
parameter_list|,
name|gint32
name|position
parameter_list|,
name|gint32
name|orientation
parameter_list|)
block|{
specifier|static
name|char
modifier|*
name|l_add_guide_proc
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
if|if
condition|(
name|orientation
operator|==
name|ORIENTATION_VERTICAL
condition|)
block|{
name|l_add_guide_proc
operator|=
literal|"gimp_image_add_vguide"
expr_stmt|;
block|}
else|else
block|{
name|l_add_guide_proc
operator|=
literal|"gimp_image_add_hguide"
expr_stmt|;
block|}
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_add_guide_proc
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_IMAGE
argument_list|,
name|image_id
argument_list|,
name|PARAM_INT32
argument_list|,
name|position
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
return|return
operator|(
name|return_vals
index|[
literal|1
index|]
operator|.
name|data
operator|.
name|d_int32
operator|)
return|;
comment|/* return the guide ID */
block|}
name|printf
argument_list|(
literal|"GAP: Error: PDB call of %s failed\n"
argument_list|,
name|l_add_guide_proc
argument_list|)
expr_stmt|;
return|return
operator|(
operator|-
literal|1
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_gimp_image_add_guide */
end_comment

begin_comment
comment|/* ============================================================================  * p_gimp_image_findnext_guide  *  * This procedure takes an image and a guide_id as input and finds the guide_id  * of the successor of the given guide_id in the image's Guide list.  * If the supplied guide_id is 0, the procedure will return the first Guide.  * The procedure will return 0 if given the final guide_id as an argument   * or the image has no guides.  *     * ============================================================================  */
end_comment

begin_function
DECL|function|p_gimp_image_findnext_guide (gint32 image_id,gint32 guide_id)
name|gint32
name|p_gimp_image_findnext_guide
parameter_list|(
name|gint32
name|image_id
parameter_list|,
name|gint32
name|guide_id
parameter_list|)
block|{
specifier|static
name|char
modifier|*
name|l_findnext_guide_proc
init|=
literal|"gimp_image_find_next_guide"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_findnext_guide_proc
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_IMAGE
argument_list|,
name|image_id
argument_list|,
name|PARAM_INT32
argument_list|,
name|guide_id
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
return|return
operator|(
name|return_vals
index|[
literal|1
index|]
operator|.
name|data
operator|.
name|d_int32
operator|)
return|;
comment|/* return the next guide ID */
block|}
name|printf
argument_list|(
literal|"GAP: Error: PDB call of %s failed\n"
argument_list|,
name|l_findnext_guide_proc
argument_list|)
expr_stmt|;
return|return
operator|(
operator|-
literal|1
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_gimp_image_findnext_guide */
end_comment

begin_comment
comment|/* ============================================================================  * p_gimp_image_get_guide_position  *  * ============================================================================  */
end_comment

begin_function
DECL|function|p_gimp_image_get_guide_position (gint32 image_id,gint32 guide_id)
name|gint32
name|p_gimp_image_get_guide_position
parameter_list|(
name|gint32
name|image_id
parameter_list|,
name|gint32
name|guide_id
parameter_list|)
block|{
specifier|static
name|char
modifier|*
name|l_get_guide_pos_proc
init|=
literal|"gimp_image_get_guide_position"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_get_guide_pos_proc
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_IMAGE
argument_list|,
name|image_id
argument_list|,
name|PARAM_INT32
argument_list|,
name|guide_id
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
return|return
operator|(
name|return_vals
index|[
literal|1
index|]
operator|.
name|data
operator|.
name|d_int32
operator|)
return|;
comment|/* return the guide position */
block|}
name|printf
argument_list|(
literal|"GAP: Error: PDB call of %s failed\n"
argument_list|,
name|l_get_guide_pos_proc
argument_list|)
expr_stmt|;
return|return
operator|(
operator|-
literal|1
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_gimp_image_get_guide_position */
end_comment

begin_comment
comment|/* ============================================================================  * p_gimp_image_get_guide_orientation  *  * ============================================================================  */
end_comment

begin_function
DECL|function|p_gimp_image_get_guide_orientation (gint32 image_id,gint32 guide_id)
name|gint32
name|p_gimp_image_get_guide_orientation
parameter_list|(
name|gint32
name|image_id
parameter_list|,
name|gint32
name|guide_id
parameter_list|)
block|{
specifier|static
name|char
modifier|*
name|l_get_guide_pos_orient
init|=
literal|"gimp_image_get_guide_orientation"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_get_guide_pos_orient
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_IMAGE
argument_list|,
name|image_id
argument_list|,
name|PARAM_INT32
argument_list|,
name|guide_id
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
return|return
operator|(
name|return_vals
index|[
literal|1
index|]
operator|.
name|data
operator|.
name|d_int32
operator|)
return|;
comment|/* return the guide orientation */
block|}
name|printf
argument_list|(
literal|"GAP: Error: PDB call of %s failed\n"
argument_list|,
name|l_get_guide_pos_orient
argument_list|)
expr_stmt|;
return|return
operator|(
operator|-
literal|1
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_gimp_image_get_guide_orientation */
end_comment

begin_comment
comment|/* ============================================================================  * p_gimp_image_delete_guide  *     * ============================================================================  */
end_comment

begin_function
DECL|function|p_gimp_image_delete_guide (gint32 image_id,gint32 guide_id)
name|gint32
name|p_gimp_image_delete_guide
parameter_list|(
name|gint32
name|image_id
parameter_list|,
name|gint32
name|guide_id
parameter_list|)
block|{
specifier|static
name|char
modifier|*
name|l_delete_guide_proc
init|=
literal|"gimp_image_delete_guide"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_delete_guide_proc
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_IMAGE
argument_list|,
name|image_id
argument_list|,
name|PARAM_INT32
argument_list|,
name|guide_id
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
return|return
operator|(
name|return_vals
index|[
literal|1
index|]
operator|.
name|data
operator|.
name|d_int32
operator|)
return|;
comment|/* return the next guide ID */
block|}
name|printf
argument_list|(
literal|"GAP: Error: PDB call of %s failed\n"
argument_list|,
name|l_delete_guide_proc
argument_list|)
expr_stmt|;
return|return
operator|(
operator|-
literal|1
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_gimp_image_delete_guide */
end_comment

begin_comment
comment|/* ============================================================================  * p_gimp_selection_none  *     * ============================================================================  */
end_comment

begin_function
DECL|function|p_gimp_selection_none (gint32 image_id)
name|gint
name|p_gimp_selection_none
parameter_list|(
name|gint32
name|image_id
parameter_list|)
block|{
specifier|static
name|char
modifier|*
name|l_sel_none_proc
init|=
literal|"gimp_selection_none"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_sel_none_proc
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_IMAGE
argument_list|,
name|image_id
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
return|return
operator|(
literal|0
operator|)
return|;
block|}
name|printf
argument_list|(
literal|"GAP: Error: PDB call of %s failed\n"
argument_list|,
name|l_sel_none_proc
argument_list|)
expr_stmt|;
return|return
operator|(
operator|-
literal|1
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_gimp_selection_none */
end_comment

begin_comment
comment|/* ============================================================================  * p_gimp_rotate  *  PDB call of 'gimp_rotate'  * ============================================================================  */
end_comment

begin_function
DECL|function|p_gimp_rotate (gint32 drawable_id,gint32 interpolation,gdouble angle_deg)
name|gint
name|p_gimp_rotate
parameter_list|(
name|gint32
name|drawable_id
parameter_list|,
name|gint32
name|interpolation
parameter_list|,
name|gdouble
name|angle_deg
parameter_list|)
block|{
specifier|static
name|char
modifier|*
name|l_rotate_proc
init|=
literal|"gimp_rotate"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
name|gdouble
name|l_angle_rad
decl_stmt|;
name|l_angle_rad
operator|=
operator|(
name|angle_deg
operator|*
literal|3.14159
operator|)
operator|/
literal|180.0
expr_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_rotate_proc
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_DRAWABLE
argument_list|,
name|drawable_id
argument_list|,
name|PARAM_INT32
argument_list|,
name|interpolation
argument_list|,
name|PARAM_FLOAT
argument_list|,
name|l_angle_rad
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
return|return
operator|(
literal|0
operator|)
return|;
block|}
return|return
operator|(
operator|-
literal|1
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_gimp_rotate */
end_comment

begin_comment
comment|/* ============================================================================  * p_gimp_channel_ops_duplicate  * ============================================================================  */
end_comment

begin_function
DECL|function|p_gimp_channel_ops_duplicate (gint32 image_ID)
name|gint32
name|p_gimp_channel_ops_duplicate
parameter_list|(
name|gint32
name|image_ID
parameter_list|)
block|{
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
name|gint32
name|new_image_ID
decl_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
literal|"gimp_channel_ops_duplicate"
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_IMAGE
argument_list|,
name|image_ID
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
name|new_image_ID
operator|=
operator|-
literal|1
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
name|new_image_ID
operator|=
name|return_vals
index|[
literal|1
index|]
operator|.
name|data
operator|.
name|d_image
expr_stmt|;
block|}
name|gimp_destroy_params
argument_list|(
name|return_vals
argument_list|,
name|nreturn_vals
argument_list|)
expr_stmt|;
return|return
name|new_image_ID
return|;
block|}
end_function

begin_comment
comment|/* end p_gimp_channel_ops_duplicate */
end_comment

begin_comment
comment|/* ============================================================================  * p_gimp_drawable_set_image  *     * ============================================================================  */
end_comment

begin_function
DECL|function|p_gimp_drawable_set_image (gint32 drawable_id,gint32 image_id)
name|gint
name|p_gimp_drawable_set_image
parameter_list|(
name|gint32
name|drawable_id
parameter_list|,
name|gint32
name|image_id
parameter_list|)
block|{
specifier|static
name|char
modifier|*
name|l_drawable_set_img_proc
init|=
literal|"gimp_drawable_set_image"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_drawable_set_img_proc
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_DRAWABLE
argument_list|,
name|drawable_id
argument_list|,
name|PARAM_IMAGE
argument_list|,
name|image_id
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
return|return
operator|(
literal|0
operator|)
return|;
block|}
name|printf
argument_list|(
literal|"GAP: Error: PDB call of %s failed\n"
argument_list|,
name|l_drawable_set_img_proc
argument_list|)
expr_stmt|;
return|return
operator|(
operator|-
literal|1
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_gimp_drawable_set_image */
end_comment

begin_comment
comment|/* ============================================================================  * p_gimp_gimprc_query  *     * ============================================================================  */
end_comment

begin_function
name|char
modifier|*
DECL|function|p_gimp_gimprc_query (char * key)
name|p_gimp_gimprc_query
parameter_list|(
name|char
modifier|*
name|key
parameter_list|)
block|{
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|gint
name|nreturn_vals
decl_stmt|;
name|char
modifier|*
name|value
decl_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
literal|"gimp_gimprc_query"
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_STRING
argument_list|,
name|key
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
name|value
operator|=
name|NULL
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
if|if
condition|(
name|return_vals
index|[
literal|1
index|]
operator|.
name|data
operator|.
name|d_string
operator|!=
name|NULL
condition|)
block|{
name|value
operator|=
name|g_strdup
argument_list|(
name|return_vals
index|[
literal|1
index|]
operator|.
name|data
operator|.
name|d_string
argument_list|)
expr_stmt|;
block|}
block|}
name|gimp_destroy_params
argument_list|(
name|return_vals
argument_list|,
name|nreturn_vals
argument_list|)
expr_stmt|;
return|return
operator|(
name|value
operator|)
return|;
block|}
end_function

begin_comment
comment|/* ============================================================================  * p_gimp_file_save_thumbnail  *     * ============================================================================  */
end_comment

begin_function
name|gint
DECL|function|p_gimp_file_save_thumbnail (gint32 image_id,char * filename)
name|p_gimp_file_save_thumbnail
parameter_list|(
name|gint32
name|image_id
parameter_list|,
name|char
modifier|*
name|filename
parameter_list|)
block|{
specifier|static
name|char
modifier|*
name|l_called_proc
init|=
literal|"gimp_file_save_thumbnail"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_called_proc
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_IMAGE
argument_list|,
name|image_id
argument_list|,
name|PARAM_STRING
argument_list|,
name|filename
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
return|return
operator|(
literal|0
operator|)
return|;
block|}
name|printf
argument_list|(
literal|"GAP: Error: PDB call of %s failed\n"
argument_list|,
name|l_called_proc
argument_list|)
expr_stmt|;
return|return
operator|(
operator|-
literal|1
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_gimp_file_save_thumbnail */
end_comment

begin_comment
comment|/* ============================================================================  * p_gimp_file_load_thumbnail  *     * ============================================================================  */
end_comment

begin_function
name|gint
DECL|function|p_gimp_file_load_thumbnail (char * filename,gint32 * th_width,gint32 * th_height,gint32 * th_data_count,unsigned char ** th_data)
name|p_gimp_file_load_thumbnail
parameter_list|(
name|char
modifier|*
name|filename
parameter_list|,
name|gint32
modifier|*
name|th_width
parameter_list|,
name|gint32
modifier|*
name|th_height
parameter_list|,
name|gint32
modifier|*
name|th_data_count
parameter_list|,
name|unsigned
name|char
modifier|*
modifier|*
name|th_data
parameter_list|)
block|{
specifier|static
name|char
modifier|*
name|l_called_proc
init|=
literal|"gimp_file_load_thumbnail"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
operator|*
name|th_data
operator|=
name|NULL
expr_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_called_proc
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_STRING
argument_list|,
name|filename
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
operator|*
name|th_width
operator|=
name|return_vals
index|[
literal|1
index|]
operator|.
name|data
operator|.
name|d_int32
expr_stmt|;
operator|*
name|th_height
operator|=
name|return_vals
index|[
literal|2
index|]
operator|.
name|data
operator|.
name|d_int32
expr_stmt|;
operator|*
name|th_data_count
operator|=
name|return_vals
index|[
literal|3
index|]
operator|.
name|data
operator|.
name|d_int32
expr_stmt|;
operator|*
name|th_data
operator|=
operator|(
name|unsigned
name|char
operator|*
operator|)
name|return_vals
index|[
literal|4
index|]
operator|.
name|data
operator|.
name|d_int8array
expr_stmt|;
return|return
operator|(
literal|0
operator|)
return|;
comment|/* OK */
block|}
name|printf
argument_list|(
literal|"GAP: Error: PDB call of %s failed\n"
argument_list|,
name|l_called_proc
argument_list|)
expr_stmt|;
return|return
operator|(
operator|-
literal|1
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_gimp_file_load_thumbnail */
end_comment

begin_function
DECL|function|p_gimp_image_thumbnail (gint32 image_id,gint32 width,gint32 height,gint32 * th_width,gint32 * th_height,gint32 * th_bpp,gint32 * th_data_count,unsigned char ** th_data)
name|gint
name|p_gimp_image_thumbnail
parameter_list|(
name|gint32
name|image_id
parameter_list|,
name|gint32
name|width
parameter_list|,
name|gint32
name|height
parameter_list|,
name|gint32
modifier|*
name|th_width
parameter_list|,
name|gint32
modifier|*
name|th_height
parameter_list|,
name|gint32
modifier|*
name|th_bpp
parameter_list|,
name|gint32
modifier|*
name|th_data_count
parameter_list|,
name|unsigned
name|char
modifier|*
modifier|*
name|th_data
parameter_list|)
block|{
specifier|static
name|char
modifier|*
name|l_called_proc
init|=
literal|"gimp_image_thumbnail"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
operator|*
name|th_data
operator|=
name|NULL
expr_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_called_proc
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_IMAGE
argument_list|,
name|image_id
argument_list|,
name|PARAM_INT32
argument_list|,
name|width
argument_list|,
name|PARAM_INT32
argument_list|,
name|height
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
operator|*
name|th_width
operator|=
name|return_vals
index|[
literal|1
index|]
operator|.
name|data
operator|.
name|d_int32
expr_stmt|;
operator|*
name|th_height
operator|=
name|return_vals
index|[
literal|2
index|]
operator|.
name|data
operator|.
name|d_int32
expr_stmt|;
operator|*
name|th_bpp
operator|=
name|return_vals
index|[
literal|3
index|]
operator|.
name|data
operator|.
name|d_int32
expr_stmt|;
operator|*
name|th_data_count
operator|=
name|return_vals
index|[
literal|4
index|]
operator|.
name|data
operator|.
name|d_int32
expr_stmt|;
operator|*
name|th_data
operator|=
operator|(
name|unsigned
name|char
operator|*
operator|)
name|return_vals
index|[
literal|5
index|]
operator|.
name|data
operator|.
name|d_int8array
expr_stmt|;
return|return
operator|(
literal|0
operator|)
return|;
comment|/* OK */
block|}
name|printf
argument_list|(
literal|"GAP: Error: PDB call of %s failed\n"
argument_list|,
name|l_called_proc
argument_list|)
expr_stmt|;
return|return
operator|(
operator|-
literal|1
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_gimp_image_thumbnail */
end_comment

begin_comment
comment|/* ============================================================================  * p_gimp_path_set_points  *     * ============================================================================  */
end_comment

begin_function
name|gint
DECL|function|p_gimp_path_set_points (gint32 image_id,char * name,gint32 path_type,gint32 num_points,gdouble * path_points)
name|p_gimp_path_set_points
parameter_list|(
name|gint32
name|image_id
parameter_list|,
name|char
modifier|*
name|name
parameter_list|,
name|gint32
name|path_type
parameter_list|,
name|gint32
name|num_points
parameter_list|,
name|gdouble
modifier|*
name|path_points
parameter_list|)
block|{
specifier|static
name|char
modifier|*
name|l_called_proc
init|=
literal|"gimp_path_set_points"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_called_proc
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_IMAGE
argument_list|,
name|image_id
argument_list|,
name|PARAM_STRING
argument_list|,
name|name
argument_list|,
name|PARAM_INT32
argument_list|,
name|path_type
argument_list|,
name|PARAM_INT32
argument_list|,
name|num_points
argument_list|,
name|PARAM_FLOATARRAY
argument_list|,
name|path_points
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
return|return
operator|(
literal|0
operator|)
return|;
comment|/* OK */
block|}
name|printf
argument_list|(
literal|"GAP: Error: PDB call of %s failed\n"
argument_list|,
name|l_called_proc
argument_list|)
expr_stmt|;
return|return
operator|(
operator|-
literal|1
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_gimp_path_set_points */
end_comment

begin_comment
comment|/* ============================================================================  * p_gimp_path_get_points  *     * ============================================================================  */
end_comment

begin_function
name|gdouble
modifier|*
DECL|function|p_gimp_path_get_points (gint32 image_id,char * name,gint32 * path_type,gint32 * path_closed,gint32 * num_points)
name|p_gimp_path_get_points
parameter_list|(
name|gint32
name|image_id
parameter_list|,
name|char
modifier|*
name|name
parameter_list|,
name|gint32
modifier|*
name|path_type
parameter_list|,
name|gint32
modifier|*
name|path_closed
parameter_list|,
name|gint32
modifier|*
name|num_points
parameter_list|)
block|{
specifier|static
name|char
modifier|*
name|l_called_proc
init|=
literal|"gimp_path_get_points"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_called_proc
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_IMAGE
argument_list|,
name|image_id
argument_list|,
name|PARAM_STRING
argument_list|,
name|name
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
operator|*
name|path_type
operator|=
name|return_vals
index|[
literal|1
index|]
operator|.
name|data
operator|.
name|d_int32
expr_stmt|;
operator|*
name|path_closed
operator|=
name|return_vals
index|[
literal|2
index|]
operator|.
name|data
operator|.
name|d_int32
expr_stmt|;
operator|*
name|num_points
operator|=
name|return_vals
index|[
literal|3
index|]
operator|.
name|data
operator|.
name|d_int32
expr_stmt|;
return|return
operator|(
name|return_vals
index|[
literal|4
index|]
operator|.
name|data
operator|.
name|d_floatarray
operator|)
return|;
comment|/* OK return path points */
block|}
name|printf
argument_list|(
literal|"GAP: Error: PDB call of %s failed\n"
argument_list|,
name|l_called_proc
argument_list|)
expr_stmt|;
operator|*
name|num_points
operator|=
literal|0
expr_stmt|;
return|return
operator|(
name|NULL
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_gimp_path_get_points */
end_comment

begin_comment
comment|/* ============================================================================  * p_gimp_path_delete  *     * ============================================================================  */
end_comment

begin_function
name|gint
DECL|function|p_gimp_path_delete (gint32 image_id,char * name)
name|p_gimp_path_delete
parameter_list|(
name|gint32
name|image_id
parameter_list|,
name|char
modifier|*
name|name
parameter_list|)
block|{
specifier|static
name|char
modifier|*
name|l_called_proc
init|=
literal|"gimp_path_delete"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_called_proc
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_IMAGE
argument_list|,
name|image_id
argument_list|,
name|PARAM_STRING
argument_list|,
name|name
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
return|return
operator|(
literal|0
operator|)
return|;
block|}
name|printf
argument_list|(
literal|"GAP: Error: PDB call of %s failed\n"
argument_list|,
name|l_called_proc
argument_list|)
expr_stmt|;
return|return
operator|(
operator|-
literal|1
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_gimp_path_delete */
end_comment

begin_comment
comment|/* ============================================================================  * p_gimp_path_list  *     * ============================================================================  */
end_comment

begin_function
name|char
modifier|*
modifier|*
DECL|function|p_gimp_path_list (gint32 image_id,gint32 * num_paths)
name|p_gimp_path_list
parameter_list|(
name|gint32
name|image_id
parameter_list|,
name|gint32
modifier|*
name|num_paths
parameter_list|)
block|{
specifier|static
name|char
modifier|*
name|l_called_proc
init|=
literal|"gimp_path_list"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_called_proc
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_IMAGE
argument_list|,
name|image_id
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
operator|*
name|num_paths
operator|=
name|return_vals
index|[
literal|1
index|]
operator|.
name|data
operator|.
name|d_int32
expr_stmt|;
return|return
operator|(
name|return_vals
index|[
literal|2
index|]
operator|.
name|data
operator|.
name|d_stringarray
operator|)
return|;
comment|/* OK, return path names */
block|}
name|printf
argument_list|(
literal|"GAP: Error: PDB call of %s failed\n"
argument_list|,
name|l_called_proc
argument_list|)
expr_stmt|;
operator|*
name|num_paths
operator|=
literal|0
expr_stmt|;
return|return
operator|(
name|NULL
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_gimp_path_list */
end_comment

begin_comment
comment|/* ============================================================================  * p_gimp_path_get_current  *     * ============================================================================  */
end_comment

begin_function
name|char
modifier|*
DECL|function|p_gimp_path_get_current (gint32 image_id)
name|p_gimp_path_get_current
parameter_list|(
name|gint32
name|image_id
parameter_list|)
block|{
specifier|static
name|char
modifier|*
name|l_called_proc
init|=
literal|"gimp_path_get_current"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_called_proc
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_IMAGE
argument_list|,
name|image_id
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
return|return
operator|(
name|g_strdup
argument_list|(
name|return_vals
index|[
literal|1
index|]
operator|.
name|data
operator|.
name|d_string
argument_list|)
operator|)
return|;
comment|/* OK */
block|}
name|printf
argument_list|(
literal|"GAP: Error: PDB call of %s failed\n"
argument_list|,
name|l_called_proc
argument_list|)
expr_stmt|;
return|return
operator|(
name|NULL
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_gimp_path_get_current */
end_comment

begin_comment
comment|/* ============================================================================  * p_gimp_path_set_current  *     * ============================================================================  */
end_comment

begin_function
name|gint
DECL|function|p_gimp_path_set_current (gint32 image_id,char * name)
name|p_gimp_path_set_current
parameter_list|(
name|gint32
name|image_id
parameter_list|,
name|char
modifier|*
name|name
parameter_list|)
block|{
specifier|static
name|char
modifier|*
name|l_called_proc
init|=
literal|"gimp_path_set_current"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_called_proc
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_IMAGE
argument_list|,
name|image_id
argument_list|,
name|PARAM_STRING
argument_list|,
name|name
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
return|return
operator|(
literal|0
operator|)
return|;
comment|/* OK */
block|}
name|printf
argument_list|(
literal|"GAP: Error: PDB call of %s failed\n"
argument_list|,
name|l_called_proc
argument_list|)
expr_stmt|;
return|return
operator|(
operator|-
literal|1
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_gimp_path_set_current */
end_comment

begin_comment
comment|/* ============================================================================  * p_gimp_path_get_locked  *     * ============================================================================  */
end_comment

begin_function
name|gint32
DECL|function|p_gimp_path_get_locked (gint32 image_id,gchar * name)
name|p_gimp_path_get_locked
parameter_list|(
name|gint32
name|image_id
parameter_list|,
name|gchar
modifier|*
name|name
parameter_list|)
block|{
specifier|static
name|gchar
modifier|*
name|l_called_proc
init|=
literal|"gimp_path_get_locked"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_called_proc
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_IMAGE
argument_list|,
name|image_id
argument_list|,
name|PARAM_STRING
argument_list|,
name|name
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
return|return
operator|(
name|return_vals
index|[
literal|1
index|]
operator|.
name|data
operator|.
name|d_int32
operator|)
return|;
comment|/* OK */
block|}
name|printf
argument_list|(
literal|"GAP: Error: PDB call of %s failed\n"
argument_list|,
name|l_called_proc
argument_list|)
expr_stmt|;
return|return
operator|(
name|FALSE
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_gimp_path_get_locked */
end_comment

begin_comment
comment|/* ============================================================================  * p_gimp_path_set_locked  *     * ============================================================================  */
end_comment

begin_function
name|gint
DECL|function|p_gimp_path_set_locked (gint32 image_id,gchar * name,gint32 lockstatus)
name|p_gimp_path_set_locked
parameter_list|(
name|gint32
name|image_id
parameter_list|,
name|gchar
modifier|*
name|name
parameter_list|,
name|gint32
name|lockstatus
parameter_list|)
block|{
specifier|static
name|gchar
modifier|*
name|l_called_proc
init|=
literal|"gimp_path_set_locked"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_called_proc
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_IMAGE
argument_list|,
name|image_id
argument_list|,
name|PARAM_STRING
argument_list|,
name|name
argument_list|,
name|PARAM_INT32
argument_list|,
name|lockstatus
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
return|return
operator|(
literal|0
operator|)
return|;
comment|/* OK */
block|}
name|printf
argument_list|(
literal|"GAP: Error: PDB call of %s failed\n"
argument_list|,
name|l_called_proc
argument_list|)
expr_stmt|;
return|return
operator|(
operator|-
literal|1
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_gimp_path_set_locked */
end_comment

begin_comment
comment|/* ============================================================================  * p_gimp_image_parasite_list  * ============================================================================  */
end_comment

begin_function
name|gchar
modifier|*
modifier|*
DECL|function|p_gimp_image_parasite_list (gint32 image_id,gint32 * num_parasites)
name|p_gimp_image_parasite_list
parameter_list|(
name|gint32
name|image_id
parameter_list|,
name|gint32
modifier|*
name|num_parasites
parameter_list|)
block|{
specifier|static
name|gchar
modifier|*
name|l_procname
init|=
literal|"gimp_image_parasite_list"
decl_stmt|;
name|GParam
modifier|*
name|return_vals
decl_stmt|;
name|int
name|nreturn_vals
decl_stmt|;
name|return_vals
operator|=
name|gimp_run_procedure
argument_list|(
name|l_procname
argument_list|,
operator|&
name|nreturn_vals
argument_list|,
name|PARAM_IMAGE
argument_list|,
name|image_id
argument_list|,
name|PARAM_END
argument_list|)
expr_stmt|;
if|if
condition|(
name|return_vals
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|==
name|STATUS_SUCCESS
condition|)
block|{
operator|*
name|num_parasites
operator|=
name|return_vals
index|[
literal|1
index|]
operator|.
name|data
operator|.
name|d_int32
expr_stmt|;
return|return
operator|(
name|return_vals
index|[
literal|2
index|]
operator|.
name|data
operator|.
name|d_stringarray
operator|)
return|;
comment|/* OK, return name list */
block|}
name|printf
argument_list|(
literal|"GAP: Error: PDB call of %s failed\n"
argument_list|,
name|l_procname
argument_list|)
expr_stmt|;
operator|*
name|num_parasites
operator|=
literal|0
expr_stmt|;
return|return
operator|(
name|NULL
operator|)
return|;
block|}
end_function

begin_comment
comment|/* end p_gimp_image_parasite_list */
end_comment

begin_comment
comment|/* ============================================================================  * Procedures to get/set the video_info_file   * ============================================================================  */
end_comment

begin_function
name|char
modifier|*
DECL|function|p_alloc_video_info_name (char * basename)
name|p_alloc_video_info_name
parameter_list|(
name|char
modifier|*
name|basename
parameter_list|)
block|{
name|int
name|l_len
decl_stmt|;
name|char
modifier|*
name|l_str
decl_stmt|;
if|if
condition|(
name|basename
operator|==
name|NULL
condition|)
block|{
return|return
operator|(
name|NULL
operator|)
return|;
block|}
name|l_str
operator|=
name|g_strdup_printf
argument_list|(
literal|"%svin.gap"
argument_list|,
name|basename
argument_list|)
expr_stmt|;
return|return
operator|(
name|l_str
operator|)
return|;
block|}
end_function

begin_function
name|int
DECL|function|p_set_video_info (t_video_info * vin_ptr,char * basename)
name|p_set_video_info
parameter_list|(
name|t_video_info
modifier|*
name|vin_ptr
parameter_list|,
name|char
modifier|*
name|basename
parameter_list|)
block|{
name|FILE
modifier|*
name|l_fp
decl_stmt|;
name|char
modifier|*
name|l_vin_filename
decl_stmt|;
name|int
name|l_rc
decl_stmt|;
name|l_rc
operator|=
operator|-
literal|1
expr_stmt|;
name|l_vin_filename
operator|=
name|p_alloc_video_info_name
argument_list|(
name|basename
argument_list|)
expr_stmt|;
if|if
condition|(
name|l_vin_filename
condition|)
block|{
name|l_fp
operator|=
name|fopen
argument_list|(
name|l_vin_filename
argument_list|,
literal|"w"
argument_list|)
expr_stmt|;
if|if
condition|(
name|l_fp
condition|)
block|{
name|fprintf
argument_list|(
name|l_fp
argument_list|,
literal|"# GIMP / GAP Videoinfo file\n"
argument_list|)
expr_stmt|;
name|fprintf
argument_list|(
name|l_fp
argument_list|,
literal|"(framerate %f) # 1.0 upto 100.0 frames per sec\n"
argument_list|,
operator|(
name|float
operator|)
name|vin_ptr
operator|->
name|framerate
argument_list|)
expr_stmt|;
name|fprintf
argument_list|(
name|l_fp
argument_list|,
literal|"(timezoom %d)  # 1 upto 100 frames\n"
argument_list|,
operator|(
name|int
operator|)
name|vin_ptr
operator|->
name|timezoom
argument_list|)
expr_stmt|;
name|fclose
argument_list|(
name|l_fp
argument_list|)
expr_stmt|;
name|l_rc
operator|=
literal|0
expr_stmt|;
block|}
name|g_free
argument_list|(
name|l_vin_filename
argument_list|)
expr_stmt|;
block|}
return|return
operator|(
name|l_rc
operator|)
return|;
block|}
end_function

begin_function
name|t_video_info
modifier|*
DECL|function|p_get_video_info (char * basename)
name|p_get_video_info
parameter_list|(
name|char
modifier|*
name|basename
parameter_list|)
block|{
name|FILE
modifier|*
name|l_fp
decl_stmt|;
name|char
modifier|*
name|l_vin_filename
decl_stmt|;
name|t_video_info
modifier|*
name|l_vin_ptr
decl_stmt|;
name|char
name|l_buf
index|[
literal|4000
index|]
decl_stmt|;
name|int
name|l_len
decl_stmt|;
name|l_vin_ptr
operator|=
name|g_malloc
argument_list|(
sizeof|sizeof
argument_list|(
name|t_video_info
argument_list|)
argument_list|)
expr_stmt|;
name|l_vin_ptr
operator|->
name|timezoom
operator|=
literal|1
expr_stmt|;
name|l_vin_ptr
operator|->
name|framerate
operator|=
literal|24.0
expr_stmt|;
name|l_vin_filename
operator|=
name|p_alloc_video_info_name
argument_list|(
name|basename
argument_list|)
expr_stmt|;
if|if
condition|(
name|l_vin_filename
condition|)
block|{
name|l_fp
operator|=
name|fopen
argument_list|(
name|l_vin_filename
argument_list|,
literal|"r"
argument_list|)
expr_stmt|;
if|if
condition|(
name|l_fp
condition|)
block|{
while|while
condition|(
name|NULL
operator|!=
name|fgets
argument_list|(
name|l_buf
argument_list|,
literal|4000
operator|-
literal|1
argument_list|,
name|l_fp
argument_list|)
condition|)
block|{
name|l_len
operator|=
name|strlen
argument_list|(
literal|"(framerate "
argument_list|)
expr_stmt|;
if|if
condition|(
name|strncmp
argument_list|(
name|l_buf
argument_list|,
literal|"(framerate "
argument_list|,
name|l_len
argument_list|)
operator|==
literal|0
condition|)
block|{
name|l_vin_ptr
operator|->
name|framerate
operator|=
name|atof
argument_list|(
operator|&
name|l_buf
index|[
name|l_len
index|]
argument_list|)
expr_stmt|;
block|}
name|l_len
operator|=
name|strlen
argument_list|(
literal|"(timezoom "
argument_list|)
expr_stmt|;
if|if
condition|(
name|strncmp
argument_list|(
name|l_buf
argument_list|,
literal|"(timezoom "
argument_list|,
name|l_len
argument_list|)
operator|==
literal|0
condition|)
block|{
name|l_vin_ptr
operator|->
name|timezoom
operator|=
name|atol
argument_list|(
operator|&
name|l_buf
index|[
name|l_len
index|]
argument_list|)
expr_stmt|;
block|}
block|}
name|fclose
argument_list|(
name|l_fp
argument_list|)
expr_stmt|;
block|}
name|g_free
argument_list|(
name|l_vin_filename
argument_list|)
expr_stmt|;
block|}
return|return
operator|(
name|l_vin_ptr
operator|)
return|;
block|}
end_function

end_unit

