begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* GIMP - The GNU Image Manipulation Program  *  * gimpseamlessclonetool.c  * Copyright (C) 2011 Barak Itkin<lightningismyname@gmail.com>  *  * This program is free software: you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 3 of the License, or  * (at your option) any later version.  *  * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *  * You should have received a copy of the GNU General Public License  * along with this program.  If not, see<http://www.gnu.org/licenses/>.  */
end_comment

begin_include
include|#
directive|include
file|"config.h"
end_include

begin_include
include|#
directive|include
file|<string.h>
end_include

begin_include
include|#
directive|include
file|<stdlib.h>
end_include

begin_include
include|#
directive|include
file|<gegl.h>
end_include

begin_include
include|#
directive|include
file|<gtk/gtk.h>
end_include

begin_include
include|#
directive|include
file|<gdk/gdkkeysyms.h>
end_include

begin_include
include|#
directive|include
file|"libgimpbase/gimpbase.h"
end_include

begin_include
include|#
directive|include
file|"libgimpmath/gimpmath.h"
end_include

begin_include
include|#
directive|include
file|"libgimpwidgets/gimpwidgets.h"
end_include

begin_include
include|#
directive|include
file|"tools-types.h"
end_include

begin_include
include|#
directive|include
file|"base/tile-manager.h"
end_include

begin_include
include|#
directive|include
file|"core/gimp.h"
end_include

begin_include
include|#
directive|include
file|"core/gimpbuffer.h"
end_include

begin_include
include|#
directive|include
file|"core/gimpchannel.h"
end_include

begin_include
include|#
directive|include
file|"core/gimpdrawable-shadow.h"
end_include

begin_include
include|#
directive|include
file|"core/gimpimage.h"
end_include

begin_include
include|#
directive|include
file|"core/gimpimagemap.h"
end_include

begin_include
include|#
directive|include
file|"core/gimplayer.h"
end_include

begin_include
include|#
directive|include
file|"core/gimpprogress.h"
end_include

begin_include
include|#
directive|include
file|"core/gimpprojection.h"
end_include

begin_include
include|#
directive|include
file|"widgets/gimphelp-ids.h"
end_include

begin_include
include|#
directive|include
file|"widgets/gimpclipboard.h"
end_include

begin_include
include|#
directive|include
file|"display/gimpdisplay.h"
end_include

begin_include
include|#
directive|include
file|"display/gimpdisplayshell.h"
end_include

begin_include
include|#
directive|include
file|"display/gimpdisplayshell-transform.h"
end_include

begin_include
include|#
directive|include
file|"gimpseamlessclonetool.h"
end_include

begin_include
include|#
directive|include
file|"gimpseamlesscloneoptions.h"
end_include

begin_include
include|#
directive|include
file|"gimptoolcontrol.h"
end_include

begin_include
include|#
directive|include
file|"gimp-intl.h"
end_include

begin_define
DECL|macro|SC_DEBUG
define|#
directive|define
name|SC_DEBUG
value|TRUE
end_define

begin_ifdef
ifdef|#
directive|ifdef
name|SC_DEBUG
end_ifdef

begin_define
DECL|macro|sc_debug_fstart ()
define|#
directive|define
name|sc_debug_fstart
parameter_list|()
value|g_debug ("%s::start", __FUNCTION__);
end_define

begin_define
DECL|macro|sc_debug_fend ()
define|#
directive|define
name|sc_debug_fend
parameter_list|()
value|g_debug ("%s::end", __FUNCTION__);
end_define

begin_else
else|#
directive|else
end_else

begin_define
DECL|macro|sc_debug_fstart ()
define|#
directive|define
name|sc_debug_fstart
parameter_list|()
end_define

begin_define
DECL|macro|sc_debug_fend ()
define|#
directive|define
name|sc_debug_fend
parameter_list|()
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_comment
comment|/*  init ----------> preprocess  *    |                  |  *    |                  |  *    |                  |  *    |                  v  *    |                render(wait, motion)  *    |               /  |  *    |         _____/   |  *    |   _____/         |  *    v  v               v  *  quit<----------  commit  *  * Begin at INIT state  *  * INIT:       Wait for click on canvas  *             have a paste ? -> PREPROCESS : -> QUIT  *   * PREPROCESS: Do the preprocessing  *             -> RENDER  *  * RENDER:     Interact and wait for quit signal  *             commit quit ? -> COMMIT : -> QUIT  *  * COMMIT:     Commit the changes  *             -> QUIT  *  * QUIT:       Invoked by sending a ACTION_HALT to the tool_control  *             Free resources  */
end_comment

begin_enum
enum|enum
DECL|enum|__anon2973aac00103
block|{
DECL|enumerator|SC_STATE_INIT
name|SC_STATE_INIT
block|,
DECL|enumerator|SC_STATE_PREPROCESS
name|SC_STATE_PREPROCESS
block|,
DECL|enumerator|SC_STATE_RENDER_WAIT
name|SC_STATE_RENDER_WAIT
block|,
DECL|enumerator|SC_STATE_RENDER_MOTION
name|SC_STATE_RENDER_MOTION
block|,
DECL|enumerator|SC_STATE_COMMIT
name|SC_STATE_COMMIT
block|,
DECL|enumerator|SC_STATE_QUIT
name|SC_STATE_QUIT
block|}
enum|;
end_enum

begin_function_decl
specifier|static
name|void
name|gimp_seamless_clone_tool_start
parameter_list|(
name|GimpSeamlessCloneTool
modifier|*
name|sc
parameter_list|,
name|GimpDisplay
modifier|*
name|display
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_seamless_clone_tool_stop
parameter_list|(
name|GimpSeamlessCloneTool
modifier|*
name|sc
parameter_list|,
name|gboolean
name|display_change_only
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_seamless_clone_tool_options_notify
parameter_list|(
name|GimpTool
modifier|*
name|tool
parameter_list|,
name|GimpToolOptions
modifier|*
name|options
parameter_list|,
specifier|const
name|GParamSpec
modifier|*
name|pspec
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_seamless_clone_tool_button_press
parameter_list|(
name|GimpTool
modifier|*
name|tool
parameter_list|,
specifier|const
name|GimpCoords
modifier|*
name|coords
parameter_list|,
name|guint32
name|time
parameter_list|,
name|GdkModifierType
name|state
parameter_list|,
name|GimpButtonPressType
name|press_type
parameter_list|,
name|GimpDisplay
modifier|*
name|display
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_seamless_clone_tool_button_release
parameter_list|(
name|GimpTool
modifier|*
name|tool
parameter_list|,
specifier|const
name|GimpCoords
modifier|*
name|coords
parameter_list|,
name|guint32
name|time
parameter_list|,
name|GdkModifierType
name|state
parameter_list|,
name|GimpButtonReleaseType
name|release_type
parameter_list|,
name|GimpDisplay
modifier|*
name|display
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|gboolean
name|gimp_seamless_clone_tool_key_press
parameter_list|(
name|GimpTool
modifier|*
name|tool
parameter_list|,
name|GdkEventKey
modifier|*
name|kevent
parameter_list|,
name|GimpDisplay
modifier|*
name|display
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_seamless_clone_tool_motion
parameter_list|(
name|GimpTool
modifier|*
name|tool
parameter_list|,
specifier|const
name|GimpCoords
modifier|*
name|coords
parameter_list|,
name|guint32
name|time
parameter_list|,
name|GdkModifierType
name|state
parameter_list|,
name|GimpDisplay
modifier|*
name|display
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_seamless_clone_tool_control
parameter_list|(
name|GimpTool
modifier|*
name|tool
parameter_list|,
name|GimpToolAction
name|action
parameter_list|,
name|GimpDisplay
modifier|*
name|display
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_seamless_clone_tool_cursor_update
parameter_list|(
name|GimpTool
modifier|*
name|tool
parameter_list|,
specifier|const
name|GimpCoords
modifier|*
name|coords
parameter_list|,
name|GdkModifierType
name|state
parameter_list|,
name|GimpDisplay
modifier|*
name|display
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_seamless_clone_tool_oper_update
parameter_list|(
name|GimpTool
modifier|*
name|tool
parameter_list|,
specifier|const
name|GimpCoords
modifier|*
name|coords
parameter_list|,
name|GdkModifierType
name|state
parameter_list|,
name|gboolean
name|proximity
parameter_list|,
name|GimpDisplay
modifier|*
name|display
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_seamless_clone_tool_draw
parameter_list|(
name|GimpDrawTool
modifier|*
name|draw_tool
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_seamless_clone_tool_create_image_map
parameter_list|(
name|GimpSeamlessCloneTool
modifier|*
name|sc
parameter_list|,
name|GimpDrawable
modifier|*
name|drawable
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_seamless_clone_tool_image_map_flush
parameter_list|(
name|GimpImageMap
modifier|*
name|image_map
parameter_list|,
name|GimpTool
modifier|*
name|tool
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_seamless_clone_tool_image_map_update
parameter_list|(
name|GimpSeamlessCloneTool
modifier|*
name|sc
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_seamless_clone_tool_create_render_node
parameter_list|(
name|GimpSeamlessCloneTool
modifier|*
name|sc
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_seamless_clone_tool_render_node_update
parameter_list|(
name|GimpSeamlessCloneTool
modifier|*
name|sc
parameter_list|)
function_decl|;
end_function_decl

begin_macro
DECL|function|G_DEFINE_TYPE (GimpSeamlessCloneTool,gimp_seamless_clone_tool,GIMP_TYPE_DRAW_TOOL)
name|G_DEFINE_TYPE
argument_list|(
argument|GimpSeamlessCloneTool
argument_list|,
argument|gimp_seamless_clone_tool
argument_list|,
argument|GIMP_TYPE_DRAW_TOOL
argument_list|)
end_macro

begin_define
DECL|macro|parent_class
define|#
directive|define
name|parent_class
value|gimp_seamless_clone_tool_parent_class
end_define

begin_function
name|void
name|gimp_seamless_clone_tool_register
parameter_list|(
name|GimpToolRegisterCallback
name|callback
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|sc_debug_fstart
argument_list|()
expr_stmt|;
call|(
modifier|*
name|callback
call|)
argument_list|(
name|GIMP_TYPE_SEAMLESS_CLONE_TOOL
argument_list|,
name|GIMP_TYPE_SEAMLESS_CLONE_OPTIONS
argument_list|,
name|gimp_seamless_clone_options_gui
argument_list|,
literal|0
argument_list|,
literal|"gimp-seamless-clone-tool"
argument_list|,
name|_
argument_list|(
literal|"Seamless Clone"
argument_list|)
argument_list|,
name|_
argument_list|(
literal|"Seamless Clone: Seamlessly paste one image into another"
argument_list|)
argument_list|,
name|N_
argument_list|(
literal|"_Seamless Clone"
argument_list|)
argument_list|,
literal|"<shift>L"
argument_list|,
name|NULL
argument_list|,
name|GIMP_HELP_TOOL_SEAMLESS_CLONE
argument_list|,
name|GIMP_STOCK_TOOL_MOVE
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|sc_debug_fend
argument_list|()
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_seamless_clone_tool_class_init (GimpSeamlessCloneToolClass * klass)
name|gimp_seamless_clone_tool_class_init
parameter_list|(
name|GimpSeamlessCloneToolClass
modifier|*
name|klass
parameter_list|)
block|{
name|GimpToolClass
modifier|*
name|tool_class
init|=
name|GIMP_TOOL_CLASS
argument_list|(
name|klass
argument_list|)
decl_stmt|;
name|GimpDrawToolClass
modifier|*
name|draw_tool_class
init|=
name|GIMP_DRAW_TOOL_CLASS
argument_list|(
name|klass
argument_list|)
decl_stmt|;
name|sc_debug_fstart
argument_list|()
expr_stmt|;
name|tool_class
operator|->
name|options_notify
operator|=
name|gimp_seamless_clone_tool_options_notify
expr_stmt|;
name|tool_class
operator|->
name|button_press
operator|=
name|gimp_seamless_clone_tool_button_press
expr_stmt|;
name|tool_class
operator|->
name|button_release
operator|=
name|gimp_seamless_clone_tool_button_release
expr_stmt|;
name|tool_class
operator|->
name|key_press
operator|=
name|gimp_seamless_clone_tool_key_press
expr_stmt|;
name|tool_class
operator|->
name|motion
operator|=
name|gimp_seamless_clone_tool_motion
expr_stmt|;
name|tool_class
operator|->
name|control
operator|=
name|gimp_seamless_clone_tool_control
expr_stmt|;
name|tool_class
operator|->
name|cursor_update
operator|=
name|gimp_seamless_clone_tool_cursor_update
expr_stmt|;
name|tool_class
operator|->
name|oper_update
operator|=
name|gimp_seamless_clone_tool_oper_update
expr_stmt|;
name|draw_tool_class
operator|->
name|draw
operator|=
name|gimp_seamless_clone_tool_draw
expr_stmt|;
name|sc_debug_fend
argument_list|()
expr_stmt|;
block|}
end_function

begin_comment
comment|/**  * gimp_seamless_clone_tool_init:  * @self: The instance of the tool to initialize  *  * Initialize all the pointers to NULL, initialize the state machine,  * moust cursor and the tool control object. This function will be  * called on the first time the tool is being switched to.  */
end_comment

begin_function
specifier|static
name|void
DECL|function|gimp_seamless_clone_tool_init (GimpSeamlessCloneTool * self)
name|gimp_seamless_clone_tool_init
parameter_list|(
name|GimpSeamlessCloneTool
modifier|*
name|self
parameter_list|)
block|{
name|GimpTool
modifier|*
name|tool
init|=
name|GIMP_TOOL
argument_list|(
name|self
argument_list|)
decl_stmt|;
name|sc_debug_fstart
argument_list|()
expr_stmt|;
comment|/* TODO: If we want our tool to be invalidated by something, enable    * the following line. Note that the enum of the dirty properties is    * GimpDirtyMask which is located under app/core/core-enums.h */
comment|//  gimp_tool_control_set_dirty_mask  (tool->control,
comment|//                                     GIMP_DIRTY_IMAGE           |
comment|//                                     GIMP_DIRTY_IMAGE_STRUCTURE |
comment|//                                     GIMP_DIRTY_DRAWABLE        |
comment|//                                     GIMP_DIRTY_SELECTION);
comment|/* TODO: We do need click events, but so do all tools. What's this? */
name|gimp_tool_control_set_wants_click
argument_list|(
name|tool
operator|->
name|control
argument_list|,
name|TRUE
argument_list|)
expr_stmt|;
name|gimp_tool_control_set_tool_cursor
argument_list|(
name|tool
operator|->
name|control
argument_list|,
name|GIMP_TOOL_CURSOR_MOVE
argument_list|)
expr_stmt|;
comment|/* In order to achieve as much instant reponse as possible, only care    * about the location of the mouse at present (while it's being moved)    * and ignore motion events that happened while we were dealing with    * previous motion events */
name|gimp_tool_control_set_motion_mode
argument_list|(
name|tool
operator|->
name|control
argument_list|,
name|GIMP_MOTION_MODE_COMPRESS
argument_list|)
expr_stmt|;
name|self
operator|->
name|paste
operator|=
name|NULL
expr_stmt|;
name|self
operator|->
name|tricache
operator|=
name|NULL
expr_stmt|;
name|self
operator|->
name|mesh_cache
operator|=
name|NULL
expr_stmt|;
name|self
operator|->
name|render_node
operator|=
name|NULL
expr_stmt|;
name|self
operator|->
name|translate_node
operator|=
name|NULL
expr_stmt|;
name|self
operator|->
name|tool_state
operator|=
name|SC_STATE_INIT
expr_stmt|;
name|self
operator|->
name|image_map
operator|=
name|NULL
expr_stmt|;
name|sc_debug_fend
argument_list|()
expr_stmt|;
block|}
end_function

begin_comment
comment|/* This function is called when the tool should pause and resume it's  * action, and when it should halt (i.e. stop and free all resources).  * We are interested in this mainly because we want to free resources  * when the tool terminates, and nothing else...  */
end_comment

begin_function
specifier|static
name|void
DECL|function|gimp_seamless_clone_tool_control (GimpTool * tool,GimpToolAction action,GimpDisplay * display)
name|gimp_seamless_clone_tool_control
parameter_list|(
name|GimpTool
modifier|*
name|tool
parameter_list|,
name|GimpToolAction
name|action
parameter_list|,
name|GimpDisplay
modifier|*
name|display
parameter_list|)
block|{
name|GimpSeamlessCloneTool
modifier|*
name|sc
init|=
name|GIMP_SEAMLESS_CLONE_TOOL
argument_list|(
name|tool
argument_list|)
decl_stmt|;
name|sc_debug_fstart
argument_list|()
expr_stmt|;
if|#
directive|if
name|SC_DEBUG
switch|switch
condition|(
name|action
condition|)
block|{
case|case
name|GIMP_TOOL_ACTION_PAUSE
case|:
name|g_debug
argument_list|(
literal|"sc_tool_control:: GIMP_TOOL_ACTION_PAUSE"
argument_list|)
expr_stmt|;
break|break;
case|case
name|GIMP_TOOL_ACTION_RESUME
case|:
name|g_debug
argument_list|(
literal|"sc_tool_control:: GIMP_TOOL_ACTION_RESUME"
argument_list|)
expr_stmt|;
break|break;
case|case
name|GIMP_TOOL_ACTION_HALT
case|:
name|g_debug
argument_list|(
literal|"sc_tool_control:: GIMP_TOOL_ACTION_HALT"
argument_list|)
expr_stmt|;
break|break;
block|}
endif|#
directive|endif
switch|switch
condition|(
name|action
condition|)
block|{
case|case
name|GIMP_TOOL_ACTION_PAUSE
case|:
case|case
name|GIMP_TOOL_ACTION_RESUME
case|:
break|break;
case|case
name|GIMP_TOOL_ACTION_HALT
case|:
comment|/* We only have what to stop if we are active on some display */
if|if
condition|(
name|tool
operator|->
name|display
operator|!=
name|NULL
condition|)
name|gimp_seamless_clone_tool_stop
argument_list|(
name|sc
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
comment|/* Now, mark that we have no display, so any needed initialization        * will happen on the next time a display is picked */
name|tool
operator|->
name|display
operator|=
name|NULL
expr_stmt|;
comment|/* TODO: If we have any tool options that should be reset, here is        *       a good place to do so.        */
break|break;
block|}
name|GIMP_TOOL_CLASS
argument_list|(
name|parent_class
argument_list|)
operator|->
name|control
argument_list|(
name|tool
argument_list|,
name|action
argument_list|,
name|display
argument_list|)
expr_stmt|;
name|sc_debug_fend
argument_list|()
expr_stmt|;
block|}
end_function

begin_comment
comment|/**  * paste_to_gegl_buf:  * @tool: The GimpTool which wishes to acquire the paste  *  * This function takes a GimpTool as a parameter, and using it's Gimp  * object, it will convert the current buffer in the clipboard into a  * GeglBuffer.  *  * Returns: A GeglBuffer* object representing the active paste in Gimp's  *          clipboard, or NULL if the clipboard does not contain image  *          data  */
end_comment

begin_function
specifier|static
name|GeglBuffer
modifier|*
DECL|function|paste_to_gegl_buf (GimpTool * tool)
name|paste_to_gegl_buf
parameter_list|(
name|GimpTool
modifier|*
name|tool
parameter_list|)
block|{
name|GeglNode
modifier|*
name|gegl
decl_stmt|,
modifier|*
name|input
decl_stmt|,
modifier|*
name|output
decl_stmt|;
name|GeglProcessor
modifier|*
name|processor
decl_stmt|;
name|GimpContext
modifier|*
name|context
init|=
operator|&
name|gimp_tool_get_options
argument_list|(
name|tool
argument_list|)
operator|->
name|parent_instance
decl_stmt|;
name|GimpBuffer
modifier|*
name|buffer
init|=
name|gimp_clipboard_get_buffer
argument_list|(
name|context
operator|->
name|gimp
argument_list|)
decl_stmt|;
name|TileManager
modifier|*
name|tiles
decl_stmt|;
name|gdouble
name|value
decl_stmt|;
name|GeglBuffer
modifier|*
name|result
init|=
name|NULL
decl_stmt|;
if|if
condition|(
name|buffer
condition|)
block|{
name|gegl
operator|=
name|gegl_node_new
argument_list|()
expr_stmt|;
name|input
operator|=
name|gegl_node_new_child
argument_list|(
name|gegl
argument_list|,
literal|"operation"
argument_list|,
literal|"gimp:tilemanager-source"
argument_list|,
literal|"tile-manager"
argument_list|,
name|tiles
operator|=
name|gimp_buffer_get_tiles
argument_list|(
name|buffer
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|output
operator|=
name|gegl_node_new_child
argument_list|(
name|gegl
argument_list|,
literal|"operation"
argument_list|,
literal|"gegl:buffer-sink"
argument_list|,
literal|"buffer"
argument_list|,
operator|&
name|result
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|gegl_node_connect_to
argument_list|(
name|input
argument_list|,
literal|"output"
argument_list|,
name|output
argument_list|,
literal|"input"
argument_list|)
expr_stmt|;
name|processor
operator|=
name|gegl_node_new_processor
argument_list|(
name|output
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
while|while
condition|(
name|gegl_processor_work
argument_list|(
name|processor
argument_list|,
operator|&
name|value
argument_list|)
condition|)
block|{          }
name|gegl_processor_destroy
argument_list|(
name|processor
argument_list|)
expr_stmt|;
name|tile_manager_unref
argument_list|(
name|tiles
argument_list|)
expr_stmt|;
name|g_object_unref
argument_list|(
name|gegl
argument_list|)
expr_stmt|;
name|g_object_unref
argument_list|(
name|buffer
argument_list|)
expr_stmt|;
block|}
return|return
name|result
return|;
block|}
end_function

begin_comment
comment|/**  * gimp_seamless_clone_tool_start:  * @sc: The GimpSeamlessCloneTool to initialize for usage on the given  *      display  * @display: The display to initialize the tool for  *  * A utility function to initialize a tool for working on a given  * display. At the begining of each function, we can check if the event's  * display is the same as the tool's one, and if not call this. This is  * not required by the gimptool interface or anything like that, but  * this is a convinient way to do all the initialization work in one  * place, and this is how the base class (GimpDrawTool) does that  */
end_comment

begin_function
specifier|static
name|void
DECL|function|gimp_seamless_clone_tool_start (GimpSeamlessCloneTool * sc,GimpDisplay * display)
name|gimp_seamless_clone_tool_start
parameter_list|(
name|GimpSeamlessCloneTool
modifier|*
name|sc
parameter_list|,
name|GimpDisplay
modifier|*
name|display
parameter_list|)
block|{
name|GimpTool
modifier|*
name|tool
init|=
name|GIMP_TOOL
argument_list|(
name|sc
argument_list|)
decl_stmt|;
name|GimpImage
modifier|*
name|image
init|=
name|gimp_display_get_image
argument_list|(
name|display
argument_list|)
decl_stmt|;
name|GimpDrawable
modifier|*
name|drawable
init|=
name|gimp_image_get_active_drawable
argument_list|(
name|image
argument_list|)
decl_stmt|;
name|sc_debug_fstart
argument_list|()
expr_stmt|;
comment|/* First handle the paste - we need to make sure we have one in order    * to do anything else. */
if|if
condition|(
name|sc
operator|->
name|paste
operator|==
name|NULL
condition|)
block|{
name|sc
operator|->
name|paste
operator|=
name|paste_to_gegl_buf
argument_list|(
name|GIMP_TOOL
argument_list|(
name|sc
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|sc
operator|->
name|paste
operator|==
name|NULL
condition|)
block|{
comment|/* TODO: prompt for some error message */
return|return;
block|}
else|else
block|{
name|sc
operator|->
name|width
operator|=
name|gegl_buffer_get_width
argument_list|(
name|sc
operator|->
name|paste
argument_list|)
expr_stmt|;
name|sc
operator|->
name|height
operator|=
name|gegl_buffer_get_height
argument_list|(
name|sc
operator|->
name|paste
argument_list|)
expr_stmt|;
block|}
block|}
comment|/* Free resources which are relevant only for the previous display */
name|gimp_seamless_clone_tool_stop
argument_list|(
name|sc
argument_list|,
name|TRUE
argument_list|)
expr_stmt|;
comment|/* Set the new tool display */
name|tool
operator|->
name|display
operator|=
name|display
expr_stmt|;
comment|/* Initialize the image map preview */
name|gimp_seamless_clone_tool_create_image_map
argument_list|(
name|sc
argument_list|,
name|drawable
argument_list|)
expr_stmt|;
comment|/* Now call the start method of the draw tool */
name|gimp_draw_tool_start
argument_list|(
name|GIMP_DRAW_TOOL
argument_list|(
name|sc
argument_list|)
argument_list|,
name|display
argument_list|)
expr_stmt|;
name|sc
operator|->
name|tool_state
operator|=
name|SC_STATE_RENDER_WAIT
expr_stmt|;
name|sc_debug_fend
argument_list|()
expr_stmt|;
block|}
end_function

begin_comment
comment|/**  * gimp_seamless_clone_tool_stop:  * @sc: The seamless clone tool whose resources should be freed  * @display_change_only: Mark that the only reason for this call was a  *                       switch of the working display.  *  * This function frees any resources associated with the seamless clone  * tool, including caches, gegl graphs, and anything the tool created.  * Afterwards, it initializes all the relevant pointers to some initial  * value (usually NULL) like the init function does.  *  * Note that for seamless cloning, no change needs to be done when  * switching to a different display, except for clearing the image map.  * So for that, we provide a boolean parameter to specify that the only  * change was one of the display  */
end_comment

begin_function
specifier|static
name|void
DECL|function|gimp_seamless_clone_tool_stop (GimpSeamlessCloneTool * sc,gboolean display_change_only)
name|gimp_seamless_clone_tool_stop
parameter_list|(
name|GimpSeamlessCloneTool
modifier|*
name|sc
parameter_list|,
name|gboolean
name|display_change_only
parameter_list|)
block|{
name|sc_debug_fstart
argument_list|()
expr_stmt|;
comment|/* See if we actually have any reason to stop */
if|if
condition|(
name|GIMP_TOOL
argument_list|(
name|sc
argument_list|)
operator|->
name|display
operator|==
name|NULL
condition|)
return|return;
if|if
condition|(
operator|!
name|display_change_only
condition|)
block|{
name|sc
operator|->
name|render_node
operator|=
name|NULL
expr_stmt|;
name|sc
operator|->
name|translate_node
operator|=
name|NULL
expr_stmt|;
name|sc
operator|->
name|tool_state
operator|=
name|SC_STATE_INIT
expr_stmt|;
name|sc
operator|->
name|image_map
operator|=
name|NULL
expr_stmt|;
if|if
condition|(
name|sc
operator|->
name|paste
condition|)
block|{
name|gegl_buffer_destroy
argument_list|(
name|sc
operator|->
name|paste
argument_list|)
expr_stmt|;
name|sc
operator|->
name|paste
operator|=
name|NULL
expr_stmt|;
block|}
if|if
condition|(
name|sc
operator|->
name|tricache
condition|)
block|{
name|gegl_buffer_destroy
argument_list|(
name|sc
operator|->
name|tricache
argument_list|)
expr_stmt|;
name|sc
operator|->
name|tricache
operator|=
name|NULL
expr_stmt|;
block|}
if|if
condition|(
name|sc
operator|->
name|render_node
condition|)
block|{
comment|/* When the parent render_node is unreffed completly, it will            * also free all of it's child nodes */
name|g_object_unref
argument_list|(
name|sc
operator|->
name|render_node
argument_list|)
expr_stmt|;
name|sc
operator|->
name|render_node
operator|=
name|NULL
expr_stmt|;
name|sc
operator|->
name|translate_node
operator|=
name|NULL
expr_stmt|;
block|}
comment|/* TODO: free the mesh_cache object */
if|if
condition|(
name|sc
operator|->
name|mesh_cache
condition|)
block|{         }
block|}
comment|/* This should always happen, even when we just switch a display */
if|if
condition|(
name|sc
operator|->
name|image_map
condition|)
block|{
comment|/* This line makes sure the tool won't be aborted when the        * active drawable is being switched.        * Now, the question is why? We are currently handling an        * abort signal, so unless somehow we can have two of these in        * parallel, I don't see any reason to be afraid. Not that it        * does any harm, but still.        * TODO: check this?! */
comment|//      gimp_tool_control_set_preserve (tool->control, TRUE);
comment|/* Stop the computation of the live preview, and mark it not        * to be committed. Then free the image map object. */
name|gimp_image_map_abort
argument_list|(
name|sc
operator|->
name|image_map
argument_list|)
expr_stmt|;
name|g_object_unref
argument_list|(
name|sc
operator|->
name|image_map
argument_list|)
expr_stmt|;
name|sc
operator|->
name|image_map
operator|=
name|NULL
expr_stmt|;
comment|/* Revert the previous set_preserve */
comment|//      gimp_tool_control_set_preserve (tool->control, FALSE);
if|if
condition|(
name|GIMP_TOOL
argument_list|(
name|sc
argument_list|)
operator|->
name|display
condition|)
name|gimp_image_flush
argument_list|(
name|gimp_display_get_image
argument_list|(
name|GIMP_TOOL
argument_list|(
name|sc
argument_list|)
operator|->
name|display
argument_list|)
argument_list|)
expr_stmt|;
block|}
name|gimp_draw_tool_stop
argument_list|(
name|GIMP_DRAW_TOOL
argument_list|(
name|sc
argument_list|)
argument_list|)
expr_stmt|;
name|sc_debug_fend
argument_list|()
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_seamless_clone_tool_options_notify (GimpTool * tool,GimpToolOptions * options,const GParamSpec * pspec)
name|gimp_seamless_clone_tool_options_notify
parameter_list|(
name|GimpTool
modifier|*
name|tool
parameter_list|,
name|GimpToolOptions
modifier|*
name|options
parameter_list|,
specifier|const
name|GParamSpec
modifier|*
name|pspec
parameter_list|)
block|{
comment|// GimpSeamlessCloneTool *sc = GIMP_SEAMLESS_CLONE_TOOL (tool);
name|sc_debug_fstart
argument_list|()
expr_stmt|;
name|GIMP_TOOL_CLASS
argument_list|(
name|parent_class
argument_list|)
operator|->
name|options_notify
argument_list|(
name|tool
argument_list|,
name|options
argument_list|,
name|pspec
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|tool
operator|->
name|display
condition|)
return|return;
comment|/* Pause the tool before modifying the tool data, so that drawing    * won't be done using data in intermidiate states */
name|gimp_draw_tool_pause
argument_list|(
name|GIMP_DRAW_TOOL
argument_list|(
name|tool
argument_list|)
argument_list|)
expr_stmt|;
comment|/* TODO: Modify data here */
comment|/* Done modifying data? If so, now restore the tool drawing */
name|gimp_draw_tool_resume
argument_list|(
name|GIMP_DRAW_TOOL
argument_list|(
name|tool
argument_list|)
argument_list|)
expr_stmt|;
name|sc_debug_fend
argument_list|()
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|gboolean
DECL|function|gimp_seamless_clone_tool_key_press (GimpTool * tool,GdkEventKey * kevent,GimpDisplay * display)
name|gimp_seamless_clone_tool_key_press
parameter_list|(
name|GimpTool
modifier|*
name|tool
parameter_list|,
name|GdkEventKey
modifier|*
name|kevent
parameter_list|,
name|GimpDisplay
modifier|*
name|display
parameter_list|)
block|{
name|sc_debug_fstart
argument_list|()
expr_stmt|;
comment|/* TODO: After checking the key code, return TRUE if the event was    * handled, or FALSE if not */
name|sc_debug_fend
argument_list|()
expr_stmt|;
return|return
name|FALSE
return|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_seamless_clone_tool_motion (GimpTool * tool,const GimpCoords * coords,guint32 time,GdkModifierType state,GimpDisplay * display)
name|gimp_seamless_clone_tool_motion
parameter_list|(
name|GimpTool
modifier|*
name|tool
parameter_list|,
specifier|const
name|GimpCoords
modifier|*
name|coords
parameter_list|,
name|guint32
name|time
parameter_list|,
name|GdkModifierType
name|state
parameter_list|,
name|GimpDisplay
modifier|*
name|display
parameter_list|)
block|{
name|GimpSeamlessCloneTool
modifier|*
name|sc
init|=
name|GIMP_SEAMLESS_CLONE_TOOL
argument_list|(
name|tool
argument_list|)
decl_stmt|;
name|sc_debug_fstart
argument_list|()
expr_stmt|;
comment|/* Pause the tool before modifying the tool data, so that drawing    * won't be done using data in intermidiate states */
name|gimp_draw_tool_pause
argument_list|(
name|GIMP_DRAW_TOOL
argument_list|(
name|tool
argument_list|)
argument_list|)
expr_stmt|;
comment|/* There is nothing to do, unless we were actually moving a paste */
if|if
condition|(
name|sc
operator|->
name|tool_state
operator|==
name|SC_STATE_RENDER_MOTION
condition|)
block|{
name|gimp_draw_tool_pause
argument_list|(
name|GIMP_DRAW_TOOL
argument_list|(
name|sc
argument_list|)
argument_list|)
expr_stmt|;
name|sc
operator|->
name|xoff
operator|=
name|sc
operator|->
name|xoff_p
operator|+
call|(
name|gint
call|)
argument_list|(
name|coords
operator|->
name|x
operator|-
name|sc
operator|->
name|xclick
argument_list|)
expr_stmt|;
name|sc
operator|->
name|yoff
operator|=
name|sc
operator|->
name|yoff_p
operator|+
call|(
name|gint
call|)
argument_list|(
name|coords
operator|->
name|y
operator|-
name|sc
operator|->
name|yclick
argument_list|)
expr_stmt|;
name|gimp_draw_tool_resume
argument_list|(
name|GIMP_DRAW_TOOL
argument_list|(
name|tool
argument_list|)
argument_list|)
expr_stmt|;
block|}
comment|/* Done modifying data? If so, now restore the tool drawing */
name|gimp_draw_tool_resume
argument_list|(
name|GIMP_DRAW_TOOL
argument_list|(
name|tool
argument_list|)
argument_list|)
expr_stmt|;
name|sc_debug_fend
argument_list|()
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_seamless_clone_tool_oper_update (GimpTool * tool,const GimpCoords * coords,GdkModifierType state,gboolean proximity,GimpDisplay * display)
name|gimp_seamless_clone_tool_oper_update
parameter_list|(
name|GimpTool
modifier|*
name|tool
parameter_list|,
specifier|const
name|GimpCoords
modifier|*
name|coords
parameter_list|,
name|GdkModifierType
name|state
parameter_list|,
name|gboolean
name|proximity
parameter_list|,
name|GimpDisplay
modifier|*
name|display
parameter_list|)
block|{
name|sc_debug_fstart
argument_list|()
expr_stmt|;
comment|/* Pause the tool before modifying the tool data, so that drawing    * won't be done using data in intermidiate states */
name|gimp_draw_tool_pause
argument_list|(
name|GIMP_DRAW_TOOL
argument_list|(
name|tool
argument_list|)
argument_list|)
expr_stmt|;
comment|/* TODO: Modify data here */
comment|/* Done modifying data? If so, now restore the tool drawing */
name|gimp_draw_tool_resume
argument_list|(
name|GIMP_DRAW_TOOL
argument_list|(
name|tool
argument_list|)
argument_list|)
expr_stmt|;
name|sc_debug_fend
argument_list|()
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_seamless_clone_tool_button_press (GimpTool * tool,const GimpCoords * coords,guint32 time,GdkModifierType state,GimpButtonPressType press_type,GimpDisplay * display)
name|gimp_seamless_clone_tool_button_press
parameter_list|(
name|GimpTool
modifier|*
name|tool
parameter_list|,
specifier|const
name|GimpCoords
modifier|*
name|coords
parameter_list|,
name|guint32
name|time
parameter_list|,
name|GdkModifierType
name|state
parameter_list|,
name|GimpButtonPressType
name|press_type
parameter_list|,
name|GimpDisplay
modifier|*
name|display
parameter_list|)
block|{
name|GimpSeamlessCloneTool
modifier|*
name|sc
init|=
name|GIMP_SEAMLESS_CLONE_TOOL
argument_list|(
name|tool
argument_list|)
decl_stmt|;
name|sc_debug_fstart
argument_list|()
expr_stmt|;
if|if
condition|(
name|display
operator|!=
name|tool
operator|->
name|display
condition|)
block|{
name|gimp_seamless_clone_tool_start
argument_list|(
name|sc
argument_list|,
name|display
argument_list|)
expr_stmt|;
name|sc
operator|->
name|xoff
operator|=
operator|(
name|gint
operator|)
name|coords
operator|->
name|x
operator|+
name|sc
operator|->
name|width
operator|/
literal|2
expr_stmt|;
name|sc
operator|->
name|yoff
operator|=
operator|(
name|gint
operator|)
name|coords
operator|->
name|y
operator|+
name|sc
operator|->
name|height
operator|/
literal|2
expr_stmt|;
block|}
if|if
condition|(
name|sc
operator|->
name|tool_state
operator|==
name|SC_STATE_RENDER_WAIT
operator|&&
name|gimp_seamless_clone_tool_is_in_paste_c
argument_list|(
name|sc
argument_list|,
name|coords
argument_list|)
condition|)
block|{
name|gimp_draw_tool_pause
argument_list|(
name|GIMP_DRAW_TOOL
argument_list|(
name|sc
argument_list|)
argument_list|)
expr_stmt|;
comment|/* Record previous location, in case the user cancel's the        * movement */
name|sc
operator|->
name|xoff_p
operator|=
name|sc
operator|->
name|xoff
expr_stmt|;
name|sc
operator|->
name|yoff_p
operator|=
name|sc
operator|->
name|yoff
expr_stmt|;
comment|/* Record the mouse location, so that the dragging offset can be        * calculated */
name|sc
operator|->
name|xclick
operator|=
name|coords
operator|->
name|x
expr_stmt|;
name|sc
operator|->
name|yclick
operator|=
name|coords
operator|->
name|y
expr_stmt|;
name|gimp_draw_tool_resume
argument_list|(
name|GIMP_DRAW_TOOL
argument_list|(
name|tool
argument_list|)
argument_list|)
expr_stmt|;
block|}
name|sc_debug_fend
argument_list|()
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_seamless_clone_tool_button_release (GimpTool * tool,const GimpCoords * coords,guint32 time,GdkModifierType state,GimpButtonReleaseType release_type,GimpDisplay * display)
name|gimp_seamless_clone_tool_button_release
parameter_list|(
name|GimpTool
modifier|*
name|tool
parameter_list|,
specifier|const
name|GimpCoords
modifier|*
name|coords
parameter_list|,
name|guint32
name|time
parameter_list|,
name|GdkModifierType
name|state
parameter_list|,
name|GimpButtonReleaseType
name|release_type
parameter_list|,
name|GimpDisplay
modifier|*
name|display
parameter_list|)
block|{
name|GimpSeamlessCloneTool
modifier|*
name|sc
init|=
name|GIMP_SEAMLESS_CLONE_TOOL
argument_list|(
name|tool
argument_list|)
decl_stmt|;
name|sc_debug_fstart
argument_list|()
expr_stmt|;
comment|/* There is nothing to do, unless we were actually moving a paste */
if|if
condition|(
name|sc
operator|->
name|tool_state
operator|==
name|SC_STATE_RENDER_MOTION
condition|)
block|{
name|gimp_draw_tool_pause
argument_list|(
name|GIMP_DRAW_TOOL
argument_list|(
name|sc
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|release_type
operator|==
name|GIMP_BUTTON_RELEASE_CANCEL
condition|)
block|{
name|sc
operator|->
name|xoff
operator|=
name|sc
operator|->
name|xoff_p
expr_stmt|;
name|sc
operator|->
name|yoff
operator|=
name|sc
operator|->
name|yoff_p
expr_stmt|;
block|}
else|else
block|{
name|sc
operator|->
name|xoff
operator|=
name|sc
operator|->
name|xoff_p
operator|+
call|(
name|gint
call|)
argument_list|(
name|coords
operator|->
name|x
operator|-
name|sc
operator|->
name|xclick
argument_list|)
expr_stmt|;
name|sc
operator|->
name|yoff
operator|=
name|sc
operator|->
name|yoff_p
operator|+
call|(
name|gint
call|)
argument_list|(
name|coords
operator|->
name|y
operator|-
name|sc
operator|->
name|yclick
argument_list|)
expr_stmt|;
block|}
name|gimp_draw_tool_resume
argument_list|(
name|GIMP_DRAW_TOOL
argument_list|(
name|tool
argument_list|)
argument_list|)
expr_stmt|;
block|}
name|sc_debug_fend
argument_list|()
expr_stmt|;
block|}
end_function

begin_comment
comment|/* Mouse cursor policy:  * - Always use the move cursor  * - While dragging the paste, use a move modified  * - Else, While hovering above it, display no modifier  * - Else, display a "bad" modifier  */
end_comment

begin_function
specifier|static
name|void
DECL|function|gimp_seamless_clone_tool_cursor_update (GimpTool * tool,const GimpCoords * coords,GdkModifierType state,GimpDisplay * display)
name|gimp_seamless_clone_tool_cursor_update
parameter_list|(
name|GimpTool
modifier|*
name|tool
parameter_list|,
specifier|const
name|GimpCoords
modifier|*
name|coords
parameter_list|,
name|GdkModifierType
name|state
parameter_list|,
name|GimpDisplay
modifier|*
name|display
parameter_list|)
block|{
name|GimpSeamlessCloneTool
modifier|*
name|sc
init|=
name|GIMP_SEAMLESS_CLONE_TOOL
argument_list|(
name|tool
argument_list|)
decl_stmt|;
name|GimpCursorModifier
name|modifier
init|=
name|GIMP_CURSOR_MODIFIER_BAD
decl_stmt|;
name|sc_debug_fstart
argument_list|()
expr_stmt|;
comment|/* Only update if the tool is actually active on some display */
if|if
condition|(
name|tool
operator|->
name|display
condition|)
block|{
if|if
condition|(
name|sc
operator|->
name|tool_state
operator|==
name|SC_STATE_RENDER_MOTION
condition|)
name|modifier
operator|=
name|GIMP_CURSOR_MODIFIER_MOVE
expr_stmt|;
elseif|else
if|if
condition|(
name|sc
operator|->
name|tool_state
operator|==
name|SC_STATE_RENDER_WAIT
operator|&&
name|gimp_seamless_clone_tool_is_in_paste_c
argument_list|(
name|sc
argument_list|,
name|coords
argument_list|)
condition|)
name|modifier
operator|=
name|GIMP_CURSOR_MODIFIER_NONE
expr_stmt|;
name|gimp_tool_control_set_cursor_modifier
argument_list|(
name|tool
operator|->
name|control
argument_list|,
name|modifier
argument_list|)
expr_stmt|;
block|}
name|GIMP_TOOL_CLASS
argument_list|(
name|parent_class
argument_list|)
operator|->
name|cursor_update
argument_list|(
name|tool
argument_list|,
name|coords
argument_list|,
name|state
argument_list|,
name|display
argument_list|)
expr_stmt|;
name|sc_debug_fend
argument_list|()
expr_stmt|;
block|}
end_function

begin_comment
comment|/* Draw any required on canvas interaction. For now, this is kept empty.  * It's a place holder for the future of this tool, for some more  * advanced features that may be added later */
end_comment

begin_function
specifier|static
name|void
DECL|function|gimp_seamless_clone_tool_draw (GimpDrawTool * draw_tool)
name|gimp_seamless_clone_tool_draw
parameter_list|(
name|GimpDrawTool
modifier|*
name|draw_tool
parameter_list|)
block|{
name|sc_debug_fstart
argument_list|()
expr_stmt|;
name|sc_debug_fend
argument_list|()
expr_stmt|;
block|}
end_function

begin_comment
comment|/**  * gimp_seamless_clone_tool_create_render_node:  * @sc: The GimpSeamlessCloneTool to intialize  *  * This function creates a Gegl node graph of the composition which is  * needed to render the drawable. The graph should have an "input" pad  * which will receive the drawable on which the preview is applied, and  * it should also have an "output" pad to which the final result will be  * rendered  */
end_comment

begin_function
specifier|static
name|void
DECL|function|gimp_seamless_clone_tool_create_render_node (GimpSeamlessCloneTool * sc)
name|gimp_seamless_clone_tool_create_render_node
parameter_list|(
name|GimpSeamlessCloneTool
modifier|*
name|sc
parameter_list|)
block|{
comment|/* Here is a textual description of the graph we are going to create:    *    *<input><- drawable    * +--+--------------------------+    * |  |output                    |    * |  |                          |    * |  |<buffer-source><- paste |    * |  |       |output            |    * |  |       |                  |    * |  |       |input             |    * |  |<translate>            |    * |  |       |output            |    * |  |       |                  |    * |  |input  |aux               |    * |<seamless-paste>             |    * |    |output                  |    * |    |                        |    * |    |input                   |    * +----+------------------------+    *<output>    */
name|GeglNode
modifier|*
name|node
decl_stmt|;
name|GeglNode
modifier|*
name|translate
decl_stmt|,
modifier|*
name|op
decl_stmt|,
modifier|*
name|paste
decl_stmt|;
name|GeglNode
modifier|*
name|input
decl_stmt|,
modifier|*
name|output
decl_stmt|;
name|sc_debug_fstart
argument_list|()
expr_stmt|;
name|node
operator|=
name|gegl_node_new
argument_list|()
expr_stmt|;
name|input
operator|=
name|gegl_node_get_input_proxy
argument_list|(
name|node
argument_list|,
literal|"input"
argument_list|)
expr_stmt|;
name|output
operator|=
name|gegl_node_get_output_proxy
argument_list|(
name|node
argument_list|,
literal|"output"
argument_list|)
expr_stmt|;
name|paste
operator|=
name|gegl_node_new_child
argument_list|(
name|node
argument_list|,
literal|"operation"
argument_list|,
literal|"gegl:buffer-source"
argument_list|,
literal|"buffer"
argument_list|,
name|sc
operator|->
name|paste
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|translate
operator|=
name|gegl_node_new_child
argument_list|(
name|node
argument_list|,
literal|"operation"
argument_list|,
literal|"gegl:translate"
argument_list|,
literal|"x"
argument_list|,
operator|(
name|gdouble
operator|)
name|sc
operator|->
name|xoff
argument_list|,
literal|"y"
argument_list|,
operator|(
name|gdouble
operator|)
name|sc
operator|->
name|yoff
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
comment|/* For now, avoid fancy stuff and use a nop passthrough op.    * Seamless-Clone operation would be integrated once the rest works.    * No need to introduce potential GEGL side bugs before we know the    * GIMP side works. */
name|op
operator|=
name|gegl_node_new_child
argument_list|(
name|node
argument_list|,
literal|"operation"
argument_list|,
literal|"gegl:over"
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|gegl_node_connect_to
argument_list|(
name|input
argument_list|,
literal|"output"
argument_list|,
name|op
argument_list|,
literal|"input"
argument_list|)
expr_stmt|;
name|gegl_node_connect_to
argument_list|(
name|paste
argument_list|,
literal|"output"
argument_list|,
name|translate
argument_list|,
literal|"input"
argument_list|)
expr_stmt|;
name|gegl_node_connect_to
argument_list|(
name|translate
argument_list|,
literal|"output"
argument_list|,
name|op
argument_list|,
literal|"aux"
argument_list|)
expr_stmt|;
name|gegl_node_connect_to
argument_list|(
name|op
argument_list|,
literal|"output"
argument_list|,
name|output
argument_list|,
literal|"input"
argument_list|)
expr_stmt|;
name|sc
operator|->
name|render_node
operator|=
name|node
expr_stmt|;
name|sc
operator|->
name|translate_node
operator|=
name|translate
expr_stmt|;
name|sc_debug_fend
argument_list|()
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_seamless_clone_tool_render_node_update (GimpSeamlessCloneTool * sc)
name|gimp_seamless_clone_tool_render_node_update
parameter_list|(
name|GimpSeamlessCloneTool
modifier|*
name|sc
parameter_list|)
block|{
name|sc_debug_fstart
argument_list|()
expr_stmt|;
comment|/* The only thing to update right now, is the location of the paste */
name|gegl_node_set
argument_list|(
name|sc
operator|->
name|translate_node
argument_list|,
literal|"x"
argument_list|,
operator|(
name|gdouble
operator|)
name|sc
operator|->
name|xoff
argument_list|,
literal|"y"
argument_list|,
operator|(
name|gdouble
operator|)
name|sc
operator|->
name|yoff
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|sc_debug_fend
argument_list|()
expr_stmt|;
block|}
end_function

begin_comment
comment|/* Create an image map to render the operation of the current tool with  * a preview on the given drawable */
end_comment

begin_function
specifier|static
name|void
DECL|function|gimp_seamless_clone_tool_create_image_map (GimpSeamlessCloneTool * sc,GimpDrawable * drawable)
name|gimp_seamless_clone_tool_create_image_map
parameter_list|(
name|GimpSeamlessCloneTool
modifier|*
name|sc
parameter_list|,
name|GimpDrawable
modifier|*
name|drawable
parameter_list|)
block|{
name|sc_debug_fstart
argument_list|()
expr_stmt|;
comment|/* FIrst, make sure we actually have the GEGL graph needed to render    * the operation's result */
if|if
condition|(
operator|!
name|sc
operator|->
name|render_node
condition|)
name|gimp_seamless_clone_tool_create_render_node
argument_list|(
name|sc
argument_list|)
expr_stmt|;
name|sc
operator|->
name|image_map
operator|=
name|gimp_image_map_new
argument_list|(
name|drawable
argument_list|,
name|_
argument_list|(
literal|"Seamless Clone"
argument_list|)
argument_list|,
name|sc
operator|->
name|render_node
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_signal_connect
argument_list|(
name|sc
operator|->
name|image_map
argument_list|,
literal|"flush"
argument_list|,
name|G_CALLBACK
argument_list|(
name|gimp_seamless_clone_tool_image_map_flush
argument_list|)
argument_list|,
name|sc
argument_list|)
expr_stmt|;
name|sc_debug_fend
argument_list|()
expr_stmt|;
block|}
end_function

begin_comment
comment|/* Flush (Refresh) the image map preview */
end_comment

begin_function
specifier|static
name|void
DECL|function|gimp_seamless_clone_tool_image_map_flush (GimpImageMap * image_map,GimpTool * tool)
name|gimp_seamless_clone_tool_image_map_flush
parameter_list|(
name|GimpImageMap
modifier|*
name|image_map
parameter_list|,
name|GimpTool
modifier|*
name|tool
parameter_list|)
block|{
name|GimpImage
modifier|*
name|image
init|=
name|gimp_display_get_image
argument_list|(
name|tool
operator|->
name|display
argument_list|)
decl_stmt|;
name|sc_debug_fstart
argument_list|()
expr_stmt|;
name|gimp_projection_flush_now
argument_list|(
name|gimp_image_get_projection
argument_list|(
name|image
argument_list|)
argument_list|)
expr_stmt|;
name|gimp_display_flush_now
argument_list|(
name|tool
operator|->
name|display
argument_list|)
expr_stmt|;
name|sc_debug_fend
argument_list|()
expr_stmt|;
block|}
end_function

begin_comment
comment|/**  * gimp_seamless_clone_tool_image_map_update:  * @sc: A GimpSeamlessCloneTool to update  *  * This functions updates the image map preview displayed by a given  * GimpSeamlessCloneTool. The image_map must be initialized prior to the  * call to this function!  */
end_comment

begin_function
specifier|static
name|void
DECL|function|gimp_seamless_clone_tool_image_map_update (GimpSeamlessCloneTool * sc)
name|gimp_seamless_clone_tool_image_map_update
parameter_list|(
name|GimpSeamlessCloneTool
modifier|*
name|sc
parameter_list|)
block|{
name|GimpTool
modifier|*
name|tool
init|=
name|GIMP_TOOL
argument_list|(
name|sc
argument_list|)
decl_stmt|;
name|GimpDisplayShell
modifier|*
name|shell
init|=
name|gimp_display_get_shell
argument_list|(
name|tool
operator|->
name|display
argument_list|)
decl_stmt|;
name|GimpItem
modifier|*
name|item
init|=
name|GIMP_ITEM
argument_list|(
name|tool
operator|->
name|drawable
argument_list|)
decl_stmt|;
name|gint
name|x
decl_stmt|,
name|y
decl_stmt|;
name|gint
name|w
decl_stmt|,
name|h
decl_stmt|;
name|gint
name|off_x
decl_stmt|,
name|off_y
decl_stmt|;
name|GeglRectangle
name|visible
decl_stmt|;
name|sc_debug_fstart
argument_list|()
expr_stmt|;
comment|/* Find out at which x,y is the top left corner of the currently    * displayed part */
name|gimp_display_shell_untransform_viewport
argument_list|(
name|shell
argument_list|,
operator|&
name|x
argument_list|,
operator|&
name|y
argument_list|,
operator|&
name|w
argument_list|,
operator|&
name|h
argument_list|)
expr_stmt|;
comment|/* Find out where is our drawable positioned */
name|gimp_item_get_offset
argument_list|(
name|item
argument_list|,
operator|&
name|off_x
argument_list|,
operator|&
name|off_y
argument_list|)
expr_stmt|;
comment|/* Create a rectangle from the intersection of the currently displayed    * part with the drawable */
name|gimp_rectangle_intersect
argument_list|(
name|x
argument_list|,
name|y
argument_list|,
name|w
argument_list|,
name|h
argument_list|,
name|off_x
argument_list|,
name|off_y
argument_list|,
name|gimp_item_get_width
argument_list|(
name|item
argument_list|)
argument_list|,
name|gimp_item_get_height
argument_list|(
name|item
argument_list|)
argument_list|,
operator|&
name|visible
operator|.
name|x
argument_list|,
operator|&
name|visible
operator|.
name|y
argument_list|,
operator|&
name|visible
operator|.
name|width
argument_list|,
operator|&
name|visible
operator|.
name|height
argument_list|)
expr_stmt|;
comment|/* Since the image_map_apply function receives a rectangle describing    * where it should update the preview, and since that rectangle should    * be relative to the drawable's location, we now offset back by the    * drawable's offsetts. */
name|visible
operator|.
name|x
operator|-=
name|off_x
expr_stmt|;
name|visible
operator|.
name|y
operator|-=
name|off_y
expr_stmt|;
comment|/* Now update the image map and show this area */
name|gimp_image_map_apply
argument_list|(
name|sc
operator|->
name|image_map
argument_list|,
operator|&
name|visible
argument_list|)
expr_stmt|;
name|sc_debug_fend
argument_list|()
expr_stmt|;
block|}
end_function

end_unit

