begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* The GIMP -- an image manipulation program  * Copyright (C) 1995 Spencer Kimball and Peter Mattis  *  * This program is free software; you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 2 of the License, or  * (at your option) any later version.  *  * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *  * You should have received a copy of the GNU General Public License  * along with this program; if not, write to the Free Software  * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  */
end_comment

begin_include
include|#
directive|include
file|"config.h"
end_include

begin_include
include|#
directive|include
file|<gtk/gtk.h>
end_include

begin_include
include|#
directive|include
file|"libgimpcolor/gimpcolor.h"
end_include

begin_include
include|#
directive|include
file|"libgimpmath/gimpmath.h"
end_include

begin_include
include|#
directive|include
file|"libgimpwidgets/gimpwidgets.h"
end_include

begin_include
include|#
directive|include
file|"tools-types.h"
end_include

begin_include
include|#
directive|include
file|"base/hue-saturation.h"
end_include

begin_include
include|#
directive|include
file|"core/gimpdrawable.h"
end_include

begin_include
include|#
directive|include
file|"core/gimpimage.h"
end_include

begin_include
include|#
directive|include
file|"core/gimpimagemap.h"
end_include

begin_include
include|#
directive|include
file|"widgets/gimphelp-ids.h"
end_include

begin_include
include|#
directive|include
file|"display/gimpdisplay.h"
end_include

begin_include
include|#
directive|include
file|"gimphuesaturationtool.h"
end_include

begin_include
include|#
directive|include
file|"gimpimagemapoptions.h"
end_include

begin_include
include|#
directive|include
file|"gimp-intl.h"
end_include

begin_define
DECL|macro|SLIDER_WIDTH
define|#
directive|define
name|SLIDER_WIDTH
value|200
end_define

begin_define
DECL|macro|DA_WIDTH
define|#
directive|define
name|DA_WIDTH
value|40
end_define

begin_define
DECL|macro|DA_HEIGHT
define|#
directive|define
name|DA_HEIGHT
value|20
end_define

begin_define
DECL|macro|HUE_SLIDER
define|#
directive|define
name|HUE_SLIDER
value|(1<< 0)
end_define

begin_define
DECL|macro|LIGHTNESS_SLIDER
define|#
directive|define
name|LIGHTNESS_SLIDER
value|(1<< 1)
end_define

begin_define
DECL|macro|SATURATION_SLIDER
define|#
directive|define
name|SATURATION_SLIDER
value|(1<< 2)
end_define

begin_define
DECL|macro|DRAW
define|#
directive|define
name|DRAW
value|(1<< 3)
end_define

begin_define
DECL|macro|OVERLAP_SLIDER
define|#
directive|define
name|OVERLAP_SLIDER
value|(1<< 4)
end_define

begin_define
DECL|macro|SLIDERS
define|#
directive|define
name|SLIDERS
value|(HUE_SLIDER        | \                             LIGHTNESS_SLIDER  | \                             SATURATION_SLIDER | \                             OVERLAP_SLIDER)
end_define

begin_define
DECL|macro|ALL
define|#
directive|define
name|ALL
value|(SLIDERS | DRAW)
end_define

begin_comment
comment|/*  local function prototypes  */
end_comment

begin_function_decl
specifier|static
name|void
name|gimp_hue_saturation_tool_class_init
parameter_list|(
name|GimpHueSaturationToolClass
modifier|*
name|klass
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_hue_saturation_tool_init
parameter_list|(
name|GimpHueSaturationTool
modifier|*
name|tool
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_hue_saturation_tool_finalize
parameter_list|(
name|GObject
modifier|*
name|object
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|gboolean
name|gimp_hue_saturation_tool_initialize
parameter_list|(
name|GimpTool
modifier|*
name|tool
parameter_list|,
name|GimpDisplay
modifier|*
name|gdisp
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_hue_saturation_tool_map
parameter_list|(
name|GimpImageMapTool
modifier|*
name|image_map_tool
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_hue_saturation_tool_dialog
parameter_list|(
name|GimpImageMapTool
modifier|*
name|image_map_tool
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_hue_saturation_tool_reset
parameter_list|(
name|GimpImageMapTool
modifier|*
name|image_map_tool
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|hue_saturation_update
parameter_list|(
name|GimpHueSaturationTool
modifier|*
name|hs_tool
parameter_list|,
name|gint
name|update
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|hue_saturation_partition_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|hue_saturation_partition_reset_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|hue_saturation_hue_adjustment_update
parameter_list|(
name|GtkAdjustment
modifier|*
name|adj
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|hue_saturation_lightness_adjustment_update
parameter_list|(
name|GtkAdjustment
modifier|*
name|adj
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|hue_saturation_saturation_adjustment_update
parameter_list|(
name|GtkAdjustment
modifier|*
name|adj
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|hue_saturation_overlap_adjustment_update
parameter_list|(
name|GtkAdjustment
modifier|*
name|adj
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_comment
comment|/*  private variables  */
end_comment

begin_decl_stmt
DECL|variable|default_colors
specifier|static
name|gint
name|default_colors
index|[
literal|6
index|]
index|[
literal|3
index|]
init|=
block|{
block|{
literal|255
block|,
literal|0
block|,
literal|0
block|}
block|,
block|{
literal|255
block|,
literal|255
block|,
literal|0
block|}
block|,
block|{
literal|0
block|,
literal|255
block|,
literal|0
block|}
block|,
block|{
literal|0
block|,
literal|255
block|,
literal|255
block|}
block|,
block|{
literal|0
block|,
literal|0
block|,
literal|255
block|}
block|,
block|{
literal|255
block|,
literal|0
block|,
literal|255
block|}
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|parent_class
specifier|static
name|GimpImageMapToolClass
modifier|*
name|parent_class
init|=
name|NULL
decl_stmt|;
end_decl_stmt

begin_comment
comment|/*  public functions  */
end_comment

begin_function
name|void
DECL|function|gimp_hue_saturation_tool_register (GimpToolRegisterCallback callback,gpointer data)
name|gimp_hue_saturation_tool_register
parameter_list|(
name|GimpToolRegisterCallback
name|callback
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
call|(
modifier|*
name|callback
call|)
argument_list|(
name|GIMP_TYPE_HUE_SATURATION_TOOL
argument_list|,
name|GIMP_TYPE_IMAGE_MAP_OPTIONS
argument_list|,
name|NULL
argument_list|,
literal|0
argument_list|,
literal|"gimp-hue-saturation-tool"
argument_list|,
name|_
argument_list|(
literal|"Hue-Saturation"
argument_list|)
argument_list|,
name|_
argument_list|(
literal|"Adjust hue and saturation"
argument_list|)
argument_list|,
name|N_
argument_list|(
literal|"Hue-_Saturation..."
argument_list|)
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|,
name|GIMP_HELP_TOOL_HUE_SATURATION
argument_list|,
name|GIMP_STOCK_TOOL_HUE_SATURATION
argument_list|,
name|data
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|GType
DECL|function|gimp_hue_saturation_tool_get_type (void)
name|gimp_hue_saturation_tool_get_type
parameter_list|(
name|void
parameter_list|)
block|{
specifier|static
name|GType
name|tool_type
init|=
literal|0
decl_stmt|;
if|if
condition|(
operator|!
name|tool_type
condition|)
block|{
specifier|static
specifier|const
name|GTypeInfo
name|tool_info
init|=
block|{
sizeof|sizeof
argument_list|(
name|GimpHueSaturationToolClass
argument_list|)
block|,
operator|(
name|GBaseInitFunc
operator|)
name|NULL
block|,
operator|(
name|GBaseFinalizeFunc
operator|)
name|NULL
block|,
operator|(
name|GClassInitFunc
operator|)
name|gimp_hue_saturation_tool_class_init
block|,
name|NULL
block|,
comment|/* class_finalize */
name|NULL
block|,
comment|/* class_data     */
sizeof|sizeof
argument_list|(
name|GimpHueSaturationTool
argument_list|)
block|,
literal|0
block|,
comment|/* n_preallocs    */
operator|(
name|GInstanceInitFunc
operator|)
name|gimp_hue_saturation_tool_init
block|,       }
decl_stmt|;
name|tool_type
operator|=
name|g_type_register_static
argument_list|(
name|GIMP_TYPE_IMAGE_MAP_TOOL
argument_list|,
literal|"GimpHueSaturationTool"
argument_list|,
operator|&
name|tool_info
argument_list|,
literal|0
argument_list|)
expr_stmt|;
block|}
return|return
name|tool_type
return|;
block|}
end_function

begin_comment
comment|/*  private functions  */
end_comment

begin_function
specifier|static
name|void
DECL|function|gimp_hue_saturation_tool_class_init (GimpHueSaturationToolClass * klass)
name|gimp_hue_saturation_tool_class_init
parameter_list|(
name|GimpHueSaturationToolClass
modifier|*
name|klass
parameter_list|)
block|{
name|GObjectClass
modifier|*
name|object_class
decl_stmt|;
name|GimpToolClass
modifier|*
name|tool_class
decl_stmt|;
name|GimpImageMapToolClass
modifier|*
name|image_map_tool_class
decl_stmt|;
name|object_class
operator|=
name|G_OBJECT_CLASS
argument_list|(
name|klass
argument_list|)
expr_stmt|;
name|tool_class
operator|=
name|GIMP_TOOL_CLASS
argument_list|(
name|klass
argument_list|)
expr_stmt|;
name|image_map_tool_class
operator|=
name|GIMP_IMAGE_MAP_TOOL_CLASS
argument_list|(
name|klass
argument_list|)
expr_stmt|;
name|parent_class
operator|=
name|g_type_class_peek_parent
argument_list|(
name|klass
argument_list|)
expr_stmt|;
name|object_class
operator|->
name|finalize
operator|=
name|gimp_hue_saturation_tool_finalize
expr_stmt|;
name|tool_class
operator|->
name|initialize
operator|=
name|gimp_hue_saturation_tool_initialize
expr_stmt|;
name|image_map_tool_class
operator|->
name|shell_desc
operator|=
name|_
argument_list|(
literal|"Adjust hue / lightness / saturation"
argument_list|)
expr_stmt|;
name|image_map_tool_class
operator|->
name|map
operator|=
name|gimp_hue_saturation_tool_map
expr_stmt|;
name|image_map_tool_class
operator|->
name|dialog
operator|=
name|gimp_hue_saturation_tool_dialog
expr_stmt|;
name|image_map_tool_class
operator|->
name|reset
operator|=
name|gimp_hue_saturation_tool_reset
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_hue_saturation_tool_init (GimpHueSaturationTool * hs_tool)
name|gimp_hue_saturation_tool_init
parameter_list|(
name|GimpHueSaturationTool
modifier|*
name|hs_tool
parameter_list|)
block|{
name|hs_tool
operator|->
name|hue_saturation
operator|=
name|g_new0
argument_list|(
name|HueSaturation
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|hs_tool
operator|->
name|hue_partition
operator|=
name|GIMP_ALL_HUES
expr_stmt|;
name|hue_saturation_init
argument_list|(
name|hs_tool
operator|->
name|hue_saturation
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_hue_saturation_tool_finalize (GObject * object)
name|gimp_hue_saturation_tool_finalize
parameter_list|(
name|GObject
modifier|*
name|object
parameter_list|)
block|{
name|GimpHueSaturationTool
modifier|*
name|hs_tool
init|=
name|GIMP_HUE_SATURATION_TOOL
argument_list|(
name|object
argument_list|)
decl_stmt|;
if|if
condition|(
name|hs_tool
operator|->
name|hue_saturation
condition|)
block|{
name|g_free
argument_list|(
name|hs_tool
operator|->
name|hue_saturation
argument_list|)
expr_stmt|;
name|hs_tool
operator|->
name|hue_saturation
operator|=
name|NULL
expr_stmt|;
block|}
name|G_OBJECT_CLASS
argument_list|(
name|parent_class
argument_list|)
operator|->
name|finalize
argument_list|(
name|object
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|gboolean
DECL|function|gimp_hue_saturation_tool_initialize (GimpTool * tool,GimpDisplay * gdisp)
name|gimp_hue_saturation_tool_initialize
parameter_list|(
name|GimpTool
modifier|*
name|tool
parameter_list|,
name|GimpDisplay
modifier|*
name|gdisp
parameter_list|)
block|{
name|GimpHueSaturationTool
modifier|*
name|hs_tool
init|=
name|GIMP_HUE_SATURATION_TOOL
argument_list|(
name|tool
argument_list|)
decl_stmt|;
name|GimpDrawable
modifier|*
name|drawable
decl_stmt|;
name|drawable
operator|=
name|gimp_image_active_drawable
argument_list|(
name|gdisp
operator|->
name|gimage
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|drawable
condition|)
return|return
name|FALSE
return|;
if|if
condition|(
operator|!
name|gimp_drawable_is_rgb
argument_list|(
name|drawable
argument_list|)
condition|)
block|{
name|g_message
argument_list|(
name|_
argument_list|(
literal|"Hue-Saturation operates only on RGB color layers."
argument_list|)
argument_list|)
expr_stmt|;
return|return
name|FALSE
return|;
block|}
name|hue_saturation_init
argument_list|(
name|hs_tool
operator|->
name|hue_saturation
argument_list|)
expr_stmt|;
name|GIMP_TOOL_CLASS
argument_list|(
name|parent_class
argument_list|)
operator|->
name|initialize
argument_list|(
name|tool
argument_list|,
name|gdisp
argument_list|)
expr_stmt|;
name|hue_saturation_update
argument_list|(
name|hs_tool
argument_list|,
name|ALL
argument_list|)
expr_stmt|;
return|return
name|TRUE
return|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_hue_saturation_tool_map (GimpImageMapTool * image_map_tool)
name|gimp_hue_saturation_tool_map
parameter_list|(
name|GimpImageMapTool
modifier|*
name|image_map_tool
parameter_list|)
block|{
name|GimpHueSaturationTool
modifier|*
name|hs_tool
init|=
name|GIMP_HUE_SATURATION_TOOL
argument_list|(
name|image_map_tool
argument_list|)
decl_stmt|;
name|gimp_image_map_apply
argument_list|(
name|image_map_tool
operator|->
name|image_map
argument_list|,
operator|(
name|GimpImageMapApplyFunc
operator|)
name|hue_saturation
argument_list|,
name|hs_tool
operator|->
name|hue_saturation
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/***************************/
end_comment

begin_comment
comment|/*  Hue-Saturation dialog  */
end_comment

begin_comment
comment|/***************************/
end_comment

begin_function
specifier|static
name|void
DECL|function|gimp_hue_saturation_tool_dialog (GimpImageMapTool * image_map_tool)
name|gimp_hue_saturation_tool_dialog
parameter_list|(
name|GimpImageMapTool
modifier|*
name|image_map_tool
parameter_list|)
block|{
name|GimpHueSaturationTool
modifier|*
name|hs_tool
init|=
name|GIMP_HUE_SATURATION_TOOL
argument_list|(
name|image_map_tool
argument_list|)
decl_stmt|;
name|GtkWidget
modifier|*
name|vbox
decl_stmt|;
name|GtkWidget
modifier|*
name|abox
decl_stmt|;
name|GtkWidget
modifier|*
name|table
decl_stmt|;
name|GtkWidget
modifier|*
name|slider
decl_stmt|;
name|GtkWidget
modifier|*
name|button
decl_stmt|;
name|GtkWidget
modifier|*
name|frame
decl_stmt|;
name|GtkWidget
modifier|*
name|hbox
decl_stmt|;
name|GtkObject
modifier|*
name|data
decl_stmt|;
name|GtkSizeGroup
modifier|*
name|label_group
decl_stmt|;
name|GtkSizeGroup
modifier|*
name|spinner_group
decl_stmt|;
name|GSList
modifier|*
name|group
init|=
name|NULL
decl_stmt|;
name|gint
name|i
decl_stmt|;
specifier|const
struct|struct
DECL|struct|__anon27dfb4b00108
block|{
DECL|member|label
specifier|const
name|gchar
modifier|*
name|label
decl_stmt|;
DECL|member|label_col
name|gint
name|label_col
decl_stmt|;
DECL|member|label_row
name|gint
name|label_row
decl_stmt|;
DECL|member|frame_col
name|gint
name|frame_col
decl_stmt|;
DECL|member|frame_row
name|gint
name|frame_row
decl_stmt|;
block|}
name|hue_partition_table
index|[]
init|=
block|{
block|{
name|N_
argument_list|(
literal|"M_aster"
argument_list|)
block|,
literal|2
block|,
literal|3
block|,
literal|0
block|,
literal|0
block|}
block|,
block|{
name|N_
argument_list|(
literal|"_R"
argument_list|)
block|,
literal|2
block|,
literal|1
block|,
literal|2
block|,
literal|0
block|}
block|,
block|{
name|N_
argument_list|(
literal|"_Y"
argument_list|)
block|,
literal|1
block|,
literal|2
block|,
literal|0
block|,
literal|2
block|}
block|,
block|{
name|N_
argument_list|(
literal|"_G"
argument_list|)
block|,
literal|1
block|,
literal|4
block|,
literal|0
block|,
literal|4
block|}
block|,
block|{
name|N_
argument_list|(
literal|"_C"
argument_list|)
block|,
literal|2
block|,
literal|5
block|,
literal|2
block|,
literal|6
block|}
block|,
block|{
name|N_
argument_list|(
literal|"_B"
argument_list|)
block|,
literal|3
block|,
literal|4
block|,
literal|4
block|,
literal|4
block|}
block|,
block|{
name|N_
argument_list|(
literal|"_M"
argument_list|)
block|,
literal|3
block|,
literal|2
block|,
literal|4
block|,
literal|2
block|}
block|}
struct|;
name|frame
operator|=
name|gimp_frame_new
argument_list|(
name|_
argument_list|(
literal|"Select Primary Color to Modify"
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|image_map_tool
operator|->
name|main_vbox
argument_list|)
argument_list|,
name|frame
argument_list|,
name|TRUE
argument_list|,
name|TRUE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|frame
argument_list|)
expr_stmt|;
name|vbox
operator|=
name|gtk_vbox_new
argument_list|(
name|FALSE
argument_list|,
literal|6
argument_list|)
expr_stmt|;
name|gtk_container_add
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|frame
argument_list|)
argument_list|,
name|vbox
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|vbox
argument_list|)
expr_stmt|;
name|abox
operator|=
name|gtk_alignment_new
argument_list|(
literal|0.5
argument_list|,
literal|0.5
argument_list|,
literal|0.0
argument_list|,
literal|0.0
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|vbox
argument_list|)
argument_list|,
name|abox
argument_list|,
name|TRUE
argument_list|,
name|TRUE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|abox
argument_list|)
expr_stmt|;
comment|/*  The table containing hue partitions  */
name|table
operator|=
name|gtk_table_new
argument_list|(
literal|7
argument_list|,
literal|5
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gtk_table_set_col_spacing
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|0
argument_list|,
literal|4
argument_list|)
expr_stmt|;
name|gtk_table_set_col_spacing
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|3
argument_list|,
literal|4
argument_list|)
expr_stmt|;
name|gtk_table_set_row_spacing
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|0
argument_list|,
literal|2
argument_list|)
expr_stmt|;
name|gtk_table_set_row_spacing
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|5
argument_list|,
literal|2
argument_list|)
expr_stmt|;
name|gtk_container_add
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|abox
argument_list|)
argument_list|,
name|table
argument_list|)
expr_stmt|;
comment|/*  the radio buttons for hue partitions  */
for|for
control|(
name|i
operator|=
literal|0
init|;
name|i
operator|<
literal|7
condition|;
name|i
operator|++
control|)
block|{
name|button
operator|=
name|gtk_radio_button_new_with_mnemonic
argument_list|(
name|group
argument_list|,
name|gettext
argument_list|(
name|hue_partition_table
index|[
name|i
index|]
operator|.
name|label
argument_list|)
argument_list|)
expr_stmt|;
name|group
operator|=
name|gtk_radio_button_get_group
argument_list|(
name|GTK_RADIO_BUTTON
argument_list|(
name|button
argument_list|)
argument_list|)
expr_stmt|;
name|g_object_set_data
argument_list|(
name|G_OBJECT
argument_list|(
name|button
argument_list|)
argument_list|,
literal|"hue_partition"
argument_list|,
name|GINT_TO_POINTER
argument_list|(
name|i
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|i
operator|==
literal|0
condition|)
block|{
name|gtk_toggle_button_set_mode
argument_list|(
name|GTK_TOGGLE_BUTTON
argument_list|(
name|button
argument_list|)
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gimp_help_set_help_data
argument_list|(
name|button
argument_list|,
name|_
argument_list|(
literal|"Modify all colors"
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
block|}
name|gtk_table_attach
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
name|button
argument_list|,
name|hue_partition_table
index|[
name|i
index|]
operator|.
name|label_col
argument_list|,
name|hue_partition_table
index|[
name|i
index|]
operator|.
name|label_col
operator|+
literal|1
argument_list|,
name|hue_partition_table
index|[
name|i
index|]
operator|.
name|label_row
argument_list|,
name|hue_partition_table
index|[
name|i
index|]
operator|.
name|label_row
operator|+
literal|1
argument_list|,
name|GTK_SHRINK
operator||
name|GTK_FILL
argument_list|,
name|GTK_SHRINK
operator||
name|GTK_FILL
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|)
expr_stmt|;
if|if
condition|(
name|i
operator|>
literal|0
condition|)
block|{
name|GimpRGB
name|color
init|=
block|{
literal|0.0
block|}
decl_stmt|;
name|frame
operator|=
name|gtk_frame_new
argument_list|(
name|NULL
argument_list|)
expr_stmt|;
name|gtk_frame_set_shadow_type
argument_list|(
name|GTK_FRAME
argument_list|(
name|frame
argument_list|)
argument_list|,
name|GTK_SHADOW_IN
argument_list|)
expr_stmt|;
name|gtk_table_attach
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
name|frame
argument_list|,
name|hue_partition_table
index|[
name|i
index|]
operator|.
name|frame_col
argument_list|,
name|hue_partition_table
index|[
name|i
index|]
operator|.
name|frame_col
operator|+
literal|1
argument_list|,
name|hue_partition_table
index|[
name|i
index|]
operator|.
name|frame_row
argument_list|,
name|hue_partition_table
index|[
name|i
index|]
operator|.
name|frame_row
operator|+
literal|1
argument_list|,
name|GTK_SHRINK
operator||
name|GTK_FILL
argument_list|,
name|GTK_SHRINK
operator||
name|GTK_FILL
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|frame
argument_list|)
expr_stmt|;
name|hs_tool
operator|->
name|hue_partition_da
index|[
name|i
operator|-
literal|1
index|]
operator|=
name|gimp_color_area_new
argument_list|(
operator|&
name|color
argument_list|,
name|GIMP_COLOR_AREA_FLAT
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_set_size_request
argument_list|(
name|hs_tool
operator|->
name|hue_partition_da
index|[
name|i
operator|-
literal|1
index|]
argument_list|,
name|DA_WIDTH
argument_list|,
name|DA_HEIGHT
argument_list|)
expr_stmt|;
name|gtk_container_add
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|frame
argument_list|)
argument_list|,
name|hs_tool
operator|->
name|hue_partition_da
index|[
name|i
operator|-
literal|1
index|]
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|hs_tool
operator|->
name|hue_partition_da
index|[
name|i
operator|-
literal|1
index|]
argument_list|)
expr_stmt|;
block|}
name|g_signal_connect
argument_list|(
name|button
argument_list|,
literal|"toggled"
argument_list|,
name|G_CALLBACK
argument_list|(
name|hue_saturation_partition_callback
argument_list|)
argument_list|,
name|hs_tool
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|button
argument_list|)
expr_stmt|;
block|}
name|gtk_widget_show
argument_list|(
name|table
argument_list|)
expr_stmt|;
name|label_group
operator|=
name|gtk_size_group_new
argument_list|(
name|GTK_SIZE_GROUP_HORIZONTAL
argument_list|)
expr_stmt|;
name|spinner_group
operator|=
name|gtk_size_group_new
argument_list|(
name|GTK_SIZE_GROUP_HORIZONTAL
argument_list|)
expr_stmt|;
comment|/* Create the 'Overlap' option slider */
name|table
operator|=
name|gtk_table_new
argument_list|(
literal|3
argument_list|,
literal|1
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gtk_table_set_col_spacings
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|4
argument_list|)
expr_stmt|;
name|gtk_table_set_row_spacings
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|2
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|vbox
argument_list|)
argument_list|,
name|table
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|table
argument_list|)
expr_stmt|;
name|data
operator|=
name|gimp_scale_entry_new
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
name|_
argument_list|(
literal|"_Overlap:"
argument_list|)
argument_list|,
name|SLIDER_WIDTH
argument_list|,
operator|-
literal|1
argument_list|,
literal|0.0
argument_list|,
literal|0
argument_list|,
literal|100.0
argument_list|,
literal|1.0
argument_list|,
literal|15.0
argument_list|,
literal|0
argument_list|,
name|TRUE
argument_list|,
literal|0.0
argument_list|,
literal|0.0
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|hs_tool
operator|->
name|overlap_data
operator|=
name|GTK_ADJUSTMENT
argument_list|(
name|data
argument_list|)
expr_stmt|;
name|gtk_size_group_add_widget
argument_list|(
name|label_group
argument_list|,
name|GIMP_SCALE_ENTRY_LABEL
argument_list|(
name|data
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_size_group_add_widget
argument_list|(
name|spinner_group
argument_list|,
name|GIMP_SCALE_ENTRY_SPINBUTTON
argument_list|(
name|data
argument_list|)
argument_list|)
expr_stmt|;
name|g_object_unref
argument_list|(
name|label_group
argument_list|)
expr_stmt|;
name|g_object_unref
argument_list|(
name|spinner_group
argument_list|)
expr_stmt|;
name|slider
operator|=
name|GIMP_SCALE_ENTRY_SCALE
argument_list|(
name|data
argument_list|)
expr_stmt|;
name|gtk_range_set_update_policy
argument_list|(
name|GTK_RANGE
argument_list|(
name|slider
argument_list|)
argument_list|,
name|GTK_UPDATE_DELAYED
argument_list|)
expr_stmt|;
name|g_signal_connect
argument_list|(
name|data
argument_list|,
literal|"value_changed"
argument_list|,
name|G_CALLBACK
argument_list|(
name|hue_saturation_overlap_adjustment_update
argument_list|)
argument_list|,
name|hs_tool
argument_list|)
expr_stmt|;
name|frame
operator|=
name|gimp_frame_new
argument_list|(
name|_
argument_list|(
literal|"Modify Selected Color"
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|image_map_tool
operator|->
name|main_vbox
argument_list|)
argument_list|,
name|frame
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|frame
argument_list|)
expr_stmt|;
comment|/*  The table containing sliders  */
name|vbox
operator|=
name|gtk_vbox_new
argument_list|(
name|FALSE
argument_list|,
literal|4
argument_list|)
expr_stmt|;
name|gtk_container_add
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|frame
argument_list|)
argument_list|,
name|vbox
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|vbox
argument_list|)
expr_stmt|;
name|table
operator|=
name|gtk_table_new
argument_list|(
literal|3
argument_list|,
literal|3
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gtk_table_set_col_spacings
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|4
argument_list|)
expr_stmt|;
name|gtk_table_set_row_spacings
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|2
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|vbox
argument_list|)
argument_list|,
name|table
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|table
argument_list|)
expr_stmt|;
comment|/*  Create the hue scale widget  */
name|data
operator|=
name|gimp_scale_entry_new
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
name|_
argument_list|(
literal|"_Hue:"
argument_list|)
argument_list|,
name|SLIDER_WIDTH
argument_list|,
operator|-
literal|1
argument_list|,
literal|0.0
argument_list|,
operator|-
literal|180.0
argument_list|,
literal|180.0
argument_list|,
literal|1.0
argument_list|,
literal|15.0
argument_list|,
literal|0
argument_list|,
name|TRUE
argument_list|,
literal|0.0
argument_list|,
literal|0.0
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|hs_tool
operator|->
name|hue_data
operator|=
name|GTK_ADJUSTMENT
argument_list|(
name|data
argument_list|)
expr_stmt|;
name|gtk_size_group_add_widget
argument_list|(
name|label_group
argument_list|,
name|GIMP_SCALE_ENTRY_LABEL
argument_list|(
name|data
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_size_group_add_widget
argument_list|(
name|spinner_group
argument_list|,
name|GIMP_SCALE_ENTRY_SPINBUTTON
argument_list|(
name|data
argument_list|)
argument_list|)
expr_stmt|;
name|slider
operator|=
name|GIMP_SCALE_ENTRY_SCALE
argument_list|(
name|data
argument_list|)
expr_stmt|;
name|gtk_range_set_update_policy
argument_list|(
name|GTK_RANGE
argument_list|(
name|slider
argument_list|)
argument_list|,
name|GTK_UPDATE_DELAYED
argument_list|)
expr_stmt|;
name|g_signal_connect
argument_list|(
name|data
argument_list|,
literal|"value_changed"
argument_list|,
name|G_CALLBACK
argument_list|(
name|hue_saturation_hue_adjustment_update
argument_list|)
argument_list|,
name|hs_tool
argument_list|)
expr_stmt|;
comment|/*  Create the lightness scale widget  */
name|data
operator|=
name|gimp_scale_entry_new
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|0
argument_list|,
literal|1
argument_list|,
name|_
argument_list|(
literal|"_Lightness:"
argument_list|)
argument_list|,
name|SLIDER_WIDTH
argument_list|,
operator|-
literal|1
argument_list|,
literal|0.0
argument_list|,
operator|-
literal|100.0
argument_list|,
literal|100.0
argument_list|,
literal|1.0
argument_list|,
literal|10.0
argument_list|,
literal|0
argument_list|,
name|TRUE
argument_list|,
literal|0.0
argument_list|,
literal|0.0
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|hs_tool
operator|->
name|lightness_data
operator|=
name|GTK_ADJUSTMENT
argument_list|(
name|data
argument_list|)
expr_stmt|;
name|gtk_size_group_add_widget
argument_list|(
name|label_group
argument_list|,
name|GIMP_SCALE_ENTRY_LABEL
argument_list|(
name|data
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_size_group_add_widget
argument_list|(
name|spinner_group
argument_list|,
name|GIMP_SCALE_ENTRY_SPINBUTTON
argument_list|(
name|data
argument_list|)
argument_list|)
expr_stmt|;
name|slider
operator|=
name|GIMP_SCALE_ENTRY_SCALE
argument_list|(
name|data
argument_list|)
expr_stmt|;
name|gtk_range_set_update_policy
argument_list|(
name|GTK_RANGE
argument_list|(
name|slider
argument_list|)
argument_list|,
name|GTK_UPDATE_DELAYED
argument_list|)
expr_stmt|;
name|g_signal_connect
argument_list|(
name|data
argument_list|,
literal|"value_changed"
argument_list|,
name|G_CALLBACK
argument_list|(
name|hue_saturation_lightness_adjustment_update
argument_list|)
argument_list|,
name|hs_tool
argument_list|)
expr_stmt|;
comment|/*  Create the saturation scale widget  */
name|data
operator|=
name|gimp_scale_entry_new
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|0
argument_list|,
literal|2
argument_list|,
name|_
argument_list|(
literal|"_Saturation:"
argument_list|)
argument_list|,
name|SLIDER_WIDTH
argument_list|,
operator|-
literal|1
argument_list|,
literal|0.0
argument_list|,
operator|-
literal|100.0
argument_list|,
literal|100.0
argument_list|,
literal|1.0
argument_list|,
literal|10.0
argument_list|,
literal|0
argument_list|,
name|TRUE
argument_list|,
literal|0.0
argument_list|,
literal|0.0
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|hs_tool
operator|->
name|saturation_data
operator|=
name|GTK_ADJUSTMENT
argument_list|(
name|data
argument_list|)
expr_stmt|;
name|gtk_size_group_add_widget
argument_list|(
name|label_group
argument_list|,
name|GIMP_SCALE_ENTRY_LABEL
argument_list|(
name|data
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_size_group_add_widget
argument_list|(
name|spinner_group
argument_list|,
name|GIMP_SCALE_ENTRY_SPINBUTTON
argument_list|(
name|data
argument_list|)
argument_list|)
expr_stmt|;
name|slider
operator|=
name|GIMP_SCALE_ENTRY_SCALE
argument_list|(
name|data
argument_list|)
expr_stmt|;
name|gtk_range_set_update_policy
argument_list|(
name|GTK_RANGE
argument_list|(
name|slider
argument_list|)
argument_list|,
name|GTK_UPDATE_DELAYED
argument_list|)
expr_stmt|;
name|g_signal_connect
argument_list|(
name|hs_tool
operator|->
name|saturation_data
argument_list|,
literal|"value_changed"
argument_list|,
name|G_CALLBACK
argument_list|(
name|hue_saturation_saturation_adjustment_update
argument_list|)
argument_list|,
name|hs_tool
argument_list|)
expr_stmt|;
name|hbox
operator|=
name|gtk_hbox_new
argument_list|(
name|FALSE
argument_list|,
literal|6
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|vbox
argument_list|)
argument_list|,
name|hbox
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|hbox
argument_list|)
expr_stmt|;
name|button
operator|=
name|gtk_button_new_with_mnemonic
argument_list|(
name|_
argument_list|(
literal|"R_eset color"
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_box_pack_end
argument_list|(
name|GTK_BOX
argument_list|(
name|hbox
argument_list|)
argument_list|,
name|button
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|button
argument_list|)
expr_stmt|;
name|g_signal_connect
argument_list|(
name|button
argument_list|,
literal|"clicked"
argument_list|,
name|G_CALLBACK
argument_list|(
name|hue_saturation_partition_reset_callback
argument_list|)
argument_list|,
name|hs_tool
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_hue_saturation_tool_reset (GimpImageMapTool * image_map_tool)
name|gimp_hue_saturation_tool_reset
parameter_list|(
name|GimpImageMapTool
modifier|*
name|image_map_tool
parameter_list|)
block|{
name|GimpHueSaturationTool
modifier|*
name|hs_tool
init|=
name|GIMP_HUE_SATURATION_TOOL
argument_list|(
name|image_map_tool
argument_list|)
decl_stmt|;
name|hue_saturation_init
argument_list|(
name|hs_tool
operator|->
name|hue_saturation
argument_list|)
expr_stmt|;
name|hue_saturation_update
argument_list|(
name|hs_tool
argument_list|,
name|ALL
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|hue_saturation_update (GimpHueSaturationTool * hs_tool,gint update)
name|hue_saturation_update
parameter_list|(
name|GimpHueSaturationTool
modifier|*
name|hs_tool
parameter_list|,
name|gint
name|update
parameter_list|)
block|{
name|gint
name|rgb
index|[
literal|3
index|]
decl_stmt|;
name|GimpRGB
name|color
decl_stmt|;
name|gint
name|i
decl_stmt|;
name|hue_saturation_calculate_transfers
argument_list|(
name|hs_tool
operator|->
name|hue_saturation
argument_list|)
expr_stmt|;
if|if
condition|(
name|update
operator|&
name|HUE_SLIDER
condition|)
name|gtk_adjustment_set_value
argument_list|(
name|GTK_ADJUSTMENT
argument_list|(
name|hs_tool
operator|->
name|hue_data
argument_list|)
argument_list|,
name|hs_tool
operator|->
name|hue_saturation
operator|->
name|hue
index|[
name|hs_tool
operator|->
name|hue_partition
index|]
argument_list|)
expr_stmt|;
if|if
condition|(
name|update
operator|&
name|LIGHTNESS_SLIDER
condition|)
name|gtk_adjustment_set_value
argument_list|(
name|GTK_ADJUSTMENT
argument_list|(
name|hs_tool
operator|->
name|lightness_data
argument_list|)
argument_list|,
name|hs_tool
operator|->
name|hue_saturation
operator|->
name|lightness
index|[
name|hs_tool
operator|->
name|hue_partition
index|]
argument_list|)
expr_stmt|;
if|if
condition|(
name|update
operator|&
name|SATURATION_SLIDER
condition|)
name|gtk_adjustment_set_value
argument_list|(
name|GTK_ADJUSTMENT
argument_list|(
name|hs_tool
operator|->
name|saturation_data
argument_list|)
argument_list|,
name|hs_tool
operator|->
name|hue_saturation
operator|->
name|saturation
index|[
name|hs_tool
operator|->
name|hue_partition
index|]
argument_list|)
expr_stmt|;
if|if
condition|(
name|update
operator|&
name|OVERLAP_SLIDER
condition|)
name|gtk_adjustment_set_value
argument_list|(
name|GTK_ADJUSTMENT
argument_list|(
name|hs_tool
operator|->
name|overlap_data
argument_list|)
argument_list|,
name|hs_tool
operator|->
name|hue_saturation
operator|->
name|overlap
argument_list|)
expr_stmt|;
if|if
condition|(
name|update
operator|&
name|DRAW
condition|)
block|{
for|for
control|(
name|i
operator|=
literal|0
init|;
name|i
operator|<
literal|6
condition|;
name|i
operator|++
control|)
block|{
name|rgb
index|[
name|RED_PIX
index|]
operator|=
name|default_colors
index|[
name|i
index|]
index|[
name|RED_PIX
index|]
expr_stmt|;
name|rgb
index|[
name|GREEN_PIX
index|]
operator|=
name|default_colors
index|[
name|i
index|]
index|[
name|GREEN_PIX
index|]
expr_stmt|;
name|rgb
index|[
name|BLUE_PIX
index|]
operator|=
name|default_colors
index|[
name|i
index|]
index|[
name|BLUE_PIX
index|]
expr_stmt|;
name|gimp_rgb_to_hsl_int
argument_list|(
name|rgb
argument_list|,
name|rgb
operator|+
literal|1
argument_list|,
name|rgb
operator|+
literal|2
argument_list|)
expr_stmt|;
name|rgb
index|[
name|RED_PIX
index|]
operator|=
name|hs_tool
operator|->
name|hue_saturation
operator|->
name|hue_transfer
index|[
name|i
index|]
index|[
name|rgb
index|[
name|RED_PIX
index|]
index|]
expr_stmt|;
name|rgb
index|[
name|GREEN_PIX
index|]
operator|=
name|hs_tool
operator|->
name|hue_saturation
operator|->
name|saturation_transfer
index|[
name|i
index|]
index|[
name|rgb
index|[
name|GREEN_PIX
index|]
index|]
expr_stmt|;
name|rgb
index|[
name|BLUE_PIX
index|]
operator|=
name|hs_tool
operator|->
name|hue_saturation
operator|->
name|lightness_transfer
index|[
name|i
index|]
index|[
name|rgb
index|[
name|BLUE_PIX
index|]
index|]
expr_stmt|;
name|gimp_hsl_to_rgb_int
argument_list|(
name|rgb
argument_list|,
name|rgb
operator|+
literal|1
argument_list|,
name|rgb
operator|+
literal|2
argument_list|)
expr_stmt|;
name|gimp_rgb_set_uchar
argument_list|(
operator|&
name|color
argument_list|,
operator|(
name|guchar
operator|)
name|rgb
index|[
literal|0
index|]
argument_list|,
operator|(
name|guchar
operator|)
name|rgb
index|[
literal|1
index|]
argument_list|,
operator|(
name|guchar
operator|)
name|rgb
index|[
literal|2
index|]
argument_list|)
expr_stmt|;
name|gimp_color_area_set_color
argument_list|(
name|GIMP_COLOR_AREA
argument_list|(
name|hs_tool
operator|->
name|hue_partition_da
index|[
name|i
index|]
argument_list|)
argument_list|,
operator|&
name|color
argument_list|)
expr_stmt|;
block|}
block|}
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|hue_saturation_partition_callback (GtkWidget * widget,gpointer data)
name|hue_saturation_partition_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpHueSaturationTool
modifier|*
name|hs_tool
init|=
name|GIMP_HUE_SATURATION_TOOL
argument_list|(
name|data
argument_list|)
decl_stmt|;
name|GimpHueRange
name|partition
decl_stmt|;
name|partition
operator|=
name|GPOINTER_TO_INT
argument_list|(
name|g_object_get_data
argument_list|(
name|G_OBJECT
argument_list|(
name|widget
argument_list|)
argument_list|,
literal|"hue_partition"
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|hs_tool
operator|->
name|hue_partition
operator|!=
name|partition
condition|)
block|{
name|hs_tool
operator|->
name|hue_partition
operator|=
name|partition
expr_stmt|;
name|hue_saturation_update
argument_list|(
name|hs_tool
argument_list|,
name|SLIDERS
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|hue_saturation_partition_reset_callback (GtkWidget * widget,gpointer data)
name|hue_saturation_partition_reset_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpHueSaturationTool
modifier|*
name|hs_tool
init|=
name|GIMP_HUE_SATURATION_TOOL
argument_list|(
name|data
argument_list|)
decl_stmt|;
name|hue_saturation_partition_reset
argument_list|(
name|hs_tool
operator|->
name|hue_saturation
argument_list|,
name|hs_tool
operator|->
name|hue_partition
argument_list|)
expr_stmt|;
name|hue_saturation_update
argument_list|(
name|hs_tool
argument_list|,
name|ALL
argument_list|)
expr_stmt|;
name|gimp_image_map_tool_preview
argument_list|(
name|GIMP_IMAGE_MAP_TOOL
argument_list|(
name|hs_tool
argument_list|)
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|hue_saturation_hue_adjustment_update (GtkAdjustment * adjustment,gpointer data)
name|hue_saturation_hue_adjustment_update
parameter_list|(
name|GtkAdjustment
modifier|*
name|adjustment
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpHueSaturationTool
modifier|*
name|hs_tool
init|=
name|GIMP_HUE_SATURATION_TOOL
argument_list|(
name|data
argument_list|)
decl_stmt|;
name|GimpHueRange
name|part
init|=
name|hs_tool
operator|->
name|hue_partition
decl_stmt|;
if|if
condition|(
name|hs_tool
operator|->
name|hue_saturation
operator|->
name|hue
index|[
name|part
index|]
operator|!=
name|adjustment
operator|->
name|value
condition|)
block|{
name|hs_tool
operator|->
name|hue_saturation
operator|->
name|hue
index|[
name|part
index|]
operator|=
name|adjustment
operator|->
name|value
expr_stmt|;
name|hue_saturation_update
argument_list|(
name|hs_tool
argument_list|,
name|DRAW
argument_list|)
expr_stmt|;
name|gimp_image_map_tool_preview
argument_list|(
name|GIMP_IMAGE_MAP_TOOL
argument_list|(
name|hs_tool
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|hue_saturation_lightness_adjustment_update (GtkAdjustment * adjustment,gpointer data)
name|hue_saturation_lightness_adjustment_update
parameter_list|(
name|GtkAdjustment
modifier|*
name|adjustment
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpHueSaturationTool
modifier|*
name|hs_tool
init|=
name|GIMP_HUE_SATURATION_TOOL
argument_list|(
name|data
argument_list|)
decl_stmt|;
name|GimpHueRange
name|part
init|=
name|hs_tool
operator|->
name|hue_partition
decl_stmt|;
if|if
condition|(
name|hs_tool
operator|->
name|hue_saturation
operator|->
name|lightness
index|[
name|part
index|]
operator|!=
name|adjustment
operator|->
name|value
condition|)
block|{
name|hs_tool
operator|->
name|hue_saturation
operator|->
name|lightness
index|[
name|part
index|]
operator|=
name|adjustment
operator|->
name|value
expr_stmt|;
name|hue_saturation_update
argument_list|(
name|hs_tool
argument_list|,
name|DRAW
argument_list|)
expr_stmt|;
name|gimp_image_map_tool_preview
argument_list|(
name|GIMP_IMAGE_MAP_TOOL
argument_list|(
name|hs_tool
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|hue_saturation_saturation_adjustment_update (GtkAdjustment * adjustment,gpointer data)
name|hue_saturation_saturation_adjustment_update
parameter_list|(
name|GtkAdjustment
modifier|*
name|adjustment
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpHueSaturationTool
modifier|*
name|hs_tool
init|=
name|GIMP_HUE_SATURATION_TOOL
argument_list|(
name|data
argument_list|)
decl_stmt|;
name|GimpHueRange
name|part
init|=
name|hs_tool
operator|->
name|hue_partition
decl_stmt|;
if|if
condition|(
name|hs_tool
operator|->
name|hue_saturation
operator|->
name|saturation
index|[
name|part
index|]
operator|!=
name|adjustment
operator|->
name|value
condition|)
block|{
name|hs_tool
operator|->
name|hue_saturation
operator|->
name|saturation
index|[
name|part
index|]
operator|=
name|adjustment
operator|->
name|value
expr_stmt|;
name|hue_saturation_update
argument_list|(
name|hs_tool
argument_list|,
name|DRAW
argument_list|)
expr_stmt|;
name|gimp_image_map_tool_preview
argument_list|(
name|GIMP_IMAGE_MAP_TOOL
argument_list|(
name|hs_tool
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|hue_saturation_overlap_adjustment_update (GtkAdjustment * adjustment,gpointer data)
name|hue_saturation_overlap_adjustment_update
parameter_list|(
name|GtkAdjustment
modifier|*
name|adjustment
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GimpHueSaturationTool
modifier|*
name|hs_tool
init|=
name|GIMP_HUE_SATURATION_TOOL
argument_list|(
name|data
argument_list|)
decl_stmt|;
if|if
condition|(
name|hs_tool
operator|->
name|hue_saturation
operator|->
name|overlap
operator|!=
name|adjustment
operator|->
name|value
condition|)
block|{
name|hs_tool
operator|->
name|hue_saturation
operator|->
name|overlap
operator|=
name|adjustment
operator|->
name|value
expr_stmt|;
name|hue_saturation_update
argument_list|(
name|hs_tool
argument_list|,
name|DRAW
argument_list|)
expr_stmt|;
name|gimp_image_map_tool_preview
argument_list|(
name|GIMP_IMAGE_MAP_TOOL
argument_list|(
name|hs_tool
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
end_function

end_unit

