begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* The GIMP -- an image manipulation program  * Copyright (C) 1995-1999 Spencer Kimball and Peter Mattis  *  * This program is free software; you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 2 of the License, or  * (at your option) any later version.  *  * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *  * You should have received a copy of the GNU General Public License  * along with this program; if not, write to the Free Software  * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  */
end_comment

begin_include
include|#
directive|include
file|"config.h"
end_include

begin_include
include|#
directive|include
file|<gtk/gtk.h>
end_include

begin_include
include|#
directive|include
file|"libgimpbase/gimpbase.h"
end_include

begin_include
include|#
directive|include
file|"libgimpconfig/gimpconfig.h"
end_include

begin_include
include|#
directive|include
file|"libgimpwidgets/gimpwidgets.h"
end_include

begin_include
include|#
directive|include
file|"tools-types.h"
end_include

begin_include
include|#
directive|include
file|"gimprectangleoptions.h"
end_include

begin_include
include|#
directive|include
file|"gimptooloptions-gui.h"
end_include

begin_include
include|#
directive|include
file|"gimp-intl.h"
end_include

begin_enum
enum|enum
DECL|enum|__anon295424110103
block|{
DECL|enumerator|PROP_0
name|PROP_0
block|,
DECL|enumerator|PROP_HIGHLIGHT
name|PROP_HIGHLIGHT
block|,
DECL|enumerator|PROP_FIXED_WIDTH
name|PROP_FIXED_WIDTH
block|,
DECL|enumerator|PROP_WIDTH
name|PROP_WIDTH
block|,
DECL|enumerator|PROP_FIXED_HEIGHT
name|PROP_FIXED_HEIGHT
block|,
DECL|enumerator|PROP_HEIGHT
name|PROP_HEIGHT
block|,
DECL|enumerator|PROP_FIXED_ASPECT
name|PROP_FIXED_ASPECT
block|,
DECL|enumerator|PROP_ASPECT
name|PROP_ASPECT
block|,
DECL|enumerator|PROP_FIXED_CENTER
name|PROP_FIXED_CENTER
block|,
DECL|enumerator|PROP_CENTER_X
name|PROP_CENTER_X
block|,
DECL|enumerator|PROP_CENTER_Y
name|PROP_CENTER_Y
block|,
DECL|enumerator|PROP_UNIT
name|PROP_UNIT
block|}
enum|;
end_enum

begin_function_decl
specifier|static
name|void
name|gimp_rectangle_options_iface_base_init
parameter_list|(
name|GimpRectangleOptionsInterface
modifier|*
name|rectangle_options_iface
parameter_list|)
function_decl|;
end_function_decl

begin_function
name|GType
DECL|function|gimp_rectangle_options_interface_get_type (void)
name|gimp_rectangle_options_interface_get_type
parameter_list|(
name|void
parameter_list|)
block|{
specifier|static
name|GType
name|rectangle_options_iface_type
init|=
literal|0
decl_stmt|;
if|if
condition|(
operator|!
name|rectangle_options_iface_type
condition|)
block|{
specifier|static
specifier|const
name|GTypeInfo
name|rectangle_options_iface_info
init|=
block|{
sizeof|sizeof
argument_list|(
name|GimpRectangleOptionsInterface
argument_list|)
block|,
operator|(
name|GBaseInitFunc
operator|)
name|gimp_rectangle_options_iface_base_init
block|,
operator|(
name|GBaseFinalizeFunc
operator|)
name|NULL
block|,       }
decl_stmt|;
name|rectangle_options_iface_type
operator|=
name|g_type_register_static
argument_list|(
name|G_TYPE_INTERFACE
argument_list|,
literal|"GimpRectangleOptionsInterface"
argument_list|,
operator|&
name|rectangle_options_iface_info
argument_list|,
literal|0
argument_list|)
expr_stmt|;
block|}
return|return
name|rectangle_options_iface_type
return|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_rectangle_options_iface_base_init (GimpRectangleOptionsInterface * rectangle_options_iface)
name|gimp_rectangle_options_iface_base_init
parameter_list|(
name|GimpRectangleOptionsInterface
modifier|*
name|rectangle_options_iface
parameter_list|)
block|{
specifier|static
name|gboolean
name|initialized
init|=
name|FALSE
decl_stmt|;
if|if
condition|(
operator|!
name|initialized
condition|)
block|{
name|initialized
operator|=
name|TRUE
expr_stmt|;
block|}
block|}
end_function

begin_function
name|void
DECL|function|gimp_rectangle_options_set_highlight (GimpRectangleOptions * options,gboolean highlight)
name|gimp_rectangle_options_set_highlight
parameter_list|(
name|GimpRectangleOptions
modifier|*
name|options
parameter_list|,
name|gboolean
name|highlight
parameter_list|)
block|{
name|GimpRectangleOptionsInterface
modifier|*
name|options_iface
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_RECTANGLE_OPTIONS
argument_list|(
name|options
argument_list|)
argument_list|)
expr_stmt|;
name|options_iface
operator|=
name|GIMP_RECTANGLE_OPTIONS_GET_INTERFACE
argument_list|(
name|options
argument_list|)
expr_stmt|;
if|if
condition|(
name|options_iface
operator|->
name|set_highlight
condition|)
name|options_iface
operator|->
name|set_highlight
argument_list|(
name|options
argument_list|,
name|highlight
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|gboolean
DECL|function|gimp_rectangle_options_get_highlight (GimpRectangleOptions * options)
name|gimp_rectangle_options_get_highlight
parameter_list|(
name|GimpRectangleOptions
modifier|*
name|options
parameter_list|)
block|{
name|GimpRectangleOptionsInterface
modifier|*
name|options_iface
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_RECTANGLE_OPTIONS
argument_list|(
name|options
argument_list|)
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|options_iface
operator|=
name|GIMP_RECTANGLE_OPTIONS_GET_INTERFACE
argument_list|(
name|options
argument_list|)
expr_stmt|;
if|if
condition|(
name|options_iface
operator|->
name|get_highlight
condition|)
return|return
name|options_iface
operator|->
name|get_highlight
argument_list|(
name|options
argument_list|)
return|;
return|return
name|FALSE
return|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_rectangle_options_set_fixed_width (GimpRectangleOptions * options,gboolean fixed_width)
name|gimp_rectangle_options_set_fixed_width
parameter_list|(
name|GimpRectangleOptions
modifier|*
name|options
parameter_list|,
name|gboolean
name|fixed_width
parameter_list|)
block|{
name|GimpRectangleOptionsInterface
modifier|*
name|options_iface
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_RECTANGLE_OPTIONS
argument_list|(
name|options
argument_list|)
argument_list|)
expr_stmt|;
name|options_iface
operator|=
name|GIMP_RECTANGLE_OPTIONS_GET_INTERFACE
argument_list|(
name|options
argument_list|)
expr_stmt|;
if|if
condition|(
name|options_iface
operator|->
name|set_fixed_width
condition|)
name|options_iface
operator|->
name|set_fixed_width
argument_list|(
name|options
argument_list|,
name|fixed_width
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|gboolean
DECL|function|gimp_rectangle_options_get_fixed_width (GimpRectangleOptions * options)
name|gimp_rectangle_options_get_fixed_width
parameter_list|(
name|GimpRectangleOptions
modifier|*
name|options
parameter_list|)
block|{
name|GimpRectangleOptionsInterface
modifier|*
name|options_iface
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_RECTANGLE_OPTIONS
argument_list|(
name|options
argument_list|)
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|options_iface
operator|=
name|GIMP_RECTANGLE_OPTIONS_GET_INTERFACE
argument_list|(
name|options
argument_list|)
expr_stmt|;
if|if
condition|(
name|options_iface
operator|->
name|get_fixed_width
condition|)
return|return
name|options_iface
operator|->
name|get_fixed_width
argument_list|(
name|options
argument_list|)
return|;
return|return
name|FALSE
return|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_rectangle_options_set_width (GimpRectangleOptions * options,gdouble width)
name|gimp_rectangle_options_set_width
parameter_list|(
name|GimpRectangleOptions
modifier|*
name|options
parameter_list|,
name|gdouble
name|width
parameter_list|)
block|{
name|GimpRectangleOptionsInterface
modifier|*
name|options_iface
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_RECTANGLE_OPTIONS
argument_list|(
name|options
argument_list|)
argument_list|)
expr_stmt|;
name|options_iface
operator|=
name|GIMP_RECTANGLE_OPTIONS_GET_INTERFACE
argument_list|(
name|options
argument_list|)
expr_stmt|;
if|if
condition|(
name|options_iface
operator|->
name|set_width
condition|)
name|options_iface
operator|->
name|set_width
argument_list|(
name|options
argument_list|,
name|width
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|gdouble
DECL|function|gimp_rectangle_options_get_width (GimpRectangleOptions * options)
name|gimp_rectangle_options_get_width
parameter_list|(
name|GimpRectangleOptions
modifier|*
name|options
parameter_list|)
block|{
name|GimpRectangleOptionsInterface
modifier|*
name|options_iface
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_RECTANGLE_OPTIONS
argument_list|(
name|options
argument_list|)
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|options_iface
operator|=
name|GIMP_RECTANGLE_OPTIONS_GET_INTERFACE
argument_list|(
name|options
argument_list|)
expr_stmt|;
if|if
condition|(
name|options_iface
operator|->
name|get_width
condition|)
return|return
name|options_iface
operator|->
name|get_width
argument_list|(
name|options
argument_list|)
return|;
return|return
literal|0
return|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_rectangle_options_set_fixed_height (GimpRectangleOptions * options,gboolean fixed_height)
name|gimp_rectangle_options_set_fixed_height
parameter_list|(
name|GimpRectangleOptions
modifier|*
name|options
parameter_list|,
name|gboolean
name|fixed_height
parameter_list|)
block|{
name|GimpRectangleOptionsInterface
modifier|*
name|options_iface
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_RECTANGLE_OPTIONS
argument_list|(
name|options
argument_list|)
argument_list|)
expr_stmt|;
name|options_iface
operator|=
name|GIMP_RECTANGLE_OPTIONS_GET_INTERFACE
argument_list|(
name|options
argument_list|)
expr_stmt|;
if|if
condition|(
name|options_iface
operator|->
name|set_fixed_height
condition|)
name|options_iface
operator|->
name|set_fixed_height
argument_list|(
name|options
argument_list|,
name|fixed_height
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|gboolean
DECL|function|gimp_rectangle_options_get_fixed_height (GimpRectangleOptions * options)
name|gimp_rectangle_options_get_fixed_height
parameter_list|(
name|GimpRectangleOptions
modifier|*
name|options
parameter_list|)
block|{
name|GimpRectangleOptionsInterface
modifier|*
name|options_iface
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_RECTANGLE_OPTIONS
argument_list|(
name|options
argument_list|)
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|options_iface
operator|=
name|GIMP_RECTANGLE_OPTIONS_GET_INTERFACE
argument_list|(
name|options
argument_list|)
expr_stmt|;
if|if
condition|(
name|options_iface
operator|->
name|get_fixed_height
condition|)
return|return
name|options_iface
operator|->
name|get_fixed_height
argument_list|(
name|options
argument_list|)
return|;
return|return
name|FALSE
return|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_rectangle_options_set_height (GimpRectangleOptions * options,gdouble height)
name|gimp_rectangle_options_set_height
parameter_list|(
name|GimpRectangleOptions
modifier|*
name|options
parameter_list|,
name|gdouble
name|height
parameter_list|)
block|{
name|GimpRectangleOptionsInterface
modifier|*
name|options_iface
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_RECTANGLE_OPTIONS
argument_list|(
name|options
argument_list|)
argument_list|)
expr_stmt|;
name|options_iface
operator|=
name|GIMP_RECTANGLE_OPTIONS_GET_INTERFACE
argument_list|(
name|options
argument_list|)
expr_stmt|;
if|if
condition|(
name|options_iface
operator|->
name|set_height
condition|)
name|options_iface
operator|->
name|set_height
argument_list|(
name|options
argument_list|,
name|height
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|gdouble
DECL|function|gimp_rectangle_options_get_height (GimpRectangleOptions * options)
name|gimp_rectangle_options_get_height
parameter_list|(
name|GimpRectangleOptions
modifier|*
name|options
parameter_list|)
block|{
name|GimpRectangleOptionsInterface
modifier|*
name|options_iface
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_RECTANGLE_OPTIONS
argument_list|(
name|options
argument_list|)
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|options_iface
operator|=
name|GIMP_RECTANGLE_OPTIONS_GET_INTERFACE
argument_list|(
name|options
argument_list|)
expr_stmt|;
if|if
condition|(
name|options_iface
operator|->
name|get_height
condition|)
return|return
name|options_iface
operator|->
name|get_height
argument_list|(
name|options
argument_list|)
return|;
return|return
literal|0
return|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_rectangle_options_set_fixed_aspect (GimpRectangleOptions * options,gboolean fixed_aspect)
name|gimp_rectangle_options_set_fixed_aspect
parameter_list|(
name|GimpRectangleOptions
modifier|*
name|options
parameter_list|,
name|gboolean
name|fixed_aspect
parameter_list|)
block|{
name|GimpRectangleOptionsInterface
modifier|*
name|options_iface
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_RECTANGLE_OPTIONS
argument_list|(
name|options
argument_list|)
argument_list|)
expr_stmt|;
name|options_iface
operator|=
name|GIMP_RECTANGLE_OPTIONS_GET_INTERFACE
argument_list|(
name|options
argument_list|)
expr_stmt|;
if|if
condition|(
name|options_iface
operator|->
name|set_fixed_aspect
condition|)
name|options_iface
operator|->
name|set_fixed_aspect
argument_list|(
name|options
argument_list|,
name|fixed_aspect
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|gboolean
DECL|function|gimp_rectangle_options_get_fixed_aspect (GimpRectangleOptions * options)
name|gimp_rectangle_options_get_fixed_aspect
parameter_list|(
name|GimpRectangleOptions
modifier|*
name|options
parameter_list|)
block|{
name|GimpRectangleOptionsInterface
modifier|*
name|options_iface
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_RECTANGLE_OPTIONS
argument_list|(
name|options
argument_list|)
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|options_iface
operator|=
name|GIMP_RECTANGLE_OPTIONS_GET_INTERFACE
argument_list|(
name|options
argument_list|)
expr_stmt|;
if|if
condition|(
name|options_iface
operator|->
name|get_fixed_aspect
condition|)
return|return
name|options_iface
operator|->
name|get_fixed_aspect
argument_list|(
name|options
argument_list|)
return|;
return|return
name|FALSE
return|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_rectangle_options_set_aspect (GimpRectangleOptions * options,gdouble aspect)
name|gimp_rectangle_options_set_aspect
parameter_list|(
name|GimpRectangleOptions
modifier|*
name|options
parameter_list|,
name|gdouble
name|aspect
parameter_list|)
block|{
name|GimpRectangleOptionsInterface
modifier|*
name|options_iface
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_RECTANGLE_OPTIONS
argument_list|(
name|options
argument_list|)
argument_list|)
expr_stmt|;
name|options_iface
operator|=
name|GIMP_RECTANGLE_OPTIONS_GET_INTERFACE
argument_list|(
name|options
argument_list|)
expr_stmt|;
if|if
condition|(
name|options_iface
operator|->
name|set_aspect
condition|)
name|options_iface
operator|->
name|set_aspect
argument_list|(
name|options
argument_list|,
name|aspect
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|gdouble
DECL|function|gimp_rectangle_options_get_aspect (GimpRectangleOptions * options)
name|gimp_rectangle_options_get_aspect
parameter_list|(
name|GimpRectangleOptions
modifier|*
name|options
parameter_list|)
block|{
name|GimpRectangleOptionsInterface
modifier|*
name|options_iface
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_RECTANGLE_OPTIONS
argument_list|(
name|options
argument_list|)
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|options_iface
operator|=
name|GIMP_RECTANGLE_OPTIONS_GET_INTERFACE
argument_list|(
name|options
argument_list|)
expr_stmt|;
if|if
condition|(
name|options_iface
operator|->
name|get_aspect
condition|)
return|return
name|options_iface
operator|->
name|get_aspect
argument_list|(
name|options
argument_list|)
return|;
return|return
literal|0
return|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_rectangle_options_set_fixed_center (GimpRectangleOptions * options,gboolean fixed_center)
name|gimp_rectangle_options_set_fixed_center
parameter_list|(
name|GimpRectangleOptions
modifier|*
name|options
parameter_list|,
name|gboolean
name|fixed_center
parameter_list|)
block|{
name|GimpRectangleOptionsInterface
modifier|*
name|options_iface
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_RECTANGLE_OPTIONS
argument_list|(
name|options
argument_list|)
argument_list|)
expr_stmt|;
name|options_iface
operator|=
name|GIMP_RECTANGLE_OPTIONS_GET_INTERFACE
argument_list|(
name|options
argument_list|)
expr_stmt|;
if|if
condition|(
name|options_iface
operator|->
name|set_fixed_center
condition|)
name|options_iface
operator|->
name|set_fixed_center
argument_list|(
name|options
argument_list|,
name|fixed_center
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|gboolean
DECL|function|gimp_rectangle_options_get_fixed_center (GimpRectangleOptions * options)
name|gimp_rectangle_options_get_fixed_center
parameter_list|(
name|GimpRectangleOptions
modifier|*
name|options
parameter_list|)
block|{
name|GimpRectangleOptionsInterface
modifier|*
name|options_iface
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_RECTANGLE_OPTIONS
argument_list|(
name|options
argument_list|)
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|options_iface
operator|=
name|GIMP_RECTANGLE_OPTIONS_GET_INTERFACE
argument_list|(
name|options
argument_list|)
expr_stmt|;
if|if
condition|(
name|options_iface
operator|->
name|get_fixed_center
condition|)
return|return
name|options_iface
operator|->
name|get_fixed_center
argument_list|(
name|options
argument_list|)
return|;
return|return
name|FALSE
return|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_rectangle_options_set_center_x (GimpRectangleOptions * options,gdouble center_x)
name|gimp_rectangle_options_set_center_x
parameter_list|(
name|GimpRectangleOptions
modifier|*
name|options
parameter_list|,
name|gdouble
name|center_x
parameter_list|)
block|{
name|GimpRectangleOptionsInterface
modifier|*
name|options_iface
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_RECTANGLE_OPTIONS
argument_list|(
name|options
argument_list|)
argument_list|)
expr_stmt|;
name|options_iface
operator|=
name|GIMP_RECTANGLE_OPTIONS_GET_INTERFACE
argument_list|(
name|options
argument_list|)
expr_stmt|;
if|if
condition|(
name|options_iface
operator|->
name|set_center_x
condition|)
name|options_iface
operator|->
name|set_center_x
argument_list|(
name|options
argument_list|,
name|center_x
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|gdouble
DECL|function|gimp_rectangle_options_get_center_x (GimpRectangleOptions * options)
name|gimp_rectangle_options_get_center_x
parameter_list|(
name|GimpRectangleOptions
modifier|*
name|options
parameter_list|)
block|{
name|GimpRectangleOptionsInterface
modifier|*
name|options_iface
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_RECTANGLE_OPTIONS
argument_list|(
name|options
argument_list|)
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|options_iface
operator|=
name|GIMP_RECTANGLE_OPTIONS_GET_INTERFACE
argument_list|(
name|options
argument_list|)
expr_stmt|;
if|if
condition|(
name|options_iface
operator|->
name|get_center_x
condition|)
return|return
name|options_iface
operator|->
name|get_center_x
argument_list|(
name|options
argument_list|)
return|;
return|return
literal|0
return|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_rectangle_options_set_center_y (GimpRectangleOptions * options,gdouble center_y)
name|gimp_rectangle_options_set_center_y
parameter_list|(
name|GimpRectangleOptions
modifier|*
name|options
parameter_list|,
name|gdouble
name|center_y
parameter_list|)
block|{
name|GimpRectangleOptionsInterface
modifier|*
name|options_iface
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_RECTANGLE_OPTIONS
argument_list|(
name|options
argument_list|)
argument_list|)
expr_stmt|;
name|options_iface
operator|=
name|GIMP_RECTANGLE_OPTIONS_GET_INTERFACE
argument_list|(
name|options
argument_list|)
expr_stmt|;
if|if
condition|(
name|options_iface
operator|->
name|set_center_y
condition|)
name|options_iface
operator|->
name|set_center_y
argument_list|(
name|options
argument_list|,
name|center_y
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|gdouble
DECL|function|gimp_rectangle_options_get_center_y (GimpRectangleOptions * options)
name|gimp_rectangle_options_get_center_y
parameter_list|(
name|GimpRectangleOptions
modifier|*
name|options
parameter_list|)
block|{
name|GimpRectangleOptionsInterface
modifier|*
name|options_iface
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_RECTANGLE_OPTIONS
argument_list|(
name|options
argument_list|)
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|options_iface
operator|=
name|GIMP_RECTANGLE_OPTIONS_GET_INTERFACE
argument_list|(
name|options
argument_list|)
expr_stmt|;
if|if
condition|(
name|options_iface
operator|->
name|get_center_y
condition|)
return|return
name|options_iface
operator|->
name|get_center_y
argument_list|(
name|options
argument_list|)
return|;
return|return
literal|0
return|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_rectangle_options_set_unit (GimpRectangleOptions * options,GimpUnit unit)
name|gimp_rectangle_options_set_unit
parameter_list|(
name|GimpRectangleOptions
modifier|*
name|options
parameter_list|,
name|GimpUnit
name|unit
parameter_list|)
block|{
name|GimpRectangleOptionsInterface
modifier|*
name|options_iface
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_RECTANGLE_OPTIONS
argument_list|(
name|options
argument_list|)
argument_list|)
expr_stmt|;
name|options_iface
operator|=
name|GIMP_RECTANGLE_OPTIONS_GET_INTERFACE
argument_list|(
name|options
argument_list|)
expr_stmt|;
if|if
condition|(
name|options_iface
operator|->
name|set_unit
condition|)
name|options_iface
operator|->
name|set_unit
argument_list|(
name|options
argument_list|,
name|unit
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|GimpUnit
DECL|function|gimp_rectangle_options_get_unit (GimpRectangleOptions * options)
name|gimp_rectangle_options_get_unit
parameter_list|(
name|GimpRectangleOptions
modifier|*
name|options
parameter_list|)
block|{
name|GimpRectangleOptionsInterface
modifier|*
name|options_iface
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_RECTANGLE_OPTIONS
argument_list|(
name|options
argument_list|)
argument_list|,
name|GIMP_UNIT_PIXEL
argument_list|)
expr_stmt|;
name|options_iface
operator|=
name|GIMP_RECTANGLE_OPTIONS_GET_INTERFACE
argument_list|(
name|options
argument_list|)
expr_stmt|;
if|if
condition|(
name|options_iface
operator|->
name|get_unit
condition|)
return|return
name|options_iface
operator|->
name|get_unit
argument_list|(
name|options
argument_list|)
return|;
return|return
name|GIMP_UNIT_PIXEL
return|;
block|}
end_function

begin_function
name|GtkWidget
modifier|*
DECL|function|gimp_rectangle_options_gui (GimpToolOptions * tool_options)
name|gimp_rectangle_options_gui
parameter_list|(
name|GimpToolOptions
modifier|*
name|tool_options
parameter_list|)
block|{
name|GObject
modifier|*
name|config
init|=
name|G_OBJECT
argument_list|(
name|tool_options
argument_list|)
decl_stmt|;
name|GtkWidget
modifier|*
name|vbox
decl_stmt|;
name|GtkWidget
modifier|*
name|button
decl_stmt|;
name|GtkWidget
modifier|*
name|controls_container
decl_stmt|;
name|GtkWidget
modifier|*
name|table
decl_stmt|;
name|GtkWidget
modifier|*
name|entry
decl_stmt|;
name|GtkWidget
modifier|*
name|hbox
decl_stmt|;
name|GtkWidget
modifier|*
name|label
decl_stmt|;
name|GtkWidget
modifier|*
name|spinbutton
decl_stmt|;
name|vbox
operator|=
name|gimp_tool_options_gui
argument_list|(
name|tool_options
argument_list|)
expr_stmt|;
name|button
operator|=
name|gimp_prop_check_button_new
argument_list|(
name|config
argument_list|,
literal|"highlight"
argument_list|,
name|_
argument_list|(
literal|"Highlight"
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|vbox
argument_list|)
argument_list|,
name|button
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|button
argument_list|)
expr_stmt|;
name|hbox
operator|=
name|gtk_hbox_new
argument_list|(
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|vbox
argument_list|)
argument_list|,
name|hbox
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|hbox
argument_list|)
expr_stmt|;
name|table
operator|=
name|gtk_table_new
argument_list|(
literal|6
argument_list|,
literal|3
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gtk_table_set_col_spacings
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|5
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|hbox
argument_list|)
argument_list|,
name|table
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|label
operator|=
name|gtk_label_new
argument_list|(
name|_
argument_list|(
literal|"Fix"
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_table_attach_defaults
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
name|label
argument_list|,
literal|0
argument_list|,
literal|1
argument_list|,
literal|0
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|label
argument_list|)
expr_stmt|;
name|button
operator|=
name|gimp_prop_check_button_new
argument_list|(
name|config
argument_list|,
literal|"fixed-width"
argument_list|,
name|_
argument_list|(
literal|"Width"
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|button
argument_list|)
expr_stmt|;
name|gtk_table_attach_defaults
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
name|button
argument_list|,
literal|0
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|)
expr_stmt|;
name|entry
operator|=
name|gimp_prop_size_entry_new
argument_list|(
name|config
argument_list|,
literal|"width"
argument_list|,
literal|"unit"
argument_list|,
literal|"%a"
argument_list|,
name|GIMP_SIZE_ENTRY_UPDATE_SIZE
argument_list|,
literal|300
argument_list|)
expr_stmt|;
name|gimp_size_entry_show_unit_menu
argument_list|(
name|GIMP_SIZE_ENTRY
argument_list|(
name|entry
argument_list|)
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gtk_table_attach_defaults
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
name|entry
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|entry
argument_list|)
expr_stmt|;
name|button
operator|=
name|gimp_prop_check_button_new
argument_list|(
name|config
argument_list|,
literal|"fixed-height"
argument_list|,
name|_
argument_list|(
literal|"Height"
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|button
argument_list|)
expr_stmt|;
name|gtk_table_attach_defaults
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
name|button
argument_list|,
literal|0
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|)
expr_stmt|;
name|entry
operator|=
name|gimp_prop_size_entry_new
argument_list|(
name|config
argument_list|,
literal|"height"
argument_list|,
literal|"unit"
argument_list|,
literal|"%a"
argument_list|,
name|GIMP_SIZE_ENTRY_UPDATE_SIZE
argument_list|,
literal|300
argument_list|)
expr_stmt|;
name|gimp_size_entry_show_unit_menu
argument_list|(
name|GIMP_SIZE_ENTRY
argument_list|(
name|entry
argument_list|)
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gtk_table_attach_defaults
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
name|entry
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|entry
argument_list|)
expr_stmt|;
name|button
operator|=
name|gimp_prop_check_button_new
argument_list|(
name|config
argument_list|,
literal|"fixed-aspect"
argument_list|,
name|_
argument_list|(
literal|"Aspect"
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|button
argument_list|)
expr_stmt|;
name|gtk_table_attach_defaults
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
name|button
argument_list|,
literal|0
argument_list|,
literal|1
argument_list|,
literal|3
argument_list|,
literal|4
argument_list|)
expr_stmt|;
name|spinbutton
operator|=
name|gimp_prop_spin_button_new
argument_list|(
name|config
argument_list|,
literal|"aspect"
argument_list|,
literal|0.01
argument_list|,
literal|0.1
argument_list|,
literal|4
argument_list|)
expr_stmt|;
name|gtk_table_attach_defaults
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
name|spinbutton
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|,
literal|4
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|spinbutton
argument_list|)
expr_stmt|;
name|button
operator|=
name|gimp_prop_check_button_new
argument_list|(
name|config
argument_list|,
literal|"fixed-center"
argument_list|,
name|_
argument_list|(
literal|"Center"
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|button
argument_list|)
expr_stmt|;
name|gtk_table_attach_defaults
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
name|button
argument_list|,
literal|0
argument_list|,
literal|1
argument_list|,
literal|4
argument_list|,
literal|6
argument_list|)
expr_stmt|;
name|entry
operator|=
name|gimp_prop_size_entry_new
argument_list|(
name|config
argument_list|,
literal|"center-x"
argument_list|,
literal|"unit"
argument_list|,
literal|"%a"
argument_list|,
name|GIMP_SIZE_ENTRY_UPDATE_SIZE
argument_list|,
literal|300
argument_list|)
expr_stmt|;
name|gimp_size_entry_show_unit_menu
argument_list|(
name|GIMP_SIZE_ENTRY
argument_list|(
name|entry
argument_list|)
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gtk_table_attach_defaults
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
name|entry
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|,
literal|4
argument_list|,
literal|5
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|entry
argument_list|)
expr_stmt|;
name|entry
operator|=
name|gimp_prop_size_entry_new
argument_list|(
name|config
argument_list|,
literal|"center-y"
argument_list|,
literal|"unit"
argument_list|,
literal|"%a"
argument_list|,
name|GIMP_SIZE_ENTRY_UPDATE_SIZE
argument_list|,
literal|300
argument_list|)
expr_stmt|;
name|gimp_size_entry_show_unit_menu
argument_list|(
name|GIMP_SIZE_ENTRY
argument_list|(
name|entry
argument_list|)
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gtk_table_attach_defaults
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
name|entry
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|,
literal|5
argument_list|,
literal|6
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|entry
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|table
argument_list|)
expr_stmt|;
name|controls_container
operator|=
name|gtk_vbox_new
argument_list|(
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|vbox
argument_list|)
argument_list|,
name|controls_container
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|controls_container
argument_list|)
expr_stmt|;
name|g_object_set_data
argument_list|(
name|G_OBJECT
argument_list|(
name|tool_options
argument_list|)
argument_list|,
literal|"controls-container"
argument_list|,
name|controls_container
argument_list|)
expr_stmt|;
return|return
name|vbox
return|;
block|}
end_function

end_unit

