begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* The GIMP -- an image manipulation program  * Copyright (C) 1995-2003 Spencer Kimball and Peter Mattis  *  * This program is free software; you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 2 of the License, or  * (at your option) any later version.  *  * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *  * You should have received a copy of the GNU General Public License  * along with this program; if not, write to the Free Software  * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  */
end_comment

begin_comment
comment|/* NOTE: This file is autogenerated by pdbgen.pl. */
end_comment

begin_include
include|#
directive|include
file|"config.h"
end_include

begin_include
include|#
directive|include
file|<glib-object.h>
end_include

begin_include
include|#
directive|include
file|"pdb-types.h"
end_include

begin_include
include|#
directive|include
file|"procedural_db.h"
end_include

begin_include
include|#
directive|include
file|"core/gimp.h"
end_include

begin_include
include|#
directive|include
file|"core/gimpcontext.h"
end_include

begin_include
include|#
directive|include
file|"plug-in/plug-in-context.h"
end_include

begin_include
include|#
directive|include
file|"plug-in/plug-in.h"
end_include

begin_decl_stmt
DECL|variable|context_push_proc
specifier|static
name|ProcRecord
name|context_push_proc
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|context_pop_proc
specifier|static
name|ProcRecord
name|context_pop_proc
decl_stmt|;
end_decl_stmt

begin_function
name|void
DECL|function|register_context_procs (Gimp * gimp)
name|register_context_procs
parameter_list|(
name|Gimp
modifier|*
name|gimp
parameter_list|)
block|{
name|procedural_db_register
argument_list|(
name|gimp
argument_list|,
operator|&
name|context_push_proc
argument_list|)
expr_stmt|;
name|procedural_db_register
argument_list|(
name|gimp
argument_list|,
operator|&
name|context_pop_proc
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|Argument
modifier|*
DECL|function|context_push_invoker (Gimp * gimp,GimpContext * context,GimpProgress * progress,Argument * args)
name|context_push_invoker
parameter_list|(
name|Gimp
modifier|*
name|gimp
parameter_list|,
name|GimpContext
modifier|*
name|context
parameter_list|,
name|GimpProgress
modifier|*
name|progress
parameter_list|,
name|Argument
modifier|*
name|args
parameter_list|)
block|{
name|gboolean
name|success
init|=
name|TRUE
decl_stmt|;
if|if
condition|(
name|gimp
operator|->
name|current_plug_in
operator|&&
name|gimp
operator|->
name|current_plug_in
operator|->
name|open
condition|)
block|{
name|success
operator|=
name|plug_in_context_push
argument_list|(
name|gimp
operator|->
name|current_plug_in
argument_list|)
expr_stmt|;
block|}
else|else
name|success
operator|=
name|FALSE
expr_stmt|;
return|return
name|procedural_db_return_args
argument_list|(
operator|&
name|context_push_proc
argument_list|,
name|success
argument_list|)
return|;
block|}
end_function

begin_decl_stmt
DECL|variable|context_push_proc
specifier|static
name|ProcRecord
name|context_push_proc
init|=
block|{
literal|"gimp_context_push"
block|,
literal|"Pushes a context to the top of the plug-in's context stack."
block|,
literal|"This procedure creates a new context by copying the current context. This copy becomes the new current context for the calling plug-in until it is popped again."
block|,
literal|"Michael Natterer<mitch@gimp.org>& Sven Neumann<sven@gimp.org>"
block|,
literal|"Michael Natterer& Sven Neumann"
block|,
literal|"2004"
block|,
name|GIMP_INTERNAL
block|,
literal|0
block|,
name|NULL
block|,
literal|0
block|,
name|NULL
block|,
block|{
block|{
name|context_push_invoker
block|}
block|}
block|}
decl_stmt|;
end_decl_stmt

begin_function
specifier|static
name|Argument
modifier|*
DECL|function|context_pop_invoker (Gimp * gimp,GimpContext * context,GimpProgress * progress,Argument * args)
name|context_pop_invoker
parameter_list|(
name|Gimp
modifier|*
name|gimp
parameter_list|,
name|GimpContext
modifier|*
name|context
parameter_list|,
name|GimpProgress
modifier|*
name|progress
parameter_list|,
name|Argument
modifier|*
name|args
parameter_list|)
block|{
name|gboolean
name|success
init|=
name|TRUE
decl_stmt|;
if|if
condition|(
name|gimp
operator|->
name|current_plug_in
operator|&&
name|gimp
operator|->
name|current_plug_in
operator|->
name|open
condition|)
block|{
name|success
operator|=
name|plug_in_context_push
argument_list|(
name|gimp
operator|->
name|current_plug_in
argument_list|)
expr_stmt|;
block|}
else|else
name|success
operator|=
name|FALSE
expr_stmt|;
return|return
name|procedural_db_return_args
argument_list|(
operator|&
name|context_pop_proc
argument_list|,
name|success
argument_list|)
return|;
block|}
end_function

begin_decl_stmt
DECL|variable|context_pop_proc
specifier|static
name|ProcRecord
name|context_pop_proc
init|=
block|{
literal|"gimp_context_pop"
block|,
literal|"Pops the topmost context from the plug-in's context stack."
block|,
literal|"This procedure creates a new context and makes it the current context for the calling plug-in."
block|,
literal|"Michael Natterer<mitch@gimp.org>& Sven Neumann<sven@gimp.org>"
block|,
literal|"Michael Natterer& Sven Neumann"
block|,
literal|"2004"
block|,
name|GIMP_INTERNAL
block|,
literal|0
block|,
name|NULL
block|,
literal|0
block|,
name|NULL
block|,
block|{
block|{
name|context_pop_invoker
block|}
block|}
block|}
decl_stmt|;
end_decl_stmt

end_unit

