begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* GIMP - The GNU Image Manipulation Program  * Copyright (C) 1995 Spencer Kimball and Peter Mattis  *  * This program is free software: you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 3 of the License, or  * (at your option) any later version.  *  * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *  * You should have received a copy of the GNU General Public License  * along with this program.  If not, see<http://www.gnu.org/licenses/>.  */
end_comment

begin_include
include|#
directive|include
file|"config.h"
end_include

begin_include
include|#
directive|include
file|<gegl.h>
end_include

begin_include
include|#
directive|include
file|<gtk/gtk.h>
end_include

begin_include
include|#
directive|include
file|"libgimpmath/gimpmath.h"
end_include

begin_include
include|#
directive|include
file|"display-types.h"
end_include

begin_include
include|#
directive|include
file|"base/boundary.h"
end_include

begin_include
include|#
directive|include
file|"core/gimpdrawable.h"
end_include

begin_include
include|#
directive|include
file|"core/gimpimage.h"
end_include

begin_include
include|#
directive|include
file|"gimpdisplay.h"
end_include

begin_include
include|#
directive|include
file|"gimpdisplayshell.h"
end_include

begin_include
include|#
directive|include
file|"gimpdisplayshell-scroll.h"
end_include

begin_include
include|#
directive|include
file|"gimpdisplayshell-transform.h"
end_include

begin_comment
comment|/**  * gimp_display_shell_transform_coordinate:  * @shell:          a #GimpDisplayShell  * @image_coords:   image coordinates  * @display_coords: returns the corresponding display coordinates  *  * Transforms from image coordinates to display coordinates, so that  * objects can be rendered at the correct points on the display.  **/
end_comment

begin_function
name|void
DECL|function|gimp_display_shell_transform_coordinate (const GimpDisplayShell * shell,GimpCoords * image_coords,GimpCoords * display_coords)
name|gimp_display_shell_transform_coordinate
parameter_list|(
specifier|const
name|GimpDisplayShell
modifier|*
name|shell
parameter_list|,
name|GimpCoords
modifier|*
name|image_coords
parameter_list|,
name|GimpCoords
modifier|*
name|display_coords
parameter_list|)
block|{
name|g_return_if_fail
argument_list|(
name|GIMP_IS_DISPLAY_SHELL
argument_list|(
name|shell
argument_list|)
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
name|image_coords
operator|!=
name|NULL
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
name|display_coords
operator|!=
name|NULL
argument_list|)
expr_stmt|;
operator|*
name|display_coords
operator|=
operator|*
name|image_coords
expr_stmt|;
name|display_coords
operator|->
name|x
operator|=
name|SCALEX
argument_list|(
name|shell
argument_list|,
name|image_coords
operator|->
name|x
argument_list|)
expr_stmt|;
name|display_coords
operator|->
name|y
operator|=
name|SCALEY
argument_list|(
name|shell
argument_list|,
name|image_coords
operator|->
name|y
argument_list|)
expr_stmt|;
name|display_coords
operator|->
name|x
operator|-=
name|shell
operator|->
name|offset_x
expr_stmt|;
name|display_coords
operator|->
name|y
operator|-=
name|shell
operator|->
name|offset_y
expr_stmt|;
block|}
end_function

begin_comment
comment|/**  * gimp_display_shell_untransform_coordinate:  * @shell:          a #GimpDisplayShell  * @display_coords: display coordinates  * @image_coords:   returns the corresponding image coordinates  *  * Transforms from display coordinates to image coordinates, so that  * points on the display can be mapped to points in the image.  **/
end_comment

begin_function
name|void
DECL|function|gimp_display_shell_untransform_coordinate (const GimpDisplayShell * shell,GimpCoords * display_coords,GimpCoords * image_coords)
name|gimp_display_shell_untransform_coordinate
parameter_list|(
specifier|const
name|GimpDisplayShell
modifier|*
name|shell
parameter_list|,
name|GimpCoords
modifier|*
name|display_coords
parameter_list|,
name|GimpCoords
modifier|*
name|image_coords
parameter_list|)
block|{
name|g_return_if_fail
argument_list|(
name|GIMP_IS_DISPLAY_SHELL
argument_list|(
name|shell
argument_list|)
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
name|display_coords
operator|!=
name|NULL
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
name|image_coords
operator|!=
name|NULL
argument_list|)
expr_stmt|;
operator|*
name|image_coords
operator|=
operator|*
name|display_coords
expr_stmt|;
name|image_coords
operator|->
name|x
operator|=
name|display_coords
operator|->
name|x
operator|+
name|shell
operator|->
name|offset_x
expr_stmt|;
name|image_coords
operator|->
name|y
operator|=
name|display_coords
operator|->
name|y
operator|+
name|shell
operator|->
name|offset_y
expr_stmt|;
name|image_coords
operator|->
name|x
operator|/=
name|shell
operator|->
name|scale_x
expr_stmt|;
name|image_coords
operator|->
name|y
operator|/=
name|shell
operator|->
name|scale_y
expr_stmt|;
block|}
end_function

begin_comment
comment|/**  * gimp_display_shell_transform_xy:  * @shell:  * @x:  * @y:  * @nx:  * @ny:  *  * Transforms an image coordinate to a shell coordinate.  **/
end_comment

begin_function
name|void
DECL|function|gimp_display_shell_transform_xy (const GimpDisplayShell * shell,gdouble x,gdouble y,gint * nx,gint * ny)
name|gimp_display_shell_transform_xy
parameter_list|(
specifier|const
name|GimpDisplayShell
modifier|*
name|shell
parameter_list|,
name|gdouble
name|x
parameter_list|,
name|gdouble
name|y
parameter_list|,
name|gint
modifier|*
name|nx
parameter_list|,
name|gint
modifier|*
name|ny
parameter_list|)
block|{
name|gint64
name|tx
decl_stmt|;
name|gint64
name|ty
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_DISPLAY_SHELL
argument_list|(
name|shell
argument_list|)
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
name|nx
operator|!=
name|NULL
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
name|ny
operator|!=
name|NULL
argument_list|)
expr_stmt|;
name|tx
operator|=
operator|(
operator|(
name|gint64
operator|)
name|x
operator|*
name|shell
operator|->
name|x_src_dec
operator|)
operator|/
name|shell
operator|->
name|x_dest_inc
expr_stmt|;
name|ty
operator|=
operator|(
operator|(
name|gint64
operator|)
name|y
operator|*
name|shell
operator|->
name|y_src_dec
operator|)
operator|/
name|shell
operator|->
name|y_dest_inc
expr_stmt|;
name|tx
operator|-=
name|shell
operator|->
name|offset_x
expr_stmt|;
name|ty
operator|-=
name|shell
operator|->
name|offset_y
expr_stmt|;
comment|/* The projected coordinates might overflow a gint in the case of big      images at high zoom levels, so we clamp them here to avoid problems.  */
operator|*
name|nx
operator|=
name|CLAMP
argument_list|(
name|tx
argument_list|,
name|G_MININT
argument_list|,
name|G_MAXINT
argument_list|)
expr_stmt|;
operator|*
name|ny
operator|=
name|CLAMP
argument_list|(
name|ty
argument_list|,
name|G_MININT
argument_list|,
name|G_MAXINT
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/**  * gimp_display_shell_untransform_xy:  * @shell:       a #GimpDisplayShell  * @x:           x coordinate in display coordinates  * @y:           y coordinate in display coordinates  * @nx:          returns x oordinate in image coordinates  * @ny:          returns y coordinate in image coordinates  * @round:       if %TRUE, round the results to the nearest integer;  *               if %FALSE, simply cast them to @gint.  *  * Transform from display coordinates to image coordinates, so that  * points on the display can be mapped to the corresponding points  * in the image.  **/
end_comment

begin_function
name|void
DECL|function|gimp_display_shell_untransform_xy (const GimpDisplayShell * shell,gint x,gint y,gint * nx,gint * ny,gboolean round)
name|gimp_display_shell_untransform_xy
parameter_list|(
specifier|const
name|GimpDisplayShell
modifier|*
name|shell
parameter_list|,
name|gint
name|x
parameter_list|,
name|gint
name|y
parameter_list|,
name|gint
modifier|*
name|nx
parameter_list|,
name|gint
modifier|*
name|ny
parameter_list|,
name|gboolean
name|round
parameter_list|)
block|{
name|gint64
name|tx
decl_stmt|;
name|gint64
name|ty
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_DISPLAY_SHELL
argument_list|(
name|shell
argument_list|)
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
name|nx
operator|!=
name|NULL
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
name|ny
operator|!=
name|NULL
argument_list|)
expr_stmt|;
name|tx
operator|=
operator|(
name|gint64
operator|)
name|x
operator|+
name|shell
operator|->
name|offset_x
expr_stmt|;
name|ty
operator|=
operator|(
name|gint64
operator|)
name|y
operator|+
name|shell
operator|->
name|offset_y
expr_stmt|;
name|tx
operator|*=
name|shell
operator|->
name|x_dest_inc
expr_stmt|;
name|ty
operator|*=
name|shell
operator|->
name|y_dest_inc
expr_stmt|;
name|tx
operator|+=
name|round
condition|?
name|shell
operator|->
name|x_dest_inc
else|:
name|shell
operator|->
name|x_dest_inc
operator|>>
literal|1
expr_stmt|;
name|ty
operator|+=
name|round
condition|?
name|shell
operator|->
name|y_dest_inc
else|:
name|shell
operator|->
name|y_dest_inc
operator|>>
literal|1
expr_stmt|;
name|tx
operator|/=
name|shell
operator|->
name|x_src_dec
expr_stmt|;
name|ty
operator|/=
name|shell
operator|->
name|y_src_dec
expr_stmt|;
operator|*
name|nx
operator|=
name|CLAMP
argument_list|(
name|tx
argument_list|,
name|G_MININT
argument_list|,
name|G_MAXINT
argument_list|)
expr_stmt|;
operator|*
name|ny
operator|=
name|CLAMP
argument_list|(
name|ty
argument_list|,
name|G_MININT
argument_list|,
name|G_MAXINT
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/**  * gimp_display_shell_transform_xy_f:  * @shell:       a #GimpDisplayShell  * @x:           x coordinate of point in image coordinates  * @y:           y coordinate of point in image coordinate  * @nx:          returns the transformed x coordinate  * @ny:          returns the transformed y coordinate  *  * This function is identical to gimp_display_shell_transfrom_xy(),  * except that it returns its results as doubles rather than ints.  **/
end_comment

begin_function
name|void
DECL|function|gimp_display_shell_transform_xy_f (const GimpDisplayShell * shell,gdouble x,gdouble y,gdouble * nx,gdouble * ny)
name|gimp_display_shell_transform_xy_f
parameter_list|(
specifier|const
name|GimpDisplayShell
modifier|*
name|shell
parameter_list|,
name|gdouble
name|x
parameter_list|,
name|gdouble
name|y
parameter_list|,
name|gdouble
modifier|*
name|nx
parameter_list|,
name|gdouble
modifier|*
name|ny
parameter_list|)
block|{
name|g_return_if_fail
argument_list|(
name|GIMP_IS_DISPLAY_SHELL
argument_list|(
name|shell
argument_list|)
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
name|nx
operator|!=
name|NULL
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
name|ny
operator|!=
name|NULL
argument_list|)
expr_stmt|;
operator|*
name|nx
operator|=
name|SCALEX
argument_list|(
name|shell
argument_list|,
name|x
argument_list|)
operator|-
name|shell
operator|->
name|offset_x
expr_stmt|;
operator|*
name|ny
operator|=
name|SCALEY
argument_list|(
name|shell
argument_list|,
name|y
argument_list|)
operator|-
name|shell
operator|->
name|offset_y
expr_stmt|;
block|}
end_function

begin_comment
comment|/**  * gimp_display_shell_untransform_xy_f:  * @shell:       a #GimpDisplayShell  * @x:           x coordinate in display coordinates  * @y:           y coordinate in display coordinates  * @nx:          place to return x coordinate in image coordinates  * @ny:          place to return y coordinate in image coordinates  *  * This function is identical to gimp_display_shell_untransform_xy(),  * except that the input and output coordinates are doubles rather than  * ints, and consequently there is no option related to rounding.  **/
end_comment

begin_function
name|void
DECL|function|gimp_display_shell_untransform_xy_f (const GimpDisplayShell * shell,gdouble x,gdouble y,gdouble * nx,gdouble * ny)
name|gimp_display_shell_untransform_xy_f
parameter_list|(
specifier|const
name|GimpDisplayShell
modifier|*
name|shell
parameter_list|,
name|gdouble
name|x
parameter_list|,
name|gdouble
name|y
parameter_list|,
name|gdouble
modifier|*
name|nx
parameter_list|,
name|gdouble
modifier|*
name|ny
parameter_list|)
block|{
name|g_return_if_fail
argument_list|(
name|GIMP_IS_DISPLAY_SHELL
argument_list|(
name|shell
argument_list|)
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
name|nx
operator|!=
name|NULL
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
name|ny
operator|!=
name|NULL
argument_list|)
expr_stmt|;
operator|*
name|nx
operator|=
operator|(
name|x
operator|+
name|shell
operator|->
name|offset_x
operator|)
operator|/
name|shell
operator|->
name|scale_x
expr_stmt|;
operator|*
name|ny
operator|=
operator|(
name|y
operator|+
name|shell
operator|->
name|offset_y
operator|)
operator|/
name|shell
operator|->
name|scale_y
expr_stmt|;
block|}
end_function

begin_comment
comment|/**  * gimp_display_shell_transform_points:  * @shell:       a #GimpDisplayShell  * @points:      array of GimpVectors2 coordinate pairs  * @coords:      returns the corresponding display coordinates  * @n_points:    number of points  *  * Transforms from image coordinates to display coordinates, so that  * objects can be rendered at the correct points on the display.  **/
end_comment

begin_function
name|void
DECL|function|gimp_display_shell_transform_points (const GimpDisplayShell * shell,const GimpVector2 * points,GdkPoint * coords,gint n_points)
name|gimp_display_shell_transform_points
parameter_list|(
specifier|const
name|GimpDisplayShell
modifier|*
name|shell
parameter_list|,
specifier|const
name|GimpVector2
modifier|*
name|points
parameter_list|,
name|GdkPoint
modifier|*
name|coords
parameter_list|,
name|gint
name|n_points
parameter_list|)
block|{
name|gint
name|i
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_DISPLAY_SHELL
argument_list|(
name|shell
argument_list|)
argument_list|)
expr_stmt|;
for|for
control|(
name|i
operator|=
literal|0
init|;
name|i
operator|<
name|n_points
condition|;
name|i
operator|++
control|)
block|{
name|gdouble
name|x
init|=
name|points
index|[
name|i
index|]
operator|.
name|x
decl_stmt|;
name|gdouble
name|y
init|=
name|points
index|[
name|i
index|]
operator|.
name|y
decl_stmt|;
name|x
operator|=
name|x
operator|*
name|shell
operator|->
name|x_src_dec
operator|/
name|shell
operator|->
name|x_dest_inc
expr_stmt|;
name|y
operator|=
name|y
operator|*
name|shell
operator|->
name|y_src_dec
operator|/
name|shell
operator|->
name|y_dest_inc
expr_stmt|;
name|coords
index|[
name|i
index|]
operator|.
name|x
operator|=
name|CLAMP
argument_list|(
name|PROJ_ROUND64
argument_list|(
name|x
argument_list|)
operator|-
name|shell
operator|->
name|offset_x
argument_list|,
name|G_MININT
argument_list|,
name|G_MAXINT
argument_list|)
expr_stmt|;
name|coords
index|[
name|i
index|]
operator|.
name|y
operator|=
name|CLAMP
argument_list|(
name|PROJ_ROUND64
argument_list|(
name|y
argument_list|)
operator|-
name|shell
operator|->
name|offset_y
argument_list|,
name|G_MININT
argument_list|,
name|G_MAXINT
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_comment
comment|/**  * gimp_display_shell_transform_coords:  * @shell:        a #GimpDisplayShell  * @image_coords: array of image coordinates  * @disp_coords:  returns the corresponding display coordinates  * @n_coords:     number of coordinates  *  * Transforms from image coordinates to display coordinates, so that  * objects can be rendered at the correct points on the display.  **/
end_comment

begin_function
name|void
DECL|function|gimp_display_shell_transform_coords (const GimpDisplayShell * shell,const GimpCoords * image_coords,GdkPoint * disp_coords,gint n_coords)
name|gimp_display_shell_transform_coords
parameter_list|(
specifier|const
name|GimpDisplayShell
modifier|*
name|shell
parameter_list|,
specifier|const
name|GimpCoords
modifier|*
name|image_coords
parameter_list|,
name|GdkPoint
modifier|*
name|disp_coords
parameter_list|,
name|gint
name|n_coords
parameter_list|)
block|{
name|gint
name|i
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_DISPLAY_SHELL
argument_list|(
name|shell
argument_list|)
argument_list|)
expr_stmt|;
for|for
control|(
name|i
operator|=
literal|0
init|;
name|i
operator|<
name|n_coords
condition|;
name|i
operator|++
control|)
block|{
name|gdouble
name|x
init|=
name|image_coords
index|[
name|i
index|]
operator|.
name|x
decl_stmt|;
name|gdouble
name|y
init|=
name|image_coords
index|[
name|i
index|]
operator|.
name|y
decl_stmt|;
name|x
operator|=
name|x
operator|*
name|shell
operator|->
name|x_src_dec
operator|/
name|shell
operator|->
name|x_dest_inc
expr_stmt|;
name|y
operator|=
name|y
operator|*
name|shell
operator|->
name|y_src_dec
operator|/
name|shell
operator|->
name|y_dest_inc
expr_stmt|;
name|disp_coords
index|[
name|i
index|]
operator|.
name|x
operator|=
name|CLAMP
argument_list|(
name|PROJ_ROUND64
argument_list|(
name|x
argument_list|)
operator|-
name|shell
operator|->
name|offset_x
argument_list|,
name|G_MININT
argument_list|,
name|G_MAXINT
argument_list|)
expr_stmt|;
name|disp_coords
index|[
name|i
index|]
operator|.
name|y
operator|=
name|CLAMP
argument_list|(
name|PROJ_ROUND64
argument_list|(
name|y
argument_list|)
operator|-
name|shell
operator|->
name|offset_y
argument_list|,
name|G_MININT
argument_list|,
name|G_MAXINT
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_comment
comment|/**  * gimp_display_shell_transform_segments:  * @shell:       a #GimpDisplayShell  * @src_segs:    array of segments in image coordinates  * @dest_segs:   returns the corresponding segments in display coordinates  * @n_segs:      number of segments  *  * Transforms from image coordinates to display coordinates, so that  * objects can be rendered at the correct points on the display.  **/
end_comment

begin_function
name|void
DECL|function|gimp_display_shell_transform_segments (const GimpDisplayShell * shell,const BoundSeg * src_segs,GdkSegment * dest_segs,gint n_segs,gdouble offset_x,gdouble offset_y)
name|gimp_display_shell_transform_segments
parameter_list|(
specifier|const
name|GimpDisplayShell
modifier|*
name|shell
parameter_list|,
specifier|const
name|BoundSeg
modifier|*
name|src_segs
parameter_list|,
name|GdkSegment
modifier|*
name|dest_segs
parameter_list|,
name|gint
name|n_segs
parameter_list|,
name|gdouble
name|offset_x
parameter_list|,
name|gdouble
name|offset_y
parameter_list|)
block|{
name|gint
name|i
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_DISPLAY_SHELL
argument_list|(
name|shell
argument_list|)
argument_list|)
expr_stmt|;
for|for
control|(
name|i
operator|=
literal|0
init|;
name|i
operator|<
name|n_segs
condition|;
name|i
operator|++
control|)
block|{
name|gdouble
name|x1
decl_stmt|,
name|x2
decl_stmt|;
name|gdouble
name|y1
decl_stmt|,
name|y2
decl_stmt|;
name|x1
operator|=
name|src_segs
index|[
name|i
index|]
operator|.
name|x1
operator|+
name|offset_x
expr_stmt|;
name|x2
operator|=
name|src_segs
index|[
name|i
index|]
operator|.
name|x2
operator|+
name|offset_x
expr_stmt|;
name|y1
operator|=
name|src_segs
index|[
name|i
index|]
operator|.
name|y1
operator|+
name|offset_y
expr_stmt|;
name|y2
operator|=
name|src_segs
index|[
name|i
index|]
operator|.
name|y2
operator|+
name|offset_y
expr_stmt|;
name|dest_segs
index|[
name|i
index|]
operator|.
name|x1
operator|=
name|SCALEX
argument_list|(
name|shell
argument_list|,
name|x1
argument_list|)
operator|-
name|shell
operator|->
name|offset_x
expr_stmt|;
name|dest_segs
index|[
name|i
index|]
operator|.
name|x2
operator|=
name|SCALEX
argument_list|(
name|shell
argument_list|,
name|x2
argument_list|)
operator|-
name|shell
operator|->
name|offset_x
expr_stmt|;
name|dest_segs
index|[
name|i
index|]
operator|.
name|y1
operator|=
name|SCALEY
argument_list|(
name|shell
argument_list|,
name|y1
argument_list|)
operator|-
name|shell
operator|->
name|offset_y
expr_stmt|;
name|dest_segs
index|[
name|i
index|]
operator|.
name|y2
operator|=
name|SCALEY
argument_list|(
name|shell
argument_list|,
name|y2
argument_list|)
operator|-
name|shell
operator|->
name|offset_y
expr_stmt|;
block|}
block|}
end_function

begin_comment
comment|/**  * gimp_display_shell_untransform_viewport:  * @shell:  a #GimpDisplayShell  * @x:      returns image x coordinate of display upper left corner  * @y:      returns image y coordinate of display upper left corner  * @width:  returns width of display measured in image coordinates  * @height: returns height of display measured in image coordinates  *  * This function calculates the part of the image, im image coordinates,  * that corresponds to the display viewport.  **/
end_comment

begin_function
name|void
DECL|function|gimp_display_shell_untransform_viewport (const GimpDisplayShell * shell,gint * x,gint * y,gint * width,gint * height)
name|gimp_display_shell_untransform_viewport
parameter_list|(
specifier|const
name|GimpDisplayShell
modifier|*
name|shell
parameter_list|,
name|gint
modifier|*
name|x
parameter_list|,
name|gint
modifier|*
name|y
parameter_list|,
name|gint
modifier|*
name|width
parameter_list|,
name|gint
modifier|*
name|height
parameter_list|)
block|{
name|GimpImage
modifier|*
name|image
decl_stmt|;
name|gint
name|x1
decl_stmt|,
name|y1
decl_stmt|,
name|x2
decl_stmt|,
name|y2
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_DISPLAY_SHELL
argument_list|(
name|shell
argument_list|)
argument_list|)
expr_stmt|;
name|gimp_display_shell_untransform_xy
argument_list|(
name|shell
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
operator|&
name|x1
argument_list|,
operator|&
name|y1
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gimp_display_shell_untransform_xy
argument_list|(
name|shell
argument_list|,
name|shell
operator|->
name|disp_width
argument_list|,
name|shell
operator|->
name|disp_height
argument_list|,
operator|&
name|x2
argument_list|,
operator|&
name|y2
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|image
operator|=
name|gimp_display_get_image
argument_list|(
name|shell
operator|->
name|display
argument_list|)
expr_stmt|;
if|if
condition|(
name|x1
operator|<
literal|0
condition|)
name|x1
operator|=
literal|0
expr_stmt|;
if|if
condition|(
name|y1
operator|<
literal|0
condition|)
name|y1
operator|=
literal|0
expr_stmt|;
if|if
condition|(
name|x2
operator|>
name|gimp_image_get_width
argument_list|(
name|image
argument_list|)
condition|)
name|x2
operator|=
name|gimp_image_get_width
argument_list|(
name|image
argument_list|)
expr_stmt|;
if|if
condition|(
name|y2
operator|>
name|gimp_image_get_height
argument_list|(
name|image
argument_list|)
condition|)
name|y2
operator|=
name|gimp_image_get_height
argument_list|(
name|image
argument_list|)
expr_stmt|;
if|if
condition|(
name|x
condition|)
operator|*
name|x
operator|=
name|x1
expr_stmt|;
if|if
condition|(
name|y
condition|)
operator|*
name|y
operator|=
name|y1
expr_stmt|;
if|if
condition|(
name|width
condition|)
operator|*
name|width
operator|=
name|x2
operator|-
name|x1
expr_stmt|;
if|if
condition|(
name|height
condition|)
operator|*
name|height
operator|=
name|y2
operator|-
name|y1
expr_stmt|;
block|}
end_function

end_unit

