begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_ifndef
ifndef|#
directive|ifndef
name|gimp_composite_generic_h
end_ifndef

begin_define
DECL|macro|gimp_composite_generic_h
define|#
directive|define
name|gimp_composite_generic_h
end_define

begin_function_decl
specifier|extern
name|gboolean
name|gimp_composite_generic_init
parameter_list|(
name|void
parameter_list|)
function_decl|;
end_function_decl

begin_comment
comment|/* 	* The function gimp_composite_*_install() is defined in the code generated by make-install.py 	* I hate to create a .h file just for that declaration, so I do it here (for now).  */
end_comment

begin_function_decl
specifier|extern
name|gboolean
name|gimp_composite_generic_install
parameter_list|(
name|void
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_addition_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_anti_erase_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_blend_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_burn_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_color_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_color_erase_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_color_only_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_convert_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_darken_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_difference_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_dissolve_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_divide_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_dodge_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_erase_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_grain_extract_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_grain_merge_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_hardlight_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_hue_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_lighten_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_multiply_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_normal_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_overlay_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_replace_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_saturation_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_scale_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_screen_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_softlight_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_subtract_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_swap_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_value_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|gimp_composite_behind_any_any_any_generic
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_endif
endif|#
directive|endif
end_endif

end_unit

