begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT */
end_comment

begin_comment
comment|/* REGENERATE BY USING make-installer.py */
end_comment

begin_include
include|#
directive|include
file|"config.h"
end_include

begin_include
include|#
directive|include
file|<glib-object.h>
end_include

begin_include
include|#
directive|include
file|<stdlib.h>
end_include

begin_include
include|#
directive|include
file|<stdio.h>
end_include

begin_include
include|#
directive|include
file|"base/base-types.h"
end_include

begin_include
include|#
directive|include
file|"gimp-composite.h"
end_include

begin_include
include|#
directive|include
file|"gimp-composite-sse2.h"
end_include

begin_function
name|void
DECL|function|gimp_composite_sse2_install (void)
name|gimp_composite_sse2_install
parameter_list|(
name|void
parameter_list|)
block|{
comment|/* nothing to do */
name|gimp_composite_sse2_init
argument_list|()
expr_stmt|;
block|}
end_function

end_unit

