begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT */
end_comment

begin_typedef
DECL|typedef|GimpCompositeFunctionTable
typedef|typedef
name|GimpCompositeFunction
argument_list|(
operator|*
name|GimpCompositeFunctionTable
index|[
name|GIMP_COMPOSITE_N
index|]
index|[
name|GIMP_PIXELFORMAT_N
index|]
index|[
name|GIMP_PIXELFORMAT_N
index|]
index|[
name|GIMP_PIXELFORMAT_N
index|]
argument_list|)
expr_stmt|;
end_typedef

end_unit

