begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT */
end_comment

begin_comment
comment|/* REGENERATE BY EXECUTING: make-installer.py gimp-composite-mmx.o */
end_comment

begin_include
include|#
directive|include
file|"config.h"
end_include

begin_include
include|#
directive|include
file|<glib-object.h>
end_include

begin_include
include|#
directive|include
file|<stdlib.h>
end_include

begin_include
include|#
directive|include
file|<stdio.h>
end_include

begin_include
include|#
directive|include
file|"base/base-types.h"
end_include

begin_include
include|#
directive|include
file|"gimp-composite.h"
end_include

begin_include
include|#
directive|include
file|"gimp-composite-mmx.h"
end_include

begin_function_decl
DECL|variable|gimp_composite_mmx
specifier|static
name|void
function_decl|(
modifier|*
name|gimp_composite_mmx
index|[
name|GIMP_COMPOSITE_N
index|]
index|[
name|GIMP_PIXELFORMAT_N
index|]
index|[
name|GIMP_PIXELFORMAT_N
index|]
index|[
name|GIMP_PIXELFORMAT_N
index|]
function_decl|)
parameter_list|(
name|GimpCompositeContext
modifier|*
parameter_list|)
init|=
block|{
block|{
comment|/* GIMP_COMPOSITE_NORMAL */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
function_decl|NULL
operator|,
function_decl|NULL
operator|,
function_decl|NULL
operator|,
end_function_decl

begin_comment
unit|},
comment|/* va8    */
end_comment

begin_block
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_comment
comment|/* rgb8   */
end_comment

begin_block
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_comment
comment|/* rgba8  */
end_comment

begin_block
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
unit|},
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
unit|},
block|{
comment|/* GIMP_COMPOSITE_DISSOLVE */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_BEHIND */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_MULTIPLY */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|gimp_composite_multiply_rgba8_rgba8_rgba8_mmx
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_SCREEN */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|gimp_composite_screen_rgba8_rgba8_rgba8_mmx
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_OVERLAY */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_DIFFERENCE */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|gimp_composite_difference_rgba8_rgba8_rgba8_mmx
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_ADDITION */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|gimp_composite_addition_rgba8_rgba8_rgba8_mmx
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_SUBTRACT */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|gimp_composite_subtract_rgba8_rgba8_rgba8_mmx
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_DARKEN */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|gimp_composite_darken_rgba8_rgba8_rgba8_mmx
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_LIGHTEN */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|gimp_composite_lighten_rgba8_rgba8_rgba8_mmx
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_HUE */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_SATURATION */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_COLOR_ONLY */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_VALUE */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_DIVIDE */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|gimp_composite_divide_rgba8_rgba8_rgba8_mmx
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_DODGE */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|gimp_composite_dodge_rgba8_rgba8_rgba8_mmx
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_BURN */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|gimp_composite_burn_rgba8_rgba8_rgba8_mmx
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_HARDLIGHT */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_SOFTLIGHT */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_GRAIN_EXTRACT */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_GRAIN_MERGE */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_COLOR_ERASE */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_ERASE */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_REPLACE */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_ANTI_ERASE */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_BLEND */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_SHADE */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_SWAP */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|gimp_composite_swap_rgba8_rgba8_rgba8_mmx
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_SCALE */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|gimp_composite_scale_rgba8_rgba8_rgba8_mmx
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_CONVERT */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_block
block|{
comment|/* GIMP_COMPOSITE_XOR */
block|{
comment|/* A = v8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = va8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgb8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|{
comment|/* A = rgba8 */
comment|/* v8     */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* va8    */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgb8   */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
comment|/* rgba8  */
block|{
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
name|NULL
operator|,
block|}
operator|,
block|}
operator|,
block|}
end_block

begin_operator
operator|,
end_operator

begin_function
unit|};
name|void
DECL|function|gimp_composite_mmx_install (void)
name|gimp_composite_mmx_install
parameter_list|(
name|void
parameter_list|)
block|{
name|int
name|mode
decl_stmt|,
name|a
decl_stmt|,
name|b
decl_stmt|,
name|d
decl_stmt|;
for|for
control|(
name|mode
operator|=
literal|0
init|;
name|mode
operator|<
name|GIMP_COMPOSITE_N
condition|;
name|mode
operator|++
control|)
block|{
for|for
control|(
name|a
operator|=
literal|0
init|;
name|a
operator|<
name|GIMP_PIXELFORMAT_N
condition|;
name|a
operator|++
control|)
block|{
for|for
control|(
name|b
operator|=
literal|0
init|;
name|b
operator|<
name|GIMP_PIXELFORMAT_N
condition|;
name|b
operator|++
control|)
block|{
for|for
control|(
name|d
operator|=
literal|0
init|;
name|d
operator|<
name|GIMP_PIXELFORMAT_N
condition|;
name|d
operator|++
control|)
block|{
if|if
condition|(
name|gimp_composite_mmx
index|[
name|mode
index|]
index|[
name|a
index|]
index|[
name|b
index|]
index|[
name|d
index|]
condition|)
block|{
name|gimp_composite_function
index|[
name|mode
index|]
index|[
name|a
index|]
index|[
name|b
index|]
index|[
name|d
index|]
operator|=
name|gimp_composite_mmx
index|[
name|mode
index|]
index|[
name|a
index|]
index|[
name|b
index|]
index|[
name|d
index|]
expr_stmt|;
if|if
condition|(
name|gimp_composite_options
operator|.
name|bits
operator|&
name|GIMP_COMPOSITE_OPTION_VERBOSE
condition|)
block|{
name|printf
argument_list|(
literal|"gimp_composite_install: %s %s %s %s: %p\n"
argument_list|,
name|gimp_composite_mode_astext
argument_list|(
name|mode
argument_list|)
argument_list|,
name|gimp_composite_pixelformat_astext
argument_list|(
name|a
argument_list|)
argument_list|,
name|gimp_composite_pixelformat_astext
argument_list|(
name|b
argument_list|)
argument_list|,
name|gimp_composite_pixelformat_astext
argument_list|(
name|d
argument_list|)
argument_list|,
name|gimp_composite_function
index|[
name|mode
index|]
index|[
name|a
index|]
index|[
name|b
index|]
index|[
name|d
index|]
argument_list|)
expr_stmt|;
block|}
block|}
block|}
block|}
block|}
block|}
name|gimp_composite_mmx_init
argument_list|()
expr_stmt|;
block|}
end_function

end_unit

