begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT */
end_comment

begin_comment
comment|/* REGENERATE BY USING make-installer.py */
end_comment

begin_include
include|#
directive|include
file|"config.h"
end_include

begin_include
include|#
directive|include
file|<glib-object.h>
end_include

begin_include
include|#
directive|include
file|<stdlib.h>
end_include

begin_include
include|#
directive|include
file|<stdio.h>
end_include

begin_include
include|#
directive|include
file|"base/base-types.h"
end_include

begin_include
include|#
directive|include
file|"base/cpu-accel.h"
end_include

begin_include
include|#
directive|include
file|"gimp-composite.h"
end_include

begin_include
include|#
directive|include
file|"gimp-composite-3dnow.h"
end_include

begin_function
name|gboolean
DECL|function|gimp_composite_3dnow_install (void)
name|gimp_composite_3dnow_install
parameter_list|(
name|void
parameter_list|)
block|{
comment|/* nothing to do */
return|return
operator|(
name|FALSE
operator|)
return|;
block|}
end_function

begin_function
name|gboolean
DECL|function|gimp_composite_3dnow_init (void)
name|gimp_composite_3dnow_init
parameter_list|(
name|void
parameter_list|)
block|{
if|#
directive|if
name|defined
argument_list|(
name|COMPILE_3DNOW_IS_OKAY
argument_list|)
if|if
condition|(
name|cpu_accel
argument_list|()
operator|&
name|CPU_ACCEL_X86_3DNOW
condition|)
block|{
return|return
operator|(
name|TRUE
operator|)
return|;
block|}
endif|#
directive|endif
return|return
operator|(
name|FALSE
operator|)
return|;
block|}
end_function

end_unit

