begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* LIBGIMP - The GIMP Library  * Copyright (C) 1995-1997 Peter Mattis and Spencer Kimball  *  * Thumbnail handling according to the Thumbnail Managing Standard.  * http://triq.net/~pearl/thumbnail-spec/  *  * Copyright (C) 2001-2004  Sven Neumann<sven@gimp.org>  *                          Michael Natterer<mitch@gimp.org>  *  * This library is free software: you can redistribute it and/or  * modify it under the terms of the GNU Lesser General Public  * License as published by the Free Software Foundation; either  * version 3 of the License, or (at your option) any later version.  *  * This library is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU  * Lesser General Public License for more details.  *  * You should have received a copy of the GNU Lesser General Public  * License along with this library.  If not, see  *<http://www.gnu.org/licenses/>.  */
end_comment

begin_include
include|#
directive|include
file|"config.h"
end_include

begin_include
include|#
directive|include
file|<string.h>
end_include

begin_include
include|#
directive|include
file|<errno.h>
end_include

begin_include
include|#
directive|include
file|<sys/types.h>
end_include

begin_ifdef
ifdef|#
directive|ifdef
name|HAVE_UNISTD_H
end_ifdef

begin_include
include|#
directive|include
file|<unistd.h>
end_include

begin_endif
endif|#
directive|endif
end_endif

begin_include
include|#
directive|include
file|<glib/gstdio.h>
end_include

begin_include
include|#
directive|include
file|<gdk-pixbuf/gdk-pixbuf.h>
end_include

begin_include
include|#
directive|include
file|"libgimpbase/gimpparam.h"
end_include

begin_ifdef
ifdef|#
directive|ifdef
name|G_OS_WIN32
end_ifdef

begin_include
include|#
directive|include
file|"libgimpbase/gimpwin32-io.h"
end_include

begin_include
include|#
directive|include
file|<process.h>
end_include

begin_define
DECL|macro|_getpid
define|#
directive|define
name|_getpid
value|getpid
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_include
include|#
directive|include
file|"gimpthumb-types.h"
end_include

begin_include
include|#
directive|include
file|"gimpthumb-error.h"
end_include

begin_include
include|#
directive|include
file|"gimpthumb-utils.h"
end_include

begin_include
include|#
directive|include
file|"gimpthumbnail.h"
end_include

begin_include
include|#
directive|include
file|"libgimp/libgimp-intl.h"
end_include

begin_comment
comment|/**  * SECTION: gimpthumbnail  * @title: GimpThumbnail  * @short_description: The GimpThumbnail object  *  * The GimpThumbnail object  **/
end_comment

begin_comment
comment|/*  #define GIMP_THUMB_DEBUG  */
end_comment

begin_if
if|#
directive|if
name|defined
argument_list|(
name|GIMP_THUMB_DEBUG
argument_list|)
operator|&&
name|defined
argument_list|(
name|__GNUC__
argument_list|)
end_if

begin_define
DECL|macro|GIMP_THUMB_DEBUG_CALL (t)
define|#
directive|define
name|GIMP_THUMB_DEBUG_CALL
parameter_list|(
name|t
parameter_list|)
define|\
value|g_printerr ("%s: %s\n", \                      __FUNCTION__, t->image_uri ? t->image_uri : "(null)")
end_define

begin_else
else|#
directive|else
end_else

begin_define
DECL|macro|GIMP_THUMB_DEBUG_CALL (t)
define|#
directive|define
name|GIMP_THUMB_DEBUG_CALL
parameter_list|(
name|t
parameter_list|)
value|((void)(0))
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_define
DECL|macro|TAG_DESCRIPTION
define|#
directive|define
name|TAG_DESCRIPTION
value|"tEXt::Description"
end_define

begin_define
DECL|macro|TAG_SOFTWARE
define|#
directive|define
name|TAG_SOFTWARE
value|"tEXt::Software"
end_define

begin_define
DECL|macro|TAG_THUMB_URI
define|#
directive|define
name|TAG_THUMB_URI
value|"tEXt::Thumb::URI"
end_define

begin_define
DECL|macro|TAG_THUMB_MTIME
define|#
directive|define
name|TAG_THUMB_MTIME
value|"tEXt::Thumb::MTime"
end_define

begin_define
DECL|macro|TAG_THUMB_FILESIZE
define|#
directive|define
name|TAG_THUMB_FILESIZE
value|"tEXt::Thumb::Size"
end_define

begin_define
DECL|macro|TAG_THUMB_MIMETYPE
define|#
directive|define
name|TAG_THUMB_MIMETYPE
value|"tEXt::Thumb::Mimetype"
end_define

begin_define
DECL|macro|TAG_THUMB_IMAGE_WIDTH
define|#
directive|define
name|TAG_THUMB_IMAGE_WIDTH
value|"tEXt::Thumb::Image::Width"
end_define

begin_define
DECL|macro|TAG_THUMB_IMAGE_HEIGHT
define|#
directive|define
name|TAG_THUMB_IMAGE_HEIGHT
value|"tEXt::Thumb::Image::Height"
end_define

begin_define
DECL|macro|TAG_THUMB_GIMP_TYPE
define|#
directive|define
name|TAG_THUMB_GIMP_TYPE
value|"tEXt::Thumb::X-GIMP::Type"
end_define

begin_define
DECL|macro|TAG_THUMB_GIMP_LAYERS
define|#
directive|define
name|TAG_THUMB_GIMP_LAYERS
value|"tEXt::Thumb::X-GIMP::Layers"
end_define

begin_enum
enum|enum
DECL|enum|__anon29afd1d30103
block|{
DECL|enumerator|PROP_0
name|PROP_0
block|,
DECL|enumerator|PROP_IMAGE_STATE
name|PROP_IMAGE_STATE
block|,
DECL|enumerator|PROP_IMAGE_URI
name|PROP_IMAGE_URI
block|,
DECL|enumerator|PROP_IMAGE_MTIME
name|PROP_IMAGE_MTIME
block|,
DECL|enumerator|PROP_IMAGE_FILESIZE
name|PROP_IMAGE_FILESIZE
block|,
DECL|enumerator|PROP_IMAGE_MIMETYPE
name|PROP_IMAGE_MIMETYPE
block|,
DECL|enumerator|PROP_IMAGE_WIDTH
name|PROP_IMAGE_WIDTH
block|,
DECL|enumerator|PROP_IMAGE_HEIGHT
name|PROP_IMAGE_HEIGHT
block|,
DECL|enumerator|PROP_IMAGE_TYPE
name|PROP_IMAGE_TYPE
block|,
DECL|enumerator|PROP_IMAGE_NUM_LAYERS
name|PROP_IMAGE_NUM_LAYERS
block|,
DECL|enumerator|PROP_THUMB_STATE
name|PROP_THUMB_STATE
block|}
enum|;
end_enum

begin_function_decl
specifier|static
name|void
name|gimp_thumbnail_finalize
parameter_list|(
name|GObject
modifier|*
name|object
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_thumbnail_set_property
parameter_list|(
name|GObject
modifier|*
name|object
parameter_list|,
name|guint
name|property_id
parameter_list|,
specifier|const
name|GValue
modifier|*
name|value
parameter_list|,
name|GParamSpec
modifier|*
name|pspec
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_thumbnail_get_property
parameter_list|(
name|GObject
modifier|*
name|object
parameter_list|,
name|guint
name|property_id
parameter_list|,
name|GValue
modifier|*
name|value
parameter_list|,
name|GParamSpec
modifier|*
name|pspec
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_thumbnail_reset_info
parameter_list|(
name|GimpThumbnail
modifier|*
name|thumbnail
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_thumbnail_update_image
parameter_list|(
name|GimpThumbnail
modifier|*
name|thumbnail
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_thumbnail_update_thumb
parameter_list|(
name|GimpThumbnail
modifier|*
name|thumbnail
parameter_list|,
name|GimpThumbSize
name|size
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|gboolean
name|gimp_thumbnail_save
parameter_list|(
name|GimpThumbnail
modifier|*
name|thumbnail
parameter_list|,
name|GimpThumbSize
name|size
parameter_list|,
specifier|const
name|gchar
modifier|*
name|filename
parameter_list|,
name|GdkPixbuf
modifier|*
name|pixbuf
parameter_list|,
specifier|const
name|gchar
modifier|*
name|software
parameter_list|,
name|GError
modifier|*
modifier|*
name|error
parameter_list|)
function_decl|;
end_function_decl

begin_ifdef
ifdef|#
directive|ifdef
name|GIMP_THUMB_DEBUG
end_ifdef

begin_function_decl
specifier|static
name|void
name|gimp_thumbnail_debug_notify
parameter_list|(
name|GObject
modifier|*
name|object
parameter_list|,
name|GParamSpec
modifier|*
name|pspec
parameter_list|)
function_decl|;
end_function_decl

begin_endif
endif|#
directive|endif
end_endif

begin_macro
DECL|function|G_DEFINE_TYPE (GimpThumbnail,gimp_thumbnail,G_TYPE_OBJECT)
name|G_DEFINE_TYPE
argument_list|(
argument|GimpThumbnail
argument_list|,
argument|gimp_thumbnail
argument_list|,
argument|G_TYPE_OBJECT
argument_list|)
end_macro

begin_define
DECL|macro|parent_class
define|#
directive|define
name|parent_class
value|gimp_thumbnail_parent_class
end_define

begin_function
specifier|static
name|void
name|gimp_thumbnail_class_init
parameter_list|(
name|GimpThumbnailClass
modifier|*
name|klass
parameter_list|)
block|{
name|GObjectClass
modifier|*
name|object_class
init|=
name|G_OBJECT_CLASS
argument_list|(
name|klass
argument_list|)
decl_stmt|;
name|object_class
operator|->
name|finalize
operator|=
name|gimp_thumbnail_finalize
expr_stmt|;
name|object_class
operator|->
name|set_property
operator|=
name|gimp_thumbnail_set_property
expr_stmt|;
name|object_class
operator|->
name|get_property
operator|=
name|gimp_thumbnail_get_property
expr_stmt|;
name|g_object_class_install_property
argument_list|(
name|object_class
argument_list|,
name|PROP_IMAGE_STATE
argument_list|,
name|g_param_spec_enum
argument_list|(
literal|"image-state"
argument_list|,
name|NULL
argument_list|,
literal|"State of the image associated to the thumbnail object"
argument_list|,
name|GIMP_TYPE_THUMB_STATE
argument_list|,
name|GIMP_THUMB_STATE_UNKNOWN
argument_list|,
name|GIMP_PARAM_READWRITE
argument_list|)
argument_list|)
expr_stmt|;
name|g_object_class_install_property
argument_list|(
name|object_class
argument_list|,
name|PROP_IMAGE_URI
argument_list|,
name|g_param_spec_string
argument_list|(
literal|"image-uri"
argument_list|,
name|NULL
argument_list|,
literal|"URI of the image file"
argument_list|,
name|NULL
argument_list|,
name|GIMP_PARAM_READWRITE
argument_list|)
argument_list|)
expr_stmt|;
name|g_object_class_install_property
argument_list|(
name|object_class
argument_list|,
name|PROP_IMAGE_MTIME
argument_list|,
name|g_param_spec_int64
argument_list|(
literal|"image-mtime"
argument_list|,
name|NULL
argument_list|,
literal|"Modification time of the image file in seconds since the Epoch"
argument_list|,
literal|0
argument_list|,
name|G_MAXINT64
argument_list|,
literal|0
argument_list|,
name|GIMP_PARAM_READWRITE
argument_list|)
argument_list|)
expr_stmt|;
name|g_object_class_install_property
argument_list|(
name|object_class
argument_list|,
name|PROP_IMAGE_FILESIZE
argument_list|,
name|g_param_spec_int64
argument_list|(
literal|"image-filesize"
argument_list|,
name|NULL
argument_list|,
literal|"Size of the image file in bytes"
argument_list|,
literal|0
argument_list|,
name|G_MAXINT64
argument_list|,
literal|0
argument_list|,
name|GIMP_PARAM_READWRITE
argument_list|)
argument_list|)
expr_stmt|;
comment|/**    * GimpThumbnail::image-mimetype:    *    * Since: GIMP 2.2    **/
name|g_object_class_install_property
argument_list|(
name|object_class
argument_list|,
name|PROP_IMAGE_MIMETYPE
argument_list|,
name|g_param_spec_string
argument_list|(
literal|"image-mimetype"
argument_list|,
name|NULL
argument_list|,
literal|"Image mimetype"
argument_list|,
name|NULL
argument_list|,
name|GIMP_PARAM_READWRITE
argument_list|)
argument_list|)
expr_stmt|;
name|g_object_class_install_property
argument_list|(
name|object_class
argument_list|,
name|PROP_IMAGE_WIDTH
argument_list|,
name|g_param_spec_int
argument_list|(
literal|"image-width"
argument_list|,
name|NULL
argument_list|,
literal|"Width of the image in pixels"
argument_list|,
literal|0
argument_list|,
name|G_MAXINT
argument_list|,
literal|0
argument_list|,
name|GIMP_PARAM_READWRITE
argument_list|)
argument_list|)
expr_stmt|;
name|g_object_class_install_property
argument_list|(
name|object_class
argument_list|,
name|PROP_IMAGE_HEIGHT
argument_list|,
name|g_param_spec_int
argument_list|(
literal|"image-height"
argument_list|,
name|NULL
argument_list|,
literal|"Height of the image in pixels"
argument_list|,
literal|0
argument_list|,
name|G_MAXINT
argument_list|,
literal|0
argument_list|,
name|GIMP_PARAM_READWRITE
argument_list|)
argument_list|)
expr_stmt|;
name|g_object_class_install_property
argument_list|(
name|object_class
argument_list|,
name|PROP_IMAGE_TYPE
argument_list|,
name|g_param_spec_string
argument_list|(
literal|"image-type"
argument_list|,
name|NULL
argument_list|,
literal|"String describing the type of the image format"
argument_list|,
name|NULL
argument_list|,
name|GIMP_PARAM_READWRITE
argument_list|)
argument_list|)
expr_stmt|;
name|g_object_class_install_property
argument_list|(
name|object_class
argument_list|,
name|PROP_IMAGE_NUM_LAYERS
argument_list|,
name|g_param_spec_int
argument_list|(
literal|"image-num-layers"
argument_list|,
name|NULL
argument_list|,
literal|"The number of layers in the image"
argument_list|,
literal|0
argument_list|,
name|G_MAXINT
argument_list|,
literal|0
argument_list|,
name|GIMP_PARAM_READWRITE
argument_list|)
argument_list|)
expr_stmt|;
name|g_object_class_install_property
argument_list|(
name|object_class
argument_list|,
name|PROP_THUMB_STATE
argument_list|,
name|g_param_spec_enum
argument_list|(
literal|"thumb-state"
argument_list|,
name|NULL
argument_list|,
literal|"State of the thumbnail file"
argument_list|,
name|GIMP_TYPE_THUMB_STATE
argument_list|,
name|GIMP_THUMB_STATE_UNKNOWN
argument_list|,
name|GIMP_PARAM_READWRITE
argument_list|)
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_thumbnail_init (GimpThumbnail * thumbnail)
name|gimp_thumbnail_init
parameter_list|(
name|GimpThumbnail
modifier|*
name|thumbnail
parameter_list|)
block|{
name|thumbnail
operator|->
name|image_state
operator|=
name|GIMP_THUMB_STATE_UNKNOWN
expr_stmt|;
name|thumbnail
operator|->
name|image_uri
operator|=
name|NULL
expr_stmt|;
name|thumbnail
operator|->
name|image_filename
operator|=
name|NULL
expr_stmt|;
name|thumbnail
operator|->
name|image_mtime
operator|=
literal|0
expr_stmt|;
name|thumbnail
operator|->
name|image_filesize
operator|=
literal|0
expr_stmt|;
name|thumbnail
operator|->
name|image_mimetype
operator|=
name|NULL
expr_stmt|;
name|thumbnail
operator|->
name|image_width
operator|=
literal|0
expr_stmt|;
name|thumbnail
operator|->
name|image_height
operator|=
literal|0
expr_stmt|;
name|thumbnail
operator|->
name|image_type
operator|=
name|NULL
expr_stmt|;
name|thumbnail
operator|->
name|image_num_layers
operator|=
literal|0
expr_stmt|;
name|thumbnail
operator|->
name|thumb_state
operator|=
name|GIMP_THUMB_STATE_UNKNOWN
expr_stmt|;
name|thumbnail
operator|->
name|thumb_size
operator|=
operator|-
literal|1
expr_stmt|;
name|thumbnail
operator|->
name|thumb_filename
operator|=
name|NULL
expr_stmt|;
name|thumbnail
operator|->
name|thumb_mtime
operator|=
literal|0
expr_stmt|;
name|thumbnail
operator|->
name|thumb_filesize
operator|=
literal|0
expr_stmt|;
ifdef|#
directive|ifdef
name|GIMP_THUMB_DEBUG
name|g_signal_connect
argument_list|(
name|thumbnail
argument_list|,
literal|"notify"
argument_list|,
name|G_CALLBACK
argument_list|(
name|gimp_thumbnail_debug_notify
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
endif|#
directive|endif
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_thumbnail_finalize (GObject * object)
name|gimp_thumbnail_finalize
parameter_list|(
name|GObject
modifier|*
name|object
parameter_list|)
block|{
name|GimpThumbnail
modifier|*
name|thumbnail
init|=
name|GIMP_THUMBNAIL
argument_list|(
name|object
argument_list|)
decl_stmt|;
if|if
condition|(
name|thumbnail
operator|->
name|image_uri
condition|)
block|{
name|g_free
argument_list|(
name|thumbnail
operator|->
name|image_uri
argument_list|)
expr_stmt|;
name|thumbnail
operator|->
name|image_uri
operator|=
name|NULL
expr_stmt|;
block|}
if|if
condition|(
name|thumbnail
operator|->
name|image_filename
condition|)
block|{
name|g_free
argument_list|(
name|thumbnail
operator|->
name|image_filename
argument_list|)
expr_stmt|;
name|thumbnail
operator|->
name|image_filename
operator|=
name|NULL
expr_stmt|;
block|}
if|if
condition|(
name|thumbnail
operator|->
name|image_mimetype
condition|)
block|{
name|g_free
argument_list|(
name|thumbnail
operator|->
name|image_mimetype
argument_list|)
expr_stmt|;
name|thumbnail
operator|->
name|image_mimetype
operator|=
name|NULL
expr_stmt|;
block|}
if|if
condition|(
name|thumbnail
operator|->
name|image_type
condition|)
block|{
name|g_free
argument_list|(
name|thumbnail
operator|->
name|image_type
argument_list|)
expr_stmt|;
name|thumbnail
operator|->
name|image_type
operator|=
name|NULL
expr_stmt|;
block|}
if|if
condition|(
name|thumbnail
operator|->
name|thumb_filename
condition|)
block|{
name|g_free
argument_list|(
name|thumbnail
operator|->
name|thumb_filename
argument_list|)
expr_stmt|;
name|thumbnail
operator|->
name|thumb_filename
operator|=
name|NULL
expr_stmt|;
block|}
name|G_OBJECT_CLASS
argument_list|(
name|parent_class
argument_list|)
operator|->
name|finalize
argument_list|(
name|object
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_thumbnail_set_property (GObject * object,guint property_id,const GValue * value,GParamSpec * pspec)
name|gimp_thumbnail_set_property
parameter_list|(
name|GObject
modifier|*
name|object
parameter_list|,
name|guint
name|property_id
parameter_list|,
specifier|const
name|GValue
modifier|*
name|value
parameter_list|,
name|GParamSpec
modifier|*
name|pspec
parameter_list|)
block|{
name|GimpThumbnail
modifier|*
name|thumbnail
init|=
name|GIMP_THUMBNAIL
argument_list|(
name|object
argument_list|)
decl_stmt|;
switch|switch
condition|(
name|property_id
condition|)
block|{
case|case
name|PROP_IMAGE_STATE
case|:
name|thumbnail
operator|->
name|image_state
operator|=
name|g_value_get_enum
argument_list|(
name|value
argument_list|)
expr_stmt|;
break|break;
case|case
name|PROP_IMAGE_URI
case|:
name|gimp_thumbnail_set_uri
argument_list|(
name|GIMP_THUMBNAIL
argument_list|(
name|object
argument_list|)
argument_list|,
name|g_value_get_string
argument_list|(
name|value
argument_list|)
argument_list|)
expr_stmt|;
break|break;
case|case
name|PROP_IMAGE_MTIME
case|:
name|thumbnail
operator|->
name|image_mtime
operator|=
name|g_value_get_int64
argument_list|(
name|value
argument_list|)
expr_stmt|;
break|break;
case|case
name|PROP_IMAGE_FILESIZE
case|:
name|thumbnail
operator|->
name|image_filesize
operator|=
name|g_value_get_int64
argument_list|(
name|value
argument_list|)
expr_stmt|;
break|break;
case|case
name|PROP_IMAGE_MIMETYPE
case|:
name|g_free
argument_list|(
name|thumbnail
operator|->
name|image_mimetype
argument_list|)
expr_stmt|;
name|thumbnail
operator|->
name|image_mimetype
operator|=
name|g_value_dup_string
argument_list|(
name|value
argument_list|)
expr_stmt|;
break|break;
case|case
name|PROP_IMAGE_WIDTH
case|:
name|thumbnail
operator|->
name|image_width
operator|=
name|g_value_get_int
argument_list|(
name|value
argument_list|)
expr_stmt|;
break|break;
case|case
name|PROP_IMAGE_HEIGHT
case|:
name|thumbnail
operator|->
name|image_height
operator|=
name|g_value_get_int
argument_list|(
name|value
argument_list|)
expr_stmt|;
break|break;
case|case
name|PROP_IMAGE_TYPE
case|:
name|g_free
argument_list|(
name|thumbnail
operator|->
name|image_type
argument_list|)
expr_stmt|;
name|thumbnail
operator|->
name|image_type
operator|=
name|g_value_dup_string
argument_list|(
name|value
argument_list|)
expr_stmt|;
break|break;
case|case
name|PROP_IMAGE_NUM_LAYERS
case|:
name|thumbnail
operator|->
name|image_num_layers
operator|=
name|g_value_get_int
argument_list|(
name|value
argument_list|)
expr_stmt|;
break|break;
case|case
name|PROP_THUMB_STATE
case|:
name|thumbnail
operator|->
name|thumb_state
operator|=
name|g_value_get_enum
argument_list|(
name|value
argument_list|)
expr_stmt|;
break|break;
default|default:
name|G_OBJECT_WARN_INVALID_PROPERTY_ID
argument_list|(
name|object
argument_list|,
name|property_id
argument_list|,
name|pspec
argument_list|)
expr_stmt|;
break|break;
block|}
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_thumbnail_get_property (GObject * object,guint property_id,GValue * value,GParamSpec * pspec)
name|gimp_thumbnail_get_property
parameter_list|(
name|GObject
modifier|*
name|object
parameter_list|,
name|guint
name|property_id
parameter_list|,
name|GValue
modifier|*
name|value
parameter_list|,
name|GParamSpec
modifier|*
name|pspec
parameter_list|)
block|{
name|GimpThumbnail
modifier|*
name|thumbnail
init|=
name|GIMP_THUMBNAIL
argument_list|(
name|object
argument_list|)
decl_stmt|;
switch|switch
condition|(
name|property_id
condition|)
block|{
case|case
name|PROP_IMAGE_STATE
case|:
name|g_value_set_enum
argument_list|(
name|value
argument_list|,
name|thumbnail
operator|->
name|image_state
argument_list|)
expr_stmt|;
break|break;
case|case
name|PROP_IMAGE_URI
case|:
name|g_value_set_string
argument_list|(
name|value
argument_list|,
name|thumbnail
operator|->
name|image_uri
argument_list|)
expr_stmt|;
break|break;
case|case
name|PROP_IMAGE_MTIME
case|:
name|g_value_set_int64
argument_list|(
name|value
argument_list|,
name|thumbnail
operator|->
name|image_mtime
argument_list|)
expr_stmt|;
break|break;
case|case
name|PROP_IMAGE_FILESIZE
case|:
name|g_value_set_int64
argument_list|(
name|value
argument_list|,
name|thumbnail
operator|->
name|image_filesize
argument_list|)
expr_stmt|;
break|break;
case|case
name|PROP_IMAGE_MIMETYPE
case|:
name|g_value_set_string
argument_list|(
name|value
argument_list|,
name|thumbnail
operator|->
name|image_mimetype
argument_list|)
expr_stmt|;
break|break;
case|case
name|PROP_IMAGE_WIDTH
case|:
name|g_value_set_int
argument_list|(
name|value
argument_list|,
name|thumbnail
operator|->
name|image_width
argument_list|)
expr_stmt|;
break|break;
case|case
name|PROP_IMAGE_HEIGHT
case|:
name|g_value_set_int
argument_list|(
name|value
argument_list|,
name|thumbnail
operator|->
name|image_height
argument_list|)
expr_stmt|;
break|break;
case|case
name|PROP_IMAGE_TYPE
case|:
name|g_value_set_string
argument_list|(
name|value
argument_list|,
name|thumbnail
operator|->
name|image_type
argument_list|)
expr_stmt|;
break|break;
case|case
name|PROP_IMAGE_NUM_LAYERS
case|:
name|g_value_set_int
argument_list|(
name|value
argument_list|,
name|thumbnail
operator|->
name|image_num_layers
argument_list|)
expr_stmt|;
break|break;
case|case
name|PROP_THUMB_STATE
case|:
name|g_value_set_enum
argument_list|(
name|value
argument_list|,
name|thumbnail
operator|->
name|thumb_state
argument_list|)
expr_stmt|;
break|break;
default|default:
name|G_OBJECT_WARN_INVALID_PROPERTY_ID
argument_list|(
name|object
argument_list|,
name|property_id
argument_list|,
name|pspec
argument_list|)
expr_stmt|;
break|break;
block|}
block|}
end_function

begin_comment
comment|/**  * gimp_thumbnail_new:  *  * Creates a new #GimpThumbnail object.  *  * Return value: a newly allocated GimpThumbnail object  **/
end_comment

begin_function
name|GimpThumbnail
modifier|*
DECL|function|gimp_thumbnail_new (void)
name|gimp_thumbnail_new
parameter_list|(
name|void
parameter_list|)
block|{
return|return
name|g_object_new
argument_list|(
name|GIMP_TYPE_THUMBNAIL
argument_list|,
name|NULL
argument_list|)
return|;
block|}
end_function

begin_comment
comment|/**  * gimp_thumbnail_set_uri:  * @thumbnail: a #GimpThumbnail object  * @uri: an escaped URI  *  * Sets the location of the image file associated with the #thumbnail.  *  * All informations stored in the #GimpThumbnail are reset.  **/
end_comment

begin_function
name|void
DECL|function|gimp_thumbnail_set_uri (GimpThumbnail * thumbnail,const gchar * uri)
name|gimp_thumbnail_set_uri
parameter_list|(
name|GimpThumbnail
modifier|*
name|thumbnail
parameter_list|,
specifier|const
name|gchar
modifier|*
name|uri
parameter_list|)
block|{
name|g_return_if_fail
argument_list|(
name|GIMP_IS_THUMBNAIL
argument_list|(
name|thumbnail
argument_list|)
argument_list|)
expr_stmt|;
name|GIMP_THUMB_DEBUG_CALL
argument_list|(
name|thumbnail
argument_list|)
expr_stmt|;
if|if
condition|(
name|thumbnail
operator|->
name|image_uri
condition|)
name|g_free
argument_list|(
name|thumbnail
operator|->
name|image_uri
argument_list|)
expr_stmt|;
name|thumbnail
operator|->
name|image_uri
operator|=
name|g_strdup
argument_list|(
name|uri
argument_list|)
expr_stmt|;
if|if
condition|(
name|thumbnail
operator|->
name|image_filename
condition|)
block|{
name|g_free
argument_list|(
name|thumbnail
operator|->
name|image_filename
argument_list|)
expr_stmt|;
name|thumbnail
operator|->
name|image_filename
operator|=
name|NULL
expr_stmt|;
block|}
if|if
condition|(
name|thumbnail
operator|->
name|thumb_filename
condition|)
block|{
name|g_free
argument_list|(
name|thumbnail
operator|->
name|thumb_filename
argument_list|)
expr_stmt|;
name|thumbnail
operator|->
name|thumb_filename
operator|=
name|NULL
expr_stmt|;
block|}
name|thumbnail
operator|->
name|thumb_size
operator|=
operator|-
literal|1
expr_stmt|;
name|thumbnail
operator|->
name|thumb_filesize
operator|=
literal|0
expr_stmt|;
name|thumbnail
operator|->
name|thumb_mtime
operator|=
literal|0
expr_stmt|;
name|g_object_set
argument_list|(
name|thumbnail
argument_list|,
literal|"image-state"
argument_list|,
name|GIMP_THUMB_STATE_UNKNOWN
argument_list|,
literal|"image-filesize"
argument_list|,
operator|(
name|gint64
operator|)
literal|0
argument_list|,
literal|"image-mtime"
argument_list|,
operator|(
name|gint64
operator|)
literal|0
argument_list|,
literal|"image-mimetype"
argument_list|,
name|NULL
argument_list|,
literal|"image-width"
argument_list|,
literal|0
argument_list|,
literal|"image-height"
argument_list|,
literal|0
argument_list|,
literal|"image-type"
argument_list|,
name|NULL
argument_list|,
literal|"image-num-layers"
argument_list|,
literal|0
argument_list|,
literal|"thumb-state"
argument_list|,
name|GIMP_THUMB_STATE_UNKNOWN
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/**  * gimp_thumbnail_set_filename:  * @thumbnail: a #GimpThumbnail object  * @filename: a local filename in the encoding of the filesystem  * @error: return location for possible errors  *  * Sets the location of the image file associated with the #thumbnail.  *  * Return value: %TRUE if the filename was successfully set,  *               %FALSE otherwise  **/
end_comment

begin_function
name|gboolean
DECL|function|gimp_thumbnail_set_filename (GimpThumbnail * thumbnail,const gchar * filename,GError ** error)
name|gimp_thumbnail_set_filename
parameter_list|(
name|GimpThumbnail
modifier|*
name|thumbnail
parameter_list|,
specifier|const
name|gchar
modifier|*
name|filename
parameter_list|,
name|GError
modifier|*
modifier|*
name|error
parameter_list|)
block|{
name|gchar
modifier|*
name|uri
init|=
name|NULL
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_THUMBNAIL
argument_list|(
name|thumbnail
argument_list|)
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
name|error
operator|==
name|NULL
operator|||
operator|*
name|error
operator|==
name|NULL
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|GIMP_THUMB_DEBUG_CALL
argument_list|(
name|thumbnail
argument_list|)
expr_stmt|;
if|if
condition|(
name|filename
condition|)
name|uri
operator|=
name|g_filename_to_uri
argument_list|(
name|filename
argument_list|,
name|NULL
argument_list|,
name|error
argument_list|)
expr_stmt|;
name|gimp_thumbnail_set_uri
argument_list|(
name|thumbnail
argument_list|,
name|uri
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|uri
argument_list|)
expr_stmt|;
return|return
operator|(
operator|!
name|filename
operator|||
name|uri
operator|)
return|;
block|}
end_function

begin_comment
comment|/**  * gimp_thumbnail_set_from_thumb:  * @thumbnail: a #GimpThumbnail object  * @filename: filename of a local thumbnail file  * @error: return location for possible errors  *  * This function tries to load the thumbnail file pointed to by  * @filename and retrieves the URI of the original image file from  * it. This allows you to find the image file associated with a  * thumbnail file.  *  * This will only work with thumbnails from the global thumbnail  * directory that contain a valid Thumb::URI tag.  *  * Return value: %TRUE if the pixbuf could be loaded, %FALSE otherwise  **/
end_comment

begin_function
name|gboolean
DECL|function|gimp_thumbnail_set_from_thumb (GimpThumbnail * thumbnail,const gchar * filename,GError ** error)
name|gimp_thumbnail_set_from_thumb
parameter_list|(
name|GimpThumbnail
modifier|*
name|thumbnail
parameter_list|,
specifier|const
name|gchar
modifier|*
name|filename
parameter_list|,
name|GError
modifier|*
modifier|*
name|error
parameter_list|)
block|{
name|GdkPixbuf
modifier|*
name|pixbuf
decl_stmt|;
specifier|const
name|gchar
modifier|*
name|uri
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_THUMBNAIL
argument_list|(
name|thumbnail
argument_list|)
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
name|filename
operator|!=
name|NULL
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
name|error
operator|==
name|NULL
operator|||
operator|*
name|error
operator|==
name|NULL
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|GIMP_THUMB_DEBUG_CALL
argument_list|(
name|thumbnail
argument_list|)
expr_stmt|;
name|pixbuf
operator|=
name|gdk_pixbuf_new_from_file
argument_list|(
name|filename
argument_list|,
name|error
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|pixbuf
condition|)
return|return
name|FALSE
return|;
name|uri
operator|=
name|gdk_pixbuf_get_option
argument_list|(
name|pixbuf
argument_list|,
name|TAG_THUMB_URI
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|uri
condition|)
block|{
name|g_set_error
argument_list|(
name|error
argument_list|,
name|GIMP_THUMB_ERROR
argument_list|,
literal|0
argument_list|,
name|_
argument_list|(
literal|"Thumbnail contains no Thumb::URI tag"
argument_list|)
argument_list|)
expr_stmt|;
name|g_object_unref
argument_list|(
name|pixbuf
argument_list|)
expr_stmt|;
return|return
name|FALSE
return|;
block|}
name|gimp_thumbnail_set_uri
argument_list|(
name|thumbnail
argument_list|,
name|uri
argument_list|)
expr_stmt|;
name|g_object_unref
argument_list|(
name|pixbuf
argument_list|)
expr_stmt|;
return|return
name|TRUE
return|;
block|}
end_function

begin_comment
comment|/**  * gimp_thumbnail_peek_image:  * @thumbnail: a #GimpThumbnail object  *  * Checks the image file associated with the @thumbnail and updates  * information such as state, filesize and modification time.  *  * Return value: the image's #GimpThumbState after the update  **/
end_comment

begin_function
name|GimpThumbState
DECL|function|gimp_thumbnail_peek_image (GimpThumbnail * thumbnail)
name|gimp_thumbnail_peek_image
parameter_list|(
name|GimpThumbnail
modifier|*
name|thumbnail
parameter_list|)
block|{
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_THUMBNAIL
argument_list|(
name|thumbnail
argument_list|)
argument_list|,
name|GIMP_THUMB_STATE_UNKNOWN
argument_list|)
expr_stmt|;
name|GIMP_THUMB_DEBUG_CALL
argument_list|(
name|thumbnail
argument_list|)
expr_stmt|;
name|g_object_freeze_notify
argument_list|(
name|G_OBJECT
argument_list|(
name|thumbnail
argument_list|)
argument_list|)
expr_stmt|;
name|gimp_thumbnail_update_image
argument_list|(
name|thumbnail
argument_list|)
expr_stmt|;
name|g_object_thaw_notify
argument_list|(
name|G_OBJECT
argument_list|(
name|thumbnail
argument_list|)
argument_list|)
expr_stmt|;
return|return
name|thumbnail
operator|->
name|image_state
return|;
block|}
end_function

begin_comment
comment|/**  * gimp_thumbnail_peek_thumb:  * @thumbnail: a #GimpThumbnail object  * @size: the preferred size of the thumbnail image  *  * Checks if a thumbnail file for the @thumbnail exists. It doesn't  * load the thumbnail image and thus cannot check if the thumbnail is  * valid and uptodate for the image file asosciated with the  * @thumbnail.  *  * If you want to check the thumbnail, either attempt to load it using  * gimp_thumbnail_load_thumb(), or, if you don't need the resulting  * thumbnail pixbuf, use gimp_thumbnail_check_thumb().  *  * Return value: the thumbnail's #GimpThumbState after the update  **/
end_comment

begin_function
name|GimpThumbState
DECL|function|gimp_thumbnail_peek_thumb (GimpThumbnail * thumbnail,GimpThumbSize size)
name|gimp_thumbnail_peek_thumb
parameter_list|(
name|GimpThumbnail
modifier|*
name|thumbnail
parameter_list|,
name|GimpThumbSize
name|size
parameter_list|)
block|{
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_THUMBNAIL
argument_list|(
name|thumbnail
argument_list|)
argument_list|,
name|GIMP_THUMB_STATE_UNKNOWN
argument_list|)
expr_stmt|;
name|GIMP_THUMB_DEBUG_CALL
argument_list|(
name|thumbnail
argument_list|)
expr_stmt|;
name|g_object_freeze_notify
argument_list|(
name|G_OBJECT
argument_list|(
name|thumbnail
argument_list|)
argument_list|)
expr_stmt|;
name|gimp_thumbnail_update_image
argument_list|(
name|thumbnail
argument_list|)
expr_stmt|;
name|gimp_thumbnail_update_thumb
argument_list|(
name|thumbnail
argument_list|,
name|size
argument_list|)
expr_stmt|;
name|g_object_thaw_notify
argument_list|(
name|G_OBJECT
argument_list|(
name|thumbnail
argument_list|)
argument_list|)
expr_stmt|;
return|return
name|thumbnail
operator|->
name|thumb_state
return|;
block|}
end_function

begin_comment
comment|/**  * gimp_thumbnail_check_thumb:  * @thumbnail: a #GimpThumbnail object  * @size: the preferred size of the thumbnail image  *  * Checks if a thumbnail file for the @thumbnail exists, loads it and  * verifies it is valid and uptodate for the image file asosciated  * with the @thumbnail.  *  * Return value: the thumbnail's #GimpThumbState after the update  *  * Since: GIMP 2.2  **/
end_comment

begin_function
name|GimpThumbState
DECL|function|gimp_thumbnail_check_thumb (GimpThumbnail * thumbnail,GimpThumbSize size)
name|gimp_thumbnail_check_thumb
parameter_list|(
name|GimpThumbnail
modifier|*
name|thumbnail
parameter_list|,
name|GimpThumbSize
name|size
parameter_list|)
block|{
name|GdkPixbuf
modifier|*
name|pixbuf
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_THUMBNAIL
argument_list|(
name|thumbnail
argument_list|)
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|GIMP_THUMB_DEBUG_CALL
argument_list|(
name|thumbnail
argument_list|)
expr_stmt|;
if|if
condition|(
name|gimp_thumbnail_peek_thumb
argument_list|(
name|thumbnail
argument_list|,
name|size
argument_list|)
operator|==
name|GIMP_THUMB_STATE_OK
condition|)
return|return
name|GIMP_THUMB_STATE_OK
return|;
name|pixbuf
operator|=
name|gimp_thumbnail_load_thumb
argument_list|(
name|thumbnail
argument_list|,
name|size
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
if|if
condition|(
name|pixbuf
condition|)
name|g_object_unref
argument_list|(
name|pixbuf
argument_list|)
expr_stmt|;
return|return
name|thumbnail
operator|->
name|thumb_state
return|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_thumbnail_update_image (GimpThumbnail * thumbnail)
name|gimp_thumbnail_update_image
parameter_list|(
name|GimpThumbnail
modifier|*
name|thumbnail
parameter_list|)
block|{
name|GimpThumbState
name|state
decl_stmt|;
name|gint64
name|mtime
init|=
literal|0
decl_stmt|;
name|gint64
name|filesize
init|=
literal|0
decl_stmt|;
if|if
condition|(
operator|!
name|thumbnail
operator|->
name|image_uri
condition|)
return|return;
name|state
operator|=
name|thumbnail
operator|->
name|image_state
expr_stmt|;
switch|switch
condition|(
name|state
condition|)
block|{
case|case
name|GIMP_THUMB_STATE_UNKNOWN
case|:
name|g_return_if_fail
argument_list|(
name|thumbnail
operator|->
name|image_filename
operator|==
name|NULL
argument_list|)
expr_stmt|;
name|thumbnail
operator|->
name|image_filename
operator|=
name|_gimp_thumb_filename_from_uri
argument_list|(
name|thumbnail
operator|->
name|image_uri
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|thumbnail
operator|->
name|image_filename
condition|)
name|state
operator|=
name|GIMP_THUMB_STATE_REMOTE
expr_stmt|;
break|break;
case|case
name|GIMP_THUMB_STATE_REMOTE
case|:
break|break;
default|default:
name|g_return_if_fail
argument_list|(
name|thumbnail
operator|->
name|image_filename
operator|!=
name|NULL
argument_list|)
expr_stmt|;
break|break;
block|}
switch|switch
condition|(
name|state
condition|)
block|{
case|case
name|GIMP_THUMB_STATE_REMOTE
case|:
break|break;
default|default:
switch|switch
condition|(
name|gimp_thumb_file_test
argument_list|(
name|thumbnail
operator|->
name|image_filename
argument_list|,
operator|&
name|mtime
argument_list|,
operator|&
name|filesize
argument_list|,
operator|&
name|thumbnail
operator|->
name|image_not_found_errno
argument_list|)
condition|)
block|{
case|case
name|GIMP_THUMB_FILE_TYPE_REGULAR
case|:
name|state
operator|=
name|GIMP_THUMB_STATE_EXISTS
expr_stmt|;
break|break;
case|case
name|GIMP_THUMB_FILE_TYPE_FOLDER
case|:
name|state
operator|=
name|GIMP_THUMB_STATE_FOLDER
expr_stmt|;
break|break;
case|case
name|GIMP_THUMB_FILE_TYPE_SPECIAL
case|:
name|state
operator|=
name|GIMP_THUMB_STATE_SPECIAL
expr_stmt|;
break|break;
default|default:
name|state
operator|=
name|GIMP_THUMB_STATE_NOT_FOUND
expr_stmt|;
break|break;
block|}
break|break;
block|}
if|if
condition|(
name|state
operator|!=
name|thumbnail
operator|->
name|image_state
condition|)
block|{
name|g_object_set
argument_list|(
name|thumbnail
argument_list|,
literal|"image-state"
argument_list|,
name|state
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|mtime
operator|!=
name|thumbnail
operator|->
name|image_mtime
operator|||
name|filesize
operator|!=
name|thumbnail
operator|->
name|image_filesize
condition|)
block|{
name|g_object_set
argument_list|(
name|thumbnail
argument_list|,
literal|"image-mtime"
argument_list|,
name|mtime
argument_list|,
literal|"image-filesize"
argument_list|,
name|filesize
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
if|if
condition|(
name|thumbnail
operator|->
name|thumb_state
operator|==
name|GIMP_THUMB_STATE_OK
condition|)
name|g_object_set
argument_list|(
name|thumbnail
argument_list|,
literal|"thumb-state"
argument_list|,
name|GIMP_THUMB_STATE_OLD
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_thumbnail_update_thumb (GimpThumbnail * thumbnail,GimpThumbSize size)
name|gimp_thumbnail_update_thumb
parameter_list|(
name|GimpThumbnail
modifier|*
name|thumbnail
parameter_list|,
name|GimpThumbSize
name|size
parameter_list|)
block|{
name|gchar
modifier|*
name|filename
decl_stmt|;
name|GimpThumbState
name|state
decl_stmt|;
name|gint64
name|filesize
init|=
literal|0
decl_stmt|;
name|gint64
name|mtime
init|=
literal|0
decl_stmt|;
if|if
condition|(
operator|!
name|thumbnail
operator|->
name|image_uri
condition|)
return|return;
name|state
operator|=
name|thumbnail
operator|->
name|thumb_state
expr_stmt|;
name|filename
operator|=
name|gimp_thumb_find_thumb
argument_list|(
name|thumbnail
operator|->
name|image_uri
argument_list|,
operator|&
name|size
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|filename
condition|)
name|state
operator|=
name|GIMP_THUMB_STATE_NOT_FOUND
expr_stmt|;
switch|switch
condition|(
name|state
condition|)
block|{
case|case
name|GIMP_THUMB_STATE_EXISTS
case|:
case|case
name|GIMP_THUMB_STATE_OLD
case|:
case|case
name|GIMP_THUMB_STATE_FAILED
case|:
case|case
name|GIMP_THUMB_STATE_OK
case|:
name|g_return_if_fail
argument_list|(
name|thumbnail
operator|->
name|thumb_filename
operator|!=
name|NULL
argument_list|)
expr_stmt|;
if|if
condition|(
name|thumbnail
operator|->
name|thumb_size
operator|==
name|size
operator|&&
name|thumbnail
operator|->
name|thumb_filesize
operator|==
name|filesize
operator|&&
name|thumbnail
operator|->
name|thumb_mtime
operator|==
name|mtime
condition|)
block|{
name|g_free
argument_list|(
name|filename
argument_list|)
expr_stmt|;
return|return;
block|}
break|break;
default|default:
break|break;
block|}
if|if
condition|(
name|thumbnail
operator|->
name|thumb_filename
condition|)
name|g_free
argument_list|(
name|thumbnail
operator|->
name|thumb_filename
argument_list|)
expr_stmt|;
name|thumbnail
operator|->
name|thumb_filename
operator|=
name|filename
expr_stmt|;
if|if
condition|(
name|filename
condition|)
name|state
operator|=
operator|(
name|size
operator|>
name|GIMP_THUMB_SIZE_FAIL
condition|?
name|GIMP_THUMB_STATE_EXISTS
else|:
name|GIMP_THUMB_STATE_FAILED
operator|)
expr_stmt|;
name|thumbnail
operator|->
name|thumb_size
operator|=
name|size
expr_stmt|;
name|thumbnail
operator|->
name|thumb_filesize
operator|=
name|filesize
expr_stmt|;
name|thumbnail
operator|->
name|thumb_mtime
operator|=
name|mtime
expr_stmt|;
if|if
condition|(
name|state
operator|!=
name|thumbnail
operator|->
name|thumb_state
condition|)
block|{
name|g_object_freeze_notify
argument_list|(
name|G_OBJECT
argument_list|(
name|thumbnail
argument_list|)
argument_list|)
expr_stmt|;
name|g_object_set
argument_list|(
name|thumbnail
argument_list|,
literal|"thumb-state"
argument_list|,
name|state
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|gimp_thumbnail_reset_info
argument_list|(
name|thumbnail
argument_list|)
expr_stmt|;
name|g_object_thaw_notify
argument_list|(
name|G_OBJECT
argument_list|(
name|thumbnail
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_thumbnail_reset_info (GimpThumbnail * thumbnail)
name|gimp_thumbnail_reset_info
parameter_list|(
name|GimpThumbnail
modifier|*
name|thumbnail
parameter_list|)
block|{
name|g_object_set
argument_list|(
name|thumbnail
argument_list|,
literal|"image-width"
argument_list|,
literal|0
argument_list|,
literal|"image-height"
argument_list|,
literal|0
argument_list|,
literal|"image-type"
argument_list|,
name|NULL
argument_list|,
literal|"image-num-layers"
argument_list|,
literal|0
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_thumbnail_set_info_from_pixbuf (GimpThumbnail * thumbnail,GdkPixbuf * pixbuf)
name|gimp_thumbnail_set_info_from_pixbuf
parameter_list|(
name|GimpThumbnail
modifier|*
name|thumbnail
parameter_list|,
name|GdkPixbuf
modifier|*
name|pixbuf
parameter_list|)
block|{
specifier|const
name|gchar
modifier|*
name|option
decl_stmt|;
name|gint
name|num
decl_stmt|;
name|g_object_freeze_notify
argument_list|(
name|G_OBJECT
argument_list|(
name|thumbnail
argument_list|)
argument_list|)
expr_stmt|;
name|gimp_thumbnail_reset_info
argument_list|(
name|thumbnail
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|thumbnail
operator|->
name|image_mimetype
argument_list|)
expr_stmt|;
name|thumbnail
operator|->
name|image_mimetype
operator|=
name|g_strdup
argument_list|(
name|gdk_pixbuf_get_option
argument_list|(
name|pixbuf
argument_list|,
name|TAG_THUMB_MIMETYPE
argument_list|)
argument_list|)
expr_stmt|;
name|option
operator|=
name|gdk_pixbuf_get_option
argument_list|(
name|pixbuf
argument_list|,
name|TAG_THUMB_IMAGE_WIDTH
argument_list|)
expr_stmt|;
if|if
condition|(
name|option
operator|&&
name|sscanf
argument_list|(
name|option
argument_list|,
literal|"%d"
argument_list|,
operator|&
name|num
argument_list|)
operator|==
literal|1
condition|)
name|thumbnail
operator|->
name|image_width
operator|=
name|num
expr_stmt|;
name|option
operator|=
name|gdk_pixbuf_get_option
argument_list|(
name|pixbuf
argument_list|,
name|TAG_THUMB_IMAGE_HEIGHT
argument_list|)
expr_stmt|;
if|if
condition|(
name|option
operator|&&
name|sscanf
argument_list|(
name|option
argument_list|,
literal|"%d"
argument_list|,
operator|&
name|num
argument_list|)
operator|==
literal|1
condition|)
name|thumbnail
operator|->
name|image_height
operator|=
name|num
expr_stmt|;
name|thumbnail
operator|->
name|image_type
operator|=
name|g_strdup
argument_list|(
name|gdk_pixbuf_get_option
argument_list|(
name|pixbuf
argument_list|,
name|TAG_THUMB_GIMP_TYPE
argument_list|)
argument_list|)
expr_stmt|;
name|option
operator|=
name|gdk_pixbuf_get_option
argument_list|(
name|pixbuf
argument_list|,
name|TAG_THUMB_GIMP_LAYERS
argument_list|)
expr_stmt|;
if|if
condition|(
name|option
operator|&&
name|sscanf
argument_list|(
name|option
argument_list|,
literal|"%d"
argument_list|,
operator|&
name|num
argument_list|)
operator|==
literal|1
condition|)
name|thumbnail
operator|->
name|image_num_layers
operator|=
name|num
expr_stmt|;
name|g_object_thaw_notify
argument_list|(
name|G_OBJECT
argument_list|(
name|thumbnail
argument_list|)
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|gboolean
DECL|function|gimp_thumbnail_save (GimpThumbnail * thumbnail,GimpThumbSize size,const gchar * filename,GdkPixbuf * pixbuf,const gchar * software,GError ** error)
name|gimp_thumbnail_save
parameter_list|(
name|GimpThumbnail
modifier|*
name|thumbnail
parameter_list|,
name|GimpThumbSize
name|size
parameter_list|,
specifier|const
name|gchar
modifier|*
name|filename
parameter_list|,
name|GdkPixbuf
modifier|*
name|pixbuf
parameter_list|,
specifier|const
name|gchar
modifier|*
name|software
parameter_list|,
name|GError
modifier|*
modifier|*
name|error
parameter_list|)
block|{
specifier|const
name|gchar
modifier|*
name|keys
index|[
literal|12
index|]
decl_stmt|;
name|gchar
modifier|*
name|values
index|[
literal|12
index|]
decl_stmt|;
name|gchar
modifier|*
name|basename
decl_stmt|;
name|gchar
modifier|*
name|dirname
decl_stmt|;
name|gchar
modifier|*
name|tmpname
decl_stmt|;
name|gboolean
name|success
decl_stmt|;
name|gint
name|i
init|=
literal|0
decl_stmt|;
name|keys
index|[
name|i
index|]
operator|=
name|TAG_DESCRIPTION
expr_stmt|;
name|values
index|[
name|i
index|]
operator|=
name|g_strdup_printf
argument_list|(
literal|"Thumbnail of %s"
argument_list|,
name|thumbnail
operator|->
name|image_uri
argument_list|)
expr_stmt|;
name|i
operator|++
expr_stmt|;
name|keys
index|[
name|i
index|]
operator|=
name|TAG_SOFTWARE
expr_stmt|;
name|values
index|[
name|i
index|]
operator|=
name|g_strdup
argument_list|(
name|software
argument_list|)
expr_stmt|;
name|i
operator|++
expr_stmt|;
name|keys
index|[
name|i
index|]
operator|=
name|TAG_THUMB_URI
expr_stmt|;
name|values
index|[
name|i
index|]
operator|=
name|g_strdup
argument_list|(
name|thumbnail
operator|->
name|image_uri
argument_list|)
expr_stmt|;
name|i
operator|++
expr_stmt|;
name|keys
index|[
name|i
index|]
operator|=
name|TAG_THUMB_MTIME
expr_stmt|;
name|values
index|[
name|i
index|]
operator|=
name|g_strdup_printf
argument_list|(
literal|"%"
name|G_GINT64_FORMAT
argument_list|,
name|thumbnail
operator|->
name|image_mtime
argument_list|)
expr_stmt|;
name|i
operator|++
expr_stmt|;
name|keys
index|[
name|i
index|]
operator|=
name|TAG_THUMB_FILESIZE
expr_stmt|;
name|values
index|[
name|i
index|]
operator|=
name|g_strdup_printf
argument_list|(
literal|"%"
name|G_GINT64_FORMAT
argument_list|,
name|thumbnail
operator|->
name|image_filesize
argument_list|)
expr_stmt|;
name|i
operator|++
expr_stmt|;
if|if
condition|(
name|thumbnail
operator|->
name|image_mimetype
condition|)
block|{
name|keys
index|[
name|i
index|]
operator|=
name|TAG_THUMB_MIMETYPE
expr_stmt|;
name|values
index|[
name|i
index|]
operator|=
name|g_strdup
argument_list|(
name|thumbnail
operator|->
name|image_mimetype
argument_list|)
expr_stmt|;
name|i
operator|++
expr_stmt|;
block|}
if|if
condition|(
name|thumbnail
operator|->
name|image_width
operator|>
literal|0
condition|)
block|{
name|keys
index|[
name|i
index|]
operator|=
name|TAG_THUMB_IMAGE_WIDTH
expr_stmt|;
name|values
index|[
name|i
index|]
operator|=
name|g_strdup_printf
argument_list|(
literal|"%d"
argument_list|,
name|thumbnail
operator|->
name|image_width
argument_list|)
expr_stmt|;
name|i
operator|++
expr_stmt|;
block|}
if|if
condition|(
name|thumbnail
operator|->
name|image_height
operator|>
literal|0
condition|)
block|{
name|keys
index|[
name|i
index|]
operator|=
name|TAG_THUMB_IMAGE_HEIGHT
expr_stmt|;
name|values
index|[
name|i
index|]
operator|=
name|g_strdup_printf
argument_list|(
literal|"%d"
argument_list|,
name|thumbnail
operator|->
name|image_height
argument_list|)
expr_stmt|;
name|i
operator|++
expr_stmt|;
block|}
if|if
condition|(
name|thumbnail
operator|->
name|image_type
condition|)
block|{
name|keys
index|[
name|i
index|]
operator|=
name|TAG_THUMB_GIMP_TYPE
expr_stmt|;
name|values
index|[
name|i
index|]
operator|=
name|g_strdup
argument_list|(
name|thumbnail
operator|->
name|image_type
argument_list|)
expr_stmt|;
name|i
operator|++
expr_stmt|;
block|}
if|if
condition|(
name|thumbnail
operator|->
name|image_num_layers
operator|>
literal|0
condition|)
block|{
name|keys
index|[
name|i
index|]
operator|=
name|TAG_THUMB_GIMP_LAYERS
expr_stmt|;
name|values
index|[
name|i
index|]
operator|=
name|g_strdup_printf
argument_list|(
literal|"%d"
argument_list|,
name|thumbnail
operator|->
name|image_num_layers
argument_list|)
expr_stmt|;
name|i
operator|++
expr_stmt|;
block|}
name|keys
index|[
name|i
index|]
operator|=
name|NULL
expr_stmt|;
name|values
index|[
name|i
index|]
operator|=
name|NULL
expr_stmt|;
name|basename
operator|=
name|g_path_get_basename
argument_list|(
name|filename
argument_list|)
expr_stmt|;
name|dirname
operator|=
name|g_path_get_dirname
argument_list|(
name|filename
argument_list|)
expr_stmt|;
name|tmpname
operator|=
name|g_strdup_printf
argument_list|(
literal|"%s%cgimp-thumb-%d-%.8s"
argument_list|,
name|dirname
argument_list|,
name|G_DIR_SEPARATOR
argument_list|,
name|getpid
argument_list|()
argument_list|,
name|basename
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|dirname
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|basename
argument_list|)
expr_stmt|;
name|success
operator|=
name|gdk_pixbuf_savev
argument_list|(
name|pixbuf
argument_list|,
name|tmpname
argument_list|,
literal|"png"
argument_list|,
operator|(
name|gchar
operator|*
operator|*
operator|)
name|keys
argument_list|,
name|values
argument_list|,
name|error
argument_list|)
expr_stmt|;
for|for
control|(
name|i
operator|=
literal|0
init|;
name|keys
index|[
name|i
index|]
condition|;
name|i
operator|++
control|)
name|g_free
argument_list|(
name|values
index|[
name|i
index|]
argument_list|)
expr_stmt|;
if|if
condition|(
name|success
condition|)
block|{
ifdef|#
directive|ifdef
name|GIMP_THUMB_DEBUG
name|g_printerr
argument_list|(
literal|"thumbnail saved to temporary file %s\n"
argument_list|,
name|tmpname
argument_list|)
expr_stmt|;
endif|#
directive|endif
name|success
operator|=
operator|(
name|g_rename
argument_list|(
name|tmpname
argument_list|,
name|filename
argument_list|)
operator|==
literal|0
operator|)
expr_stmt|;
if|if
condition|(
operator|!
name|success
condition|)
name|g_set_error
argument_list|(
name|error
argument_list|,
name|G_FILE_ERROR
argument_list|,
name|g_file_error_from_errno
argument_list|(
name|errno
argument_list|)
argument_list|,
name|_
argument_list|(
literal|"Could not create thumbnail for %s: %s"
argument_list|)
argument_list|,
name|thumbnail
operator|->
name|image_uri
argument_list|,
name|g_strerror
argument_list|(
name|errno
argument_list|)
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|success
condition|)
block|{
ifdef|#
directive|ifdef
name|GIMP_THUMB_DEBUG
name|g_printerr
argument_list|(
literal|"temporary thumbnail file renamed to %s\n"
argument_list|,
name|filename
argument_list|)
expr_stmt|;
endif|#
directive|endif
name|success
operator|=
operator|(
name|g_chmod
argument_list|(
name|filename
argument_list|,
literal|0600
argument_list|)
operator|==
literal|0
operator|)
expr_stmt|;
if|if
condition|(
operator|!
name|success
condition|)
name|g_set_error
argument_list|(
name|error
argument_list|,
name|G_FILE_ERROR
argument_list|,
name|g_file_error_from_errno
argument_list|(
name|errno
argument_list|)
argument_list|,
literal|"Could not set permissions of thumbnail for %s: %s"
argument_list|,
name|thumbnail
operator|->
name|image_uri
argument_list|,
name|g_strerror
argument_list|(
name|errno
argument_list|)
argument_list|)
expr_stmt|;
name|g_object_freeze_notify
argument_list|(
name|G_OBJECT
argument_list|(
name|thumbnail
argument_list|)
argument_list|)
expr_stmt|;
name|gimp_thumbnail_update_thumb
argument_list|(
name|thumbnail
argument_list|,
name|size
argument_list|)
expr_stmt|;
if|if
condition|(
name|success
operator|&&
name|thumbnail
operator|->
name|thumb_state
operator|==
name|GIMP_THUMB_STATE_EXISTS
operator|&&
name|strcmp
argument_list|(
name|filename
argument_list|,
name|thumbnail
operator|->
name|thumb_filename
argument_list|)
operator|==
literal|0
condition|)
block|{
name|thumbnail
operator|->
name|thumb_state
operator|=
name|GIMP_THUMB_STATE_OK
expr_stmt|;
block|}
name|g_object_thaw_notify
argument_list|(
name|G_OBJECT
argument_list|(
name|thumbnail
argument_list|)
argument_list|)
expr_stmt|;
block|}
name|g_unlink
argument_list|(
name|tmpname
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|tmpname
argument_list|)
expr_stmt|;
return|return
name|success
return|;
block|}
end_function

begin_ifdef
ifdef|#
directive|ifdef
name|GIMP_THUMB_DEBUG
end_ifdef

begin_function
specifier|static
name|void
DECL|function|gimp_thumbnail_debug_notify (GObject * object,GParamSpec * pspec)
name|gimp_thumbnail_debug_notify
parameter_list|(
name|GObject
modifier|*
name|object
parameter_list|,
name|GParamSpec
modifier|*
name|pspec
parameter_list|)
block|{
name|GValue
name|value
init|=
block|{
literal|0
block|, }
decl_stmt|;
name|gchar
modifier|*
name|str
init|=
name|NULL
decl_stmt|;
specifier|const
name|gchar
modifier|*
name|name
decl_stmt|;
name|g_value_init
argument_list|(
operator|&
name|value
argument_list|,
name|pspec
operator|->
name|value_type
argument_list|)
expr_stmt|;
name|g_object_get_property
argument_list|(
name|object
argument_list|,
name|pspec
operator|->
name|name
argument_list|,
operator|&
name|value
argument_list|)
expr_stmt|;
if|if
condition|(
name|G_VALUE_HOLDS_STRING
argument_list|(
operator|&
name|value
argument_list|)
condition|)
block|{
name|str
operator|=
name|g_value_dup_string
argument_list|(
operator|&
name|value
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|g_value_type_transformable
argument_list|(
name|pspec
operator|->
name|value_type
argument_list|,
name|G_TYPE_STRING
argument_list|)
condition|)
block|{
name|GValue
name|tmp
init|=
block|{
literal|0
block|, }
decl_stmt|;
name|g_value_init
argument_list|(
operator|&
name|tmp
argument_list|,
name|G_TYPE_STRING
argument_list|)
expr_stmt|;
name|g_value_transform
argument_list|(
operator|&
name|value
argument_list|,
operator|&
name|tmp
argument_list|)
expr_stmt|;
name|str
operator|=
name|g_value_dup_string
argument_list|(
operator|&
name|tmp
argument_list|)
expr_stmt|;
name|g_value_unset
argument_list|(
operator|&
name|tmp
argument_list|)
expr_stmt|;
block|}
name|g_value_unset
argument_list|(
operator|&
name|value
argument_list|)
expr_stmt|;
name|name
operator|=
name|GIMP_THUMBNAIL
argument_list|(
name|object
argument_list|)
operator|->
name|image_uri
expr_stmt|;
name|g_printerr
argument_list|(
literal|" GimpThumb (%s) %s: %s\n"
argument_list|,
name|name
condition|?
name|name
else|:
literal|"(null)"
argument_list|,
name|pspec
operator|->
name|name
argument_list|,
name|str
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|str
argument_list|)
expr_stmt|;
block|}
end_function

begin_endif
endif|#
directive|endif
end_endif

begin_comment
comment|/**  * gimp_thumbnail_load_thumb:  * @thumbnail: a #GimpThumbnail object  * @size: the preferred #GimpThumbSize for the preview  * @error: return location for possible errors  *  * Attempts to load a thumbnail preview for the image associated with  * @thumbnail. Before you use this function you need need to set an  * image location using gimp_thumbnail_set_uri() or  * gimp_thumbnail_set_filename(). You can also peek at the thumb  * before loading it using gimp_thumbnail_peek_thumb.  *  * This function will return the best matching pixbuf for the  * specified @size. It returns the pixbuf as loaded from disk. It is  * left to the caller to scale it to the desired size. The returned  * pixbuf may also represent an outdated preview of the image file.  * In order to verify if the preview is uptodate, you should check the  * "thumb_state" property after calling this function.  *  * Return value: a preview pixbuf or %NULL if no thumbnail was found  **/
end_comment

begin_function
name|GdkPixbuf
modifier|*
DECL|function|gimp_thumbnail_load_thumb (GimpThumbnail * thumbnail,GimpThumbSize size,GError ** error)
name|gimp_thumbnail_load_thumb
parameter_list|(
name|GimpThumbnail
modifier|*
name|thumbnail
parameter_list|,
name|GimpThumbSize
name|size
parameter_list|,
name|GError
modifier|*
modifier|*
name|error
parameter_list|)
block|{
name|GimpThumbState
name|state
decl_stmt|;
name|GdkPixbuf
modifier|*
name|pixbuf
decl_stmt|;
specifier|const
name|gchar
modifier|*
name|option
decl_stmt|;
name|gint64
name|image_mtime
decl_stmt|;
name|gint64
name|image_size
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_THUMBNAIL
argument_list|(
name|thumbnail
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|GIMP_THUMB_DEBUG_CALL
argument_list|(
name|thumbnail
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|thumbnail
operator|->
name|image_uri
condition|)
return|return
name|NULL
return|;
name|state
operator|=
name|gimp_thumbnail_peek_thumb
argument_list|(
name|thumbnail
argument_list|,
name|size
argument_list|)
expr_stmt|;
if|if
condition|(
name|state
operator|<
name|GIMP_THUMB_STATE_EXISTS
operator|||
name|state
operator|==
name|GIMP_THUMB_STATE_FAILED
condition|)
return|return
name|NULL
return|;
name|pixbuf
operator|=
name|gdk_pixbuf_new_from_file
argument_list|(
name|thumbnail
operator|->
name|thumb_filename
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|pixbuf
condition|)
return|return
name|NULL
return|;
ifdef|#
directive|ifdef
name|GIMP_THUMB_DEBUG
name|g_printerr
argument_list|(
literal|"thumbnail loaded from %s\n"
argument_list|,
name|thumbnail
operator|->
name|thumb_filename
argument_list|)
expr_stmt|;
endif|#
directive|endif
name|g_object_freeze_notify
argument_list|(
name|G_OBJECT
argument_list|(
name|thumbnail
argument_list|)
argument_list|)
expr_stmt|;
comment|/* URI and mtime from the thumbnail need to match our file */
name|option
operator|=
name|gdk_pixbuf_get_option
argument_list|(
name|pixbuf
argument_list|,
name|TAG_THUMB_URI
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|option
condition|)
goto|goto
name|finish
goto|;
if|if
condition|(
name|strcmp
argument_list|(
name|option
argument_list|,
name|thumbnail
operator|->
name|image_uri
argument_list|)
condition|)
block|{
comment|/*  might be a local thumbnail, try if the local part matches  */
specifier|const
name|gchar
modifier|*
name|baseuri
init|=
name|strrchr
argument_list|(
name|thumbnail
operator|->
name|image_uri
argument_list|,
literal|'/'
argument_list|)
decl_stmt|;
if|if
condition|(
operator|!
name|baseuri
operator|||
name|strcmp
argument_list|(
name|option
argument_list|,
name|baseuri
argument_list|)
condition|)
goto|goto
name|finish
goto|;
block|}
name|state
operator|=
name|GIMP_THUMB_STATE_OLD
expr_stmt|;
name|option
operator|=
name|gdk_pixbuf_get_option
argument_list|(
name|pixbuf
argument_list|,
name|TAG_THUMB_MTIME
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|option
operator|||
name|sscanf
argument_list|(
name|option
argument_list|,
literal|"%"
name|G_GINT64_FORMAT
argument_list|,
operator|&
name|image_mtime
argument_list|)
operator|!=
literal|1
condition|)
goto|goto
name|finish
goto|;
name|option
operator|=
name|gdk_pixbuf_get_option
argument_list|(
name|pixbuf
argument_list|,
name|TAG_THUMB_FILESIZE
argument_list|)
expr_stmt|;
if|if
condition|(
name|option
operator|&&
name|sscanf
argument_list|(
name|option
argument_list|,
literal|"%"
name|G_GINT64_FORMAT
argument_list|,
operator|&
name|image_size
argument_list|)
operator|!=
literal|1
condition|)
goto|goto
name|finish
goto|;
comment|/* TAG_THUMB_FILESIZE is optional but must match if present */
if|if
condition|(
name|image_mtime
operator|==
name|thumbnail
operator|->
name|image_mtime
operator|&&
operator|(
name|option
operator|==
name|NULL
operator|||
name|image_size
operator|==
name|thumbnail
operator|->
name|image_filesize
operator|)
condition|)
block|{
if|if
condition|(
name|thumbnail
operator|->
name|thumb_size
operator|==
name|GIMP_THUMB_SIZE_FAIL
condition|)
name|state
operator|=
name|GIMP_THUMB_STATE_FAILED
expr_stmt|;
else|else
name|state
operator|=
name|GIMP_THUMB_STATE_OK
expr_stmt|;
block|}
if|if
condition|(
name|state
operator|==
name|GIMP_THUMB_STATE_FAILED
condition|)
name|gimp_thumbnail_reset_info
argument_list|(
name|thumbnail
argument_list|)
expr_stmt|;
else|else
name|gimp_thumbnail_set_info_from_pixbuf
argument_list|(
name|thumbnail
argument_list|,
name|pixbuf
argument_list|)
expr_stmt|;
name|finish
label|:
if|if
condition|(
name|thumbnail
operator|->
name|thumb_size
operator|==
name|GIMP_THUMB_SIZE_FAIL
operator|||
operator|(
name|state
operator|!=
name|GIMP_THUMB_STATE_OLD
operator|&&
name|state
operator|!=
name|GIMP_THUMB_STATE_OK
operator|)
condition|)
block|{
name|g_object_unref
argument_list|(
name|pixbuf
argument_list|)
expr_stmt|;
name|pixbuf
operator|=
name|NULL
expr_stmt|;
block|}
name|g_object_set
argument_list|(
name|thumbnail
argument_list|,
literal|"thumb-state"
argument_list|,
name|state
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_object_thaw_notify
argument_list|(
name|G_OBJECT
argument_list|(
name|thumbnail
argument_list|)
argument_list|)
expr_stmt|;
return|return
name|pixbuf
return|;
block|}
end_function

begin_comment
comment|/**  * gimp_thumbnail_save_thumb:  * @thumbnail: a #GimpThumbnail object  * @pixbuf: a #GdkPixbuf representing the preview thumbnail  * @software: a string describing the software saving the thumbnail  * @error: return location for possible errors  *  * Saves a preview thumbnail for the image associated with @thumbnail.  * to the global thumbnail repository.  *  * The caller is responsible for setting the image file location, it's  * filesize, modification time. One way to set this info is to is to  * call gimp_thumbnail_set_uri() followed by gimp_thumbnail_peek_image().  * Since this won't work for remote images, it is left to the user of  * gimp_thumbnail_save_thumb() to do this or to set the information  * using the @thumbnail object properties.  *  * The image format type and the number of layers can optionally be  * set in order to be stored with the preview image.  *  * Return value: %TRUE if a thumbnail was successfully written,  *               %FALSE otherwise  **/
end_comment

begin_function
name|gboolean
DECL|function|gimp_thumbnail_save_thumb (GimpThumbnail * thumbnail,GdkPixbuf * pixbuf,const gchar * software,GError ** error)
name|gimp_thumbnail_save_thumb
parameter_list|(
name|GimpThumbnail
modifier|*
name|thumbnail
parameter_list|,
name|GdkPixbuf
modifier|*
name|pixbuf
parameter_list|,
specifier|const
name|gchar
modifier|*
name|software
parameter_list|,
name|GError
modifier|*
modifier|*
name|error
parameter_list|)
block|{
name|GimpThumbSize
name|size
decl_stmt|;
name|gchar
modifier|*
name|name
decl_stmt|;
name|gboolean
name|success
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_THUMBNAIL
argument_list|(
name|thumbnail
argument_list|)
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
name|thumbnail
operator|->
name|image_uri
operator|!=
name|NULL
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GDK_IS_PIXBUF
argument_list|(
name|pixbuf
argument_list|)
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
name|software
operator|!=
name|NULL
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
name|error
operator|==
name|NULL
operator|||
operator|*
name|error
operator|==
name|NULL
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|GIMP_THUMB_DEBUG_CALL
argument_list|(
name|thumbnail
argument_list|)
expr_stmt|;
name|size
operator|=
name|MAX
argument_list|(
name|gdk_pixbuf_get_width
argument_list|(
name|pixbuf
argument_list|)
argument_list|,
name|gdk_pixbuf_get_height
argument_list|(
name|pixbuf
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|size
operator|<
literal|1
condition|)
return|return
name|TRUE
return|;
name|name
operator|=
name|gimp_thumb_name_from_uri
argument_list|(
name|thumbnail
operator|->
name|image_uri
argument_list|,
name|size
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|name
condition|)
return|return
name|TRUE
return|;
if|if
condition|(
operator|!
name|gimp_thumb_ensure_thumb_dir
argument_list|(
name|size
argument_list|,
name|error
argument_list|)
condition|)
block|{
name|g_free
argument_list|(
name|name
argument_list|)
expr_stmt|;
return|return
name|FALSE
return|;
block|}
name|success
operator|=
name|gimp_thumbnail_save
argument_list|(
name|thumbnail
argument_list|,
name|size
argument_list|,
name|name
argument_list|,
name|pixbuf
argument_list|,
name|software
argument_list|,
name|error
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|name
argument_list|)
expr_stmt|;
return|return
name|success
return|;
block|}
end_function

begin_comment
comment|/**  * gimp_thumbnail_save_thumb_local:  * @thumbnail: a #GimpThumbnail object  * @pixbuf: a #GdkPixbuf representing the preview thumbnail  * @software: a string describing the software saving the thumbnail  * @error: return location for possible errors  *  * Saves a preview thumbnail for the image associated with @thumbnail  * to the local thumbnail repository. Local thumbnails have been added  * with version 0.7 of the spec.  *  * Please see also gimp_thumbnail_save_thumb(). The notes made there  * apply here as well.  *  * Return value: %TRUE if a thumbnail was successfully written,  *               %FALSE otherwise  *  * Since: GIMP 2.2  **/
end_comment

begin_function
name|gboolean
DECL|function|gimp_thumbnail_save_thumb_local (GimpThumbnail * thumbnail,GdkPixbuf * pixbuf,const gchar * software,GError ** error)
name|gimp_thumbnail_save_thumb_local
parameter_list|(
name|GimpThumbnail
modifier|*
name|thumbnail
parameter_list|,
name|GdkPixbuf
modifier|*
name|pixbuf
parameter_list|,
specifier|const
name|gchar
modifier|*
name|software
parameter_list|,
name|GError
modifier|*
modifier|*
name|error
parameter_list|)
block|{
name|GimpThumbSize
name|size
decl_stmt|;
name|gchar
modifier|*
name|name
decl_stmt|;
name|gchar
modifier|*
name|filename
decl_stmt|;
name|gchar
modifier|*
name|dirname
decl_stmt|;
name|gboolean
name|success
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_THUMBNAIL
argument_list|(
name|thumbnail
argument_list|)
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
name|thumbnail
operator|->
name|image_uri
operator|!=
name|NULL
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GDK_IS_PIXBUF
argument_list|(
name|pixbuf
argument_list|)
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
name|software
operator|!=
name|NULL
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
name|error
operator|==
name|NULL
operator|||
operator|*
name|error
operator|==
name|NULL
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|GIMP_THUMB_DEBUG_CALL
argument_list|(
name|thumbnail
argument_list|)
expr_stmt|;
name|size
operator|=
name|MAX
argument_list|(
name|gdk_pixbuf_get_width
argument_list|(
name|pixbuf
argument_list|)
argument_list|,
name|gdk_pixbuf_get_height
argument_list|(
name|pixbuf
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|size
operator|<
literal|1
condition|)
return|return
name|TRUE
return|;
name|filename
operator|=
name|_gimp_thumb_filename_from_uri
argument_list|(
name|thumbnail
operator|->
name|image_uri
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|filename
condition|)
return|return
name|TRUE
return|;
name|dirname
operator|=
name|g_path_get_dirname
argument_list|(
name|filename
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|filename
argument_list|)
expr_stmt|;
name|name
operator|=
name|gimp_thumb_name_from_uri_local
argument_list|(
name|thumbnail
operator|->
name|image_uri
argument_list|,
name|size
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|name
condition|)
block|{
name|g_free
argument_list|(
name|dirname
argument_list|)
expr_stmt|;
return|return
name|TRUE
return|;
block|}
if|if
condition|(
operator|!
name|gimp_thumb_ensure_thumb_dir_local
argument_list|(
name|dirname
argument_list|,
name|size
argument_list|,
name|error
argument_list|)
condition|)
block|{
name|g_free
argument_list|(
name|name
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|dirname
argument_list|)
expr_stmt|;
return|return
name|FALSE
return|;
block|}
name|g_free
argument_list|(
name|dirname
argument_list|)
expr_stmt|;
name|success
operator|=
name|gimp_thumbnail_save
argument_list|(
name|thumbnail
argument_list|,
name|size
argument_list|,
name|name
argument_list|,
name|pixbuf
argument_list|,
name|software
argument_list|,
name|error
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|name
argument_list|)
expr_stmt|;
return|return
name|success
return|;
block|}
end_function

begin_comment
comment|/**  * gimp_thumbnail_save_failure:  * @thumbnail: a #GimpThumbnail object  * @software: a string describing the software saving the thumbnail  * @error: return location for possible errors  *  * Saves a failure thumbnail for the image associated with  * @thumbnail. This is an empty pixbuf that indicates that an attempt  * to create a preview for the image file failed. It should be used to  * prevent the software from further attempts to create this thumbnail.  *  * Return value: %TRUE if a failure thumbnail was successfully written,  *               %FALSE otherwise  **/
end_comment

begin_function
name|gboolean
DECL|function|gimp_thumbnail_save_failure (GimpThumbnail * thumbnail,const gchar * software,GError ** error)
name|gimp_thumbnail_save_failure
parameter_list|(
name|GimpThumbnail
modifier|*
name|thumbnail
parameter_list|,
specifier|const
name|gchar
modifier|*
name|software
parameter_list|,
name|GError
modifier|*
modifier|*
name|error
parameter_list|)
block|{
name|GdkPixbuf
modifier|*
name|pixbuf
decl_stmt|;
name|gchar
modifier|*
name|name
decl_stmt|;
name|gchar
modifier|*
name|desc
decl_stmt|;
name|gchar
modifier|*
name|time_str
decl_stmt|;
name|gchar
modifier|*
name|size_str
decl_stmt|;
name|gboolean
name|success
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_THUMBNAIL
argument_list|(
name|thumbnail
argument_list|)
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
name|thumbnail
operator|->
name|image_uri
operator|!=
name|NULL
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
name|software
operator|!=
name|NULL
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|GIMP_THUMB_DEBUG_CALL
argument_list|(
name|thumbnail
argument_list|)
expr_stmt|;
name|name
operator|=
name|gimp_thumb_name_from_uri
argument_list|(
name|thumbnail
operator|->
name|image_uri
argument_list|,
name|GIMP_THUMB_SIZE_FAIL
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|name
condition|)
return|return
name|TRUE
return|;
if|if
condition|(
operator|!
name|gimp_thumb_ensure_thumb_dir
argument_list|(
name|GIMP_THUMB_SIZE_FAIL
argument_list|,
name|error
argument_list|)
condition|)
block|{
name|g_free
argument_list|(
name|name
argument_list|)
expr_stmt|;
return|return
name|FALSE
return|;
block|}
name|pixbuf
operator|=
name|gdk_pixbuf_new
argument_list|(
name|GDK_COLORSPACE_RGB
argument_list|,
name|FALSE
argument_list|,
literal|8
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|desc
operator|=
name|g_strdup_printf
argument_list|(
literal|"Thumbnail failure for %s"
argument_list|,
name|thumbnail
operator|->
name|image_uri
argument_list|)
expr_stmt|;
name|time_str
operator|=
name|g_strdup_printf
argument_list|(
literal|"%"
name|G_GINT64_FORMAT
argument_list|,
name|thumbnail
operator|->
name|image_mtime
argument_list|)
expr_stmt|;
name|size_str
operator|=
name|g_strdup_printf
argument_list|(
literal|"%"
name|G_GINT64_FORMAT
argument_list|,
name|thumbnail
operator|->
name|image_filesize
argument_list|)
expr_stmt|;
name|success
operator|=
name|gdk_pixbuf_save
argument_list|(
name|pixbuf
argument_list|,
name|name
argument_list|,
literal|"png"
argument_list|,
name|error
argument_list|,
name|TAG_DESCRIPTION
argument_list|,
name|desc
argument_list|,
name|TAG_SOFTWARE
argument_list|,
name|software
argument_list|,
name|TAG_THUMB_URI
argument_list|,
name|thumbnail
operator|->
name|image_uri
argument_list|,
name|TAG_THUMB_MTIME
argument_list|,
name|time_str
argument_list|,
name|TAG_THUMB_FILESIZE
argument_list|,
name|size_str
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
if|if
condition|(
name|success
condition|)
block|{
name|success
operator|=
operator|(
name|g_chmod
argument_list|(
name|name
argument_list|,
literal|0600
argument_list|)
operator|==
literal|0
operator|)
expr_stmt|;
if|if
condition|(
name|success
condition|)
name|gimp_thumbnail_update_thumb
argument_list|(
name|thumbnail
argument_list|,
name|GIMP_THUMB_SIZE_NORMAL
argument_list|)
expr_stmt|;
else|else
name|g_set_error
argument_list|(
name|error
argument_list|,
name|G_FILE_ERROR
argument_list|,
name|g_file_error_from_errno
argument_list|(
name|errno
argument_list|)
argument_list|,
literal|"Could not set permissions of thumbnail '%s': %s"
argument_list|,
name|name
argument_list|,
name|g_strerror
argument_list|(
name|errno
argument_list|)
argument_list|)
expr_stmt|;
block|}
name|g_object_unref
argument_list|(
name|pixbuf
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|size_str
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|time_str
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|desc
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|name
argument_list|)
expr_stmt|;
return|return
name|success
return|;
block|}
end_function

begin_comment
comment|/**  * gimp_thumbnail_delete_failure:  * @thumbnail: a #GimpThumbnail object  *  * Removes a failure thumbnail if one exists. This function should be  * used after a thumbnail has been successfully created.  *  * Since: GIMP 2.2  **/
end_comment

begin_function
name|void
DECL|function|gimp_thumbnail_delete_failure (GimpThumbnail * thumbnail)
name|gimp_thumbnail_delete_failure
parameter_list|(
name|GimpThumbnail
modifier|*
name|thumbnail
parameter_list|)
block|{
name|gchar
modifier|*
name|filename
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_THUMBNAIL
argument_list|(
name|thumbnail
argument_list|)
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
name|thumbnail
operator|->
name|image_uri
operator|!=
name|NULL
argument_list|)
expr_stmt|;
name|GIMP_THUMB_DEBUG_CALL
argument_list|(
name|thumbnail
argument_list|)
expr_stmt|;
name|filename
operator|=
name|gimp_thumb_name_from_uri
argument_list|(
name|thumbnail
operator|->
name|image_uri
argument_list|,
name|GIMP_THUMB_SIZE_FAIL
argument_list|)
expr_stmt|;
if|if
condition|(
name|filename
condition|)
block|{
name|g_unlink
argument_list|(
name|filename
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|filename
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_comment
comment|/**  * gimp_thumbnail_delete_others:  * @thumbnail: a #GimpThumbnail object  * @size: the thumbnail size which should not be deleted  *  * Removes all other thumbnails from the global thumbnail  * repository. Only the thumbnail for @size is not deleted.  This  * function should be used after a thumbnail has been successfully  * updated. See the spec for a more detailed description on when to  * delete thumbnails.  *  * Since: GIMP 2.2  **/
end_comment

begin_function
name|void
DECL|function|gimp_thumbnail_delete_others (GimpThumbnail * thumbnail,GimpThumbSize size)
name|gimp_thumbnail_delete_others
parameter_list|(
name|GimpThumbnail
modifier|*
name|thumbnail
parameter_list|,
name|GimpThumbSize
name|size
parameter_list|)
block|{
name|g_return_if_fail
argument_list|(
name|GIMP_IS_THUMBNAIL
argument_list|(
name|thumbnail
argument_list|)
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
name|thumbnail
operator|->
name|image_uri
operator|!=
name|NULL
argument_list|)
expr_stmt|;
name|GIMP_THUMB_DEBUG_CALL
argument_list|(
name|thumbnail
argument_list|)
expr_stmt|;
name|_gimp_thumbs_delete_others
argument_list|(
name|thumbnail
operator|->
name|image_uri
argument_list|,
name|size
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/**  * gimp_thumbnail_has_failed:  * @thumbnail: a #GimpThumbnail object  *  * Checks if a valid failure thumbnail for the given thumbnail exists  * in the global thumbnail repository. This may be the case even if  * gimp_thumbnail_peek_thumb() doesn't return %GIMP_THUMB_STATE_FAILED  * since there might be a real thumbnail and a failure thumbnail for  * the same image file.  *  * The application should not attempt to create the thumbnail if a  * valid failure thumbnail exists.  *  * Return value: %TRUE if a failure thumbnail exists or  *  * Since: GIMP 2.2  **/
end_comment

begin_function
name|gboolean
DECL|function|gimp_thumbnail_has_failed (GimpThumbnail * thumbnail)
name|gimp_thumbnail_has_failed
parameter_list|(
name|GimpThumbnail
modifier|*
name|thumbnail
parameter_list|)
block|{
name|GdkPixbuf
modifier|*
name|pixbuf
decl_stmt|;
specifier|const
name|gchar
modifier|*
name|option
decl_stmt|;
name|gchar
modifier|*
name|filename
decl_stmt|;
name|gint64
name|image_mtime
decl_stmt|;
name|gint64
name|image_size
decl_stmt|;
name|gboolean
name|failed
init|=
name|FALSE
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_THUMBNAIL
argument_list|(
name|thumbnail
argument_list|)
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
name|thumbnail
operator|->
name|image_uri
operator|!=
name|NULL
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|GIMP_THUMB_DEBUG_CALL
argument_list|(
name|thumbnail
argument_list|)
expr_stmt|;
name|filename
operator|=
name|gimp_thumb_name_from_uri
argument_list|(
name|thumbnail
operator|->
name|image_uri
argument_list|,
name|GIMP_THUMB_SIZE_FAIL
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|filename
condition|)
return|return
name|FALSE
return|;
name|pixbuf
operator|=
name|gdk_pixbuf_new_from_file
argument_list|(
name|filename
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|filename
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|pixbuf
condition|)
return|return
name|FALSE
return|;
if|if
condition|(
name|gimp_thumbnail_peek_image
argument_list|(
name|thumbnail
argument_list|)
operator|<
name|GIMP_THUMB_STATE_EXISTS
condition|)
goto|goto
name|finish
goto|;
comment|/* URI and mtime from the thumbnail need to match our file */
name|option
operator|=
name|gdk_pixbuf_get_option
argument_list|(
name|pixbuf
argument_list|,
name|TAG_THUMB_URI
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|option
operator|||
name|strcmp
argument_list|(
name|option
argument_list|,
name|thumbnail
operator|->
name|image_uri
argument_list|)
condition|)
goto|goto
name|finish
goto|;
name|option
operator|=
name|gdk_pixbuf_get_option
argument_list|(
name|pixbuf
argument_list|,
name|TAG_THUMB_MTIME
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|option
operator|||
name|sscanf
argument_list|(
name|option
argument_list|,
literal|"%"
name|G_GINT64_FORMAT
argument_list|,
operator|&
name|image_mtime
argument_list|)
operator|!=
literal|1
condition|)
goto|goto
name|finish
goto|;
name|option
operator|=
name|gdk_pixbuf_get_option
argument_list|(
name|pixbuf
argument_list|,
name|TAG_THUMB_FILESIZE
argument_list|)
expr_stmt|;
if|if
condition|(
name|option
operator|&&
name|sscanf
argument_list|(
name|option
argument_list|,
literal|"%"
name|G_GINT64_FORMAT
argument_list|,
operator|&
name|image_size
argument_list|)
operator|!=
literal|1
condition|)
goto|goto
name|finish
goto|;
comment|/* TAG_THUMB_FILESIZE is optional but must match if present */
if|if
condition|(
name|image_mtime
operator|==
name|thumbnail
operator|->
name|image_mtime
operator|&&
operator|(
name|option
operator|==
name|NULL
operator|||
name|image_size
operator|==
name|thumbnail
operator|->
name|image_filesize
operator|)
condition|)
block|{
name|failed
operator|=
name|TRUE
expr_stmt|;
block|}
name|finish
label|:
name|g_object_unref
argument_list|(
name|pixbuf
argument_list|)
expr_stmt|;
return|return
name|failed
return|;
block|}
end_function

end_unit

