begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* GIMP - The GNU Image Manipulation Program  * Copyright (C) 1995 Spencer Kimball and Peter Mattis  *  * Diffraction plug-in --- Generate diffraction patterns  * Copyright (C) 1997 Federico Mena Quintero and David Bleecker  * federico@nuclecu.unam.mx  * bleecker@math.hawaii.edu  *  * This program is free software: you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 3 of the License, or  * (at your option) any later version.  *  * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *  * You should have received a copy of the GNU General Public License  * along with this program.  If not, see<http://www.gnu.org/licenses/>.  */
end_comment

begin_include
include|#
directive|include
file|"config.h"
end_include

begin_include
include|#
directive|include
file|<libgimp/gimp.h>
end_include

begin_include
include|#
directive|include
file|<libgimp/gimpui.h>
end_include

begin_include
include|#
directive|include
file|"libgimp/stdplugins-intl.h"
end_include

begin_define
DECL|macro|PLUG_IN_PROC
define|#
directive|define
name|PLUG_IN_PROC
value|"plug-in-diffraction"
end_define

begin_define
DECL|macro|PLUG_IN_BINARY
define|#
directive|define
name|PLUG_IN_BINARY
value|"diffraction"
end_define

begin_define
DECL|macro|PLUG_IN_ROLE
define|#
directive|define
name|PLUG_IN_ROLE
value|"gimp-diffraction"
end_define

begin_comment
comment|/***** Magic numbers *****/
end_comment

begin_define
DECL|macro|ITERATIONS
define|#
directive|define
name|ITERATIONS
value|100
end_define

begin_define
DECL|macro|WEIRD_FACTOR
define|#
directive|define
name|WEIRD_FACTOR
value|0.04
end_define

begin_define
DECL|macro|PREVIEW_WIDTH
define|#
directive|define
name|PREVIEW_WIDTH
value|64
end_define

begin_define
DECL|macro|PREVIEW_HEIGHT
define|#
directive|define
name|PREVIEW_HEIGHT
value|64
end_define

begin_define
DECL|macro|PROGRESS_WIDTH
define|#
directive|define
name|PROGRESS_WIDTH
value|32
end_define

begin_define
DECL|macro|PROGRESS_HEIGHT
define|#
directive|define
name|PROGRESS_HEIGHT
value|16
end_define

begin_define
DECL|macro|SCALE_WIDTH
define|#
directive|define
name|SCALE_WIDTH
value|150
end_define

begin_comment
comment|/***** Types *****/
end_comment

begin_typedef
typedef|typedef
struct|struct
DECL|struct|__anon275c237c0108
block|{
DECL|member|lam_r
name|gdouble
name|lam_r
decl_stmt|;
DECL|member|lam_g
name|gdouble
name|lam_g
decl_stmt|;
DECL|member|lam_b
name|gdouble
name|lam_b
decl_stmt|;
DECL|member|contour_r
name|gdouble
name|contour_r
decl_stmt|;
DECL|member|contour_g
name|gdouble
name|contour_g
decl_stmt|;
DECL|member|contour_b
name|gdouble
name|contour_b
decl_stmt|;
DECL|member|edges_r
name|gdouble
name|edges_r
decl_stmt|;
DECL|member|edges_g
name|gdouble
name|edges_g
decl_stmt|;
DECL|member|edges_b
name|gdouble
name|edges_b
decl_stmt|;
DECL|member|brightness
name|gdouble
name|brightness
decl_stmt|;
DECL|member|scattering
name|gdouble
name|scattering
decl_stmt|;
DECL|member|polarization
name|gdouble
name|polarization
decl_stmt|;
DECL|typedef|diffraction_vals_t
block|}
name|diffraction_vals_t
typedef|;
end_typedef

begin_typedef
typedef|typedef
struct|struct
DECL|struct|__anon275c237c0208
block|{
DECL|member|preview
name|GtkWidget
modifier|*
name|preview
decl_stmt|;
DECL|member|progress
name|GtkWidget
modifier|*
name|progress
decl_stmt|;
DECL|member|preview_buffer
name|guchar
name|preview_buffer
index|[
name|PREVIEW_WIDTH
operator|*
name|PREVIEW_HEIGHT
operator|*
literal|3
index|]
decl_stmt|;
DECL|typedef|diffraction_interface_t
block|}
name|diffraction_interface_t
typedef|;
end_typedef

begin_comment
comment|/***** Prototypes *****/
end_comment

begin_function_decl
specifier|static
name|void
name|query
parameter_list|(
name|void
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|run
parameter_list|(
specifier|const
name|gchar
modifier|*
name|name
parameter_list|,
name|gint
name|nparams
parameter_list|,
specifier|const
name|GimpParam
modifier|*
name|param
parameter_list|,
name|gint
modifier|*
name|nreturn_vals
parameter_list|,
name|GimpParam
modifier|*
modifier|*
name|return_vals
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|diffraction
parameter_list|(
name|GimpDrawable
modifier|*
name|drawable
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|diff_init_luts
parameter_list|(
name|void
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|diff_diffract
parameter_list|(
name|gdouble
name|x
parameter_list|,
name|gdouble
name|y
parameter_list|,
name|GimpRGB
modifier|*
name|rgb
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|double
name|diff_point
parameter_list|(
name|gdouble
name|x
parameter_list|,
name|gdouble
name|y
parameter_list|,
name|gdouble
name|edges
parameter_list|,
name|gdouble
name|contours
parameter_list|,
name|gdouble
name|lam
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|double
name|diff_intensity
parameter_list|(
name|gdouble
name|x
parameter_list|,
name|gdouble
name|y
parameter_list|,
name|gdouble
name|lam
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|gboolean
name|diffraction_dialog
parameter_list|(
name|void
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|dialog_update_preview
parameter_list|(
name|void
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|dialog_update_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_comment
comment|/***** Variables *****/
end_comment

begin_decl_stmt
DECL|variable|PLUG_IN_INFO
specifier|const
name|GimpPlugInInfo
name|PLUG_IN_INFO
init|=
block|{
name|NULL
block|,
comment|/* init  */
name|NULL
block|,
comment|/* quit  */
name|query
block|,
comment|/* query */
name|run
comment|/* run   */
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|dvals
specifier|static
name|diffraction_vals_t
name|dvals
init|=
block|{
literal|0.815
block|,
comment|/* lam_r */
literal|1.221
block|,
comment|/* lam_g */
literal|1.123
block|,
comment|/* lam_b */
literal|0.821
block|,
comment|/* contour_r */
literal|0.821
block|,
comment|/* contour_g */
literal|0.974
block|,
comment|/* contour_b */
literal|0.610
block|,
comment|/* edges_r */
literal|0.677
block|,
comment|/* edges_g */
literal|0.636
block|,
comment|/* edges_b */
literal|0.066
block|,
comment|/* brightness */
literal|37.126
block|,
comment|/* scattering */
operator|-
literal|0.473
comment|/* polarization */
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|dint
specifier|static
name|diffraction_interface_t
name|dint
init|=
block|{
name|NULL
block|,
comment|/* preview */
name|NULL
block|,
comment|/* progress */
block|{
literal|0
block|}
comment|/* preview_buffer */
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|cos_lut
specifier|static
name|gdouble
name|cos_lut
index|[
name|ITERATIONS
operator|+
literal|1
index|]
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|param_lut1
specifier|static
name|gdouble
name|param_lut1
index|[
name|ITERATIONS
operator|+
literal|1
index|]
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|param_lut2
specifier|static
name|gdouble
name|param_lut2
index|[
name|ITERATIONS
operator|+
literal|1
index|]
decl_stmt|;
end_decl_stmt

begin_comment
comment|/***** Functions *****/
end_comment

begin_macro
DECL|function|MAIN ()
name|MAIN
argument_list|()
end_macro

begin_function
specifier|static
name|void
name|query
parameter_list|(
name|void
parameter_list|)
block|{
specifier|static
specifier|const
name|GimpParamDef
name|args
index|[]
init|=
block|{
block|{
name|GIMP_PDB_INT32
block|,
literal|"run-mode"
block|,
literal|"The run mode { RUN-INTERACTIVE (0), RUN-NONINTERACTIVE (1) }"
block|}
block|,
block|{
name|GIMP_PDB_IMAGE
block|,
literal|"image"
block|,
literal|"Input image"
block|}
block|,
block|{
name|GIMP_PDB_DRAWABLE
block|,
literal|"drawable"
block|,
literal|"Input drawable"
block|}
block|,
block|{
name|GIMP_PDB_FLOAT
block|,
literal|"lam-r"
block|,
literal|"Light frequency (red)"
block|}
block|,
block|{
name|GIMP_PDB_FLOAT
block|,
literal|"lam-g"
block|,
literal|"Light frequency (green)"
block|}
block|,
block|{
name|GIMP_PDB_FLOAT
block|,
literal|"lam-b"
block|,
literal|"Light frequency (blue)"
block|}
block|,
block|{
name|GIMP_PDB_FLOAT
block|,
literal|"contour-r"
block|,
literal|"Number of contours (red)"
block|}
block|,
block|{
name|GIMP_PDB_FLOAT
block|,
literal|"contour-g"
block|,
literal|"Number of contours (green)"
block|}
block|,
block|{
name|GIMP_PDB_FLOAT
block|,
literal|"contour-b"
block|,
literal|"Number of contours (blue)"
block|}
block|,
block|{
name|GIMP_PDB_FLOAT
block|,
literal|"edges-r"
block|,
literal|"Number of sharp edges (red)"
block|}
block|,
block|{
name|GIMP_PDB_FLOAT
block|,
literal|"edges-g"
block|,
literal|"Number of sharp edges (green)"
block|}
block|,
block|{
name|GIMP_PDB_FLOAT
block|,
literal|"edges-b"
block|,
literal|"Number of sharp edges (blue)"
block|}
block|,
block|{
name|GIMP_PDB_FLOAT
block|,
literal|"brightness"
block|,
literal|"Brightness and shifting/fattening of contours"
block|}
block|,
block|{
name|GIMP_PDB_FLOAT
block|,
literal|"scattering"
block|,
literal|"Scattering (Speed vs. quality)"
block|}
block|,
block|{
name|GIMP_PDB_FLOAT
block|,
literal|"polarization"
block|,
literal|"Polarization"
block|}
block|}
decl_stmt|;
name|gimp_install_procedure
argument_list|(
name|PLUG_IN_PROC
argument_list|,
name|N_
argument_list|(
literal|"Generate diffraction patterns"
argument_list|)
argument_list|,
literal|"Help?  What help?  Real men do not need help :-)"
argument_list|,
literal|"Federico Mena Quintero"
argument_list|,
literal|"Federico Mena Quintero& David Bleecker"
argument_list|,
literal|"April 1997, 0.5"
argument_list|,
name|N_
argument_list|(
literal|"_Diffraction Patterns..."
argument_list|)
argument_list|,
literal|"RGB*"
argument_list|,
name|GIMP_PLUGIN
argument_list|,
name|G_N_ELEMENTS
argument_list|(
name|args
argument_list|)
argument_list|,
literal|0
argument_list|,
name|args
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|gimp_plugin_menu_register
argument_list|(
name|PLUG_IN_PROC
argument_list|,
literal|"<Image>/Filters/Render/Pattern"
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|run (const gchar * name,gint nparams,const GimpParam * param,gint * nreturn_vals,GimpParam ** return_vals)
name|run
parameter_list|(
specifier|const
name|gchar
modifier|*
name|name
parameter_list|,
name|gint
name|nparams
parameter_list|,
specifier|const
name|GimpParam
modifier|*
name|param
parameter_list|,
name|gint
modifier|*
name|nreturn_vals
parameter_list|,
name|GimpParam
modifier|*
modifier|*
name|return_vals
parameter_list|)
block|{
specifier|static
name|GimpParam
name|values
index|[
literal|1
index|]
decl_stmt|;
name|GimpDrawable
modifier|*
name|active_drawable
decl_stmt|;
name|GimpPDBStatusType
name|status
decl_stmt|;
name|GimpRunMode
name|run_mode
decl_stmt|;
comment|/* Initialize */
name|INIT_I18N
argument_list|()
expr_stmt|;
name|diff_init_luts
argument_list|()
expr_stmt|;
name|status
operator|=
name|GIMP_PDB_SUCCESS
expr_stmt|;
name|run_mode
operator|=
name|param
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_int32
expr_stmt|;
name|values
index|[
literal|0
index|]
operator|.
name|type
operator|=
name|GIMP_PDB_STATUS
expr_stmt|;
name|values
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|=
name|status
expr_stmt|;
operator|*
name|nreturn_vals
operator|=
literal|1
expr_stmt|;
operator|*
name|return_vals
operator|=
name|values
expr_stmt|;
switch|switch
condition|(
name|run_mode
condition|)
block|{
case|case
name|GIMP_RUN_INTERACTIVE
case|:
comment|/* Possibly retrieve data */
name|gimp_get_data
argument_list|(
name|PLUG_IN_PROC
argument_list|,
operator|&
name|dvals
argument_list|)
expr_stmt|;
comment|/* Get information from the dialog */
if|if
condition|(
operator|!
name|diffraction_dialog
argument_list|()
condition|)
return|return;
break|break;
case|case
name|GIMP_RUN_NONINTERACTIVE
case|:
comment|/* Make sure all the arguments are present */
if|if
condition|(
name|nparams
operator|!=
literal|15
condition|)
name|status
operator|=
name|GIMP_PDB_CALLING_ERROR
expr_stmt|;
if|if
condition|(
name|status
operator|==
name|GIMP_PDB_SUCCESS
condition|)
block|{
name|dvals
operator|.
name|lam_r
operator|=
name|param
index|[
literal|3
index|]
operator|.
name|data
operator|.
name|d_float
expr_stmt|;
name|dvals
operator|.
name|lam_g
operator|=
name|param
index|[
literal|4
index|]
operator|.
name|data
operator|.
name|d_float
expr_stmt|;
name|dvals
operator|.
name|lam_b
operator|=
name|param
index|[
literal|5
index|]
operator|.
name|data
operator|.
name|d_float
expr_stmt|;
name|dvals
operator|.
name|contour_r
operator|=
name|param
index|[
literal|6
index|]
operator|.
name|data
operator|.
name|d_float
expr_stmt|;
name|dvals
operator|.
name|contour_g
operator|=
name|param
index|[
literal|7
index|]
operator|.
name|data
operator|.
name|d_float
expr_stmt|;
name|dvals
operator|.
name|contour_b
operator|=
name|param
index|[
literal|8
index|]
operator|.
name|data
operator|.
name|d_float
expr_stmt|;
name|dvals
operator|.
name|edges_r
operator|=
name|param
index|[
literal|9
index|]
operator|.
name|data
operator|.
name|d_float
expr_stmt|;
name|dvals
operator|.
name|edges_g
operator|=
name|param
index|[
literal|10
index|]
operator|.
name|data
operator|.
name|d_float
expr_stmt|;
name|dvals
operator|.
name|edges_b
operator|=
name|param
index|[
literal|11
index|]
operator|.
name|data
operator|.
name|d_float
expr_stmt|;
name|dvals
operator|.
name|brightness
operator|=
name|param
index|[
literal|12
index|]
operator|.
name|data
operator|.
name|d_float
expr_stmt|;
name|dvals
operator|.
name|scattering
operator|=
name|param
index|[
literal|13
index|]
operator|.
name|data
operator|.
name|d_float
expr_stmt|;
name|dvals
operator|.
name|polarization
operator|=
name|param
index|[
literal|14
index|]
operator|.
name|data
operator|.
name|d_float
expr_stmt|;
block|}
break|break;
case|case
name|GIMP_RUN_WITH_LAST_VALS
case|:
comment|/* Possibly retrieve data */
name|gimp_get_data
argument_list|(
name|PLUG_IN_PROC
argument_list|,
operator|&
name|dvals
argument_list|)
expr_stmt|;
break|break;
default|default:
break|break;
block|}
comment|/* Get the active drawable */
name|active_drawable
operator|=
name|gimp_drawable_get
argument_list|(
name|param
index|[
literal|2
index|]
operator|.
name|data
operator|.
name|d_drawable
argument_list|)
expr_stmt|;
comment|/* Create the diffraction pattern */
if|if
condition|(
operator|(
name|status
operator|==
name|GIMP_PDB_SUCCESS
operator|)
operator|&&
name|gimp_drawable_is_rgb
argument_list|(
name|active_drawable
operator|->
name|drawable_id
argument_list|)
condition|)
block|{
comment|/* Set the tile cache size */
name|gimp_tile_cache_ntiles
argument_list|(
operator|(
name|active_drawable
operator|->
name|width
operator|+
name|gimp_tile_width
argument_list|()
operator|-
literal|1
operator|)
operator|/
name|gimp_tile_width
argument_list|()
argument_list|)
expr_stmt|;
comment|/* Run! */
name|diffraction
argument_list|(
name|active_drawable
argument_list|)
expr_stmt|;
comment|/* If run mode is interactive, flush displays */
if|if
condition|(
name|run_mode
operator|!=
name|GIMP_RUN_NONINTERACTIVE
condition|)
name|gimp_displays_flush
argument_list|()
expr_stmt|;
comment|/* Store data */
if|if
condition|(
name|run_mode
operator|==
name|GIMP_RUN_INTERACTIVE
condition|)
name|gimp_set_data
argument_list|(
name|PLUG_IN_PROC
argument_list|,
operator|&
name|dvals
argument_list|,
sizeof|sizeof
argument_list|(
name|diffraction_vals_t
argument_list|)
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|status
operator|==
name|GIMP_PDB_SUCCESS
condition|)
block|{
name|status
operator|=
name|GIMP_PDB_EXECUTION_ERROR
expr_stmt|;
block|}
name|values
index|[
literal|0
index|]
operator|.
name|data
operator|.
name|d_status
operator|=
name|status
expr_stmt|;
name|gimp_drawable_detach
argument_list|(
name|active_drawable
argument_list|)
expr_stmt|;
block|}
end_function

begin_typedef
DECL|struct|__anon275c237c0308
typedef|typedef
struct|struct
block|{
DECL|member|dhoriz
name|gdouble
name|dhoriz
decl_stmt|;
DECL|member|dvert
name|gdouble
name|dvert
decl_stmt|;
DECL|member|x
name|gint
name|x
decl_stmt|;
DECL|member|y
name|gint
name|y
decl_stmt|;
DECL|typedef|DiffractionParam_t
block|}
name|DiffractionParam_t
typedef|;
end_typedef

begin_function
specifier|static
name|void
DECL|function|diffraction_func (gint x,gint y,guchar * dest,gint bpp,gpointer data)
name|diffraction_func
parameter_list|(
name|gint
name|x
parameter_list|,
name|gint
name|y
parameter_list|,
name|guchar
modifier|*
name|dest
parameter_list|,
name|gint
name|bpp
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|DiffractionParam_t
modifier|*
name|param
init|=
operator|(
name|DiffractionParam_t
operator|*
operator|)
name|data
decl_stmt|;
name|gdouble
name|px
decl_stmt|,
name|py
decl_stmt|;
name|GimpRGB
name|rgb
decl_stmt|;
name|px
operator|=
operator|-
literal|5.0
operator|+
name|param
operator|->
name|dhoriz
operator|*
operator|(
name|x
operator|-
name|param
operator|->
name|x
operator|)
expr_stmt|;
name|py
operator|=
literal|5.0
operator|+
name|param
operator|->
name|dvert
operator|*
operator|(
name|y
operator|-
name|param
operator|->
name|y
operator|)
expr_stmt|;
name|diff_diffract
argument_list|(
name|px
argument_list|,
name|py
argument_list|,
operator|&
name|rgb
argument_list|)
expr_stmt|;
name|dest
index|[
literal|0
index|]
operator|=
literal|255.0
operator|*
name|rgb
operator|.
name|r
expr_stmt|;
name|dest
index|[
literal|1
index|]
operator|=
literal|255.0
operator|*
name|rgb
operator|.
name|g
expr_stmt|;
name|dest
index|[
literal|2
index|]
operator|=
literal|255.0
operator|*
name|rgb
operator|.
name|b
expr_stmt|;
if|if
condition|(
name|bpp
operator|==
literal|4
condition|)
name|dest
index|[
literal|3
index|]
operator|=
literal|255
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|diffraction (GimpDrawable * drawable)
name|diffraction
parameter_list|(
name|GimpDrawable
modifier|*
name|drawable
parameter_list|)
block|{
name|GimpRgnIterator
modifier|*
name|iter
decl_stmt|;
name|DiffractionParam_t
name|param
decl_stmt|;
name|gint
name|x
decl_stmt|,
name|y
decl_stmt|,
name|width
decl_stmt|,
name|height
decl_stmt|;
if|if
condition|(
operator|!
name|gimp_drawable_mask_intersect
argument_list|(
name|drawable
operator|->
name|drawable_id
argument_list|,
operator|&
name|x
argument_list|,
operator|&
name|y
argument_list|,
operator|&
name|width
argument_list|,
operator|&
name|height
argument_list|)
condition|)
block|{
return|return;
block|}
name|param
operator|.
name|x
operator|=
name|x
expr_stmt|;
name|param
operator|.
name|y
operator|=
name|y
expr_stmt|;
name|param
operator|.
name|dhoriz
operator|=
literal|10.0
operator|/
operator|(
name|width
operator|-
literal|1
operator|)
expr_stmt|;
name|param
operator|.
name|dvert
operator|=
operator|-
literal|10.0
operator|/
operator|(
name|height
operator|-
literal|1
operator|)
expr_stmt|;
name|gimp_progress_init
argument_list|(
name|_
argument_list|(
literal|"Creating diffraction pattern"
argument_list|)
argument_list|)
expr_stmt|;
name|iter
operator|=
name|gimp_rgn_iterator_new
argument_list|(
name|drawable
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gimp_rgn_iterator_dest
argument_list|(
name|iter
argument_list|,
name|diffraction_func
argument_list|,
operator|&
name|param
argument_list|)
expr_stmt|;
name|gimp_rgn_iterator_free
argument_list|(
name|iter
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|diff_init_luts (void)
name|diff_init_luts
parameter_list|(
name|void
parameter_list|)
block|{
name|int
name|i
decl_stmt|;
name|double
name|a
decl_stmt|;
name|double
name|sina
decl_stmt|;
name|a
operator|=
operator|-
name|G_PI
expr_stmt|;
for|for
control|(
name|i
operator|=
literal|0
init|;
name|i
operator|<=
name|ITERATIONS
condition|;
name|i
operator|++
control|)
block|{
name|sina
operator|=
name|sin
argument_list|(
name|a
argument_list|)
expr_stmt|;
name|cos_lut
index|[
name|i
index|]
operator|=
name|cos
argument_list|(
name|a
argument_list|)
expr_stmt|;
name|param_lut1
index|[
name|i
index|]
operator|=
literal|0.75
operator|*
name|sina
expr_stmt|;
name|param_lut2
index|[
name|i
index|]
operator|=
literal|0.5
operator|*
operator|(
literal|4.0
operator|*
name|cos_lut
index|[
name|i
index|]
operator|*
name|cos_lut
index|[
name|i
index|]
operator|+
name|sina
operator|*
name|sina
operator|)
expr_stmt|;
name|a
operator|+=
operator|(
literal|2.0
operator|*
name|G_PI
operator|/
name|ITERATIONS
operator|)
expr_stmt|;
block|}
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|diff_diffract (double x,double y,GimpRGB * rgb)
name|diff_diffract
parameter_list|(
name|double
name|x
parameter_list|,
name|double
name|y
parameter_list|,
name|GimpRGB
modifier|*
name|rgb
parameter_list|)
block|{
name|rgb
operator|->
name|r
operator|=
name|diff_point
argument_list|(
name|x
argument_list|,
name|y
argument_list|,
name|dvals
operator|.
name|edges_r
argument_list|,
name|dvals
operator|.
name|contour_r
argument_list|,
name|dvals
operator|.
name|lam_r
argument_list|)
expr_stmt|;
name|rgb
operator|->
name|g
operator|=
name|diff_point
argument_list|(
name|x
argument_list|,
name|y
argument_list|,
name|dvals
operator|.
name|edges_g
argument_list|,
name|dvals
operator|.
name|contour_g
argument_list|,
name|dvals
operator|.
name|lam_g
argument_list|)
expr_stmt|;
name|rgb
operator|->
name|b
operator|=
name|diff_point
argument_list|(
name|x
argument_list|,
name|y
argument_list|,
name|dvals
operator|.
name|edges_b
argument_list|,
name|dvals
operator|.
name|contour_b
argument_list|,
name|dvals
operator|.
name|lam_b
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|double
DECL|function|diff_point (double x,double y,double edges,double contours,double lam)
name|diff_point
parameter_list|(
name|double
name|x
parameter_list|,
name|double
name|y
parameter_list|,
name|double
name|edges
parameter_list|,
name|double
name|contours
parameter_list|,
name|double
name|lam
parameter_list|)
block|{
return|return
name|fabs
argument_list|(
name|edges
operator|*
name|sin
argument_list|(
name|contours
operator|*
name|atan
argument_list|(
name|dvals
operator|.
name|brightness
operator|*
name|diff_intensity
argument_list|(
name|x
argument_list|,
name|y
argument_list|,
name|lam
argument_list|)
argument_list|)
argument_list|)
argument_list|)
return|;
block|}
end_function

begin_function
specifier|static
name|double
DECL|function|diff_intensity (double x,double y,double lam)
name|diff_intensity
parameter_list|(
name|double
name|x
parameter_list|,
name|double
name|y
parameter_list|,
name|double
name|lam
parameter_list|)
block|{
name|int
name|i
decl_stmt|;
name|double
name|cxy
decl_stmt|,
name|sxy
decl_stmt|;
name|double
name|param
decl_stmt|;
name|double
name|polpi2
decl_stmt|;
name|double
name|cospolpi2
decl_stmt|,
name|sinpolpi2
decl_stmt|;
name|cxy
operator|=
literal|0.0
expr_stmt|;
name|sxy
operator|=
literal|0.0
expr_stmt|;
name|lam
operator|*=
literal|4.0
expr_stmt|;
for|for
control|(
name|i
operator|=
literal|0
init|;
name|i
operator|<=
name|ITERATIONS
condition|;
name|i
operator|++
control|)
block|{
name|param
operator|=
name|lam
operator|*
operator|(
name|cos_lut
index|[
name|i
index|]
operator|*
name|x
operator|+
name|param_lut1
index|[
name|i
index|]
operator|*
name|y
operator|-
name|param_lut2
index|[
name|i
index|]
operator|)
expr_stmt|;
name|cxy
operator|+=
name|cos
argument_list|(
name|param
argument_list|)
expr_stmt|;
name|sxy
operator|+=
name|sin
argument_list|(
name|param
argument_list|)
expr_stmt|;
block|}
name|cxy
operator|*=
name|WEIRD_FACTOR
expr_stmt|;
name|sxy
operator|*=
name|WEIRD_FACTOR
expr_stmt|;
name|polpi2
operator|=
name|dvals
operator|.
name|polarization
operator|*
operator|(
name|G_PI
operator|/
literal|2.0
operator|)
expr_stmt|;
name|cospolpi2
operator|=
name|cos
argument_list|(
name|polpi2
argument_list|)
expr_stmt|;
name|sinpolpi2
operator|=
name|sin
argument_list|(
name|polpi2
argument_list|)
expr_stmt|;
return|return
name|dvals
operator|.
name|scattering
operator|*
operator|(
operator|(
name|cospolpi2
operator|+
name|sinpolpi2
operator|)
operator|*
name|cxy
operator|*
name|cxy
operator|+
operator|(
name|cospolpi2
operator|-
name|sinpolpi2
operator|)
operator|*
name|sxy
operator|*
name|sxy
operator|)
return|;
block|}
end_function

begin_function
specifier|static
name|gboolean
DECL|function|diffraction_dialog (void)
name|diffraction_dialog
parameter_list|(
name|void
parameter_list|)
block|{
name|GtkWidget
modifier|*
name|dialog
decl_stmt|;
name|GtkWidget
modifier|*
name|hbox
decl_stmt|;
name|GtkWidget
modifier|*
name|notebook
decl_stmt|;
name|GtkWidget
modifier|*
name|frame
decl_stmt|;
name|GtkWidget
modifier|*
name|vbox
decl_stmt|;
name|GtkWidget
modifier|*
name|table
decl_stmt|;
name|GtkWidget
modifier|*
name|label
decl_stmt|;
name|GtkWidget
modifier|*
name|button
decl_stmt|;
name|GtkObject
modifier|*
name|adj
decl_stmt|;
name|gboolean
name|run
decl_stmt|;
name|gimp_ui_init
argument_list|(
name|PLUG_IN_BINARY
argument_list|,
name|TRUE
argument_list|)
expr_stmt|;
name|dialog
operator|=
name|gimp_dialog_new
argument_list|(
name|_
argument_list|(
literal|"Diffraction Patterns"
argument_list|)
argument_list|,
name|PLUG_IN_ROLE
argument_list|,
name|NULL
argument_list|,
literal|0
argument_list|,
name|gimp_standard_help_func
argument_list|,
name|PLUG_IN_PROC
argument_list|,
name|GTK_STOCK_CANCEL
argument_list|,
name|GTK_RESPONSE_CANCEL
argument_list|,
name|GTK_STOCK_OK
argument_list|,
name|GTK_RESPONSE_OK
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|gtk_dialog_set_alternative_button_order
argument_list|(
name|GTK_DIALOG
argument_list|(
name|dialog
argument_list|)
argument_list|,
name|GTK_RESPONSE_OK
argument_list|,
name|GTK_RESPONSE_CANCEL
argument_list|,
operator|-
literal|1
argument_list|)
expr_stmt|;
name|gimp_window_set_transient
argument_list|(
name|GTK_WINDOW
argument_list|(
name|dialog
argument_list|)
argument_list|)
expr_stmt|;
name|hbox
operator|=
name|gtk_hbox_new
argument_list|(
name|FALSE
argument_list|,
literal|12
argument_list|)
expr_stmt|;
name|gtk_container_set_border_width
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|hbox
argument_list|)
argument_list|,
literal|12
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|gtk_dialog_get_content_area
argument_list|(
name|GTK_DIALOG
argument_list|(
name|dialog
argument_list|)
argument_list|)
argument_list|)
argument_list|,
name|hbox
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|hbox
argument_list|)
expr_stmt|;
comment|/* Preview */
name|vbox
operator|=
name|gtk_vbox_new
argument_list|(
name|FALSE
argument_list|,
literal|2
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|hbox
argument_list|)
argument_list|,
name|vbox
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|vbox
argument_list|)
expr_stmt|;
name|frame
operator|=
name|gtk_aspect_frame_new
argument_list|(
name|NULL
argument_list|,
literal|0.5
argument_list|,
literal|0.5
argument_list|,
literal|1.0
argument_list|,
name|TRUE
argument_list|)
expr_stmt|;
name|gtk_frame_set_shadow_type
argument_list|(
name|GTK_FRAME
argument_list|(
name|frame
argument_list|)
argument_list|,
name|GTK_SHADOW_IN
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|vbox
argument_list|)
argument_list|,
name|frame
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|frame
argument_list|)
expr_stmt|;
name|dint
operator|.
name|preview
operator|=
name|gimp_preview_area_new
argument_list|()
expr_stmt|;
name|gtk_widget_set_size_request
argument_list|(
name|dint
operator|.
name|preview
argument_list|,
name|PREVIEW_WIDTH
argument_list|,
name|PREVIEW_HEIGHT
argument_list|)
expr_stmt|;
name|gtk_container_add
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|frame
argument_list|)
argument_list|,
name|dint
operator|.
name|preview
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|dint
operator|.
name|preview
argument_list|)
expr_stmt|;
name|dint
operator|.
name|progress
operator|=
name|gtk_progress_bar_new
argument_list|()
expr_stmt|;
name|gtk_widget_set_size_request
argument_list|(
name|dint
operator|.
name|progress
argument_list|,
name|PROGRESS_WIDTH
argument_list|,
name|PROGRESS_HEIGHT
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|vbox
argument_list|)
argument_list|,
name|dint
operator|.
name|progress
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|dint
operator|.
name|progress
argument_list|)
expr_stmt|;
name|button
operator|=
name|gtk_button_new_with_mnemonic
argument_list|(
name|_
argument_list|(
literal|"_Preview!"
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|vbox
argument_list|)
argument_list|,
name|button
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|button
argument_list|)
expr_stmt|;
name|g_signal_connect
argument_list|(
name|button
argument_list|,
literal|"clicked"
argument_list|,
name|G_CALLBACK
argument_list|(
name|dialog_update_callback
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
comment|/* Notebook */
name|notebook
operator|=
name|gtk_notebook_new
argument_list|()
expr_stmt|;
name|gtk_notebook_set_tab_pos
argument_list|(
name|GTK_NOTEBOOK
argument_list|(
name|notebook
argument_list|)
argument_list|,
name|GTK_POS_TOP
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|hbox
argument_list|)
argument_list|,
name|notebook
argument_list|,
name|TRUE
argument_list|,
name|TRUE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|notebook
argument_list|)
expr_stmt|;
comment|/* Frequencies tab */
name|table
operator|=
name|gtk_table_new
argument_list|(
literal|3
argument_list|,
literal|3
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gtk_table_set_col_spacings
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|6
argument_list|)
expr_stmt|;
name|gtk_table_set_row_spacings
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|6
argument_list|)
expr_stmt|;
name|gtk_container_set_border_width
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|table
argument_list|)
argument_list|,
literal|12
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|table
argument_list|)
expr_stmt|;
name|adj
operator|=
name|gimp_scale_entry_new
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
name|_
argument_list|(
literal|"_Red:"
argument_list|)
argument_list|,
name|SCALE_WIDTH
argument_list|,
literal|0
argument_list|,
name|dvals
operator|.
name|lam_r
argument_list|,
literal|0.0
argument_list|,
literal|20.0
argument_list|,
literal|0.2
argument_list|,
literal|1.0
argument_list|,
literal|3
argument_list|,
name|TRUE
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_signal_connect
argument_list|(
name|adj
argument_list|,
literal|"value-changed"
argument_list|,
name|G_CALLBACK
argument_list|(
name|gimp_double_adjustment_update
argument_list|)
argument_list|,
operator|&
name|dvals
operator|.
name|lam_r
argument_list|)
expr_stmt|;
name|adj
operator|=
name|gimp_scale_entry_new
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|0
argument_list|,
literal|1
argument_list|,
name|_
argument_list|(
literal|"_Green:"
argument_list|)
argument_list|,
name|SCALE_WIDTH
argument_list|,
literal|0
argument_list|,
name|dvals
operator|.
name|lam_g
argument_list|,
literal|0.0
argument_list|,
literal|20.0
argument_list|,
literal|0.2
argument_list|,
literal|1.0
argument_list|,
literal|3
argument_list|,
name|TRUE
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_signal_connect
argument_list|(
name|adj
argument_list|,
literal|"value-changed"
argument_list|,
name|G_CALLBACK
argument_list|(
name|gimp_double_adjustment_update
argument_list|)
argument_list|,
operator|&
name|dvals
operator|.
name|lam_g
argument_list|)
expr_stmt|;
name|adj
operator|=
name|gimp_scale_entry_new
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|0
argument_list|,
literal|2
argument_list|,
name|_
argument_list|(
literal|"_Blue:"
argument_list|)
argument_list|,
name|SCALE_WIDTH
argument_list|,
literal|0
argument_list|,
name|dvals
operator|.
name|lam_b
argument_list|,
literal|0.0
argument_list|,
literal|20.0
argument_list|,
literal|0.2
argument_list|,
literal|1.0
argument_list|,
literal|3
argument_list|,
name|TRUE
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_signal_connect
argument_list|(
name|adj
argument_list|,
literal|"value-changed"
argument_list|,
name|G_CALLBACK
argument_list|(
name|gimp_double_adjustment_update
argument_list|)
argument_list|,
operator|&
name|dvals
operator|.
name|lam_b
argument_list|)
expr_stmt|;
name|label
operator|=
name|gtk_label_new_with_mnemonic
argument_list|(
name|_
argument_list|(
literal|"Frequencies"
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_notebook_append_page
argument_list|(
name|GTK_NOTEBOOK
argument_list|(
name|notebook
argument_list|)
argument_list|,
name|table
argument_list|,
name|label
argument_list|)
expr_stmt|;
comment|/* Contours tab */
name|table
operator|=
name|gtk_table_new
argument_list|(
literal|3
argument_list|,
literal|3
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gtk_table_set_col_spacings
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|6
argument_list|)
expr_stmt|;
name|gtk_table_set_row_spacings
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|6
argument_list|)
expr_stmt|;
name|gtk_container_set_border_width
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|table
argument_list|)
argument_list|,
literal|12
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|table
argument_list|)
expr_stmt|;
name|adj
operator|=
name|gimp_scale_entry_new
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
name|_
argument_list|(
literal|"_Red:"
argument_list|)
argument_list|,
name|SCALE_WIDTH
argument_list|,
literal|0
argument_list|,
name|dvals
operator|.
name|contour_r
argument_list|,
literal|0.0
argument_list|,
literal|10.0
argument_list|,
literal|0.1
argument_list|,
literal|1.0
argument_list|,
literal|3
argument_list|,
name|TRUE
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_signal_connect
argument_list|(
name|adj
argument_list|,
literal|"value-changed"
argument_list|,
name|G_CALLBACK
argument_list|(
name|gimp_double_adjustment_update
argument_list|)
argument_list|,
operator|&
name|dvals
operator|.
name|contour_r
argument_list|)
expr_stmt|;
name|adj
operator|=
name|gimp_scale_entry_new
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|0
argument_list|,
literal|1
argument_list|,
name|_
argument_list|(
literal|"_Green:"
argument_list|)
argument_list|,
name|SCALE_WIDTH
argument_list|,
literal|0
argument_list|,
name|dvals
operator|.
name|contour_g
argument_list|,
literal|0.0
argument_list|,
literal|10.0
argument_list|,
literal|0.1
argument_list|,
literal|1.0
argument_list|,
literal|3
argument_list|,
name|TRUE
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_signal_connect
argument_list|(
name|adj
argument_list|,
literal|"value-changed"
argument_list|,
name|G_CALLBACK
argument_list|(
name|gimp_double_adjustment_update
argument_list|)
argument_list|,
operator|&
name|dvals
operator|.
name|contour_g
argument_list|)
expr_stmt|;
name|adj
operator|=
name|gimp_scale_entry_new
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|0
argument_list|,
literal|2
argument_list|,
name|_
argument_list|(
literal|"_Blue:"
argument_list|)
argument_list|,
name|SCALE_WIDTH
argument_list|,
literal|0
argument_list|,
name|dvals
operator|.
name|contour_b
argument_list|,
literal|0.0
argument_list|,
literal|10.0
argument_list|,
literal|0.1
argument_list|,
literal|1.0
argument_list|,
literal|3
argument_list|,
name|TRUE
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_signal_connect
argument_list|(
name|adj
argument_list|,
literal|"value-changed"
argument_list|,
name|G_CALLBACK
argument_list|(
name|gimp_double_adjustment_update
argument_list|)
argument_list|,
operator|&
name|dvals
operator|.
name|contour_b
argument_list|)
expr_stmt|;
name|label
operator|=
name|gtk_label_new_with_mnemonic
argument_list|(
name|_
argument_list|(
literal|"Contours"
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_notebook_append_page
argument_list|(
name|GTK_NOTEBOOK
argument_list|(
name|notebook
argument_list|)
argument_list|,
name|table
argument_list|,
name|label
argument_list|)
expr_stmt|;
comment|/* Sharp edges tab */
name|table
operator|=
name|gtk_table_new
argument_list|(
literal|3
argument_list|,
literal|2
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gtk_table_set_col_spacings
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|6
argument_list|)
expr_stmt|;
name|gtk_table_set_row_spacings
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|6
argument_list|)
expr_stmt|;
name|gtk_container_set_border_width
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|table
argument_list|)
argument_list|,
literal|12
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|table
argument_list|)
expr_stmt|;
name|adj
operator|=
name|gimp_scale_entry_new
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
name|_
argument_list|(
literal|"_Red:"
argument_list|)
argument_list|,
name|SCALE_WIDTH
argument_list|,
literal|0
argument_list|,
name|dvals
operator|.
name|edges_r
argument_list|,
literal|0.0
argument_list|,
literal|1.0
argument_list|,
literal|0.01
argument_list|,
literal|0.1
argument_list|,
literal|3
argument_list|,
name|TRUE
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_signal_connect
argument_list|(
name|adj
argument_list|,
literal|"value-changed"
argument_list|,
name|G_CALLBACK
argument_list|(
name|gimp_double_adjustment_update
argument_list|)
argument_list|,
operator|&
name|dvals
operator|.
name|edges_r
argument_list|)
expr_stmt|;
name|adj
operator|=
name|gimp_scale_entry_new
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|0
argument_list|,
literal|1
argument_list|,
name|_
argument_list|(
literal|"_Green:"
argument_list|)
argument_list|,
name|SCALE_WIDTH
argument_list|,
literal|0
argument_list|,
name|dvals
operator|.
name|edges_g
argument_list|,
literal|0.0
argument_list|,
literal|1.0
argument_list|,
literal|0.01
argument_list|,
literal|0.1
argument_list|,
literal|3
argument_list|,
name|TRUE
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_signal_connect
argument_list|(
name|adj
argument_list|,
literal|"value-changed"
argument_list|,
name|G_CALLBACK
argument_list|(
name|gimp_double_adjustment_update
argument_list|)
argument_list|,
operator|&
name|dvals
operator|.
name|edges_g
argument_list|)
expr_stmt|;
name|adj
operator|=
name|gimp_scale_entry_new
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|0
argument_list|,
literal|2
argument_list|,
name|_
argument_list|(
literal|"_Blue:"
argument_list|)
argument_list|,
name|SCALE_WIDTH
argument_list|,
literal|0
argument_list|,
name|dvals
operator|.
name|edges_b
argument_list|,
literal|0.0
argument_list|,
literal|1.0
argument_list|,
literal|0.01
argument_list|,
literal|0.1
argument_list|,
literal|3
argument_list|,
name|TRUE
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_signal_connect
argument_list|(
name|adj
argument_list|,
literal|"value-changed"
argument_list|,
name|G_CALLBACK
argument_list|(
name|gimp_double_adjustment_update
argument_list|)
argument_list|,
operator|&
name|dvals
operator|.
name|edges_b
argument_list|)
expr_stmt|;
name|label
operator|=
name|gtk_label_new_with_mnemonic
argument_list|(
name|_
argument_list|(
literal|"Sharp Edges"
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_notebook_append_page
argument_list|(
name|GTK_NOTEBOOK
argument_list|(
name|notebook
argument_list|)
argument_list|,
name|table
argument_list|,
name|label
argument_list|)
expr_stmt|;
comment|/* Other options tab */
name|table
operator|=
name|gtk_table_new
argument_list|(
literal|3
argument_list|,
literal|2
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gtk_table_set_col_spacings
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|6
argument_list|)
expr_stmt|;
name|gtk_table_set_row_spacings
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|6
argument_list|)
expr_stmt|;
name|gtk_container_set_border_width
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|table
argument_list|)
argument_list|,
literal|12
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|table
argument_list|)
expr_stmt|;
name|adj
operator|=
name|gimp_scale_entry_new
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
name|_
argument_list|(
literal|"_Brightness:"
argument_list|)
argument_list|,
name|SCALE_WIDTH
argument_list|,
literal|7
argument_list|,
name|dvals
operator|.
name|brightness
argument_list|,
literal|0.0
argument_list|,
literal|1.0
argument_list|,
literal|0.01
argument_list|,
literal|0.1
argument_list|,
literal|3
argument_list|,
name|TRUE
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_signal_connect
argument_list|(
name|adj
argument_list|,
literal|"value-changed"
argument_list|,
name|G_CALLBACK
argument_list|(
name|gimp_double_adjustment_update
argument_list|)
argument_list|,
operator|&
name|dvals
operator|.
name|brightness
argument_list|)
expr_stmt|;
name|adj
operator|=
name|gimp_scale_entry_new
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|0
argument_list|,
literal|1
argument_list|,
name|_
argument_list|(
literal|"Sc_attering:"
argument_list|)
argument_list|,
name|SCALE_WIDTH
argument_list|,
literal|7
argument_list|,
name|dvals
operator|.
name|scattering
argument_list|,
literal|0.0
argument_list|,
literal|100.0
argument_list|,
literal|1.0
argument_list|,
literal|10.0
argument_list|,
literal|3
argument_list|,
name|TRUE
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_signal_connect
argument_list|(
name|adj
argument_list|,
literal|"value-changed"
argument_list|,
name|G_CALLBACK
argument_list|(
name|gimp_double_adjustment_update
argument_list|)
argument_list|,
operator|&
name|dvals
operator|.
name|scattering
argument_list|)
expr_stmt|;
name|adj
operator|=
name|gimp_scale_entry_new
argument_list|(
name|GTK_TABLE
argument_list|(
name|table
argument_list|)
argument_list|,
literal|0
argument_list|,
literal|2
argument_list|,
name|_
argument_list|(
literal|"Po_larization:"
argument_list|)
argument_list|,
name|SCALE_WIDTH
argument_list|,
literal|7
argument_list|,
name|dvals
operator|.
name|polarization
argument_list|,
operator|-
literal|1.0
argument_list|,
literal|1.0
argument_list|,
literal|0.02
argument_list|,
literal|0.2
argument_list|,
literal|3
argument_list|,
name|TRUE
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_signal_connect
argument_list|(
name|adj
argument_list|,
literal|"value-changed"
argument_list|,
name|G_CALLBACK
argument_list|(
name|gimp_double_adjustment_update
argument_list|)
argument_list|,
operator|&
name|dvals
operator|.
name|polarization
argument_list|)
expr_stmt|;
name|label
operator|=
name|gtk_label_new_with_mnemonic
argument_list|(
name|_
argument_list|(
literal|"Other Options"
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_notebook_append_page
argument_list|(
name|GTK_NOTEBOOK
argument_list|(
name|notebook
argument_list|)
argument_list|,
name|table
argument_list|,
name|label
argument_list|)
expr_stmt|;
comment|/* Done */
name|gtk_widget_show
argument_list|(
name|dialog
argument_list|)
expr_stmt|;
name|dialog_update_preview
argument_list|()
expr_stmt|;
name|run
operator|=
operator|(
name|gimp_dialog_run
argument_list|(
name|GIMP_DIALOG
argument_list|(
name|dialog
argument_list|)
argument_list|)
operator|==
name|GTK_RESPONSE_OK
operator|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|dialog
argument_list|)
expr_stmt|;
return|return
name|run
return|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|dialog_update_preview (void)
name|dialog_update_preview
parameter_list|(
name|void
parameter_list|)
block|{
name|double
name|left
decl_stmt|,
name|right
decl_stmt|,
name|bottom
decl_stmt|,
name|top
decl_stmt|;
name|double
name|px
decl_stmt|,
name|py
decl_stmt|;
name|double
name|dx
decl_stmt|,
name|dy
decl_stmt|;
name|GimpRGB
name|rgb
decl_stmt|;
name|int
name|x
decl_stmt|,
name|y
decl_stmt|;
name|guchar
modifier|*
name|p
decl_stmt|;
name|left
operator|=
operator|-
literal|5.0
expr_stmt|;
name|right
operator|=
literal|5.0
expr_stmt|;
name|bottom
operator|=
operator|-
literal|5.0
expr_stmt|;
name|top
operator|=
literal|5.0
expr_stmt|;
name|dx
operator|=
operator|(
name|right
operator|-
name|left
operator|)
operator|/
operator|(
name|PREVIEW_WIDTH
operator|-
literal|1
operator|)
expr_stmt|;
name|dy
operator|=
operator|(
name|bottom
operator|-
name|top
operator|)
operator|/
operator|(
name|PREVIEW_HEIGHT
operator|-
literal|1
operator|)
expr_stmt|;
name|py
operator|=
name|top
expr_stmt|;
name|p
operator|=
name|dint
operator|.
name|preview_buffer
expr_stmt|;
for|for
control|(
name|y
operator|=
literal|0
init|;
name|y
operator|<
name|PREVIEW_HEIGHT
condition|;
name|y
operator|++
control|)
block|{
name|px
operator|=
name|left
expr_stmt|;
for|for
control|(
name|x
operator|=
literal|0
init|;
name|x
operator|<
name|PREVIEW_WIDTH
condition|;
name|x
operator|++
control|)
block|{
name|diff_diffract
argument_list|(
name|px
argument_list|,
name|py
argument_list|,
operator|&
name|rgb
argument_list|)
expr_stmt|;
operator|*
name|p
operator|++
operator|=
literal|255.0
operator|*
name|rgb
operator|.
name|r
expr_stmt|;
operator|*
name|p
operator|++
operator|=
literal|255.0
operator|*
name|rgb
operator|.
name|g
expr_stmt|;
operator|*
name|p
operator|++
operator|=
literal|255.0
operator|*
name|rgb
operator|.
name|b
expr_stmt|;
name|px
operator|+=
name|dx
expr_stmt|;
block|}
if|if
condition|(
operator|(
name|y
operator|%
literal|10
operator|)
operator|==
literal|0
condition|)
block|{
name|gtk_progress_bar_set_fraction
argument_list|(
name|GTK_PROGRESS_BAR
argument_list|(
name|dint
operator|.
name|progress
argument_list|)
argument_list|,
operator|(
name|gdouble
operator|)
name|y
operator|/
call|(
name|gdouble
call|)
argument_list|(
name|PREVIEW_HEIGHT
operator|-
literal|1
argument_list|)
argument_list|)
expr_stmt|;
while|while
condition|(
name|gtk_events_pending
argument_list|()
condition|)
name|gtk_main_iteration
argument_list|()
expr_stmt|;
block|}
name|py
operator|+=
name|dy
expr_stmt|;
block|}
name|gimp_preview_area_draw
argument_list|(
name|GIMP_PREVIEW_AREA
argument_list|(
name|dint
operator|.
name|preview
argument_list|)
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
name|PREVIEW_WIDTH
argument_list|,
name|PREVIEW_HEIGHT
argument_list|,
name|GIMP_RGB_IMAGE
argument_list|,
name|dint
operator|.
name|preview_buffer
argument_list|,
literal|3
operator|*
name|PREVIEW_WIDTH
argument_list|)
expr_stmt|;
name|gtk_progress_bar_set_fraction
argument_list|(
name|GTK_PROGRESS_BAR
argument_list|(
name|dint
operator|.
name|progress
argument_list|)
argument_list|,
literal|0.0
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|dialog_update_callback (GtkWidget * widget,gpointer data)
name|dialog_update_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|dialog_update_preview
argument_list|()
expr_stmt|;
block|}
end_function

end_unit

