begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* The GIMP -- an image manipulation program  * Copyright (C) 1995 Spencer Kimball and Peter Mattis  *  * This program is free software; you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 2 of the License, or  * (at your option) any later version.  *  * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *  * You should have received a copy of the GNU General Public License  * along with this program; if not, write to the Free Software  * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  */
end_comment

begin_include
include|#
directive|include
file|"config.h"
end_include

begin_include
include|#
directive|include
file|<gtk/gtk.h>
end_include

begin_include
include|#
directive|include
file|"libgimpcolor/gimpcolor.h"
end_include

begin_include
include|#
directive|include
file|"libgimpwidgets/gimpwidgets.h"
end_include

begin_include
include|#
directive|include
file|"libgimp/gimpenv.h"
end_include

begin_include
include|#
directive|include
file|"apptypes.h"
end_include

begin_include
include|#
directive|include
file|"widgets/gimpcontainerlistview.h"
end_include

begin_include
include|#
directive|include
file|"widgets/gimpdatafactoryview.h"
end_include

begin_include
include|#
directive|include
file|"widgets/gimppreview.h"
end_include

begin_include
include|#
directive|include
file|"color-area.h"
end_include

begin_include
include|#
directive|include
file|"color-notebook.h"
end_include

begin_include
include|#
directive|include
file|"palette-editor.h"
end_include

begin_include
include|#
directive|include
file|"palette-import-dialog.h"
end_include

begin_include
include|#
directive|include
file|"palette-select.h"
end_include

begin_include
include|#
directive|include
file|"context_manager.h"
end_include

begin_include
include|#
directive|include
file|"dialog_handler.h"
end_include

begin_include
include|#
directive|include
file|"gimage.h"
end_include

begin_include
include|#
directive|include
file|"gimpcontext.h"
end_include

begin_include
include|#
directive|include
file|"gimpdatafactory.h"
end_include

begin_include
include|#
directive|include
file|"gimpdatalist.h"
end_include

begin_include
include|#
directive|include
file|"gimpdnd.h"
end_include

begin_include
include|#
directive|include
file|"gimppalette.h"
end_include

begin_include
include|#
directive|include
file|"gimprc.h"
end_include

begin_include
include|#
directive|include
file|"libgimp/gimpintl.h"
end_include

begin_include
include|#
directive|include
file|"pixmaps/zoom_in.xpm"
end_include

begin_include
include|#
directive|include
file|"pixmaps/zoom_out.xpm"
end_include

begin_define
DECL|macro|ENTRY_WIDTH
define|#
directive|define
name|ENTRY_WIDTH
value|12
end_define

begin_define
DECL|macro|ENTRY_HEIGHT
define|#
directive|define
name|ENTRY_HEIGHT
value|10
end_define

begin_define
DECL|macro|SPACING
define|#
directive|define
name|SPACING
value|1
end_define

begin_define
DECL|macro|COLUMNS
define|#
directive|define
name|COLUMNS
value|16
end_define

begin_define
DECL|macro|ROWS
define|#
directive|define
name|ROWS
value|11
end_define

begin_define
DECL|macro|PREVIEW_WIDTH
define|#
directive|define
name|PREVIEW_WIDTH
value|((ENTRY_WIDTH  * COLUMNS) + (SPACING * (COLUMNS + 1)))
end_define

begin_define
DECL|macro|PREVIEW_HEIGHT
define|#
directive|define
name|PREVIEW_HEIGHT
value|((ENTRY_HEIGHT * ROWS)    + (SPACING * (ROWS    + 1)))
end_define

begin_define
DECL|macro|PALETTE_EVENT_MASK
define|#
directive|define
name|PALETTE_EVENT_MASK
value|(GDK_EXPOSURE_MASK     | \                             GDK_BUTTON_PRESS_MASK | \                             GDK_ENTER_NOTIFY_MASK)
end_define

begin_typedef
DECL|typedef|PaletteDialog
typedef|typedef
name|struct
name|_PaletteDialog
name|PaletteDialog
typedef|;
end_typedef

begin_struct
DECL|struct|_PaletteDialog
struct|struct
name|_PaletteDialog
block|{
DECL|member|shell
name|GtkWidget
modifier|*
name|shell
decl_stmt|;
DECL|member|color_area
name|GtkWidget
modifier|*
name|color_area
decl_stmt|;
DECL|member|scrolled_window
name|GtkWidget
modifier|*
name|scrolled_window
decl_stmt|;
DECL|member|color_name
name|GtkWidget
modifier|*
name|color_name
decl_stmt|;
DECL|member|view
name|GtkWidget
modifier|*
name|view
decl_stmt|;
DECL|member|context
name|GimpContext
modifier|*
name|context
decl_stmt|;
DECL|member|popup_menu
name|GtkWidget
modifier|*
name|popup_menu
decl_stmt|;
DECL|member|delete_menu_item
name|GtkWidget
modifier|*
name|delete_menu_item
decl_stmt|;
DECL|member|edit_menu_item
name|GtkWidget
modifier|*
name|edit_menu_item
decl_stmt|;
DECL|member|color_notebook
name|ColorNotebook
modifier|*
name|color_notebook
decl_stmt|;
DECL|member|color_notebook_active
name|gboolean
name|color_notebook_active
decl_stmt|;
DECL|member|color
name|GimpPaletteEntry
modifier|*
name|color
decl_stmt|;
DECL|member|dnd_color
name|GimpPaletteEntry
modifier|*
name|dnd_color
decl_stmt|;
DECL|member|entry_sig_id
name|guint
name|entry_sig_id
decl_stmt|;
DECL|member|zoom_factor
name|gfloat
name|zoom_factor
decl_stmt|;
comment|/* range from 0.1 to 4.0 */
DECL|member|col_width
name|gint
name|col_width
decl_stmt|;
DECL|member|last_width
name|gint
name|last_width
decl_stmt|;
DECL|member|columns
name|gint
name|columns
decl_stmt|;
DECL|member|freeze_update
name|gboolean
name|freeze_update
decl_stmt|;
DECL|member|columns_valid
name|gboolean
name|columns_valid
decl_stmt|;
DECL|member|invalidate_preview_handler_id
name|GQuark
name|invalidate_preview_handler_id
decl_stmt|;
block|}
struct|;
end_struct

begin_comment
comment|/*  local function prototypes  */
end_comment

begin_function_decl
specifier|static
name|PaletteDialog
modifier|*
name|palette_dialog_new
parameter_list|(
name|gboolean
name|editor
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|palette_dialog_create_popup_menu
parameter_list|(
name|PaletteDialog
modifier|*
name|palette_dialog
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|palette_dialog_new_entry_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|palette_dialog_edit_entry_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|palette_dialog_delete_entry_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|palette_dialog_color_notebook_callback
parameter_list|(
name|ColorNotebook
modifier|*
name|color_notebook
parameter_list|,
specifier|const
name|GimpRGB
modifier|*
name|color
parameter_list|,
name|ColorNotebookState
name|state
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|gint
name|palette_dialog_eventbox_button_press
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|GdkEventButton
modifier|*
name|bevent
parameter_list|,
name|PaletteDialog
modifier|*
name|palette_dialog
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|gint
name|palette_dialog_color_area_events
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|GdkEvent
modifier|*
name|event
parameter_list|,
name|PaletteDialog
modifier|*
name|palette_dialog
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|palette_dialog_draw_entries
parameter_list|(
name|PaletteDialog
modifier|*
name|palette
parameter_list|,
name|gint
name|row_start
parameter_list|,
name|gint
name|column_highlight
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|palette_dialog_redraw
parameter_list|(
name|PaletteDialog
modifier|*
name|palette
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|palette_dialog_scroll_top_left
parameter_list|(
name|PaletteDialog
modifier|*
name|palette
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|palette_dialog_color_name_changed
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|palette_dialog_zoomin_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|palette_dialog_zoomout_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|palette_dialog_redraw_zoom
parameter_list|(
name|PaletteDialog
modifier|*
name|palette_dialog
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|palette_dialog_import_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|palette_dialog_merge_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|palette_dialog_do_merge_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gchar
modifier|*
name|palette_name
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|palette_dialog_close_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|palette_dialog_palette_changed
parameter_list|(
name|GimpContext
modifier|*
name|context
parameter_list|,
name|GimpPalette
modifier|*
name|palette
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|palette_dialog_drag_color
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|GimpRGB
modifier|*
name|color
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|palette_dialog_drop_color
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
specifier|const
name|GimpRGB
modifier|*
name|color
parameter_list|,
name|gpointer
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|palette_dialog_invalidate_preview
parameter_list|(
name|GimpPalette
modifier|*
name|palette
parameter_list|,
name|PaletteDialog
modifier|*
name|palette_dialog
parameter_list|)
function_decl|;
end_function_decl

begin_decl_stmt
DECL|variable|top_level_edit_palette
name|PaletteDialog
modifier|*
name|top_level_edit_palette
init|=
name|NULL
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|top_level_palette
name|PaletteDialog
modifier|*
name|top_level_palette
init|=
name|NULL
decl_stmt|;
end_decl_stmt

begin_comment
comment|/*  dnd stuff  */
end_comment

begin_decl_stmt
DECL|variable|color_palette_target_table
specifier|static
name|GtkTargetEntry
name|color_palette_target_table
index|[]
init|=
block|{
name|GIMP_TARGET_COLOR
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|n_color_palette_targets
specifier|static
name|guint
name|n_color_palette_targets
init|=
operator|(
sizeof|sizeof
argument_list|(
name|color_palette_target_table
argument_list|)
operator|/
sizeof|sizeof
argument_list|(
name|color_palette_target_table
index|[
literal|0
index|]
argument_list|)
operator|)
decl_stmt|;
end_decl_stmt

begin_comment
comment|/*  public functions  ********************************************************/
end_comment

begin_function
name|GtkWidget
modifier|*
DECL|function|palette_dialog_create (void)
name|palette_dialog_create
parameter_list|(
name|void
parameter_list|)
block|{
if|if
condition|(
name|top_level_palette
operator|==
name|NULL
condition|)
block|{
name|top_level_palette
operator|=
name|palette_dialog_new
argument_list|(
name|FALSE
argument_list|)
expr_stmt|;
name|dialog_register
argument_list|(
name|top_level_palette
operator|->
name|shell
argument_list|)
expr_stmt|;
block|}
return|return
name|top_level_palette
operator|->
name|shell
return|;
block|}
end_function

begin_function
name|void
DECL|function|palette_dialog_free (void)
name|palette_dialog_free
parameter_list|(
name|void
parameter_list|)
block|{
if|if
condition|(
name|top_level_edit_palette
condition|)
block|{
name|palette_import_dialog_destroy
argument_list|()
expr_stmt|;
if|if
condition|(
name|top_level_edit_palette
operator|->
name|color_notebook
condition|)
name|color_notebook_free
argument_list|(
name|top_level_edit_palette
operator|->
name|color_notebook
argument_list|)
expr_stmt|;
name|gtk_signal_disconnect_by_func
argument_list|(
name|GTK_OBJECT
argument_list|(
name|top_level_edit_palette
operator|->
name|context
argument_list|)
argument_list|,
name|palette_dialog_palette_changed
argument_list|,
name|top_level_edit_palette
argument_list|)
expr_stmt|;
name|gimp_container_remove_handler
argument_list|(
name|global_palette_factory
operator|->
name|container
argument_list|,
name|top_level_edit_palette
operator|->
name|invalidate_preview_handler_id
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|top_level_edit_palette
argument_list|)
expr_stmt|;
name|top_level_edit_palette
operator|=
name|NULL
expr_stmt|;
block|}
if|if
condition|(
name|top_level_palette
condition|)
block|{
if|if
condition|(
name|top_level_palette
operator|->
name|color_notebook
condition|)
name|color_notebook_free
argument_list|(
name|top_level_palette
operator|->
name|color_notebook
argument_list|)
expr_stmt|;
name|gtk_signal_disconnect_by_func
argument_list|(
name|GTK_OBJECT
argument_list|(
name|top_level_palette
operator|->
name|context
argument_list|)
argument_list|,
name|palette_dialog_palette_changed
argument_list|,
name|top_level_palette
argument_list|)
expr_stmt|;
name|gimp_container_remove_handler
argument_list|(
name|global_palette_factory
operator|->
name|container
argument_list|,
name|top_level_palette
operator|->
name|invalidate_preview_handler_id
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|top_level_palette
argument_list|)
expr_stmt|;
name|top_level_palette
operator|=
name|NULL
expr_stmt|;
block|}
block|}
end_function

begin_comment
comment|/*  called from color_picker.h  *********************************************/
end_comment

begin_function
name|void
DECL|function|palette_set_active_color (gint r,gint g,gint b,gint state)
name|palette_set_active_color
parameter_list|(
name|gint
name|r
parameter_list|,
name|gint
name|g
parameter_list|,
name|gint
name|b
parameter_list|,
name|gint
name|state
parameter_list|)
block|{
name|GimpPalette
modifier|*
name|palette
decl_stmt|;
name|GimpRGB
name|color
decl_stmt|;
name|gimp_rgba_set_uchar
argument_list|(
operator|&
name|color
argument_list|,
operator|(
name|guchar
operator|)
name|r
argument_list|,
operator|(
name|guchar
operator|)
name|g
argument_list|,
operator|(
name|guchar
operator|)
name|b
argument_list|,
literal|255
argument_list|)
expr_stmt|;
if|if
condition|(
name|top_level_edit_palette
condition|)
block|{
name|palette
operator|=
name|gimp_context_get_palette
argument_list|(
name|top_level_edit_palette
operator|->
name|context
argument_list|)
expr_stmt|;
if|if
condition|(
name|palette
condition|)
block|{
switch|switch
condition|(
name|state
condition|)
block|{
case|case
name|COLOR_NEW
case|:
name|top_level_edit_palette
operator|->
name|color
operator|=
name|gimp_palette_add_entry
argument_list|(
name|palette
argument_list|,
name|NULL
argument_list|,
operator|&
name|color
argument_list|)
expr_stmt|;
break|break;
case|case
name|COLOR_UPDATE_NEW
case|:
name|top_level_edit_palette
operator|->
name|color
operator|->
name|color
operator|=
name|color
expr_stmt|;
name|gimp_data_dirty
argument_list|(
name|GIMP_DATA
argument_list|(
name|palette
argument_list|)
argument_list|)
expr_stmt|;
break|break;
default|default:
break|break;
block|}
block|}
block|}
if|if
condition|(
name|active_color
operator|==
name|FOREGROUND
condition|)
name|gimp_context_set_foreground
argument_list|(
name|gimp_context_get_user
argument_list|()
argument_list|,
operator|&
name|color
argument_list|)
expr_stmt|;
elseif|else
if|if
condition|(
name|active_color
operator|==
name|BACKGROUND
condition|)
name|gimp_context_set_background
argument_list|(
name|gimp_context_get_user
argument_list|()
argument_list|,
operator|&
name|color
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/*  called from palette_select.c  ********************************************/
end_comment

begin_function
name|void
DECL|function|palette_dialog_edit_palette (GimpData * data)
name|palette_dialog_edit_palette
parameter_list|(
name|GimpData
modifier|*
name|data
parameter_list|)
block|{
name|GimpPalette
modifier|*
name|palette
decl_stmt|;
name|palette
operator|=
name|GIMP_PALETTE
argument_list|(
name|data
argument_list|)
expr_stmt|;
if|if
condition|(
name|top_level_edit_palette
operator|==
name|NULL
condition|)
block|{
name|top_level_edit_palette
operator|=
name|palette_dialog_new
argument_list|(
name|TRUE
argument_list|)
expr_stmt|;
name|dialog_register
argument_list|(
name|top_level_edit_palette
operator|->
name|shell
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|top_level_edit_palette
operator|->
name|shell
argument_list|)
expr_stmt|;
name|palette_dialog_draw_entries
argument_list|(
name|top_level_edit_palette
argument_list|,
operator|-
literal|1
argument_list|,
operator|-
literal|1
argument_list|)
expr_stmt|;
block|}
else|else
block|{
if|if
condition|(
operator|!
name|GTK_WIDGET_VISIBLE
argument_list|(
name|top_level_edit_palette
operator|->
name|shell
argument_list|)
condition|)
name|gtk_widget_show
argument_list|(
name|top_level_edit_palette
operator|->
name|shell
argument_list|)
expr_stmt|;
else|else
name|gdk_window_raise
argument_list|(
name|top_level_edit_palette
operator|->
name|shell
operator|->
name|window
argument_list|)
expr_stmt|;
block|}
name|gimp_context_set_palette
argument_list|(
name|top_level_edit_palette
operator|->
name|context
argument_list|,
name|palette
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/*  private functions  */
end_comment

begin_comment
comment|/*  the palette& palette edit dialog constructor  ***************************/
end_comment

begin_function
name|PaletteDialog
modifier|*
DECL|function|palette_dialog_new (gboolean editor)
name|palette_dialog_new
parameter_list|(
name|gboolean
name|editor
parameter_list|)
block|{
name|PaletteDialog
modifier|*
name|palette_dialog
decl_stmt|;
name|GtkWidget
modifier|*
name|hbox
decl_stmt|;
name|GtkWidget
modifier|*
name|hbox2
decl_stmt|;
name|GtkWidget
modifier|*
name|vbox
decl_stmt|;
name|GtkWidget
modifier|*
name|scrolledwindow
decl_stmt|;
name|GtkWidget
modifier|*
name|palette_region
decl_stmt|;
name|GtkWidget
modifier|*
name|entry
decl_stmt|;
name|GtkWidget
modifier|*
name|eventbox
decl_stmt|;
name|GtkWidget
modifier|*
name|alignment
decl_stmt|;
name|GtkWidget
modifier|*
name|frame
decl_stmt|;
name|GtkWidget
modifier|*
name|button
decl_stmt|;
name|palette_dialog
operator|=
name|g_new0
argument_list|(
name|PaletteDialog
argument_list|,
literal|1
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|editor
condition|)
name|palette_dialog
operator|->
name|context
operator|=
name|gimp_context_get_user
argument_list|()
expr_stmt|;
else|else
name|palette_dialog
operator|->
name|context
operator|=
name|gimp_context_new
argument_list|(
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|palette_dialog
operator|->
name|zoom_factor
operator|=
literal|1.0
expr_stmt|;
name|palette_dialog
operator|->
name|columns
operator|=
name|COLUMNS
expr_stmt|;
name|palette_dialog
operator|->
name|columns_valid
operator|=
name|TRUE
expr_stmt|;
name|palette_dialog
operator|->
name|freeze_update
operator|=
name|FALSE
expr_stmt|;
if|if
condition|(
name|editor
condition|)
block|{
name|palette_dialog
operator|->
name|shell
operator|=
name|gimp_dialog_new
argument_list|(
name|_
argument_list|(
literal|"Color Palette Edit"
argument_list|)
argument_list|,
literal|"color_palette_edit"
argument_list|,
name|gimp_standard_help_func
argument_list|,
literal|"dialogs/palette_editor/palette_editor.html"
argument_list|,
name|GTK_WIN_POS_NONE
argument_list|,
name|FALSE
argument_list|,
name|TRUE
argument_list|,
name|FALSE
argument_list|,
literal|"_delete_event_"
argument_list|,
name|palette_dialog_close_callback
argument_list|,
name|palette_dialog
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|,
name|TRUE
argument_list|,
name|TRUE
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|palette_dialog
operator|->
name|shell
operator|=
name|gimp_dialog_new
argument_list|(
name|_
argument_list|(
literal|"Color Palette"
argument_list|)
argument_list|,
literal|"color_palette"
argument_list|,
name|gimp_standard_help_func
argument_list|,
literal|"dialogs/palette_selection.html"
argument_list|,
name|GTK_WIN_POS_NONE
argument_list|,
name|FALSE
argument_list|,
name|TRUE
argument_list|,
name|FALSE
argument_list|,
literal|"_delete_event_"
argument_list|,
name|palette_dialog_close_callback
argument_list|,
name|palette_dialog
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|,
name|TRUE
argument_list|,
name|TRUE
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
block|}
name|gtk_widget_hide
argument_list|(
name|GTK_WIDGET
argument_list|(
name|g_list_nth_data
argument_list|(
name|gtk_container_children
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|GTK_DIALOG
argument_list|(
name|palette_dialog
operator|->
name|shell
argument_list|)
operator|->
name|vbox
argument_list|)
argument_list|)
argument_list|,
literal|0
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_widget_hide
argument_list|(
name|GTK_DIALOG
argument_list|(
name|palette_dialog
operator|->
name|shell
argument_list|)
operator|->
name|action_area
argument_list|)
expr_stmt|;
comment|/*  The main container widget  */
if|if
condition|(
operator|!
name|editor
condition|)
block|{
name|hbox
operator|=
name|gtk_notebook_new
argument_list|()
expr_stmt|;
name|gtk_container_set_border_width
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|hbox
argument_list|)
argument_list|,
literal|1
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|hbox
operator|=
name|gtk_hbox_new
argument_list|(
name|FALSE
argument_list|,
literal|4
argument_list|)
expr_stmt|;
name|gtk_container_set_border_width
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|hbox
argument_list|)
argument_list|,
literal|4
argument_list|)
expr_stmt|;
block|}
name|gtk_container_add
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|GTK_DIALOG
argument_list|(
name|palette_dialog
operator|->
name|shell
argument_list|)
operator|->
name|vbox
argument_list|)
argument_list|,
name|hbox
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|hbox
argument_list|)
expr_stmt|;
name|vbox
operator|=
name|gtk_vbox_new
argument_list|(
name|FALSE
argument_list|,
literal|2
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|vbox
argument_list|)
expr_stmt|;
name|palette_dialog
operator|->
name|scrolled_window
operator|=
name|scrolledwindow
operator|=
name|gtk_scrolled_window_new
argument_list|(
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|gtk_scrolled_window_set_policy
argument_list|(
name|GTK_SCROLLED_WINDOW
argument_list|(
name|scrolledwindow
argument_list|)
argument_list|,
name|GTK_POLICY_AUTOMATIC
argument_list|,
name|GTK_POLICY_ALWAYS
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|vbox
argument_list|)
argument_list|,
name|scrolledwindow
argument_list|,
name|TRUE
argument_list|,
name|TRUE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|scrolledwindow
argument_list|)
expr_stmt|;
name|eventbox
operator|=
name|gtk_event_box_new
argument_list|()
expr_stmt|;
name|gtk_scrolled_window_add_with_viewport
argument_list|(
name|GTK_SCROLLED_WINDOW
argument_list|(
name|scrolledwindow
argument_list|)
argument_list|,
name|eventbox
argument_list|)
expr_stmt|;
name|gtk_signal_connect
argument_list|(
name|GTK_OBJECT
argument_list|(
name|eventbox
argument_list|)
argument_list|,
literal|"button_press_event"
argument_list|,
name|GTK_SIGNAL_FUNC
argument_list|(
name|palette_dialog_eventbox_button_press
argument_list|)
argument_list|,
name|palette_dialog
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|eventbox
argument_list|)
expr_stmt|;
name|alignment
operator|=
name|gtk_alignment_new
argument_list|(
literal|0.5
argument_list|,
literal|0.5
argument_list|,
literal|0.0
argument_list|,
literal|0.0
argument_list|)
expr_stmt|;
name|gtk_container_add
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|eventbox
argument_list|)
argument_list|,
name|alignment
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|alignment
argument_list|)
expr_stmt|;
name|palette_dialog
operator|->
name|color_area
operator|=
name|palette_region
operator|=
name|gtk_preview_new
argument_list|(
name|GTK_PREVIEW_COLOR
argument_list|)
expr_stmt|;
name|gtk_preview_set_dither
argument_list|(
name|GTK_PREVIEW
argument_list|(
name|palette_dialog
operator|->
name|color_area
argument_list|)
argument_list|,
name|GDK_RGB_DITHER_MAX
argument_list|)
expr_stmt|;
name|gtk_preview_size
argument_list|(
name|GTK_PREVIEW
argument_list|(
name|palette_region
argument_list|)
argument_list|,
name|PREVIEW_WIDTH
argument_list|,
name|PREVIEW_HEIGHT
argument_list|)
expr_stmt|;
name|gtk_widget_set_events
argument_list|(
name|palette_region
argument_list|,
name|PALETTE_EVENT_MASK
argument_list|)
expr_stmt|;
name|gtk_signal_connect
argument_list|(
name|GTK_OBJECT
argument_list|(
name|palette_dialog
operator|->
name|color_area
argument_list|)
argument_list|,
literal|"event"
argument_list|,
name|GTK_SIGNAL_FUNC
argument_list|(
name|palette_dialog_color_area_events
argument_list|)
argument_list|,
name|palette_dialog
argument_list|)
expr_stmt|;
name|gtk_container_add
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|alignment
argument_list|)
argument_list|,
name|palette_region
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|palette_region
argument_list|)
expr_stmt|;
comment|/*  dnd stuff  */
name|gtk_drag_source_set
argument_list|(
name|palette_region
argument_list|,
name|GDK_BUTTON1_MASK
operator||
name|GDK_BUTTON2_MASK
argument_list|,
name|color_palette_target_table
argument_list|,
name|n_color_palette_targets
argument_list|,
name|GDK_ACTION_COPY
operator||
name|GDK_ACTION_MOVE
argument_list|)
expr_stmt|;
name|gimp_dnd_color_source_set
argument_list|(
name|palette_region
argument_list|,
name|palette_dialog_drag_color
argument_list|,
name|palette_dialog
argument_list|)
expr_stmt|;
name|gtk_drag_dest_set
argument_list|(
name|alignment
argument_list|,
name|GTK_DEST_DEFAULT_HIGHLIGHT
operator||
name|GTK_DEST_DEFAULT_MOTION
operator||
name|GTK_DEST_DEFAULT_DROP
argument_list|,
name|color_palette_target_table
argument_list|,
name|n_color_palette_targets
argument_list|,
name|GDK_ACTION_COPY
argument_list|)
expr_stmt|;
name|gimp_dnd_color_dest_set
argument_list|(
name|alignment
argument_list|,
name|palette_dialog_drop_color
argument_list|,
name|palette_dialog
argument_list|)
expr_stmt|;
comment|/*  The color name entry  */
name|hbox2
operator|=
name|gtk_hbox_new
argument_list|(
name|FALSE
argument_list|,
literal|2
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|vbox
argument_list|)
argument_list|,
name|hbox2
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|hbox2
argument_list|)
expr_stmt|;
name|entry
operator|=
name|palette_dialog
operator|->
name|color_name
operator|=
name|gtk_entry_new
argument_list|()
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|entry
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|hbox2
argument_list|)
argument_list|,
name|entry
argument_list|,
name|TRUE
argument_list|,
name|TRUE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_entry_set_text
argument_list|(
name|GTK_ENTRY
argument_list|(
name|entry
argument_list|)
argument_list|,
name|_
argument_list|(
literal|"Undefined"
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_widget_set_sensitive
argument_list|(
name|entry
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|palette_dialog
operator|->
name|entry_sig_id
operator|=
name|gtk_signal_connect
argument_list|(
name|GTK_OBJECT
argument_list|(
name|entry
argument_list|)
argument_list|,
literal|"changed"
argument_list|,
name|GTK_SIGNAL_FUNC
argument_list|(
name|palette_dialog_color_name_changed
argument_list|)
argument_list|,
name|palette_dialog
argument_list|)
expr_stmt|;
comment|/*  + and - buttons  */
name|button
operator|=
name|gimp_pixmap_button_new
argument_list|(
name|zoom_in_xpm
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|hbox2
argument_list|)
argument_list|,
name|button
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_signal_connect
argument_list|(
name|GTK_OBJECT
argument_list|(
name|button
argument_list|)
argument_list|,
literal|"clicked"
argument_list|,
name|GTK_SIGNAL_FUNC
argument_list|(
name|palette_dialog_zoomin_callback
argument_list|)
argument_list|,
name|palette_dialog
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|button
argument_list|)
expr_stmt|;
name|button
operator|=
name|gimp_pixmap_button_new
argument_list|(
name|zoom_out_xpm
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|hbox2
argument_list|)
argument_list|,
name|button
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_signal_connect
argument_list|(
name|GTK_OBJECT
argument_list|(
name|button
argument_list|)
argument_list|,
literal|"clicked"
argument_list|,
name|GTK_SIGNAL_FUNC
argument_list|(
name|palette_dialog_zoomout_callback
argument_list|)
argument_list|,
name|palette_dialog
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|button
argument_list|)
expr_stmt|;
comment|/*  The Palette List  */
name|palette_dialog
operator|->
name|view
operator|=
name|gimp_data_factory_view_new
argument_list|(
name|GIMP_VIEW_TYPE_LIST
argument_list|,
name|global_palette_factory
argument_list|,
name|editor
condition|?
name|NULL
else|:
name|palette_dialog_edit_palette
argument_list|,
name|palette_dialog
operator|->
name|context
argument_list|,
name|SM_PREVIEW_HEIGHT
argument_list|,
literal|2
argument_list|,
literal|4
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|editor
condition|)
block|{
name|gtk_notebook_append_page
argument_list|(
name|GTK_NOTEBOOK
argument_list|(
name|hbox
argument_list|)
argument_list|,
name|vbox
argument_list|,
name|gtk_label_new
argument_list|(
name|_
argument_list|(
literal|"Palette"
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_notebook_append_page
argument_list|(
name|GTK_NOTEBOOK
argument_list|(
name|hbox
argument_list|)
argument_list|,
name|palette_dialog
operator|->
name|view
argument_list|,
name|gtk_label_new
argument_list|(
name|_
argument_list|(
literal|"Select"
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|hbox
argument_list|)
argument_list|,
name|vbox
argument_list|,
name|TRUE
argument_list|,
name|TRUE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|hbox
argument_list|)
argument_list|,
name|palette_dialog
operator|->
name|view
argument_list|,
name|TRUE
argument_list|,
name|TRUE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|editor
condition|)
name|gtk_list_set_selection_mode
argument_list|(
name|GTK_LIST
argument_list|(
name|GIMP_CONTAINER_LIST_VIEW
argument_list|(
name|GIMP_DATA_FACTORY_VIEW
argument_list|(
name|palette_dialog
operator|->
name|view
argument_list|)
operator|->
name|view
argument_list|)
operator|->
name|gtk_list
argument_list|)
argument_list|,
name|GTK_SELECTION_EXTENDED
argument_list|)
expr_stmt|;
name|gtk_signal_connect
argument_list|(
name|GTK_OBJECT
argument_list|(
name|palette_dialog
operator|->
name|context
argument_list|)
argument_list|,
literal|"palette_changed"
argument_list|,
name|GTK_SIGNAL_FUNC
argument_list|(
name|palette_dialog_palette_changed
argument_list|)
argument_list|,
name|palette_dialog
argument_list|)
expr_stmt|;
name|palette_dialog
operator|->
name|invalidate_preview_handler_id
operator|=
name|gimp_container_add_handler
argument_list|(
name|global_palette_factory
operator|->
name|container
argument_list|,
literal|"invalidate_preview"
argument_list|,
name|GTK_SIGNAL_FUNC
argument_list|(
name|palette_dialog_invalidate_preview
argument_list|)
argument_list|,
name|palette_dialog
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|palette_dialog
operator|->
name|view
argument_list|)
expr_stmt|;
if|if
condition|(
name|editor
condition|)
block|{
name|frame
operator|=
name|gtk_frame_new
argument_list|(
name|_
argument_list|(
literal|"Palette Ops"
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|hbox
argument_list|)
argument_list|,
name|frame
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|frame
argument_list|)
expr_stmt|;
name|vbox
operator|=
name|gtk_vbox_new
argument_list|(
name|FALSE
argument_list|,
literal|2
argument_list|)
expr_stmt|;
name|gtk_container_set_border_width
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|vbox
argument_list|)
argument_list|,
literal|4
argument_list|)
expr_stmt|;
name|gtk_container_add
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|frame
argument_list|)
argument_list|,
name|vbox
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|vbox
argument_list|)
expr_stmt|;
name|button
operator|=
name|gtk_button_new_with_label
argument_list|(
name|_
argument_list|(
literal|"Import"
argument_list|)
argument_list|)
expr_stmt|;
name|GTK_WIDGET_UNSET_FLAGS
argument_list|(
name|button
argument_list|,
name|GTK_RECEIVES_DEFAULT
argument_list|)
expr_stmt|;
name|gtk_misc_set_padding
argument_list|(
name|GTK_MISC
argument_list|(
name|GTK_BIN
argument_list|(
name|button
argument_list|)
operator|->
name|child
argument_list|)
argument_list|,
literal|2
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_signal_connect
argument_list|(
name|GTK_OBJECT
argument_list|(
name|button
argument_list|)
argument_list|,
literal|"clicked"
argument_list|,
name|GTK_SIGNAL_FUNC
argument_list|(
name|palette_dialog_import_callback
argument_list|)
argument_list|,
name|palette_dialog
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|vbox
argument_list|)
argument_list|,
name|button
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gimp_help_set_help_data
argument_list|(
name|button
argument_list|,
name|NULL
argument_list|,
literal|"dialogs/palette_editor/import_palette.html"
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|button
argument_list|)
expr_stmt|;
name|button
operator|=
name|gtk_button_new_with_label
argument_list|(
name|_
argument_list|(
literal|"Merge"
argument_list|)
argument_list|)
expr_stmt|;
name|GTK_WIDGET_UNSET_FLAGS
argument_list|(
name|button
argument_list|,
name|GTK_RECEIVES_DEFAULT
argument_list|)
expr_stmt|;
name|gtk_misc_set_padding
argument_list|(
name|GTK_MISC
argument_list|(
name|GTK_BIN
argument_list|(
name|button
argument_list|)
operator|->
name|child
argument_list|)
argument_list|,
literal|2
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gtk_signal_connect
argument_list|(
name|GTK_OBJECT
argument_list|(
name|button
argument_list|)
argument_list|,
literal|"clicked"
argument_list|,
name|GTK_SIGNAL_FUNC
argument_list|(
name|palette_dialog_merge_callback
argument_list|)
argument_list|,
name|palette_dialog
argument_list|)
expr_stmt|;
name|gtk_box_pack_start
argument_list|(
name|GTK_BOX
argument_list|(
name|vbox
argument_list|)
argument_list|,
name|button
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|gimp_help_set_help_data
argument_list|(
name|button
argument_list|,
name|NULL
argument_list|,
literal|"dialogs/palette_editor/merge_palette.html"
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|button
argument_list|)
expr_stmt|;
block|}
name|gtk_widget_realize
argument_list|(
name|palette_dialog
operator|->
name|shell
argument_list|)
expr_stmt|;
name|palette_dialog_create_popup_menu
argument_list|(
name|palette_dialog
argument_list|)
expr_stmt|;
return|return
name|palette_dialog
return|;
block|}
end_function

begin_comment
comment|/*  the palette dialog popup menu& callbacks  *******************************/
end_comment

begin_function
specifier|static
name|void
DECL|function|palette_dialog_create_popup_menu (PaletteDialog * palette_dialog)
name|palette_dialog_create_popup_menu
parameter_list|(
name|PaletteDialog
modifier|*
name|palette_dialog
parameter_list|)
block|{
name|GtkWidget
modifier|*
name|menu
decl_stmt|;
name|GtkWidget
modifier|*
name|menu_item
decl_stmt|;
name|palette_dialog
operator|->
name|popup_menu
operator|=
name|menu
operator|=
name|gtk_menu_new
argument_list|()
expr_stmt|;
name|menu_item
operator|=
name|gtk_menu_item_new_with_label
argument_list|(
name|_
argument_list|(
literal|"New"
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_menu_append
argument_list|(
name|GTK_MENU
argument_list|(
name|menu
argument_list|)
argument_list|,
name|menu_item
argument_list|)
expr_stmt|;
name|gtk_signal_connect
argument_list|(
name|GTK_OBJECT
argument_list|(
name|menu_item
argument_list|)
argument_list|,
literal|"activate"
argument_list|,
name|GTK_SIGNAL_FUNC
argument_list|(
name|palette_dialog_new_entry_callback
argument_list|)
argument_list|,
name|palette_dialog
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|menu_item
argument_list|)
expr_stmt|;
name|menu_item
operator|=
name|gtk_menu_item_new_with_label
argument_list|(
name|_
argument_list|(
literal|"Edit"
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_menu_append
argument_list|(
name|GTK_MENU
argument_list|(
name|menu
argument_list|)
argument_list|,
name|menu_item
argument_list|)
expr_stmt|;
name|gtk_signal_connect
argument_list|(
name|GTK_OBJECT
argument_list|(
name|menu_item
argument_list|)
argument_list|,
literal|"activate"
argument_list|,
name|GTK_SIGNAL_FUNC
argument_list|(
name|palette_dialog_edit_entry_callback
argument_list|)
argument_list|,
name|palette_dialog
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|menu_item
argument_list|)
expr_stmt|;
name|palette_dialog
operator|->
name|edit_menu_item
operator|=
name|menu_item
expr_stmt|;
name|menu_item
operator|=
name|gtk_menu_item_new_with_label
argument_list|(
name|_
argument_list|(
literal|"Delete"
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_signal_connect
argument_list|(
name|GTK_OBJECT
argument_list|(
name|menu_item
argument_list|)
argument_list|,
literal|"activate"
argument_list|,
name|GTK_SIGNAL_FUNC
argument_list|(
name|palette_dialog_delete_entry_callback
argument_list|)
argument_list|,
name|palette_dialog
argument_list|)
expr_stmt|;
name|gtk_menu_append
argument_list|(
name|GTK_MENU
argument_list|(
name|menu
argument_list|)
argument_list|,
name|menu_item
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|menu_item
argument_list|)
expr_stmt|;
name|palette_dialog
operator|->
name|delete_menu_item
operator|=
name|menu_item
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|palette_dialog_new_entry_callback (GtkWidget * widget,gpointer data)
name|palette_dialog_new_entry_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|PaletteDialog
modifier|*
name|palette_dialog
decl_stmt|;
name|GimpRGB
name|color
decl_stmt|;
name|palette_dialog
operator|=
operator|(
name|PaletteDialog
operator|*
operator|)
name|data
expr_stmt|;
if|if
condition|(
operator|!
operator|(
name|palette_dialog
operator|&&
name|gimp_context_get_palette
argument_list|(
name|palette_dialog
operator|->
name|context
argument_list|)
operator|)
condition|)
return|return;
if|if
condition|(
name|active_color
operator|==
name|FOREGROUND
condition|)
name|gimp_context_get_foreground
argument_list|(
name|gimp_context_get_user
argument_list|()
argument_list|,
operator|&
name|color
argument_list|)
expr_stmt|;
elseif|else
if|if
condition|(
name|active_color
operator|==
name|BACKGROUND
condition|)
name|gimp_context_get_background
argument_list|(
name|gimp_context_get_user
argument_list|()
argument_list|,
operator|&
name|color
argument_list|)
expr_stmt|;
name|palette_dialog
operator|->
name|color
operator|=
name|gimp_palette_add_entry
argument_list|(
name|gimp_context_get_palette
argument_list|(
name|palette_dialog
operator|->
name|context
argument_list|)
argument_list|,
name|NULL
argument_list|,
operator|&
name|color
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|palette_dialog_edit_entry_callback (GtkWidget * widget,gpointer data)
name|palette_dialog_edit_entry_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|PaletteDialog
modifier|*
name|palette_dialog
decl_stmt|;
name|palette_dialog
operator|=
operator|(
name|PaletteDialog
operator|*
operator|)
name|data
expr_stmt|;
if|if
condition|(
operator|!
operator|(
name|palette_dialog
operator|&&
name|gimp_context_get_palette
argument_list|(
name|palette_dialog
operator|->
name|context
argument_list|)
operator|&&
name|palette_dialog
operator|->
name|color
operator|)
condition|)
return|return;
if|if
condition|(
operator|!
name|palette_dialog
operator|->
name|color_notebook
condition|)
block|{
name|palette_dialog
operator|->
name|color_notebook
operator|=
name|color_notebook_new
argument_list|(
name|_
argument_list|(
literal|"Edit Palette Color"
argument_list|)
argument_list|,
operator|(
specifier|const
name|GimpRGB
operator|*
operator|)
operator|&
name|palette_dialog
operator|->
name|color
operator|->
name|color
argument_list|,
name|palette_dialog_color_notebook_callback
argument_list|,
name|palette_dialog
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|palette_dialog
operator|->
name|color_notebook_active
operator|=
name|TRUE
expr_stmt|;
block|}
else|else
block|{
if|if
condition|(
operator|!
name|palette_dialog
operator|->
name|color_notebook_active
condition|)
block|{
name|color_notebook_show
argument_list|(
name|palette_dialog
operator|->
name|color_notebook
argument_list|)
expr_stmt|;
name|palette_dialog
operator|->
name|color_notebook_active
operator|=
name|TRUE
expr_stmt|;
block|}
name|color_notebook_set_color
argument_list|(
name|palette_dialog
operator|->
name|color_notebook
argument_list|,
operator|&
name|palette_dialog
operator|->
name|color
operator|->
name|color
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|palette_dialog_delete_entry_callback (GtkWidget * widget,gpointer data)
name|palette_dialog_delete_entry_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|PaletteDialog
modifier|*
name|palette_dialog
decl_stmt|;
name|palette_dialog
operator|=
operator|(
name|PaletteDialog
operator|*
operator|)
name|data
expr_stmt|;
if|if
condition|(
operator|!
operator|(
name|palette_dialog
operator|&&
name|gimp_context_get_palette
argument_list|(
name|palette_dialog
operator|->
name|context
argument_list|)
operator|&&
name|palette_dialog
operator|->
name|color
operator|)
condition|)
return|return;
name|gimp_palette_delete_entry
argument_list|(
name|gimp_context_get_palette
argument_list|(
name|palette_dialog
operator|->
name|context
argument_list|)
argument_list|,
name|palette_dialog
operator|->
name|color
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|palette_dialog_color_notebook_callback (ColorNotebook * color_notebook,const GimpRGB * color,ColorNotebookState state,gpointer data)
name|palette_dialog_color_notebook_callback
parameter_list|(
name|ColorNotebook
modifier|*
name|color_notebook
parameter_list|,
specifier|const
name|GimpRGB
modifier|*
name|color
parameter_list|,
name|ColorNotebookState
name|state
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|PaletteDialog
modifier|*
name|palette_dialog
decl_stmt|;
name|GimpPalette
modifier|*
name|palette
decl_stmt|;
name|palette_dialog
operator|=
name|data
expr_stmt|;
name|palette
operator|=
name|gimp_context_get_palette
argument_list|(
name|palette_dialog
operator|->
name|context
argument_list|)
expr_stmt|;
switch|switch
condition|(
name|state
condition|)
block|{
case|case
name|COLOR_NOTEBOOK_UPDATE
case|:
break|break;
case|case
name|COLOR_NOTEBOOK_OK
case|:
if|if
condition|(
name|palette_dialog
operator|->
name|color
condition|)
block|{
name|palette_dialog
operator|->
name|color
operator|->
name|color
operator|=
operator|*
name|color
expr_stmt|;
comment|/*  Update either foreground or background colors  */
if|if
condition|(
name|active_color
operator|==
name|FOREGROUND
condition|)
name|gimp_context_set_foreground
argument_list|(
name|gimp_context_get_user
argument_list|()
argument_list|,
name|color
argument_list|)
expr_stmt|;
elseif|else
if|if
condition|(
name|active_color
operator|==
name|BACKGROUND
condition|)
name|gimp_context_set_background
argument_list|(
name|gimp_context_get_user
argument_list|()
argument_list|,
name|color
argument_list|)
expr_stmt|;
name|gimp_data_dirty
argument_list|(
name|GIMP_DATA
argument_list|(
name|palette
argument_list|)
argument_list|)
expr_stmt|;
block|}
comment|/* Fallthrough */
case|case
name|COLOR_NOTEBOOK_CANCEL
case|:
if|if
condition|(
name|palette_dialog
operator|->
name|color_notebook_active
condition|)
block|{
name|color_notebook_hide
argument_list|(
name|palette_dialog
operator|->
name|color_notebook
argument_list|)
expr_stmt|;
name|palette_dialog
operator|->
name|color_notebook_active
operator|=
name|FALSE
expr_stmt|;
block|}
block|}
block|}
end_function

begin_comment
comment|/*  the color area event callbacks  ******************************************/
end_comment

begin_function
specifier|static
name|gint
DECL|function|palette_dialog_eventbox_button_press (GtkWidget * widget,GdkEventButton * bevent,PaletteDialog * palette_dialog)
name|palette_dialog_eventbox_button_press
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|GdkEventButton
modifier|*
name|bevent
parameter_list|,
name|PaletteDialog
modifier|*
name|palette_dialog
parameter_list|)
block|{
if|if
condition|(
name|gtk_get_event_widget
argument_list|(
operator|(
name|GdkEvent
operator|*
operator|)
name|bevent
argument_list|)
operator|==
name|palette_dialog
operator|->
name|color_area
condition|)
return|return
name|FALSE
return|;
if|if
condition|(
name|bevent
operator|->
name|button
operator|==
literal|3
condition|)
block|{
if|if
condition|(
name|GTK_WIDGET_SENSITIVE
argument_list|(
name|palette_dialog
operator|->
name|edit_menu_item
argument_list|)
condition|)
block|{
name|gtk_widget_set_sensitive
argument_list|(
name|palette_dialog
operator|->
name|edit_menu_item
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gtk_widget_set_sensitive
argument_list|(
name|palette_dialog
operator|->
name|delete_menu_item
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
block|}
name|gtk_menu_popup
argument_list|(
name|GTK_MENU
argument_list|(
name|palette_dialog
operator|->
name|popup_menu
argument_list|)
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|,
literal|3
argument_list|,
name|bevent
operator|->
name|time
argument_list|)
expr_stmt|;
block|}
return|return
name|TRUE
return|;
block|}
end_function

begin_function
specifier|static
name|gint
DECL|function|palette_dialog_color_area_events (GtkWidget * widget,GdkEvent * event,PaletteDialog * palette_dialog)
name|palette_dialog_color_area_events
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|GdkEvent
modifier|*
name|event
parameter_list|,
name|PaletteDialog
modifier|*
name|palette_dialog
parameter_list|)
block|{
name|GdkEventButton
modifier|*
name|bevent
decl_stmt|;
name|GList
modifier|*
name|list
decl_stmt|;
name|gint
name|entry_width
decl_stmt|;
name|gint
name|entry_height
decl_stmt|;
name|gint
name|row
decl_stmt|,
name|col
decl_stmt|;
name|gint
name|pos
decl_stmt|;
switch|switch
condition|(
name|event
operator|->
name|type
condition|)
block|{
case|case
name|GDK_EXPOSE
case|:
name|palette_dialog_redraw
argument_list|(
name|palette_dialog
argument_list|)
expr_stmt|;
break|break;
case|case
name|GDK_BUTTON_PRESS
case|:
name|bevent
operator|=
operator|(
name|GdkEventButton
operator|*
operator|)
name|event
expr_stmt|;
name|entry_width
operator|=
name|palette_dialog
operator|->
name|col_width
operator|+
name|SPACING
expr_stmt|;
name|entry_height
operator|=
operator|(
name|ENTRY_HEIGHT
operator|*
name|palette_dialog
operator|->
name|zoom_factor
operator|)
operator|+
name|SPACING
expr_stmt|;
name|col
operator|=
operator|(
name|bevent
operator|->
name|x
operator|-
literal|1
operator|)
operator|/
name|entry_width
expr_stmt|;
name|row
operator|=
operator|(
name|bevent
operator|->
name|y
operator|-
literal|1
operator|)
operator|/
name|entry_height
expr_stmt|;
name|pos
operator|=
name|row
operator|*
name|palette_dialog
operator|->
name|columns
operator|+
name|col
expr_stmt|;
if|if
condition|(
name|gimp_context_get_palette
argument_list|(
name|palette_dialog
operator|->
name|context
argument_list|)
condition|)
name|list
operator|=
name|g_list_nth
argument_list|(
name|gimp_context_get_palette
argument_list|(
name|palette_dialog
operator|->
name|context
argument_list|)
operator|->
name|colors
argument_list|,
name|pos
argument_list|)
expr_stmt|;
else|else
name|list
operator|=
name|NULL
expr_stmt|;
if|if
condition|(
name|list
condition|)
name|palette_dialog
operator|->
name|dnd_color
operator|=
name|list
operator|->
name|data
expr_stmt|;
else|else
name|palette_dialog
operator|->
name|dnd_color
operator|=
name|NULL
expr_stmt|;
if|if
condition|(
operator|(
name|bevent
operator|->
name|button
operator|==
literal|1
operator|||
name|bevent
operator|->
name|button
operator|==
literal|3
operator|)
operator|&&
name|gimp_context_get_palette
argument_list|(
name|palette_dialog
operator|->
name|context
argument_list|)
condition|)
block|{
if|if
condition|(
name|list
condition|)
block|{
if|if
condition|(
name|palette_dialog
operator|->
name|color
condition|)
block|{
name|palette_dialog
operator|->
name|freeze_update
operator|=
name|TRUE
expr_stmt|;
name|palette_dialog_draw_entries
argument_list|(
name|palette_dialog
argument_list|,
operator|-
literal|1
argument_list|,
operator|-
literal|1
argument_list|)
expr_stmt|;
name|palette_dialog
operator|->
name|freeze_update
operator|=
name|FALSE
expr_stmt|;
block|}
name|palette_dialog
operator|->
name|color
operator|=
operator|(
name|GimpPaletteEntry
operator|*
operator|)
name|list
operator|->
name|data
expr_stmt|;
if|if
condition|(
name|active_color
operator|==
name|FOREGROUND
condition|)
block|{
if|if
condition|(
name|bevent
operator|->
name|state
operator|&
name|GDK_CONTROL_MASK
condition|)
name|gimp_context_set_background
argument_list|(
name|gimp_context_get_user
argument_list|()
argument_list|,
operator|&
name|palette_dialog
operator|->
name|color
operator|->
name|color
argument_list|)
expr_stmt|;
else|else
name|gimp_context_set_foreground
argument_list|(
name|gimp_context_get_user
argument_list|()
argument_list|,
operator|&
name|palette_dialog
operator|->
name|color
operator|->
name|color
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|active_color
operator|==
name|BACKGROUND
condition|)
block|{
if|if
condition|(
name|bevent
operator|->
name|state
operator|&
name|GDK_CONTROL_MASK
condition|)
name|gimp_context_set_foreground
argument_list|(
name|gimp_context_get_user
argument_list|()
argument_list|,
operator|&
name|palette_dialog
operator|->
name|color
operator|->
name|color
argument_list|)
expr_stmt|;
else|else
name|gimp_context_set_background
argument_list|(
name|gimp_context_get_user
argument_list|()
argument_list|,
operator|&
name|palette_dialog
operator|->
name|color
operator|->
name|color
argument_list|)
expr_stmt|;
block|}
name|palette_dialog_draw_entries
argument_list|(
name|palette_dialog
argument_list|,
name|row
argument_list|,
name|col
argument_list|)
expr_stmt|;
comment|/*  Update the active color name  */
name|gtk_entry_set_text
argument_list|(
name|GTK_ENTRY
argument_list|(
name|palette_dialog
operator|->
name|color_name
argument_list|)
argument_list|,
name|palette_dialog
operator|->
name|color
operator|->
name|name
argument_list|)
expr_stmt|;
name|gtk_widget_set_sensitive
argument_list|(
name|palette_dialog
operator|->
name|color_name
argument_list|,
name|TRUE
argument_list|)
expr_stmt|;
comment|/* palette_update_current_entry (palette_dialog); */
if|if
condition|(
name|bevent
operator|->
name|button
operator|==
literal|3
condition|)
block|{
if|if
condition|(
operator|!
name|GTK_WIDGET_SENSITIVE
argument_list|(
name|palette_dialog
operator|->
name|edit_menu_item
argument_list|)
condition|)
block|{
name|gtk_widget_set_sensitive
argument_list|(
name|palette_dialog
operator|->
name|edit_menu_item
argument_list|,
name|TRUE
argument_list|)
expr_stmt|;
name|gtk_widget_set_sensitive
argument_list|(
name|palette_dialog
operator|->
name|delete_menu_item
argument_list|,
name|TRUE
argument_list|)
expr_stmt|;
block|}
name|gtk_menu_popup
argument_list|(
name|GTK_MENU
argument_list|(
name|palette_dialog
operator|->
name|popup_menu
argument_list|)
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|,
literal|3
argument_list|,
name|bevent
operator|->
name|time
argument_list|)
expr_stmt|;
block|}
block|}
else|else
block|{
if|if
condition|(
name|bevent
operator|->
name|button
operator|==
literal|3
condition|)
block|{
if|if
condition|(
name|GTK_WIDGET_SENSITIVE
argument_list|(
name|palette_dialog
operator|->
name|edit_menu_item
argument_list|)
condition|)
block|{
name|gtk_widget_set_sensitive
argument_list|(
name|palette_dialog
operator|->
name|edit_menu_item
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gtk_widget_set_sensitive
argument_list|(
name|palette_dialog
operator|->
name|delete_menu_item
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
block|}
name|gtk_menu_popup
argument_list|(
name|GTK_MENU
argument_list|(
name|palette_dialog
operator|->
name|popup_menu
argument_list|)
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|,
literal|3
argument_list|,
name|bevent
operator|->
name|time
argument_list|)
expr_stmt|;
block|}
block|}
block|}
break|break;
default|default:
break|break;
block|}
return|return
name|FALSE
return|;
block|}
end_function

begin_comment
comment|/*  functions for drawing& updating the palette dialog color area  **********/
end_comment

begin_function
specifier|static
name|gint
DECL|function|palette_dialog_draw_color_row (guchar * colors,gint n_colors,gint y,gint column_highlight,guchar * buffer,PaletteDialog * palette_dialog)
name|palette_dialog_draw_color_row
parameter_list|(
name|guchar
modifier|*
name|colors
parameter_list|,
name|gint
name|n_colors
parameter_list|,
name|gint
name|y
parameter_list|,
name|gint
name|column_highlight
parameter_list|,
name|guchar
modifier|*
name|buffer
parameter_list|,
name|PaletteDialog
modifier|*
name|palette_dialog
parameter_list|)
block|{
name|guchar
modifier|*
name|p
decl_stmt|;
name|guchar
name|bcolor
decl_stmt|;
name|gint
name|width
decl_stmt|,
name|height
decl_stmt|;
name|gint
name|entry_width
decl_stmt|;
name|gint
name|entry_height
decl_stmt|;
name|gint
name|vsize
decl_stmt|;
name|gint
name|vspacing
decl_stmt|;
name|gint
name|i
decl_stmt|,
name|j
decl_stmt|;
name|GtkWidget
modifier|*
name|preview
decl_stmt|;
if|if
condition|(
operator|!
name|palette_dialog
condition|)
return|return
operator|-
literal|1
return|;
name|preview
operator|=
name|palette_dialog
operator|->
name|color_area
expr_stmt|;
name|bcolor
operator|=
literal|0
expr_stmt|;
name|width
operator|=
name|preview
operator|->
name|requisition
operator|.
name|width
expr_stmt|;
name|height
operator|=
name|preview
operator|->
name|requisition
operator|.
name|height
expr_stmt|;
name|entry_width
operator|=
name|palette_dialog
operator|->
name|col_width
expr_stmt|;
name|entry_height
operator|=
operator|(
name|ENTRY_HEIGHT
operator|*
name|palette_dialog
operator|->
name|zoom_factor
operator|)
expr_stmt|;
if|if
condition|(
operator|(
name|y
operator|>=
literal|0
operator|)
operator|&&
operator|(
operator|(
name|y
operator|+
name|SPACING
operator|)
operator|<
name|height
operator|)
condition|)
name|vspacing
operator|=
name|SPACING
expr_stmt|;
elseif|else
if|if
condition|(
name|y
operator|<
literal|0
condition|)
name|vspacing
operator|=
name|SPACING
operator|+
name|y
expr_stmt|;
else|else
name|vspacing
operator|=
name|height
operator|-
name|y
expr_stmt|;
if|if
condition|(
name|vspacing
operator|>
literal|0
condition|)
block|{
if|if
condition|(
name|y
operator|<
literal|0
condition|)
name|y
operator|+=
name|SPACING
operator|-
name|vspacing
expr_stmt|;
for|for
control|(
name|i
operator|=
name|SPACING
operator|-
name|vspacing
init|;
name|i
operator|<
name|SPACING
condition|;
name|i
operator|++
operator|,
name|y
operator|++
control|)
block|{
name|p
operator|=
name|buffer
expr_stmt|;
for|for
control|(
name|j
operator|=
literal|0
init|;
name|j
operator|<
name|width
condition|;
name|j
operator|++
control|)
block|{
operator|*
name|p
operator|++
operator|=
name|bcolor
expr_stmt|;
operator|*
name|p
operator|++
operator|=
name|bcolor
expr_stmt|;
operator|*
name|p
operator|++
operator|=
name|bcolor
expr_stmt|;
block|}
if|if
condition|(
name|column_highlight
operator|>=
literal|0
condition|)
block|{
name|guchar
modifier|*
name|ph
decl_stmt|;
name|ph
operator|=
operator|&
name|buffer
index|[
literal|3
operator|*
name|column_highlight
operator|*
operator|(
name|entry_width
operator|+
name|SPACING
operator|)
index|]
expr_stmt|;
for|for
control|(
name|j
operator|=
literal|0
init|;
name|j
operator|<=
name|entry_width
operator|+
name|SPACING
condition|;
name|j
operator|++
control|)
block|{
operator|*
name|ph
operator|++
operator|=
operator|~
name|bcolor
expr_stmt|;
operator|*
name|ph
operator|++
operator|=
operator|~
name|bcolor
expr_stmt|;
operator|*
name|ph
operator|++
operator|=
operator|~
name|bcolor
expr_stmt|;
block|}
name|gtk_preview_draw_row
argument_list|(
name|GTK_PREVIEW
argument_list|(
name|preview
argument_list|)
argument_list|,
name|buffer
argument_list|,
literal|0
argument_list|,
name|y
operator|+
name|entry_height
operator|+
literal|1
argument_list|,
name|width
argument_list|)
expr_stmt|;
block|}
name|gtk_preview_draw_row
argument_list|(
name|GTK_PREVIEW
argument_list|(
name|preview
argument_list|)
argument_list|,
name|buffer
argument_list|,
literal|0
argument_list|,
name|y
argument_list|,
name|width
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|y
operator|>
name|SPACING
condition|)
name|y
operator|+=
name|SPACING
operator|-
name|vspacing
expr_stmt|;
block|}
else|else
name|y
operator|+=
name|SPACING
expr_stmt|;
name|vsize
operator|=
operator|(
name|y
operator|>=
literal|0
operator|)
condition|?
operator|(
name|entry_height
operator|)
else|:
operator|(
name|entry_height
operator|+
name|y
operator|)
expr_stmt|;
if|if
condition|(
operator|(
name|y
operator|>=
literal|0
operator|)
operator|&&
operator|(
operator|(
name|y
operator|+
name|entry_height
operator|)
operator|<
name|height
operator|)
condition|)
name|vsize
operator|=
name|entry_height
expr_stmt|;
elseif|else
if|if
condition|(
name|y
operator|<
literal|0
condition|)
name|vsize
operator|=
name|entry_height
operator|+
name|y
expr_stmt|;
else|else
name|vsize
operator|=
name|height
operator|-
name|y
expr_stmt|;
if|if
condition|(
name|vsize
operator|>
literal|0
condition|)
block|{
name|p
operator|=
name|buffer
expr_stmt|;
for|for
control|(
name|i
operator|=
literal|0
init|;
name|i
operator|<
name|n_colors
condition|;
name|i
operator|++
control|)
block|{
for|for
control|(
name|j
operator|=
literal|0
init|;
name|j
operator|<
name|SPACING
condition|;
name|j
operator|++
control|)
block|{
operator|*
name|p
operator|++
operator|=
name|bcolor
expr_stmt|;
operator|*
name|p
operator|++
operator|=
name|bcolor
expr_stmt|;
operator|*
name|p
operator|++
operator|=
name|bcolor
expr_stmt|;
block|}
for|for
control|(
name|j
operator|=
literal|0
init|;
name|j
operator|<
name|entry_width
condition|;
name|j
operator|++
control|)
block|{
operator|*
name|p
operator|++
operator|=
name|colors
index|[
name|i
operator|*
literal|3
index|]
expr_stmt|;
operator|*
name|p
operator|++
operator|=
name|colors
index|[
name|i
operator|*
literal|3
operator|+
literal|1
index|]
expr_stmt|;
operator|*
name|p
operator|++
operator|=
name|colors
index|[
name|i
operator|*
literal|3
operator|+
literal|2
index|]
expr_stmt|;
block|}
block|}
for|for
control|(
name|i
operator|=
literal|0
init|;
name|i
operator|<
operator|(
name|palette_dialog
operator|->
name|columns
operator|-
name|n_colors
operator|)
condition|;
name|i
operator|++
control|)
block|{
for|for
control|(
name|j
operator|=
literal|0
init|;
name|j
operator|<
operator|(
name|SPACING
operator|+
name|entry_width
operator|)
condition|;
name|j
operator|++
control|)
block|{
operator|*
name|p
operator|++
operator|=
literal|0
expr_stmt|;
operator|*
name|p
operator|++
operator|=
literal|0
expr_stmt|;
operator|*
name|p
operator|++
operator|=
literal|0
expr_stmt|;
block|}
block|}
for|for
control|(
name|j
operator|=
literal|0
init|;
name|j
operator|<
name|SPACING
condition|;
name|j
operator|++
control|)
block|{
if|if
condition|(
name|n_colors
operator|==
name|column_highlight
condition|)
block|{
operator|*
name|p
operator|++
operator|=
operator|~
name|bcolor
expr_stmt|;
operator|*
name|p
operator|++
operator|=
operator|~
name|bcolor
expr_stmt|;
operator|*
name|p
operator|++
operator|=
operator|~
name|bcolor
expr_stmt|;
block|}
else|else
block|{
operator|*
name|p
operator|++
operator|=
name|bcolor
expr_stmt|;
operator|*
name|p
operator|++
operator|=
name|bcolor
expr_stmt|;
operator|*
name|p
operator|++
operator|=
name|bcolor
expr_stmt|;
block|}
block|}
if|if
condition|(
name|y
operator|<
literal|0
condition|)
name|y
operator|+=
name|entry_height
operator|-
name|vsize
expr_stmt|;
for|for
control|(
name|i
operator|=
literal|0
init|;
name|i
operator|<
name|vsize
condition|;
name|i
operator|++
operator|,
name|y
operator|++
control|)
block|{
if|if
condition|(
name|column_highlight
operator|>=
literal|0
condition|)
block|{
name|guchar
modifier|*
name|ph
decl_stmt|;
name|ph
operator|=
operator|&
name|buffer
index|[
literal|3
operator|*
name|column_highlight
operator|*
operator|(
name|entry_width
operator|+
name|SPACING
operator|)
index|]
expr_stmt|;
operator|*
name|ph
operator|++
operator|=
operator|~
name|bcolor
expr_stmt|;
operator|*
name|ph
operator|++
operator|=
operator|~
name|bcolor
expr_stmt|;
operator|*
name|ph
operator|++
operator|=
operator|~
name|bcolor
expr_stmt|;
name|ph
operator|+=
literal|3
operator|*
operator|(
name|entry_width
operator|)
expr_stmt|;
operator|*
name|ph
operator|++
operator|=
operator|~
name|bcolor
expr_stmt|;
operator|*
name|ph
operator|++
operator|=
operator|~
name|bcolor
expr_stmt|;
operator|*
name|ph
operator|++
operator|=
operator|~
name|bcolor
expr_stmt|;
block|}
name|gtk_preview_draw_row
argument_list|(
name|GTK_PREVIEW
argument_list|(
name|preview
argument_list|)
argument_list|,
name|buffer
argument_list|,
literal|0
argument_list|,
name|y
argument_list|,
name|width
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|y
operator|>
name|entry_height
condition|)
name|y
operator|+=
name|entry_height
operator|-
name|vsize
expr_stmt|;
block|}
else|else
name|y
operator|+=
name|entry_height
expr_stmt|;
return|return
name|y
return|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|palette_dialog_draw_entries (PaletteDialog * palette_dialog,gint row_start,gint column_highlight)
name|palette_dialog_draw_entries
parameter_list|(
name|PaletteDialog
modifier|*
name|palette_dialog
parameter_list|,
name|gint
name|row_start
parameter_list|,
name|gint
name|column_highlight
parameter_list|)
block|{
name|GimpPaletteEntry
modifier|*
name|entry
decl_stmt|;
name|guchar
modifier|*
name|buffer
decl_stmt|;
name|guchar
modifier|*
name|colors
decl_stmt|;
name|GList
modifier|*
name|list
decl_stmt|;
name|gint
name|width
decl_stmt|,
name|height
decl_stmt|;
name|gint
name|entry_width
decl_stmt|;
name|gint
name|entry_height
decl_stmt|;
name|gint
name|index
decl_stmt|,
name|y
decl_stmt|;
if|if
condition|(
operator|!
operator|(
name|palette_dialog
operator|&&
name|gimp_context_get_palette
argument_list|(
name|palette_dialog
operator|->
name|context
argument_list|)
operator|)
condition|)
return|return;
name|width
operator|=
name|palette_dialog
operator|->
name|color_area
operator|->
name|requisition
operator|.
name|width
expr_stmt|;
name|height
operator|=
name|palette_dialog
operator|->
name|color_area
operator|->
name|requisition
operator|.
name|height
expr_stmt|;
name|entry_width
operator|=
name|palette_dialog
operator|->
name|col_width
expr_stmt|;
name|entry_height
operator|=
operator|(
name|ENTRY_HEIGHT
operator|*
name|palette_dialog
operator|->
name|zoom_factor
operator|)
expr_stmt|;
if|if
condition|(
name|entry_width
operator|<=
literal|0
condition|)
return|return;
name|colors
operator|=
name|g_new
argument_list|(
name|guchar
argument_list|,
name|palette_dialog
operator|->
name|columns
operator|*
literal|3
argument_list|)
expr_stmt|;
name|buffer
operator|=
name|g_new
argument_list|(
name|guchar
argument_list|,
name|width
operator|*
literal|3
argument_list|)
expr_stmt|;
if|if
condition|(
name|row_start
operator|<
literal|0
condition|)
block|{
name|y
operator|=
literal|0
expr_stmt|;
name|list
operator|=
name|gimp_context_get_palette
argument_list|(
name|palette_dialog
operator|->
name|context
argument_list|)
operator|->
name|colors
expr_stmt|;
name|column_highlight
operator|=
operator|-
literal|1
expr_stmt|;
block|}
else|else
block|{
name|y
operator|=
operator|(
name|entry_height
operator|+
name|SPACING
operator|)
operator|*
name|row_start
expr_stmt|;
name|list
operator|=
name|g_list_nth
argument_list|(
name|gimp_context_get_palette
argument_list|(
name|palette_dialog
operator|->
name|context
argument_list|)
operator|->
name|colors
argument_list|,
name|row_start
operator|*
name|palette_dialog
operator|->
name|columns
argument_list|)
expr_stmt|;
block|}
name|index
operator|=
literal|0
expr_stmt|;
for|for
control|(
init|;
name|list
condition|;
name|list
operator|=
name|g_list_next
argument_list|(
name|list
argument_list|)
control|)
block|{
name|entry
operator|=
operator|(
name|GimpPaletteEntry
operator|*
operator|)
name|list
operator|->
name|data
expr_stmt|;
name|gimp_rgb_get_uchar
argument_list|(
operator|&
name|entry
operator|->
name|color
argument_list|,
operator|&
name|colors
index|[
name|index
operator|*
literal|3
index|]
argument_list|,
operator|&
name|colors
index|[
name|index
operator|*
literal|3
operator|+
literal|1
index|]
argument_list|,
operator|&
name|colors
index|[
name|index
operator|*
literal|3
operator|+
literal|2
index|]
argument_list|)
expr_stmt|;
name|index
operator|++
expr_stmt|;
if|if
condition|(
name|index
operator|==
name|palette_dialog
operator|->
name|columns
condition|)
block|{
name|index
operator|=
literal|0
expr_stmt|;
name|y
operator|=
name|palette_dialog_draw_color_row
argument_list|(
name|colors
argument_list|,
name|palette_dialog
operator|->
name|columns
argument_list|,
name|y
argument_list|,
name|column_highlight
argument_list|,
name|buffer
argument_list|,
name|palette_dialog
argument_list|)
expr_stmt|;
if|if
condition|(
name|y
operator|>=
name|height
operator|||
name|row_start
operator|>=
literal|0
condition|)
block|{
comment|/* This row only */
name|gtk_widget_draw
argument_list|(
name|palette_dialog
operator|->
name|color_area
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|buffer
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|colors
argument_list|)
expr_stmt|;
return|return;
block|}
block|}
block|}
while|while
condition|(
name|y
operator|<
name|height
condition|)
block|{
name|y
operator|=
name|palette_dialog_draw_color_row
argument_list|(
name|colors
argument_list|,
name|index
argument_list|,
name|y
argument_list|,
name|column_highlight
argument_list|,
name|buffer
argument_list|,
name|palette_dialog
argument_list|)
expr_stmt|;
name|index
operator|=
literal|0
expr_stmt|;
if|if
condition|(
name|row_start
operator|>=
literal|0
condition|)
break|break;
block|}
name|g_free
argument_list|(
name|buffer
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|colors
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|palette_dialog
operator|->
name|freeze_update
condition|)
name|gtk_widget_draw
argument_list|(
name|palette_dialog
operator|->
name|color_area
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|palette_dialog_scroll_top_left (PaletteDialog * palette_dialog)
name|palette_dialog_scroll_top_left
parameter_list|(
name|PaletteDialog
modifier|*
name|palette_dialog
parameter_list|)
block|{
name|GtkAdjustment
modifier|*
name|hadj
decl_stmt|;
name|GtkAdjustment
modifier|*
name|vadj
decl_stmt|;
if|if
condition|(
operator|!
operator|(
name|palette_dialog
operator|&&
name|palette_dialog
operator|->
name|scrolled_window
operator|)
condition|)
return|return;
name|hadj
operator|=
name|gtk_scrolled_window_get_hadjustment
argument_list|(
name|GTK_SCROLLED_WINDOW
argument_list|(
name|palette_dialog
operator|->
name|scrolled_window
argument_list|)
argument_list|)
expr_stmt|;
name|vadj
operator|=
name|gtk_scrolled_window_get_vadjustment
argument_list|(
name|GTK_SCROLLED_WINDOW
argument_list|(
name|palette_dialog
operator|->
name|scrolled_window
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|hadj
condition|)
name|gtk_adjustment_set_value
argument_list|(
name|hadj
argument_list|,
literal|0.0
argument_list|)
expr_stmt|;
if|if
condition|(
name|vadj
condition|)
name|gtk_adjustment_set_value
argument_list|(
name|vadj
argument_list|,
literal|0.0
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|palette_dialog_redraw (PaletteDialog * palette_dialog)
name|palette_dialog_redraw
parameter_list|(
name|PaletteDialog
modifier|*
name|palette_dialog
parameter_list|)
block|{
name|GtkWidget
modifier|*
name|parent
decl_stmt|;
name|gint
name|vsize
decl_stmt|;
name|gint
name|nrows
decl_stmt|;
name|gint
name|n_entries
decl_stmt|;
name|gint
name|preview_width
decl_stmt|;
name|guint
name|width
decl_stmt|;
if|if
condition|(
operator|!
name|gimp_context_get_palette
argument_list|(
name|palette_dialog
operator|->
name|context
argument_list|)
condition|)
return|return;
name|width
operator|=
name|palette_dialog
operator|->
name|color_area
operator|->
name|parent
operator|->
name|parent
operator|->
name|parent
operator|->
name|allocation
operator|.
name|width
expr_stmt|;
if|if
condition|(
operator|(
name|palette_dialog
operator|->
name|columns_valid
operator|)
operator|&&
name|palette_dialog
operator|->
name|last_width
operator|==
name|width
condition|)
return|return;
name|palette_dialog
operator|->
name|last_width
operator|=
name|width
expr_stmt|;
name|palette_dialog
operator|->
name|col_width
operator|=
name|width
operator|/
operator|(
name|palette_dialog
operator|->
name|columns
operator|+
literal|1
operator|)
operator|-
name|SPACING
expr_stmt|;
if|if
condition|(
name|palette_dialog
operator|->
name|col_width
operator|<
literal|0
condition|)
name|palette_dialog
operator|->
name|col_width
operator|=
literal|0
expr_stmt|;
name|palette_dialog
operator|->
name|columns_valid
operator|=
name|TRUE
expr_stmt|;
name|n_entries
operator|=
name|gimp_context_get_palette
argument_list|(
name|palette_dialog
operator|->
name|context
argument_list|)
operator|->
name|n_colors
expr_stmt|;
name|nrows
operator|=
name|n_entries
operator|/
name|palette_dialog
operator|->
name|columns
expr_stmt|;
if|if
condition|(
name|n_entries
operator|%
name|palette_dialog
operator|->
name|columns
condition|)
name|nrows
operator|+=
literal|1
expr_stmt|;
name|vsize
operator|=
name|nrows
operator|*
operator|(
name|SPACING
operator|+
call|(
name|gint
call|)
argument_list|(
name|ENTRY_HEIGHT
operator|*
name|palette_dialog
operator|->
name|zoom_factor
argument_list|)
operator|)
operator|+
name|SPACING
expr_stmt|;
name|parent
operator|=
name|palette_dialog
operator|->
name|color_area
operator|->
name|parent
operator|->
name|parent
expr_stmt|;
name|gtk_widget_ref
argument_list|(
name|palette_dialog
operator|->
name|color_area
operator|->
name|parent
argument_list|)
expr_stmt|;
name|gtk_container_remove
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|parent
argument_list|)
argument_list|,
name|palette_dialog
operator|->
name|color_area
operator|->
name|parent
argument_list|)
expr_stmt|;
name|preview_width
operator|=
operator|(
name|palette_dialog
operator|->
name|col_width
operator|+
name|SPACING
operator|)
operator|*
name|palette_dialog
operator|->
name|columns
operator|+
name|SPACING
expr_stmt|;
name|gtk_preview_size
argument_list|(
name|GTK_PREVIEW
argument_list|(
name|palette_dialog
operator|->
name|color_area
argument_list|)
argument_list|,
name|preview_width
argument_list|,
name|vsize
argument_list|)
expr_stmt|;
name|gtk_container_add
argument_list|(
name|GTK_CONTAINER
argument_list|(
name|parent
argument_list|)
argument_list|,
name|palette_dialog
operator|->
name|color_area
operator|->
name|parent
argument_list|)
expr_stmt|;
name|gtk_widget_unref
argument_list|(
name|palette_dialog
operator|->
name|color_area
operator|->
name|parent
argument_list|)
expr_stmt|;
if|if
condition|(
name|palette_dialog
operator|->
name|color
condition|)
name|palette_dialog_draw_entries
argument_list|(
name|palette_dialog
argument_list|,
name|palette_dialog
operator|->
name|color
operator|->
name|position
operator|/
name|palette_dialog
operator|->
name|columns
argument_list|,
name|palette_dialog
operator|->
name|color
operator|->
name|position
operator|%
name|palette_dialog
operator|->
name|columns
argument_list|)
expr_stmt|;
else|else
name|palette_dialog_draw_entries
argument_list|(
name|palette_dialog
argument_list|,
operator|-
literal|1
argument_list|,
operator|-
literal|1
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|palette_dialog_palette_changed (GimpContext * context,GimpPalette * palette,gpointer data)
name|palette_dialog_palette_changed
parameter_list|(
name|GimpContext
modifier|*
name|context
parameter_list|,
name|GimpPalette
modifier|*
name|palette
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|PaletteDialog
modifier|*
name|palette_dialog
decl_stmt|;
name|palette_dialog
operator|=
operator|(
name|PaletteDialog
operator|*
operator|)
name|data
expr_stmt|;
comment|/* FIXME */
if|if
condition|(
operator|!
name|palette
condition|)
return|return;
if|if
condition|(
name|palette_dialog
operator|->
name|color_notebook_active
condition|)
block|{
name|color_notebook_hide
argument_list|(
name|palette_dialog
operator|->
name|color_notebook
argument_list|)
expr_stmt|;
name|palette_dialog
operator|->
name|color_notebook_active
operator|=
name|FALSE
expr_stmt|;
block|}
if|if
condition|(
name|palette_dialog
operator|->
name|color_notebook
condition|)
name|color_notebook_free
argument_list|(
name|palette_dialog
operator|->
name|color_notebook
argument_list|)
expr_stmt|;
name|palette_dialog
operator|->
name|color_notebook
operator|=
name|NULL
expr_stmt|;
name|palette_dialog
operator|->
name|columns_valid
operator|=
name|FALSE
expr_stmt|;
name|palette_dialog_redraw
argument_list|(
name|palette_dialog
argument_list|)
expr_stmt|;
name|palette_dialog_scroll_top_left
argument_list|(
name|palette_dialog
argument_list|)
expr_stmt|;
comment|/*  Stop errors in case no colors are selected  */
name|gtk_signal_handler_block
argument_list|(
name|GTK_OBJECT
argument_list|(
name|palette_dialog
operator|->
name|color_name
argument_list|)
argument_list|,
name|palette_dialog
operator|->
name|entry_sig_id
argument_list|)
expr_stmt|;
name|gtk_entry_set_text
argument_list|(
name|GTK_ENTRY
argument_list|(
name|palette_dialog
operator|->
name|color_name
argument_list|)
argument_list|,
name|_
argument_list|(
literal|"Undefined"
argument_list|)
argument_list|)
expr_stmt|;
name|gtk_widget_set_sensitive
argument_list|(
name|palette_dialog
operator|->
name|color_name
argument_list|,
name|FALSE
argument_list|)
expr_stmt|;
name|gtk_signal_handler_unblock
argument_list|(
name|GTK_OBJECT
argument_list|(
name|palette_dialog
operator|->
name|color_name
argument_list|)
argument_list|,
name|palette_dialog
operator|->
name|entry_sig_id
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/*  the color name entry callback  *******************************************/
end_comment

begin_function
specifier|static
name|void
DECL|function|palette_dialog_color_name_changed (GtkWidget * widget,gpointer data)
name|palette_dialog_color_name_changed
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|PaletteDialog
modifier|*
name|palette_dialog
decl_stmt|;
name|palette_dialog
operator|=
operator|(
name|PaletteDialog
operator|*
operator|)
name|data
expr_stmt|;
name|g_return_if_fail
argument_list|(
name|gimp_context_get_palette
argument_list|(
name|palette_dialog
operator|->
name|context
argument_list|)
operator|!=
name|NULL
argument_list|)
expr_stmt|;
if|if
condition|(
name|palette_dialog
operator|->
name|color
operator|->
name|name
condition|)
name|g_free
argument_list|(
name|palette_dialog
operator|->
name|color
operator|->
name|name
argument_list|)
expr_stmt|;
name|palette_dialog
operator|->
name|color
operator|->
name|name
operator|=
name|g_strdup
argument_list|(
name|gtk_entry_get_text
argument_list|(
name|GTK_ENTRY
argument_list|(
name|palette_dialog
operator|->
name|color_name
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|gimp_data_dirty
argument_list|(
name|GIMP_DATA
argument_list|(
name|gimp_context_get_palette
argument_list|(
name|palette_dialog
operator|->
name|context
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/*  palette zoom functions& callbacks  **************************************/
end_comment

begin_function
specifier|static
name|void
DECL|function|palette_dialog_zoomin_callback (GtkWidget * widget,gpointer data)
name|palette_dialog_zoomin_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|PaletteDialog
modifier|*
name|palette_dialog
decl_stmt|;
name|palette_dialog
operator|=
operator|(
name|PaletteDialog
operator|*
operator|)
name|data
expr_stmt|;
name|palette_dialog
operator|->
name|zoom_factor
operator|+=
literal|0.1
expr_stmt|;
name|palette_dialog_redraw_zoom
argument_list|(
name|palette_dialog
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|palette_dialog_zoomout_callback (GtkWidget * widget,gpointer data)
name|palette_dialog_zoomout_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|PaletteDialog
modifier|*
name|palette_dialog
decl_stmt|;
name|palette_dialog
operator|=
operator|(
name|PaletteDialog
operator|*
operator|)
name|data
expr_stmt|;
name|palette_dialog
operator|->
name|zoom_factor
operator|-=
literal|0.1
expr_stmt|;
name|palette_dialog_redraw_zoom
argument_list|(
name|palette_dialog
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|palette_dialog_redraw_zoom (PaletteDialog * palette_dialog)
name|palette_dialog_redraw_zoom
parameter_list|(
name|PaletteDialog
modifier|*
name|palette_dialog
parameter_list|)
block|{
if|if
condition|(
name|palette_dialog
operator|->
name|zoom_factor
operator|>
literal|4.0
condition|)
block|{
name|palette_dialog
operator|->
name|zoom_factor
operator|=
literal|4.0
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|palette_dialog
operator|->
name|zoom_factor
operator|<
literal|0.1
condition|)
block|{
name|palette_dialog
operator|->
name|zoom_factor
operator|=
literal|0.1
expr_stmt|;
block|}
name|palette_dialog
operator|->
name|columns
operator|=
name|COLUMNS
expr_stmt|;
name|palette_dialog
operator|->
name|columns_valid
operator|=
name|FALSE
expr_stmt|;
name|palette_dialog_redraw
argument_list|(
name|palette_dialog
argument_list|)
expr_stmt|;
name|palette_dialog_scroll_top_left
argument_list|(
name|palette_dialog
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/*  the palette dialog action callbacks  **************************************/
end_comment

begin_function
specifier|static
name|void
DECL|function|palette_dialog_import_callback (GtkWidget * widget,gpointer data)
name|palette_dialog_import_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|palette_import_dialog_show
argument_list|()
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|palette_dialog_merge_callback (GtkWidget * widget,gpointer data)
name|palette_dialog_merge_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|GtkWidget
modifier|*
name|qbox
decl_stmt|;
name|qbox
operator|=
name|gimp_query_string_box
argument_list|(
name|_
argument_list|(
literal|"Merge Palette"
argument_list|)
argument_list|,
name|gimp_standard_help_func
argument_list|,
literal|"dialogs/palette_editor/merge_palette.html"
argument_list|,
name|_
argument_list|(
literal|"Enter a name for merged palette"
argument_list|)
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|,
name|NULL
argument_list|,
name|palette_dialog_do_merge_callback
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|gtk_widget_show
argument_list|(
name|qbox
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|palette_dialog_do_merge_callback (GtkWidget * widget,gchar * palette_name,gpointer data)
name|palette_dialog_do_merge_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gchar
modifier|*
name|palette_name
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|PaletteDialog
modifier|*
name|palette_dialog
decl_stmt|;
name|GimpPalette
modifier|*
name|palette
decl_stmt|;
name|GimpPalette
modifier|*
name|new_palette
decl_stmt|;
name|GimpPaletteEntry
modifier|*
name|entry
decl_stmt|;
name|GList
modifier|*
name|sel_list
decl_stmt|;
name|new_palette
operator|=
name|GIMP_PALETTE
argument_list|(
name|gimp_palette_new
argument_list|(
name|palette_name
argument_list|)
argument_list|)
expr_stmt|;
name|palette_dialog
operator|=
operator|(
name|PaletteDialog
operator|*
operator|)
name|data
expr_stmt|;
name|sel_list
operator|=
name|GTK_LIST
argument_list|(
name|GIMP_CONTAINER_LIST_VIEW
argument_list|(
name|GIMP_DATA_FACTORY_VIEW
argument_list|(
name|palette_dialog
operator|->
name|view
argument_list|)
operator|->
name|view
argument_list|)
operator|->
name|gtk_list
argument_list|)
operator|->
name|selection
expr_stmt|;
while|while
condition|(
name|sel_list
condition|)
block|{
name|GtkWidget
modifier|*
name|list_item
decl_stmt|;
name|GList
modifier|*
name|cols
decl_stmt|;
name|list_item
operator|=
name|GTK_WIDGET
argument_list|(
name|sel_list
operator|->
name|data
argument_list|)
expr_stmt|;
name|palette
operator|=
operator|(
name|GimpPalette
operator|*
operator|)
name|GIMP_PREVIEW
argument_list|(
name|gtk_object_get_data
argument_list|(
name|GTK_OBJECT
argument_list|(
name|list_item
argument_list|)
argument_list|,
literal|"preview"
argument_list|)
argument_list|)
operator|->
name|viewable
expr_stmt|;
if|if
condition|(
name|palette
condition|)
block|{
for|for
control|(
name|cols
operator|=
name|palette
operator|->
name|colors
init|;
name|cols
condition|;
name|cols
operator|=
name|g_list_next
argument_list|(
name|cols
argument_list|)
control|)
block|{
name|entry
operator|=
operator|(
name|GimpPaletteEntry
operator|*
operator|)
name|cols
operator|->
name|data
expr_stmt|;
name|gimp_palette_add_entry
argument_list|(
name|new_palette
argument_list|,
name|entry
operator|->
name|name
argument_list|,
operator|&
name|entry
operator|->
name|color
argument_list|)
expr_stmt|;
block|}
block|}
name|sel_list
operator|=
name|sel_list
operator|->
name|next
expr_stmt|;
block|}
name|gimp_container_add
argument_list|(
name|global_palette_factory
operator|->
name|container
argument_list|,
name|GIMP_OBJECT
argument_list|(
name|new_palette
argument_list|)
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|palette_dialog_close_callback (GtkWidget * widget,gpointer data)
name|palette_dialog_close_callback
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|PaletteDialog
modifier|*
name|palette_dialog
decl_stmt|;
name|palette_dialog
operator|=
operator|(
name|PaletteDialog
operator|*
operator|)
name|data
expr_stmt|;
if|if
condition|(
name|palette_dialog
condition|)
block|{
if|if
condition|(
name|palette_dialog
operator|->
name|color_notebook_active
condition|)
block|{
name|color_notebook_hide
argument_list|(
name|palette_dialog
operator|->
name|color_notebook
argument_list|)
expr_stmt|;
name|palette_dialog
operator|->
name|color_notebook_active
operator|=
name|FALSE
expr_stmt|;
block|}
if|if
condition|(
name|palette_dialog
operator|==
name|top_level_edit_palette
condition|)
block|{
name|palette_import_dialog_destroy
argument_list|()
expr_stmt|;
block|}
if|if
condition|(
name|GTK_WIDGET_VISIBLE
argument_list|(
name|palette_dialog
operator|->
name|shell
argument_list|)
condition|)
name|gtk_widget_hide
argument_list|(
name|palette_dialog
operator|->
name|shell
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_comment
comment|/*  the palette dialog color dnd callbacks  **********************************/
end_comment

begin_function
specifier|static
name|void
DECL|function|palette_dialog_drag_color (GtkWidget * widget,GimpRGB * color,gpointer data)
name|palette_dialog_drag_color
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
name|GimpRGB
modifier|*
name|color
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|PaletteDialog
modifier|*
name|palette_dialog
decl_stmt|;
name|palette_dialog
operator|=
operator|(
name|PaletteDialog
operator|*
operator|)
name|data
expr_stmt|;
if|if
condition|(
name|palette_dialog
operator|&&
name|gimp_context_get_palette
argument_list|(
name|palette_dialog
operator|->
name|context
argument_list|)
operator|&&
name|palette_dialog
operator|->
name|dnd_color
condition|)
block|{
operator|*
name|color
operator|=
name|palette_dialog
operator|->
name|dnd_color
operator|->
name|color
expr_stmt|;
block|}
else|else
block|{
name|gimp_rgba_set
argument_list|(
name|color
argument_list|,
literal|0.0
argument_list|,
literal|0.0
argument_list|,
literal|0.0
argument_list|,
literal|1.0
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|palette_dialog_drop_color (GtkWidget * widget,const GimpRGB * color,gpointer data)
name|palette_dialog_drop_color
parameter_list|(
name|GtkWidget
modifier|*
name|widget
parameter_list|,
specifier|const
name|GimpRGB
modifier|*
name|color
parameter_list|,
name|gpointer
name|data
parameter_list|)
block|{
name|PaletteDialog
modifier|*
name|palette_dialog
decl_stmt|;
name|palette_dialog
operator|=
operator|(
name|PaletteDialog
operator|*
operator|)
name|data
expr_stmt|;
if|if
condition|(
name|palette_dialog
operator|&&
name|gimp_context_get_palette
argument_list|(
name|palette_dialog
operator|->
name|context
argument_list|)
condition|)
block|{
name|palette_dialog
operator|->
name|color
operator|=
name|gimp_palette_add_entry
argument_list|(
name|gimp_context_get_palette
argument_list|(
name|palette_dialog
operator|->
name|context
argument_list|)
argument_list|,
name|NULL
argument_list|,
operator|(
name|GimpRGB
operator|*
operator|)
name|color
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|palette_dialog_invalidate_preview (GimpPalette * palette,PaletteDialog * palette_dialog)
name|palette_dialog_invalidate_preview
parameter_list|(
name|GimpPalette
modifier|*
name|palette
parameter_list|,
name|PaletteDialog
modifier|*
name|palette_dialog
parameter_list|)
block|{
if|if
condition|(
name|palette
operator|==
name|gimp_context_get_palette
argument_list|(
name|palette_dialog
operator|->
name|context
argument_list|)
condition|)
block|{
name|palette_dialog
operator|->
name|columns_valid
operator|=
name|FALSE
expr_stmt|;
name|palette_dialog_redraw
argument_list|(
name|palette_dialog
argument_list|)
expr_stmt|;
block|}
block|}
end_function

end_unit

