begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* GIMP - The GNU Image Manipulation Program  * Copyright (C) 1995 Spencer Kimball and Peter Mattis  *  * This program is free software: you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 3 of the License, or  * (at your option) any later version.  *  * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *  * You should have received a copy of the GNU General Public License  * along with this program.  If not, see<https://www.gnu.org/licenses/>.  */
end_comment

begin_include
include|#
directive|include
file|"config.h"
end_include

begin_include
include|#
directive|include
file|<string.h>
end_include

begin_include
include|#
directive|include
file|<gdk-pixbuf/gdk-pixbuf.h>
end_include

begin_include
include|#
directive|include
file|<gegl.h>
end_include

begin_include
include|#
directive|include
file|"libgimpbase/gimpbase.h"
end_include

begin_include
include|#
directive|include
file|"libgimpmath/gimpmath.h"
end_include

begin_include
include|#
directive|include
file|"core-types.h"
end_include

begin_include
include|#
directive|include
file|"gegl/gimp-gegl-mask-combine.h"
end_include

begin_include
include|#
directive|include
file|"gegl/gimp-gegl-utils.h"
end_include

begin_include
include|#
directive|include
file|"gimpchannel.h"
end_include

begin_include
include|#
directive|include
file|"gimpchannel-combine.h"
end_include

begin_typedef
typedef|typedef
struct|struct
DECL|struct|__anon2bb2c0be0108
block|{
DECL|member|rect
name|GeglRectangle
name|rect
decl_stmt|;
DECL|member|bounds_known
name|gboolean
name|bounds_known
decl_stmt|;
DECL|member|empty
name|gboolean
name|empty
decl_stmt|;
DECL|member|bounds
name|GeglRectangle
name|bounds
decl_stmt|;
DECL|typedef|GimpChannelCombineData
block|}
name|GimpChannelCombineData
typedef|;
end_typedef

begin_comment
comment|/*  local function prototypes  */
end_comment

begin_function_decl
specifier|static
name|void
name|gimp_channel_combine_clear
parameter_list|(
name|GimpChannel
modifier|*
name|mask
parameter_list|,
specifier|const
name|GeglRectangle
modifier|*
name|rect
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_channel_combine_clear_complement
parameter_list|(
name|GimpChannel
modifier|*
name|mask
parameter_list|,
specifier|const
name|GeglRectangle
modifier|*
name|rect
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|gboolean
name|gimp_channel_combine_start
parameter_list|(
name|GimpChannel
modifier|*
name|mask
parameter_list|,
name|GimpChannelOps
name|op
parameter_list|,
specifier|const
name|GeglRectangle
modifier|*
name|rect
parameter_list|,
name|gboolean
name|full_extent
parameter_list|,
name|gboolean
name|full_value
parameter_list|,
name|GimpChannelCombineData
modifier|*
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_channel_combine_end
parameter_list|(
name|GimpChannel
modifier|*
name|mask
parameter_list|,
name|GimpChannelCombineData
modifier|*
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_comment
comment|/*  private functions  */
end_comment

begin_function
specifier|static
name|void
DECL|function|gimp_channel_combine_clear (GimpChannel * mask,const GeglRectangle * rect)
name|gimp_channel_combine_clear
parameter_list|(
name|GimpChannel
modifier|*
name|mask
parameter_list|,
specifier|const
name|GeglRectangle
modifier|*
name|rect
parameter_list|)
block|{
name|GeglBuffer
modifier|*
name|buffer
decl_stmt|;
name|GeglRectangle
name|area
decl_stmt|;
name|GeglRectangle
name|update_area
decl_stmt|;
if|if
condition|(
name|mask
operator|->
name|bounds_known
operator|&&
name|mask
operator|->
name|empty
condition|)
return|return;
name|buffer
operator|=
name|gimp_drawable_get_buffer
argument_list|(
name|GIMP_DRAWABLE
argument_list|(
name|mask
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|rect
condition|)
block|{
if|if
condition|(
name|rect
operator|->
name|width
operator|<=
literal|0
operator|||
name|rect
operator|->
name|height
operator|<=
literal|0
condition|)
return|return;
if|if
condition|(
name|mask
operator|->
name|bounds_known
condition|)
block|{
if|if
condition|(
operator|!
name|gegl_rectangle_intersect
argument_list|(
operator|&
name|area
argument_list|,
name|GEGL_RECTANGLE
argument_list|(
name|mask
operator|->
name|x1
argument_list|,
name|mask
operator|->
name|y1
argument_list|,
name|mask
operator|->
name|x2
operator|-
name|mask
operator|->
name|x1
argument_list|,
name|mask
operator|->
name|y2
operator|-
name|mask
operator|->
name|y1
argument_list|)
argument_list|,
name|rect
argument_list|)
condition|)
block|{
return|return;
block|}
block|}
else|else
block|{
name|area
operator|=
operator|*
name|rect
expr_stmt|;
block|}
name|update_area
operator|=
name|area
expr_stmt|;
block|}
else|else
block|{
if|if
condition|(
name|mask
operator|->
name|bounds_known
condition|)
block|{
name|area
operator|.
name|x
operator|=
name|mask
operator|->
name|x1
expr_stmt|;
name|area
operator|.
name|y
operator|=
name|mask
operator|->
name|y1
expr_stmt|;
name|area
operator|.
name|width
operator|=
name|mask
operator|->
name|x2
operator|-
name|mask
operator|->
name|x1
expr_stmt|;
name|area
operator|.
name|height
operator|=
name|mask
operator|->
name|y2
operator|-
name|mask
operator|->
name|y1
expr_stmt|;
block|}
else|else
block|{
name|area
operator|.
name|x
operator|=
literal|0
expr_stmt|;
name|area
operator|.
name|y
operator|=
literal|0
expr_stmt|;
name|area
operator|.
name|width
operator|=
name|gimp_item_get_width
argument_list|(
name|GIMP_ITEM
argument_list|(
name|mask
argument_list|)
argument_list|)
expr_stmt|;
name|area
operator|.
name|height
operator|=
name|gimp_item_get_height
argument_list|(
name|GIMP_ITEM
argument_list|(
name|mask
argument_list|)
argument_list|)
expr_stmt|;
block|}
name|update_area
operator|=
name|area
expr_stmt|;
name|gimp_gegl_rectangle_align_to_tile_grid
argument_list|(
operator|&
name|area
argument_list|,
operator|&
name|area
argument_list|,
name|buffer
argument_list|)
expr_stmt|;
block|}
name|gegl_buffer_clear
argument_list|(
name|buffer
argument_list|,
operator|&
name|area
argument_list|)
expr_stmt|;
name|gimp_drawable_update
argument_list|(
name|GIMP_DRAWABLE
argument_list|(
name|mask
argument_list|)
argument_list|,
name|update_area
operator|.
name|x
argument_list|,
name|update_area
operator|.
name|y
argument_list|,
name|update_area
operator|.
name|width
argument_list|,
name|update_area
operator|.
name|height
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_channel_combine_clear_complement (GimpChannel * mask,const GeglRectangle * rect)
name|gimp_channel_combine_clear_complement
parameter_list|(
name|GimpChannel
modifier|*
name|mask
parameter_list|,
specifier|const
name|GeglRectangle
modifier|*
name|rect
parameter_list|)
block|{
name|gint
name|width
init|=
name|gimp_item_get_width
argument_list|(
name|GIMP_ITEM
argument_list|(
name|mask
argument_list|)
argument_list|)
decl_stmt|;
name|gint
name|height
init|=
name|gimp_item_get_height
argument_list|(
name|GIMP_ITEM
argument_list|(
name|mask
argument_list|)
argument_list|)
decl_stmt|;
name|gimp_channel_combine_clear
argument_list|(
name|mask
argument_list|,
name|GEGL_RECTANGLE
argument_list|(
literal|0
argument_list|,
literal|0
argument_list|,
name|width
argument_list|,
name|rect
operator|->
name|y
argument_list|)
argument_list|)
expr_stmt|;
name|gimp_channel_combine_clear
argument_list|(
name|mask
argument_list|,
name|GEGL_RECTANGLE
argument_list|(
literal|0
argument_list|,
name|rect
operator|->
name|y
operator|+
name|rect
operator|->
name|height
argument_list|,
name|width
argument_list|,
name|height
operator|-
operator|(
name|rect
operator|->
name|y
operator|+
name|rect
operator|->
name|height
operator|)
argument_list|)
argument_list|)
expr_stmt|;
name|gimp_channel_combine_clear
argument_list|(
name|mask
argument_list|,
name|GEGL_RECTANGLE
argument_list|(
literal|0
argument_list|,
name|rect
operator|->
name|y
argument_list|,
name|rect
operator|->
name|x
argument_list|,
name|rect
operator|->
name|height
argument_list|)
argument_list|)
expr_stmt|;
name|gimp_channel_combine_clear
argument_list|(
name|mask
argument_list|,
name|GEGL_RECTANGLE
argument_list|(
name|rect
operator|->
name|x
operator|+
name|rect
operator|->
name|width
argument_list|,
name|rect
operator|->
name|y
argument_list|,
name|width
operator|-
operator|(
name|rect
operator|->
name|x
operator|+
name|rect
operator|->
name|width
operator|)
argument_list|,
name|rect
operator|->
name|height
argument_list|)
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|gboolean
DECL|function|gimp_channel_combine_start (GimpChannel * mask,GimpChannelOps op,const GeglRectangle * rect,gboolean full_extent,gboolean full_value,GimpChannelCombineData * data)
name|gimp_channel_combine_start
parameter_list|(
name|GimpChannel
modifier|*
name|mask
parameter_list|,
name|GimpChannelOps
name|op
parameter_list|,
specifier|const
name|GeglRectangle
modifier|*
name|rect
parameter_list|,
name|gboolean
name|full_extent
parameter_list|,
name|gboolean
name|full_value
parameter_list|,
name|GimpChannelCombineData
modifier|*
name|data
parameter_list|)
block|{
name|GeglBuffer
modifier|*
name|buffer
init|=
name|gimp_drawable_get_buffer
argument_list|(
name|GIMP_DRAWABLE
argument_list|(
name|mask
argument_list|)
argument_list|)
decl_stmt|;
name|GeglRectangle
name|extent
decl_stmt|;
name|gboolean
name|intersects
decl_stmt|;
name|extent
operator|.
name|x
operator|=
literal|0
expr_stmt|;
name|extent
operator|.
name|y
operator|=
literal|0
expr_stmt|;
name|extent
operator|.
name|width
operator|=
name|gimp_item_get_width
argument_list|(
name|GIMP_ITEM
argument_list|(
name|mask
argument_list|)
argument_list|)
expr_stmt|;
name|extent
operator|.
name|height
operator|=
name|gimp_item_get_height
argument_list|(
name|GIMP_ITEM
argument_list|(
name|mask
argument_list|)
argument_list|)
expr_stmt|;
name|intersects
operator|=
name|gegl_rectangle_intersect
argument_list|(
operator|&
name|data
operator|->
name|rect
argument_list|,
name|rect
argument_list|,
operator|&
name|extent
argument_list|)
expr_stmt|;
name|data
operator|->
name|bounds_known
operator|=
name|mask
operator|->
name|bounds_known
expr_stmt|;
name|data
operator|->
name|empty
operator|=
name|mask
operator|->
name|empty
expr_stmt|;
name|data
operator|->
name|bounds
operator|.
name|x
operator|=
name|mask
operator|->
name|x1
expr_stmt|;
name|data
operator|->
name|bounds
operator|.
name|y
operator|=
name|mask
operator|->
name|y1
expr_stmt|;
name|data
operator|->
name|bounds
operator|.
name|width
operator|=
name|mask
operator|->
name|x2
operator|-
name|mask
operator|->
name|x1
expr_stmt|;
name|data
operator|->
name|bounds
operator|.
name|height
operator|=
name|mask
operator|->
name|y2
operator|-
name|mask
operator|->
name|y1
expr_stmt|;
name|gegl_buffer_freeze_changed
argument_list|(
name|buffer
argument_list|)
expr_stmt|;
comment|/*  Determine new boundary  */
switch|switch
condition|(
name|op
condition|)
block|{
case|case
name|GIMP_CHANNEL_OP_REPLACE
case|:
name|gimp_channel_combine_clear
argument_list|(
name|mask
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|intersects
condition|)
block|{
name|data
operator|->
name|bounds_known
operator|=
name|TRUE
expr_stmt|;
name|data
operator|->
name|empty
operator|=
name|TRUE
expr_stmt|;
return|return
name|FALSE
return|;
block|}
name|data
operator|->
name|bounds_known
operator|=
name|FALSE
expr_stmt|;
if|if
condition|(
name|full_extent
condition|)
block|{
name|data
operator|->
name|bounds_known
operator|=
name|TRUE
expr_stmt|;
name|data
operator|->
name|empty
operator|=
name|FALSE
expr_stmt|;
name|data
operator|->
name|bounds
operator|=
name|data
operator|->
name|rect
expr_stmt|;
block|}
break|break;
case|case
name|GIMP_CHANNEL_OP_ADD
case|:
if|if
condition|(
operator|!
name|intersects
condition|)
return|return
name|FALSE
return|;
name|data
operator|->
name|bounds_known
operator|=
name|FALSE
expr_stmt|;
if|if
condition|(
name|full_extent
operator|&&
operator|(
name|mask
operator|->
name|bounds_known
operator|||
name|gegl_rectangle_equal
argument_list|(
operator|&
name|data
operator|->
name|rect
argument_list|,
operator|&
name|extent
argument_list|)
operator|)
condition|)
block|{
name|data
operator|->
name|bounds_known
operator|=
name|TRUE
expr_stmt|;
name|data
operator|->
name|empty
operator|=
name|FALSE
expr_stmt|;
if|if
condition|(
name|mask
operator|->
name|bounds_known
operator|&&
operator|!
name|mask
operator|->
name|empty
condition|)
block|{
name|gegl_rectangle_bounding_box
argument_list|(
operator|&
name|data
operator|->
name|bounds
argument_list|,
operator|&
name|data
operator|->
name|bounds
argument_list|,
operator|&
name|data
operator|->
name|rect
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|data
operator|->
name|bounds
operator|=
name|data
operator|->
name|rect
expr_stmt|;
block|}
block|}
break|break;
case|case
name|GIMP_CHANNEL_OP_SUBTRACT
case|:
if|if
condition|(
name|intersects
operator|&&
name|mask
operator|->
name|bounds_known
condition|)
block|{
if|if
condition|(
name|mask
operator|->
name|empty
condition|)
block|{
name|intersects
operator|=
name|FALSE
expr_stmt|;
block|}
else|else
block|{
name|intersects
operator|=
name|gegl_rectangle_intersect
argument_list|(
operator|&
name|data
operator|->
name|rect
argument_list|,
operator|&
name|data
operator|->
name|rect
argument_list|,
operator|&
name|data
operator|->
name|bounds
argument_list|)
expr_stmt|;
block|}
block|}
if|if
condition|(
operator|!
name|intersects
condition|)
return|return
name|FALSE
return|;
if|if
condition|(
name|full_value
operator|&&
name|gegl_rectangle_contains
argument_list|(
operator|&
name|data
operator|->
name|rect
argument_list|,
name|mask
operator|->
name|bounds_known
condition|?
operator|&
name|data
operator|->
name|bounds
else|:
operator|&
name|extent
argument_list|)
condition|)
block|{
name|gimp_channel_combine_clear
argument_list|(
name|mask
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|data
operator|->
name|bounds_known
operator|=
name|TRUE
expr_stmt|;
name|data
operator|->
name|empty
operator|=
name|TRUE
expr_stmt|;
return|return
name|FALSE
return|;
block|}
name|data
operator|->
name|bounds_known
operator|=
name|FALSE
expr_stmt|;
name|gegl_buffer_set_abyss
argument_list|(
name|buffer
argument_list|,
operator|&
name|data
operator|->
name|rect
argument_list|)
expr_stmt|;
break|break;
case|case
name|GIMP_CHANNEL_OP_INTERSECT
case|:
if|if
condition|(
name|intersects
operator|&&
name|mask
operator|->
name|bounds_known
condition|)
block|{
if|if
condition|(
name|mask
operator|->
name|empty
condition|)
block|{
name|intersects
operator|=
name|FALSE
expr_stmt|;
block|}
else|else
block|{
name|intersects
operator|=
name|gegl_rectangle_intersect
argument_list|(
operator|&
name|data
operator|->
name|rect
argument_list|,
operator|&
name|data
operator|->
name|rect
argument_list|,
operator|&
name|data
operator|->
name|bounds
argument_list|)
expr_stmt|;
block|}
block|}
if|if
condition|(
operator|!
name|intersects
condition|)
block|{
name|gimp_channel_combine_clear
argument_list|(
name|mask
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|data
operator|->
name|bounds_known
operator|=
name|TRUE
expr_stmt|;
name|data
operator|->
name|empty
operator|=
name|TRUE
expr_stmt|;
return|return
name|FALSE
return|;
block|}
if|if
condition|(
name|full_value
operator|&&
name|mask
operator|->
name|bounds_known
operator|&&
name|gegl_rectangle_contains
argument_list|(
operator|&
name|data
operator|->
name|rect
argument_list|,
operator|&
name|data
operator|->
name|bounds
argument_list|)
condition|)
block|{
return|return
name|FALSE
return|;
block|}
name|data
operator|->
name|bounds_known
operator|=
name|FALSE
expr_stmt|;
name|gimp_channel_combine_clear_complement
argument_list|(
name|mask
argument_list|,
operator|&
name|data
operator|->
name|rect
argument_list|)
expr_stmt|;
name|gegl_buffer_set_abyss
argument_list|(
name|buffer
argument_list|,
operator|&
name|data
operator|->
name|rect
argument_list|)
expr_stmt|;
break|break;
block|}
return|return
name|TRUE
return|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_channel_combine_end (GimpChannel * mask,GimpChannelCombineData * data)
name|gimp_channel_combine_end
parameter_list|(
name|GimpChannel
modifier|*
name|mask
parameter_list|,
name|GimpChannelCombineData
modifier|*
name|data
parameter_list|)
block|{
name|GeglBuffer
modifier|*
name|buffer
init|=
name|gimp_drawable_get_buffer
argument_list|(
name|GIMP_DRAWABLE
argument_list|(
name|mask
argument_list|)
argument_list|)
decl_stmt|;
name|gegl_buffer_set_abyss
argument_list|(
name|buffer
argument_list|,
name|gegl_buffer_get_extent
argument_list|(
name|buffer
argument_list|)
argument_list|)
expr_stmt|;
name|gegl_buffer_thaw_changed
argument_list|(
name|buffer
argument_list|)
expr_stmt|;
name|mask
operator|->
name|bounds_known
operator|=
name|data
operator|->
name|bounds_known
expr_stmt|;
if|if
condition|(
name|data
operator|->
name|bounds_known
condition|)
block|{
name|mask
operator|->
name|empty
operator|=
name|data
operator|->
name|empty
expr_stmt|;
if|if
condition|(
name|data
operator|->
name|empty
condition|)
block|{
name|mask
operator|->
name|x1
operator|=
literal|0
expr_stmt|;
name|mask
operator|->
name|y1
operator|=
literal|0
expr_stmt|;
name|mask
operator|->
name|x2
operator|=
name|gimp_item_get_width
argument_list|(
name|GIMP_ITEM
argument_list|(
name|mask
argument_list|)
argument_list|)
expr_stmt|;
name|mask
operator|->
name|y2
operator|=
name|gimp_item_get_height
argument_list|(
name|GIMP_ITEM
argument_list|(
name|mask
argument_list|)
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|mask
operator|->
name|x1
operator|=
name|data
operator|->
name|bounds
operator|.
name|x
expr_stmt|;
name|mask
operator|->
name|y1
operator|=
name|data
operator|->
name|bounds
operator|.
name|y
expr_stmt|;
name|mask
operator|->
name|x2
operator|=
name|data
operator|->
name|bounds
operator|.
name|x
operator|+
name|data
operator|->
name|bounds
operator|.
name|width
expr_stmt|;
name|mask
operator|->
name|y2
operator|=
name|data
operator|->
name|bounds
operator|.
name|y
operator|+
name|data
operator|->
name|bounds
operator|.
name|height
expr_stmt|;
block|}
block|}
name|gimp_drawable_update
argument_list|(
name|GIMP_DRAWABLE
argument_list|(
name|mask
argument_list|)
argument_list|,
name|data
operator|->
name|rect
operator|.
name|x
argument_list|,
name|data
operator|->
name|rect
operator|.
name|y
argument_list|,
name|data
operator|->
name|rect
operator|.
name|width
argument_list|,
name|data
operator|->
name|rect
operator|.
name|height
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/*  public functions  */
end_comment

begin_function
name|void
DECL|function|gimp_channel_combine_rect (GimpChannel * mask,GimpChannelOps op,gint x,gint y,gint w,gint h)
name|gimp_channel_combine_rect
parameter_list|(
name|GimpChannel
modifier|*
name|mask
parameter_list|,
name|GimpChannelOps
name|op
parameter_list|,
name|gint
name|x
parameter_list|,
name|gint
name|y
parameter_list|,
name|gint
name|w
parameter_list|,
name|gint
name|h
parameter_list|)
block|{
name|GimpChannelCombineData
name|data
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_CHANNEL
argument_list|(
name|mask
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|gimp_channel_combine_start
argument_list|(
name|mask
argument_list|,
name|op
argument_list|,
name|GEGL_RECTANGLE
argument_list|(
name|x
argument_list|,
name|y
argument_list|,
name|w
argument_list|,
name|h
argument_list|)
argument_list|,
name|TRUE
argument_list|,
name|TRUE
argument_list|,
operator|&
name|data
argument_list|)
condition|)
block|{
name|GeglBuffer
modifier|*
name|buffer
init|=
name|gimp_drawable_get_buffer
argument_list|(
name|GIMP_DRAWABLE
argument_list|(
name|mask
argument_list|)
argument_list|)
decl_stmt|;
name|gimp_gegl_mask_combine_rect
argument_list|(
name|buffer
argument_list|,
name|op
argument_list|,
name|x
argument_list|,
name|y
argument_list|,
name|w
argument_list|,
name|h
argument_list|)
expr_stmt|;
block|}
name|gimp_channel_combine_end
argument_list|(
name|mask
argument_list|,
operator|&
name|data
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_channel_combine_ellipse (GimpChannel * mask,GimpChannelOps op,gint x,gint y,gint w,gint h,gboolean antialias)
name|gimp_channel_combine_ellipse
parameter_list|(
name|GimpChannel
modifier|*
name|mask
parameter_list|,
name|GimpChannelOps
name|op
parameter_list|,
name|gint
name|x
parameter_list|,
name|gint
name|y
parameter_list|,
name|gint
name|w
parameter_list|,
name|gint
name|h
parameter_list|,
name|gboolean
name|antialias
parameter_list|)
block|{
name|gimp_channel_combine_ellipse_rect
argument_list|(
name|mask
argument_list|,
name|op
argument_list|,
name|x
argument_list|,
name|y
argument_list|,
name|w
argument_list|,
name|h
argument_list|,
name|w
operator|/
literal|2.0
argument_list|,
name|h
operator|/
literal|2.0
argument_list|,
name|antialias
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_channel_combine_ellipse_rect (GimpChannel * mask,GimpChannelOps op,gint x,gint y,gint w,gint h,gdouble rx,gdouble ry,gboolean antialias)
name|gimp_channel_combine_ellipse_rect
parameter_list|(
name|GimpChannel
modifier|*
name|mask
parameter_list|,
name|GimpChannelOps
name|op
parameter_list|,
name|gint
name|x
parameter_list|,
name|gint
name|y
parameter_list|,
name|gint
name|w
parameter_list|,
name|gint
name|h
parameter_list|,
name|gdouble
name|rx
parameter_list|,
name|gdouble
name|ry
parameter_list|,
name|gboolean
name|antialias
parameter_list|)
block|{
name|GimpChannelCombineData
name|data
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_CHANNEL
argument_list|(
name|mask
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|gimp_channel_combine_start
argument_list|(
name|mask
argument_list|,
name|op
argument_list|,
name|GEGL_RECTANGLE
argument_list|(
name|x
argument_list|,
name|y
argument_list|,
name|w
argument_list|,
name|h
argument_list|)
argument_list|,
name|TRUE
argument_list|,
name|FALSE
argument_list|,
operator|&
name|data
argument_list|)
condition|)
block|{
name|GeglBuffer
modifier|*
name|buffer
init|=
name|gimp_drawable_get_buffer
argument_list|(
name|GIMP_DRAWABLE
argument_list|(
name|mask
argument_list|)
argument_list|)
decl_stmt|;
name|gimp_gegl_mask_combine_ellipse_rect
argument_list|(
name|buffer
argument_list|,
name|op
argument_list|,
name|x
argument_list|,
name|y
argument_list|,
name|w
argument_list|,
name|h
argument_list|,
name|rx
argument_list|,
name|ry
argument_list|,
name|antialias
argument_list|)
expr_stmt|;
block|}
name|gimp_channel_combine_end
argument_list|(
name|mask
argument_list|,
operator|&
name|data
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_channel_combine_mask (GimpChannel * mask,GimpChannel * add_on,GimpChannelOps op,gint off_x,gint off_y)
name|gimp_channel_combine_mask
parameter_list|(
name|GimpChannel
modifier|*
name|mask
parameter_list|,
name|GimpChannel
modifier|*
name|add_on
parameter_list|,
name|GimpChannelOps
name|op
parameter_list|,
name|gint
name|off_x
parameter_list|,
name|gint
name|off_y
parameter_list|)
block|{
name|GeglBuffer
modifier|*
name|add_on_buffer
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_CHANNEL
argument_list|(
name|mask
argument_list|)
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_CHANNEL
argument_list|(
name|add_on
argument_list|)
argument_list|)
expr_stmt|;
name|add_on_buffer
operator|=
name|gimp_drawable_get_buffer
argument_list|(
name|GIMP_DRAWABLE
argument_list|(
name|add_on
argument_list|)
argument_list|)
expr_stmt|;
name|gimp_channel_combine_buffer
argument_list|(
name|mask
argument_list|,
name|add_on_buffer
argument_list|,
name|op
argument_list|,
name|off_x
argument_list|,
name|off_y
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_channel_combine_buffer (GimpChannel * mask,GeglBuffer * add_on_buffer,GimpChannelOps op,gint off_x,gint off_y)
name|gimp_channel_combine_buffer
parameter_list|(
name|GimpChannel
modifier|*
name|mask
parameter_list|,
name|GeglBuffer
modifier|*
name|add_on_buffer
parameter_list|,
name|GimpChannelOps
name|op
parameter_list|,
name|gint
name|off_x
parameter_list|,
name|gint
name|off_y
parameter_list|)
block|{
name|GimpChannelCombineData
name|data
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_CHANNEL
argument_list|(
name|mask
argument_list|)
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
name|GEGL_IS_BUFFER
argument_list|(
name|add_on_buffer
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|gimp_channel_combine_start
argument_list|(
name|mask
argument_list|,
name|op
argument_list|,
name|GEGL_RECTANGLE
argument_list|(
name|off_x
argument_list|,
name|off_y
argument_list|,
name|gegl_buffer_get_width
argument_list|(
name|add_on_buffer
argument_list|)
argument_list|,
name|gegl_buffer_get_height
argument_list|(
name|add_on_buffer
argument_list|)
argument_list|)
argument_list|,
name|FALSE
argument_list|,
name|FALSE
argument_list|,
operator|&
name|data
argument_list|)
condition|)
block|{
name|GeglBuffer
modifier|*
name|buffer
init|=
name|gimp_drawable_get_buffer
argument_list|(
name|GIMP_DRAWABLE
argument_list|(
name|mask
argument_list|)
argument_list|)
decl_stmt|;
name|gimp_gegl_mask_combine_buffer
argument_list|(
name|buffer
argument_list|,
name|add_on_buffer
argument_list|,
name|op
argument_list|,
name|off_x
argument_list|,
name|off_y
argument_list|)
expr_stmt|;
block|}
name|gimp_channel_combine_end
argument_list|(
name|mask
argument_list|,
operator|&
name|data
argument_list|)
expr_stmt|;
block|}
end_function

end_unit

