begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* GIMP - The GNU Image Manipulation Program  * Copyright (C) 1995 Spencer Kimball and Peter Mattis  *  * This program is free software: you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 3 of the License, or  * (at your option) any later version.  *  * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *  * You should have received a copy of the GNU General Public License  * along with this program.  If not, see<http://www.gnu.org/licenses/>.  */
end_comment

begin_include
include|#
directive|include
file|"config.h"
end_include

begin_include
include|#
directive|include
file|<gdk-pixbuf/gdk-pixbuf.h>
end_include

begin_include
include|#
directive|include
file|<gegl.h>
end_include

begin_include
include|#
directive|include
file|"libgimpbase/gimpbase.h"
end_include

begin_include
include|#
directive|include
file|"libgimpconfig/gimpconfig.h"
end_include

begin_include
include|#
directive|include
file|"core-types.h"
end_include

begin_include
include|#
directive|include
file|"gimpcontext.h"
end_include

begin_include
include|#
directive|include
file|"gimptoolpreset.h"
end_include

begin_include
include|#
directive|include
file|"gimptoolpreset-load.h"
end_include

begin_include
include|#
directive|include
file|"gimp-intl.h"
end_include

begin_function
name|GList
modifier|*
DECL|function|gimp_tool_preset_load (GimpContext * context,GFile * file,GError ** error)
name|gimp_tool_preset_load
parameter_list|(
name|GimpContext
modifier|*
name|context
parameter_list|,
name|GFile
modifier|*
name|file
parameter_list|,
name|GError
modifier|*
modifier|*
name|error
parameter_list|)
block|{
name|GimpToolPreset
modifier|*
name|tool_preset
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_CONTEXT
argument_list|(
name|context
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
name|G_IS_FILE
argument_list|(
name|file
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
name|error
operator|==
name|NULL
operator|||
operator|*
name|error
operator|==
name|NULL
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|tool_preset
operator|=
name|g_object_new
argument_list|(
name|GIMP_TYPE_TOOL_PRESET
argument_list|,
literal|"gimp"
argument_list|,
name|context
operator|->
name|gimp
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
if|if
condition|(
name|gimp_config_deserialize_gfile
argument_list|(
name|GIMP_CONFIG
argument_list|(
name|tool_preset
argument_list|)
argument_list|,
name|file
argument_list|,
name|NULL
argument_list|,
name|error
argument_list|)
condition|)
block|{
if|if
condition|(
name|GIMP_IS_CONTEXT
argument_list|(
name|tool_preset
operator|->
name|tool_options
argument_list|)
condition|)
block|{
return|return
name|g_list_prepend
argument_list|(
name|NULL
argument_list|,
name|tool_preset
argument_list|)
return|;
block|}
else|else
block|{
name|gchar
modifier|*
name|path
init|=
name|g_file_get_path
argument_list|(
name|file
argument_list|)
decl_stmt|;
name|g_set_error
argument_list|(
name|error
argument_list|,
name|GIMP_CONFIG_ERROR
argument_list|,
name|GIMP_CONFIG_ERROR_PARSE
argument_list|,
name|_
argument_list|(
literal|"Error while parsing '%s'"
argument_list|)
argument_list|,
name|gimp_filename_to_utf8
argument_list|(
name|path
argument_list|)
argument_list|)
expr_stmt|;
name|g_free
argument_list|(
name|path
argument_list|)
expr_stmt|;
block|}
block|}
name|g_object_unref
argument_list|(
name|tool_preset
argument_list|)
expr_stmt|;
return|return
name|NULL
return|;
block|}
end_function

end_unit

