begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* The GIMP -- an image manipulation program  * Copyright (C) 1995-1997 Spencer Kimball and Peter Mattis  *  * This program is free software; you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 2 of the License, or  * (at your option) any later version.  *  * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *  * You should have received a copy of the GNU General Public License  * along with this program; if not, write to the Free Software  * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  */
end_comment

begin_include
include|#
directive|include
file|"config.h"
end_include

begin_include
include|#
directive|include
file|<string.h>
end_include

begin_comment
comment|/* strlen */
end_comment

begin_include
include|#
directive|include
file|<gtk/gtk.h>
end_include

begin_include
include|#
directive|include
file|"libgimpbase/gimpbase.h"
end_include

begin_include
include|#
directive|include
file|"core-types.h"
end_include

begin_include
include|#
directive|include
file|"base/tile-manager.h"
end_include

begin_include
include|#
directive|include
file|"pdb/procedural_db.h"
end_include

begin_include
include|#
directive|include
file|"gimp.h"
end_include

begin_include
include|#
directive|include
file|"gimpbrush.h"
end_include

begin_include
include|#
directive|include
file|"gimpbrushgenerated.h"
end_include

begin_include
include|#
directive|include
file|"gimpbrushpipe.h"
end_include

begin_include
include|#
directive|include
file|"gimpbuffer.h"
end_include

begin_include
include|#
directive|include
file|"gimpcontext.h"
end_include

begin_include
include|#
directive|include
file|"gimpcoreconfig.h"
end_include

begin_include
include|#
directive|include
file|"gimpdatafactory.h"
end_include

begin_include
include|#
directive|include
file|"gimpdocuments.h"
end_include

begin_include
include|#
directive|include
file|"gimpgradient.h"
end_include

begin_include
include|#
directive|include
file|"gimpimage.h"
end_include

begin_include
include|#
directive|include
file|"gimpimage-new.h"
end_include

begin_include
include|#
directive|include
file|"gimpimagefile.h"
end_include

begin_include
include|#
directive|include
file|"gimplist.h"
end_include

begin_include
include|#
directive|include
file|"gimppalette.h"
end_include

begin_include
include|#
directive|include
file|"gimppattern.h"
end_include

begin_include
include|#
directive|include
file|"gimpparasite.h"
end_include

begin_include
include|#
directive|include
file|"gimptoolinfo.h"
end_include

begin_include
include|#
directive|include
file|"gimpunit.h"
end_include

begin_include
include|#
directive|include
file|"app_procs.h"
end_include

begin_include
include|#
directive|include
file|"libgimp/gimpintl.h"
end_include

begin_function_decl
specifier|static
name|void
name|gimp_class_init
parameter_list|(
name|GimpClass
modifier|*
name|klass
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_init
parameter_list|(
name|Gimp
modifier|*
name|gimp
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_dispose
parameter_list|(
name|GObject
modifier|*
name|object
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_finalize
parameter_list|(
name|GObject
modifier|*
name|object
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|gimp_context_disconnect_callback
parameter_list|(
name|GimpContext
modifier|*
name|context
parameter_list|,
name|Gimp
modifier|*
name|gimp
parameter_list|)
function_decl|;
end_function_decl

begin_decl_stmt
DECL|variable|parent_class
specifier|static
name|GimpObjectClass
modifier|*
name|parent_class
init|=
name|NULL
decl_stmt|;
end_decl_stmt

begin_function
name|GType
DECL|function|gimp_get_type (void)
name|gimp_get_type
parameter_list|(
name|void
parameter_list|)
block|{
specifier|static
name|GType
name|object_type
init|=
literal|0
decl_stmt|;
if|if
condition|(
operator|!
name|object_type
condition|)
block|{
specifier|static
specifier|const
name|GTypeInfo
name|object_info
init|=
block|{
sizeof|sizeof
argument_list|(
name|GimpClass
argument_list|)
block|,
operator|(
name|GBaseInitFunc
operator|)
name|NULL
block|,
operator|(
name|GBaseFinalizeFunc
operator|)
name|NULL
block|,
operator|(
name|GClassInitFunc
operator|)
name|gimp_class_init
block|,
name|NULL
block|,
comment|/* class_finalize */
name|NULL
block|,
comment|/* class_data     */
sizeof|sizeof
argument_list|(
name|Gimp
argument_list|)
block|,
literal|0
block|,
comment|/* n_preallocs    */
operator|(
name|GInstanceInitFunc
operator|)
name|gimp_init
block|,       }
decl_stmt|;
name|object_type
operator|=
name|g_type_register_static
argument_list|(
name|GIMP_TYPE_OBJECT
argument_list|,
literal|"Gimp"
argument_list|,
operator|&
name|object_info
argument_list|,
literal|0
argument_list|)
expr_stmt|;
block|}
return|return
name|object_type
return|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_class_init (GimpClass * klass)
name|gimp_class_init
parameter_list|(
name|GimpClass
modifier|*
name|klass
parameter_list|)
block|{
name|GObjectClass
modifier|*
name|object_class
decl_stmt|;
name|object_class
operator|=
name|G_OBJECT_CLASS
argument_list|(
name|klass
argument_list|)
expr_stmt|;
name|parent_class
operator|=
name|g_type_class_peek_parent
argument_list|(
name|klass
argument_list|)
expr_stmt|;
name|object_class
operator|->
name|dispose
operator|=
name|gimp_dispose
expr_stmt|;
name|object_class
operator|->
name|finalize
operator|=
name|gimp_finalize
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_init (Gimp * gimp)
name|gimp_init
parameter_list|(
name|Gimp
modifier|*
name|gimp
parameter_list|)
block|{
name|gimp_core_config_init
argument_list|(
name|gimp
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|create_display_func
operator|=
name|NULL
expr_stmt|;
name|gimp
operator|->
name|gui_set_busy_func
operator|=
name|NULL
expr_stmt|;
name|gimp
operator|->
name|gui_unset_busy_func
operator|=
name|NULL
expr_stmt|;
name|gimp
operator|->
name|busy
operator|=
name|FALSE
expr_stmt|;
name|gimp
operator|->
name|busy_idle_id
operator|=
literal|0
expr_stmt|;
name|gimp_units_init
argument_list|(
name|gimp
argument_list|)
expr_stmt|;
name|gimp_parasites_init
argument_list|(
name|gimp
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|images
operator|=
name|gimp_list_new
argument_list|(
name|GIMP_TYPE_IMAGE
argument_list|,
name|GIMP_CONTAINER_POLICY_WEAK
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|next_image_ID
operator|=
literal|1
expr_stmt|;
name|gimp
operator|->
name|next_guide_ID
operator|=
literal|1
expr_stmt|;
name|gimp
operator|->
name|image_table
operator|=
name|g_hash_table_new
argument_list|(
name|g_direct_hash
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|next_drawable_ID
operator|=
literal|1
expr_stmt|;
name|gimp
operator|->
name|drawable_table
operator|=
name|g_hash_table_new
argument_list|(
name|g_direct_hash
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|global_buffer
operator|=
name|NULL
expr_stmt|;
name|gimp
operator|->
name|named_buffers
operator|=
name|gimp_list_new
argument_list|(
name|GIMP_TYPE_BUFFER
argument_list|,
name|GIMP_CONTAINER_POLICY_STRONG
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|brush_factory
operator|=
name|NULL
expr_stmt|;
name|gimp
operator|->
name|pattern_factory
operator|=
name|NULL
expr_stmt|;
name|gimp
operator|->
name|gradient_factory
operator|=
name|NULL
expr_stmt|;
name|gimp
operator|->
name|palette_factory
operator|=
name|NULL
expr_stmt|;
name|procedural_db_init
argument_list|(
name|gimp
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|tool_info_list
operator|=
name|gimp_list_new
argument_list|(
name|GIMP_TYPE_TOOL_INFO
argument_list|,
name|GIMP_CONTAINER_POLICY_STRONG
argument_list|)
expr_stmt|;
name|gimp_documents_init
argument_list|(
name|gimp
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|image_base_type_names
operator|=
name|NULL
expr_stmt|;
name|gimp
operator|->
name|fill_type_names
operator|=
name|NULL
expr_stmt|;
name|gimp
operator|->
name|have_current_cut_buffer
operator|=
name|FALSE
expr_stmt|;
name|gimp
operator|->
name|context_list
operator|=
name|NULL
expr_stmt|;
name|gimp
operator|->
name|standard_context
operator|=
name|NULL
expr_stmt|;
name|gimp
operator|->
name|default_context
operator|=
name|NULL
expr_stmt|;
name|gimp
operator|->
name|user_context
operator|=
name|NULL
expr_stmt|;
name|gimp
operator|->
name|current_context
operator|=
name|NULL
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_dispose (GObject * object)
name|gimp_dispose
parameter_list|(
name|GObject
modifier|*
name|object
parameter_list|)
block|{
name|Gimp
modifier|*
name|gimp
decl_stmt|;
name|gimp
operator|=
name|GIMP
argument_list|(
name|object
argument_list|)
expr_stmt|;
if|if
condition|(
name|gimp
operator|->
name|brush_factory
condition|)
name|gimp_data_factory_data_free
argument_list|(
name|gimp
operator|->
name|brush_factory
argument_list|)
expr_stmt|;
if|if
condition|(
name|gimp
operator|->
name|pattern_factory
condition|)
name|gimp_data_factory_data_free
argument_list|(
name|gimp
operator|->
name|pattern_factory
argument_list|)
expr_stmt|;
if|if
condition|(
name|gimp
operator|->
name|gradient_factory
condition|)
name|gimp_data_factory_data_free
argument_list|(
name|gimp
operator|->
name|gradient_factory
argument_list|)
expr_stmt|;
if|if
condition|(
name|gimp
operator|->
name|palette_factory
condition|)
name|gimp_data_factory_data_free
argument_list|(
name|gimp
operator|->
name|palette_factory
argument_list|)
expr_stmt|;
name|G_OBJECT_CLASS
argument_list|(
name|parent_class
argument_list|)
operator|->
name|dispose
argument_list|(
name|object
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_finalize (GObject * object)
name|gimp_finalize
parameter_list|(
name|GObject
modifier|*
name|object
parameter_list|)
block|{
name|Gimp
modifier|*
name|gimp
decl_stmt|;
name|gimp
operator|=
name|GIMP
argument_list|(
name|object
argument_list|)
expr_stmt|;
if|if
condition|(
name|gimp
operator|->
name|current_context
condition|)
name|gimp_set_current_context
argument_list|(
name|gimp
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
if|if
condition|(
name|gimp
operator|->
name|user_context
condition|)
name|gimp_set_user_context
argument_list|(
name|gimp
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
if|if
condition|(
name|gimp
operator|->
name|default_context
condition|)
name|gimp_set_default_context
argument_list|(
name|gimp
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
if|if
condition|(
name|gimp
operator|->
name|standard_context
condition|)
block|{
name|g_object_unref
argument_list|(
name|G_OBJECT
argument_list|(
name|gimp
operator|->
name|standard_context
argument_list|)
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|standard_context
operator|=
name|NULL
expr_stmt|;
block|}
if|if
condition|(
name|gimp
operator|->
name|image_base_type_names
condition|)
name|gimp_image_new_exit
argument_list|(
name|gimp
argument_list|)
expr_stmt|;
if|if
condition|(
name|gimp
operator|->
name|documents
condition|)
name|gimp_documents_exit
argument_list|(
name|gimp
argument_list|)
expr_stmt|;
if|if
condition|(
name|gimp
operator|->
name|tool_info_list
condition|)
block|{
name|g_object_unref
argument_list|(
name|G_OBJECT
argument_list|(
name|gimp
operator|->
name|tool_info_list
argument_list|)
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|tool_info_list
operator|=
name|NULL
expr_stmt|;
block|}
if|if
condition|(
name|gimp
operator|->
name|procedural_ht
condition|)
name|procedural_db_free
argument_list|(
name|gimp
argument_list|)
expr_stmt|;
if|if
condition|(
name|gimp
operator|->
name|brush_factory
condition|)
block|{
name|g_object_unref
argument_list|(
name|G_OBJECT
argument_list|(
name|gimp
operator|->
name|brush_factory
argument_list|)
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|brush_factory
operator|=
name|NULL
expr_stmt|;
block|}
if|if
condition|(
name|gimp
operator|->
name|pattern_factory
condition|)
block|{
name|g_object_unref
argument_list|(
name|G_OBJECT
argument_list|(
name|gimp
operator|->
name|pattern_factory
argument_list|)
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|pattern_factory
operator|=
name|NULL
expr_stmt|;
block|}
if|if
condition|(
name|gimp
operator|->
name|gradient_factory
condition|)
block|{
name|g_object_unref
argument_list|(
name|G_OBJECT
argument_list|(
name|gimp
operator|->
name|gradient_factory
argument_list|)
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|gradient_factory
operator|=
name|NULL
expr_stmt|;
block|}
if|if
condition|(
name|gimp
operator|->
name|palette_factory
condition|)
block|{
name|g_object_unref
argument_list|(
name|G_OBJECT
argument_list|(
name|gimp
operator|->
name|palette_factory
argument_list|)
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|palette_factory
operator|=
name|NULL
expr_stmt|;
block|}
if|if
condition|(
name|gimp
operator|->
name|named_buffers
condition|)
block|{
name|g_object_unref
argument_list|(
name|G_OBJECT
argument_list|(
name|gimp
operator|->
name|named_buffers
argument_list|)
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|named_buffers
operator|=
name|NULL
expr_stmt|;
block|}
if|if
condition|(
name|gimp
operator|->
name|global_buffer
condition|)
block|{
name|tile_manager_destroy
argument_list|(
name|gimp
operator|->
name|global_buffer
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|global_buffer
operator|=
name|NULL
expr_stmt|;
block|}
if|if
condition|(
name|gimp
operator|->
name|drawable_table
condition|)
block|{
name|g_hash_table_destroy
argument_list|(
name|gimp
operator|->
name|drawable_table
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|drawable_table
operator|=
name|NULL
expr_stmt|;
block|}
if|if
condition|(
name|gimp
operator|->
name|image_table
condition|)
block|{
name|g_hash_table_destroy
argument_list|(
name|gimp
operator|->
name|image_table
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|image_table
operator|=
name|NULL
expr_stmt|;
block|}
if|if
condition|(
name|gimp
operator|->
name|images
condition|)
block|{
name|g_object_unref
argument_list|(
name|G_OBJECT
argument_list|(
name|gimp
operator|->
name|images
argument_list|)
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|images
operator|=
name|NULL
expr_stmt|;
block|}
if|if
condition|(
name|gimp
operator|->
name|parasites
condition|)
name|gimp_parasites_exit
argument_list|(
name|gimp
argument_list|)
expr_stmt|;
if|if
condition|(
name|gimp
operator|->
name|user_units
condition|)
name|gimp_units_exit
argument_list|(
name|gimp
argument_list|)
expr_stmt|;
name|G_OBJECT_CLASS
argument_list|(
name|parent_class
argument_list|)
operator|->
name|finalize
argument_list|(
name|object
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|Gimp
modifier|*
DECL|function|gimp_new (void)
name|gimp_new
parameter_list|(
name|void
parameter_list|)
block|{
name|Gimp
modifier|*
name|gimp
decl_stmt|;
comment|/* EEK */
name|g_type_class_ref
argument_list|(
name|GIMP_TYPE_CONTEXT
argument_list|)
expr_stmt|;
name|g_type_class_ref
argument_list|(
name|GIMP_TYPE_CONTAINER
argument_list|)
expr_stmt|;
name|g_type_class_ref
argument_list|(
name|GIMP_TYPE_IMAGE
argument_list|)
expr_stmt|;
name|g_type_class_ref
argument_list|(
name|GIMP_TYPE_IMAGEFILE
argument_list|)
expr_stmt|;
name|gimp
operator|=
name|g_object_new
argument_list|(
name|GIMP_TYPE_GIMP
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
return|return
name|gimp
return|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_initialize (Gimp * gimp)
name|gimp_initialize
parameter_list|(
name|Gimp
modifier|*
name|gimp
parameter_list|)
block|{
name|GimpContext
modifier|*
name|context
decl_stmt|;
specifier|static
specifier|const
name|GimpDataFactoryLoaderEntry
name|brush_loader_entries
index|[]
init|=
block|{
block|{
name|gimp_brush_load
block|,
name|GIMP_BRUSH_FILE_EXTENSION
block|}
block|,
block|{
name|gimp_brush_load
block|,
name|GIMP_BRUSH_PIXMAP_FILE_EXTENSION
block|}
block|,
block|{
name|gimp_brush_generated_load
block|,
name|GIMP_BRUSH_GENERATED_FILE_EXTENSION
block|}
block|,
block|{
name|gimp_brush_pipe_load
block|,
name|GIMP_BRUSH_PIPE_FILE_EXTENSION
block|}
block|}
decl_stmt|;
specifier|static
name|gint
name|n_brush_loader_entries
init|=
operator|(
sizeof|sizeof
argument_list|(
name|brush_loader_entries
argument_list|)
operator|/
sizeof|sizeof
argument_list|(
name|brush_loader_entries
index|[
literal|0
index|]
argument_list|)
operator|)
decl_stmt|;
specifier|static
specifier|const
name|GimpDataFactoryLoaderEntry
name|pattern_loader_entries
index|[]
init|=
block|{
block|{
name|gimp_pattern_load
block|,
name|GIMP_PATTERN_FILE_EXTENSION
block|}
block|}
decl_stmt|;
specifier|static
name|gint
name|n_pattern_loader_entries
init|=
operator|(
sizeof|sizeof
argument_list|(
name|pattern_loader_entries
argument_list|)
operator|/
sizeof|sizeof
argument_list|(
name|pattern_loader_entries
index|[
literal|0
index|]
argument_list|)
operator|)
decl_stmt|;
specifier|static
specifier|const
name|GimpDataFactoryLoaderEntry
name|gradient_loader_entries
index|[]
init|=
block|{
block|{
name|gimp_gradient_load
block|,
name|GIMP_GRADIENT_FILE_EXTENSION
block|}
block|,
block|{
name|gimp_gradient_load
block|,
name|NULL
comment|/* legacy loader */
block|}
block|}
decl_stmt|;
specifier|static
name|gint
name|n_gradient_loader_entries
init|=
operator|(
sizeof|sizeof
argument_list|(
name|gradient_loader_entries
argument_list|)
operator|/
sizeof|sizeof
argument_list|(
name|gradient_loader_entries
index|[
literal|0
index|]
argument_list|)
operator|)
decl_stmt|;
specifier|static
specifier|const
name|GimpDataFactoryLoaderEntry
name|palette_loader_entries
index|[]
init|=
block|{
block|{
name|gimp_palette_load
block|,
name|GIMP_PALETTE_FILE_EXTENSION
block|}
block|,
block|{
name|gimp_palette_load
block|,
name|NULL
comment|/* legacy loader */
block|}
block|}
decl_stmt|;
specifier|static
name|gint
name|n_palette_loader_entries
init|=
operator|(
sizeof|sizeof
argument_list|(
name|palette_loader_entries
argument_list|)
operator|/
sizeof|sizeof
argument_list|(
name|palette_loader_entries
index|[
literal|0
index|]
argument_list|)
operator|)
decl_stmt|;
name|g_return_if_fail
argument_list|(
name|GIMP_IS_GIMP
argument_list|(
name|gimp
argument_list|)
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|brush_factory
operator|=
name|gimp_data_factory_new
argument_list|(
name|GIMP_TYPE_BRUSH
argument_list|,
operator|(
specifier|const
name|gchar
operator|*
operator|*
operator|)
operator|&
name|gimp
operator|->
name|config
operator|->
name|brush_path
argument_list|,
name|brush_loader_entries
argument_list|,
name|n_brush_loader_entries
argument_list|,
name|gimp_brush_new
argument_list|,
name|gimp_brush_get_standard
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|pattern_factory
operator|=
name|gimp_data_factory_new
argument_list|(
name|GIMP_TYPE_PATTERN
argument_list|,
operator|(
specifier|const
name|gchar
operator|*
operator|*
operator|)
operator|&
name|gimp
operator|->
name|config
operator|->
name|pattern_path
argument_list|,
name|pattern_loader_entries
argument_list|,
name|n_pattern_loader_entries
argument_list|,
name|gimp_pattern_new
argument_list|,
name|gimp_pattern_get_standard
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|gradient_factory
operator|=
name|gimp_data_factory_new
argument_list|(
name|GIMP_TYPE_GRADIENT
argument_list|,
operator|(
specifier|const
name|gchar
operator|*
operator|*
operator|)
operator|&
name|gimp
operator|->
name|config
operator|->
name|gradient_path
argument_list|,
name|gradient_loader_entries
argument_list|,
name|n_gradient_loader_entries
argument_list|,
name|gimp_gradient_new
argument_list|,
name|gimp_gradient_get_standard
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|palette_factory
operator|=
name|gimp_data_factory_new
argument_list|(
name|GIMP_TYPE_PALETTE
argument_list|,
operator|(
specifier|const
name|gchar
operator|*
operator|*
operator|)
operator|&
name|gimp
operator|->
name|config
operator|->
name|palette_path
argument_list|,
name|palette_loader_entries
argument_list|,
name|n_palette_loader_entries
argument_list|,
name|gimp_palette_new
argument_list|,
name|gimp_palette_get_standard
argument_list|)
expr_stmt|;
name|gimp_image_new_init
argument_list|(
name|gimp
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|standard_context
operator|=
name|gimp_create_context
argument_list|(
name|gimp
argument_list|,
literal|"Standard"
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
comment|/*  the default context contains the user's saved preferences    *    *  TODO: load from disk    */
name|context
operator|=
name|gimp_create_context
argument_list|(
name|gimp
argument_list|,
literal|"Default"
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|gimp_set_default_context
argument_list|(
name|gimp
argument_list|,
name|context
argument_list|)
expr_stmt|;
name|g_object_unref
argument_list|(
name|G_OBJECT
argument_list|(
name|context
argument_list|)
argument_list|)
expr_stmt|;
comment|/*  the initial user_context is a straight copy of the default context    */
name|context
operator|=
name|gimp_create_context
argument_list|(
name|gimp
argument_list|,
literal|"User"
argument_list|,
name|context
argument_list|)
expr_stmt|;
name|gimp_set_user_context
argument_list|(
name|gimp
argument_list|,
name|context
argument_list|)
expr_stmt|;
name|gimp_set_current_context
argument_list|(
name|gimp
argument_list|,
name|context
argument_list|)
expr_stmt|;
name|g_object_unref
argument_list|(
name|G_OBJECT
argument_list|(
name|context
argument_list|)
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_restore (Gimp * gimp,gboolean no_data)
name|gimp_restore
parameter_list|(
name|Gimp
modifier|*
name|gimp
parameter_list|,
name|gboolean
name|no_data
parameter_list|)
block|{
name|g_return_if_fail
argument_list|(
name|GIMP_IS_GIMP
argument_list|(
name|gimp
argument_list|)
argument_list|)
expr_stmt|;
comment|/*  initialize  the global parasite table  */
name|app_init_update_status
argument_list|(
name|_
argument_list|(
literal|"Looking for data files"
argument_list|)
argument_list|,
name|_
argument_list|(
literal|"Parasites"
argument_list|)
argument_list|,
literal|0.00
argument_list|)
expr_stmt|;
name|gimp_parasiterc_load
argument_list|(
name|gimp
argument_list|)
expr_stmt|;
comment|/*  initialize the list of gimp brushes    */
name|app_init_update_status
argument_list|(
name|NULL
argument_list|,
name|_
argument_list|(
literal|"Brushes"
argument_list|)
argument_list|,
literal|0.18
argument_list|)
expr_stmt|;
name|gimp_data_factory_data_init
argument_list|(
name|gimp
operator|->
name|brush_factory
argument_list|,
name|no_data
argument_list|)
expr_stmt|;
comment|/*  initialize the list of gimp patterns   */
name|app_init_update_status
argument_list|(
name|NULL
argument_list|,
name|_
argument_list|(
literal|"Patterns"
argument_list|)
argument_list|,
literal|0.36
argument_list|)
expr_stmt|;
name|gimp_data_factory_data_init
argument_list|(
name|gimp
operator|->
name|pattern_factory
argument_list|,
name|no_data
argument_list|)
expr_stmt|;
comment|/*  initialize the list of gimp palettes   */
name|app_init_update_status
argument_list|(
name|NULL
argument_list|,
name|_
argument_list|(
literal|"Palettes"
argument_list|)
argument_list|,
literal|0.54
argument_list|)
expr_stmt|;
name|gimp_data_factory_data_init
argument_list|(
name|gimp
operator|->
name|palette_factory
argument_list|,
name|no_data
argument_list|)
expr_stmt|;
comment|/*  initialize the list of gimp gradients  */
name|app_init_update_status
argument_list|(
name|NULL
argument_list|,
name|_
argument_list|(
literal|"Gradients"
argument_list|)
argument_list|,
literal|0.72
argument_list|)
expr_stmt|;
name|gimp_data_factory_data_init
argument_list|(
name|gimp
operator|->
name|gradient_factory
argument_list|,
name|no_data
argument_list|)
expr_stmt|;
comment|/*  initialize  the global parasite table  */
name|app_init_update_status
argument_list|(
name|NULL
argument_list|,
name|_
argument_list|(
literal|"Documents"
argument_list|)
argument_list|,
literal|0.90
argument_list|)
expr_stmt|;
name|gimp_documents_load
argument_list|(
name|gimp
argument_list|)
expr_stmt|;
name|app_init_update_status
argument_list|(
name|NULL
argument_list|,
name|NULL
argument_list|,
literal|1.00
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_shutdown (Gimp * gimp)
name|gimp_shutdown
parameter_list|(
name|Gimp
modifier|*
name|gimp
parameter_list|)
block|{
name|g_return_if_fail
argument_list|(
name|GIMP_IS_GIMP
argument_list|(
name|gimp
argument_list|)
argument_list|)
expr_stmt|;
name|gimp_data_factory_data_save
argument_list|(
name|gimp
operator|->
name|brush_factory
argument_list|)
expr_stmt|;
name|gimp_data_factory_data_save
argument_list|(
name|gimp
operator|->
name|pattern_factory
argument_list|)
expr_stmt|;
name|gimp_data_factory_data_save
argument_list|(
name|gimp
operator|->
name|gradient_factory
argument_list|)
expr_stmt|;
name|gimp_data_factory_data_save
argument_list|(
name|gimp
operator|->
name|palette_factory
argument_list|)
expr_stmt|;
name|gimp_documents_save
argument_list|(
name|gimp
argument_list|)
expr_stmt|;
name|gimp_parasiterc_save
argument_list|(
name|gimp
argument_list|)
expr_stmt|;
name|gimp_unitrc_save
argument_list|(
name|gimp
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_set_busy (Gimp * gimp)
name|gimp_set_busy
parameter_list|(
name|Gimp
modifier|*
name|gimp
parameter_list|)
block|{
name|g_return_if_fail
argument_list|(
name|GIMP_IS_GIMP
argument_list|(
name|gimp
argument_list|)
argument_list|)
expr_stmt|;
comment|/* FIXME: gimp_busy HACK */
name|gimp
operator|->
name|busy
operator|=
name|TRUE
expr_stmt|;
if|if
condition|(
name|gimp
operator|->
name|gui_set_busy_func
condition|)
name|gimp
operator|->
name|gui_set_busy_func
argument_list|(
name|gimp
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|gboolean
DECL|function|gimp_idle_unset_busy (gpointer data)
name|gimp_idle_unset_busy
parameter_list|(
name|gpointer
name|data
parameter_list|)
block|{
name|Gimp
modifier|*
name|gimp
decl_stmt|;
name|gimp
operator|=
operator|(
name|Gimp
operator|*
operator|)
name|data
expr_stmt|;
name|gimp_unset_busy
argument_list|(
name|gimp
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|busy_idle_id
operator|=
literal|0
expr_stmt|;
return|return
name|FALSE
return|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_set_busy_until_idle (Gimp * gimp)
name|gimp_set_busy_until_idle
parameter_list|(
name|Gimp
modifier|*
name|gimp
parameter_list|)
block|{
name|g_return_if_fail
argument_list|(
name|GIMP_IS_GIMP
argument_list|(
name|gimp
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|gimp
operator|->
name|busy_idle_id
condition|)
block|{
name|gimp_set_busy
argument_list|(
name|gimp
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|busy_idle_id
operator|=
name|g_idle_add_full
argument_list|(
name|G_PRIORITY_HIGH
argument_list|,
name|gimp_idle_unset_busy
argument_list|,
name|gimp
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
name|void
DECL|function|gimp_unset_busy (Gimp * gimp)
name|gimp_unset_busy
parameter_list|(
name|Gimp
modifier|*
name|gimp
parameter_list|)
block|{
name|g_return_if_fail
argument_list|(
name|GIMP_IS_GIMP
argument_list|(
name|gimp
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|gimp
operator|->
name|gui_unset_busy_func
condition|)
name|gimp
operator|->
name|gui_unset_busy_func
argument_list|(
name|gimp
argument_list|)
expr_stmt|;
comment|/* FIXME: gimp_busy HACK */
name|gimp
operator|->
name|busy
operator|=
name|FALSE
expr_stmt|;
block|}
end_function

begin_function
name|GimpImage
modifier|*
DECL|function|gimp_create_image (Gimp * gimp,gint width,gint height,GimpImageBaseType type,gboolean attach_comment)
name|gimp_create_image
parameter_list|(
name|Gimp
modifier|*
name|gimp
parameter_list|,
name|gint
name|width
parameter_list|,
name|gint
name|height
parameter_list|,
name|GimpImageBaseType
name|type
parameter_list|,
name|gboolean
name|attach_comment
parameter_list|)
block|{
name|GimpImage
modifier|*
name|gimage
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_GIMP
argument_list|(
name|gimp
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|gimage
operator|=
name|gimp_image_new
argument_list|(
name|gimp
argument_list|,
name|width
argument_list|,
name|height
argument_list|,
name|type
argument_list|)
expr_stmt|;
name|gimp_container_add
argument_list|(
name|gimp
operator|->
name|images
argument_list|,
name|GIMP_OBJECT
argument_list|(
name|gimage
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|attach_comment
operator|&&
name|gimp
operator|->
name|config
operator|->
name|default_comment
condition|)
block|{
name|GimpParasite
modifier|*
name|parasite
decl_stmt|;
name|parasite
operator|=
name|gimp_parasite_new
argument_list|(
literal|"gimp-comment"
argument_list|,
name|GIMP_PARASITE_PERSISTENT
argument_list|,
name|strlen
argument_list|(
name|gimp
operator|->
name|config
operator|->
name|default_comment
argument_list|)
operator|+
literal|1
argument_list|,
name|gimp
operator|->
name|config
operator|->
name|default_comment
argument_list|)
expr_stmt|;
name|gimp_image_parasite_attach
argument_list|(
name|gimage
argument_list|,
name|parasite
argument_list|)
expr_stmt|;
name|gimp_parasite_free
argument_list|(
name|parasite
argument_list|)
expr_stmt|;
block|}
return|return
name|gimage
return|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_create_display (Gimp * gimp,GimpImage * gimage)
name|gimp_create_display
parameter_list|(
name|Gimp
modifier|*
name|gimp
parameter_list|,
name|GimpImage
modifier|*
name|gimage
parameter_list|)
block|{
name|g_return_if_fail
argument_list|(
name|GIMP_IS_GIMP
argument_list|(
name|gimp
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|gimp
operator|->
name|create_display_func
condition|)
name|gimp
operator|->
name|create_display_func
argument_list|(
name|gimage
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/* void gimp_open_file (Gimp        *gimp, 		const gchar *filename, 		gboolean     with_display) {   GimpImage *gimage;   gint       status;    g_return_if_fail (GIMP_IS_GIMP (gimp));   g_return_if_fail (filename != NULL);    gimage = file_open_image (gimp, 			    filename, 			    filename, 			    _("Open"), 			    NULL, 			    RUN_INTERACTIVE,&status);    if (gimage)     {       gchar *absolute;        * enable& clear all undo steps *       gimp_image_undo_enable (gimage);        * set the image to clean  *       gimp_image_clean_all (gimage);        if (with_display) 	gimp_create_display (gimage->gimp, gimage);        absolute = file_open_absolute_filename (filename);        document_index_add (absolute);       menus_last_opened_add (absolute);        g_free (absolute);     } } */
end_comment

begin_function
name|GimpContext
modifier|*
DECL|function|gimp_create_context (Gimp * gimp,const gchar * name,GimpContext * template)
name|gimp_create_context
parameter_list|(
name|Gimp
modifier|*
name|gimp
parameter_list|,
specifier|const
name|gchar
modifier|*
name|name
parameter_list|,
name|GimpContext
modifier|*
name|template
parameter_list|)
block|{
name|GimpContext
modifier|*
name|context
decl_stmt|;
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_GIMP
argument_list|(
name|gimp
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|g_return_val_if_fail
argument_list|(
operator|!
name|template
operator|||
name|GIMP_IS_CONTEXT
argument_list|(
name|template
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
comment|/*  FIXME: need unique names here  */
if|if
condition|(
operator|!
name|name
condition|)
name|name
operator|=
literal|"Unnamed"
expr_stmt|;
name|context
operator|=
name|gimp_context_new
argument_list|(
name|gimp
argument_list|,
name|name
argument_list|,
name|template
argument_list|)
expr_stmt|;
name|gimp
operator|->
name|context_list
operator|=
name|g_list_prepend
argument_list|(
name|gimp
operator|->
name|context_list
argument_list|,
name|context
argument_list|)
expr_stmt|;
name|g_signal_connect_object
argument_list|(
name|G_OBJECT
argument_list|(
name|context
argument_list|)
argument_list|,
literal|"disconnect"
argument_list|,
name|G_CALLBACK
argument_list|(
name|gimp_context_disconnect_callback
argument_list|)
argument_list|,
name|G_OBJECT
argument_list|(
name|gimp
argument_list|)
argument_list|,
literal|0
argument_list|)
expr_stmt|;
return|return
name|context
return|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|gimp_context_disconnect_callback (GimpContext * context,Gimp * gimp)
name|gimp_context_disconnect_callback
parameter_list|(
name|GimpContext
modifier|*
name|context
parameter_list|,
name|Gimp
modifier|*
name|gimp
parameter_list|)
block|{
name|gimp
operator|->
name|context_list
operator|=
name|g_list_remove
argument_list|(
name|gimp
operator|->
name|context_list
argument_list|,
name|context
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|GimpContext
modifier|*
DECL|function|gimp_get_standard_context (Gimp * gimp)
name|gimp_get_standard_context
parameter_list|(
name|Gimp
modifier|*
name|gimp
parameter_list|)
block|{
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_GIMP
argument_list|(
name|gimp
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
return|return
name|gimp
operator|->
name|standard_context
return|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_set_default_context (Gimp * gimp,GimpContext * context)
name|gimp_set_default_context
parameter_list|(
name|Gimp
modifier|*
name|gimp
parameter_list|,
name|GimpContext
modifier|*
name|context
parameter_list|)
block|{
name|g_return_if_fail
argument_list|(
name|GIMP_IS_GIMP
argument_list|(
name|gimp
argument_list|)
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
operator|!
name|context
operator|||
name|GIMP_IS_CONTEXT
argument_list|(
name|context
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|gimp
operator|->
name|default_context
condition|)
block|{
name|g_object_unref
argument_list|(
name|G_OBJECT
argument_list|(
name|gimp
operator|->
name|default_context
argument_list|)
argument_list|)
expr_stmt|;
block|}
name|gimp
operator|->
name|default_context
operator|=
name|context
expr_stmt|;
if|if
condition|(
name|gimp
operator|->
name|default_context
condition|)
block|{
name|g_object_ref
argument_list|(
name|G_OBJECT
argument_list|(
name|gimp
operator|->
name|default_context
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
name|GimpContext
modifier|*
DECL|function|gimp_get_default_context (Gimp * gimp)
name|gimp_get_default_context
parameter_list|(
name|Gimp
modifier|*
name|gimp
parameter_list|)
block|{
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_GIMP
argument_list|(
name|gimp
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
return|return
name|gimp
operator|->
name|default_context
return|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_set_user_context (Gimp * gimp,GimpContext * context)
name|gimp_set_user_context
parameter_list|(
name|Gimp
modifier|*
name|gimp
parameter_list|,
name|GimpContext
modifier|*
name|context
parameter_list|)
block|{
name|g_return_if_fail
argument_list|(
name|GIMP_IS_GIMP
argument_list|(
name|gimp
argument_list|)
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
operator|!
name|context
operator|||
name|GIMP_IS_CONTEXT
argument_list|(
name|context
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|gimp
operator|->
name|user_context
condition|)
block|{
name|g_object_unref
argument_list|(
name|G_OBJECT
argument_list|(
name|gimp
operator|->
name|user_context
argument_list|)
argument_list|)
expr_stmt|;
block|}
name|gimp
operator|->
name|user_context
operator|=
name|context
expr_stmt|;
if|if
condition|(
name|gimp
operator|->
name|user_context
condition|)
block|{
name|g_object_ref
argument_list|(
name|G_OBJECT
argument_list|(
name|gimp
operator|->
name|user_context
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
name|GimpContext
modifier|*
DECL|function|gimp_get_user_context (Gimp * gimp)
name|gimp_get_user_context
parameter_list|(
name|Gimp
modifier|*
name|gimp
parameter_list|)
block|{
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_GIMP
argument_list|(
name|gimp
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
return|return
name|gimp
operator|->
name|user_context
return|;
block|}
end_function

begin_function
name|void
DECL|function|gimp_set_current_context (Gimp * gimp,GimpContext * context)
name|gimp_set_current_context
parameter_list|(
name|Gimp
modifier|*
name|gimp
parameter_list|,
name|GimpContext
modifier|*
name|context
parameter_list|)
block|{
name|g_return_if_fail
argument_list|(
name|GIMP_IS_GIMP
argument_list|(
name|gimp
argument_list|)
argument_list|)
expr_stmt|;
name|g_return_if_fail
argument_list|(
operator|!
name|context
operator|||
name|GIMP_IS_CONTEXT
argument_list|(
name|context
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|gimp
operator|->
name|current_context
condition|)
block|{
name|g_object_unref
argument_list|(
name|G_OBJECT
argument_list|(
name|gimp
operator|->
name|current_context
argument_list|)
argument_list|)
expr_stmt|;
block|}
name|gimp
operator|->
name|current_context
operator|=
name|context
expr_stmt|;
if|if
condition|(
name|gimp
operator|->
name|current_context
condition|)
block|{
name|g_object_ref
argument_list|(
name|G_OBJECT
argument_list|(
name|gimp
operator|->
name|current_context
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_function
name|GimpContext
modifier|*
DECL|function|gimp_get_current_context (Gimp * gimp)
name|gimp_get_current_context
parameter_list|(
name|Gimp
modifier|*
name|gimp
parameter_list|)
block|{
name|g_return_val_if_fail
argument_list|(
name|GIMP_IS_GIMP
argument_list|(
name|gimp
argument_list|)
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
return|return
name|gimp
operator|->
name|current_context
return|;
block|}
end_function

end_unit

